.ycm_extra_conf.py

Source: http://jesrui.sdf-eu.org/ycm-config-for-qt5.html

Vim YouCompleteMe config

---

src/VehicleSetup/SetupView.cc

Fix crash when no UAS

---

README.md

Fix the formatting at "Initialize submodules".

fix style in README

---

src/comm/SerialLink.cc
src/comm/SerialLink.h
src/ui/SerialConfigurationWindow.cc
src/ui/SerialConfigurationWindow.h

There's also a partial fix for the databits and stopbits. I'm unsure how to deal with the logic
around the 'is_cdc' variable, as I can't really follow what it's for.
Closes #1212

Fix setting the baud rate.

---

src/VehicleSetup/SetupViewButtons.qml

This is the first simpler try on the black setup button view problem.

Set Column component size correctly

---

src/VehicleSetup/SetupView.cc
src/VehicleSetup/SetupView.h
src/VehicleSetup/SetupViewButtons.qml

Updating style for mixing qml and C++ for UI into more of an MVC model.

Change SetupView to MVC model

---

src/ui/XbeeConfigurationWindow.h
src/ui/map/MAV2DIcon.h
src/ui/map/QGCMapWidget.h
src/ui/map3D/Pixhawk3DWidget.cc

Remove '../' from includes

---

CodingStyle.cc
CodingStyle.h

These are example header and code files for QGroundControl coding style. They basically match the style that I've been using for the last year for all the new code I've been writing. They are not meant to be comprehensive, just cover the high level stuff. Don't really want to enforce a really detailed coding style.
Comments on whether something important is missing.

Coding style examples

---

CodingStyle.h

Changed to what is the prevalent style in the codebase.

Use more normal double include ifdef

---

src/VehicleSetup/SetupView.cc
src/VehicleSetup/SetupView.ui
src/ui/px4_configuration/PX4RCCalibration.ui
src/ui/px4_configuration/QGCPX4AirframeConfig.ui

Resize setup view to fill space available

---

QGCInstaller.pri
QGCSetup.pri
README.md
qgroundcontrol.pro
src/QGCQmlWidgetHolder.cpp
src/QGCQmlWidgetHolder.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/SetupViewButtons.qml
src/ui/map/QGCMapToolBar.cc
src/ui/map/QGCMapToolBar.h

Replacement for Pull #1249.
Waiting to hear back from Lorenz on one last sanity check. I'll let the Google Group email notice sit for today. Then if Lorenz comes back positive and no technical issues from Google Group still start the cutover tomorrow.

Qt 5.4 Upgrade

---

src/QGCQmlWidgetHolder.cpp
src/QGCQmlWidgetHolder.h
src/QGCQuickWidget.cc
src/QGCQuickWidget.h
src/QmlControls/QmlTest.qml

You can now switch themes from the Qml palette/control test dialog. Also fixed the placement of some qml source loading error checking code.

Qml Test dialog theme selection support

---

qgroundcontrol.qrc
src/QmlControls/QGCComboBox.qml
src/QmlControls/QmlTest.qml
src/QmlControls/qmldir

Currently just overrides the normal Qml ComboBox. NYI: Visuals to match ui design, QGCPalette support. That will come later. Putting in now so that it can be referenced in new Qml code.

QGCComboBox initial implementation

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

I closes this without merging! Trying again.

Firmware progress

---

src/ui/QGCWaypointListMulti.cc
src/ui/QGCWaypointListMulti.h
src/ui/uas/UASView.cc

Fix object de-reference crash on deletion

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml

Handle sensor difference for Fixed Wing

---

src/VehicleSetup/VehicleSummary.qml

No longer buttons so switch to Rectangle for cleaner Qml

Cleanup Vehicle Summary Qml

---

QGCSetup.pri

Also added more plugins, just in case

Windows Installer: Add missing Qml Modules

---

src/VehicleSetup/SetupViewButtons.qml

Make it more obvious why setup buttons are missing

---

QGCInstaller.pri

Fix OSX installer problem

---

QGCInstaller.pri

Switch to cd into release and then back to run macdelpoyqt

Previous cp of app to current dir too flaky (OS X Installer)

---

src/AutoPilotPlugins/PX4/AirframeComponent.cc
src/AutoPilotPlugins/PX4/AirframeComponent.h
src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/FlightModesComponent.h
src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml
src/AutoPilotPlugins/PX4/PX4Component.cc
src/AutoPilotPlugins/PX4/PX4Component.h
src/AutoPilotPlugins/PX4/RadioComponent.cc
src/AutoPilotPlugins/PX4/RadioComponent.h
src/AutoPilotPlugins/PX4/RadioComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponent.cc
src/AutoPilotPlugins/PX4/SafetyComponent.h
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.h

Using new logic to signal need for radio cal:
- Needed if any attitude control mapping is missing
- Needed if min, max and trim for still set to defaults for channel 1-4

Update Radio Cal trigger

---

src/AutoPilotPlugins/PX4/SensorsComponentController.cc

This is required to make sure progress indicator goes to 100. Also required to trigger param refresh.

Catch mag/dpress calibration complete

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml

Caused scroll bar so show up at wrong times

Incorrect height for text area

---

src/uas/UAS.cc
src/uas/UAS.h

@dogmaphobic This should fix the battery estimation for you - please cross test. If not, the diff should light up the relevant locations to fix - it should be a quick fix, if any.

Remove old battery estimation cruft

---

src/AutoPilotPlugins/PX4/Tests/FlightModeConfigTest.cc
src/VehicleSetup/SetupViewTest.cc
src/VehicleSetup/SetupViewTest.h
src/qgcunittest/MainWindowTest.cc
src/qgcunittest/MainWindowTest.h
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h

- Work around strange Window Qt bug/feature/something strange
- SetupView and MainWindow tests modified for new toolbar and turned back on.

Unit Test fixes

---

src/VehicleSetup/ParameterEditor.ui

Fix parameter config sizing

---

qgroundcontrol.qrc
src/QmlControls/QGCToolBarButton.qml
src/QmlControls/qmldir
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

Added custom "chevron" buttons to the main tool bar.

Chevron buttons in Main Tool Bar

---

qgroundcontrol.pro
src/QGCApplication.cc
src/QmlControls/MousePosition.cc
src/QmlControls/MousePosition.h
src/QmlControls/QGCButton.qml

Fix hover state of Button

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml

I made this param optional by moving it to the controller side of things. But then I left the Fact in by mistake.

Remove unused Fact

---

src/GAudioOutput.cc
src/ui/MainWindow.cc

Move some more signals & slots to the new syntax.
Fix a bug with restoring the last connection.

Couple o' changes

---

src/uas/UAS.cc

Minor adjustments to the audio text that's spoken. See commits for details.

Audio imps

---

src/AutoPilotPlugins/PX4/PowerComponent.qml

Hiding prop settings and mag calibration for the time being.

Disabling (undone) prop and mag cal settings.

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml

Causes failure when not all compass rotation values are available

Forgot to remove controller rotation setting

---

src/QGCPalette.cc

Current light palette was pretty nasty. Made light palette to be essentially the reverse of dark palette.

Light palette color changes

---

src/comm/UDPLink.cc

Fixes to the UDP link.
This is in response to issue #1371. I got my MavLink *slave* done (the most convoluted pile of wires with a Raspberry PI in the middle of it all) and was able to finally test UDP links. In the process, I found not only the issue mentioned above but also a couple of thread racing conditions. UPD links are functional but as I only have one MavLink device, I have not tested it with multiple connections.

UPD Link Fix

---

src/ui/DebugConsole.cc

Sorry I was trying to get away with testing on OS X and not have to crank up Ubuntu. The problem was the link deletion ordering problem. But in this case there were two part that needed fixing.

Debug console

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h

Deal with the fact that some parameters may not always be available.

Handle parameters not being available

---

src/qgcunittest/MockLink.cc
src/uas/QGCUASParamManager.cc
src/uas/QGCUASParamManager.h
src/uas/QGCUASParamManagerInterface.h
src/uas/UASParameterCommsMgr.cc
src/uas/UASParameterCommsMgr.h
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

Parameter load progress bar

---

src/uas/UASParameterCommsMgr.cc

Left in some qDebug with the progress bar pull

Remove qDebug's

---

README.md

Adding the changes required to build QGC on Windows.

Updating README for Windows builds.

---

src/AutoPilotPlugins/PX4/AirframeComponent.cc
src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/PX4Component.cc
src/AutoPilotPlugins/PX4/PX4Component.h
src/AutoPilotPlugins/PX4/PowerComponent.cc
src/AutoPilotPlugins/PX4/RadioComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/VehicleSetup/SetupViewTest.cc
src/VehicleSetup/VehicleComponent.cc
src/VehicleSetup/VehicleComponent.h
src/ui/MainWindow.h
src/ui/map/Waypoint2DIcon.cc

- SetupView unit test now clicks through all buttons preventing any further Qml screw ups
- Cut over more code to use FactSystem only for params.

Cut over more code fully to FactSystem, plus setup view unit test click through

---

src/uas/UASParameterCommsMgr.cc

Fix div by zero

---

src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml

Likely a result of a copy/paste.

Fixing superfluous curly braces.

---

src/QtLocationPlugin/OpenPilotMaps.cc
src/QtLocationPlugin/OpenPilotMaps.h
src/QtLocationPlugin/qgeotilefetcherqgc.cpp
src/QtLocationPlugin/qgeotilefetcherqgc.h

It was introduced by the Open Pilot URL Factory code I added the other day.

Fixed thread race condition.

---

README.md

Just updating after @DonLakeFlyer's renaming and cleanup.

Updating README to reflect the renaming of projects files.

---

src/ui/WaypointEditableView.cc
src/ui/mission/QGCMissionNavWaypoint.cc

Useful for when testing and you want to do a specific set of waypoints but aren't sure where you will be able to test them. By using the vehicle's position as the reference point, this is really easy.

Support LOCAL_OFFSET_NED waypoints.

---

src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml

Convert to use VehicleSummaryRow. Screwed this up with previous checkin only partially implemented.

Finish conversion of sensors summary

---

QGCSetup.pri

I think the will fix Issue #1456

Add QtLocation stuff to Windows

---

src/AutoPilotPlugins/PX4/AirframeComponentController.cc

Fix connected link check

---

QGCApplication.pro

This PR is a bit cosmetic but it helps me group blocks of code for exclusion for the upcoming iOS and Android builds. I've simply sorted the various lists of files (headers, sources, forms, etc.)

Sorting files.

---

src/ui/toolbar/MainToolBar.qml

I was using this while trying to figure out dimensions on Android.

Removing leftover debugging output.

---

src/QGCApplication.cc

Fix crash on reconnect

---

src/ui/HDDisplay.cc

Fixes crash on disconnect/connect.

Correctly handle UAS going away

---

src/QmlControls/ParameterEditor.qml

Fix the original cheesy implementation

Move dialog to a single instance to improve perf

---

src/QmlControls/QGCToolBarButton.qml

Towards a pixel dimension free UI.

Removing hardcoded pixel dimensions from toolbar buttons.

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/AutoPilotPlugins/PX4/FlightModesComponentController.h

Updated FlightMode setup to new spec which requires Return and Offboard switches to be on their own channels.

Return and Offboard must be on separate channel

---

src/AutoPilotPlugins/AutoPilotPluginManager.cc
src/FactSystem/FactBinder.cc
src/FactSystem/ParameterLoader.cc
src/QGCApplication.cc
src/QGCApplication.h

Exit app immediately if missing required paramter

---

src/ui/MainWindow.cc

@dogmaphobic I noticed that these were removed by one of your commits. Was there a reason or just something missed?

Put back Fly View default widgets

---

src/VehicleSetup/SetupViewTest.cc

Wait for pluginReady

---

src/comm/UDPLink.cc

This is a fix for issue #1540.
I'm trying to detect an ip address (x.x.x.x) and using it directly instead of asking Qt, which will do a reverse DNS lookup each time.

Skipping DNS lookup if not needed.

---

src/qgcunittest/FileManagerTest.h
src/uas/FileManager.cc
src/uas/FileManager.h
src/ui/QGCUASFileView.cc
src/ui/QGCUASFileView.h

Made a big pass through FileManager cleaning it up. Fixed a bunch of and error paths along the way. Burst download is now working.
After this goes through I'll start working on upload.

Cleanup FileManager

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/QmlControls/ParameterEditor.qml
src/QmlControls/QGCView.qml
src/QmlControls/QGCViewDialog.qml
src/QmlControls/QGCViewPanel.qml
src/QmlControls/qmldir

- Changed name of ViewWithDialog to QGCView
- More work on making QGCView real
- Converted Parameter Editor to QGCView. This fixes Issue #1544

ViewWithDialog -> QGCView

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/QGCApplication.cc
src/QGCApplication.h

Changed as per discussion in Issue #1548

Airframe Config: No longer tries to reconnect after reboot

---

src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.cc

VTOL must report as fixed wing

---

src/QmlControls/QGCView.qml

Having a little fun while on the road. Try the editing a parameter.

Animate QGCView dialog

---

src/uas/FileManager.cc

@LorenzMeier Can you give this a try? Should prevent it from looping.

Fix list EOF handling

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h
src/uas/UAS.cc
src/uas/UASInterface.h

@DonLakeFlyer This implements the horizon levelling and there is a matching Firmware PR coming.

Horizon level cal

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h
src/VehicleSetup/VehicleSummary.qml

@DonLakeFlyer This addresses the low hanging fruits in terms of usability.

Text cleanup

---

src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc

This just adds labels / string conversions

PX4 flight modes: Cleanup acro, introduce stabilize

---

QGCApplication.pro
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/PowerComponentController.cc
src/AutoPilotPlugins/PX4/PowerComponentController.h
src/QGCApplication.cc
src/QmlControls/ScreenTools.cc
src/QmlControls/ScreenTools.h
src/uas/UAS.cc
src/uas/UASInterface.h

Added to the Power Component. Requires firmware pull: https://github.com/PX4/Firmware/pull/2216/files#diff-136fc0576591fc6267a38badf810aec5R142.
Also added new medium and large default font sizes to ScreenTools. So for example the top Setup screen labels are large font and the gray shaded section headers in the setup screens are medium.

ESC Calibration

---

src/comm/UDPLink.cc

UDP was not setting SO_REUSEADDR so if a connection were to be made right after another was disconnected, QGC was not being able to bind the port (it takes a bit for the port to be free again). In addition, there was no error handling for binding errors. This was causing the MavLinkProtocol to receive a disconnect signal from an unconnected link, which in turns, causes an assert.

Fixing UDP connections issues.

---

src/input/JoystickInput.cc
src/input/JoystickInput.h
src/uas/UAS.cc
src/uas/UAS.h
src/ui/JoystickAxis.h
src/ui/JoystickWidget.cc
src/ui/JoystickWidget.h
src/ui/JoystickWidget.ui

@thomasgubler Can you give some recommendations how to best integrate this branch? Is this the better solution compared to joystickinput_settargets?

Joystickinput settargets2

---

src/comm/QGCFlightGearLink.cc
src/comm/QGCJSBSimLink.cc
src/comm/QGCXPlaneLink.cc

@dogmaphobic This is your fix from #1600 applied to the simulation links.
@tumbili This will likely improve your experience when running HIL.

UDP fix sim links

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/RadioComponent.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/FactSystem/FactControls/FactPanel.qml
src/QmlControls/ParameterEditor.qml
src/QmlControls/QGCView.qml
src/QmlControls/QGCViewPanel.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/qgcunittest/PX4RCCalibrationTest.cc

This simplifies using QGCView and friends. Converted everything over to it, which also fixed the Sensor config crash.

QGCViewPanel no longer needs to be in component

---

src/comm/LinkManager.cc
src/comm/LinkManager.h

Added PX4Flow identification

---

src/AutoPilotPlugins/PX4/AirframeComponentController.cc

This might be a fix for Issue #1630

Bump param wait time

---

src/ViewWidgets/CustomCommandWidget.qml

This keeps the custom command widget from popping a dialog

Keep FactPanelController happy

---

src/QGCApplication.cc
src/comm/LinkManager.cc

Turns on full logging even in release builds. Used as debugging tool for release builds.

--full-logging command line option

---

src/audio/QGCAudioWorker.cpp

A few more gibberish translated to English for the speech-to-text engine.
Plugged a new Pixhawk in for the first time today and got a barrage of gibberish voice alerts.

A few more gibberish into English translations.

---

src/comm/UDPLink.cc
src/ui/QGCUDPLinkConfiguration.cc

This fixes issue #1634 .
Not only editing was not persistent, deleting a target was not working either.

Fixed a few issues with target UDP hosts.

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml

Fixing typo.

---

src/AutoPilotPlugins/PX4/PowerComponent.qml

Also adjusting text layout while at it.

Adding note about USB connection for ESC calibration.

---

src/QGCConfig.h

Switch master to 2.6 Dev daily builds

Switch to Development 2.6

---

src/uas/UAS.cc

HIL is disabled for mobile builds.

Small build fix for mobile (Android and iOS).

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h

Requires corresponding firmware pull.
I'm going to reset the Stable 2.5 branch again after this goes through.

Change mag cal to 6 orientations

---

src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

I had fixed this previously but I think I broke with with one my other pulls.

Pull image size from FirmwareImage object

---

src/AutoPilotPlugins/AutoPilotPluginManager.cc
src/AutoPilotPlugins/AutoPilotPluginManager.h
src/AutoPilotPlugins/Generic/GenericAutoPilotPlugin.cc
src/AutoPilotPlugins/Generic/GenericAutoPilotPlugin.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/uas/UAS.cc
src/uas/UAS.h

This fixes the audio feedback for the PX4 flight stack.

Audio fix for PX4

---

src/uas/UAS.h

Remove old MAV_AUTOPILOT_PIXHAWK

---

src/SerialPortIds.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.h

Add in AeroCore support to the new firmware upgrade utility.

Add Gumstix AeroCore board support to firmware flashing.

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/AutoPilotPlugins/PX4/FlightModesComponentController.h
src/QmlControls/ModeSwitchDisplay.qml
src/QmlControls/QGroundControl.Controls.qmldir

Can now scroll to work on laptops and tablets. Plus many other changes:
- Thresholds can now be set manually or automatically
- Better live RC display
- Flight Modes names and descriptions
Some example screens for MultiRotor and FixedWing:

Flight Mode config redesign

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/AutoPilotPlugins/PX4/FlightModesComponentController.h

Flight Mode Config: Show text on already used channels

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml

@LorenzMeier Here it is for your review. One more question: Should fixed wing use Roll/Pitch/Yaw terminology for sticks or Aileron/Elevator/Rudder?

Update to Flight Mode descriptions

---

src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml
src/ui/QGCMapRCToParamDialog.cpp
src/ui/QGCMapRCToParamDialog.h

Map rc to param fix

---

src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h
src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorController.h

Parameter load errors shown to user

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h

Fix for Issue #1714. Or not really a fix, but better reporting of what went wrong.

Report failed initial parameter load to user

---

src/VehicleSetup/SetupViewTest.cc
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/comm/MockLink.h
src/qgcunittest/MainWindowTest.cc
src/qgcunittest/MavlinkLogTest.cc
src/qgcunittest/MavlinkLogTest.h

This prevents the annoying dialog when you are just doing thiings like calibrating.

Prompt for log save only if armed

---

src/VehicleSetup/PX4FirmwareUpgradeThread.h

Still guessing at upgrade problems

Search faster to not miss bootloader

---

src/GAudioOutput.cc
src/ui/MainWindow.cc

MainToolBar blank on Ubunto 15.04

---

src/uas/UAS.cc
src/uas/UAS.h

This is an attempt to fix #1753. @kd0aij If you like you can give this a go, I tested it as far as in that it enables HIL mode, but I haven't flown HIL with it yet.

UAS: Connect message sending via buffered signals

---

src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/AutoPilotPlugins/PX4/AirframeComponentController.h
src/FactSystem/Fact.cc
src/FactSystem/Fact.h

@LorenzMeier Can you give this a try. I haven't had a ton of time to test, but I think it works.

Wait for params before reboot

---

src/comm/UDPLink.cc

This is in response to #1752. The code was removing hosts from the list if a data send failed. The idea was that as new hosts show up (when QGC receives a packet from them), they are added to the list of hosts to redirect mavlink messages. If the host is gone, we should stop sending data.
There are two problems with that. First, static hosts, those added manually were not being detected as such. They should be flagged as static and never removed. Second, the code should only remove a host after some time has passed and nobody is there to received it, not on the first failure.
In the mean time, I disabled the "remove host" altogether until a better method is implemented.
Well, make that three problems. Another one not directly related to this bug but nonetheless important. The current code …

Stop removing UDP hosts when data send fails.

---

src/FactSystem/ParameterLoader.cc
src/uas/UASMessageHandler.cc
src/uas/UASMessageHandler.h

This shows the appropriate message on boot fails.

Boot report

---

src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc

@LorenzMeier Can you make sure I have this right?

Respect COM_RC_IN_MODE setting

---

src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/PowerComponentController.cc
src/AutoPilotPlugins/PX4/PowerComponentController.h
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h

This adds a button in the power config to allow triggering a UAVCAN configuration run.

UAVCAN config button

---

src/AutoPilotPlugins/PX4/PowerComponent.qml
src/QGCPalette.cc
src/QGCPalette.h
src/VehicleSetup/VehicleSummary.qml
src/ui/toolbar/MainToolBar.qml

Add new warning color palette entry:
- Use it for toolbar message modeless dialogs
- Use it in the other places which were hardcoded to yellow

Warning color

---

src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorController.h

- Parameter Editor now has commands like Refresh, Load from File on a Tools menu button instead of individual buttons.
- Added support for Reset all Parameters to Defaults
- Fix for Issue #1766

Param reset

---

qgroundcontrol.qrc
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/qmlcommon/QGCMapBackground.qml
src/ui/qmlcommon/VehicleMapItem.qml
src/ui/qmlcommon/qmldir
src/ui/uas/UASQuickView.cc

It's still a proof of concept at this point but what is there does work. Including support for displaying multiple vehicles, with vehicles coming and going.
I got deep enough into to it to familiarize myself with Gus's mapping stuff and now have a plan as to how to integrate Vehicle, MavManager and Mapping all together.

Add vehicle indicator to flight display

---

.travis.yml

Currently builds debug/release on linux. Working on getting it to run the unittests.

initial travis-ci

---

src/FlightDisplay/FlightDisplayWidget.qml

Primary Flight Display widget now has Options button to turn video background on/off

Add Video option menu

---

.travis.yml
test/qtlogging.ini

Using this PR to get OSX support working.

[WIP] travis-ci OSX

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc

Allow custom firmware flash on PX4Flow

---

src/GAudioOutput.cc
src/GAudioOutput.h
src/uas/UAS.cc
src/uas/UAS.h

Fix UT only shutdown ordering crash

---

QGCApplication.pro
src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/MissionMapItem.qml
src/FlightMap/qmldir
src/MissionItem.h
src/QGCApplication.cc
src/QmlControls/MissionItemSummary.qml
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

- New QMLObjectListModel which allows you to create a true model from a list object QObject's. They key to this model is that add and remove pass through to the Qml object using it.
- Use the above to modify the crazy vehicle and mission item adding code on the flight to much simpler QML friendly use of ListView and MapItemView's.

Use true list models for vehicles and mission items

---

src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/VehicleMapItem.qml

Don't show vehicle till 2d gps lock

---

QGCApplication.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/MissionItemIndicator.qml
src/FlightMap/qmldir
src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/MissionItem.cc
src/MissionItem.h
src/QmlControls/MissionItemEditor.qml
src/QmlControls/MissionItemIndexLabel.qml
src/QmlControls/MissionItemSummary.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/Vehicle/Vehicle.cc
src/uas/UASWaypointManager.cc
src/ui/HSIDisplay.cc
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui
src/ui/WaypointEditableView.cc
src/ui/WaypointList.cc
src/ui/WaypointViewOnlyView.cc
src/ui/map/QGCMapWidget.cc
src/ui/map/Waypoint2DIcon.cc
src/ui/map/Waypoint2DIcon.h

Not yet connected to vehicle. Click to add Mission Items. Still much work to do. From the menu View/New Mission Editor.

Mission editor (WIP)

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/FlightMap.qml

On the Fly view:
- You can switch between video and map background through the Options menu
- Map background shows compass and attitude widgets
- Video background shows compass and attitude HUDs
- Both show waypoint list

Add video background support

---

src/FactSystem/Fact.h
src/MissionItem.cc
src/MissionItem.h
src/QmlControls/MissionItemEditor.qml
src/ui/HSIDisplay.cc
src/ui/map/QGCMapWidget.cc
src/ui/map/Waypoint2DIcon.cc

All waypoint type editors are now supported. Getting closer...

More mission editing work

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/FlightMap.qml

- Only show video option if supported Issue #1856 
- Persist settings
- Show/Hide/Add items correctly

Map menu fixes

---

android/AndroidManifest.xml

It now uses the sensor to maintain proper landscape mode.

Fixing Android screen orientation.

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/MissionItem.cc
src/MissionItem.h
src/ui/map/Waypoint2DIcon.cc

Use Facts internally for mission item param storage

Mission work

---

QGCApplication.pro
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/FlightMap/FlightMap.qml
src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/MissionItem.cc
src/MissionItem.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/QGCApplication.cc
src/QmlControls/MissionItemEditor.qml
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASWaypointManager.cc
src/ui/HSIDisplay.cc
src/ui/WaypointEditableView.cc
src/ui/WaypointList.cc
src/ui/WaypointViewOnlyView.cc
src/ui/map/QGCMapWidget.cc
src/ui/map/Waypoint2DIcon.cc

- New MissionManager
- Plumb MissionManager through MissionEditor
- Mission Editor supports get/set
- Mission Editor visuals beginning to line up with designer visual
Warning: This is WIP. I would not fly with this. And it says that on the Mission Editor. But is does read and write back to the vehicle now. Click on the map to add Mission Items. Still lots of stuff missing, but it is functional now end to end.

More MissionEditor work

---

src/VehicleSetup/VehicleSummary.qml

Fix for the Vehicle Summary part of Issue #1864.
@dogmaphobic Can you give this a try?

Stop using fixed pixel count spacing

---

src/FlightMap/MapItems/MissionItemIndicator.qml
src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/QmlControls/MissionItemEditor.qml
src/QmlControls/MissionItemIndexLabel.qml
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h

Plus more overall ui work. Still a WIP.

Add Delete, Move Up, Move Down

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/QmlControls/IndicatorButton.qml
src/QmlControls/QGCView.qml
src/QmlControls/SubMenuButton.qml
src/VehicleSetup/VehicleSummary.qml

This fixes a large pile problems from Issue #1866. Left to do is Safety and Parameters editor.

Font size based sizing and relative positioning fixes

---

src/MissionEditor/MissionEditor.qml
src/MissionItem.cc
src/MissionItem.h
src/QmlControls/MissionItemEditor.qml
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h
src/Vehicle/Vehicle.cc

Also much other cleanup/change.
This should bring the New Mission Editor up to the state of being testable under HIL/SITL. I still wouldn't fly with it. But it's to the point where it's time to gather feedback/bugs.

Add relative altitude support

---

src/VehicleSetup/SetupView.qml

More fixes for Issue #1866. Quick fix for button scrolling.

Allow buttons to be scrolled

---

.travis.yml
QGCCommon.pri
src/VehicleSetup/JoystickConfigController.cc

Joystick fix

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/Vehicle/Vehicle.cc

Previous code was horribly wrong.

Fix APM adjustMavlinkMessage

---

src/comm/MockLink.cc
src/comm/MockLink.h
src/uas/UAS.cc

This was done to support both PX4 and APM flight stack with same code

Change arm/disarm mavlink message usage

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h

Since MissionItems are passed to Qml then need to be on the main thread

Take MissionManager off separate thread

---

src/QtLocationPlugin/OpenPilotMaps.cc
src/QtLocationPlugin/qgeomapreplyqgc.cpp
src/QtLocationPlugin/qgeotiledmappingmanagerengineqgc.cpp
src/QtLocationPlugin/qgeotilefetcherqgc.cpp

Updated Google Maps API Version
Updated User Agent used for map tile requests
Removed some annoying, unnecessary warnings,
Removed redundant errors (those are later reported by Qt anyway)

Fixed QtLocation Caching

---

src/ui/MainWindow.cc

Fix for Issue #1895.
@dogmaphobic Can you give this a try?

No widgets in mobile builds

---

qgroundcontrol.qrc
src/FlightMap/FlightMap.qml
src/FlightMap/Images/MapCenter.svg
src/FlightMap/Images/PiP.svg
src/FlightMap/Images/ZoomMinus.svg
src/FlightMap/Images/ZoomPlus.svg
src/QmlControls/DropButton.qml

Tweaking MapType and MapCenter icons
Added Zoom Plus/Minus icons to be used for maps
Added PiP icon for the upcoming Picture-in-Picture functionality

Icon Tweaks

---

src/FlightDisplay/FlightDisplayView.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

@LorenzMeier I flashed master this morning. Booted HIL and armed. Didn't get MAVLINK_MSG_ID_HOME_POSITION across the wire. Double-checked mavlink inspector as well, not there either.
Can you try?

Show home position on flight map

---

QGCApplication.pro
src/MissionEditor/MissionEditor.cc
src/MissionItem.cc
src/MissionItem.h
src/MissionItemTest.cc
src/MissionItemTest.h
src/MissionManager/MissionManager.cc
src/QGCApplication.cc
src/uas/UASWaypointManager.cc
src/ui/WaypointList.cc

- Fixed bugs found by ut
- Plus a few tweaks to mission items for better defaults.

Mission item Unit Test

---

QGCApplication.pro
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/MissionManagerTest.cc
src/MissionManager/MissionManagerTest.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/comm/MockLinkMissionItemHandler.cc
src/comm/MockLinkMissionItemHandler.h
src/qgcunittest/MultiSignalSpy.cc

- fix bugs found by test
- Implemented Mock mission item protocol in MockLink
I would now deem the new MissionManager about 90% verified against normal operation. Need to add a few more boundary test cases and then also implement Mission Item protocol failure unit testing and we'll be done.

Add MissionManager unit test

---

README.md

Update ubuntu readme

---

src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/AutoPilotPlugins/Generic/GenericAutoPilotPlugin.cc
src/AutoPilotPlugins/Generic/GenericAutoPilotPlugin.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h
src/MissionManager/MissionManager.cc
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/SetupView.qml

Allow param edit with missing parameters

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/ui/toolbar/MainToolBar.qml

Respect FirmwarePlugin::flightModeSetAvailable

---

src/Joystick/Joystick.cc
src/VehicleSetup/JoystickConfig.qml
src/VehicleSetup/JoystickConfigController.cc
src/VehicleSetup/JoystickConfigController.h

This should be the fix for Issue #1850. I found a bunch of bugs when you have multiple joysticks as well that I fixed.

Fix multi-joystick bugs and validation bug

---

src/AutoPilotPlugins/PX4/ParameterFactMetaData.xml
src/FlightDisplay/FlightDisplayView.qml
src/QGCApplication.cc
src/comm/LogReplayLink.cc

Also:
- Udpated parameter meta data. Old version had bad values whic caused warnings.
- Fixed yet another stop timer on wrong thread problem
- Turned off bogus qt.network.ssl warning

Flight map center tool

---

QGCApplication.pro
src/FlightDisplay/FlightDisplayView.qml
src/QGCApplication.cc
src/QmlControls/CoordinateVector.cc
src/QmlControls/CoordinateVector.h
src/QmlControls/QGCQGeoCoordinate.cc
src/QmlControls/QGCQGeoCoordinate.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

@LorenzMeier Is this enough damn lines for you!

Add support for flight track lines

---

src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/MissionItem.cc
src/MissionItem.h
src/QmlControls/QGCCanvas.qml
src/QmlControls/QmlObjectListModel.cc

Editor lines

---

QGCApplication.pro
src/audio/QGCAudioWorker.h
src/ui/HILDockWidget.cc
src/ui/HILDockWidget.h
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui
src/ui/MultiVehicleDockWidget.cc
src/ui/MultiVehicleDockWidget.h
src/ui/MultiVehicleDockWidget.ui
src/ui/QGCHilConfiguration.cc

There is also no longer a special Simulation view. You just show the HIL widget to do HIL.

Make HIL Dock Widget a normal widget

---

qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/RoundButton.qml

Also moving the Plan View tool bar buttons into a Row element.

Adding a RoundButton element.

---

src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/MissionItem.cc
src/MissionItem.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/MissionManagerTest.cc
src/QmlControls/MissionItemEditor.qml
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h

More work on waypoint lines

---

src/FlightMap/FlightMap.qml

Using textual description for now. We should have some enums for these (as it used to be) so they don't break if the text changes later down the road.

Change vehicle position icon based on map type.

---

.appveyor.yml
QGCInstaller.pri

Hacks to figure out why s3 deploy doesn't work.

appveyor s3 deploy

---

src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/QGCApplication.cc
src/QmlControls/MissionItemEditor.qml
src/comm/LogReplayLink.cc
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h

Fixes for Issue #1991 and #1992 
Also removed telemetry log support from mobile builds. This is likely a temp removal. Gets rid of the annoying crashed logs pop up. The whole lost log thing just doesn't work on mobile.

Home position fixes

---

README.md

+ fix "Unknown module(s) in QT: location-private positioning-private"

add qt5-qtlocation-devel for fedora

---

.gitignore
QGCApplication.pro
deploy/ubuntu_ppa
git_version.pri
qgroundcontrol.pro
src/QGCApplication.cc
src/QGCConfig.h
src/comm/MAVLinkProtocol.cc
src/git_version.h

Blocked on https://github.com/mavlink/qgroundcontrol/issues/1802

set QGC version from git

---

src/FlightMap/Images/ArrowHead.svg

Arrowhead for vehicle heading identification.

---

QGCSetup.pri

Switch to windeployqt to pull in install dependencies

---

src/FlightMap/Images/MapSyncChanged.svg

Updated existing icon and added a new one for when things have changed.

MapSync Icons

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/FlightMap.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionEditorController.cc
src/MissionItem.cc
src/MissionItem.h
src/MissionItemTest.cc
src/QmlControls/DropButton.qml
src/QmlControls/MissionItemEditor.qml
src/QmlControls/MissionItemIndexLabel.qml
src/ui/MainWindow.qml

Mission Editor usability changes

---

src/FlightMap/Images/TrashDelete.svg
src/FlightMap/Images/XDelete.svg

Two versions, a simple "X" and a Trash Can icon. We can tweak as needed once in place.

Delete Icons for Don

---

QGCApplication.pro
src/MissionEditor/MissionEditor.qml
src/QGCApplication.cc
src/VehicleSetup/SetupView.qml
src/comm/LinkManager.cc
src/comm/MockLink.cc
src/comm/MockLink.h
src/ui/MockLinkConfiguration.cc
src/ui/MockLinkConfiguration.h
src/ui/MockLinkConfiguration.ui
src/ui/QGCCommConfiguration.cc

- Fix Issue #2032 
Plus:
Disconnected:
Connected to Vehicle which has no plugin components defined:

Ui changes

---

.travis.yml
src/QGCApplication.cc
src/QGCFileDialog.cc
src/QGCMessageBox.h
src/VehicleSetup/SetupViewTest.cc
src/apps/qgcvideo/QGCVideoApp.cc
src/qgcunittest/MainWindowTest.cc
src/ui/MainWindow.cc
src/ui/MainWindow.h

@dogmaphobic @DonLakeFlyer Who knows if the splash screen messes with tablets. For sure easier without.
More code removed! Isn't that beautiful?

Remove splash screen. Fixes #2028

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/MapItems/MissionItemView.qml
src/FlightMap/MapItems/MissionLineView.qml
src/FlightMap/qmldir
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionEditorController.cc
src/MissionItem.cc
src/MissionItem.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManagerTest.cc

- Fly view now has waypoint lines
- Fixed a pile of 1-based mission item bugs
- Fixed a pile of home position in position 0 bugs
- Update MissionManager unit test to better match the editor usage pattern

Lines and more

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/RadioComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/QGCApplication.cc
src/QGCPalette.cc
src/QGCPalette.h
src/QmlControls/ClickableColor.qml
src/QmlControls/DropButton.qml
src/QmlControls/IndicatorButton.qml
src/QmlControls/ModeSwitchDisplay.qml
src/QmlControls/QGCButton.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/QmlTest.qml
src/QmlControls/QmlTestWidget.cc
src/QmlControls/QmlTestWidget.h
src/QmlControls/RoundButton.qml
src/QmlControls/ScreenToolsController.cc
src/QmlControls/SubMenuButton.qml
src/VehicleSetup/SetupView.qml
src/VehicleSetup/VehicleSummary.qml
src/ui/MainWindow.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarActiveVehicleComponent.qml

Plus lots of other tweaks to ui for visuals.

Better light palette for mobile

---

qgroundcontrol.qrc
src/FlightMap/FlightMapSettings.cc
src/FlightMap/FlightMapSettings.h
src/MissionEditor/MissionEditor.qml

Better visuals/mechanism for editor help

---

src/VideoStreaming/VideoStreaming.pri
src/VideoStreaming/gstqtvideosink/delegates/qtvideosinkdelegate.cpp
src/VideoStreaming/gstqtvideosink/painters/openglsurfacepainter.cpp
src/VideoStreaming/gstqtvideosink/painters/videomaterial.cpp
src/VideoStreaming/gstqtvideosink/utils/glutils.h

I finally tried a Windows build using Qt 5.5.1 and found it to be broken if Video Streaming was enabled. This follows @NaterGator OpenGL fixes in #1982.

Fixing OpenGL issues for Windows (Video Streaming)

---

QGCExternalLibs.pri
android/src/org/qgroundcontrol/qgchelper/UsbDeviceJNI.java
src/GAudioOutput.cc
src/GAudioOutput.h
src/audio/QGCAudioWorker.cpp
src/audio/QGCAudioWorker.h
src/uas/UAS.cc

A bit of work with Text To Speech
* Re-enabled speech for debug builds (only avoids unittest)
* Replaced deprecated API for Mac OS
* Added TTS support for Android
* Fixed some phrases here and there

Text to Speech Work

---

CodingStyle.cc
CodingStyle.h
CodingStyle.qml

Add Qml Coding Style

---

QGCApplication.pro
qgcresources.qrc
qgroundcontrol.qrc
src/ui/MainWindow.qml

Pulling this in now to avoid conflicts later.
* Split qrc into two files (QML and *Everything Else*)
* Made FlightDisplayView an *Item* off MainWindow rather than its root.

Preliminary work on the Flight View

---

src/FlightDisplay/FlightDisplayView.qml
src/MissionEditor/MissionEditor.qml
src/ui/MainWindow.qml

I also disabled the Field Manager for now until I can work out a decent user model.

Use tablet position for initial Fly/Plan location

---

src/comm/MockLink.cc
src/comm/MockLink.h
src/ui/MockLinkConfiguration.cc
src/ui/MockLinkConfiguration.h
src/ui/MockLinkConfiguration.ui

Add status text and voice output support

---

QGCCommon.pri

QtCreator now default build environment

---

src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/AutoPilotPlugins/PX4/FlightModesComponentController.h

Fix channel index reordering notification

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewDelayLoadInner.qml
src/FlightDisplay/FlightDisplayViewDelayLoadOuter.qml
src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/MissionItemView.qml
src/FlightMap/MapItems/MissionLineView.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/QGroundControlQmlGlobal.h
src/VehicleSetup/SetupView.qml
src/ui/MainWindow.qml

Moved Z order constants to QGroundControlQmlGlobal.

Fix z order

---

src/MissionManager/MissionManager.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Wait until parameter load complete for Mission Load

---

qgcresources.qrc
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionControllerManagerTest.cc
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionControllerTest.h
src/ui/MainWindow.qml

Also:
- Added unit test for MissionController offline to online transition
- Fixed a bunch of offline to online MissionController bugs
- Fixed tablet postion not getting to FlightDisplayView

Mission drag visuals

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewDelayLoadInner.qml
src/FlightMap/MapItems/VehicleMapItem.qml
src/FlightMap/Widgets/QGCCompassWidget.qml
src/MissionEditor/MissionEditor.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc

- Move editor map to home position once it becomes valid Issue #2102
- Fix Compass not updating problem

Mission home move

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/QmlControls/ModeSwitchDisplay.qml

Fix Flight Mode binding loop

---

src/QmlControls/ModeSwitchDisplay.qml

Fix mode selection coloring

---

src/MissionManager/MissionControllerManagerTest.cc
src/MissionManager/MissionManagerTest.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

This is the first step on the dark and twisty road known as AutoConnect.

Disconnect Vehicle after 30 seconds of lost communication

---

src/comm/MAVLinkProtocol.cc

Step #2 in the valley of the shadow of death known as AutoConnect

Start logging on heartbeat instead of connect

---

src/VideoStreaming/README.md

Only Doc change. No need for any build or functionality testing.

Doc fix for getting gstreamer in to android build

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

@scott-eddy this adds rattitude in QGC for your PR:
https://github.com/PX4/Firmware/pull/3038

Add Rattitude mode for PX4

---

src/MissionManager/MissionManagerTest.cc
src/qgcunittest/MavlinkLogTest.cc

Too unstable for CI at the moment

Disable MissionManagerTest and MavlinkLogTest

---

qgroundcontrol.qrc
src/QmlControls/ScreenTools.qml
src/QmlControls/ScreenToolsController.h
src/VehicleSetup/DebugWindow.qml
src/VehicleSetup/SetupView.qml

This is an attempt to determine some sort of constant to be used to compute dimensions for the various platforms and devices. This window is only reachable on *Debug Builds*.
The idea is to load it, take a screen grab and send it to me so I can gather the necessary data for coming up with a *size right everywhere* solution.

Debug window to help define device sizing issues.

---

qgcresources.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Images/PiP.svg
src/FlightMap/Widgets/QGCInstrumentWidget.qml

Added a button to the PIP window allowing you to close it (and get it out of the way). 
Made both, this new PIP close and the Instrument Panel close states persistent.

Adding button to close PIP

---

src/Vehicle/Vehicle.cc

@tumbili @devbharat This should put your joystick issues to rest. Please test and let us know.

Fix Joystick instantitation from settings

---

src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc

Fix loading of meta data

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h

Discovered some things while trying to debug missing mission items:
- Move MissionController to FlightDisplayViewMap. It worked in FlightDisplayView, but it is more correct to be in FlightDisplayViewMap since it is not needed in FlightDisplayView
- Added some logging to MultiVehicleManager

View tweaks

---

src/comm/MAVLinkProtocol.cc

Yet another try at a minor auto connect directional change

Start logging on heartbeat

---

src/ui/toolbar/MainToolBarIndicators.qml

This is for when arming/disarming the vehicle from the Toolbar.

Adding a confirmation dialog for when arming vehicle.

---

.appveyor.yml
QGCInstaller.pri

-qmake rename installer output

appveyor cleanup s3 deploy

---

QGCApplication.pro
QGCCommon.pri
QGCExternalLibs.pri
src/QGCApplication.cc
src/QGCMessageBox.h
src/QmlControls/ScreenToolsController.cc
src/QmlControls/SubMenuButton.qml
src/QtLocationPlugin/OpenPilotMaps.cc
src/QtLocationPlugin/qgeotilefetcherqgc.cpp
src/VideoStreaming/VideoStreaming.cc
src/ViewWidgets/ViewWidget.qml
src/audio/QGCAudioWorker.cpp
src/audio/QGCAudioWorker_iOS.mm
src/comm/QGCFlightGearLink.cc
src/ui/MainWindow.cc
src/ui/MainWindow.qml
src/ui/toolbar/MainToolBar.qml

In addition:
* Fixing code exclusion issues where Mac OS and iOS were both included when they shouldn't.
* Hardcoding warning text color on Fly View as that view does not respect the current palette.

Adding TTS to iOS

---

src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/ui/MainWindow.cc
src/ui/MultiVehicleDockWidget.cc

Tweaks on the way to auto-connect

Use vehicle count instead of link count

---

src/MissionEditor/MissionEditor.qml

Make the tool buttons in both views consistent.

Consistent buttons in Fly and Mission views.

---

src/MissionEditor/MissionEditor.qml

Fix tool button order in mission view.

---

src/FactSystem/FactControls/FactPanelController.cc
src/QmlControls/ParameterEditor.qml

Fix issue #2225 and some clean up.

Work on Parameter Editor

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/VehicleSetup/PX4FlowSensor.qml
src/VehicleSetup/VehicleSummary.qml

Added a check box for Showing/Hiding UAVCAN setting in the power dialog. In the process, I did some tidying up in the Summary, PX4Flow, Airframe, Power and Safety dialogues.

Tidying up Setup dialogs.

---

QGCSetup.pri
deploy/qgroundcontrol-start.sh

This shell script is used to run a installed version of QGC which goes against a Qt installed using the online installer.

Linux shell script run command

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

Remove MavCmdPreflightStorageCapability

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/preferences/GeneralSettings.qml

Also reflow settings pane to take less space

Add virtual joystick setting.

---

src/QmlControls/SubMenuButton.qml
src/VehicleSetup/SetupView.qml

Redesigned setup buttons to save space

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

New item uses altitude from last item

---

src/ui/MainWindow.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

Also made toolbar background consistent between street and satellite maps. The *light* version was too light and hard to see certain colors.
Now making sure to close any open *pop up* item when switching views.

Added extended GPS Info

---

src/ui/toolbar/MainToolBar.qml

Fixing black on black font issue.

---

src/FlightDisplay/FlightDisplayView.qml
src/QmlControls/JoystickThumbPad.qml

Did my final testing on desktop and managed to completely screw up multi-touch which was the whole point in the first place!

Fix virtual joystick MultiTouch

---

qgroundcontrol.qrc
src/comm/LinkManager.h
src/ui/MainWindowLeftPanel.qml
src/ui/preferences/LinkSettings.qml
src/ui/toolbar/MainToolBarIndicators.qml

This is work in progress. I'm adding the link configuration to the QML side. For now it will list the existing link configurations and you can connect and disconnect them.
Next will come the ability to create and edit links.

First pass at Comm Link settings (in QML)

---

src/FlightDisplay/FlightDisplayView.qml

Fix virtual joystick polling rate

---

src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/LogReplayLink.h
src/comm/MockLink.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/comm/TCPLink.h
src/comm/UDPLink.h
src/ui/QGCLinkConfiguration.cc
src/ui/SerialConfigurationWindow.cc
src/ui/preferences/GeneralSettings.qml
src/ui/preferences/LinkSettings.qml
src/ui/preferences/MavlinkSettings.qml

More work towards a QML version of Comm Link Settings.
Way too many system wide changes done. Sending it in to avoid conflicts later on.

Link Settings (WIP)

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QGCMapPalette.cc
src/QGCMapPalette.h

Map text color

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/QmlControls/ModeSwitchDisplay.qml

Was starting to look a bit nasty:

Tweaks to Flight Mode Config visuals

---

src/AutoPilotPlugins/AutoPilotPlugin.cc

Don't pop modal dialog during boot sequence

---

src/QGCLoggingCategory.cc
src/QGCLoggingCategory.h
src/VehicleSetup/Bootloader.cc
src/VehicleSetup/FirmwareImage.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.cc

Verify is still failing though. Better than before. Working on #2312

More reliable radio flash

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/LinkManager.cc
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h

@davids5 @kd0aij This adds support to flash v4 boards through QGC.

Add support for v4 boards

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/MissionManager/MavCmdInfo.json
src/MissionManager/MissionCommands.cc
src/MissionManager/MissionCommands.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/QGCApplication.cc
src/QGCToolbox.cc
src/QGCToolbox.h
src/QmlControls/MissionCommandDialog.qml
src/QmlControls/MissionItemEditor.qml
src/QmlControls/QGCView.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h

- New mission command editor dialog
- New MissionCommands toolbox object to get command info
- Added APM mission item set. Both PX4 and APM show same set of available commands.
- Deals with #2277

Add mission item categories

---

src/VehicleSetup/FirmwareUpgradeController.cc

Disconnect inactive links

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h

Fix for Issue #1475
This has a bad commit comment but for some reason I can't regenerate the patch so I'm putting it through like this.

Show altitude difference from prev waypoint in editor

---

src/MissionManager/MissionItem.cc

Fix altitude relative to home default

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/MapItems/MissionItemIndicator.qml
src/FlightMap/MapItems/MissionItemView.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionItem.h
src/QmlControls/MissionItemEditor.qml
src/QmlControls/MissionItemIndexLabel.qml

Show altitude in mission item

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionManager.cc

Send fake home pos waypoint with correct type

APM Mission fixes

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMFlightModesComponent.cc
src/AutoPilotPlugins/APM/APMFlightModesComponent.h
src/AutoPilotPlugins/APM/APMFlightModesComponent.qml
src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc
src/AutoPilotPlugins/APM/APMFlightModesComponentController.h
src/AutoPilotPlugins/APM/APMFlightModesComponentSummary.qml
src/FactSystem/Fact.cc
src/QGCApplication.cc
src/comm/MockLink.cc

Apm flight mode config

---

src/MissionEditor/MissionEditor.qml

After last delete don't move to invalid home position

---

src/MissionEditor/MissionEditor.qml

Also remove the little arrow things for dragging. Just made the invisible drag target larger instead.

Continuous drag of mission items

---

QGCCommon.pri
qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/AutoPilotPlugin.cc
src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/ParameterEditorController.cc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/ScreenToolsController.cc
src/VehicleSetup/SetupViewTest.cc
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/main.cc
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindowHybrid.qml
src/ui/MainWindowInner.qml
src/ui/MainWindowNative.qml
src/ui/preferences/GeneralSettings.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarController.cc
src/ui/toolbar/MainToolBarController.h

This was pretty pervasive so likely I missed some connection somewhere. But as far as I can tell it works.
Still not sure how you close an android app and get a window close event. So the concept of prompting for close when active connections is coded in their, but no idea how you trigger that.
@dogmaphobic Can you up level you Nexus 7 os and check that were are good there now. Then I'll update the play store listing.

Mobile runs Native QML

---

src/QGCApplication.cc

I think the assert caused boot crashes at some times

Assert -> qWarning

---

src/QGCApplication.cc
src/qgcunittest/UnitTestList.cc

Getting ready for #2350 changes. Don't want to do those without unit testing.

Mission manager test back on

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMNotSupported.qml
src/AutoPilotPlugins/APM/APMSafetyComponent.cc
src/AutoPilotPlugins/APM/APMSafetyComponent.h
src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentPlane.qml
src/AutoPilotPlugins/APM/APMSafetyComponentRover.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryPlane.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryRover.qml

APM Safety Config

---

src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryCopter.qml

Still more work left:
- Flickable isn't working correctly
- Need to reformat to take less vertical real estate
- Failsafe settings not in Summary page

APM GeoFence and Failsafe Triggers

---

src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryCopter.qml
src/QmlControls/QGCCheckBox.qml
src/QmlControls/QGCRadioButton.qml

- Fixed Flickable scrolling
- Failsafe on summary screen
- Better real estate usage

APM Safety fixes

---

src/AutoPilotPlugins/APM/APMFlightModesComponent.qml

APM Flight Mode: Flickable works, better real estate usage

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h

- Fix for Issue #2389
- Possible fix for Issue #2387

Retry initial param request if it fails, notify user

---

src/AutoPilotPlugins/APM/APMAirframeComponent.cc
src/AutoPilotPlugins/APM/APMAirframeComponent.h
src/AutoPilotPlugins/APM/APMFlightModesComponent.cc
src/AutoPilotPlugins/APM/APMFlightModesComponent.h
src/AutoPilotPlugins/APM/APMRadioComponent.cc
src/AutoPilotPlugins/APM/APMRadioComponent.h
src/AutoPilotPlugins/APM/APMSafetyComponent.cc
src/AutoPilotPlugins/APM/APMSafetyComponent.h
src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.h
src/AutoPilotPlugins/PX4/AirframeComponent.cc
src/AutoPilotPlugins/PX4/AirframeComponent.h
src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/FlightModesComponent.h
src/AutoPilotPlugins/PX4/PX4RadioComponent.cc
src/AutoPilotPlugins/PX4/PX4RadioComponent.h
src/AutoPilotPlugins/PX4/PowerComponent.cc
src/AutoPilotPlugins/PX4/PowerComponent.h
src/AutoPilotPlugins/PX4/SafetyComponent.cc
src/AutoPilotPlugins/PX4/SafetyComponent.h
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.h
src/VehicleSetup/VehicleComponent.h

Remove unused methods from VehicleComponent

---

src/AutoPilotPlugins/APM/APMRadioComponentSummary.qml
src/AutoPilotPlugins/APM/APMSafetyComponentPlane.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryPlane.qml

APM Plane safety config

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMTuningComponent.cc
src/AutoPilotPlugins/APM/APMTuningComponent.h
src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml
src/AutoPilotPlugins/APM/APMTuningComponentPlane.qml
src/AutoPilotPlugins/APM/APMTuningComponentRover.qml
src/FactSystem/ParameterLoader.cc
src/VehicleSetup/VehicleSummary.qml

APM Copter Basic tuning

---

src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/comm/PX4MockLink.params

PX4 GeoFence support

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

Left some stuff commented out from my geofence pull

Fix missin Safety Config warnings

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml

pending PR #3354 on PX4/Firmware

add rotation for Stryker VTOL

---

qgroundcontrol.pro
src/QGCFileDownload.cc
src/QGCFileDownload.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Show Apm version info when flashing

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMPowerComponent.cc
src/AutoPilotPlugins/APM/APMPowerComponent.h
src/AutoPilotPlugins/APM/APMPowerComponent.qml
src/AutoPilotPlugins/APM/APMPowerComponentController.cc
src/AutoPilotPlugins/APM/APMPowerComponentController.h
src/AutoPilotPlugins/APM/APMPowerComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponent.cc
src/FactSystem/FactControls/FactTextField.qml
src/FirmwarePlugin/APM/APMParameterMetaData.cc

- Also added support for FactMetaData::enumInfo from APM parameter meta data

APM Power Config

---

qgroundcontrol.pro
src/AutoPilotPlugins/APM/APMAirframeComponent.cc
src/AutoPilotPlugins/APM/APMAirframeComponent.h
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMFlightModesComponent.qml
src/VehicleSetup/SetupView.qml

- Airframe component is always created. Just doesn't show up if not ArduCopter
- Flight Modes: Channel Options not available in all firmwares

APM  plane fixes

---

qgcresources.qrc
src/AutoPilotPlugins/APM/APMAirframeComponent.cc
src/AutoPilotPlugins/APM/APMAirframeComponent.h
src/AutoPilotPlugins/APM/APMAirframeComponentAirframes.cc
src/AutoPilotPlugins/APM/APMAirframeFactMetaData.xml
src/AutoPilotPlugins/APM/APMAirframeLoader.cc

- Tri and Traditional helicopter don't need Airframe config
- Add missing V Tail, A Tail frame type
- Fix images for frame type to be correct

Show APM Airframe config at appropriate times

---

deploy/qgroundcontrol_installer.nsi

Windows: Force uninstall before new install

---

src/FactSystem/ParameterLoader.cc

qWarning instead of assert

---

src/AutoPilotPlugins/APM/APMAirframeComponentSummary.qml
src/AutoPilotPlugins/APM/APMCameraComponentSummary.qml
src/AutoPilotPlugins/APM/APMFlightModesComponentSummary.qml
src/AutoPilotPlugins/APM/APMPowerComponentSummary.qml
src/AutoPilotPlugins/APM/APMRadioComponentSummary.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryPlane.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryRover.qml
src/AutoPilotPlugins/APM/APMSensorsComponentSummary.qml
src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml
src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml
src/AutoPilotPlugins/PX4/PX4RadioComponentSummary.qml
src/AutoPilotPlugins/PX4/PowerComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml
src/VehicleSetup/VehicleSummary.qml

Takes less real estate and flows better on small displays. Fix for Issue #2463. Still a bit of a work in progress but better than before.

New Vehicle Summary format

---

src/comm/QGCSerialPortInfo.cc

Identify V4 board as Pixhawk

---

src/FactSystem/FactControls/FactPanel.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/QGCView.qml
src/QmlControls/QGCViewDialog.qml

Total hack but it seems to work. Fix for Issue #2398

Esc/Enter key support in QGCView dialogs

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h

Check for bad compass cal

---

src/QmlControls/QGCView.qml

Fix anchoring, resize main window now works correctly

---

src/AutoPilotPlugins/APM/APMAirframeComponentSummary.qml
src/AutoPilotPlugins/APM/APMCameraComponentSummary.qml
src/AutoPilotPlugins/APM/APMFlightModesComponentSummary.qml
src/AutoPilotPlugins/APM/APMPowerComponentSummary.qml
src/AutoPilotPlugins/APM/APMRadioComponentSummary.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryPlane.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryRover.qml
src/AutoPilotPlugins/APM/APMSensorsComponentSummary.qml
src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml
src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml
src/AutoPilotPlugins/PX4/PX4RadioComponentSummary.qml
src/AutoPilotPlugins/PX4/PowerComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml
src/VehicleSetup/VehicleSummary.qml

Reverts mavlink/qgroundcontrol#2468. This new thing is just too horrible to live with until I make a new thing.

Revert "New Vehicle Summary format"

---

src/AutoPilotPlugins/PX4/PowerComponentController.cc
src/AutoPilotPlugins/PX4/PowerComponentController.h
src/ui/SettingsDialog.cc

Power component shutdown

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml

- Better match to current setup config ui
- Also changes to be closer to airframe ui spec

Airframe Config: Changes to UI style

---

src/FactSystem/Fact.cc

We have real meta data now. Fake meta data was buggy. Fix for Issue #2490

Remove meta data hack

---

.appveyor.yml

I just noticed appveyor is failing every build due to nsis problems. I'll try to fix it here.

appveyor fix nsis install

---

src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCView.qml

()*@#$)(*&@#$ keyboard focus is still not working correctly. Causes UI to lock up in strange ways if you open a side dialog. Giving up again for another month or so.

Focus is still not working correctly

---

src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryCopter.qml
src/FirmwarePlugin/APM/APMParameterMetaData.cc

Issue #2493
Safety Config:
Vehicle Summary:

Arming checks added to Safety

---

src/AutoPilotPlugins/APM/APMCameraComponent.qml

Add MNT_DEFLT_MODE combo

---

src/AutoPilotPlugins/APM/APMAirframeComponent.qml
src/AutoPilotPlugins/APM/APMAirframeFactMetaData.xml

Users are getting confused because we are missing images. Will put back
new fancy version once we get new airframe config plus auto-generate of
images sorted out.
Fix for Issue #2491

Simplifying Airframe config

---

src/AutoPilotPlugins/APM/APMAirframeComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/FactSystem/FactControls/FactTextField.qml
src/QmlControls/MissionItemEditor.qml
src/QmlControls/ParameterEditor.qml
src/QmlControls/QGCView.qml
src/VehicleSetup/FirmwareUpgrade.qml

QGCView::showDialog std size

---

src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/comm/SerialLink.cc
src/comm/SerialLink.h

PX4 Firmware no longer requires mavlink USB start

---

src/FactSystem/ParameterLoader.cc

Fix default comp id detection

---

src/AutoPilotPlugins/Common/RadioComponentController.cc
src/AutoPilotPlugins/Common/RadioComponentController.h

Fix for Issue #2515.
@pritamghanghas Can you try this again your Linux board which is missing the params?

Harden code for missing params, handle APM special case

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/Generic/GenericFirmwarePlugin.cc
src/FirmwarePlugin/Generic/GenericFirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/Vehicle/Vehicle.cc

Warn on unsupported APM version

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/QGCApplication.cc
src/ViewWidgets/LogDownload.cc
src/ViewWidgets/LogDownload.h
src/ViewWidgets/LogDownload.qml
src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h
src/uas/UAS.cc
src/uas/UASInterface.h
src/ui/MainWindow.cc

Implementation of Log Download.
This needs an updated firmware to respond (https://github.com/PX4/Firmware/pull/3398)
I have not tested with APM. I need to flash something with it and generate some logs.
First shot at it. There is room for improvement. Waiting for feedback.

Log handling

---

src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/MissionManagerTest.cc
src/MissionManager/MissionManagerTest.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/comm/MockLinkMissionItemHandler.cc
src/comm/MockLinkMissionItemHandler.h

Fix for Issue #2350
Tested again unit test, real board and SITL.

Mission protocol robustness rework

---

src/MissionManager/MissionController.cc

Set dirty bit when RemoveAllItems

---

src/FlightMap/MapItems/MissionItemIndicator.qml
src/MissionManager/MissionController.cc

- "H" Home position indicator fix
- Fake home position fix

Mission fixes

---

src/QmlControls/ParameterEditor.qml

Fix QgcView::showDialogDefaultWidth reference

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorDialog.qml

RCToParam is PX4 stack specific

---

src/ui/QGCUASFileView.cc
src/ui/QGCUASFileView.h
src/ui/QGCUASFileViewMulti.cc

Onboard Files is PX4 only

---

android/AndroidManifest.xml

Android limit to tablets for now

---

src/MissionEditor/MissionEditor.qml

Prevent map from stealing ListView scrolls

---

src/VehicleSetup/FirmwareUpgrade.qml

Be specific about direct usb connection

---

src/MissionEditor/MissionEditor.qml
src/QGCApplication.cc
src/QGCApplication.h
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindowHybrid.qml
src/ui/MainWindowInner.qml
src/ui/MainWindowNative.qml

Partial fix for Issue #2408. Still missing is offline mission edit followed by vehicle connect.

Prevent loss of mission due to load or close app

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionManager.cc

Fix for Issues #2408 (added dialog text), #2585

Mission changes

---

src/ui/toolbar/MainToolBar.qml

Following suggestions from @lvale in #2570.

Updating GPS lock type text.

---

src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml

Add GCS Failsafe option

---

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml

Added QuadRanger airframe to Standard VTOL group
See https://github.com/PX4/Firmware/pull/3504

QuadRanger airframe

---

src/QmlControls/ParameterEditorDialog.qml

Param Edit: Combo box showing incorrect value

---

src/QmlControls/ParameterEditor.qml

Reset Flickable position when new group selected

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/FlightMap.qml
src/ui/MainWindowInner.qml

Also remove concept of “interactive” since it is no longer needed. Fix for Issue #2621

Prevent message popup from scrolling map

---

src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.qml

Now handles missing params from older FW revs. Still need to look at actual compass cal for older FWs.

APM Sensor: UI handles older firmwares

---

src/QGCApplication.cc

Fix for Issue #2609, #2608
@LorenzMeier @dogmaphobic Can you guys look this over. Especially for wording.

Stupid proof Linux serial port use

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h

Fix more incorrect severity problems

---

src/QGCConfig.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/comm/MockLink.cc
src/ui/MAVLinkSettingsWidget.cc
src/ui/MAVLinkSettingsWidget.ui
src/ui/preferences/MavlinkSettings.qml

Move GCS heartbeat to MultiVehicleManager

---

src/AutoPilotPlugins/APM/APMFlightModesComponent.qml
src/AutoPilotPlugins/APM/APMTuningComponent.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

I believe this fixes all the problems with supporting APM 3.2 Plane/Copter

APM 3.2 support

---

src/AutoPilotPlugins/Common/ESP8266ComponentController.cc
src/AutoPilotPlugins/Common/ESP8266ComponentController.h
src/AutoPilotPlugins/Common/ESP8266ComponentSummary.qml

Show ESP8266 Firmware Version in Summary Panel

---

src/QmlControls/ParameterEditor.qml

Clip parameter row strings

---

src/QmlControls/ParameterEditor.qml

Prevent incorrect param binding while switching component id

---

src/comm/PX4MockLink.params

Add missing MockLink params

---

src/AutoPilotPlugins/PX4/PX4RadioComponent.cc

Add missing Radio Component trigger

---

src/FlightDisplay/FlightDisplayView.qml
src/QmlControls/JoystickThumbPad.qml
src/comm/MockLink.cc
src/comm/MockLink.h

- Joystick position is bounded to rectangle
- No longer re-centers if thumb goes outside boundary. Stick stays at edge of boundary
- Thumb Pad moves to center itself at first thumb press location. This way as you put your thumb down for the first time it has no affect on joystick until you actually start dragging your thumb around
Fix for Issue #2308
@rjehangir This should be much better I think

Virtual joystick improvments

---

src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/LogReplayLink.cc
src/ui/MainWindow.cc
src/ui/QGCMAVLinkLogPlayer.cc
src/ui/toolbar/MainToolBarIndicators.qml

- Also fix vehicle selector dropdown in toolbar
Fix for Issue #2674 
@jgoppert Can you test this?

Fix multiple vehicles on same link

---

src/ui/uas/UASMessageView.cc

Info View: Fix multi-vehicle handling

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/SetupView.qml

Firmware upgrade usability

---

qgcresources.qrc

Some of my test changes went into master

Fix bad resource in Airframe Icons

---

src/Vehicle/Vehicle.h
src/comm/LinkManager.cc
src/comm/LinkManager.h

Prompt for missing SD Card

---

src/MissionEditor/MissionEditor.qml

Add mission item no longer times out

---

qgcresources.qrc
src/FlightDisplay/FlightDisplayView.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionControllerTest.cc
src/QmlControls/MissionItemEditor.qml
src/Vehicle/Vehicle.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/SetupView.qml
src/comm/LinkManager.cc
src/comm/LinkManager.h

Also removed some automatic map centering. Fix for Issue #2227

Add support for mission item insert in hamburger

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

- Load v110 format mission files as ArduPilot file format with home position as first item
- Fix error messaging from load/save
- Map now fits its viewport to the mission items when loaded
Fixes for issue #2694

Mission editor fixes

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightDisplay/qmldir
src/QmlControls/QGCPipable.qml
src/QmlControls/QGroundControl.Controls.qmldir

They are no longer created/destroyed each time you toggle PIP.
This is response to #2560

Making Map and Video view persistent.

---

.vagrantconfig.yml
README.md
Vagrantfile

A "vagrant up" on a host machine of Ubuntu 15.10 will provide binaries and a Qt environment in shadow-build/release which can be run on the host machine.

Add a Vagrantfile

---

deploy/qgroundcontrol_installer.nsi

Remove current user's settings and cache during uninstall too

---

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml

PX4: Update airframe meta data

---

deploy/qgroundcontrol_installer.nsi

Nobody asked for this but it drives me crazy on windows so I figured I would address it.
This commit adds a registry scan pass to detect if the USB serial driver package included is already installed (it checks for an exact version match). If the drivers are unnecessary we skip executing the USB driver installer.

Read currently installed USB serial drivers and skip reinstallation

---

src/VehicleSetup/FirmwareUpgradeController.cc

To address issue https://github.com/mavlink/qgroundcontrol/issues/2735

APM file locations revised

---

src/AutoPilotPlugins/PX4/PX4AirframeLoader.cc
src/AutoPilotPlugins/PX4/PX4AirframeLoader.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.h
src/QGCApplication.cc

It wasn't removing:
- Airframe meta data
- Parameter meta data
- Parameter cache

clear setting clears cached files

---

src/MissionEditor/MissionItemStatus.qml

Plan: Altitude display should not show non-spatial items

---

qgroundcontrol.pro
src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/MissionItemView.qml
src/FlightMap/MapItems/MissionLineView.qml
src/JsonHelper.cc
src/JsonHelper.h
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionControllerTest.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/MissionManager/MissionItemTest.cc
src/MissionManager/MissionManagerTest.cc
src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/MissionCommandDialog.qml
src/QmlControls/MissionItemEditor.qml
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/Vehicle.cc
src/VehicleSetup/SetupViewTest.cc
src/qgcunittest/UnitTestList.cc

As described here: Issue #2700. Fairly major change, make sure to read through Issue if interested.

Planned home position support

---

src/FirmwarePlugin/APM/MavCmdInfoCommon.json
src/FirmwarePlugin/APM/MavCmdInfoFixedWing.json
src/MissionManager/MissionCommands.cc
src/MissionManager/MissionItem.cc
src/MissionManager/MissionManagerTest.cc

Fix mission command overrides for offline edit

---

src/VehicleSetup/SetupView.qml

Fix conditions for showing Summary on lost vehicle

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManagerTest.cc

Fix DO_JUMP id handling

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/VehicleSetup/FirmwareUpgrade.qml

Change from APM to ArduPilot naming

---

src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItemTest.cc

It is also no longer a user visible field. Fix for Issue #2744

Default acceptance radius to 0

---

src/MissionManager/MissionController.cc

Fix line to home logic

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h

Plan view tracks mission progress by changing current mission item indicator as flight moves through items.

Track current mission item while flying

---

src/MissionManager/MissionCommands.cc

Fix vehicle switch crash

---

src/ui/uas/UASQuickView.cc
src/ui/uas/UASQuickView.h

Fix bad connection

---

src/MissionEditor/MissionItemStatus.qml

Plane: Fix scrolling on altitude display

---

src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/MissionManager/MissionCommandList.cc
src/MissionManager/MissionCommandList.h

Along the way I've written helper routines for things like Json parsing. This pull converts older code to use the new helper code.

Use helper routines

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/QGroundControlQmlGlobal.h

- Plan view uses Fly view location as initial position
- Added support for Center map to Mission
Fix for Issue #2560

Copy Fly view position to Plan

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/ValuesWidgetController.cc
src/Vehicle/BatteryFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml
src/ui/uas/UASQuickView.cc

* Vehicle.battery FactGroup
* Vehicle.battery.voltage
* Vehicle.battery.percentRemaining
* Vehicle.battery.percentRemaining
* Vehicle.battery.mahConsumed
* Vehicle.battery.current
* Vehicle.battery.temperature
* Vehicle.battery.cellCount
* Changed default Altitude display to Vehicle.altitudeRelative
* Removed incorrect Vehicle.altitudeWGS84
* Fixed battery handling so it works correctly with both PX4 and ArduPilot

Vehicle.battery FactGroup

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml
src/FlightMap/qmldir

Thumbstick alternate instrument panel

---

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml
src/AutoPilotPlugins/PX4/ParameterFactMetaData.xml

Mechanistic update. Please merge as it passes.

Update param meta data for PX4

---

src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc
src/AutoPilotPlugins/APM/APMFlightModesComponentController.h

Fix ArduPlane FLTMODE_CH usage

---

src/QmlControls/QGCTextField.qml

Don't auto-select on mobile

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h

Only save to eeprom when value changes

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h
src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h
src/ui/MAVLinkDecoder.cc

Keep ParameterLoader on first seen dedicated link

---

src/FirmwarePlugin/APM/MavCmdInfoCommon.json
src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionItem.cc
src/QmlControls/DropButton.qml
src/QmlControls/RoundButton.qml

* Flight patch lines are red now to match vehicle and to distinguish from waypoint lines
* Vehicle are shown in Plan view
* The sync button will spin when a send/load to/from vehicle is in progress
* Mission items which are related to landing have altitude defaulted to 0
Fix for Issues #2836, #2830

Bunch 'o Changes

---

src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionCommandList.cc

Land start is now standalone coordinate

---

src/MissionEditor/MissionItemStatus.qml
src/MissionManager/MissionController.cc

Also fixed bug where last item altitude was incorrectly pulled from home position.

Plan: Add Gradient to bottom item status

---

src/FlightMap/Widgets/ValuesWidget.qml
src/FlightMap/Widgets/ValuesWidgetController.cc
src/FlightMap/Widgets/ValuesWidgetController.h

This way you can glance at the intrument panel on tablet and easily see altitude

Altitude properties are visually distinct

---

src/FlightMap/Widgets/QGCInstrumentWidget.qml

Instruments not updating correctly.

---

src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui

Get rid of View menu

---

QGCSetup.pri

Adding libraries and plugin for Sqlite. It *should* be all that's needed but I can't test it right now (Linux box busy with an 11-hour long print job).

Sqlite for Linux

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

Remove unsupported commands

---

src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/AutoPilotPlugins/APM/APMSensorsComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml

- Sensors summary now shows you how many compasses you have
- Fix for APM accel cal. Can only use first accel offsets
@tcanabrava I was in there, so I replicated your changes for APM accel cal

Usability plus bug fixes

---

src/QmlControls/ParameterEditorDialog.qml
src/VehicleSetup/FirmwareUpgrade.qml

Restructure side dialog ui to flow from top to bottom

---

src/FlightMap/Widgets/InstrumentSwipeView.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml

- I broke it with my page swipe thiing
- Only show gear in panel if active vehicle

Fix instrument panel value picker

---

src/VehicleSetup/SetupView.qml

Mobile builds say "Click Firmware on the right ..."

---

src/Vehicle/Vehicle.cc
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

Update gps indicator to hdop, new hdop boundaries

---

src/MissionManager/MissionController.cc

Plane: Fix crash on delete

---

src/MissionEditor/MissionEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/SimpleMissionItem.h

Generated grid is dumb and meant mainly for testing:
* Polygon is converted to Rectangle
* Simple grid generated from that Rect
* Spacing works, Angle does not
* Fancy grid generation coming..
It's does prove out architecture though. You can round trip through load/save, send to vehicle and fly it.
Related to Issue #2507

Survey initial grid generation

---

src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h

Still a bit buggy.
Related to Issue #2507

Survey: Polygon grid support, with angle support

---

src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h

Survey: Add camera trigger support

---

src/QmlControls/QGCLabel.qml
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/ui/MainWindowLeftPanel.qml
src/ui/preferences/GeneralSettings.qml
src/ui/preferences/LinkSettings.qml
src/ui/preferences/MavlinkSettings.qml
src/ui/preferences/MockLink.qml

Everything except for Offline Maps tile generation screen is working now.

Settings: Fix for small screens

---

android/AndroidManifest.xml
src/FlightMap/FlightMap.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/MissionItemEditor.qml

Fixes for small screens on Plan/Fly

---

src/MissionEditor/MissionEditor.qml

MouseArea preventing Windows Surface scrolling

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml
src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml
src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc
src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4FlightModes.qml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.cc
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.h
src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml
src/QGCApplication.cc
src/VehicleSetup/VehicleComponent.cc

Simple flight mode config

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.cc
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.h

Add switch assignment to simple flight mode

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/QmlControls/FactSliderPanel.qml

Support increment parameter meta data

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/comm/LinkManager.cc
src/comm/QGCSerialPortInfo.cc
src/ui/preferences/GeneralSettings.qml

3DR Radios no longer exist
Fix for issue #2879

Change 3DR Radio -> SiK Radio

---

src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc

Fix flight mode channel

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/InstrumentSwipeView.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/SetupView.qml
src/uas/UAS.cc

* Speech changes to be more clear and less wordy
* Offline maps uses flight map position/zoom as initial position
* Add "Clear flight path" support to Fly view

Laundry list: Fixing things while tablet testing

---

src/AutoPilotPlugins/PX4/PX4FlightModes.qml

Simple FM config: Show Advanced if older firmware

---

Custom-Info.plist
QGCCommon.pri
QGCSetup.pri
ios/iOS-Info.plist
ios/iOSForAppStore-Info.plist
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Correct version info for all OSX/iOS builds

---

src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml

Flight Mode string cleanup

---

src/AutoPilotPlugins/APM/APMFlightModesComponent.qml
src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc
src/AutoPilotPlugins/APM/APMFlightModesComponentController.h

Fix settable flight mode channel

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/ParameterLoader.cc

Save params with 18 digit precision

---

src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml

Throttle-Mid Tuning

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/QGCApplication.cc
src/QGCApplication.h
src/QGCMobileFileDialogController.cc
src/QGCMobileFileDialogController.h
src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorController.h
src/QmlControls/QGCLabel.qml
src/QmlControls/QGCMobileFileDialog.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/QGroundControlQmlGlobal.h

- Supports open/save modes, with replace file notification
- Convert mission load/save to it
- Allow parameter load/save on mobile
Work towards #2857

New QGCMobileFileDialog for mobile

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionManager.cc

DO_JUMP fix

---

src/AutoPilotPlugins/APM/APMCompassCal.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Fix ArduPilot compass cal

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/ui/MainWindowLeftPanel.qml

Fix some control width problems

---

src/AutoPilotPlugins/APM/APMSafetyComponent.h
src/AutoPilotPlugins/APM/APMTuningComponent.h
src/AutoPilotPlugins/PX4/PX4TuningComponent.h
src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml
src/AutoPilotPlugins/PX4/SafetyComponent.h
src/QmlControls/FactSliderPanel.qml
src/VehicleSetup/SetupView.qml
src/VehicleSetup/VehicleComponent.cc
src/VehicleSetup/VehicleComponent.h
src/comm/PX4MockLink.params

Allow armed setup for Safety/Tuning

---

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc

Reorder vehicle components

---

src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/MissionEditor/MissionItemStatus.qml
src/QmlControls/QGroundControlQmlGlobal.h

* Guide mode altitude widget support
* Plan: Mission Item status indicator
Fix for Issue #3008

Support user configurable unit conversion

---

qgroundcontrol.pro
src/MobileScreenMgr.cc
src/MobileScreenMgr.h
src/MobileScreenMgr.mm
src/Vehicle/MultiVehicleManager.cc
src/ui/preferences/MockLink.qml

Turn off screen sleep if Vehicle connected

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/MissionEditor/MissionEditor.qml
src/QGCApplication.cc
src/QGCQuickWidget.cc
src/QmlControls/ParameterEditor.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/JoystickConfig.qml
src/VehicleSetup/PX4FlowSensor.qml
src/VehicleSetup/SetupView.qml
src/VehicleSetup/VehicleSummary.qml
src/ui/MainWindowInner.qml
src/ui/preferences/MavlinkSettings.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

Pull multiVehicleManager from QGroundControl

---

src/ui/linechart/ChartPlot.cc
src/ui/linechart/ChartPlot.h
src/ui/linechart/IncrementalPlot.cc
src/ui/linechart/LinechartPlot.cc

Bugs causing it to not be able to un-zoom. Fix for Issue #1723

Remove zoom support

---

src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapEngine.h
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp

Deleting old map tile disk cache if one is found.

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/SliderSwitch.qml

SliderSwitch is iOS stil confirmation

Add new SliderSwitch control, use for Guide mode confirmation

---

src/QmlControls/SliderSwitch.qml

@dogmaphobic I added some temp text indicators in there. You can pull these out when you replace with somethign better.

Add temp text indicators to SliderSwitch

---

.travis.yml

This is just for catching build breaks. A small step towards getting iOS into the Apple store.

Add iOS release builds

---

.appveyor.yml
deploy/qgroundcontrol_installer.nsi

Hopefully this will address #2996

Demote safe mode links so they don't confuse users of a fresh install

---

src/QGC.h

We just wanna move some code from QThread, from private
to public, se can use using:: for that.

Remove uneeded code

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h

Update flight mode naming

---

src/QGC.h
src/Vehicle/Vehicle.cc
src/comm/QGCFlightGearLink.cc
src/comm/QGCJSBSimLink.cc
src/uas/UAS.cc
src/ui/QGCDataPlot2D.cc

This way we don't need macro-magic to deal with
different operating systems and compilers.

Change calls to isnan / isinf to qIsNan / qIsInf

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QmlControls/SliderSwitch.qml

Click away is fine. No need to cancel
Related to #3042

Confirm slider: Remove cancel button support

---

src/QmlControls/FactSliderPanel.qml

Fix for Issue #3067. I completely broke this with my last set of small screen changes. Incredibly shitty testing on my part.

PX4 Tuning: Fix many bugs

---

src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h

Add new QuadPlane flight modes

---

src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.cc
src/comm/LinkManager.cc
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h

Fix for #2862. Also changed code flow so it's easier top add new vid/pid combinations.

Add SILabs serial ids for radio

---

src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/Vehicle/Vehicle.cc

Number of fixes to make QGC work with 3DR Solo

Solo fixes

---

src/ui/toolbar/MainToolBar.qml

Temp workaround until I can get to auto-disconnect in 3.1 release:
Related to #3056

Make disconnect for prominent

---

src/Vehicle/Vehicle.cc
src/comm/BluetoothLink.cc
src/comm/BluetoothLink.h
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LogReplayLink.cc
src/comm/LogReplayLink.h
src/comm/MAVLinkProtocol.cc
src/comm/MockLink.cc
src/comm/MockLink.h
src/comm/QGCFlightGearLink.cc
src/comm/QGCFlightGearLink.h
src/comm/QGCHilLink.h
src/comm/QGCJSBSimLink.cc
src/comm/QGCJSBSimLink.h
src/comm/QGCXPlaneLink.cc
src/comm/QGCXPlaneLink.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/comm/TCPLink.cc
src/comm/TCPLink.h
src/comm/UDPLink.cc
src/comm/UDPLink.h
src/comm/XbeeLink.cpp
src/comm/XbeeLink.h
src/qgcunittest/TCPLinkTest.cc

We are having issues with various types of link behaving improperly when they are threaded.
This is an attempt to clean up some of the rough spots where the link interfaces are interacted with in a thread unsafe manner.

[WIP] Link thread safety enforcement

---

.travis.yml

Had to change from brew install since that was installing 5.6

Travis: Use Qt5.5 download for OSX

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QGCApplication.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

- APM PreArm message show up in middle of map
- Self destruct after 30 seconds
- No pop-up message for PreArm message

APM PreArm message handling

---

src/comm/LinkManager.cc

Don't use channel 0 to avoid sequence number problems

---

.travis.yml

Also fix problem with log files over 4M causing build failure.

Improve travis.yml readability

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/FlightDisplay/FlightDisplayView.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/SimpleItemEditor.qml
src/QGCPalette.cc
src/QmlControls/IndicatorButton.qml
src/QmlControls/QGCButton.qml
src/QmlControls/QGCComboBox.qml
src/QmlControls/QGCToolBarButton.qml
src/VehicleSetup/SetupView.qml
src/ui/MainWindowInner.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

Outdoor palette is now a lot more palatable

Much better Outdoor palette visuals

---

src/ui/toolbar/MainToolBarIndicators.qml

Fix Message Indicator display

---

src/MissionEditor/MissionItemStatus.qml

Fix layout of mission item status values

---

src/MG.h

Found a unused class, safe to remove.

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/ui/preferences/LinkSettings.qml

Control was using __qgcPal which did not exist within control. It use to work because parent control had a __qgcPal.

Fix references to __qgcPal which did not exist in control

---

src/AutoPilotPlugins/Common/RadioComponentController.cc

Radio Cal: Only set reverse for multi-rotor

---

src/FlightDisplay/FlightDisplayViewWidgets.qml

Fix null _activeVehicle references

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml

Sensors: Use standard font size to fit on tablet

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/FlightMap/MapItems/MissionItemIndicator.qml

Radio cal scroll

---

src/FlightMap/Widgets/InstrumentSwipeView.qml

Fix for #3150. Need to use dynamic binding to additions to values page affects height after you swipe.

Swipe View: Use dynamic binding for height

---

.travis.yml

Need to get it into the installer as well first

Turn off streamer for OSX

---

src/QmlControls/VehicleRotationCal.qml

Mag cal: Fix text

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h

Parameter save: Notify user on read/write failures after retries

---

src/QmlControls/MissionItemEditor.qml

* Fix for Issue #3162
* Change visuals on command button to make it feel more like you should click it
* Also added "Change command.." to hamburger menu for folks that don't know they can click the button

Plan: Adjust "Change command" for better usability

---

src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/ui/UASInfo.ui
src/ui/uas/UASInfoWidget.cc
src/ui/uas/UASInfoWidget.h

Show mavlink sequence number packet loss in UI

---

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml

@DonLakeFlyer This just updates PX4 param meta, needed for tablet users.

Update PX4 meta data

---

src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/FactSystem/ParameterLoader.cc

* Fix for Issue #3167
* Also remove bonehead forgotten test code preventing param save from working

Mag cal fix

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h
src/Vehicle/Vehicle.h
src/uas/UAS.cc

Warn user about sensor cal over WiFi unreliability

WiFi sensor cal

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml

Better messaging for no airframe set

---

src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc

Fix noisy output

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

Fix RTL_LAND_DELAY usage

---

src/MissionManager/MissionController.cc

Plan: Remove All sets dirty bit

---

src/ui/MainWindowLeftPanel.qml

Especially on Windows touch (Surface Pro-like) devices

Fix opening QML based settings is twitchy and unreliable 

---

src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/SerialLink.cc

* This will automatically disconnect the Vehicle is you pull the cable on the connection for it.
* It does not automatically disconnect if the link i still there but the heartbeat is lost. For that you still get "Communication Lost" and Disconnect button.
Fix for Issues #3056, #3072

Auto-Disconnect on cable pull

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/QGCApplication.cc
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/RCChannelMonitor.qml
src/QmlControls/RCChannelMonitorController.cc
src/QmlControls/RCChannelMonitorController.h

* Abstract RC Channel Monitor into reusable control
* Changed RC Cal to use new control
* Changed FM Config to use new control
Fix for #2950

New RCChannelMonitorControl

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.cc

Fix flight mode display for PX4. Missed reverse channel check

---

src/AutoPilotPlugins/PX4/PX4TuningComponent.cc

Tuning not supported on VTOL

---

.travis.yml

travis-ci fold no longer needed

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h

@DonLakeFlyer @dogmaphobic This goes with: https://github.com/PX4/Firmware/pull/4347
One thing I couldn't figure out yet is how to click a point on the map. How does this work?
Since this is not a major UI thing I'd like to get this into 3.0 so that we can offer basic tablet operation with the release. I found already a few feedback items that we should address in general.

Support REPOSITION MAVLink command in PX4

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml

Minor usability fixes which enable decent percent usage.

PX4 Param System Update

---

src/AutoPilotPlugins/PX4/Images/DatalinkLoss.svg
src/AutoPilotPlugins/PX4/Images/DatalinkLossLight.svg
src/AutoPilotPlugins/PX4/Images/RCLoss.svg
src/AutoPilotPlugins/PX4/Images/RCLossLight.svg

Safety Icons Tweak

---

src/FlightMap/Widgets/ValuesWidget.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCView.qml
src/ui/MainWindowInner.qml

This commit fixes the QGCViewDialog with non Bitmask values.

Fix fact text field 2

---

qgcresources.qrc
qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/CameraComponent.cc
src/AutoPilotPlugins/PX4/CameraComponent.h
src/AutoPilotPlugins/PX4/CameraComponent.qml
src/AutoPilotPlugins/PX4/CameraComponentSummary.qml
src/AutoPilotPlugins/PX4/Images/CameraTrigger.svg
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/FactControls/FactPanelController.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Adding PX4 Camera Component (Settings)

Camera component

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/PX4/CameraComponentSummary.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/ui/QGCMapRCToParamDialog.cpp
src/ui/QGCMapRCToParamDialog.ui

Px4 usability

---

src/GPS/GPSManager.cc
src/GPS/GPSManager.h
src/Joystick/Joystick.cc
src/QGCToolbox.cc
src/QGCToolbox.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/UDPLink.cc
src/ui/preferences/GeneralSettings.qml

First cut at auto connect for RTK GPS:
* It will auto connect to UBlox RTK GPS
* RTK GPS auto-connect can be turned on/off from Settings
Not yet working:
* Auto-disconnect NYI
* Support for connecting to RTK GPS using a manually created comm link is NYI
* Mobile NYI
@LorenzMeier @bkueng FYI

AutoConnect for RTK GPS

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.h

Move Search from Tools menu

---

src/ui/QGCMapRCToParamDialog.ui

Fix dialog layout

---

src/ui/MainWindowInner.qml

This is in response to #3255 
Changed the background color to offer greater contrast.

Change background of the Critical Message Window

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ScreenTools.qml

Fix for Issue #3337. Keyboard support not there. Tied up in related issue.

Rework param search ui

---

.appveyor.yml
QGCCommon.pri
deploy/genPDBsrcsrv.py
deploy/lowercaseify_symbolstore.ps1
deploy/qgroundcontrol_installer.nsi
src/main.cc

closes #2679 
Questions
- how to rotate daily build symbols
- store by YYYY-MM-DD/buildId and delete after 1 month?
- or buildId % 100 and let s3 upload keep overwriting
- estimate s3 storage requirments
- ec2 micro instance for symbol server

deploy release and daily build pdbs

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/QmlControls/QGCView.qml

Fix double Reset button

---

QGCCommon.pri

With this Eigen3 is a MPLv2 dependency.

Turn Eigen into a MPLv2 dependency

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.cc

This should help with confused users who complain that the boundaries do not match.

PX4: Do mode switch mapping as done onboard

---

.appveyor.yml
.travis.yml
src/comm/TCPLink.h
src/qgcunittest/FileManagerTest.cc
src/qgcunittest/FlightGearTest.h
src/qgcunittest/LinkManagerTest.cc
src/qgcunittest/LinkManagerTest.h
src/qgcunittest/TCPLinkTest.cc
src/qgcunittest/TCPLinkTest.h
src/qgcunittest/UnitTestList.cc

try enabling tests

---

src/QtLocationPlugin/QGCMapUrlEngine.cpp

Fixes issue: Proxy settings ignored #601

use system proxy settings when fetching maps

---

src/FlightDisplay/FlightDisplayViewWidgets.qml

Fix map button exclusivity

---

src/ui/MainWindowInner.qml
src/ui/MainWindowLeftPanel.qml
src/ui/preferences/LinkSettings.qml
src/ui/toolbar/MainToolBar.qml

In response to #3400.
The preferences panel is now promoted to a top level panel.

Preferences panel

---

src/ViewWidgets/LogDownload.qml

Minor cosmetic fix.
While looking into #3376, it annoyed me that the buttons were all different sizes.

Making buttons same width.

---

src/AutoPilotPlugins/APM/APMCompassCal.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/FactSystem/ParameterLoader.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Remove 3rd compass fail check

---

src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc
src/AutoPilotPlugins/APM/APMFlightModesComponentController.h
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Fix/Review VTOL handling

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

Failsafe Action should be available for all airframe types.

Failsafe action

---

src/QGCApplication.cc

Move logging option setup to correct place

---

src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc

Support boolean meta data as param enum

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Show PX4 Stable version for flashing

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Now show beta version name as well as stable

Show PX4 beta version info for flash

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml

Tweak orientation UI for better usability

---

src/AutoPilotPlugins/APM/APMPowerComponentSummary.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummaryPlane.qml
src/AutoPilotPlugins/PX4/PowerComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponentSummary.qml

Show units in summary items

---

src/MissionEditor/MissionEditor.qml

Fix button z-order

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h

Parameter Protocol no longer stays on single link

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/MissionManager/MavCmdInfoCommon.json

This can be merged to enable ROI and CMD_DO_MOUNT messages support for PX4 once https://github.com/PX4/Firmware/issues/4584 has been merged.

Enable ROI and MOUNT support for PX4

---

src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/SimpleItemEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/QmlControls/MissionItemEditor.qml

Mission Plan Tweaks

---

src/FactSystem/FactControls/FactTextField.qml
src/FactSystem/FactMetaData.cc
src/FirmwarePlugin/APM/MavCmdInfoCommon.json
src/FirmwarePlugin/APM/MavCmdInfoFixedWing.json
src/FirmwarePlugin/APM/MavCmdInfoMultiRotor.json
src/FirmwarePlugin/PX4/MavCmdInfoFixedWing.json
src/FirmwarePlugin/PX4/MavCmdInfoMultiRotor.json
src/MissionEditor/MissionEditor.qml
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/SimpleMissionItem.cc
src/QmlControls/MissionItemEditor.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/ScreenTools.qml

iPhone 5:
FYI: This shows an additional bug (not yet fixed) where height display isn't showing up.
iPhone 4s:

Plan view small screen fixes

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/ui/preferences/GeneralSettings.qml

4s before:
4s after:
5s after:

General setting sizing

---

src/AutoPilotPlugins/PX4/PowerComponent.qml
src/QmlControls/AppMessages.qml

Fix for #3484. Plus...
5s:
4s clips a little but good enough:

Power small screen

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

Safety: Hide icon on small screens

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/comm/MockLink.cc
src/comm/MockLink.h

iPhone 5s:
iPhone 4s, requires horizontal scroll, but still works:

Simple flight mode small screen

---

src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml
src/QmlControls/ModeSwitchDisplay.qml

Shorter text and hide some text on small screens.
iPhone 5s:
iPhone 4s:

Advanced Flight Mode: Small screen updates

---

src/QmlControls/ScreenTools.qml
src/QtLocationPlugin/QGCMapUrlEngine.cpp

Updating mapping URLs.
Remove spurious debug message from ScreenTools.

Update map URLs

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/Common/RadioComponentController.cc
src/QmlControls/RCChannelMonitor.qml

Radio: Small screen fixes

---

src/AutoPilotPlugins/APM/APMFlightModesComponent.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml

Flight Mode: Flow sections to available real estate

---

src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentPlane.qml
src/FactSystem/FactControls/FactBitmask.qml

Works fine now all the way down to iPhone 4s

Safety: Small screen fixes

---

src/AutoPilotPlugins/APM/APMCameraComponent.qml

Camera: Small screen fixes

---

qgroundcontrol.qrc
src/FlightMap/MapScale.qml
src/FlightMap/qmldir
src/QtLocationPlugin/QMLControl/OfflineMap.qml

This one was a bit of a bear to get to work on small screens. Needed to do a decent job since on the iPhone you only have WiFi hence you always need offline maps to fly.
Here are 5s screens:
I removed the title from the top tp save real esate. I'm going to do that with all the Settings screens since it is redundant with the selected button.
Moved options to a side dialog to better follow the existing ui pattern.
* In general I moved this little popup thingies to the right edge since across bottom is too valuable real estate for a small screen. Across the bottom practically cover the whole map.
* Description is no longer supported
* Pulled out the numbers from the zoom buttons. Originally this was for two reasons: 1) I had some misconceptions on setting zoom which made me think you didn't …

Offline map small screen

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/QmlControls/VehicleRotationCal.qml
src/comm/MockLink.cc
src/comm/MockLink.h

Sensors small screen

---

src/VehicleSetup/JoystickConfig.qml

Allow disable of uncalibrated joystick

---

src/QmlControls/ParameterEditorDialog.qml

Fix bitmask editing

---

src/AutoPilotPlugins/APM/APMCompassCal.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.cc
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/Joystick/JoystickManager.h
src/QmlControls/QGCButton.qml
src/QmlControls/SliderSwitch.qml
src/Vehicle/Vehicle.cc
src/VehicleSetup/FirmwareUpgrade.qml
src/ui/toolbar/MainToolBarIndicators.qml

Pile of fixes listed, see commit descriptions. Fixes for: #3534, #3529, #3481, #3238

Testing 3.0 fixes

---

deploy/create_linux_appimage.sh

AppImage add more libfusion, libdirect

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QmlControls/SliderSwitch.qml

- Mobile large
- Desktop default

Guider bar font sizing changes

---

QGCInstaller.pri

To debug travis failure: #3543

Turn on verbose in hdiutil

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h

Fix problems which would only show up on certain OS

Offline map fixes

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml

Fix for: #3557, #3548
iPhone 5s:

Offline Map: Add preview and zoom numbers

---

src/QGCFileDownload.cc

Handle parameters at end of URL

---

src/FlightMap/MapScale.qml

MapScale: Add support for feet/miles

---

src/MissionEditor/SimpleItemEditor.qml
src/QmlControls/MissionItemEditor.qml

Planned Home Position: Tweaks to wording to help with confusion

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/ui/preferences/GeneralSettings.qml
src/ui/preferences/LinkSettings.qml
src/ui/preferences/MavlinkSettings.qml

Settings real estate

---

src/QGCMobileFileDialogController.cc
src/QGCMobileFileDialogController.h

To hel debugging user problems

Mobile file dialog: Add logging

---

src/QmlControls/JoystickThumbPad.qml

Virtual joystick: Throttle no longer spring loaded to center

---

src/ui/MainWindowInner.qml

Move message area to top

---

src/comm/MockLink.cc
src/comm/MockLink.h

- Delay gps position for better testing
- Longer delay on home position

MockLink: Support multi-vehicle simulation

---

src/FlightMap/MapItems/MissionItemView.qml
src/MissionEditor/MissionEditor.qml

Fixes ardupilot abbreviations for #3588

---

src/MissionManager/MissionManager.cc

Disregard spurious MISSION_ITEM

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml

Don't show board orientation after compass cal

---

src/AutoPilotPlugins/APM/APMFlightModesComponent.qml
src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc
src/AutoPilotPlugins/APM/APMFlightModesComponentController.h
src/AutoPilotPlugins/APM/APMFlightModesComponentSummary.qml
src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Various fixes to support Rover

Rover fixes

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionManager.cc

Plan: Mission loads from vehicle automatically

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml

Support for "Use compass" params

---

src/AutoPilotPlugins/Common/RadioComponentController.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc

Rover radio cal

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.4.xml

ArduCopter 3.4: Update meta data

---

src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml

Support both THR_MID and MOT_THST_HOVER

---

src/AutoPilotPlugins/APM/APMPowerComponent.qml

Add voltage/current calculators

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/QmlControls/RCChannelMonitor.qml

Radio Cal: PWM range is now 800<->2200

---

src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/FactSystem/FactControls/FactBitmask.qml

Make arming check ui less confusing

---

src/QmlControls/QGCMobileFileDialog.qml

Mobile file dialog: More debug logging

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/uas/UAS.cc
src/uas/UASInterface.h

Add CompassMot support

---

.travis.yml

The android builder is ignoring the cache.

travis-ci explicitly cache .ccache

---

src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Solo param usage fixes

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/Common/RadioComponentController.cc
src/AutoPilotPlugins/Common/RadioComponentController.h

Radio Cal: Warn on reversed throttle

---

src/qgcunittest/RadioConfigTest.cc

RadioConfigTest: Delay for mission item sync

---

src/VehicleSetup/FirmwareUpgradeController.cc

Add full set of v4 firmware

---

src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

Toolbar: Show sat count and hdop instead of signal strength

---

src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.h

Airspeed + circuit breaker check not quite right for setup complete check

Fix airspeed checking

---

src/QmlControls/QGCView.qml

Side dialog: Fix header height

---

src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/QmlControls/ParameterEditorDialog.qml

- Add reboot required
- Fix long description meta data
Fix for #3677

Param meta data fixes

---

src/MissionEditor/MissionItemStatus.qml

Fix no values case to draw correct grid

---

src/QGCApplication.cc
src/QGCFileDownload.cc
src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/VehicleSetup/FirmwareUpgradeController.cc

Add network proxy support

---

src/ui/preferences/GeneralSettings.qml

Convert to QGCView so validation will work for Facts

---

src/FollowMe/FollowMe.cc

Follow Me is PX4 only

---

src/AutoPilotPlugins/PX4/CameraComponent.qml
src/AutoPilotPlugins/PX4/CameraComponentSummary.qml
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml

This add support for the Seagull MAP2 cable. Goes with: https://github.com/PX4/Firmware/pull/4935

Camera triggering config update for PX4

---

src/AutoPilotPlugins/PX4/PowerComponent.qml

Px4 volt/amp calculators

---

src/Vehicle/Vehicle.cc

Keep 3 minutes of trajectory points

---

src/MissionManager/MissionController.cc

Replacement for #3666. Details there

Prevent double request of mission items

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QmlControls/SliderSwitch.qml

Fix height of slider confirm switch

---

src/QmlControls/QGCToolBarButton.qml
src/ui/MainWindowInner.qml
src/ui/toolbar/MainToolBar.qml

Fix for #3612. Help text stays on for 10 seconds:
https://www.youtube.com/watch?v=pw7Fpbtk_N0

Help text for toolbar buttons

---

.travis.yml

Disable CCCache

---

src/ui/QGCMAVLinkLogPlayer.cc
src/ui/QGCMAVLinkLogPlayer.h
src/ui/QGCMAVLinkLogPlayer.ui

Too buggy to leave it in for 3.0 release.
Related to #3601

Remove speed change support from log replay

---

src/Vehicle/BatteryFact.json

Fix percentRemainingAnnounce description

---

src/Joystick/Joystick.cc
src/VehicleSetup/JoystickConfig.qml

Joystick: Fix button code

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Needs testing. No wind in SITL.

mavlink WIND_COV -> windFactGroup

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/Vehicle/Vehicle.cc
src/ui/toolbar/MainToolBarIndicators.qml

Center hdop in toolbar, fix goto enabled state handling

---

src/MissionEditor/MissionItemStatus.qml
src/MissionManager/MissionController.cc

Fix home position distance to 0.0

---

src/AutoPilotPlugins/PX4/PowerComponent.cc

Button will show red correctly now

Power: Fix trigger list

---

src/AutoPilotPlugins/APM/APMAirframeComponentController.cc

Refresh params after airframe load

---

src/ViewWidgets/LogDownloadController.cc

Fix for #3364 
Gus, can you try to repro the crash as well using the new code. Maybe I was just lucky.

Log download: Correct ownership and deleteLater

---

src/QmlControls/QGCToolBarButton.qml
src/ui/toolbar/MainToolBar.qml

Remove fading help text

---

src/AutoPilotPlugins/Common/RadioComponentController.cc

Needs to be multi-rotor of helicopter only.

Radio Cal: Fix reverse throttle check

---

src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml

Issue: https://github.com/mavlink/qgroundcontrol/issues/3675
I couldn't run the unittests on my pc but Travis should do that now...

[APM] [Copter] Ch6 tune

---

src/ViewWidgets/LogDownloadController.cc

... cleaned up.
@DonLakeFlyer found this while dealing with #3364

Fixing a crash bug where a leaving vehicle was not being properly 

---

.appveyor.yml
.travis.yml
deploy/qgroundcontrol-start.sh
qgroundcontrol.pro
tools/google_play_upload.py

- all tagged builds to s3 latest/
- appveyor tagged builds to vX.Y.Z
- name qgroundcontrol -> QGroundControl (fixes android app name)
- travis-ci ccache OSX error

Build misc

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/Common/RadioComponentController.cc
src/QmlControls/RCChannelMonitor.qml

Radio Cal: Fix channel monitor when reversed

---

QGCCommon.pri
QGCInstaller.pri
android_environment.sh
deploy/create_linux_appimage.sh
src/QGCApplication.cc

branch:sha (Development) date
Too much?

Update development version from git

---

.appveyor.yml
QGCInstaller.pri

Trying to get everything named consistently.

more qgroundcontrol -> QGroundControl renaming

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

Replacement for #3699 on Stable_V3.0

Change to match mavlink spec

---

src/QGCApplication.cc
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapEngine.h

Adding a dialog telling the user the map cache database has been reset.

Map Reset Dialog

---

src/ui/uas/UASQuickView.cc
src/ui/uas/UASQuickViewTextItem.cc

Info view font

---

src/ui/uas/UASQuickView.cc
src/ui/uas/UASQuickViewTextItem.cc

Hack out dynamic font sizing

---

src/QmlControls/QGCView.qml

Prevent multiple clicks on dialog buttons

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorController.h
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h

Rewrote editor to be performant enough to support typedown. For for #3768

Parameter search is now typedown style

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/Common/RadioComponentController.h
src/AutoPilotPlugins/Common/SetupPage.qml
src/AutoPilotPlugins/PX4/AirframeComponent.cc
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/CameraComponent.cc
src/AutoPilotPlugins/PX4/CameraComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml
src/AutoPilotPlugins/PX4/PX4FlightModes.qml
src/AutoPilotPlugins/PX4/PX4RadioComponent.cc
src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/AutoPilotPlugins/PX4/PX4TuningComponent.cc
src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml
src/AutoPilotPlugins/PX4/PX4TuningComponentPlane.qml
src/AutoPilotPlugins/PX4/PX4TuningComponentVTOL.qml
src/AutoPilotPlugins/PX4/PowerComponent.cc
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/SafetyComponent.cc
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/QmlControls/FactSliderPanel.qml
src/QmlControls/ModeSwitchDisplay.qml
src/QmlControls/RCChannelMonitor.qml
src/qgcunittest/RadioConfigTest.cc

Most of PX4 Setup is done now. Still have ArduPilot to do.

Convert setup pages to use SetupPage

---

src/FlightMap/FlightMap.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h

Support for adjusting existing survey polygon

---

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Numbering on motor command is wrong (or strange), so wrong motors spin when using sliders. Fix for #3850

Remove motor test

---

deploy/qgroundcontrol_installer.nsi

Windows installer: Remove license page

---

QGCInstaller.pri

OSX Installer: Fix app naming

---

QGCInstaller.pri
deploy/qgroundcontrol_installer.nsi

Stable v3.0 installer fixes

---

QGCCommon.pri
ios/iOS-Info.plist
src/FlightMap/FlightMapSettings.cc
src/FlightMap/FlightMapSettings.h
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.h
src/QtLocationPlugin/QGeoCodeReplyQGC.cpp
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
src/ui/preferences/GeneralSettings.qml

Removed google maps from iOS builds.
Removed *Map Sources* from the General Settings panel (Bing is the only option there)

Restrict map providers for iOS.

---

doc/Doxyfile
src/QGCMapPalette.h
src/QGCPalette.h
src/QmlControls/ScreenTools.qml

Doxygen qml support

---

src/ViewWidgets/LogDownloadController.cc

Also report the current transfer rate in the currently downloading status to help expose regressions in performance.

Use human appropriate values for bytes in log downloader

---

src/VideoStreaming/VideoStreaming.cc
src/VideoStreaming/VideoStreaming.pri

Not the prettiest way to do it but it works.

GStreamer windows setup

---

.appveyor.yml
src/VideoStreaming/VideoStreaming.pri

Seems to work differently on appveyor build

GStreamer Setup: Fix xcopy problem

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/LinkManager.cc
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h

This adds support for another board. Something is not quite right with the boot loader setup as its not showing the next step to flash.

Add support for a custom board

---

src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml

Fix active binding

---

src/AutoPilotPlugins/Common/SetupPage.qml
src/VehicleSetup/JoystickConfig.qml
src/VehicleSetup/SetupView.qml

Joystick config: Fix scrolling

---

src/FactSystem/FactGroup.cc
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/MissionManager/SimpleMissionItem.cc

Use app settings translators on params

---

src/FactSystem/FactMetaData.cc

This should probably get fixed pronto. :panda_face:

Fix knots to m/s conversion. Oops.

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/BatteryFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/preferences/GeneralSettings.qml

The static Fact was causes problems with Qml.
Fix for #3949, #3919

Move battery.percentRemainingAnnounce to Qml Global

---

src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h

* Facts have meta data so you now gets units and unit conversion
* Restructured polygon buttons
* Moved survey stats from bottom mission item stats area up into survey editor
* Corrected camera shots to be 0 when no camera is triggered

Survey update

---

src/MissionManager/SurveyMissionItem.cc

Fix starting point for first grid line

---

qgroundcontrol.pro
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/FactControls/FactPanelController.h
src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h
src/ViewWidgets/LogDownloadTest.cc
src/ViewWidgets/LogDownloadTest.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/qgcunittest/UnitTest.cc
src/qgcunittest/UnitTest.h
src/qgcunittest/UnitTestList.cc

Currently does not simulate lossy connection. I will be adding that after this so I can use it to track down log download file corruption. Related to #3977

Initial implementation of LogDownloadTest

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/VideoManager.h

Turn camera off when not in use.

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/FlightMap.qml
src/FlightMap/qmldir
src/MissionEditor/GeoFenceEditor.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/QGCMapPolygonControls.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.cc
src/MissionManager/GeoFenceManager.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionManager.h
src/MissionManager/PlanElementController.cc
src/MissionManager/PlanElementController.h
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/QGCApplication.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Still very crude at this point. Major work in progress.

Initial GeoFence implementation

---

QGCExternalLibs.pri
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/Vehicle.cc
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/ui/MAVLinkDecoder.cc
src/ui/preferences/MavlinkSettings.qml

Reverts mavlink/qgroundcontrol#3967

Revert "Mavlink 2.0 support"

---

qgroundcontrol.pro
src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMGeoFenceManager.h
src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.4.xml
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.h
src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/GeoFenceEditor.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.cc
src/MissionManager/GeoFenceManager.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/PlanElementController.cc
src/MissionManager/PlanElementController.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

- GeoFence support comes from plugin
- Circle fence support
- Better param support

More work on GeoFence support

---

qgroundcontrol.pro
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4GeoFenceManager.cc
src/FirmwarePlugin/PX4/PX4GeoFenceManager.h
src/MissionEditor/GeoFenceEditor.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/GeoFenceController.cc
src/QmlControls/QGCRadioButton.qml
src/comm/LinkManager.cc

* Implemented PX4 GeoFence plugin
* Changed Plan Element (Mission, GeoFence) ui selection mechanism

PX4 fence plugin

---

src/VideoStreaming/README.md

Update README.md [ci skip]

---

src/QmlControls/QGCView.qml

Fix dialog buttons stuck in disabled state

---

src/FlightMap/FlightMap.qml
src/MissionEditor/MissionEditor.qml

Cancel polygon edit in appropriate places

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/CopterGeoFenceEditor.qml
src/FirmwarePlugin/APM/PlaneGeoFenceEditor.qml
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4GeoFenceManager.cc
src/MissionEditor/MissionEditor.qml
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/Vehicle/Vehicle.cc

* Make sure breach return stays inside polygon
* Various bug fixes.

GeoFence: Breach validate

---

src/MissionManager/MissionCommandTree.cc

Mission command tree respects FirmwarePlugin::supportedMissionCommands

---

src/QGCFileDialog.cc

Switch to native file dialogs on desktop builds

---

src/FlightMap/FlightMapSettings.cc
src/MissionEditor/SurveyItemEditor.qml
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.h
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp

This map is an absolute necessary for navigating the northern part of the country, steep mountains and deep valleys.

Maps:Added Statkart Topo2 (very useful norwegian topographic map)

---

.travis.yml
QGCCommon.pri
tools/patch_qt_for_xcode8.sh
tools/qt_ios_xcode8.patch
tools/qt_macos_xcode8.patch

Patching Qt qmake files for Xcode 8.

Another attempt at Xcode 8

---

build_ios.sh
ios/iOSForAppStore-Info-Source.plist

Some new requirements for iOS 10.

iOS Build Tweaks

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/VirtualJoystick.qml

Fix joystick coloring

---

qgcresources.qrc
src/main.cc

Linux add icon with setWindowIcon

---

src/QGCFileDownload.cc
src/QGCFileDownload.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

ArduPilot firmware urls now redirect

Handle redirects in file downloads

---

QGCExternalLibs.pri
src/comm/LinkManager.cc
src/comm/MAVLinkProtocol.cc
src/ui/MAVLinkDecoder.cc
src/ui/MAVLinkDecoder.h
src/ui/QGCMAVLinkInspector.cc
src/ui/QGCMAVLinkInspector.h

No signing support yet.
This pull still has these two unresolved issues:
* https://github.com/mavlink/mavlink/issues/630
* https://github.com/mavlink/mavlink/issues/625
But I think it's still ok without those.

Mavlink 2.0 support

---

src/ui/MAVLinkDecoder.cc
src/ui/MAVLinkDecoder.h
src/ui/QGCMAVLinkInspector.cc

Correct address of payload for Mav2

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Sub.3.4.xml

This PR only updates the parameter XML file for ArduSub. This is the reflect recent parameter additions and changes in the ArduSub firmware.
Let me know if anything needs to change.
-Rusty

Update MAVLink parameter definitions for ArduSub

---

src/MissionManager/MissionController.cc
src/comm/MockLink.cc
src/qgcunittest/MavlinkLogTest.cc

Fix line back to home for VTOL takeoff

---

src/MissionManager/MavCmdInfoCommon.json

Fix for #3861
This is what you wanted right?

Update VTOL command text

---

deploy/create_linux_appimage.sh

AppImage update to libsdl2

---

src/qgcunittest/UnitTestList.cc
src/ui/MainWindow.cc

Too buggy to leave in for now. For for #4143

Temp removal of Onboard Files

---

src/ui/toolbar/MainToolBar.qml

Fix brand image visibility calculation

---

qgroundcontrol.pro
src/QGCToolbox.cc
src/QGCToolbox.h
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/MAVLinkLogManager.cc
src/Vehicle/MAVLinkLogManager.h
src/Vehicle/MavlinkLogManager.cc
src/ui/AppSettings.qml
src/ui/preferences/MavlinkSettings.qml

MAVLink consistency

---

src/QmlControls/QGroundControlQmlGlobal.h
src/ui/MainWindow.cc
src/ui/preferences/GeneralSettings.qml

This makes it available on mobile builds. Fix for #4045

Add QGC version info to bottom of Settings/General

---

src/FlightDisplay/FlightDisplayViewWidgets.qml

This gets it above your head. Fix for #4174

Change default takeoff alt to 3 meters

---

qgroundcontrol.qrc
src/FlightMap/Widgets/InstrumentSwipeView.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/VehicleHealthWidget.qml
src/FlightMap/qmldir
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Fix for #4202
* Vehicle health is shown in second page of instrument panel center area
* If vehicle health changes to the worse, the health page will automatically show

New vehicle health display using SYS_STATUS info

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/PX4/PX4RadioComponentSummary.qml

No flaps for multi-rotor

---

src/uas/UASMessageHandler.cc
src/uas/UASMessageHandler.h

Filter out calibration messages

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

Correct altitude usage for Change Altitude

---

src/MissionEditor/MissionItemStatus.qml

Show mission time in minutes

---

src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml

Hi Don, this is a very minor update with some text fixed on the Sub safety page.

Improve Sub's leak sensor labeling for better clarity

---

src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMGeoFenceManager.h
src/FirmwarePlugin/APM/CopterGeoFenceEditor.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.h

Fix for #4215 as well as other problems found along the way.

Pile of GeoFence fixes

---

src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/MissionManagerTest.cc
src/MissionManager/MissionManagerTest.h
src/comm/MockLinkMissionItemHandler.cc
src/comm/MockLinkMissionItemHandler.h

Retry in all the right/possible places. Don’t freak out about things coming in unknown sequences.
Fix for #4214

Harden mission protocol to lost packets

---

src/AutoPilotPlugins/APM/APMSensorsComponent.cc

Only depend on accel 1 for setup complete

---

src/FlightMap/FlightMap.qml

Fix mobile polygon draw

---

qgroundcontrol.pro
src/AnalyzeView/ExifParser.cc
src/AnalyzeView/ExifParser.cpp
src/AnalyzeView/ExifParser.h
src/AnalyzeView/GeoTagController.cc
src/AnalyzeView/GeoTagController.h
src/AnalyzeView/GeoTagPage.qml
src/QGCLoggingCategory.cc
src/QGCLoggingCategory.h

Needs more documentation, testing and some tweaks in robustness.

Geotagging backend

---

src/FirmwarePlugin/APM/APMRallyPointManager.cc
src/FirmwarePlugin/APM/APMRallyPointManager.h

RallyPoint support should be optional

---

src/Vehicle/MultiVehicleManager.cc

Don't change active vehicle for additional vehicles

---

src/MissionEditor/MissionEditor.qml
src/QmlControls/DropButton.qml

Replacement for #4188
Replacement for #4189

Small fixes

---

src/FlightMap/Widgets/InstrumentSwipeView.qml
src/FlightMap/Widgets/VibrationWidget.qml

Swipe view click

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml

Fix combo selection bug

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h

Found some small bugs and make logging better while I was chasing down red herrings in multi-vehicle support.

ParameterManager: Better logging, plus some retry fixes

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarController.cc
src/ui/toolbar/MainToolBarController.h

Also removed intermediate param load retry message. Fix for #4154

Per-Vehicle parameter load progess

---

src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h

Allow changes of log saving if not armed with reboot

---

src/QmlControls/QGroundControl.Controls.qmldir
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

Toolbar multi vehicle fixes

---

qgroundcontrol.pro
src/RunGuard.cc
src/RunGuard.h
src/main.cc

Single instance app guarding mechanism

---

qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/QmlControls/AppMessages.qml
src/QmlControls/MissionCommandDialog.qml
src/QmlControls/ParameterEditor.qml
src/QmlControls/QGCListView.qml
src/QmlControls/QGCMobileFileDialog.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/ui/preferences/MavlinkSettings.qml

Shows horizontal/vertical scroll indicators. Fix for #3489

Use new QGCListView

---

src/AutoPilotPlugins/APM/APMSensorsComponentController.cc

Turn off COMPASS_LEARN after cal

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h

ArduPilot: Level Horizon support

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManagerTest.cc
src/FactSystem/ParameterManagerTest.h

Param mgr fix

---

src/ui/MainWindowInner.qml

This prevent the visibility change from trashing source setting

Hide view before settings source

---

src/MissionManager/MissionController.cc

Correct use of specifiesCoordinate

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml

Fix z-order

---

src/FirmwarePlugin/APM/APMParameterMetaData.cc

Default decimal places for PID params

---

src/MissionManager/MissionManager.cc

MissionManager: Fix read transaction flag

---

src/comm/LinkManager.cc

Android build stop serial probe after first connect

---

src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMGeoFenceManager.h
src/FirmwarePlugin/PX4/PX4GeoFenceManager.cc
src/FirmwarePlugin/PX4/PX4GeoFenceManager.h
src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.h

Update fence visibility flags

---

src/Vehicle/BatteryFact.json
src/Vehicle/Vehicle.cc

Change Vehicle.Battery.current to Amps units

---

src/AutoPilotPlugins/Common/ESP8266ComponentController.cc
src/AutoPilotPlugins/Common/ESP8266ComponentController.h
src/FactSystem/ParameterManager.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/LinkManager.cc
src/uas/UAS.cc

* Fix for #4296
* Use sendMavCommand in appropriate places

Vehicle::sendMavCommand fixes

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/Vehicle/GPSFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h

* Cleaned up the handling of specified messages to get correct values for all firmware types
* Remove a pile of unused code from UAS (still working towards making this class fo away completely)
* Fix for #4304 - Guided bar handles altitudes correctly

Correct message handling: GPS_RAW_INT, GLOBAL_POSITION_INT, VFR_HUD, ALTITUDE

---

src/Vehicle/MAVLinkLogManager.cc
src/Vehicle/MAVLinkLogManager.h
src/ui/preferences/MavlinkSettings.qml

Added additional fields present in the "flightreport" form.
Moved persistent settings to its own group

Updated MAVLink logging to the new “flightreport" form upload.

---

src/ui/Linechart.ui
src/ui/linechart/ChartPlot.cc
src/ui/linechart/ChartPlot.h
src/ui/linechart/IncrementalPlot.cc
src/ui/linechart/LinechartPlot.cc
src/ui/linechart/LinechartWidget.cc
src/ui/linechart/LinechartWidget.h

Minor UI tweaking to the charting widget as I try to grok all that it does (and how it does it).

Charting Tweaks

---

src/QtLocationPlugin/QGeoMapReplyQGC.cpp

In response to #4320. I added proxy handling elsewhere but I missed one spot. Note that I can't test this as I don't have any proxy to test with.

Handling proxies when fetching tiles.

---

src/Vehicle/BatteryFact.json
src/Vehicle/Vehicle.cc

Change battery.current to float with 2 decimal places

---

src/comm/LinkManager.cc
src/ui/preferences/GeneralSettings.qml
src/ui/preferences/LinkSettings.qml

Don't show dynamic links in Comm Links

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Also changed GPS FactGroup values to use NaN appropriately to show unavailable values.
Fixes for #4334 and #4338

Change priority of messages from which altitude comes from

---

src/AutoPilotPlugins/PX4/PowerComponent.qml

Correct UAVCAN settings

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightDisplay/qmldir
src/FlightMap/FlightMap.qml
src/FlightMap/Widgets/CenterMapDropButton.qml
src/FlightMap/qmldir
src/MissionEditor/MissionEditor.qml
src/QmlControls/OfflineMapButton.qml
src/QtLocationPlugin/QMLControl/OfflineMap.qml

Centralized all map centering code into new CenterMapDropButton control. This same control and functionality is then used in Fly, Plan and Offline Maps.
Fix for #4048

New CenterMapDropButton control

---

src/comm/LinkManager.cc
src/comm/LinkManager.h

Fix Qml API

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/DropButton.qml

Fix DropButton parenting

---

src/comm/UDPLink.cc

Better error output

---

src/AutoPilotPlugins/Common/RadioComponentController.cc

Radio Cal: Allow reverse setting for PX4

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml

ArduPilot compass cal: Fix compass numbering

---

src/Vehicle/Vehicle.cc

Fix current fact type

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml

Fix for #4385. Not super pretty but workable for now.

Alternate instrument fixes

---

src/ui/toolbar/MainToolBar.qml

Remove check marks

---

src/QtLocationPlugin/QGCMapUrlEngine.cpp

Update goole version

---

qgroundcontrol.qrc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/MultiVehicleList.qml
src/FlightDisplay/qmldir
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/PlanElementController.cc
src/MissionManager/PlanElementController.h
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointController.h
src/MultiVehicle/MultiVehicleView.qml
src/QmlControls/FlightModeDropdown.qml
src/QmlControls/GuidedBar.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/ScreenTools.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/MainWindowInner.qml

Radio buttons only show up when multiple vehicles are connected.

Starting point for new MultiVehicle view [WIP]

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/FlightMap.qml
src/FlightMap/MapScale.qml
src/MissionEditor/MissionEditor.qml
src/QGCMapPalette.cc
src/QGCMapPalette.h
src/QmlControls/QGCMapLabel.qml
src/QmlControls/QGCRadioButton.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QtLocationPlugin/QMLControl/OfflineMap.qml

This makes text show up better on map images

New QGCMapLabel using outline font

---

src/Vehicle/Vehicle.cc

Allow fallback to first link even with no serial

---

src/Vehicle/Vehicle.cc

Keep first link fallback when NO_SERIAL_LINK

---

qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/MissionSettingsEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/ComplexMissionItem.h
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/MissionManager/PlanElementController.cc
src/MissionManager/PlanElementController.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/MissionManager/VisualMissionItem.h
src/QmlControls/QGroundControlQmlGlobal.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/preferences/GeneralSettings.qml

- Shot Interval in Survey
- Much change to time/distance calc
- Time calculation now takes into account DO_CHANGE_SPEED in mission
Mission Settings:
Survey - Shot Interval

Mission Settings replaces Planned Home Position

---

src/Joystick/JoystickSDL.cc

Condition SDL counts so we don't pass negative numbers to new

---

qgroundcontrol.qrc
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/VehicleSetup/PX4FirmwareUpgradeThread.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.h
src/comm/LinkManager.cc
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h
src/comm/USBBoardInfo.json

This is phase 1 of making adding a new known board to the system a trival change. Phase 2 is json for firmware flash as well.

AutoConnect list driven from json file

---

src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

ArduPilot: New firmware format

---

qgroundcontrol.qrc
src/FlightDisplay/MultiVehicleList.qml
src/MissionManager/GeoFenceController.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionLoader.h
src/MissionManager/RallyPointController.cc
src/QmlControls/FlightModeMenu.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/Vehicle.cc
src/ui/preferences/GeneralSettings.qml

By specifying a directory here:
in General Settings. When QGC connects to a vehicle it will automatically upload a mission from that directory named "AutoLoad#.mission" where the # is replaced with the vehicle id. Browse button for directories coming soon.

Mission auto load

---

src/Joystick/JoystickManager.cc
src/Joystick/JoystickManager.h
src/Joystick/JoystickSDL.cc
src/QGCApplication.cc

Should help with debugging #4442

SDL: warn with SDL error string when joystick feature detection fails

---

src/QtLocationPlugin/QGCTileCacheWorker.cpp

Suggested by jieqian.li. It speeds up the creation of large sets.

Optimize SQL set creation.

---

src/MissionEditor/MissionEditor.qml
src/QmlControls/ScreenTools.qml
src/api/QGCOptions.h
src/ui/preferences/GeneralSettings.qml
src/ui/toolbar/MainToolBarController.h

* Remove some unused code in MainToolbarController
* Allow plugin to define fixed font size, toolbar height, etc.

More tweaks
