src/QGCApplication.cc
src/QGCFileDialog.cc
src/QGCFileDialog.h
src/qgcunittest/UnitTest.cc
src/qgcunittest/UnitTest.h
src/ui/MainWindow.cc
src/ui/QGCBaseParamWidget.cc
src/ui/QGCDataPlot2D.cc
src/ui/QGCDataPlot2D.h
src/ui/WaypointList.cc
src/ui/designer/QGCToolWidget.cc
src/ui/linechart/LinechartWidget.cc
src/ui/linechart/LinechartWidget.h

This is my first contribution and I'm still learning the ropes with GitHub. By now I've learned I should be working on an issue branch off my fork instead of my master branch. For now, this will do. I will get that right in my future PRs.
This fixes issue #1173 and add a few other things asked by @Susurrus:
CHANGED:
- Added (optional) argument to QGCFileDialog::getSaveFileName() allowing you to define a default suffix (extension) to be added if none is given by the user. If the user _does_ provide one, it is not replaced. That is, if the user enters "myflight.log", that's what it will be used. If the user however, enters "myflight" alone and the default suffix is set to "mavlink", the resulting filename will be "myflight.mavlink".
- Note that the default suffix is purposely not setup for …

Fix issue #1173

---

src/ui/map3D/Q3DWidget.cc

Local 3D view was completely unusable because updateWidget was never being called after it was renamed from update. The signal was not being emitted by Q3D.

Made Q3D emit updateWidget so that local view updates correctly.

---

src/QGCFileDialog.cc

No filters are to be selected. The argument selectedFilter is a pointer to a QString to receive the filter selected/used by the user.

Remove erroneous use of QFileDialog::selectNameFilter()

---

src/QGCApplication.cc
src/QGCFileDialog.cc
src/QGCFileDialog.h
src/qgcunittest/UnitTest.cc
src/qgcunittest/UnitTest.h
src/ui/MainWindow.cc
src/ui/QGCBaseParamWidget.cc
src/ui/QGCDataPlot2D.cc
src/ui/WaypointList.cc
src/ui/designer/QGCToolWidget.cc
src/ui/linechart/LinechartWidget.cc

Fix issue #1185.
Given that it's not used, I removed the *selectedFilter* argument from the QGXFileDialog file (static) helper methods. If you need to know what file type was selected, you can always do something like:
```c++
QString filename = QGCFileDialog::getSaveFileName(
this, tr("Save File"), "~/", "Foo files (*.foo);;All Files (*.*)", "foo");
if (!filename.isEmpty()) {
QFileInfo fi(filename);
QString fileExtension(fi.suffix());
if (fileExtension == QString("foo")) {
// do something
}
}
```
While at it:
* Added the above example to the Doxygen documentation.
* I've fixed the formatting of the method declarations and prototypes of QGCFileDialog (and other places I happened to be changing) to follow guidelines.
* Changed the caption of a few file save/load operations to something a …

Removing unused selectedFilter argument from QGXFileDialog methods.

---

qml/QGroundControl/FactControls/FactCheckBox.qml
qml/QGroundControl/FactControls/FactLabel.qml
qml/QGroundControl/FactControls/FactTextField.qml
src/QGCApplication.cc
src/QGCPalette.cc
src/QGCPalette.h

Adds support for QML ui to respect a Light/Dark style palette. Initial palette colors are basic light/dark style similar to exist Widget based light/dark style. Colors will be better defined as we work with UI designers. This may also require adding additional color properties to the palette at some point.

Add Light/Dark theme support to QML

---

README.md

Only seems to be missing in some cases but can’t hurt if already
installed.

Add missing qml module

---

src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.h
src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml
src/ui/px4_configuration/QGCPX4SensorCalibration.cc
src/ui/px4_configuration/QGCPX4SensorCalibration.h

The parameters for calibration were changed in the latest master. QGC
needs to work with both. Hacked in for now, waiting on a true parameter
re-mapping implementation.
This fixed Issue #1208.

Support two param sets for calibration

---

src/comm/SerialLink.cc

I had fixed this in my branch but when running today with master, it crashed on me again (it happens for me when switching USB connections between VMs). It's a small fix but if the port doesn't create, it crashes when moving threads...
P.S. It seems my editor is cleaning up blank spaces too and git is taking those as changes as well...

Fix small logic error with NULL serial port.

---

src/uas/UASManager.h
src/uas/UASManagerInterface.h

Using "..." on header includes not only is nasty but can end up doing different things on different compiler versions. This fixes a problem on Fedora.

Fix Eigen includes

---

src/ui/HUD.cc

problem:
in src/ui/HUD.cc copyImage(UASInterface* u): u->getImage() was called twice. The first called already erased the buffer.
changes:
src/ui/HUD.cc: copyImage(UASInterface* u): instead of getting the image a second time, we take the one we already fetched

Repaired feature to save images from video downlink (fixes #1239)

---

src/comm/SerialLink.cc
src/comm/SerialLink.h

Also converted qDebug statements to logging category.
This is the change to remove the disconnect/reconnect code from SerialLink as discussed previously. SerialLink was the only link type that did this. It's hard to say it actually accomplished anything other than adding confusion. Now the user will get true connection lost message due to loss of heartbeat and they can decide what they want to do. It will also now keep the connection open until the user explicitly decides to disconnect. Or if the communication actually does come back things will start working again. 
This will allow us to fix Issue #1219. Also it will stop strange behavior like issue #1214.

Remove disconnect/re-connect on too many link errors

---

src/QGCApplication.cc

changed QGCApplication::saveTempFlightDataLogOnMainThread(QString tempLogfile) to enable overwriting files
existing file is removed before saving file (QFile::copy cannot overwrite files)

Repaired overwriting current files for flight data log (fix #1241)

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/SafetyComponent.cc
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/FactSystem/Fact.cc
src/FactSystem/FactControls/FactCheckBox.qml
src/FactSystem/FactControls/FactTextField.qml
src/QGCPalette.cc
src/QGCPalette.h
src/QmlControls/QGCButton.qml
src/QmlControls/QGCCheckBox.qml
src/QmlControls/QGCLabel.qml
src/QmlControls/QGCRadioButton.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/QmlTest.qml
src/QmlControls/QmlTestWidget.cc
src/QmlControls/SubMenuButton.qml
src/QmlControls/qmldir
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/SetupViewButtons.qml
src/VehicleSetup/VehicleSummary.qml
src/test.qml

- Palette updated per ui discussion. Simplified the color group selection to just enabled/disabled. Also removed the InActive color for each entry.
- QML Controls now fully respect palette
- Fact Controls are now based on QGC* qml control variants as base
- Added new QGCTextField qml control
The Tools Widget/Test Qml Controls dialog shows the full new palette as well as working instances of all currently available controls:

Updated palette and QML Controls per ui discussion

---

src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h

Links were being disconnected but never deleted (and never re-used). These links were just accumulating and bloating resources. I did not have much success trying to simply disconnecting and immediately deleting them because it takes a thread cycle for the link disconnect signal to reach the MAVLinkProtocol instance, which keeps talking to the link. It would be a boatload of work to change that signaling and much more prone to errors.
Instead, I've implemented a simple delayed link delete mechanism to clean up these dangling, unused links.

Cleaning dangling links

---

src/comm/TCPLink.cc
src/comm/UDPLink.cc
src/comm/UDPLink.h
src/ui/QGCUDPLinkConfiguration.cc

This fixes issue #1261
Fixed logic where target UDP hosts were using the same local, listening port by default.
Also fixed a typo (copy/paste error) in the TCP link settings loading where it was using the UDP port as the default value instead of the TCP port.

Fixed issue #1261

---

src/QmlControls/QGCComboBox.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc

- QGCComboBox now follows QGCPalette and ui design
- Firmware Upgrade uses combo box for firmware selection
- Firmware Upgrade warns with message box if you select beta or developer firmware versions

Firmware Upgrade ui re-work, plus QGCComboBox work

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc

- Now tells you to disconnect and unplug at the start
- Tells you to click Upgrade again if you didn't unplug 
This is a partial fix to usability issues described in Issue #1272. Better sequence which doesn't require unplug will come later.

Better help text for Firmware Upgrade

---

src/AutoPilotPlugins/PX4/RadioComponent.cc
src/qgcunittest/PX4RCCalibrationTest.cc
src/ui/px4_configuration/PX4RCCalibration.cc

You have to do that from Flight Modes config. Changing in prep for new Flight Modes implementation.

Radio Cal no longer selects flight mode switches

---

src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui

Reorganized the Main Menu a bit into a slightly more logical order. The idea was to move everything a new user would get confused with into a new *Advanced* menu. No functionality was removed or added. Just shuffled around.
I also removed the icons some of the menu entries had. Most entries did not have an icon and those that did would not show at all under Mac OS. They differed wildly in style, none of which matching the new look and feel. We either come up with a new crop of consistently designed icons or leave as is. Clean.

Main Menu Reorg

---

src/audio/QGCAudioWorker.cpp
src/audio/QGCAudioWorker.h

Simple cosmetic change that was annoying me. When the RC signal is lost or regained, the reported time is given in milliseconds and the text to speech engine was spelling out this large number that is mostly incomprehensible. I changed the logic so when it detects a given time in milliseconds ([0-9]*ms), it converts into seconds, or minutes and seconds when warranted. It makes for a more normal spoken message. Now, instead of QGC speaking “RC signal regained after 372695 milliseconds” it says “RC signal regained after 6 minutes and 12 seconds”.
Note that when the RC signal is lost, the time reported is the elapsed time since the PX4 was started. However, when the RC signal is regained, the reported elapsed time is the time since the signal was lost.

Text to Speech Tweaks

---

src/VehicleSetup/SetupViewTest.cc
src/uas/UASMessageHandler.cc
src/uas/UASMessageHandler.h
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

Tool Bar Tweaks
Per #1310, the satellite icon now has 4 color behaviors:
* No GPS: Gray
* GPS present but no lock: Red
* 2D Lock: Blue (rare)
* 3D Lock: Green
The count is only shown if more than 0 satellites are seen. The logic behind the gray icon when there is no GPS is that you (will be able to) can chose to have the icon in the tool bar as a preference. In that way, the presence of the icon is based on a preference and not automatic. It makes for a more predictable behavior.
Per #1311, I’ve fixed the message icon so the drop down triangle is not shown if there are no messages to be displayed. Clicking on the gray icon has no effect if there are no messages. The icon is always visible, even if no messages are present, following the same logic as in above.
Per #1312, I’ve changed the …

Tool Bar Tweaks

---

QGCInstaller.pri

macdeployqt can not be reliably used to create a dmg. Sometimes it just fails silently. Going back to using hdiutil to create the dmg.

Fix OS X Installer yet again

---

src/ui/MainWindow.h
src/ui/SettingsDialog.cc
src/ui/SettingsDialog.h
src/ui/SettingsDialog.ui
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

I've added a Tool Bar section to the general section of the preferences dialog where you can set what to display in the tool bar. For now you can set if these items are shown:
* GPS
* Battery Status
* Messages
* Mav Icon
I've cleaned up a bit the dialog while at it though it seems the preferences dialog is also in need of quite a bit of TLC.

Completed Tool Bar settings in Preferences Dialog

---

src/ui/toolbar/MainToolBar.qml

The button is too small when it switches to "Disconnect" with multiple connections. That adds a drop down icon to the button and it was overlapping the text.

Minor fix to "Connect" button

---

qgroundcontrol.pro
src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml
src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml
src/AutoPilotPlugins/PX4/RadioComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/AutoPilotPlugins/PX4/SafetyComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml
src/FactSystem/FactBinder.cc
src/FactSystem/FactBinder.h
src/FactSystem/FactControls/FactCheckBox.qml
src/FactSystem/FactControls/FactComboBox.qml
src/FactSystem/FactControls/FactLabel.qml
src/FactSystem/FactControls/FactTextField.qml
src/FactSystem/FactLoader.h
src/FactSystem/FactSystemTest.qml
src/QmlControls/QmlTest.qml

Passing parameters QVariantMap across C++ boundary was causing crashes in Qt due to Qml array bugs. Referencing same Fact* across Qml boundary in multiple QQuickWidgets caused jScript GC to crash.
You now create a Fact object in your Qml and connect it to the appropriate fact by setting the "name" property: "property Fact fact:  Fact { name: "RC_MAP_THROTTLE }". The autopilot.parameters mechanism has been removed.
This way the behind the scenes FactBinder C++ object is created in the Qml context side of things thus preventing cross-widget GC references which cause things to crash.

Use FactBinder to access facts from Qml

---

src/FactSystem/FactBinder.cc

Also changed to qWarning. This usually indicates a bad problem so putting assert back.

Add assert back

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/FactSystem/FactSystemTest.qml
src/QmlControls/ScreenTools.cc
src/QmlControls/ScreenTools.h
src/QmlControls/VehicleRotationCal.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/VehicleSummary.qml
src/ui/toolbar/MainToolBar.qml

When defining fonts in point size, you need to take into account the display pixel density. Otherwise you end up with varying font sizes depending on the platform used (i.e. 72dpi for Mac OS, 96dpi for Windows, etc.) When I created the new tool bar (as a QML widget), I added code to handle this. I've now replicated it in all QML widgets.
While at it I've added missing licensing headers to the files I touched and documented *ScreenTools*.

Added code to handle point size fonts in all QML widgets.

---

src/QGCConfig.h
src/comm/LinkManager.cc
src/comm/SerialLink.cc
src/ui/QGCLinkConfiguration.cc

For whatever reason, QSerialPort stopped working when you provide the “short” name for the port you want to open. As far as I can tell, this is how it’s always beed done (the short version, I mean). All my 3 platforms, Mac OS, Linux and Windows stopped working. I switched to use the full port name and that fixed the problem.
I do not know the reason for it all to stop working and it is specially weird given that I have not heard of anybody else having issues.
The error I was getting when attempting to open the port was *Not Found*. Opening the port from the command line worked just fine so I knew it had to be QGC (QSerialPort).
When debugging, I switched from *usbserial-AH02QFUO* to */dev/cu.usbserial-AH02QFUO* and it then found the port just fine. From there I switched the port name …

Serial port fix

---

src/comm/SerialLink.cc
src/comm/SerialLink.h
src/ui/QGCLinkConfiguration.cc
src/ui/SerialConfigurationWindow.cc
src/ui/SerialConfigurationWindow.h
src/ui/SerialSettings.ui

Change to the **Serial Link Settings** dialog to show the *user friendly* port name in the serial port drop down box. The actual port name stored in the configuration is the full port name.
While at it, I've cleaned up a bit the serial settings code, which still contained some of the original code.

Show user friendly port name in Serial Settings combo box.

---

files/QLoggingCategory/qtlogging.ini
qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/PX4ParameterFacts.cc
src/FactSystem/FactLoader.cc
src/QGCApplication.cc
src/QGCLoggingCategory.cc
src/QGCLoggingCategory.h
src/comm/MAVLinkProtocol.cc
src/comm/SerialLink.cc
src/qgcunittest/MockLink.cc
src/qgcunittest/MockQGCUASParamManager.cc
src/uas/UAS.cc
src/uas/UASParameterCommsMgr.cc

Logging categories are now supported per Issues #1112.
QGC_LOGGING_CATEGORY macro should now be used instead of Q_LOGGING_CATEGORY. This is required to register all category names to the system.

qtlogging.ini automatically created at startup, populated with full list of category names

---

src/uas/UAS.cc

NOTICE messages are "unusual" events that shouldn't be seen during normal operations. In this context I would like to have them output as audio automatically.
Also fixed a bug where setting "#" at the start of the string triggers the audio reading of a message, but what was removed was always exactly "#audio:", which could result in odd behavior. I'd actually propose just using the '#' for indicating that it should be read over audio, but no need to follow through on that here.

Output audio for NOTICE severity STATUSTEXT messages.

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h

Also changed to pull specific small parameter set after cal instead of full refresh. This way, the red/green indicators update much more quickly.

Disable calibration buttons while calibrating

---

src/ui/linechart/LinechartWidget.cc

This change enforces ground time if the system is not synced well to the GCS clock. I think this greatly improves usability. If we replace the checkboxes visuals to make them easier to find people should have less issues with the live plot. It also ticks the ground time checkbox, but it does not leave it ticked on the next boot unless the user ticked it manually.

Line chart widget: Auto-force ground time if offset is more than 3 seconds

---

src/uas/UAS.cc
src/uas/UASInterface.h
src/ui/HSIDisplay.cc
src/ui/HSIDisplay.h
src/ui/PrimaryFlightDisplay.cc
src/ui/PrimaryFlightDisplay.h

Fix some dead code in both the HSI widget and the PFD widget. I think everything's working here, though the CDI is not like the pictures I've seen on the internet. Hopefully someone else has the `NAV_CONTROLLER_DATA` message being broadcast with correct data and can test this out and confirm it's correct.
The `NAV_CONTROLLER_DATA` message is lacking a few descriptions, so I'm just guessing that the `target_bearing` field is the subtraction of the bearing that the current mission segments has from the current bearing (course over ground).
And should the CDI have an arrow? It's not obvious what it's saying when you're angled 90deg to the current mission track.

Crosstrack error

---

src/ui/MainWindow.cc

This fixes issue #1366.
Not sure when this changed as it seems it predates me but the Quick Info View was missing a call to let it know where to get data from.
Now you get the full gory, unwieldy list of options to choose from (meaning, we really need to rethink this dialog):

Fixing list of items in Quick Info View

---

src/AutoPilotPlugins/PX4/ParameterFactMetaData.xml
src/AutoPilotPlugins/PX4/PowerComponent.qml

Cleanup of Power Settings
Advanced power settings are now in their own area and no longer appear within the basic power settings area when enabled. While at it, I've added "Battery Capacity" to the advanced section.

Advanced Power Config

---

libs/opmapcontrol/src/core/tilecachequeue.cpp
libs/opmapcontrol/src/core/tilecachequeue.h

Cleaning up the Tile Cache Queue code based on an issue brought up in the px4users  list:
https://groups.google.com/forum/#!topic/px4users/i1vAFNO_KLk

Cleaning up Tile Cache Queue

---

src/QGCConfig.h

Stable 2.3 is released. So switching master to 2.4 Development. Daily Builds are now back to dev builds.

Bump to 2.4 Developer Release

---

src/FactSystem/FactSystemTestBase.cc
src/VehicleSetup/SetupViewButtons.qml
src/VehicleSetup/SetupViewTest.cc
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/comm/MAVLinkSimulationLink.cc
src/comm/SerialLink.h
src/comm/TCPLink.h
src/comm/UDPLink.h
src/qgcunittest/LinkManagerTest.cc
src/qgcunittest/MainWindowTest.cc
src/qgcunittest/MavlinkLogTest.cc
src/uas/UAS.cc
src/uas/UAS.h
src/ui/MainWindow.cc
src/ui/QGCLinkConfiguration.cc
src/ui/QGCMAVLinkLogPlayer.cc
src/ui/QGCToolBar.cc
src/ui/toolbar/MainToolBar.cc
src/ui/uas/UASListWidget.cc

Also many LinkManager API changes to further isolate all link management inside LinkManager.
This fixes the shutdown issues where MAVLinkProtocol was still holding onto a deleted link. The issue is that you can't keep non-reference counted pointers to LinkInterface objects on another thread. If you do you run into all sorts of cross-thread signaling issues during shutdown. Which in turn leads the non-ui thread the reference a LinkInterface* after it has been deleted.
This change uses QSharedPointers for LinkInterface* objects kept in LinkManager. It also uses copies of these same QSharedPointers in MAVLinkProtocol and UAS we run on different threads. This way they are correctly reference counted and will shutdown in an orderly fashion when they are disconnected.
Another important point to …

Use QSharedPointer for cross-thread Link references

---

src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/VehicleSetup/VehicleSummary.qml

Also tweak vehicle summary to be more forceful about messaging to NOT FLY when setup items are not complete.

Pull full param list after calibration

---

src/ui/MainWindow.cc
src/ui/MainWindow.h

This should fix issue #1386 and the newly-brought-to-life issue when a link is (truly) disconnected (PR #1392). A link state change also causes the UI to fully redraw. Whenever there is a full redraw, the canvases used within QML elements must be forcefully redrawn as they don't get the hint on their own...

Fix redraw issues with OpenGL canvases when link states change.

---

src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/comm/MAVLinkSimulationLink.cc
src/comm/MAVLinkSimulationLink.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/comm/TCPLink.cc
src/comm/TCPLink.h
src/comm/UDPLink.cc
src/comm/UDPLink.h
src/comm/XbeeLink.cpp
src/comm/XbeeLink.h
src/qgcunittest/MockLink.cc
src/qgcunittest/MockLink.h
src/uas/UAS.cc
src/ui/DebugConsole.cc
src/ui/QGCMAVLinkLogPlayer.cc

Link ids were being used interchangeably with the mavlink channel for the link. Link ids are handed out as a numerically increasing integer. Once the counter went past MAVLINK_COMM_NUM_BUFFERS all hell would break loose and cause memory corruption.
This was causing intermittent unit test failures which I've been tearing my hair out over for more than a week. Finally figured it out. Unit tests would exacerbate this since they connect/disconnect lots of links in one run of QGC. You can also hit this in normal QGC running if you happen to connect/disconnect more than 16 times.
This fix isn't perfect in checking all limits either. But it's 100 times better than it was before. Still need to deal with Issue #1397.

Remove link ids and add link mavlink channel

---

src/ui/DebugConsole.cc
src/ui/DebugConsole.h

Since debug console maintains a list of links it needs to use shared pointers so it doesn’t run into the link delete ordering problem. This should be the fix for Issue #1402

Track links using shared pointed

---

files/styles/style-dark.css
files/styles/style-light.css
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/QGCApplication.cc
src/QGCPalette.cc
src/QGCPalette.h
src/QmlControls/QGCButton.qml
src/QmlControls/QGCCheckBox.qml
src/QmlControls/QGCComboBox.qml
src/QmlControls/QGCLabel.qml
src/QmlControls/QGCRadioButton.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/QGCToolBarButton.qml
src/QmlControls/ScreenTools.cc
src/QmlControls/ScreenTools.h
src/QmlControls/SubMenuButton.qml
src/QmlControls/VehicleRotationCal.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/VehicleSummary.qml
src/ui/toolbar/MainToolBar.qml

- Added new dpiAdjustedDefaultFontPointSize to QGCPallete for use in controls
- All Qml controls default to the above point size
- Widget style sheets font sizes are dpi adjusted at boot time
- Fixed some incorrect pixel font size usage
The above changes should limit the need for specifying your own font size. You only need to do that when you want something other than default. In that case you still must always use ScreenTools::dpiAdjustPointSize in your Qml.

Font's are now correctly and equally size across all OS

---

src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui

I renamed the *Perspectives* menu to a more standard *View* menu. In addition, I've added an option to show and hide the Status Bar, giving more screen real estate when you don't need the log playback.

Status bar

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml
src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml
src/AutoPilotPlugins/PX4/PowerComponentSummary.qml
src/AutoPilotPlugins/PX4/RadioComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml
src/QmlControls/VehicleSummaryRow.qml
src/QmlControls/qmldir

Some of the text in the summary boxes was positioned incorrectly. Now uses a common control for rows so they are all the same.

Use common control for summary rows

---

QGCExternalLibs.pri
QGCSetup.pri

This allows Qt Creator to be used for building/debugging QGC. The project was hardcoded to create a *Release* target for the platform plugin and trying to copy to *Debug* (failing in the process). I also added Ole32.lib library, without which, there was a link error caused by a Speech library dependency.

Fixing QMake project for Windows

---

qgroundcontrol.qrc

It got renamed to *HexaRoto* and it was failing to load...

Fixing HexaRotor typo.

---

src/QtLocationPlugin/OpenPilotMaps.cc

This is following @DonLakeFlyer's work on trying to remove SSL dependencies on Mac OS. It follows changes done in https://github.com/mavlink/qgroundcontrol/commit/d61846e3fc2ea4cc330816e477af1c0e43162b9c#diff-196af59d74aecde6f8a746db640a6199

Switching away from https to http.

---

src/AutoPilotPlugins/PX4/PX4ParameterFacts.cc
src/AutoPilotPlugins/PX4/PX4ParameterFacts.h
src/AutoPilotPlugins/PX4/ParameterFactMetaData.xml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Parameter meta data is stored in firmware files. Pull it out and store it next to settings. Use this newer meta dat if available, otherwise fall back to version stored in resources.

Firmware Upgrade pulls parameter meta data

---

src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/VehicleSetup/VehicleSummary.qml

Trying to do some more hand holding without being too annoying...
Vehicle Summary for a vehicle which doesn't require setup:
Connect to a vehicle which still required setup. You get this:
Click Ok and you are automatically taken to Vehicle Summary page which now looks like this:

Lead the user through fixing setup problems

---

src/QGCConfig.h
src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h
src/comm/LinkManager.cc
src/ui/SerialConfigurationWindow.cc
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

I've reworked how links are managed. Gone is the combo box with the links. Instead you will find one single *Connect* button. If nothing is physically connected to the computer and you don't have any connection configured, the only option it will provide is to *Add a Connection*. As you plug in a device, either a Pixhawk or a 3DR Radio Modem, these will be automatically added to the list. These automatically found devices are *Dynamic Devices*. They are not persistent and are also automatically removed from the list once you physically disconnect them from the computer.
Link configurations that are manually entered are *Persistent Links*. These will be saved and always displayed on the connection list. If you edit a *Dynamic* link, it becomes persistent and it will also be saved.
The …

Link Management Work

---

qgroundcontrol.qrc
src/QmlControls/QGCMovableItem.qml
src/QmlControls/qmldir
src/ui/flightdisplay/FlightDisplay.qml
src/ui/qmlcommon/QGCAttitudeInstrument.qml
src/ui/qmlcommon/QGCCompassInstrument.qml
src/ui/qmlcommon/QGCMapBackground.qml
src/ui/qmlcommon/QGCSlider.qml

An early experiment where the idea is to have arbitrary (QML) widgets on the *Primary Flight Display*, which you can move them around as well as change their sizes.
Double-clicking on the gadget causes it to restore its original position and size.

Created new movable/scalable Item type.

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/PX4Bootloader.cc
src/VehicleSetup/PX4Bootloader.h

- Unknown board ids are force to custom firmware load
- Board id must still match board id in px4
- Flash of .bin is allowed in all cases

Allow firmware flash for unknown board ids

---

src/ui/toolbar/MainToolBar.cc

This fixes #1481.
The heartbeat timeout was not being reset on new connections.

Reset heartbeat timeout on new connection.

---

src/ui/MainWindow.cc

This deals with issue #1467.
On smaller screens (1280 or less), it goes full (available) screen. On larger screens it goes up to 1600x800 as an initial size.
The original code was using the *Desktop* size to compute how large a window could go. On Windows, when you have multiple displays, the *Desktop* is the combined area spanning all displays.

Starting window size

---

src/ui/px4_configuration/PX4RCCalibration.cc

This way live rc update is correct after a calibrate. Fixes Issue #1297

Reset internal param values after calibrate

---

src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

This fixes #1500.
If there is no GPS, the icon is gray and shows *NA*.

Fix GPS icon when no GPS is present.

---

android/src/com/hoho/android/usbserial/driver/UsbSerialProber.java
android/src/org/qgroundcontrol/qgchelper/UsbDeviceJNI.java
libs/qtandroidserialport/src/qserialport.cpp
libs/qtandroidserialport/src/qserialport.h
libs/qtandroidserialport/src/qserialport_android.cpp
libs/qtandroidserialport/src/qserialport_p.h
libs/qtandroidserialport/src/qserialportinfo.cpp
libs/qtandroidserialport/src/qserialportinfo.h
libs/qtandroidserialport/src/qserialportinfo_android.cpp
libs/qtandroidserialport/src/qserialportinfo_p.h
libs/qtandroidserialport/src/qtandroidserialport.pri
src/comm/SerialLink.cc

Still not working right...
The issues are beyond what I understand about Java and/or Android. These changes, besides some cosmetic ones to match the current Qt file headers, take it a bit further but in general, this whole Qt SerialPort layer for Android is not working. Too many crashes (it doesn't at all like being called from a different thread for instance). I'm trying to track down Mike Goza, who originally wrote this and submitted as a patch to Qt (which was never integrated). In the mean time, the only reliable way to connect to Android is UPD/TCP and even that needs to be hardcoded for the moment, as the UI for setting up connections (Qt Widgets) os not usable within Android/iOS.

Android SerialPort work.

---

src/uas/UASWaypointManager.cc

When you load a waypoint files, the changes you do in the waypoint list (for example, changing the longitude of a waypoint) are not applied to the points displayed on the map.
Reproduce the bug: Load a waypoint file, and try to modify a waypoint longitude with the spin box in the waypoints list.
What does this fix do: In the loadWaypoints function, it uses the function addEditableWaypoint to add the waypoints instead of adding them directly to the map. This function was used before in the code, for example when we get the waypoints for the UAS.

Fixed the load waypoint bug - points from the list out of sync with points on the map

---

src/AutoPilotPlugins/PX4/AirframeComponentController.cc

Fix for Issue #1504. But it will just assert later because the RTL_LAND_DELAY parameter has gone missing from the parameter list in the latest firmware and it's required by Vehicle Summary and Safety Config.

Fix SYS_AUTOSTART=0 issue

---

src/ui/flightdisplay/QGCFlightDisplay.cc
src/ui/flightdisplay/QGCFlightDisplay.h
src/ui/qmlcommon/QGCAttitudeInstrument.qml

The original logic, which was inherited from the original Main Flight Display, would update every UI element for any change that might have occurred. I've changed the code so only relevant changes are updated. There were way too many unnecessary *onXyzChanged* events coming to the QML side.

Eliminating unnecessary value updates in main flight display.

---

src/comm/LinkManager.cc
src/comm/MockLink.cc

No need to do the Preferences dance in debug builds. Also fixed a crashing bug in mock like with null termination.

Mock link automatically added to Connect

---

QGCCommon.pri
src/QGCFileDialog.cc
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/flightdisplay/FlightDisplay.qml
src/ui/flightdisplay/QGCFlightDisplay.h
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

Removed *Chevron Buttons* from Main Tool bar for *__Mobile__* builds. Instead, a mobile style *hamburger* menu button is used.
I removed the old *hamburger* button from the flight display as it is no longer needed. It was used to access its context menu. You can now access it either though the tool bar (for mobile builds) or right-clicking anywhere on the screen for desktop builds.
The menu may contain a context sub-menu based on the current view. In the example below, it shows the *Flight View Options* when the current view is the *Flight View*.
I made the (mobile) menu *Checkable* as this was the idea behind the *Chevron* buttons (indicating the current view through a highlighted color). I'm not sure this is needed. I'm open to suggestions.
If you select it, the context menu for the …

Mobile Menu Bar

---

src/FactSystem/ParameterLoader.cc
src/QmlControls/ParameterEditor.qml
src/VehicleSetup/SetupParameterEditor.qml
src/comm/MockLink.cc

- Fixes Issue #1507 providing the ability to cancel a parameter change
- Much better perf since not all params are shown at once
- Much more tablet friendly UI
Screen shots from Galaxy Tab...
Groups are on the left. Select a group to show params for the group:
Click on a parameter opens a panel for editing with all meta data shown:
Note 1: This Qml generates a binding loop error debug output which I believe is incorrect. I'm still looking at it. It doesn't prevent it from working.
Note 2: As I was typing this up I realized that I didn't put in reset to default and the rc map stuff in the new ui. I'll do that in a separate pull.

New parameter editor

---

QGCApplication.pro
qgroundcontrol.qrc
src/QGCApplication.cc
src/ViewWidgets/CustomCommandWidget.cc
src/ViewWidgets/CustomCommandWidget.h
src/ViewWidgets/CustomCommandWidget.qml
src/ViewWidgets/CustomCommandWidgetController.cc
src/ViewWidgets/CustomCommandWidgetController.h
src/ui/MainWindow.cc
src/ui/MainWindow.h

This allows you to build your own custom command widgets using Qml. You can access the new widgets from the menu.
You must be connected to a vehicle to get this:
Here is the example file running:
If youre Qml has errors, it shows up in the widget like this:
Here is the example Qml file from the wiki:
```javascript
// This is an example Custom Command Qml file. You have full access to the entire Qml language
// for creating any user interface you like. From the ui you can affect the following changes
// with respect to your vehicle:
//    1) Sending COMMAND_LONG commands out over mavlink using QGCButton control
//    2) Modifying parameters
//
// When developing custom Qml file implementations. You must restart QGroundControl to pick up
// the changes. You need to do this even if you …
```

New Custom Command Widget

---

src/ui/qmlcommon/QGCMapBackground.qml

Small, incremental work on the new Mission Plan View. You can now add a new waypoint by double-clicking on a point on the map.
Waiting to sort out how we will handle these as well as how to edit individual waypoints (list view).

Adding the ability to add a waypoint.

---

QGCApplication.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/AutoPilotPlugins/PX4/AirframeComponentController.h
src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml
src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml
src/AutoPilotPlugins/PX4/RadioComponentSummary.qml
src/AutoPilotPlugins/PX4/SafetyComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml
src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml
src/FactSystem/Fact.h
src/FactSystem/FactBinder.cc
src/FactSystem/FactBinder.h
src/FactSystem/FactControls/FactPanel.qml
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/FactControls/FactPanelController.h
src/FactSystem/FactControls/qmldir
src/FactSystem/FactSystem.cc
src/FactSystem/ParameterLoader.cc
src/QGCApplication.cc
src/QGCApplication.h

This is a much better (and somewhat more complicated) approach to handling missing facts in QGC without having to shutdown the app immediately. You still end up with unusable portions of the ui but it should at least provide you with the ability to orderly retrieve your vehicle and disconnect.
The main concept is to isolate the havoc that a missing parameter causes to one or more subsections of the ui. In order to do this I introduce the concept of a FactPanel in qml. A FactPanel will catch missing parameters, notify the user and disable it's ui. Here is an example of using a FactPanel when you do not need a C++ controller to go along with it:
```javascript
FactPanel {
Fact { 
id: sysIdFact
name: "MAV_SYS_ID"
onFactMissing: showMissingFactOverlay(name) 
}
...
}
```
So instead of using a …

Much better handling of missing parameters

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/AutoPilotPlugins/PX4/AirframeComponentController.h
src/QmlControls/ViewWithDialog.qml
src/QmlControls/qmldir

This fixes a number of bugs in airframe config:
Issue #1543 - You can now scroll the config screen if it doesn't fit
Issue #1539  - Non-standard airframe configs are now supported. It will detect this and show you:
It also allows you to reset you airframe config if you want to switch from non-standard to standard using the Reset button.
The right hand dialog overlay is implemented using a new standard control I implemented: ViewWithDialog. This control allows you to specify the view you want to show and then pop up those right hand dialog overlay thingies as needed. Both the view an dialog are FactPanel's. It's not quite ready for general use. I'm going to convert more stuff over to it like Sensor Cal to get rotations before/after. Also the Parameter Editor which already uses this style …

Airframe config

---

src/comm/LinkManager.cc

The LinkManager keeps checking to see when new (serial) interfaces show up. When that happens, it checks if it's something that can be used (either a PX4 or a 3DR Radio Modem) and automatically creates a link configuration for it. At the same time, if it sees that a previously automatic link is no longer present, it removes it from the list.
This fix prevents removing a link configuration if an active link is still using it. Once the active link goes down, the configuration will then be properly disposed of.
This fixes the crash reported in #1548 as the code was trying to copy the active link's link configuration and, depending on timing, it could have already been deleted.
Note that this fixes the crash but just moves the problem some place else. Once you reboot the PX4, the link is …

Don't delete link configuration if there is still an active link.

---

src/FactSystem/ParameterLoader.cc

Was causing unnecessary read re-requests to get sent out. Fix for Issue #1555

Param read timeout too short

---

QGCApplication.pro
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/AutoPilotPlugins/PX4/AirframeComponentController.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h
src/FactSystem/FactControls/FactPanel.qml
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/FactControls/FactPanelController.h
src/QGCApplication.cc
src/QmlControls/QGCView.qml
src/QmlControls/QGCViewDialog.qml
src/QmlControls/QGCViewPanel.qml
src/VehicleSetup/FirmwareUpgrade.qml

There are quite a few changes in here which have been discussed in various forums to improve usability. Instead of including a massive amount of screens shots I'll let folks just run it and send comments.
While testing this I found a number of things which used to work but which are now broken with the latest firmware:
- I calibrated a board with an external mag but CAL_MAG1_ROT always came back as -1 not allowing me to set external mag rotation.
- Cancel is broken during mag cal. If you cancel during the rotate detection step, it will emit the calibration cancelled message and continue on and still do the calibration step. 
- The mag cal step which tries to detect rotation before calibrating a side seems flaky. I could get it to detect rotation maybe 50% of the time. For example if my …

Sensor cal usability

---

src/QmlControls/SubMenuButton.qml
src/VehicleSetup/SetupView.ui

This prevents the indicator from overlapping the “Flight Modes” text

Tweak SetupButton width

---

src/QmlControls/MavManager.cc
src/QmlControls/MavManager.h
src/uas/UAS.cc
src/uas/UASInterface.h
src/ui/toolbar/MainToolBar.qml

Adding battery consumption to the toolbar.
It doesn't seem to be working though. I haven't had the time to dig too deep but even with full throttle, the rate of increase didn't change from that shown at idle (disarmed and motors off). After a minute or so of full throttle (theoretically a good 2A discharge), it still shows around 100mA.
P.S. Throttle response seems to be completely out of whack. Again, I didn't have time to dig further but at first only three motors (out of six) started and moving the throttle all the way up did nothing. After quite a while, all of the sudden, all motors started at full throttle scaring the crap out of me. All this in *Manual* mode.
P.P.S The error messages are related to the radio as I was messing with it and it kept connecting and disconnecting before I …

Adding Battery Consumption to the tool bar.

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/QmlControls/QGCView.qml

Showing a new dialog while the animation from a previous hide was still playing would lead to the panel still being overlaid.
Also fixed some typos, and changed some naming.

Animation fix

---

src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/qgcunittest/PX4RCCalibrationTest.cc
src/ui/px4_configuration/PX4RCCalibration.cc
src/ui/px4_configuration/PX4RCCalibration.h

This is the first phase of Acro switch support. It just prevents QGC from doing the wrong thing if the acro switch is configured. Support for setting macro switch in Flight Mode setup is not yet supported.

Validate against Acro switch setting

---

src/QGCConfig.h

Stable 2.4 is in separate branch and release. Switch mainline to new 2.5 Development version.

Switch to Development 2.5

---

deploy/ubuntu_ppa

I updated the Ubuntu ppa to Stable 2.4 by doing this. It could be turned into a proper script if we get the version out somehow and properly handle the paths.
I still can't register for the wiki (the captcha doesn't work?). Can you readd the instructions?

basic ubuntu ppa instructions

---

QGCCommon.pri

This will allow us to capture usable crash dumps

Debug information in windows release builds

---

src/QGCApplication.cc

This will help with debugging released build problems.

Generate qtlogging.ini in release builds as well

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/AutoPilotPlugins/PX4/FlightModesComponentController.h

Support for the Acro switch in Flight Mode setup. Given the fact that whenever I go into flight modes the various switch combinations make my head hurt this could use some testing from someone other than me. 
The Acro switch works just like PostCtl and Loiter switches in that:
- It can be assigned to the same channel as the mode switch
- It can be assigned to a completely separate channel
- It can be assigned to the same channel as the PostCtl and/or Loiter switches

Acro switch support

---

src/comm/UDPLink.cc

A socket must be *closed* in order for it to be properly released by the kernel. Otherwise, it would only be released when the process exits. The call to close however, must be done in the same thread that created the socket.
I've also changed the thread priority to *Normal* as I see no reason for it to be created in *HighPriority*. It's just wasted context switches when IO, in relationship to everything else is peanuts in comparison.

Move the socket close to the proper thread.

---

QGCInstaller.pri

Daily builds include groundcontrol.pdb in installer to aid in debugging user crashes.

Include .pdb in windows installer

---

src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/LinkManager.cc

This will allow users to easily update their AeroCore boards rather than building the code themselves.
The link manager update just avoids some confusion.  When an AeroCore board is plugged in, it will show "AeroCore on /dev/..." rather than "Pixhawk on /dev/...".

Add AeroCore support to firmware upgrade utility and link manager.

---

QGCExternalLibs.pri
src/comm/UDPLink.cc
src/comm/UDPLink.h

This will allow a client to find QGC without knowing its IP address. It greatly simplifies the configuration of UDP links.
For now it's only enabled for Mac OS and iOS (they both have support built in). Linux is next once I figure out how to deal with a system that doesn't have Avahi installed.
It is possible to use it for Windows but it would require installing the Bonjour SDK for Windows in order to build and to have the Bonjour service installed for it to run. Too much work for an experimental feature.
To use it, just browse for a service called: *_qgroundcontrol._udp*

Enabling Zeroconf (Bonjour) on Mac OS/iOS

---

src/comm/LinkManager.cc

Following #1629, adding code to make sure the newly found *Vendor ID 9900* is really a PX4.

Adding check for a PX4.

---

src/AutoPilotPlugins/PX4/RadioComponent.qml
src/AutoPilotPlugins/PX4/RadioComponentController.cc
src/AutoPilotPlugins/PX4/RadioComponentController.h
src/uas/UAS.cc
src/uas/UASInterface.h

Also:
- Prompts to reset trims to zero prior to calibrate
- Turned of radio check for now since it prevents spectrum bind. Too much change prior to Stable release to fix this now. Issue #1652.
@LorenzMeier I don't have much time today. I've done some amount of testing and it looks to be working. Can you test as well and then I'll start building Stable. I believe I have the list of things done.

Add Copy Trims support

---

qgroundcontrol.qrc
src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/MavManager.cc
src/QmlControls/MavManager.h
src/uas/UASMessageHandler.cc
src/uas/UASMessageHandler.h
src/ui/flightdisplay/FlightDisplay.qml
src/ui/qmlcommon/QGCHudMessage.qml
src/ui/qmlcommon/qmldir
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

Added a message area to the *Main Flight Display* (HUD), showing the latest error message (if any). The message will stay there for 30 seconds, after which, it fades out. If a new message comes in, it replaces the old one and the timeout is reset. Clicking on the message makes it go away.
This is an attempt to ameliorate the issue brought up by #1586.
In the process, I moved the message handling out of the Main Toolbar code and into the MavManager, which is shared by all QML elements. The original message icon in the Main Toolbar and its functionality are unchanged.

Added latest error message to Main Flight Display

---

src/AutoPilotPlugins/PX4/RadioComponent.qml

- Only show clear trim dialog once
- Remove animation from bars
- Move additional setup down with bar
@LorenzMeier Can you try this one out?

Usability fixes:

---

src/audio/QGCAudioWorker.cpp

A few more text to speech fixes. I was a bit entertained having QGC telling me the system *ID* (the Latin version as in ego/super-ego) was mismatched. That would get Freud quite confused...

Adding a few more speech fixes.

---

src/VehicleSetup/FirmwareUpgradeController.cc

I originally didn't realize we were able to use the cleaner versions of the AWS links.  This pull just brings the links in line with the format of other AWS links.

Update firmware upgrade controller links for AeroCore firmware

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/AirframeComponent.cc
src/AutoPilotPlugins/PX4/AirframeComponentAirframes.cc
src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/PowerComponent.cc
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/RadioComponent.cc
src/AutoPilotPlugins/PX4/SafetyComponent.cc
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/QmlControls/QGCButton.qml
src/QmlControls/QGCComboBox.qml
src/QmlControls/SubMenuButton.qml
src/VehicleSetup/SetupView.qml
src/ui/mapdisplay/MapDisplay.qml
src/ui/qmlcommon/QGCAttitudeInstrument.qml
src/ui/qmlcommon/QGCAttitudeWidget.qml
src/ui/qmlcommon/QGCCompass.qml
src/ui/qmlcommon/QGCCompassInstrument.qml
src/ui/qmlcommon/QGCMapBackground.qml
src/ui/toolbar/MainToolBar.qml

This is a cosmetic but rather large change. It can wait.
Both QML files and Image resources are all in the same QRC root (qml). That causes quite a bit of clutter when using Qt Creator as you have to browse through a zillion images in order to find the QML file you are looking for.

Moving image resources to their own QRC path.

---

src/uas/UAS.cc

I was looking through the handling here and found that joystick updates only happen if manual mode is set. Might this be a bug or are the other modes unsupported/untested ATM?

Send MAVLink message for all joystick modes

---

src/FactSystem/FactMetaData.cc

Should help usability for users not being able to find custom parameters they add which don't have meta data. Also will help with catching missing meta data from standard builds.

Force Default Group to top of parameter editor list

---

src/comm/UDPLink.cc
src/comm/UDPLink.h

For whatever reason, UDP connections would some times stop working. What I've found was that the ```readReady()``` signal would stop being called (outgoing datagrams were being sent just fine though). When the Pixhawk/Companion computer link was set to 57600, this would happen rarely but when the speed was set to 900k, the problem would show up quite often. In the case of the Android build, the issue was consistent at any speed and quite soon. As far as I could tell, Qt was getting stuck on a ```select()``` call and could not recover.
The fix was to stop using the ```readReady()``` signal and running my own loop. In the process, I also moved the *writes* to the link thread (it used to be in the MavLinkProtocol thread).
In addition, I've changed the addressing to ```AnyIPv4``` instead of …

Fixing Qt event loop issue where UDP readReady signal would not work.

---

src/comm/LinkManager.cc
src/ui/QGCCommConfiguration.cc
src/ui/QGCLinkConfiguration.cc
src/ui/QGCUDPLinkConfiguration.cc

This is in response to the ongoing discussion in #1681. Until we come up with a solution on how to deal with the *Connect* and *Disconnect* buttons in the main tool bar. In the mean time, I've added code that automatically creates a *Default UDP Link*. QGC will not (yet) automatically connect this link. It just automatically adds to the list. This way you don't need to configure a new link in order to use UDP. It will be already added for you to the list. When you click the *Connect* button, it will be there. This is specially useful for mobile devices as the link management UI is still QtWidget based and it sucks on mobile devices.
The next step will be a more fundamental change in the *Connect*/*Disconnect* semantics, which we need to further discuss and come up with a proper solution.

Automatic UDP Link Configuration

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/PX4ParameterLoader.cc
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactControls/FactTextField.qml
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/QGCApplication.cc
src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCView.qml
src/QmlControls/QGroundControl.Controls.qmldir

Parameter values are now validated against meta data. If the string you enter cannot be converted to the appropriately typed number and/or the value fails validation against the meta data you will get the parameter editor dialog popping up for you to fix it. There is also a "Force" option to save anyway even though it fails validation.
If you are using a FactTextField inside a QGCView this all works automagically for you. Also Parameter Editor implementation is changed to support this.
Here is an example of what it looks like from Safety Config:

Parameter validation

---

src/comm/LinkInterface.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/comm/TCPLink.cc
src/comm/UDPLink.cc
src/comm/XbeeLink.cpp

This is needed in order to use radios on Android. Since serial link on android is implemented as a C++/Java combination all code must run on main thread. The secondary thread for serial ports was not really needed anyway since QSerialPort supports a signal based read/write mechanism.
NOTE: This does not yet make radios works on Android. That is a second phase of debugging hell to go through.

Serial link runs on main thread

---

src/main.cc

This is needed for firmware upgrade which is not part of mobile

Remove QSerialPortInfo from mobile build

---

src/AutoPilotPlugins/PX4/AirframeComponentAirframes.cc

Switches Bixler to Generic AERT and adds Generic AETR aiframes. Requires corresponding firmware pull.

Generic AERT and AETR airframe support

---

src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h

PWM RSSI has too much jitter. This is an attempt at low pass filtering it to smooth it out.
@LorenzMeier Could you please validate this? It looks fine to me but I would like your opinion (maybe you want to handle this on the Firmware side?)
This is a sample of incoming data, low pass filtered value and displayed value:
```
100 100     100
100 100     100
100 100     100
99 99.9    100
100 99.91   100
100 99.919  100
100 99.9271 100
100 99.9344 100
100 99.9409 100
100 99.9468 100
99 99.8522 100
100 99.8669 100
100 99.8802 100
100 99.8922 100
100 99.903  100
100 99.9127 100
100 99.9214 100
100 99.9293 100
100 99.9363 100
100 99.9427 100
100 99.9484 100
99 99.8536 100
100 99.8682 100
100 99.8814 100
100 99.8933 100
100 99.9039 100
100 99.9135 100
100 99.9222 100
```

Low pass filter on RC RSSI

---

src/ui/toolbar/MainToolBar.qml

As this info shows  consumed energy, its unit should be mAh instead of mA (which is a current)

fixed spelling error in toolbar battery consumed

---

src/AutoPilotPlugins/PX4/PowerComponent.qml

Added some explanation and a warning on the use of *Voltage Drop* as discussed on issue #1701. I'm also now showing the computed compensated minimum voltage under load.

Warning and explanation for voltage drop.

---

src/ui/MainWindow.cc
src/ui/MainWindow.ui

The combination of using a dynamic menu entry string (Show / Hide Status Bar) IN COMBINATION with a tick is very confusing. It should only use one of both.

"Show Status Bar" menu entry more sensible.

---

.gitignore
QGCApplication.pro
QGCInstaller.pri
QGCSetup.pri
src/QGCApplication.cc
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoStreaming.pri
src/main.cc
tools/osxrelocator.py
tools/prepare_gstreamer_framework.sh

This PR (attempts) to bundle the necessary gstreamer binaries into the (Mac OS) app bundle. I've created an installer helper script that handles copying the framework, pruning unused stuff, relocating the dylibs so they can be loaded from within the bundle, etc.
I'm not adding the gstreamer distribution to the GitHub repo. I didn't think it would make sense. Instead, it relies on a system installed framework. This is only relevant to the build machine producing a release bundle. Local builds are not affected by this (they all use the system installed framework). Again, if the build system doesn't find the (system installed) gstreamer libraries, it simply ignores it and builds normally with no video streaming support.
@DonLakeFlyer Note that I could not, for whatever reason build an …

Initial setup for Mac Installer (Video Steaming)

---

src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCTextField.qml

- Escape key - Closes editor dialog
- Enter key - Saves editor dialog
- Moving focus into a QGCTextField will now select all text automatically
- Focus automatically placed into text field in editor dialog
This should make parameter editing way faster. So far Esc/Enter key support only in parameter editor dialog. I'll look at transferring that to other dialogs as well.

Parameter editor keys

---

src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.cc

Do not merge.
missing submodule pull request : https://github.com/mavlink/mavlink/pull/372
Added MAV_TYPE_VTOL_TILTROTOR for vtol tilt-rotor airspeed sensor calibration.

VTOL tilt-rotor airspeed sensor

---

src/VehicleSetup/PX4FirmwareUpgradeThread.cc

Hopefully this will fix Issue #1718. Delay was in there for 3DR Radio but it seems to work fine without it. Delay was putting thing right on the edge of the bootloader timeout. So if you were unlucky you could miss the bootloader going by.

Remove delay waiting for bootloader

---

QGCApplication.pro
src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/LogReplayLink.cc
src/comm/LogReplayLink.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h
src/ui/LogReplayLinkConfigurationWidget.cc
src/ui/LogReplayLinkConfigurationWidget.h
src/ui/LogReplayLinkConfigurationWidget.ui
src/ui/MainWindow.cc
src/ui/QGCCommConfiguration.cc
src/ui/QGCLinkConfiguration.cc
src/ui/QGCMAVLinkLogPlayer.cc
src/ui/QGCMAVLinkLogPlayer.h
src/ui/QGCMAVLinkLogPlayer.ui

This turns log replay into a custom communicaiton link. You still use the log replay status bar for replay. When you are done replaying, just Disconnect.
The reason for this change is that it makes more of the QGC ui work during replay, like the toolbar items. Log Replay itself as well as the Analyze tab is just as flaky as it was before. This just helps a little bit.

Convert Log Replay to Link

---

QGCApplication.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/AirframeComponentAirframes.cc
src/AutoPilotPlugins/PX4/AirframeComponentAirframes.h
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml
src/AutoPilotPlugins/PX4/PX4AirframeLoader.cc
src/AutoPilotPlugins/PX4/PX4AirframeLoader.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/VehicleSetup/FirmwareImage.cc

This adds airframe meta info handling from Firmware, which auto-exports all available configurations:

Airframe meta information

---

src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/AirframeComponentController.cc

This fixes a couple of usability issues with airframe config where things had to be done in a certain order and things that intuitively are expected (like clicking on an icon to select) didn't work.
I also fixed timing / race issues with param handling in the process and tested the result quite intensively successfully. When this PR is in its probably a good time to cut a new stable.

Airframeconfig usability fix

---

src/VehicleSetup/PX4FirmwareUpgradeThread.cc

Unfortunately I couldn't add the other boards as I don't know their serial port description.

Added port name matching fallback for detecting the Pixhawk FMUv2 on USB

---

src/AutoPilotPlugins/PX4/RadioComponent.cc

This trigger turned out to not work all the time.
@LorenzMeier Could you give this a test. I don't have a radio. Also still think it would be worth considering setting attitude control mapping parameter defaults to 0 to force a radio cal on new flash or param reset.

Remove MIN/MAX/TRIM as cal trigger

---

src/FactSystem/ParameterLoader.cc
src/QGCApplication.cc
src/QGCApplication.h
src/QGCQmlWidgetHolder.cpp
src/QGCQmlWidgetHolder.h
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

This is step 1 of the following changes:
1-Completed in this pull) After parameters finish loading (whether success or fail) show all mavlink error messages to the user in a modeless ui.
2-Coming soon) After that has been done, show subsequent mavlink error messages to the user in the same modeless ui. Do this on some sort of delay in between each message to collect as many messages together into a single display to the user as possible.
The goal of this is two-fold:
- Make mavlink error messages more visible to the user since these severity errors need to be acted upon prior to or during flight.
- Mavlink error messages at boot tend to indicate why parameters are not fully loading as well. So this provides a better indicator as to why that might be happening.
This is what the modeless ui …

Show vehicle errors after parameters load

---

src/QmlControls/ScreenTools.qml
src/QmlControls/ScreenToolsController.cc
src/QmlControls/ScreenToolsController.h

Windows builds should have a font size about the same as OSX and Ubuntu now.

Bump font size on Windows

---

src/ui/MainWindow.cc
src/ui/MainWindow.h

On Windows:
- Close window with active connections
- Click yes, to close all connections
- Boom!

Queue delayed window close if open connections

---

src/FactSystem/ParameterLoader.cc
src/uas/UASMessageHandler.cc
src/uas/UASMessageHandler.h
src/ui/toolbar/MainToolBar.cc
src/ui/toolbar/MainToolBar.h
src/ui/toolbar/MainToolBar.qml

- New modeless mechanism now queues messages if a message is alread being displayed
- Messages are batched in .5 second increments
- Once initial error message list is displayed after parameter load any further mavlink error messages are displayed using modeless mechanism
Also fixed Issue #1781

Modeless messages

---

src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/ScreenToolsController.h

Putting this on command line causes mobile ui to the displayed on non-mobile devices. Used for testing.

--fake-mobile command line support

---

src/VehicleSetup/SetupView.cc
src/VehicleSetup/VehicleComponent.h
src/comm/QGCFlightGearLink.cc
src/comm/QGCHilLink.h
src/uas/UAS.cc
src/ui/linechart/LinechartPlot.cc
src/ui/linechart/LinechartWidget.cc

We are primarily trying to harden QGC for Windows systems and catch major crashes that have lingered in the win32 environment for a while. 
This first set of patches mostly addresses initial issues I encountered while building with MSVC 2013 as well as the following bugs:
- QGCFlightGearLink: fix crash when clicking Stop in HIL simulator panel due to thread-unsafe object access
- LinechartWidget: fix unable to turn off "Ground Time" checkbox in analysis view
- TimeSeriesData: decrease busy memory management of plotted data in analysis view
We're using builds of QGC with debug symbols in the release configuration to catch and fix crashing bugs as they pop up, so expect additional patches in the future.

QGC bugfixes 

---

.gitignore
QGCApplication.pro
deploy/ubuntu_ppa
git_version.pri
qgroundcontrol.pro
src/QGCApplication.cc
src/QGCConfig.h
src/comm/MAVLinkProtocol.cc
src/git_version.h

This PR uses `git describe` to set the QGC version.
For example the current version displayed for this branch is
v2.6.0-50-gb4f941e
Which means v2.6.0 + 50 commits and git sha b4f941e. A stable version (directly on a tag) would only display the version (eg v2.6.1)
When it's time for a new stable release just drop a new tag. No need to update QGCConfig.h
I'll likely need to tweak this to work on windows.

set QGC version from git

---

src/ui/uas/UASView.cc
src/ui/uas/UASView.h

This fixes a long standing error with the global position display in UASview, where Lat and Lon were mixed up.

fix global position display in UAS widget

---

QGCApplication.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.cc
src/FlightDisplay/FlightDisplayView.h
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayWidget.cc
src/FlightDisplay/FlightDisplayWidget.h
src/FlightDisplay/FlightDisplayWidget.qml
src/FlightMap/FlightMap.qml
src/FlightMap/Widgets/QGCAttitudeHUD.qml
src/FlightMap/Widgets/QGCAttitudeWidget.qml
src/FlightMap/Widgets/QGCCompassHUD.qml
src/FlightMap/Widgets/QGCCompassWidget.qml
src/FlightMap/Widgets/QGCCurrentAltitude.qml
src/FlightMap/Widgets/QGCCurrentSpeed.qml
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/toolbar/MainToolBar.cc

- Separated view and widget into separate controls
- Removed scale display and slider from map (trial to see how +/- works). Need to free up real estate so I can put list of mission items across bottom of map
- Replace with +/- button to save real estate
- Add Options button instead of right click to be more tablet friendly

Separated Flight map into View and Widget

---

qgroundcontrol.qrc
src/FlightMap/FlightMap.qml
src/FlightMap/Images/airplaneOpaque.svg
src/FlightMap/Images/airplaneOutline.svg
src/FlightMap/MapItems/VehicleMapItem.qml

There are two new graphics for the current vehicle position. One for *street* map types and another for *satellite* map types. The former is just a see-through outline and the later is opaque for better contrast.

Handle different vehicle position graphics based on the current map.

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/QGCLoggingCategory.h

Set JoystickValuesLog=true in your qtlogging.ini file to get the values output which are being sent from the joystick to the UAS setpoint method.

Fix center stick zero throttle, add JoystickValuesLog

---

src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/FlightModesComponent.qml
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/RadioComponent.cc
src/AutoPilotPlugins/PX4/RadioComponent.qml
src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/JoystickConfig.qml
src/VehicleSetup/JoystickConfigController.cc
src/VehicleSetup/JoystickConfigController.h
src/VehicleSetup/SetupView.qml

Changes to follow these rules:
COM_RC_IN_MODE = 2
- All config screen enabled and run as if there was normal RC connected
COM_RC_IN_MODE = 1
- Radio Config disabled
- Flight Mode Config disabled
As well as these changes:
- Change Simulate RC joystick mode to Normal
- Disable “Enabled” check box if COM_RC_IN_MODE > 1
- Move enabled to first setting
- Fixed bugs with active joystick changing in config
- Moved Joystick enabled save setting to Vehicle instead of globally on joystick

Joystick fixes

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/VehicleSetup/JoystickConfigController.cc

When on Joystick config page:
- Not calibrating: If joystick is enabled, joystick messages should
continue to go to vehicle

Joystick message fixes

---

src/Vehicle/Vehicle.cc

The threshold was set to 1 degree, which was causing the display to jump a bit.
While at it, I've also changed the airspeed jitter threshold to make it consistent with ground speed.

Decreasing the angle jitter threshold for row, pitch and yaw.

---

.travis.yml
QGCInstaller.pri
src/QGCApplication.cc

On travis-ci linux the unit tests assert because QStandardPaths::DocumentsLocation is `/home/travis/Documents` which doesn't exist. Can we just remove the assert?
`documentsDir.mkpath(_defaultSavedFileDirectoryName)` will create the parent directory if it's missing.
QDir documentsDir(documentsLocation);
//Q_ASSERT(documentsDir.exists());
bool pathCreated = documentsDir.mkpath(_defaultSavedFileDirectoryName);

fix linux unittests failure

---

src/QGCApplication.cc
src/QGCApplication.h
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui

The file menu now has a menu item which says: "Use new mission editor (reboot required)". This allows you to switch globally between the new and old mission editor. After you change the settings you must exit and reboot for it to take affect. If you don't reboot, strange things will happen in the future. Plan will now take you the the right place, based on the setting of this swich.
The reason for this is that I'm about to work on the new Mission Item backend. It will not be able to coexist with the old waypoint manager. It's an either/or selection. So leave this alone to continue using the existing code (which works). Check it to use the new code from top to bottom (which is not fully implemented yet).

Add switch for using old/new mission editor

---

.gitignore
QGCApplication.pro
QGCSetup.pri
libs/qtandroidserialport/src/qserialportinfo_android.cpp
src/QGCApplication.cc
src/Vehicle/Vehicle.cc
src/VideoStreaming/README.md
src/VideoStreaming/VideoStreaming.cc
src/VideoStreaming/VideoStreaming.h
src/VideoStreaming/VideoStreaming.pri
src/VideoStreaming/gstqtvideosink/gstqtvideosinkplugin.cpp

Video on Android is now fully functional.
It took quite a bit of trial an error to figure out the used plugins so I could link them statically but the work was worthwhile as it will be the same for iOS.
Sorry for the messy commit but there were so many changes in between that I got way too out of sync and I completely botched the merge/rebase in #1849. Started it all from scratch with this one.

Enable Android Video Streaming

---

src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/ScreenTools.qml
src/QmlControls/ScreenToolsController.cc
src/QmlControls/ScreenToolsController.h

This allows for testing issues found on high dpi screen without needing a high dpi screen. it does this by doubling the font sizes:

Add --test-high-dpi command line option

---

QGCApplication.pro
src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/FirmwarePluginManager.cc
src/FirmwarePlugin/Generic/GenericFirmwarePlugin.cc
src/FirmwarePlugin/Generic/GenericFirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/QGCApplication.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc

- Added new new FirmwarePlugin::adjustMavlinkMessage support. This allows the plugin to take a whack at modifying the mavlink message on the way in and out. This is used to to adjust for protocol implementation differences aross firmware stacks.
- APM firmware plugin using the above to adjust for the way it handles parameter values
- Remove APM parameter hack code from base code since firmware plugin handles this now
- adjustMavlinkMessage will also be the way we handle the issues with APM stack mavlink severity changes: https://github.com/diydrones/apm_planner/issues/788

Added APM Firmware Plugin

---

src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/MissionItem.cc
src/MissionItem.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h

Also understand the concept of missions which cannot be edited. Only a subset of the possible mission items are supported for visual editing. If the mission can not be edited, you can still send it to the vehicle or save it to a file. This way the UI supports the most common set of mission actions/settings and then loading from a file supports everything possible.

Support load/save

---

QGCApplication.pro
src/HomePositionManager.cc
src/HomePositionManager.h
src/MissionEditor/MissionEditor.qml
src/QGCApplication.cc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h
src/comm/QGCFlightGearLink.cc
src/comm/QGCXPlaneLink.cc
src/uas/UAS.cc
src/ui/MainWindow.cc

New Mission Editor now has a Home Position Manager which is availble from the Tools menu.This allows you to save multiple named home positions. This is handy to save multiple flying locations that you can then use as starting points to create missions from. Selecting a home position from the combo will take you there on the map.

Home position manager

---

.appveyor.yml
src/comm/MockLink.cc
src/qgcunittest/MavlinkLogTest.cc

Appveyor windows builds are currently missing unit tests (fails) and s3 deploy.

[WIP] appveyor windows builds

---

src/FlightMap/Images/MapCenter.svg
src/FlightMap/Images/MapHomeTearDrop.svg
src/FlightMap/Images/MapType.svg

@DonLakeFlyer 
These are the icons for the Map Display. Once you have them integrated (so I can see them within their context), I can tweak them.
MapCenter is to select where to center the map (Home or Vehicle)
MapType is to select the type of map display (Satellite, road, terrain, etc.)
MapHomeTearDrop is to denote the home position.
For the vehicle position, I'm assuming we can use the existing airplane icon.
This is a start. I assume there will be quite a few new icons to be created. When you find yourself in need of a new icon for something, just make a purple rectangle (or anything) as a placeholder and I can later replace it.

Icons for Map Display

---

qgroundcontrol.qrc
src/FlightMap/FlightMap.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/DropButton.qml
src/QmlControls/QGroundControl.Controls.qmldir

This adds a new control which is a button which when clicked displays a bubble with content. You can put  whatever you want in the bubble. This is about 80% complete at this point. The hard part is done which is sizing and position the bubble according to the content you put in at as well as making sure the bubble never goes off screen and the little arrow thing is always at the right place.
Usage look like this:
```
DropButton {
id:                     centerMapButton
anchors.rightMargin:    ScreenTools.defaultFontPixelHeight
anchors.right:          mapTypeButton.left
anchors.top:            mapTypeButton.top
dropDirection:          dropDown
label:                  "C"
viewportMargins:        ScreenTools.defaultFontPixelWidth / 2
dropDownComponent: Component {
Row {
spacing: …
```

Add new DropButton control - WIP

---

QGCApplication.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.cc
src/FlightDisplay/FlightDisplayView.h
src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/FlightMap.qml
src/FlightMap/FlightMapSettings.cc
src/FlightMap/FlightMapSettings.h
src/HomePositionManager.cc
src/MissionEditor/MissionEditor.qml
src/QGCApplication.cc
src/QmlControls/DropButton.qml
src/QmlControls/QGCCanvas.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/SettingsDialog.cc
src/ui/SettingsDialog.h
src/ui/SettingsDialog.ui

- FlightMapSettings is the new object which is used to store all map settings with. Access from Qml using QGroundControl.flightMapSettings.
- You now pick the map provider from Settings: Bing, Google, Open Street. Bing is the default since it provides a hybrid map.
- Map type selection implemented in Mission Editor and Fly view. You now just pick Street, Satetellite and so forth.'
- Add new QGCCanvas control which automatically fixed the repatin problem with Canvas.

More Drop Button, Mission Editor, Map work

---

src/VehicleSetup/PX4FirmwareUpgradeThread.cc

Some clone V2 boards only have descriptions set to "PX4 FMU".

Add another Firmware detect fallback

---

src/CmdLineOptParser.cc
src/CmdLineOptParser.h
src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h
src/QGCApplication.cc
src/main.cc

http://www.qgroundcontrol.org/bugreporting
http://www.qgroundcontrol.org/command_line_options
Also notice that GGC with no command line options will output qtlogging.ini location so you can find that more easily if you want to go that route instead.

Easier command line logging options

---

src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/MissionManagerTest.cc
src/MissionManager/MissionManagerTest.h
src/Vehicle/Vehicle.cc
src/comm/MockLink.cc
src/comm/MockLink.h
src/comm/MockLinkMissionItemHandler.cc
src/comm/MockLinkMissionItemHandler.h

- Fixed bugs found to unit test
This provides a high level of hardening on the write protocol sequence. Should be very resilient to packet loss or bad firmware implementations.
Still have read side of protocol to beat the daylights out of. Pushed this separately since lots of good fixes in here.

MissionManagerTest protocol hardening tests

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/Generic/GenericFirmwarePlugin.cc
src/FirmwarePlugin/Generic/GenericFirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

- APM stack must request data streams at connect
- Added new Vehicle::sendMessageMultiple which will send the same message multiple times with a delay. Used for message you really want to make sure the vehicle gets.
- Added Vehicle::requestDataStream which requests a specific data stream at a specific rate. Uses sendMessageMultiple to make sure it gets to the vehicle.

Apm Stack data stream request

---

src/MissionManager/MissionManager.cc
src/MissionManager/MissionManagerTest.cc
src/MissionManager/MissionManagerTest.h
src/comm/MockLinkMissionItemHandler.cc

- Fixed found bugs in MissionManager
MissionManager is now fully hardened for both the read and write protocol sequences. Only thing left to do is unit test for correct response to unexpected mission messages while state machine is idle. Also need to hook error messages to ui.

MissionManager read hardening unit test

---

.appveyor.yml
QGCCommon.pri

Specify we're using jom in appveyor. Helps to address #1928

Add note to Windows developers to turn off -MP when using jom. 

---

src/QmlControls/ScreenTools.qml

Limit font pixel size to work around OSX El Capitan problem

---

QGCApplication.pro
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePluginManager.cc
src/QGCApplication.cc
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc

APM Flight Stack has different firmware depending on MAV_TYPE. This pull adds support for FirmwarePlugin's to be keyed off of both MAV_AUTOPILOT and MAV_TYPE.

Add support for MAV_TYPE specific FirmwarePlugin

---

src/Vehicle/Vehicle.cc
src/uas/UAS.cc
src/uas/UAS.h
src/ui/toolbar/MainToolBar.qml

This helps to avoid indicating some voltage when in fact we don't know anything.

Battery indication fixes

---

src/QGCApplication.cc
src/comm/MockLink.cc
src/comm/MockLink.h
src/qgcunittest/MavlinkLogTest.cc

Was failing due to incorrectly named MockLinkLogVerbose category which would get past the *Log.debug=false rule. Then it would blow out the log files size limit on AppVeyor.
I hope :)

Log fixes, MavlinkLogTest::_connectLogArm_test

---

src/FlightMap/FlightMap.qml

Pinch zoom doesn’t seem to be working for some reason. Fix for Issue #1956

Zoom buttons back on

---

src/AutoPilotPlugins/PX4/PowerComponent.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/QGCButton.qml
src/QmlControls/QGCCheckBox.qml
src/QmlControls/QGCComboBox.qml
src/QmlControls/QGCRadioButton.qml
src/QmlControls/QGCTextField.qml

- Power Component setup needed a Flickable since it was large than the screen
- Increased the default height of QGCButton, QGCComboBox, QGCCheckBox, QGCRadioButton to make them easier to click.

Tablet usability fixes

---

src/MissionEditor/MissionEditor.qml

This is to toggle off help view when clicking on items on the map and checking the appropriate buttons accordingly.

Missed in conflicted merge

---

src/FactSystem/FactControls/FactTextField.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCViewDialog.qml
src/QmlControls/ScreenTools.qml

- Use numeric virtual keyboard for FactTectField and parameter edtior dialog field
- Close virtual keyboad when QGCViewDialog closes
- Don't do El Capitan hack on Mobile

Mobile virtual keyboard fixes, plus font

---

src/FlightMap/FlightMap.qml

This is the workaround found in the *Places* example code in Qt (as explained in #1963). It should be fixed for 5.5.1 but in the mean time, this works.

Work around for pinch zoom bug in Qt (Qt Location)

---

src/MissionEditor/MissionEditor.cc
src/MissionEditor/MissionEditor.h
src/MissionEditor/MissionEditor.qml
src/Vehicle/Vehicle.cc
src/comm/MockLink.cc
src/comm/MockLink.h

If you are not connected to a Vehicle you get the Offline Home Position Manager which allows you to set up fake home positions. If you are connected to a Vehicle and it has home position lock then it will use that for home position.

Support live home position in Mission Editor

---

qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/QmlControls/ExclusiveGroupItem.qml
src/QmlControls/QGroundControl.Controls.qmldir

This was done to reduce confusion around the fact that you don't really have a home position when you are editing offline. You are only simulating.
- naming changes
- Flying Field positions show up with "F" instead of "H". This is quick hack to differtiate between a live home position and a simulated flying field on.
- Fixed a bunch of button checked/right panel visible state problems. I think they all do the right thing now at the right time.
Just to reiterate what happen once you are connected to vehicle:
- the "F" indicator will go away and change to a real "H" home position indicator
- The Flying Field Manager will no longer be visible, instead you get static display of home position lat/lon/alt

Changed Home Position Manager to Flying Field Manager

---

QGCSetup.pri

I get this error when i build the app in Windows.
> mkdir -p D:\Projects\QGroundControl\debug\platforms
> A subdirectory or file D:\Projects\QGroundControl\debug\platforms already exists.
Error occurred while processing: D:\Projects\QGroundControl\debug\platforms.
jom: D:\Projects\QGroundControl\Makefile.QGCApplication.Debug [debug\qgroundcontrol.exe] Error 1
jom: D:\Projects\QGroundControl\Makefile.QGCApplication [debug] Error 2
jom: D:\Projects\QGroundControl\Makefile [sub-QGCApplication-pro-make_first-ordered] Error 2
14:31:52: The process "C:\Utils\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
> Error while building/deploying project qgroundcontrol (kit: Desktop Qt 5.4.2 MSVC2013 OpenGL 32bit)
When executing step "Make"
It happens because windows version of mkdir have no -p key. …

Fix Windows postbuild error

---

src/QtLocationPlugin/qgeotiledmappingmanagerengineqgc.cpp
src/QtLocationPlugin/qgeotiledmappingmanagerengineqgc.h

Map cacheing for < 5.5.0 was broken and we were using whatever default was provided by QtLocation. Now we're properly creating and configuring a cache manager.
This also solves the weird message output by QtLocation:
```
Plugin uses uninitialized directory for QGeoTileCache which will was deleted during startup
```

Fixing map cache for Qt 5.5.1

---

git_version.pri

The inline build of git_version was using the *default* target SDK, which caused a warning as it didn't match the one used by the project as a whole.

Getting rid of warning on Mac OS

---

qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionEditorController.cc
src/MissionEditor/MissionEditorController.h
src/MissionItem.cc
src/QmlControls/MissionItemEditor.qml
src/ui/toolbar/MainToolBar.qml

- Transitioning from offline to online handled correctly
- Added "AutoSync" capability. Turn it on and the vehicle will be kept in sync automatically with your changes. Turned on by default. You can turn off via Sync Tool. Disabled if vehicle is armed.
- Fix toolbar messages, Issue #2025 
Transition from offline to online:

More editor changes

---

QGCApplication.pro
src/qgcunittest/MainWindowTest.h
src/qgcunittest/UnitTest.cc

I've turned off one of the main window unit tests to work around a strange qml/jscript problem crash. There is an ASSERT in the script interpreter which gets hit. I'm fairly certain that it is only a unit test problem. The way Qml and the script ending cleans up after itself is a bit strange. So when we create main window's more than once in a unit test (without taking down the QApplication) it gets confused.

Unit tests

---

qgroundcontrol.qrc
resources/styles/style-dark.css
src/FlightDisplay/FlightDisplayWidget.cc
src/QGCApplication.cc
src/QmlControls/ScreenToolsController.cc
src/QmlControls/ScreenToolsController.h
src/QmlControls/ScreenToolsFontQuery.qml

For QWidget we will just use the Qt default font sizes. This removes the extra QQuickWidget creation which breaks boot Qml Profiling

Remove font query from QWidget side of code

---

android/AndroidManifest.xml

@DonLakeFlyer @LorenzMeier 
Opening this to provide basic instructions for updating the google play app.
To update the android app on google play the `versionCode` in android/AndroidManifest.xml must be incremented. The versionName is displayed, but versionCode is what android uses to update. I'll start committing this change everytime I update the build so that it's easier for others.
android:versionName="2.7.1-548-g9417909" android:versionCode="6"
The app must be built in release mode and signed with the keystore `android/android_release.keystore`. I'll send the password.
Once a release apk is built you just login to https://play.google.com/apps/publish and select 'Upload new APK' under APK. I'm currently only uploading to the beta channel, although I've been calling it alpha.
Ideally …

update android versionCode and google play instructions

---

src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h

This fixes rotate images showing up at the wrong time. Fixes Issue #1989

Reset internal state correctly

---

QGCApplication.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/MapItems/MissionItemView.qml
src/FlightMap/qmldir
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionEditorController.cc
src/MissionEditor/MissionEditorController.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManagerTest.cc
src/QGCApplication.cc
src/ui/toolbar/MainToolBar.qml

Plan/Fly views now show mission item indicators exactly the same way. Working my way towards lines in Fly. And also figuring my way through restructuring to consider Plan/Fly merge at some point,

Share item indicator display code between Plan/Fly views

---

README.md

Maintaining these specific instructions for multiple distros is unsustainable and seems to be fairly brittle. I was thinking something like just pointing everyone to the right version of the qt online installer, but I don't want to just delete the Arch and Fedora instructions that others have added.

README.md update Ubuntu instructions for Qt 5.5.1

---

QGCApplication.pro
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionControllerManagerTest.cc
src/MissionManager/MissionControllerManagerTest.h
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionControllerTest.h
src/MissionManager/MissionManagerTest.cc
src/MissionManager/MissionManagerTest.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/qgcunittest/MultiSignalSpy.cc
src/qgcunittest/MultiSignalSpy.h

The MissionController is responsible for providing the data structures for mission items and waypoint lines to the Qml views. Added a basic unit test for it. I'll expand on it more in the future.

Mission controller Unit Test

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Images/compassInstrumentDial.svg
src/FlightMap/Widgets/QGCCompassWidget.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h

I made the *Instrument Panel* vertical to optimize screen real estate.
I've added some basic telemetry data to the panel. For now we have:
* Altitude (WGS84)
* Ground Speed
* Air Speed (Only shows if there is one to show)
* Vertical Speed (Climb Rate)
Once we figure out what else should go there I can add it. These are some possibilities:
* Altitude Above Ground
* Some kind of a timer, possibly started when armed
* Distance from Ground Station (Ground Station needs its own GPS coordinates for this)
While at it, I've added a save/restore setting for *Map Is Main* for the fly view. I've also added a global settings set of functions to QGroundControlQmlGlobal to handle it.

Flight view continue

---

src/comm/MAVLinkProtocol.cc

Reverts mavlink/qgroundcontrol#2125. Pulling this out since it's breaking unit test. No idea why it passed the first time!

Revert "Start logging on heartbeat instead of connect"

---

src/FlightMap/Widgets/QGCArtificialHorizon.qml

This fixes #2135 
The trick to get a circular mask relies on the root entity to be hidden (*visible: false*). The mask element makes only the masked out parts visible. The artificial horizon code had a check to see if it was *visible* and it wouldn't do anything if *hidden*.

Fix artificial horizon (it was stuck)

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/QGCAttitudeWidget.qml
src/FlightMap/Widgets/QGCCompassWidget.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/QGCPitchIndicator.qml
src/QmlControls/DropButton.qml
src/QmlControls/RoundButton.qml
src/QmlControls/ScreenTools.qml
src/ui/MainWindow.qml

* The two main UI elements in the Fly View now scale according to the root window size.
* Adjusted tool button sizes and the size of their borders as well (it was using hardcoded pixels)
* Added a *isTinyScreen* variable to detect little screens (phones primarily)
* Experimenting with differentiating the UI for small screens (long ways before it's usable)

Scaling UI Elements

---

.travis.yml

I've restricted unit tests and singletons in another pull that is coming which creates issues this fatal warnings. I'll fix that up separately after the other pull goes through.

Turn off fatal warnings yet again

---

src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/toolbar/MainToolBar.qml

When you selected via the Menu to go to Fly Mode, the QML
toolbar didn't followed the option, and if you selected
via the menu to go to all the three possible views (setup,
fly and plan) the menu would be all-selected.
This tries to keep consistency of things.

Fix state of buttons (menu, toolbar)

---

src/ui/QGCHilConfiguration.cc
src/ui/QGCHilConfiguration.ui
src/ui/QGCHilFlightGearConfiguration.cc

@DonLakeFlyer This is not a complete cleanup, but I'd like to do that once we figure out HIL in general. Also need to think about simulation on tablets (so users can learn how to use QGC). Right now just making sure the options which are displayed actually work.

Remove Flightgear and JSBSim and only leave options which work

---

src/comm/QGCFlightGearLink.cc

I'm not sure if this changed between FlightGear versions. With the latest one, this is now the path to the executable.

Update path to executable for FlightGear on OSX

---

QGCApplication.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/FlightMap/FlightMapSettings.cc
src/FlightMap/FlightMapSettings.h
src/QGCPalette.cc
src/QGCSettings.cpp
src/QGCSettings.h
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/QmlTest.qml
src/QmlControls/ScreenToolsController.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/GeneralSettings.qml
src/VehicleSetup/SetupView.qml

Started some basic preferences panel. I placed it as one of the buttons in the *Setup View*. I used the original QtWidgets preference panel as a guide. It's far from complete but all the settings there are functional. That is, they do get set and saved.
While at it, I tweaked the palette a bit. The *Warning* text was bright yellow for both themes, which made it almost impossible to read on a full white background (the window color for the *Light* theme). I also replaced a few hardcoded HTML color tags (all setting the text to bright yellow for warning), with the proper warning color set in the system palette.

Started preferences panel

---

src/QmlControls/QGCCheckBox.qml
src/ui/MainWindow.cc

The original code was *centering* the text within the parent. That caused the text to be away from the *checkbox* if the control was sized larger than its contents. I had removed that and now I noticed that on Android, the *checkbox* was out of alignment. Now I realized what this was trying to do.
This is the proper fix. Instead of centering, it's using vertical alignment.

Fix checkbox aligment.

---

src/ui/toolbar/MainToolBarIndicators.qml

It was using wrong size variable (and consequently too big)

Fixed critical icon size.

---

QGCApplication.pro
src/FactSystem/FactSystemTestGeneric.cc
src/FactSystem/FactSystemTestPX4.cc
src/MissionItemTest.cc
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionManagerTest.cc
src/VehicleSetup/SetupViewTest.cc
src/main.cc
src/qgcunittest/FileDialogTest.cc
src/qgcunittest/FileManagerTest.cc
src/qgcunittest/FlightGearTest.cc
src/qgcunittest/GeoTest.cc
src/qgcunittest/LinkManagerTest.cc
src/qgcunittest/MainWindowTest.cc
src/qgcunittest/MavlinkLogTest.cc
src/qgcunittest/MessageBoxTest.cc
src/qgcunittest/PX4RCCalibrationTest.cc
src/qgcunittest/TCPLinkTest.cc
src/qgcunittest/UnitTest.h
src/qgcunittest/UnitTestList.cc

- Centralize unit test declaration list into UnitTestList.cc. This way there is a single place to see what tests are on/off
- Added new --unittest-stress command line option. Works just like --unittest, but it runs the test 20 times in a row, to hopefully catch an intermittent failure.
- Turned MavlinkLogTest back on, since I'll need it for auto connect

Mavlink log test

---

qgroundcontrol.qrc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/MainWindowLeftPanel.qml
src/ui/preferences/MockLink.qml

Preparation for auto-connect having no connect/disconnect buttons. Added debug only MockLink button to Qml Preferences to support mock link start/stop when there is no connect/disconnect button.

Add MockLink Start/Stop to Preferences

---

qgroundcontrol.pro
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.h
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/MAVLinkProtocol.cc
src/comm/MockLink.cc
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/main.cc

- Centralize board detection in QGCSerialPortInfo class. This also hides the android/non-android differences from consumers.
- Change code to use new QGCSerialPortInfo board detection logic.
- Add new requiresUSBMavlinkStart method to LinkInterface. This signals whether the mavlink start shell command is needed.
- Update MAVLinkProtocol to use requiresUSBMavlinkStart appropriately.

Auto-Connect port stuff

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/QmlControls/ParameterEditorDialog.qml

Fix for Issue #2240.
Changed to “f” string conversion from “g” to get better results. BAT_V_CAPACITY now will show as 5200.000. This is because precision is not set for this param and it defaults to 3 past the decimal place.
With this change min/max/default value output string now use same precision formatting as associated parameters. So you get better output in the editor dialog.

Meta data values need string conversion as well

---

src/Joystick/Joystick.cc
src/Vehicle/Vehicle.cc
src/VehicleSetup/JoystickConfig.qml
src/VehicleSetup/JoystickConfigController.cc

The joystick API had two corner cases:
* It did not send anything to the vehicle right after calibration if not in the calibration view
* It did start to send manual control commands to the vehicle during the calibration, even if the joystick was not enabled
There was a third issue which was just a bad user model: The calibration did not enable the joystick by default, which left users stumble over the non-obvious checkbox in the section below. Now its all correct and easy.

Joystick fix: Enable joystick right after calibration & do not send anything to vehicle if not configured

---

src/AutoPilotPlugins/PX4/FlightModesComponent.qml

With COM_RC_IN_MODE the flight mode tab doesn't update QML layout and clips/overlaps in a cluttered fashion. This allows layout updates even when blocked by the modal joystick mode warning pane.

Reflow flight mode layout even when joystick control is enabled

---

src/AutoPilotPlugins/APM/APMAirframeComponent.cc
src/AutoPilotPlugins/PX4/AirframeComponent.cc
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/AutoPilotPlugins/PX4/PowerComponent.cc
src/AutoPilotPlugins/PX4/RadioComponent.cc
src/AutoPilotPlugins/PX4/RadioComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactSystemTestBase.cc
src/FactSystem/ParameterLoader.cc
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/qgcunittest/PX4RCCalibrationTest.cc

With the new translator support the methods need to be clearer as to whether they are referring to the raw or cooked (after translation) values. In general if you are writing C++ code you use rawValue 99% of the time.

Explicit raw/cooked values for Facts

---

src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/ui/toolbar/MainToolBarController.cc
src/ui/toolbar/MainToolBarController.h
src/ui/toolbar/MainToolBarIndicators.qml

The old RSSI value was computed by halving the RSSI figure injected in the mavlink stream. Originally we were halving the injected value, likely based on this statement in the datasheet about RSSI resolution:
Actual input power follows the following curve:
This PR implements accurate input power calculations for telemetry radios that identify themselves matching the [DIYDrones Si1k firmware](https://github.com/Dronecode/SiK/blob/c264c6766ddf778e75fe0b901635ace90b0836f7/Firmware/radio/mavlink.c#L133).

Fix telemetry radio RSSI calculation for SI1000 based modems

---

src/ui/MainWindow.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

Instead of having extended information in the toolbar and making options to show them or not, I've made the indicators clickable. When you click/touch on an indicator, a drop down message box shows up with extended information. Touching anywhere will dismiss the popup.
For now only the RC RSSI and Battery indicators have this feature. I will next add an icon for telemetry RSSI using the same mechanism. Not sure if anything else is needed for GPS. If so, I will add the interfaces to collect lock state and so on.
Telemetry RSSI could be from the SiK radio when that is what is being used but it could also be from the WiFi module. When using a WiFi module however, it could be used for telemetry only or for both telemetry and control. In that case, it would combine RC and Telemetry RSSI in one …

Added toolbar indicators popup (drop down) showing extended information.

---

qgcresources.qrc
src/ui/toolbar/Images/TelemRSSI.svg
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarController.cc
src/ui/toolbar/MainToolBarController.h
src/ui/toolbar/MainToolBarIndicators.qml

Added a Telemetry RSSI indicator to the toolbar.
As the others, when clicking the icon, you will have access to the full batch of Telemetry RSSI status data.
Note that if you are not using a radio, or telemetry RSSI data is not available, the icon will not be displayed at all.

Telemetry RSSI

---

src/comm/LinkManager.cc
src/comm/LinkManager.h
src/ui/preferences/GeneralSettings.qml

The Auto-Connect setup for UDP is now inside a function that used to be only used for Serial Connections. That function has always been disabled for iOS (as it doesn't support serial links). As a result, the UDP initialization was being skipped on iOS.
In addition, I've removed the auto-connect options in the general settings dialog for connections not supported by iOS.

Fix UDP Auto-Connect for iOS.

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/QGCApplication.cc
src/QGCMapPalette.cc
src/QGCMapPalette.h
src/QGCQuickWidget.cc
src/QmlControls/JoystickThumbPad.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UAS.h
src/ui/preferences/GeneralSettings.qml

- Turn on virtual joystick from QML General settings. May at some point move to Joystick config as new joystick type for dropdown. Still considering.
- Virtual joystick is available on both desktop (use with mouse) and mobile (use with thumbs)
- Add new QGCMapPalette which is used for light/dark color palette for different map types

Virtual thumb joystick

---

src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/FlightDisplay/FlightDisplayView.qml
src/QmlControls/QGroundControlQmlGlobal.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/SetupView.qml
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/qgcunittest/UnitTest.cc
src/ui/QGCLinkConfiguration.cc
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

On some OS when you pull the cable on a usb device the port will close, on other OS it will not. Autoconnect was originally implemented assuming the former. Since that assumption is incorrect I needed to restructure auto connect as well as change how disconnecting an inactive vehicle works.
- Port is no longer automatically closed when you pull a usb cable
- Vehicles no longer automatically disconnect after a certain amount of inactivity time
- When QGC detects inactivity on a Vehicle it will show Connection Lost in the toolbar as well as a Disconnect button.
- QGC delays connecting to a discovered port in order to let the boot loader go by. On some OS, boot loader detection is flaky. If you mistakenly connect to the boot loader then auto connect just gets confused. You will now notice …

Change disconnect model for vehicles

---

src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/SerialLink.cc
src/comm/SerialLink.h

#2320, #2311
- Boot Windows QGC, connect direct usb. Works now. Had to add OS specific delay. Windows about 3 seconds slower to connect than OS X.
- Boot QGC, connect direct usb, disconnect, connect again. Works now.
- Connect jmavsim HIL to piaxhawk. Boot QGC, no longe spits out port error from trying to connect to board which HIL is connected to

Autoconnect fixes

---

src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/ui/preferences/LinkSettings.qml

More work done with the link config in QML.
Serial configuration is complete.
Note that I've added an *Auto Connect* settings for link configurations but this is not yet used. More on that once I finish all link configurations.
Fixed an issue with the configuration save function. It was using the total count of configs but it should not count *dynamic* links. You would end up with bogus entries in the settings file.

Serial settings (QML)

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/Joystick/Joystick.cc

This is the corresponding QGC support for https://github.com/PX4/Firmware/pull/3307 in PX4. It enables binding gamepad buttons to discrete mode switch commands.

Enable binding mode commands to joystick buttons

---

qgroundcontrol.pro
src/FactSystem/FactSystemTestBase.cc
src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.qml
src/ui/MainWindowLeftPanel.qml
src/ui/QGCCommConfiguration.cc
src/ui/QGCLinkConfiguration.cc
src/ui/preferences/LinkSettings.qml

Some fixes for Mobile
* Disabled *Mock Links* altogether for Release builds
* Disabled *Log Replay* for mobile. The File Picker does not work on mobile platforms and there is no way to use it.
* Adjusted the size in the *Settings* panel buttons. The default font is too big and there is no way to define a smaller font size for QGCButtons.

Mobile tweaks

---

src/MissionManager/MavCmdInfo.json
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/MissionManager/MissionItemTest.cc
src/MissionManager/MissionItemTest.h

This is a better fix for #2339 
- Acceptance radius move to friendly edit. This way fixed wing user can bump the radius
- Last acceptance radius is used for newer waypoints, just like altitude
- Updated unit test to check for incorrect defaults

Acceptance radius fixes

---

src/MissionManager/MavCmdInfo.json
src/MissionManager/MissionCommands.cc
src/MissionManager/MissionCommands.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/QmlControls/MissionCommandDialog.qml

A standalone coordinate is a mission item which specifies a coordinate, so you can still drag it around. But waypoint lines do not pass through it. ROI mission items are an example of this.

Standalone coordinate support for mission items

---

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/Common/RadioComponentController.cc
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PowerComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/FactSystemTestBase.cc
src/FactSystem/ParameterLoader.cc
src/HomePositionManager.cc
src/MissionManager/MissionController.cc
src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/ParameterEditorController.cc
src/Vehicle/Vehicle.cc
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/JoystickConfigController.cc
src/VehicleSetup/SetupViewTest.cc
src/comm/LinkManager.cc
src/uas/UAS.cc
src/uas/UASMessageHandler.cc

- Changed QGCApplication::showToolbarMessage to showMessage since it isn't in the toolbar any more
- Converted a pile of QGCMessageBox usage to QGCApplication::showMessage
A baby step towards native QML top level window for mobile

Convert QGCMessageBox to QGCApplication::showMessage

---

src/AutoPilotPlugins/Common/RadioComponentController.cc
src/FactSystem/ParameterLoader.cc
src/QGCApplication.cc
src/QGCQuickWidget.cc
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.qml

This removes the last QGCMessageBox usage which is on the mobile code path.
Next pull: Remove QGCMessageBox.h and QGCFileDialog.h/cc from the mobile build and see if anything else breaks.
Next next pull: Fork MainWindow into desktop hybrid model and mobile native model.

More message box removal

---

qgcresources.qrc
resources/ArrowDown.svg
src/FlightMap/MapItems/VehicleMapItem.qml
src/QGCApplication.cc
src/uas/UASMessageHandler.cc
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarController.cc
src/ui/toolbar/MainToolBarController.h
src/ui/toolbar/MainToolBarIndicators.qml

Routing *critical* messages through the MainWindow (QML) instead of through the toolbar. I've also moved the logic that handles queueing up subsequent messages to the MainWindow.
If there are more messages than can be displayed in the dialog, an arrow is shown, indicating you can scroll down to see more messages.
While at it, I've also tweaked the text colors for the system messages (the upper system message dialog) as indicated in #2356.

Message box

---

qgroundcontrol.pro
src/FactSystem/ParameterLoader.cc
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/QGCApplication.cc
src/QGCApplication.h
src/QGCFileDialog.h
src/QGCMessageBox.h
src/QGCQuickWidget.cc
src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorDialog.qml
src/comm/MAVLinkProtocol.cc
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/toolbar/MainToolBarController.cc
src/ui/toolbar/MainToolBarController.h

Mobile build will throw compile error is QGCMessageBox or QGCFileDialog are referenced.

Remove all message and file dialog code from mobile

---

QGCCommon.pri
qgroundcontrol.pro
src/QGCApplication.cc
src/QGCApplication.h
src/comm/BluetoothLink.cc
src/comm/BluetoothLink.h
src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/main.cc
src/ui/preferences/BluetoothSettings.qml

Cleaning up support for Bluetooth
I was having threading issues with Bluetooth and moved the code to the main thread. There is no good reason for it to be on its own thread any way, given that IO happens on a separate thread already and signals are used to tell you when to read data.
Bluetooth support is only built by default on Android builds. You can manually add support for it by defining ```DEFINES += QGC_ENABLE_BLUETOOTH``` (either on the command line or through user_config.pri).
The opposite is also possible (if you want it for any reason). On Android, you can define ```QGC_DISABLE_BLUETOOTH``` to force its exclusion.
Because Bluetooth is possible it doesn't mean it is available. This is especially true for Desktop builds where the computer may not have Bluetooth hardware. Because …

Bluetooth Cleanup

---

qgroundcontrol.qrc
src/FlightMap/MapItems/MissionItemIndicator.qml
src/FlightMap/MapItems/MissionItemView.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/QmlControls/MissionItemIndexLabel.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/ScreenTools.qml

Decided showing altitude in item indicator looked like crap. Back to showing item number in indicator. Instead adding altitude map to little distance between waypoint thingy. You can open and close it to get it out of the way.

Mission: Switch back to item #, plus alt display

---

src/MissionManager/MissionController.cc
src/ui/MainWindowHybrid.qml
src/ui/MainWindowInner.qml
src/ui/MainWindowNative.qml

Fix for Issue #2372. Tablet crashes if you close while in the debugger. That seems to be new. But regular users will never notice.

Tablet app close

---

src/VehicleSetup/SetupView.qml

Direct connect to PX4 Flow shows up as generic. Fix for #2317

Only show PX4 Flow config if generic firmware

---

src/ui/toolbar/MainToolBarIndicators.qml

The Crossfire does not report battery percentage. Only current voltage.
I changed the toolbar battery indicator so it now shows the voltage (provided itself is available) if the battery percentage is not available.

Show battery voltage if percentage not available.

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/MissionManager/MissionItem.cc

- Fact system can handle unknown enum values by modifying the enum lists with and "Unknown: #" entry, where # will be replaced with he unknown value. This way if you are using a FactComboBox with indexModel=false (which means you are using enum meta data) and the value of the fact is not in the enum list, a new item will be added to the meta data. Then the fact signals changes to enum properties which in turn updates the combo box model with the new entry such that you can get a correct display even for values which were not originally in the enum meta data.
- Using the above, Mission Editor can now handle unknown MAV_CMDs which it may load from a file or get from a Vehicle without crashing.
Fixes for Issues #2384, #2371

Handle unknown enum values in meta data

---

qgcresources.qrc
qgroundcontrol.pro
src/AutoPilotPlugins/APM/APMAirframeComponent.cc
src/AutoPilotPlugins/APM/APMAirframeComponent.qml
src/AutoPilotPlugins/APM/APMAirframeComponentAirframes.cc
src/AutoPilotPlugins/APM/APMAirframeComponentAirframes.h
src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
src/AutoPilotPlugins/APM/APMAirframeComponentController.h
src/AutoPilotPlugins/APM/APMAirframeComponentSummary.qml
src/AutoPilotPlugins/APM/APMAirframeLoader.cc
src/AutoPilotPlugins/APM/APMAirframeLoader.h
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMFlightModesComponent.cc
src/AutoPilotPlugins/APM/APMRadioComponent.cc
src/AutoPilotPlugins/APM/APMRemoteParamsDownloader.cc
src/AutoPilotPlugins/APM/APMRemoteParamsDownloader.h
src/AutoPilotPlugins/APM/APMSafetyComponent.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/AutoPilotPlugins/APM/APMTuningComponent.cc
src/AutoPilotPlugins/APM/AirframeFactMetaData.xml
src/AutoPilotPlugins/AutoPilotPlugin.h
src/QGCApplication.cc
src/QmlControls/QGCView.qml

This commit introduces the APM Airframe configuration. The interface
is the same as the PX4 one, but the way we deal with the uas is a bit different
Since the APM stack doesn't provide a xml with airframe definitions a
new one was created by hand with only the values that we need, wich will
trigger a download of the parameters file from the mavlink github
Now it correctly handles the FRAME variable and it's faster
regarding the download of the parameters for each type of Frame.
Only show Airframes for ArduCopter, not for ArduRover nor ArduPlane

Add the initial stub for the AirFrame configuration for APM

---

src/QmlControls/SubMenuButton.qml
src/VehicleSetup/SetupView.qml

The setup button column width was a fixed size. Not only didn't it work on various dpis, it just can't be a fixed size. The plugin determines the text in the component buttons. So you don't really know till runtime how big they need to be.

Handle dynamic sizing of setup buttons

---

QGCExternalLibs.pri

Currently QGC is compiled using the "common" mavlink dialect which is all that is needed for the PX4 Flight Stack . This means that the "ardupilotmega" dialect additions are not available for use with APM Stack vehicles. With QGC providing support for both PX4 and APM stacks it needs to be able to work with the APM dialect as well. Since PX4 uses common and ardupilotmega dialect is superset on top of common it should be fine to instead use the ardupilotmega dialect as the base dialect for QGC. This way both PX4 and APM flight stack gets full access to their message sets.
This approach is a "workaround" to the issue that the mavlink helper routines do not allow for multiple dialects to be compiled into the same codebase. It only works because PX4 uses only common. If PX4 used a superset …

Use ardupilotmega mavlink dialect as main dialect

---

src/AutoPilotPlugins/APM/APMRadioComponent.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/PX4/FlightModesComponentController.cc
src/AutoPilotPlugins/PX4/PX4Component.cc
src/AutoPilotPlugins/PX4/PX4RadioComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/ParameterLoader.cc
src/HomePositionManager.cc
src/Joystick/JoystickManager.cc
src/LogCompressor.cc
src/MissionManager/MissionCommands.cc
src/QGCApplication.cc
src/QmlControls/ParameterEditorController.cc
src/VideoStreaming/VideoStreaming.cc
src/comm/MockLink.cc
src/comm/QGCFlightGearLink.cc
src/comm/UDPLink.cc
src/qgcunittest/MavlinkLogTest.cc
src/qgcunittest/RadioConfigTest.cc
src/ui/linechart/LinechartPlot.cc
src/ui/linechart/LinechartWidget.cc

There are many ways of iterating over lists in C++/Qt.
In the specific case of QStrings, it is known [1] that using
foreach with const references avoids the creation of new
QString objects in each iteration, reducing the time consumed
by the loops.
[1] https://blog.qt.io/blog/2009/01/23/iterating-efficiently/
Signed-off-by: Anselmo L. S. Melo <anselmo.melo@intel.com>

Review iterations over QStrings

---

src/AutoPilotPlugins/APM/APMCompassCal.cc
src/AutoPilotPlugins/APM/APMCompassCal.h
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc

Also fixed problem with setup complete signaling after positive calibration completed. Indicators were not going green when they should have.
Fixed for Issue #2442

Reset compass offsets to previous if cal cancelled

---

src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui

This is in response to #2452. It's a bug in Qt and instead of leaving there not functioning, I've removed it altogether. You can always maximize the window using the OS' own features.

Remove Full Screen menu action (and its opposite, Normal as well)

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/MissionManager/MavCmdInfo.json
src/MissionManager/MissionCommands.cc
src/MissionManager/MissionCommands.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h

Fix for Issue #2466. Currently only hooked up for radians and centi-degrees units. Waiting to validate meta data to take any further. Basically this change means that just using a Fact control will automatically get you correct translation to a more user friendly format of units.
Once I validate meta data a bit for good "unit" values I can easily add a setting which allows the user to convert things like meters to feet automatically.

Automatic raw->cooked translation based on units meta data

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/Common/RadioComponentController.cc
src/Vehicle/Vehicle.cc
src/qgcunittest/RadioConfigTest.cc

- Channel count incorrect from Vehicle
- Show prop warning on side dialog for APM stack as well as in status text area
- APM Stack has Pitch channel concept of forward and reverse backwards from PX4 Stack. That led to an exciting first flight on my APM Stack Iris fully setup using QGC!

Radio cal fixes

---

qgroundcontrol.qrc
src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml
src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactControls/FactBitmask.qml
src/FactSystem/FactControls/FactComboBox.qml
src/FactSystem/FactControls/qmldir
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/APM/APMParameterMetaData.h

- Add AutoTune to APM Copter Tuning config. Issue #2493
- Added support for bitmask meta data to FactSystem
- Parse bitmask parameter meta data from APM meta data
- Add new FactBitmask control which automatically generates a set of checkboxes from a Fact with bitmask meta data. An example is shown below in the image for AutoTune Axes: 
```
FactBitmask {
fact: controller.getParameterFact(-1, "AUTOTUNE_AXES")
}
```

APM Auto tune, FactSystem bitmask support

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UAS.h
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

I'm now using HDOP for determining the GPS signal strength (the graphical indicator). The drop down message box for GPS now shows these additional *raw* data items (HDOP, VDOP and COG).
I could only test with SITL as none of my boards are in a state I can test GPS at the moment.
P.S. While at it, that UAS.cc file is in desperate need for a make over...

Using HDOP for GPS signal strength indicator.

---

src/ui/MainWindow.cc
src/ui/MainWindow.h

If a widget used by a previous (QGC) session was changed (the name or missing altogether), QGC would crash when trying to load it.

Fixing crash bug.

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorDialog.qml

- Show enumStringValue for parameter value if there are enums
- Use ComboBox with enums if they are available in editor dialog
Fix for Issue #2464

Parameter editor work

---

src/ViewWidgets/LogDownload.qml
src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h

APM log entries are 1-based. Some times, the first log entry (entry 0) is sent with an uninitialized ID, zeroed size and date and the log entry count. It's not consistent. Most of the time the first packet is not sent at all. All other (valid) entries are 1-based (even though they all contain the total number of logs).
While "fixing" the log download to deal with this, I've also changed the date threshold to determine an *Unknown Date*. Those are logs recorded with no GPS time. The PX4 just have it zeroed (1 Jan 1970) while the APM returns something around the year 2000.
Renamed the saved log file from ".txt" to ".mavlink". It's not a text file and ".mavlink" is the extension used by the log replay widget.

APM Log Download "Fix"

---

src/ui/toolbar/MainToolBar.qml

This is in response to #2561. If the value (HDOP or VDOP) is not present, it's initialized to some large number (1e10f). The GPS indicator was not testing for this and showing it any way.

Fix GPS indicator so it handles non existing HDOP/VDOP values.

---

src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

This is in response to #2568 and #2566.
The indicator will only be enabled if GPS data is actually present. If there is no GPS receiver, you will see this:
If there is a receiver but no signal (indoors for example), you get this:
With proper reception, you get the full data (though even with 13 satellites, I didn't get beyond "3D Lock"):

GPS Indicator fixes.

---

QGCCommon.pri
QGCSetup.pri
src/VideoStreaming/gstqtvideosink/utils/glutils.h

Allows QGC to run on Raspberry Pi 2 with direct framebuffer (X/startx not needed). Memory split seems to need 128 for GPU. Qt5 needs to be configured with "-opengl es2 -qpa eglfs -device linux-rasp-pi2-g++".

R.Pi2 Support

---

src/Vehicle/Vehicle.cc

Added conditional statement to disable the virtualTabletJoystick output if a real joystick is connected and enabled. Without this, two different sets of values would be sent and would appear highly sporadic.

Prioritize real joystick over virtual joystick.

---

QGCSetup.pri

Otherwise the installer is created for every debug and release build, which often fails outside of Ubuntu with Qt from the online installer.

qmake only copy linux libs for installer

---

src/VehicleSetup/Bootloader.cc
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareImage.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.cc

Verify was failing due to incorrect READ_MULTI max size. Fix for Issue #2312

Fix RadioFlash

---

src/FactSystem/ParameterLoader.cc
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ViewWidgets/LogDownloadController.cc
src/comm/LinkManager.cc
src/comm/SerialLink.cc
src/comm/SerialLink.h
src/uas/FileManager.cc
src/uas/FileManager.h
src/uas/UAS.cc

Fix for Issue #2433
- Vehicle supports concept of priorityLink. This is the highest quality link available. Currently will return direct usb connection if available, if not it just returns the first link the vehicle has. Could be fancier at some point and use real link quality. Doesn't seem to be needed at this point.
- Parameter protocol: Always send out over a the single priority link. Protocol does not need to stay on same link.
- FTP protocol: Each transaction stays on the same single priority link
- Log download protocol: Always send out over a the single priority link. Protocol does not need to stay on same link.
- Mission Manager: Each read/write transaction stays on the same single priority link

Mini-protocol must only send on one link, in some case entire transaction must stay on same link

---

src/uas/UAS.cc

The ESP8266 Firmware parameters uses these for sending the UPD ports it uses and it was being caught by the lack of support.

Adding uint16_t to the list of supported types.

---

src/VideoStreaming/VideoStreaming.cc

The destruction order changed and I could not figure why the thread was hanging on a select(). The solution was simply: *don't do it*.

"Fix" for hanging on exit when Video Streaming build is enabled.

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/FlightMap.qml
src/MissionEditor/MissionEditor.qml
src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/Vehicle.cc
src/ui/MainWindowInner.qml

- Last known vehicle home position is saved as a setting
- Initial position for maps is last known home position. If last known home is not available, default to San Fran location.
- If GCS position is available, it will move to that position one time and override the last known home position
- Fly view: If Follow Vehicle is set, that supercedes all of the above
- Edit view: If Vehicle has gps lock, map will move to vehicle location one time, superceding all of the above
- GCS position is shown on map if available
Fix for issue #2560

Initial map position changes, plus GCS position on map

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/APM/APMParameterMetaData.h
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc

Fix for Issue #2465. Parameters which are marked as requiring reboot to take affect in meta data will now warn user with message if param is changed.
@LorenzMeier If you update the firmware parser to support a @RebootRequired param tag which outputs:
```
<reboot_required>true</reboot_required>
``` 
to the meta data xml this will work with PX4 as well.
@dogmaphobic This should help with your Radio parameters. Working to plumb component meta data through the system.

Add Reboot Required fact meta data

---

src/VehicleSetup/FirmwareUpgrade.qml

- Simplified initial pre-flash wording back to Plugin in via USB. Was getting too long, with people likely not longer reading due to lenght.
- If flash fails, show detail instructions about USB, direct connect, no hub, no battery.
Fix for Issue #2563

Show detailed instructions on flash fail

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h
src/ui/toolbar/MainToolBar.qml

- heartbeatTimeout stuff is gone
- Vehicle.connectionLost indicates connection state
- Vehice.connectionLostEnabled allows you to turn on/off connection lost checking. This is why I made the change. For APM stack when you are doing accel cal it doesn't send heartbeats. I need to turn off connection lost singalling while that is running.

Move connection lost handling to Vehicle

---

src/VehicleSetup/JoystickConfigController.cc

The lines removed set the center point of the throttle axis to one extreme of the joystick range. This causes an offset value when the stick is centered if the joystick does not return exactly zero. This is important for vehicles with reversible throttle, such as ground robots or boats.
Note: I've tested this code and the joystick behavior is almost identical except that the center point is correct for throttle. The "center stick is zero throttle" and "full down stick is zero throttle" works correctly and produces the same output as the original.

Joystick: Fix throttle center point.

---

src/AutoPilotPlugins/Common/RadioComponentController.cc

Since parameter system will pop message based on meta data. Fix for Issue #2603

Reboot message no longer needed

---

src/ViewWidgets/LogDownload.cc
src/ViewWidgets/LogDownload.qml

This is in response to #2649. Note that this is just for the first time you load Log Download. Whatever size you change to will be saved and restored in subsequent sessions.

Set initial size for log download.

---

src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h

APM stops sending heartbeats while streaming log files. Need to stop paying attention to heartbeats while downloading logs in order to prevent QGC from "Losing Connection". Same as in Accel Cal.

Stop paying attention to heartbeats while downloading logs.

---

qgroundcontrol.qrc
src/AutoPilotPlugins/APM/APMAirframeComponent.qml
src/AutoPilotPlugins/APM/APMCameraComponent.qml
src/AutoPilotPlugins/APM/APMFlightModesComponent.qml
src/AutoPilotPlugins/APM/APMPowerComponent.qml
src/AutoPilotPlugins/APM/APMSafetyComponentCopter.qml
src/AutoPilotPlugins/APM/APMSafetyComponentPlane.qml
src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml
src/AutoPilotPlugins/PX4/AirframeComponent.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/MissionEditor/MissionItemStatus.qml
src/QmlControls/FactSliderPanel.qml
src/QmlControls/ParameterEditor.qml
src/QmlControls/QGCFlickable.qml
src/QmlControls/QGCFlickableHorizontalIndicator.qml
src/QmlControls/QGCFlickableVerticalIndicator.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/VehicleSetup/SetupView.qml
src/VehicleSetup/VehicleSummary.qml
src/ui/MainWindowInner.qml
src/ui/preferences/GeneralSettings.qml
src/ui/preferences/LinkSettings.qml
src/ui/preferences/MavlinkSettings.qml

QGCFlickable should be used as the standard control wherever a Flickable or ScrollView would be normally used. It supports horizontal and vertical scroll height indicators which work just like the scroll indicators on iOs. They should up as needed and then fade out to get out of your way.
Fix for Issue #2469

New QGCFlickable control

---

src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc

Using ```factExists()``` instead of ```getFact()``` to see if the WiFi Bridge is present.

Using proper Fact testing to test if the WiFi Bridge is present.

---

src/AutoPilotPlugins/APM/APMAirframeComponent.cc
src/AutoPilotPlugins/APM/APMAirframeComponent.h
src/AutoPilotPlugins/APM/APMAirframeComponentAirframes.cc
src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
src/AutoPilotPlugins/APM/APMAirframeLoader.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMCameraComponent.cc
src/AutoPilotPlugins/APM/APMCameraComponent.h
src/AutoPilotPlugins/APM/APMCompassCal.cc
src/AutoPilotPlugins/APM/APMFlightModesComponent.cc
src/AutoPilotPlugins/APM/APMFlightModesComponent.h
src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc
src/AutoPilotPlugins/APM/APMFlightModesComponentController.h
src/AutoPilotPlugins/APM/APMPowerComponent.cc
src/AutoPilotPlugins/APM/APMPowerComponent.h
src/AutoPilotPlugins/APM/APMRadioComponent.cc
src/AutoPilotPlugins/APM/APMRadioComponent.h
src/AutoPilotPlugins/APM/APMSafetyComponent.cc
src/AutoPilotPlugins/APM/APMSafetyComponent.h
src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.h
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMTuningComponent.cc
src/AutoPilotPlugins/APM/APMTuningComponent.h

A cleaned version of the staled branch: 
- Don't check for null pointers after a new, they won't be null, ever.
- use QStringLiteral / QLatin1Literal when they should be used
- fix some const correctness
- don't create virtual methods on overrides, use 'override' or 'final' keywords when needed.

Apm stuff v2

---

QGCSetup.pri

When you generate a Visual Studio project, the build fails as it doesn't not know where to find windeployqt.

Adding full path to windeployqt.

---

src/comm/LinkManager.cc

Seems that a typo is preventing a bitwise operation.

bitwise and, not boolean and, to check for bitmasks.

---

src/FlightDisplay/FlightDisplayView.qml

Warn user if they have joystick enabled on APM stack since it normally would not be supported. This way custom firmware with added MANUAL_CONTROL support will still get joystick support, but users using standard firmware will hopefully not be confused.
Fix for Issue #2636

Warn about joystick on APM stack

---

src/main.cc

In response to #2524.
Using (arbitrarily chosen) port 14999 to detect instance. Cannot use normal (default) port because that can be changed and there is no simple way to detect it until is too late.

Detect running instance and prevent loading second instance.

---

src/VehicleSetup/FirmwareUpgrade.qml
src/comm/LinkManager.cc
src/comm/LinkManager.h

- Timeout was too slow for slower ardupilot boot and and/or cases where boot also needs to flash px4io
- Changed message wording: Your Vehicle is not responding. If this continues please check that you have an SD Card inserted and try again.
- Turn off firmware upgrade restart. Now if you flash, you wll have to leave firwmare upgrade and come back to flash again. The restart was causing problems with slower boots time and stealing port from auto-connect. This would cause intermittent failures of auto-connect after flashing
Fix for #2704

SD card delay detection changes

---

src/ViewWidgets/LogDownload.qml
src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h

This is in response to #2706.
Formatting the log sizes and the downloaded amount using separators.

Formatting log sizes using locale specific separators.

---

src/AutoPilotPlugins/Common/ESP8266Component.qml
src/AutoPilotPlugins/Common/ESP8266ComponentController.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

This is optional. You need to click the *Show Status* button to enable it. Data is collected from the WiFi bridge using dynamic json requests as well as directly from QGC's link. This way we can identify where the errors are occurring. In the case below, the errors are at the QGC's UDP receiving end.
*Reset Counters* allows you to synchronize the counters. Each new session of either end will start with 0s, making the end that continues to run to continue *counting*.
P.S. The message counts don't match because the QGC data is in real time while the Bridge data comes in 1Hz Query/Response interval.

Adding (optional) link status data to the WiFi Bridge panel.

---

src/AutoPilotPlugins/PX4/ParameterFactMetaData.xml

@DonLakeFlyer This adds this param meta for PX4 (note the <values> tag). It would be great if that could be enabled in the UI to drive the drop-downs like for APM. I also have a wish list for a few config UI additions driven by this.
```xml
<parameter default="157600" name="SYS_COMPANION" type="INT32">
<short_desc>Companion computer interface</short_desc>
<long_desc>CHANGING THIS VALUE REQUIRES A RESTART. Configures the baud rate of the companion computer interface. Set to zero to disable, set to these values to enable (NO OTHER VALUES SUPPORTED!) 921600: enables onboard mode at 921600 baud, 8N1. 57600: enables onboard mode at 57600 baud, 8N1. 157600: enables OSD mode at 57600 baud, 8N1.</long_desc>
<min>0</min>
<max>921600</max>
<reboot_required>true</reboot_required>
<values>
<value …
```

Update PX4 default param meta file

---

src/QGCFileDownload.cc
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

This change will display a message to a the user when a FW image is not found as
`Error: File Not Found. Please check beta firmware version is available`
`Error: File Not Found. Please check developer firmware version is available`
`Error: File Not Found. Please check stable firmware version is available`
etc..
ie.
```
QGroundControl can upgrade the firmware on Pixhawk devices, 3DR Radios and PX4 Flow Smart Cameras.
All QGroundControl connections to vehicles must be disconnected prior to firmware upgrade.
Please unplug your Pixhawk and/or Radio from USB.
Plug in your device via USB to start firmware upgrade. 
Found device: Pixhawk
Connected to bootloader:
Version: 5
Board ID: 11
Flash size: 2080768
Downloading firmware...
From: http://firmware.diydrones.com/Copter/beta/PX4-quad/ArduCopter- …
```

Add Error Message when FW is not found on Server.

---

src/FirmwarePlugin/APM/MavCmdInfoFixedWing.json
src/FirmwarePlugin/APM/MavCmdInfoMultiRotor.json
src/MissionManager/MissionControllerTest.cc
src/comm/MockLink.cc

Fix for Issue #2699. Use new command override mechanism to fix it.

ArduPilot takeoff mission command does not specify coordinate

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/FirmwareUpgrade.qml

- Add Vehicle::autoDisconnect property. Set to true and Vehicle will automatically disconnect when it loses heartbeat
- When firmware upgrade asks to unplug board set autoDisconnect=true to improve usability flow. User no longer needs to click Disconnect for thing to proceed.
- Fix broken property in Qml which was preventing cancel from closing dialog
Fix for Issue #2770, #2695
Note that this was a simpler usability than a full firmware upgrade rewrite. A full upgrade re-write is still likely needed for even better usabilty and OTA upgrade. But that can now wait until 3.1

Flash auto-disconnect from vehicle

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactGroup.cc
src/FactSystem/FactGroup.h
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/FactSystem.cc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/MapItems/VehicleMapItem.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/JsonHelper.cc
src/JsonHelper.h
src/Vehicle/BatteryFact.json
src/Vehicle/GPSFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json
src/comm/QGCXPlaneLink.cc
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

- A FactGroup allows you to create a hierarchy of Facts where the leaf nodes of the tree are Facts.
- The leaf node Facts have full meta data available for them. MetaData is defined in json files. 
- Methods are exposed to both C++ and Qml to traverse the object model hierarchy. This allows for user friendly property picker ui to be created. Think user friendly Info View property selection.
- The Facts within a FactGroup can have their valueChanged signals rate limited. This allow you to create a slower refresh rate of values to connect to ui elements.
- The Vehicle object is now a FactGroup with the following initial hierarchy (more to come):
```
vehicle.roll
vehicle.pitch
vehicle.heading
vehicle.groundSpeed
vehicle.airSpeed
vehicle.climbRate
vehicle.altitudeRelative …
```

Add new FactGroup support

---

src/MissionEditor/MissionEditor.qml

This allows you to click/add waypoints under the list view if it isn't taking up the screen real estate. For fix Issue #2785

Size ListView to content height

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

Fix for Issue #2788. Nothing fancy, but functional. Files must be in Documents location and end in .mission extension.

Add support for load/save mission on tablet

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactGroup.cc
src/FactSystem/FactSystem.cc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/ValuesWidget.qml
src/FlightMap/Widgets/ValuesWidgetController.cc
src/FlightMap/Widgets/ValuesWidgetController.h
src/FlightMap/qmldir
src/QGCApplication.cc

Instrument panel now has a configurable center section where you can pick the values you want to show there. There are two formats for value display: large and small.
Here is the default setup which pretty much matches the original visuals. Except the text is slightly smaller to fit more items. These are two large value widgets.
Here is an example of what it looks like with a couple small value widgets added:
Click on the control to pick values to show. Picker is functional, still needs better visuals:
The values you can choose from will grow as I build out the Vehicle object model.

ValueWidget inside instrument panel

---

src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h
src/ui/MAVLinkDecoder.cc

The LogDownloadController had a gap handling mechanism that was not very efficient (particularly with large log files). This map-based approach should improve things considerably for large files.
Additionally the MavlinkDecoder was assaulting the UI thread with updates from the LOG_DATA mavlink messages, so we've gone ahead and filtered that out. 
I have tested with a couple of log files and some simulated dropped packets and things seem to be working normally. Hash checks matched on the downloaded files vs. straight from the SD card. Unfortunately small sparsely spaced gaps are slow to finish up because the timeout has to occur after every segment.
I wouldn't mind a bit more testing and feedback though.

Improvements to Log Downloading

---

src/MissionEditor/MissionEditor.qml

Fix for Issue #2837. Screwed it up when I added mission load/save to tablet.

Fix incorrect method name

---

src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h
src/QGCApplication.cc

- Request list of all parameters, expecting device to lead each component with _HASH_CHECK cache value
- Test for hash collision, if so our cache is valid and respond with _HASH_CHECK to stop listing
- Else: let listing continue as normal to get updated param values
- Store each cache by systemID + componentID
For #2586 and PX4/Firmware#3764

New parameter cache loading spec

---

src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp

I can't reproduce this here but the stack trace in #2850 is in the same place my Windows build had issues with. I'm basically trying to get Qt NOT to use disk cache (redundancy). There is no way to disable it altogether so I'm telling it to use 1kb of disk space. This worked for all but Windows, which crashed unless I set it to 100kb. Apparently I was being lucky.
I'm now setting it to 100kb for all platforms. This will all change when we switch to 5.6.

Hopefully fixes crash Lorenz is seeing.

---

src/QtLocationPlugin/QGCMapTileSet.cpp
src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGeoCodeReplyQGC.cpp
src/QtLocationPlugin/QGeoCodingManagerEngineQGC.cpp
src/QtLocationPlugin/QGeoMapReplyQGC.cpp
src/QtLocationPlugin/QGeoServiceProviderPluginQGC.cpp
src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc

The Nexus 7 (Android) has a very wide but short window. Some parts of the Offline maps UI did not fit the height. I've added Flickable where appropriate.
While at it, I've reordered the header files as requested by @DonLakeFlyer.

Flickable in Offline Maps

---

android/AndroidManifest.xml
android/src/org/qgroundcontrol/qgchelper/UsbDeviceJNI.java
src/Vehicle/MultiVehicleManager.cc

I tried all possible permutations of the desired `getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);` with no effect whatsoever (as reported by many people at stakoverflow). The issue, I think, is that it needs to be called at a point in the Activity creation process we have no access (that's within the Qt bootstrap code).
I'm using the PowerManager class to force Android from dimming and turning off the screen *while* a vehicle is connected. If there are no vehicles connected, I restore to normal (to save the battery).

Android stay on

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/ValuesWidget.qml
src/Vehicle/VehicleFact.json

- This is all in the ValuesWidget which is the center of the instrument panel.
- Also changed user text for Vehicle.altitudeRelative to "Altitude-rel" from "Altitude (home)". Previous text was taking too much space. We'll see if anyone else has better suggestions.

Fix font sizing for small screens

---

qgroundcontrol.qrc
src/FactSystem/Fact.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/WindFact.json

New Vehicle.wind object model. Available to instrument panel config. Currently hooked to ardupilot dialect _WIND message. Waiting on Issue #2833 to complete for PX4 implementation.
* Vehicle.wind.direction
* units: degrees
* decimal places: 1
* name: "Wind Direction"
* mavlink: __mavlink_wind_t.direction
* Vehicle.wind.speed
* units: m/s
* decimal places 1
* name: "Wind Spd"
* mavlink: __mavlink_wind_t.speed
* Vehicle.wind.verticalSpeed
* units: m/s
* decimal places 1
* name: "Wind Spd (vert)"
* mavlink: __mavlink_wind_t.speed_z

Add Vehicle.wind properties

---

qgroundcontrol.qrc
src/FactSystem/FactGroup.cc
src/FlightMap/Widgets/InstrumentSwipeView.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/VibrationWidget.qml
src/FlightMap/qmldir
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VibrationFact.json
src/comm/MockLink.cc
src/comm/MockLink.h

* Instrument panel center section can now flip through pages. Swipe left/right to flip pages. Center will resize to appropriate size.
* Added second page for vibration display. Here it is running on my Asus 7" tablet:
* New Vehicle.vibration properties, plumbed through from _VIBRATION mavlink message
```
{
"version": 1,
"properties": [
{
"name":             "xAxis",
"shortDescription": "Vibe xAxis",
"type":             "double",
"decimalPlaces":    1
},
{
"name":             "yAxis",
"shortDescription": "Vibe yAxis",
"type":             "double",
"decimalPlaces":    1
},
{
"name":             "zAxis",
"shortDescription": "Vibe zAxis",
"type":             "double",
"decimalPlaces":    1
},
{
"name":             "clipCount1",
"shortDescription": "Clip Count (1)",
"type": …
```

Add Vehicle.vibration property support, plus vibe page in instrument panel

---

src/AutoPilotPlugins/Common/ESP8266ComponentSummary.qml

This was causing an error to popup about incorrect FactPanel hookup

Fix mission factPanel hookup in ESP WiFi thingy summary qml

---

qgroundcontrol.qrc
src/JsonHelper.cc
src/JsonHelper.h
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/SimpleItemEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/VisualMissionItem.h
src/QmlControls/MissionItemEditor.qml

- Load/Save working. You can now round trip a complex mission item (like a survey) without having it devolve into just a huge pile of waypoints.
- Entry point working. A complex mission item has both and entry and exit waypoint.
Here is an example after I reloaded from a mission file. You can see the entry into the survey area:

More work on complex mission items

---

src/FlightMap/Widgets/ValuesWidget.qml

Scrolling was going up under title bar. Here you can see the problem from my 7" tablet:

Values picker dialog: Clip to inner size

---

src/FlightMap/MapItems/MissionItemIndicator.qml
src/FlightMap/MapItems/MissionItemView.qml
src/FlightMap/Widgets/VibrationWidget.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/VisualMissionItem.cc
src/MissionManager/VisualMissionItem.h

Plus many load/save fixes. Here is any example of what a mission with two structure scans in it would look like:

Add complex mission item exit coordinate support

---

src/ui/toolbar/MainToolBar.qml

Connection Lost makes user think they need to Disconnect. When in reality if the Vehicle is still there they should just wait for the signal to come back (hopefully).

Change wording to Communication Lost

---

qgroundcontrol.pro
src/FactSystem/FactControls/FactTextField.qml
src/FactSystem/FactGroup.cc
src/FactSystem/FactGroup.h
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/ValuesWidget.qml
src/FlightMap/Widgets/VibrationWidget.qml
src/GAudioOutput.cc
src/GAudioOutput.h
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/BatteryFact.json
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/audio/QGCAudioWorker.cpp
src/audio/QGCAudioWorker.h
src/uas/UAS.cc
src/uas/UAS.h
src/ui/preferences/GeneralSettings.qml

* New configurable talking battery warning. You can set the precent remaining in settings
* New MultiVehicleManager::disconnectedVehicle. This is a disconnected Vehicle object which you can use to get access to FactGroup meta data without a vehicle
* Updated a number of the spoken message to use Vehicle::_vehicleIdSpeak which will say only "Vehicle" if there is only on vehicle, or "Vehicle #" is there are multiple vehicles
Fix for Issue #2901

Talking battery, plus other stuff

---

src/Vehicle/MultiVehicleManager.cc
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/LogReplayLink.cc
src/comm/LogReplayLink.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/comm/SerialLink.cc
src/comm/SerialLink.h

Also fixed an important AutoConnect bug which has been around forever but I hadn't been able to track down a repro. If an autoconnect failed in that QGC connected physically, but no heartbeat ever came across the connection. No matter how many times you unplug/replug via QGC you wont be able to connect until you restart QGC. Fix now, yay!
Fix for Issue #2931

Much better missing SD Card detection

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/toolbar/MainToolBarIndicators.qml

Guided mode allows you direct control over a Vehicle:
* Guided mode commands are implemented through new methods/capabilities in FirmwarePlugin. This way main QGC code is agnostic to the guided mode implementation of a specific firmware. 
* You can determine if guided commands are supported by a firmware using FirmwarePlugin::isCapable and the two new capabilities: PauseVehicleCapability, GuidedModeCapability.
* The guided mode command bar is at the bottom of the window.
* Arm/Disarm has moved from the toolbar to the guided bar
* Guided bar supports: Arm/Disarm/EmergencyStop, RTL, Takeoff/Land, Pause, Change altitude
* Takeoff, Change Altitude support inputing an Altitude value
* When the vehicle is in Guided mode, clicking on the map will move it to that location
Currently full guided …

Add Guided mode support

---

src/VehicleSetup/PX4FirmwareUpgradeThread.cc

QGC would crash if there was an error during write. This was due to a bad return path.

Flash: Correct return after error

---

src/FactSystem/FactGroup.cc
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/MissionManager/SimpleMissionItem.cc
src/QGCApplication.cc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/preferences/GeneralSettings.qml

* Added more translators to FactMetaData
* Add support for selecting FactMetaData translator based on user configurable settings for distance and speed units.
* Turned on user selectable unit translation for all Mission Item values
* Turned on user selectable unit translation for all FactGroup properties (instrument panel)
* Units are configurable from General Settings. Requires a reboot to take affect. I know it's a pain. But it required a lot more plumbing to handle it on the fly. That will come later (maybe 3.1).
* There are still a couple other places that show distance values without using the FactSystem. Hence they don't get free conversion support. Those will get converted as well in a separate pull (this will be in 3.0). For example: 
* Plan view, altitude status display
* Guided …

Unit conversion for FactGroup and Mission Items

---

qgcresources.qrc
resources/ArrowRight.svg
resources/cancel.svg
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QmlControls/SliderSwitch.qml

* Replaced the text "buttons" with proper icons.
* Adjusted the slider width to give a bit more room for the message within.
* Made the "Reject" button optional (and disabled it within he UI). This is closer to the normal iOS controller. Clicking anywhere outside the slider dismisses it. I found it confusing. A bit of a contradiction with the command "Slide to *Action*", when the arrow points to a "Cancel".
If you think the "X" to cancel should be there, it's just a matter of enabling the `showReject` property to *true*.
The UI (with *showReject* disabled):
The "Reject Button" when enabled:

Tweaking the SliderSwitch controller.

---

QGCCommon.pri
qgroundcontrol.pro
src/FlightMap/FlightMap.qml
src/QtLocationPlugin/QGCLocationPlugin.pri
src/QtLocationPlugin/QGeoTileFetcherQGC.h
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp

First shot at a Qt 5.6 build. Mostly, an update on the location plugin to conform with the new interfaces. For Mac OS, I had to bump the target platform to 10.7 (from 10.6) and include a framework for TTS, which apparently is no longer added automatically by qmake.
Tested on Mac OS, iOS and Ubuntu.
Map elements (like vehicle position, waypoints and lines in between them) are not showing up on Mac OS or Ubuntu. They do show up fine on iOS.

Initial Qt 5.6 build support.

---

src/FlightDisplay/FlightDisplayView.qml

The *Pipable* control was still visible even if no video support was built, with nothing to pip :P

Remove "Pipable" control if there is no Video.

---

src/QGC.h

This shouldn't break a thing on other linux boxes that compiles
fine.

Fix compilation on some linux boxes

---

android/src/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java
android/src/com/hoho/android/usbserial/driver/UsbId.java

This enable qgroundcontrol to open a u-blox GPS connected directly by USB.

added u-blox USB device IDs

---

src/QGC.h

this simple patch cleans more than 500 warnings on my build
and it should be really safe to apply since it basically remove
unused variables.

Clean unused variables / Fix QObject macro

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h

Given the way parameter request works we can't know whether all components have completely loading params without using some sort of timeout mechanism. I've udpated the code to handle the case where non default components fully complete, before the default component sends its first param. I've tested with test code as well as various real multi-component vehicles. But this ended up being a fairly pervasive change in a very central/important part of the codebase. May need to bake time to settle out.  
This also adds some new failure case handling where the default component never responds with parameters. It also allows the parameter editor to work even if full param load fails.
Fix for Issue #3057.

Handle waiting for default component to come through in a better way

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml

Guided mode bar will move down and get out of the way when you are not using it. Click in the map to bring it back. This was needed for small screens ilke iPhone. I have it turned on for all screen types now. We'll see if it's too annoying. If so, I'll make it optional and default to on for small height screens only.

Auto-Hide guided mode bar

---

src/audio/QGCAudioWorker.cpp

Initialize espeak in async playback mode and explicitly synchronize after each synth operation in the worker thread.

Fix for espeak / alsa errors for #3015

---

src/FactSystem/FactControls/FactTextField.qml

All facts are numeric, atm. this means that the input should only
accept numbers. it already had the     inputMethodHints:   Qt.ImhFormattedNumbersOnly
option, but for some reason it still accepted letters and symbols.
by adding a     validator: DoubleValidator {} we limit the characters
to numbers only - and if the value is a integer, it will still work.
Tested by adding waypoints on the map & messing with the GPS coordinates.

Only accept numbers in FactTextEdit

---

deploy/qgroundcontrol-start.sh

This patch makes it possible to run qgroundcontrol-start.sh from outside its directory, e.g.,
`/qgroundcontrol/qgroundcontrol-start.sh` instead of having to `cd qgroundcontrol/ && ./qgroundcontrol-start.sh`.

Make it possible to run qgroundcontrol-start.sh from outside its directory

---

src/MissionManager/MissionItem.cc
src/MissionManager/MissionItemTest.cc
src/MissionManager/MissionItemTest.h

* SimpleMissionItem resets default values when command changes (correct behavior). MissionItem::loadFromJson was setting command after coordinate was loaded. This was causing coordinate to be modified after correct value was loaded.
* Update unit tests to catch this case.
Fix for Issue #3117.

Mission item fixes

---

src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc

Hack fix for #3086. The real fix is too involved as this point since we are trying to close down for 3.0. What this fix does is not disconnect if the link is being used by other Vehicles. The issues with this is that the inactive Vehicle will still hang around. But that's better than the current state of disconnecting the other active vehicle.

Hack fix for multi-vehicle disconnect on same link

---

src/ui/toolbar/MainToolBar.qml

Using proper logo background color in main toolbar.

Using proper logo colors.

---

src/MissionManager/MavCmdInfoCommon.json
src/uas/UAS.cc

Fix for Issue #3165.
* QGC message output for COMMAND_LONG failure translates command names using MissionCommands info.
* Set good friendly names for SET_MODE and ARM_DISARM which are common failures.

Better command failure output

---

qgroundcontrol.pro
src/VideoStreaming/VideoStreaming.cc
tools/osxrelocator.py
tools/prepare_gstreamer_framework.sh

While at it, I also defined a new `DEFINES`. If you add `ENABLE_VERBOSE_OUTPUT` to your `user_config.pri`, you get “noise” compiler output.

Fix GStreamer relocation for Mac OS release (installer) builds.

---

QGCInstaller.pri

These are libraries added by `macdeployqt`, which use non public Mac OS API and are therefore *Non Compliant*. They are not used by QGC any way.
Note that you will still see the warning during the build accompanied with the message these libraries are being skipped:
```
WARNING: Plugin "libqsqlodbc.dylib" uses private API and is not Mac App store compliant.
WARNING: Skip plugin "libqsqlodbc.dylib"
WARNING: Plugin "libqsqlpsql.dylib" uses private API and is not Mac App store compliant.
WARNING: Skip plugin "libqsqlpsql.dylib"
```

Skip "non compliant" Qt libraries (for Mac OS App Store)

---

src/MissionEditor/MissionEditor.qml

* When you select a waypoint in the map the list scrolss to it. it not 100% correct, but it's better than before
* Scroll the item list on the right no longer scrolls the map underneath it
Related to #2922

Plan: Scroll list to current item

---

src/AutoPilotPlugins/Common/ESP8266ComponentController.cc
src/AutoPilotPlugins/Common/ESP8266ComponentController.h
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionCommandList.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MockLink.cc
src/uas/UAS.cc
src/uas/UASInterface.h

* COMMAND_LONG failures now show up in pop up message instead of toolbar dropdown
* Add missing MAV_CMDs to json meta data
* Added friendly names for all MAV_CMDs so command failures for any of these will give good feedback
Fix for #3071

Better feedback for command failures

---

src/FlightDisplay/FlightDisplayViewWidgets.qml

This hides the "No GPS Lock on Vehicle" message when the video stream is full screen.
I'm doing this for ArduSub, since ROVs don't have GPS but do use the video stream. This would also be helpful for people flying FPV with no GPS. 
If you disagree that the error should be hidden, then I would ask that we put it in a less conspicuous place.

Show GPS error message only on map view

---

src/comm/MAVLinkProtocol.cc

https://github.com/mavlink/qgroundcontrol/issues/3151
Adding default case for RADIO_STATUS. This means it is now possible to send a RADIO_STATUS message with the actual, negative rssi and remrssi (i.e. using mavlink_msg_radio_status_pack) and this will correctly displayed in the QGC telemetry.

Default case for RADIO_STATUS

---

src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/FirmwarePlugin.cc
src/Vehicle/Vehicle.cc
src/ui/MainWindow.cc

In response to #2829:
A boolean was added to the message handler preventing it from sending critical messages to the main window until told otherwise. The call to enable these messages was within the parameter handler and it would only get called once the parameters were received (`msgHandler->showErrorsInToolbar();`). That code in turn would send whatever error messages the handler had accumulated so far and enabled the handler. This was also causing these messages to be sent twice. Once by the parameter handler and another by the normal behavior of the message handler, which was now enabled to send messages to the main window.
On a minor note I noticed that the error message *"Guided mode not supported by Vehicle."* was issued 12 times from different places (repeating the entire message …

Restore critical messages in the main window.

---

.gitmodules
qgroundcontrol.pro
src/GPS/GPSManager.cc
src/GPS/GPSManager.h
src/GPS/GPSPositionMessage.h
src/GPS/GPSProvider.cc
src/GPS/GPSProvider.h
src/GPS/RTCM/RTCMMavlink.cc
src/GPS/RTCM/RTCMMavlink.h
src/GPS/definitions.h
src/GPS/satellite_info.h
src/GPS/vehicle_gps_position.h
src/QGCToolbox.cc
src/QGCToolbox.h

This adds the drivers and structure used for RTK GPS. The gps driver code is added as a submodule since it is shared with the PX4 firmware.
It provides a working version, but is still under development and not finalized yet. The whole thing is disabled so it does not interfere with the existing code. Dependencies should be Qt and STL only so it should compile for all platforms. Testing was done under Linux.
@DonLakeFlyer can you review this?

Add GPS drivers and RTCM output for RTK GPS

---

android/gradle/wrapper/gradle-wrapper.properties
src/QmlControls/QGCButton.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/ScreenToolsController.cc
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/ui/MainWindowLeftPanel.qml

Work on the *Offline Tile Cache* UI
* Made the map a lot larger during the definition of a set, making better use of the screen real estate.
* When viewing an existing tile set, the UI now shows the map and delineates the cached region.

Offline map

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightMap/Widgets/ValuesWidget.qml
src/QmlControls/QGCView.qml
src/QmlControls/ScreenTools.qml
src/ui/MainWindowInner.qml
src/ui/toolbar/MainToolBar.qml

This is in response to issue #3190 
I've restored the main Toolbar transparency. For that to work, the main map/video view has to fill the entire screen. The gadgets, widgets and dialogs have to be aware of the available height (as opposed to using the full height). That is accomplished by querying *ScreenTools*.
While at it, I've fixed the layout for the *ValueWidget*, making the tabulation work correctly.
I still think that has a bit of a *Mission Planner* feel to it. All that's missing is an option to display cubits per lunar cycle.

Restoring toolbar transparency.

---

src/MissionEditor/MissionEditor.qml
src/ui/MainWindowInner.qml

... so the map extends beneath the toolbar.
When working with the toolbar transparency, I failed to notice the mission editor had its own handling of the map viewing area. It only extended to the bottom of the toolbar (making it look opaque as the map started below it).
This adds the same behavior as the main Flight View.

Fixing the Mission Editor view to respect the view area

---

src/AutoPilotPlugins/PX4/FlightModesComponent.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.cc

This was reported by @sn0west and @jcooper21 in #3262. If you were to select the *Flight Modes* panel before running the calibrations (*Sensors*), QGC would crash while plowing through non existing *Facts*.
This "*fix*" prevents you from attempting to run the Flight Modes before running the calibrations. I've also added some NULL pointer checks as the original code was making indirect calls without any checks.
To be consistent with the above, I've moved *Flight Modes* below *Sensors* in the setup list.
@DonLakeFlyer If indeed you need to run the calibration before assigning Flight Modes (weird), I guess this is all that was needed. If not, this is the code that was causing the crash:
https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/PX4/PX4SimpleFlightModesControll …

Fixed crash when switching to the Flight Modes panel.

---

qgroundcontrol.pro
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FollowMe/FollowMe.cc
src/FollowMe/FollowMe.h
src/PositionManager/PositionManager.cpp
src/PositionManager/PositionManager.h
src/PositionManager/SimulatedPosition.cc
src/PositionManager/SimulatedPosition.h
src/QGCApplication.cc
src/QGCToolbox.cc
src/QGCToolbox.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/MainWindowInner.qml

Adds an abstraction layer to the positional information read by the qgc system. Any type inheriting from QGeoPositionInfoSource can easily inject it's GPS data into the system via this new class(some examples would be, simulate qgc movement, add log play back, use an external gps, ect...) . This also removes all simulated position methods from the Follow me class and puts them in their own class.

Enhancement.position manager

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionItemTest.cc

My development environment is Windows 7, Qt5.5.1(x86), VS2013. There are always building error about MissionItemTest, after I git clone QGC. When the source code assignes values to the objects of QJsonAray or QJsonObject, building errors appear. After I study the implementation of the class QJsonArray and QJsonObject, I find the solution.

Fix windows build bug, about MissionItemTest. Fix Survey delete bug.

---

src/VehicleSetup/SetupView.qml
src/VehicleSetup/VehicleSummary.qml

Clicking on the sumarry titles enters the edit mode
On the tests with users, they always clicked on the
title (because it resembled a button or something) and
nothing happened. it was a bit confusing to have the
same information in two places and only one of them
being clickable.

Clicking on the summary titles enter edit mode

---

src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
src/AutoPilotPlugins/APM/APMAirframeComponentController.h
src/AutoPilotPlugins/APM/APMAirframeComponentSummary.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

During tests, if the airframe was configured to be an 'X' type
we showed just 'X' on the airframe type. It's correct but a
single letter - specially an X - made users think that it was
a error code, not the airframe name. So, because of that, also
show the vehicle type plus the airframe type - a wrong value, but elucidative for users.

Show a more educative airframe configuration

---

src/QmlControls/ParameterEditorDialog.qml

This makes it possible to select more than one value
to be used in the parameter configuration, and since
the parameter is actually a bitfield - this is the
correct thing to do.
one of the drawbacks is that in the parameter listing
the value of the Fact will not be displayed as string
anymore, but with 'undefined: numerical-value', that is
the OR combination of the applied values.

Parameter Edit: Handle bitfields as ComboBoxes

---

src/FlightMap/Widgets/ValuesWidget.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCView.qml
src/ui/MainWindowInner.qml

Actually, I changed it so `showDialog` figures out on its own if it should use available height or full parent height. The variable is now set by the main window, which controls which view is being shown.
I commented off some code in `ParameterEditorDialog.qml` as it is not properly handling the dialog and causing it to get "stuck".

Fix QGCView.showDialog() when called from FactTextField.

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

Making the Safety Panel scroll area full width (as opposed to just the content area).

Making scroll area full width.

---

qgcresources.qrc
src/AutoPilotPlugins/Common/ESP8266Component.qml
src/AutoPilotPlugins/Common/ESP8266ComponentController.cc
src/AutoPilotPlugins/Common/ESP8266ComponentController.h
src/AutoPilotPlugins/Common/ESP8266ComponentSummary.qml
src/AutoPilotPlugins/Common/Images/APMode.svg
src/AutoPilotPlugins/Common/Images/StationMode.svg

The new MavEsp8266 Firmware (1.0.7) allows you to set it to either *AP Mode* (the default, and what it's been up to now) or *Station Mode*. When set to Station Mode, it will connect to the AP defined by the SSID (using the defined password). This allows for multiple vehicles to connect to QGC provided they all belong to the same AP network.
The firmware once booted, will attempt to connect to the defined Access Point. If after a minute it cannot connect, it will revert to AP mode.

Support for new esp firmware

---

src/AutoPilotPlugins/PX4/PowerComponent.qml

Fact was named `uavcanEnable` and reference to it was using `_uavcanEnabled`

Fixing Fact name typo.

---

src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/QmlControls/MissionItemIndexLabel.qml

The Mission Item Status was using the font *pixel* size to compute dimensions (instead of its height or width in pixels). With the change to point size, the computations were all over the place.
While at it, fixed some clipping errors in both the mission list within the Plan View and the Mission Item Status view as well.

Fix sizing within MissionItemStatus

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/ScreenTools.qml
src/VehicleSetup/SetupView.qml
src/ui/preferences/GeneralSettings.qml

I've added a setting under *General Settings* allowing users to set the base UI font point size. This is used throughout QGroundControl to size almost all UI controls (in addition to fonts). You can now fine tune the UI size to your liking.

Allow users to change base UI font point size.

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/MissionEditor/MissionEditor.qml
src/QmlControls/DropButton.qml
src/QmlControls/QGCButton.qml
src/QmlControls/QGCComboBox.qml
src/QmlControls/QGCRadioButton.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/RoundButton.qml
src/ui/MainWindowInner.qml

In response to #3349 
Made quite a few UI adjustments:
* Larger button sizes for all mobile devices. It used to be only for *Tiny Screens*
* Made touch sensitive area for the "X" to close both the Critical Message Area and the Message Window larger for mobile devices. Normally, only the "X" is touch sensitive, which works fine on desktop platforms with a mouse but quite tricky to hit it using touch.
* Made the DropDown buttons (and the RoundButtons) slightly larger on all mobile devices.
* Fixed the Down Arrow icon on buttons with menus (#3352). The padding and overall width were being computed incorrectly. In addition, several dimensions were hardcoded with small numbers, which become irrelevant on high density devices.
* Made all QGCButtons, QGCRadioButton and QGCTextField slightly …

More size adjustments.

---

src/AutoPilotPlugins/APM/APMAirframeComponentSummary.qml
src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/comm/MockLink.cc
src/comm/MockLink.h

@LorenzMeier This pull assumes PX4 stack will begin returning AUTOPILOT_VERSION.flight_sw_version using the following semantics. This mechanism is already supported by ArduPilot. PX4 stack is currently returning 0 in AUTOPILOT_VERSION.flight_sw_version.
```
void Vehicle::_handleAutopilotVersion(mavlink_message_t& message)
{
mavlink_autopilot_version_t autopilotVersion;
mavlink_msg_autopilot_version_decode(&message, &autopilotVersion);
if (autopilotVersion.flight_sw_version != 0) {
int majorVersion, minorVersion, patchVersion;
FIRMWARE_VERSION_TYPE versionType;
majorVersion = (autopilotVersion.flight_sw_version >> (8*3)) & 0xFF;
minorVersion = (autopilotVersion.flight_sw_version >> (8*2)) & 0xFF;
patchVersion = (autopilotVersion.flight_sw_version >> (8*1)) & 0xFF;
versionType = …
```

Show firmware version in Vehicle summary

---

src/FactSystem/FactMetaData.cc

Decimal places adjustment for cooked values wasn't handling the case wher decimal places is not specified in meta data.

Fix logic to handle decimal places not specified in meta data

---

src/QGCQuickWidget.cc

This is the workaround around for pinch problems on the Map control with mac trackpads. It disables Pinch zoom support on macos only. This isn't a major issue since on the map since two finger scroll still zooms the map in/out.
The actual issues is a Qt bug: https://bugreports.qt.io/browse/QTBUG-53634
Fix for Issue #3058

Turn off touch events for Mac OS

---

src/ui/MainWindow.ui

Since the help menu items don't really have any good places to point to I removed it.
Fix for #3320

Remove help menu

---

src/AutoPilotPlugins/Common/ESP8266Component.qml
src/AutoPilotPlugins/Common/ESP8266ComponentSummary.qml

In response to #3453
QGC disables the (WiFi) channel assignment if the module is set to *Station Mode*. The problem was that with it, it was also disabling it if you were running older Firmware that did not support changing WiFi modes.

Better handle disabling AP channel number for WiFi parameters.

---

src/FlightDisplay/FlightDisplayViewWidgets.qml

Vehicle should fail arm command if not allowed as opposed to having QGC make the rules for when arm is allowed/disallowed. Otherwise it gets much too complicated as to whether the vehicle even requires a gps. Or if it does whether it has a circuit breaker set for it to allow arm without gps lock.
@LorenzMeier This reverses your change.
Fix for #3391

Allow arm with no GPS lock

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/FlightMap.qml
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/ScreenTools.qml
src/QmlControls/ScreenToolsController.cc
src/QmlControls/ScreenToolsController.h

Very small iOS screens have a different density and need and appropriate default font point size, which in turn defines the overall UI scale.
The code now identifies iOS very small screens (4s, 5 and 5s), medium (6 and 6s) and larger screens (6/6s Plus and all iPads).
In addition, I am hiding the map scale on tiny screens. It just doesn't fit as the Fly Widget overlaps it.
This handles most, if not all problems defined in #3483

Tweaks for small screens on iOS.

---

src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h

According to #2641, the link change signal was causing a crash on shutdown. Since this signal is not used anywhere, I removed it.

Removing unused signal.

---

src/comm/LinkConfiguration.cc
src/comm/LinkConfiguration.h

Restoring link change signal.
Link configuration (QML) relies on the existence of the link (active) configuration to know if the link is active or not. Removing the signal got it confused. I'm restoring the signal but making sure the signal is emitted if the link is truly changed. When a link is disconnected, the link manager resets the link configuration (which causes a signal to be emitted as it changed). When the link itself is deleted, it also sets the link configuration to NULL, which was causing it to emit another signal when no signal was needed (there were no changes as it was already NULL).

Restoring link change signal.

---

src/QtLocationPlugin/QGCTileCacheWorker.cpp

For the time being, I'm making sure the description is not empty (so it will continue to work with existing databases).

Making tile cache description not mandatory.

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/FlightMap.qml
src/FlightMap/FlightMapSettings.cc
src/FlightMap/FlightMapSettings.h
src/FlightMap/MapScale.qml
src/MissionEditor/MissionEditor.qml
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/ui/preferences/GeneralSettings.qml

- Offline maps now set defaults to default map type
- Plan/Fly views uses new MapScale control
- Remove map scale on/off option from settings. 1) Due to less is more 2) Added complexity of scale showing up on all maps and also not showing up on small screens
Fix for #3517, #3518

Single map type setting for all maps

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/Joystick/JoystickSDL.cc
src/Joystick/JoystickSDL.h
src/VehicleSetup/JoystickConfig.qml

(Note: This is a new version of PR #3455 that has been updated for the new joystick code.)
This PR addresses the issue that joystick/gamepad hats are considered to be "hats" in Windows but "buttons" on Mac and Linux. This causes inconsistent numbers of joystick buttons between OSes.
This PR causes joystick hats to be detected and appended to the normal button list. Only the up, down, left, right buttons are recognized and appear in the same order that they are detect on Mac/Linux.
A few things worth mentioning:
- The other buttons are still detected in different orders on different OSes so this doesn't provide complete consistency
- The center button (like the "X" on the Xbox controller) is not detected on Windows. This will be fixed in SDL2
- This does not affect the indices of any …

Recognize joystick hats and append to the button list (rev 2)

---

.appveyor.yml
.travis.yml

I'm moving the continuous builds from the top level of the qgc bucket to builds/$branch to enable auto expire.

move continuous s3 builds

---

src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/AutoPilotPlugin.cc
src/FactSystem/ParameterLoader.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FollowMe/FollowMe.cc
src/GPS/RTCM/RTCMMavlink.cc
src/MissionManager/MissionManager.cc
src/QGC.h
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ViewWidgets/LogDownloadController.cc
src/comm/MAVLinkProtocol.cc
src/uas/UAS.cc

* Messages are now only sent out on priority link
* All appropriate commands are targetted to the default component id

Fix priority link and default component id usage

---

.travis.yml

-closes #3479
This is hard to test without dropping a tag and accidentally pushing something to production.

travis-ci deploy tagged Android builds to google play production

---

resources/opengl/buglist.json

Upstream: https://bugreports.qt.io/browse/QTBUG-49541
Report: https://groups.google.com/forum/#!topic/qgroundcontrol/1BjN5M4f7Tg
This may make a strong case for reading the current Qt blacklist from memory and making whatever modifications we feel necessary on the fly. Granted we haven't upgraded to 5.6.0 so we wouldn't have gotten the fix yet, but we were dependent on users to report something that was already fixed upstream.

Update OpenGL buglist to blacklist rotation on Intel HD graphics adapters

---

.travis.yml
src/VideoStreaming/README.md
src/VideoStreaming/VideoStreaming.pri

This was lost on travis-ci when switching to their newer infrastructure with the apt add-on instead of just using the command line to install packages.

travis-ci install gstreamer for linux

---

src/ui/preferences/MockLinkSettings.qml

Settings of mock link take now effect (Arducopter / Arduplane)

Save vehicle type for APM mock link

---

src/FactSystem/ParameterLoader.cc
src/FactSystem/ParameterLoader.h

Also don’t pop errors for initial request failure on generic vehicle. This helps with not annoying users using things like BeBop since they have no parameters exposed.

Param load: Try initial request 5 times max

---

qgroundcontrol.pro
src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FirmwarePlugin/PX4/px4_custom_mode.h
src/comm/MockLink.cc

I made the PX4 mode naming consistent with the COM_FLTMODE* params. I also pulled in the px4_custom_mode.h header straight from PX4 as a crude way to stay in sync.
https://github.com/PX4/Firmware/blob/master/src/modules/commander/px4_custom_mode.h
https://github.com/PX4/Firmware/issues/4796

PX4 mode cleanup

---

src/VehicleSetup/JoystickConfigController.cc

Amount of delta to detect joystick settle was too low. This was preventing calibrating of joysticks which don't have real solid stop positions.

Bump joystick settle constant

---

src/ui/toolbar/MainToolBarIndicators.qml

This is the Yield button for messages on the toolbar. When the animation for that starts it chews a ridiculous amount of CPU on iOS. I get it more often on my Solo since it's always complaining about the GPS pre-arm state. Which cause the animation to go off.
Related to #3576

Remove animation to save perf

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/MapItems/MissionLineView.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionCommands.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/VisualMissionItem.cc
src/QmlControls/CoordinateVector.cc
src/QmlControls/CoordinateVector.h
src/QmlControls/MissionItemEditor.qml
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h

This goes a long way towards making waypoint dragging smooth on my machine. Even still with all the QML bindings and aggressive updating I still manage to peg a core while dragging around a waypoint in a large mission, but the update rate is much much higher and things feel significantly more responsive. 
Also included:
- Fixes the memory leak in the waypoint line model 
- Fixes waypoints not being inserted properly from the hamburger menu
- Fixes abbreviations not updating properly when sequence numbers were recomputed 
- Other performance optimizations / tweaks to mission related items

Rework mission lines + various mission-related bug fixes

---

src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/SimpleItemEditor.qml

Also should finally fix mission editor view sync when changing current waypoint.
During creation of a very large mission with 100s of points I noticed the mission editor was getting really laggy. QML profiler showed the editor bindings for the simple mission item delegate were extremely expensive and slow.
Instead, load them only for each point when it is selected. This makes the ListView scroll smoothly with a ton of points too.

Defer loading and binding of mission editing QML components

---

.travis.yml

This might be why a compile failure isn't registered.
#3596

travis-ci remove sed

---

src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
src/QtLocationPlugin/QMLControl/OfflineMap.qml

In response to #3676.
Qt is using a 32-bit signed integer for setting the max memory cache (which limits it to < 2G). I'm limiting it to 1G, rounding down as there is no good reason to use more than that.

Limit max memory cache for offline maps.

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h

This solves #3469. The Joystick class was creating an array of QString an and accessing them as if they were in the heap. Changing it all to a QStringList as it is more appropriate in this case.

Fixing a crash in the Joystick class.

---

src/Vehicle/MultiVehicleManager.cc
src/Vehicle/Vehicle.cc

Related to #3699
Version decoding is as follows:
```
void Vehicle::_handleAutopilotVersion(mavlink_message_t& message)
{
mavlink_autopilot_version_t autopilotVersion;
mavlink_msg_autopilot_version_decode(&message, &autopilotVersion);
if (autopilotVersion.flight_sw_version != 0) {
int majorVersion, minorVersion, patchVersion;
FIRMWARE_VERSION_TYPE versionType;
majorVersion = (autopilotVersion.flight_sw_version >> (8*3)) & 0xFF;
minorVersion = (autopilotVersion.flight_sw_version >> (8*2)) & 0xFF;
patchVersion = (autopilotVersion.flight_sw_version >> (8*1)) & 0xFF;
versionType = (FIRMWARE_VERSION_TYPE)((autopilotVersion.flight_sw_version >> (8*0)) & 0xFF);
setFirmwareVersion(majorVersion, minorVersion, patchVersion, versionType);
}
}
```

Adjust version query semantics

---

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc

Look at src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc for the main change. I included updated param and airframe metadata. 
https://github.com/mavlink/qgroundcontrol/pull/3723/files#diff-96a673062773c2b8d313746933b7ac71R315

PX4 add bitmask for param metadata

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

Currently adding a new item copies the altitude from the previous waypoint. It also need to copy the coordinate frame, otherwise this could lead to confusion and bad things happening on the mission.

Plan: Copy coordinate frame from prev waypoint as well

---

src/QmlControls/OfflineMapButton.qml
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapEngine.h
src/QtLocationPlugin/QGCMapTileSet.cpp
src/QtLocationPlugin/QGCMapTileSet.h
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGCTileCacheWorker.h
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h

This started with something @glody found and posted in #3778.
The original issue was that the Max Disk Cache was not being properly computed. Some changes from a few weeks ago caused it to be computed wrongly and always returning 0. This would cause the engine to keep pruning the database. That in turn triggered an original bug in the pruning code.
Pruning only occurs in the *Default Tile Cache*. The one where tiles are saved when you just move about. Tile sets you create are not pruned. The bug was that when pruning the Default Tile Cache, the logic looking for "common" tiles (to avoid deleting), that is, tiles used in more than one set, was not working. This in turn caused these tiles to be deleted and saved sets that had them got out of sync, gumming the entire work.
I fixed that whole …

Fixes to Offline Map Cache

---

src/FlightMap/FlightMap.qml
src/MissionEditor/SurveyItemEditor.qml
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h

FlightMap control nows support a generic polygon drawing tool. Reusable by Survey (already converted), GeoFence (coming soon) and so forth. Will also add polygon re-editing at a later time.
```
//
// Usage:
//
// Connections {
//     target: map.polygonDraw
//
//    onPolygonStarted: {
//      // Polygon creation has started
//    }
//
//    onPolygonFinished: {
//      // Polygon capture complete, coordinates signal variable contains the polygon points
//    }
// }
//
// map.polygonDraqw.startPolgyon() - begin capturing a new polygon
// map.polygonDraqw.endPolygon() - end capture (right-click will also end capture)
```
Example usage in SurveyItemEditor:
```
Connections {
target: editorMap.polygonDraw
onPolygonStarted: {
missionItem.clearPolygon()
}
onPolygonFinished: {
for (var i=0; …
```

Map polygon drawing tool

---

src/VideoStreaming/VideoStreaming.pri

Windows builds without gstreamer install were failing

Windows GStreamer: Copy files in right place

---

src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h

Use constant's inverse to ensure we don't accumulate error when converting back and forth

Switch to exact conversion constants

---

src/FlightDisplay/FlightDisplayView.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

When an APM vehicle is connected and a joystick is enabled, QGC currently pops up a dialog warning the user that the vehicle must support the `MANUAL_CONTROL` message to be used with the joystick. That is appropriate for most APM vehicles, which don't support `MANUAL_CONTROL`. 
This PR disables this message for ArduSub firmware, which does support the `MANUAL_CONTROL` message. The message is still shown for all other APM firmware types.
ArduSub is detected with `MAV_TYPE_SUBMARINE`.
Please let me know if you have any questions or concerns.
Thanks!

ArduSub: Disable joystick warning message

---

src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h

In response to #3763 
Increased the timeout for log listing to accommodate the time it takes for the firmware to build the list before sending it.
Disabled heartbeat timeout during log listing as it is done with log downloading. For long listings (where you have a lot of log files to list), QGC was timing out and issuing "Connection Lost" during the list download.
There is a corresponding firmware change (https://github.com/PX4/Firmware/pull/5133), which handles the deletion of the "msgs_*" files along with the log files.

Log download fixes.

---

src/ViewWidgets/LogDownloadController.cc
src/ViewWidgets/LogDownloadController.h

In response to #3763
Increased the timeout for log listing to accommodate the time it takes for the firmware to build the list before sending it.
Disabled heartbeat timeout during log listing as it is done with log downloading. For long listings (where you have a lot of log files to list), QGC was timing out and issuing "Connection Lost" during the list download.
There is a corresponding firmware change (PX4/Firmware#5133), which handles the deletion of the "msgs_*" files along with the log files.

Log Download Fixes

---

src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/preferences/GeneralSettings.qml

It adds a choice for area unit, which will then later be used to display the area of a survey mission.
It supports:
* Square meters
* Square kilometers
* Hectares
* Square feet
* Acres
* Square miles

[Mission stats] Added area translation

---

src/MissionEditor/MissionItemStatus.qml

This PR exposes the mission stats values, displaying some dummy values. The actual calculations will follow in separate PRs.
Additional values are:
* Total mission distance
* Total mission time
* For VTOL vehicles both values split in cruise and hover
* If a survey item is selected:
* Number of shots
* Covered area

[Mission stats] Dummy mission stats

---

qgroundcontrol.pro
src/FirmwarePlugin/APM/APMParameterFactMetaData.Sub.3.4.xml
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePluginManager.cc
src/FirmwarePlugin/FirmwarePluginManager.h

This PR provides the (relatively minor) changes needed to add an ArduSub plugin to QGC. This plugin is very minimal at the moment and only serves to help provide the right flight modes.
ArduSub is detected by `MAV_TYPE_SUBMARINE`.
This also includes updates to the ArduSub XML file to reflect the available flight modes that should be shown when an ArduSub vehicle is connected.
Please let me know if you have any questions, comments, or requested changes.
Thanks!

ArduSub Plugin: Basic Files + XML Update

---

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMFlightModesComponent.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

This PR disables the radio setup page when an ArduSub vehicle is connected. The vehicle is detected with MAV_TYPE_SUBMARINE.
The radio page is not needed for ArduSub because it is controlled exclusively through the use of the QGC joystick feature. The radio setup page is confusing for ArduSub users and the calibration process results in settings that are changed to undesirable values.
Please let me know if you have any questions or require any changes. I really appreciate your support!
Thanks!

ArduSub: Disable radio setup page (Take 2)

---

src/Vehicle/Vehicle.cc

As discussed with Don, this prevents the "joystick enabled" setting from being disabled every time QGC opens without a joystick attached. The "joystick enabled" setting will only be loaded and saved if a joystick is attached, otherwise, it will always be `false`.

Fix persistency of joystickEnable setting

---

src/MissionEditor/MissionItemStatus.qml
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h

This PR requires merging of https://github.com/mavlink/qgroundcontrol/pull/3828 and https://github.com/mavlink/qgroundcontrol/pull/3829 first.
* Computes the number of shots of a survey item, based on the distance and the selected triggering distance.
* Computes the area of the drawn polygon in the survey item and displays it as Covered area.

[Mission stats] Computing number of shots and covered area

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/preferences/GeneralSettings.qml

It gives the user the option to select in general settings:
* Vehicle type: {Fixedwing, Multicopter, VTOL}
* Nominal cruise speed (only visible if not selected multicopter)
* Nominal hover speed (only visible if not selected fixedwing)
These values will be used to calculated a flight duration estimate while planning missions.

[Mission stats] Offline planning settings

---

src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/ComplexMissionItemTest.cc

Survey: Adjust grid line direction after polygon clip

---

src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/VisualMissionItem.h

This PR will require a rebase once https://github.com/mavlink/qgroundcontrol/pull/3852 and https://github.com/mavlink/qgroundcontrol/pull/3830 are merged.
The following is computed:
* Mission distance
* Mission time
* Maximum telemetry distance
For the case of a VTOL the code added also computes
* distance estimate for hover and cruise individually
* time estimate for hover and cruise individually
and outputs them all in the previously established mission statistics display.

[Mission stats] Compute distance & time

---

src/VehicleSetup/FirmwareImage.cc

down bin file to pixhawk fail,because it do not set value for _binFilename in _binLoad

Fix download custom firm file err: no file name specified

---

src/FactSystem/FactControls/FactComboBox.qml
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/Joystick/Joystick.cc
src/VehicleSetup/JoystickConfig.qml

This PR contains changes for a joystick button function selector specifically to support ArduSub. It is integrated so that it does not have any affect whatsoever on existing features and appearance. The button function selector allows selection of the button "function" and the "shift function" directly from the joystick page, greatly increasing usability for ArduSub users.
Additionally, there are some minor changes along the way:
- The `throttleMode` radio buttons on the joystick page are now hidden for ArduSub and forced to use "full down stick is zero throttle" to avoid issues during use.
- The FactComboBox implementation was fixed to allow for null Facts
- The `manualControlReservedButtonCount` function in `APMFirmwarePlugin` was made non-final so it could be overridden by the ArduSub …

Joystick button function selector for ArduSub

---

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/Joystick/Joystick.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/JoystickConfig.qml

Per Issue #3894, this fixes the way various UI options are detected using a plugin based method instead of direct detection by vehicle type. This fixes this in a number of places beyond those mentioned in #3894.
Specifically, the following methods are now part of `Vehicle` and `FirmwarePlugin`:
- `supportsManualControl`
- `supportsThrottleModeCenterZero`
- `supportsRadio`
- `supportsJSButton`
Please let me know if there are any questions or required changes.
-Rusty

Fix plugin semantics for ArduSub additions

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/VehicleSetup/JoystickConfig.qml

This adds an exponential response to the joystick roll, pitch, yaw axes for better usability and better similarity to an actual RC radio.
The exponential equation is:
```
float expo = -0.35;
roll = -expo*powf(roll,3) + (1+expo)*roll;
[etc..]
```
The exponential factor is very similar to RC radio expo settings, which usually go from 0% to -50% or so. The output remains normalized regardless of the exponential factor. The default is hardcoded at -35%, which gives a good response for joystick axes.
I made a quick illustration of what this looks like from 0% (linear) to -50% (strong exponential):
https://www.dropbox.com/s/86l66vb2tl7syjv/expo-qgc-20160528.mov?dl=0
Note: This only applies to the physical joysticks and not to the virtual joysticks. I can fix that if you'd like.

Add RC-radio-like exponential to joystick RPY axes

---

src/Vehicle/Vehicle.h
src/ui/toolbar/MainToolBarIndicators.qml

Optional radio support was added as a plugin feature recently. This PR removes the radio signal strength icon from the top toolbar when the radio is not supported by the firmware plugin.
Please let me know if you have any questions.
-Rusty

Hide radio rssi icon from toolbar if radio is not supported

---

src/FlightDisplay/FlightDisplayView.qml

The state of the main map/video window is storable as a global setting. It is currently being loaded from the global settings source, but it is never being saved, so this does not persist. 
This PR is a bugfix to resolve that. With this fix, the map/video window will remain on map or video through restarts instead of always defaulting to the map.
This may have been done intentionally and I don't know about, so please let me know if there are any issues.
-Rusty

Save _mainIsMap state persistently

---

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml

This adds the transition switch to the simple flight mode UI. The switch is only displayed if the airframe is a VTOL. Also updates airframe and param meta so QGC shows these new parameters correctly in their correct group.
@tubeme @kd0aij

VTOL transition switch UI

---

src/MissionManager/MissionController.cc

As pointed out [here](https://github.com/mavlink/qgroundcontrol/pull/3863#discussion_r73190742) in PR #3863, while calculating mission distance, we fail to take into account the case when survey mission item is the first waypoint after home. This PR takes care of that.

[Mission stats in Survey Feature]: check when survey item is first mission item

---

src/ViewWidgets/LogDownloadController.cc

Without this change we need 500ms to elapse so the [timer](https://github.com/NaterGator/qgroundcontrol/blob/b4afd5283bff3291f1bfabfc06d99e8af9c63e84/src/ViewWidgets/LogDownloadController.cc#L117) fires for each missing bin in a chunk (dropped / corrupted packets, or whatever else may cause it). 
This checks if a LOG_DATA packet is being received at the end of a gap in the downloaded data to continue searching for other gaps of missing data to request immediately.

Quickly handle downloading scattered gaps

---

src/VideoStreaming/README.md

Add a quick note in the video streamer readme that you have to select the "Complete" install of gstreamer during the install process, otherwise the project will not build.

Add note about gstreamer complete install in readme

---

QGCExternalLibs.pri
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/Vehicle.cc
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/ui/MAVLinkDecoder.cc
src/ui/preferences/MavlinkSettings.qml

* Centralize all mavlink message sending in MAVLinkProtocol to provide single point for mavlink version setting
* Add Mavlink Version options to Settings/Mavlink. Default is "Default to 1, switch to 2 if Vehicle sends version 2"

Mavlink 2.0 support

---

src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/ComplexMissionItemTest.cc
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h

This is an initial solution to https://github.com/mavlink/qgroundcontrol/issues/3801.
By setting the turnaround distance to >0 additional waypoints are inserted. For now they are simply offset from the polygon edge by the given distance.
For turnaround distance <=0 everything remains as before.
We will test the feature during flights this week. If we find we have to adapt the the shape of the offset, this patch should allow easy prototyping.

Turnaround waypoints for fixed-wing surveying

---

QGCCommon.pri
qgroundcontrol.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewDummy.qml
src/FlightDisplay/FlightDisplayViewUVC.qml
src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoStreaming.pri
src/VideoStreaming/VideoSurface.cc
src/VideoStreaming/VideoSurface.h
src/VideoStreaming/gstqtvideosink/gstqtvideosinkplugin.cpp
src/ui/preferences/GeneralSettings.qml

* Added support for Android x86 (including GStreamer)
* Added support for RTSP Video Streams
* Switching between UDP and RTSP, or changing the options for either one requires restarting the application. I still need to see what is not being reset for a seamless switch to occur.
* Made a bit of a reorg in the General Settings panel. The idea is to make all panels consistent.
* Added build flag to skip UVC support if desired (QGC_DISABLE_UVC)
* Made Camera view to fit screen, cropping if necessary (as opposed to stretch it)
* Fixed crash bug on Linux when no UVC device was available
* Moved QML Camera item into a loader, which is only loaded if UVC is available (it crashes if it is not)

RTSP Video, Android x86 and other fixes.

---

QGCSetup.pri
qgroundcontrol.pro
src/FlightDisplay/VideoManager.cc

I'm also including `multimedia` to QT only when UVC is enabled.
In addition, I've added `libQt5Multimedia.so.5` to the Linux setup in hopes that's all that is needed. I don't have a system to try it on.

Fix inverted logic when disabling UVC.

---

QGCSetup.pri

I had added `libQt5Multimedia.so.5` but I missed `libQt5MultimediaQuick_p.so.5`. It will be a trial-and-error until we get it all there as I don't have a way to fully test what libraries are needed. Let's see if this is all it takes.

Adding missing library to Linux build.

---

src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/SurveyMissionItem.cc

This extends the camera survey feature by:
* adding parameters like ground sampling distance (gsd) and frontal/side overlap
* allowing the calculation of gsd and overlap from altitude and grid spacing or the reverse. This allows you to set up a mission either from desired height and gridspacing or desired gsd and overlap
* adding more camera parameters, like image size (needed for enhanced calculations) and moving their edit fields to a popout to save space
* adding a way to add default camera models and choosing between them from a dropdown menu

Camera survey enhancement with additional parameters

---

src/VideoStreaming/README.md

libgstreamer-plugins-bad1.0 is not installed if 3rd party plugins are opted-out during OS install

Add video streaming dependency

---

src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h

This adds the gridAltitude to the survey item coordinate and exitCoordinate and updates them whenever gridAltitude is changed.
This allows the correct calculation of alt. diff. and gradient for a survey item and shows the correct altitude in the bottom bar.

Add altitde to survey item coordinate

---

qgcresources.qrc
src/FactSystem/FactMetaData.cc
src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMGeoFenceManager.h
src/FirmwarePlugin/APM/CopterGeoFenceEditor.qml
src/FirmwarePlugin/APM/PlaneGeoFenceEditor.qml
src/FirmwarePlugin/GeoFenceEditor.qml
src/FirmwarePlugin/PX4/PX4GeoFenceEditor.qml
src/FirmwarePlugin/PX4/PX4GeoFenceManager.h
src/MissionEditor/GeoFenceEditor.qml
src/MissionEditor/MissionEditor.qml
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.h
src/QmlControls/MissionItemEditor.qml

This allows for custom designed geo fence editors. I've implemented custom editors for PX4 and ArduPlane. Copter will come soon, it's still generic param list at this point.
PX4:
ArduPlane:

Allow GenFenceManager to specify QML for fence editor

---

qgroundcontrol.pro
src/VideoStreaming/VideoStreaming.pri

* Updated message for required GStreamer on Linux (to support RTSP)
* Disabled UVC video for Ubuntu with Qt 5.5.1 (conflict with Qt trying to use GStreamer 0.10 for USB video)

Video updates for Ubuntu.

---

android/src/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java
android/src/com/hoho/android/usbserial/driver/UsbId.java
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h
src/comm/SerialLink.cc
src/ui/preferences/GeneralSettings.qml

This PR aim at adding support for several boards compatible with LibrePilot firmware for its upcoming MAVLink interface Implementation.
This is done with the following additions: 
- More robust Interface detection. It is not tied to a specific layout and support composite interfaces;
- USB id for currently supported boards are supplied;
- DTR is asserted when the port is open;

Improve USB Interface detection reliability and support for LibrePilot compatible USB IDs

---

src/FactSystem/FactControls/FactTextField.qml
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCTextField.qml

Any place you use a FactTextField you now automatically get detailed help associated with the value. Here is an example using it on a settings (offline edit cruise speed) that may be unclear to the user. Also an example for a param on a mission item.
Note: Mission Items params don't have good meta data yet. I'm working on that.

Show help button on FactTextFields

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/QGCXPlaneLink.cc
src/comm/QGCXPlaneLink.h
src/uas/UAS.cc
src/uas/UAS.h
src/ui/QGCHilXPlaneConfiguration.cc
src/ui/QGCHilXPlaneConfiguration.ui

This supports the new mavlink message HIL_ACTUATOR_CONTROLS for use with X-Plane HITL. The coolest feature is that it can now control individual actuators in X-Plane, instead of emulating the joystick. The old message HIL_CONTROLS is still working. A checkbox is added in the ui to switch between the two.
I also ran fix_code_style on the files but apparently a lot was still wrong. To get a better idea of the changes I made, only look at the first commit.

Add support for HIL_ACTUATOR_CONTROLS with X-Plane HITL

---

src/MissionEditor/SurveyItemEditor.qml

The 22mm as stated on the lens is actual, not 35mm equvalent as on smaller
cameras.  - So it was wrong to reverse calculate for crop factor.

Survey: Corrected EOS-M focal length

---

src/MissionEditor/SurveyItemEditor.qml

Sony a6000 ILCE-6000 with 16mm lens.
Source : 
http://www.sony.co.uk/electronics/interchangeable-lens-cameras/ilce-6000-body-kit#product_details_default

Adding Sony a6000 to camera list

---

QGCCommon.pri

In response to #4058, I commented off the setting of the Mac OS SDK.
The reason this was being set by hand was due to a bug in qmake, which was not properly assigning the variable and using non-existing SDKs. This has since been fixed.
With this commit, QGC will build using the latest available SDK installed on the system. It doesn't affect the App Store build as that has to be done manually (from an Xcode project) any way.

Removing forced Mac OS SDK.

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

before, with a PX4 version of eg. 1.5.0, the user was wrongly notified.

px4firmwareplugin: fix minimum required version comparison

---

qgroundcontrol.qrc
src/FactSystem/FactControls/FactTextFieldGrid.qml
src/FactSystem/FactControls/FactTextFieldRow.qml
src/FactSystem/FactControls/qmldir
src/JsonHelper.cc
src/JsonHelper.h
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/Survey.FactMetaData.json
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h

Reworked survey UI for better usability. There are now essentially three types of surveys you can set up (from a user perspective):
* Manual Grid - Specify all values yourself. Doesn't use camera specs to determine grid
* Custom Camera Grid - Grid is generated based on camera specs, but you specify the camera specs yourself.
* Specific Camera - Grid is generated from the camera specs for the selected known camera.
New features realting to Survey:
* The ability to specify whether you want altitude or ground resolution to take precedence when entering new values. You can see this in the camera grid ui examples below.
* All fields are now Facts which means you get the little help thingy for all survey values.
Also in this pull are some new framework capabilities:
* New FactTextFieldRow and …

Major Survey UI rework

---

src/QGCFileDownload.cc
src/QGCFileDownload.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

ArduPilot is now redirecting urls for firmware urls. This breaks current QGC.

Handle redirects in file downloads

---

src/MissionEditor/MissionEditor.qml

Since [here](https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionManager/MissionController.cc#L481) the save function requires a filename as input, but we weren't providing this [here](https://github.com/mavlink/qgroundcontrol/compare/master...wingtra:fix/load_save_on_tablet?expand=1#diff-476fe2248af8c57c641f0128ede640a1R259), we couldn't save mission files on tablet.
Further, because of a typo in `loadFromFile`, couldn't load mission files, either.
Fixing these two typos here.

Fix saving and loading mission file on tablet

---

src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemEditor.qml

What is happening -
Currently, the insert functionality (as shown in the screenshot) after a Survey Item, doesn't work and if trying to use thus, qgc stops working in the planning view.
This is because, on using the insert functionality, the sequence number set [here](https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionEditor/MissionItemEditor.qml#L77) is the actual sequence number allotted to the waypoint after the SurveyItem has been converted to waypoints, i.e., a large number such as 156 as seen above.
This is then passed to function `insertSimpleMissionItem` defined [here](https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionManager/MissionController.cc#L159). However, this function sets indices based on "visual items", [(see …

Fix insert functionality after Survey Item

---

QGCSetup.pri

- fixes #4105 
My default qmake build had QGC_DISABLE_UVC defined, but still needed these libs. Any objection to just leaving them in all the time?

linux package always include libQt5Multimedia

---

src/QGCApplication.cc
src/Vehicle/Vehicle.cc
src/comm/LinkManager.cc
src/comm/MAVLinkProtocol.cc
src/comm/QGCMAVLink.h
src/ui/MAVLinkDecoder.cc
src/ui/QGCMAVLinkInspector.cc

Using generic mavlink header support was causing mavlink_status_t to be created for each source file. Which in turn caused the mavlink 2.0 flags to be out of whack.

Use single mavlink_status_t array

---

libs/lib/Frameworks/SDL2.framework/Versions/A/Resources/Info.plist

Since this file is in the `.gitignore` file, it was never added to the SDL2 files. On macOS Sierra, this causes code signing issues.
If I download the app and copy this file into the SDL2.framework, then it works just fine. I'm 99% sure this will fix the issue with Sierra.
-Rusty

SDL2: Add missing Info.plist file for SDL2 framework.

---

src/FlightMap/FlightMap.qml

I originally set out to fix a few minor issues with unwanted black lines being drawn while drawing polygons as mentioned in PR #4142 . I couldn't find a quick and simple way to do this without creating issues so I ended up making a few bigger changes.
In addition to fixing the original issues, this pull request adds a second polygon which indicates what the polygon will look like if you end the drawing, while the original polygon shows what the polygon will look like if you click to add a new point. If you wanted to go back to the original look you could simply set the new polygon to be invisible.

Multicolored polygon

---

src/comm/MAVLinkProtocol.cc

Following a comment form @bkueng, enabling a test for MAVLink version test when a message is first decoded.
Note that I feel this to be a temporary stop-gap fix until @DonLakeFlyer is back. That `decodedFirstPacket` variable is static and it will "stick" on subsequent connections. This will certainly not work if you have two vehicles connected or if you disconnect and connect again.

Checking for MAVLink 2.0 when first message is received.

---

src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMGeoFenceManager.h
src/FirmwarePlugin/APM/APMRallyPointManager.cc
src/MissionEditor/MissionEditor.qml
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.cc
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointController.h
src/MissionManager/RallyPointManager.cc

* When the Plan view first comes up it will adjust the viewport on the map to include all items: Mission, Fence, Rally
* When you load items back from the vehicle (Mission, Fence, Rally) the map viewport will adjust to show those items
* New Center map: All Items support to fit all items (mission/fence/rally) into view
* Also fixed a number of fence and rally point bugs
Fix for #4051

Better Plan view map viewport handling

---

src/AutoPilotPlugins/Common/RadioComponentController.cc
src/AutoPilotPlugins/Common/RadioComponentController.h
src/qgcunittest/RadioConfigTest.cc
src/qgcunittest/RadioConfigTest.h

Fix for #3228
This code was a hold over from when the flight mode setup was in rc cal.

Don't let other function mapping lock out usage of those channels for radio cal

---

src/AnalyzeView/GeoTagController.cc
src/MissionManager/GeoFenceController.cc
src/MissionManager/MissionController.cc
src/QmlControls/ParameterEditorController.cc

On ubuntu and mac some of the file dialogs open behind the QGC window. This is fixed in this PR by giving it the main window as parent.

Open file and directory dialogs in foreground

---

src/Vehicle/MAVLinkLogManager.cc
src/Vehicle/Vehicle.cc

The early return lead to data being dropped. Some of this data could have been
part of the ulog header, which lead to corrupt files.
@dogmaphobic with this ulog streaming seems to work well now. Thanks for your efforts.

fix for MAVLinkLogManager

---

src/FlightDisplay/VideoManager.cc
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h

RTSP will try to connect to the server. If it cannot connect,  it will simply give up and never try again. I added code to keep trying to make a connection to the server first. Only when I get a connection, will I actually start the stream. 
This solves the problem where if QGC was started before it had a network connection, or before the video source had started, it would not connect to the stream.

Handle delayed RTSP video connection.

---

qgroundcontrol.pro
src/AutoPilotPlugins/APM/APMCompassCal.cc
src/AutoPilotPlugins/Common/ESP8266ComponentController.cc
src/AutoPilotPlugins/Common/ESP8266ComponentController.h
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/FactSystem/ParameterManager.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/Vehicle/MAVLinkLogManager.cc
src/Vehicle/MAVLinkLogManager.h
src/Vehicle/SendMavCommandTest.cc
src/Vehicle/SendMavCommandTest.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ViewWidgets/CustomCommandWidgetController.cc
src/ViewWidgets/CustomCommandWidgetController.h
src/comm/MockLink.cc
src/qgcunittest/UnitTestList.cc
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h

Support for new Vehicle::sendMavCommand method. This will wait for an ack to come back for the command. If no ack comes back the command will be send again, up to a max number of retries. There is only one command going out to the vehicle at a time in order to verify acts correctly. If a command is already in progress additional commands will be queued.
Converted existing code to use new method and removed old methods which did not verify vehicle reception of command.
Fix for #2975.

Mav command retry work

---

src/QmlControls/QGCToolBarButton.qml
src/ui/MainWindowInner.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml

* Make MainToolbarIndicators reusable by other views
* Change to font based ratio sizing
* Remove all the up/down/sideways references to global properties

Toolbar: Remove global property usage

---

src/Vehicle/MAVLinkLogManager.cc

It's not desired to have automatic log streaming for several reasons:
- There's already SD logging (which is the case for the majority of the
users)
- The link does not provide the necessary bandwidth (eg. wireless telemetry)
@dogmaphobic

MAVLinkLogManager: disable automatic start of log streaming

---

src/QmlControls/ScreenTools.qml

This has always driven me crazy. This seems to be a general-case app-wide fix of the font rendering problems no matter what base font size is selected. Presumably this is because the defaultFontPixelWidth/defaultFontPixelHeight are used throughout the QML codebase to define margins (usually divided by 2). Just ensuring that those numbers are even and hence divide by two into an integer prevents the transforms applied to QML views from corrupting Windows font rendering. 
Before:
After:

Fix most (all?) QML font rendering glitches on Windows

---

src/Vehicle/Vehicle.cc

altitudeAMSL and altitudeRelative do not need divide 1000，the unit is meter and float format。 can you use _handleGlobalPositionInt message for altitudeAMSL and altitudeRelative？ because _handleGlobalPositionInt is default 5Hz and _handleAltitude is 1Hz.

the message handleAltitude

---

src/uas/UAS.cc

This PR fixes an issue that causes QGC to crash when exiting when a joystick is connected. I'm not confident on the series of events when QGC shuts down, but somehow the function to send a MANUAL_CONTROL message is being called after the vehicle's MAVlink connection ceases to exist. This causes a null point exception and a crash.
This code adds one line to check to see if the pointer in question is null.
I'm open to other fixes if there's a better way to do this.
This addresses ArduSub Issue: https://github.com/bluerobotics/ardusub/issues/56

Null pointer issue

---

qgcresources.qrc
src/FlightMap/Images/compassInstrumentArrow.svg
src/FlightMap/Images/vehicleArrowOpaque.svg
src/FlightMap/Images/vehicleArrowOutline.svg
src/FlightMap/MapItems/VehicleMapItem.qml
src/FlightMap/Widgets/QGCCompassWidget.qml

This PR changes the compass icon to an arrow instead of an airplane. This shape better suites the other firmware types besides plane including Copter, Rover, and Sub. The arrow design is loosely based on the compass icon from other digital compasses, such as Garmin watches.
Here are a few screenshots of how it looks at various angles:
This is currently implemented across all firmware types, however we can make it a firmware plugin feature if desired. Please let me know if you'd like me to do that!

Change airplane compass icon to generic arrow icon

---

src/Vehicle/Vehicle.cc

PX4 firmware is inconsistent in returning an Ack from a COMMAND_LONG. Some commands do, some don't. Hence QGC can't use smart retry logic when running PX4 stack.

Turn off command retry logic for PX4 Stack

---

src/QmlControls/ParameterEditorDialog.qml
src/comm/LinkManager.cc

Bad code ordering and remove from list will cause config to delete when last reference goes. The delete pConfig was deleting an already deleted object.

Link reference bug fix

---

src/Vehicle/Vehicle.cc
src/comm/LinkInterface.cc
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/MAVLinkProtocol.cc

Replacement for #4199
Fix for #4198:
* State of decode for first mavlink packet is kept on link by link basis instead of single value for all of QGC.
* QGC will switch to outbound Mav 2 if it gets inbound Mav 2
* QGC will **not** switch to outbound Mav 2 if Vehicle reports Mav 2 capability. This is due to the fact that both SiK Radio and WiFi don't support Mav 2 yet.
* QGC will **not** switch back to outbound Mav 1 from Mav 2 if it gets inbound Mav 1
Note: Multi-vehicle Mav 2 issues are still not fixed / figured out.

Update MAV 2 switching semantics

---

src/Vehicle/MAVLinkLogManager.cc
src/ui/preferences/MavlinkSettings.qml

In response to #4238 I'm disabling logging for non PX4 firmware and also replacing all `qCCritical` messages with `qCWarning` ones.

Disabling MAVLink 2.0 logging for APM.

---

src/Vehicle/Vehicle.cc

* PX4 firmware below 1.5.3 **will not** retry commands
* PX4 firmware which reports no version number info (like custom built master) assumes it has fix and **will** retry commands
Fix for #4341

Add version check to command retry

---

src/FlightMap/Widgets/QGCArtificialHorizon.qml

In response to #3974
It was not working right when pointing straight up or down. Important for rocketry or ICBMs :P
In reality, something changed that caused the angle to end at 270/-270 instead of 180/-180. That in turn would make the display go past its end.

Fixed issue with artificial horizon

---

android/AndroidManifest.xml

In response to #3128 (and others), it seems that by targeting KITKAT instead of LOLIPOP, we should be able to have both Cellular and WiFi communications even when WiFi has no Internet. This is based on what I found here:
https://developer.android.com/reference/android/net/wifi/WifiManager.html#enableNetwork%28int,%20boolean%29
I can't test this as I don't have any Android phone (or an Android tablet with Cellular data). Could someone running Android 5.x or 6.x test and see if this is indeed true? Android 7.x has an additional issue of not connecting to WiFi at all if it doesn't find google.com (no internet access -- issue #4355).
QGC was (arbitrarily) targeting LOLLIPOP_MR1 (API level 22). We don't use anything special to justify that.

Testing Android issues with WiFi and no Internet.

---

src/JsonHelper.cc
src/JsonHelper.h
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/GeoFenceController.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/MissionManager/MissionItemTest.cc
src/MissionManager/MissionItemTest.h
src/MissionManager/RallyPointController.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/MissionManager/VisualMissionItem.cc
src/MissionManager/VisualMissionItem.h

As I was documenting the mission file format I realized that there was no way to generate the v1 format with a survey in it manually. You would need to know the QGC survey creation internals to do it. The new V2 format fixes this problem. QGC now supports both V1 and V2 formats, but only outputs V2 format.

New V2 mission file format

---

src/comm/UDPLink.cc

Explicitly join the default multicast address seems to be required on windows when multicasting telemetry over vpn.

UDP join multicast group for windows client

---

src/Vehicle/MAVLinkLogManager.cc

previously the start log button was always disabled, even for PX4.
Fixes regression from 9d413108f8116a5ba049f41d94929789f799a509
@dogmaphobic @ChristophTobler

MAVLinkLogManager: fix use of wrong variable

---

src/VideoStreaming/VideoReceiver.cc

Calling delete on a socket callback is not safe and this can crash
QGroundControl. Using deleteLater method from socket to perform deletion.

Fix crash by invalid socket deletion

---

src/FirmwarePlugin/FirmwarePluginManager.cc

It was being added each time the function was called.

Add MAV_AUTOPILOT_GENERIC only once.

---

src/ui/toolbar/MainToolBar.qml

When you first launch QGC and nothing is connected, the tool bar has a large blank space where the toolbar items are displayed once a vehicle is connected. This adds a message telling you QGC is waiting for a vehicle to connect.

Add message telling QGC is waiting for a vehicle

---

src/AnalyzeView/ExifParser.cc

Fixes #4416.
* Old format for rational was (ddd/1,mmmm/1000,0/1), new (ddd/1,mm/1,ssss/1000).
* This brings accuracy of representation to sub cm.
@saitej09 can you test this?

Increase accuracy of geotags

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.h

There's probably a better place for this, but some param changes require a reboot to take effect so this seemed like a good place to hide it.

reboot vehicle from param menu

---

src/QmlControls/FactSliderPanel.qml

Add mouse area to the FactSliderPanel in order to avoid unwanted value changes while scrolling, but still allow scrolling to change values if slider is explicitly focused

Add mouse area to the FactSliderPanel in order to avoid unwanted value changes while scrolling

---

QGCCommon.pri
src/ui/MAVLinkDecoder.cc
src/ui/MAVLinkDecoder.h
src/ui/MainWindow.cc

Just a few simple tweaks to improve things. MAVLinkDecoder was not properly parented (the whole threading the right way can of worms) so this PR removes the parent pointer we aren't using (false sense of proper QObject parenting) and uses a signal to quit the thread and move the object back to the creating thread context. MainWindow waits 1s for the thread to finish and then invokes deleteLater on it so the object is destroyed when the event loop returns.
Also turned on contextual information for release builds in the message logger so we have a trace back in source files when users submit logs.

Improve release logging, deal with MAVLinkDecoder shutdown

---

src/QGCPalette.cc

Fix for #4500 
It was using a bogus color encoding and QColor was taking is as zero (black). I'm not sure what I did as that wasn't the color I was editing when I got this change in.

Fix wrong QColor argument encoding.

---

src/QmlControls/ParameterEditor.qml

On Android, when searching for a parameter you could not use the clear button until you closed the Android Keyboard. I could not quite figured out why the text field would not accept changes from within the button's onClicked signal. It just would not, even if forcing focus, reseting it, whatever. What I did was to trigger a timer than handles the clearing.
While at it, I'm also dismissing the keyboard so you don't have to click in two places (to clear the search field and to dismiss the keyboard).

Work around using the Clear button while mobile keyboard is up.

---

src/MissionEditor/MissionSettingsEditor.qml
src/MissionEditor/SurveyItemEditor.qml

Mostly making the controls sizes more consistent and legible. This is a first stab at this. There is still way too much info crammed into one dialog. Help text also makes it too busy but not sure what to do about them.
It was this:
And for now it looks like this:

Tidying up Mission Settings and Survey Settings

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightDisplay/MultiVehicleList.qml
src/FlightMap/MapItems/VehicleMapItem.qml
src/FlightMap/Widgets/QGCCompassWidget.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

These are for the icons shown over the map and the one used in the Compass widget. If nothing is defined, the defaults (current icons) are used.

Allow FirmwarePlugin to provide vehicle icons.

---

src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapEngine.h
src/QtLocationPlugin/QGCMapEngineData.h
src/QtLocationPlugin/QGCMapTileSet.cpp
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGCTileCacheWorker.h
src/QtLocationPlugin/QGeoMapReplyQGC.cpp
src/QtLocationPlugin/QGeoMapReplyQGC.h
src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
src/QtLocationPlugin/QGeoTileFetcherQGC.h

When you have no Internet connection (Tablet out in the field), tile downloading can bog the system down. Specially on Android. That's because the system will try to download all and every tile. As each request normally times out in around a minute, you ended up with hundreds of tile requests in the queue.
This change keeps track of the availability of (real) Internet connection. If there is none, QGC won't bother trying to download any tiles. If you have them cached, they will be displayed. Otherwise it will immediately show a "No Tile" tile.

Dealing with lack of Internet connectivity.

---

src/VideoStreaming/VideoReceiver.cc

This corrects a minor error that will appear at application close if video was never connected while the application was open.

Don't send EOS on pipeline if not streaming video

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/MissionManager/GeoFenceController.cc
src/QmlControls/ParameterEditorController.cc
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h

Use component id from heartbeat. Previous mechanism wasn't needed and didn't work with generic vehicles.

Changed default component id discovery

---

src/QGCApplication.cc
src/comm/BluetoothLink.h
src/comm/LinkConfiguration.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/LogReplayLink.h
src/comm/UDPLink.h
src/ui/preferences/LinkSettings.qml

This PR
- sets autoconnect flag on start for selected UDP link that helps if you use QGC for outgoing connection and for links with another listening port (not only for 14550). To use this feature set checkbox in the link configuration:
-  changes return code of virtual method ```isAutoConnectAllowed``` from true to false. This way allowing to autoconnect only for UDP links and prohibiting for all other link types.

Auto connect on start for UDP links

---

src/ui/MAVLinkDecoder.cc
src/ui/MAVLinkDecoder.h

This fixes integer overflow issues with mavlink 2 msgid's and get the analyze view working for mavlink 2 messages.
Closes https://github.com/mavlink/qgroundcontrol/issues/4479

Fix analyze view to work for mavlink 2.0

---

qgroundcontrol.qrc
src/FlightMap/Widgets/CenterMapDropPanel.qml
src/FlightMap/Widgets/MapFitFunctions.qml
src/FlightMap/qmldir
src/MissionEditor/MissionEditor.qml
src/QmlControls/DropPanel.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/ToolStrip.qml

* New ToolStrip control which replaces DropButtons
* ToolStrip control better matches square visual style of QGC
* Plan view moved over to ToolStrip
* Drop panels which pop out from ToolStrip are the same as before
* This is also prep work for Survey button switching to Pattern which will eventually support a popup to select from multiple complex mission items to insert
* Also possible prep work for new Camera controls showing up in ToolStrip on Fly view
* Fix for Issue #4543
Work left to do (was getting too big, so I cut it off here and will continue on in another pull):
* Zoom Buttons NYI
* Small Screen Optimization
* Use on Fly view

Use new ToolStrip control in Plan View

---

src/comm/BluetoothLink.cc

This is in response to #2910.
It fixes a bug introduced by #4349.
The Bluetooth configuration was not being set and the code would crash when using it.

Fix regression bug with Bluetooth.

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightDisplay/MultiVehicleList.qml
src/FlightMap/Widgets/QGCAttitudeWidget.qml
src/FlightMap/Widgets/QGCCompassWidget.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml
src/FlightMap/qmldir
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h
src/api/QGCOptions.cc
src/api/QGCOptions.h
src/ui/AppSettings.qml
src/ui/toolbar/MainToolBarController.h

Move instrument widget off to a loader.
This allows a custom plugin the option to replace the entire widget with its own.
In the process of working with the instrument widget, I've removed a hole pile of unnecessary *properties*, which where passed around and around. Things like *active*, which would indicate if there was an active vehicle. And others such as *heading*, *roll*, *pitch*, etc., which are all properties of Vehicle, which is accessible globally.
While at it, removed some unused cruft from the toolbar controller. I'm looking into eventually removing the toolbar controller and move its functionality to Vehicle where it truly belongs. The toolbar was the very first QML code added to QGC, long before the Vehicle controller came into existence.

Instrument widgets

---

qgroundcontrol.qrc
src/MissionEditor/ComplexMissionItem.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/SurveyComplexItem.qml
src/MissionManager/ComplexMissionItem.h
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/SurveyMissionItem.h
src/QmlControls/QGroundControl.Controls.qmldir

Previously the visuals for the Survey complex mission item where hardwired into the MissionEditor (Plan View) Map control. Up until now I hadn't figured out how to dynamically add the needed controls to the Map since the Map controls work differently than the rest of QML controls. Now that I know how to do that I changed it such that the Qml for complex item visuals is now specified by ComplexMissionItem. Then the map loads a ComplexMissionItem control for each complex item, which then dynamically loads the control(s) for the complex item visuals.
Basically all of that means new complex mission items can be added to the system without modifying the MissionEditor control.

Complex item visual dynamically added to map

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

New semantics:
* When a new item is inserted we look backwards from that item for a previous MAV_CMD_NAV_WAYPOINT and use the altitude and frame from that item as the defaults for the new item.
* The semantics above only apply to newly added MAV_CMD_NAV_WAYPOINT items
* Removed support for look back/set on new items for acceptance radius. Since acceptance radius is not normally shown on new items it's dangerous to override the default (which is 0) on something that isn't shown.
This differs from previous support which would find the last mission item which specified a coordinate and was not a land item. The issue with that method were:
* If you inserted a new item in the middle of a mission it would still use the value from the last mission item. This just didn't make any sense.
* I tried …

Plan: Change semantics for pulling altitude from mission items for new items

---

src/FirmwarePlugin/APM/APMFirmwarePluginFactory.cc
src/FirmwarePlugin/APM/APMFirmwarePluginFactory.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/FirmwarePluginManager.cc
src/FirmwarePlugin/FirmwarePluginManager.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePluginFactory.cc
src/FirmwarePlugin/PX4/PX4FirmwarePluginFactory.h
src/MissionManager/MissionCommandTree.cc
src/QmlControls/QGroundControlQmlGlobal.cc

This allows a plugin to override the list of available vehicle types.

Add FirmwarePluginFactory::supportedVehicleTypes support

---

src/VehicleSetup/FirmwareImage.cc

`_binFormat` was never set to true, as the function returned before that assignment, resulting in failing uploads of bin fails

fixed uploading of bin files

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UASInterface.h

This could be used for the other vehicle types, but I was not sure if it is supported or handled on APM side, so it is only available for Sub.

Add calibrate pressure button in sensors page, enabled only for ArduSub

---

.travis.yml

Paring back OS X travis builds to a single installer only build since travis OS X sucks so bad at the moment it's taking 3-6 hours to clear the pull queue.

Paring back OS X travis to installer only

---

src/FactSystem/SettingsFact.cc
src/FactSystem/SettingsFact.h
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h
src/ui/preferences/GeneralSettings.qml

Modified QCGCorePlugin settings override mechanism to support full modification of setting meta data as well as visibility:
```
/// Allows the core plugin to override the setting meta data before the setting fact is created.
///     @param metaData - MetaData for setting fact
/// @return true: Setting should be visible in ui, false: Setting should not be shown in ui
virtual bool adjustSettingMetaData                  (FactMetaData& metaData);
```
Plumbed visibility bits into General Settings page:
* Units, AutoConnect support individual setting visible
* Remainder of visibility on settings is WIP

Add support for SettingsFact::visible

---

src/FlightDisplay/FlightDisplayView.qml
src/ui/MainWindowInner.qml

Added a root loader to help deep nested children to show an element in the middle of the root Window.
While at it, fixed annoying QML error that would show when QGroundControl.videoManager would go out of scope.

Root loader

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

QGeoCoordinate has 3 components: latitude, longitude and altitude. Up to now, only lat/lon were set, leaving the altitude fixed at 0. I'm now adding the altitude so I can compute an accurate distance between QGC and the vehicle.
In addition, instead of using functions to set lat/lon/alt, I'm setting them all at once and generating a single signal instead of multiple signals for the same variable as it was the case.

Added altitude to the Vehicle coordinate (QGeoCoordinate)

---

src/QmlControls/QGCComboBox.qml

Currently, settings are easily changed by accident when scrolling a page, when the mouse passes over a combobox while scrolling. It is also easy to not notice this when it occurs. This patch will disable changing the options on comboboxes via scrolling, by handling the event (do nothing) with a mousearea over the combobox.

Disable scrolling on QGCComboBox

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h

This way third parties can use PX4FirmwarePlugin as base class and
override as needed

PX4FirmwarePlugin: Virtuals should be override not final

---

src/VideoStreaming/VideoReceiver.cc

I have been getting crashes on windows with rtspsrc. Took a bit of hunting with the debugger but ultimately I realized the argument passed for timeout is a 32-bit value.  Since g_object_set uses varargs and the argument size was not properly matched, the null to indicate the last arg was read as part of the timeout and undefined behavior resulted when trying to interpret the remaining varargs. 
Additionally this PR includes 17msec of buffering on rtsp sources to give rtpjitterbuffer a chance to work; the impact should be imperceptible.

Fix rtspsrc timeout storage type, add a few ms of jitterbuffer

---

src/AnalyzeView/AnalyzeView.qml
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightDisplay/VirtualJoystick.qml
src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/ScreenTools.qml
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/VehicleSetup/SetupView.qml
src/ui/linechart/ChartPlot.cc
src/ui/linechart/LinechartWidget.cc
src/ui/preferences/GeneralSettings.qml

* Font point size
* Virtual joystick
* Indoor/Outdoor palette
This will disconnect the QGCOptions based third party overrides in favor of the new mechanism.

More moves of settings to new support

---

src/FlightDisplay/FlightDisplayViewVideo.qml
src/Settings/Video.SettingsGroup.json
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/ui/preferences/GeneralSettings.qml

Up to now, the video display for video streaming would stretch to fit the window. This new setting allows you to set the proper aspect ratio. If the window is wider than the video, you get black bars on the sides. Setting the aspect ratio to 0.0 makes it ignore it and it will stretch the video to fit.
Also changed the "NO VIDEO" message to a more optimistic "WAITING FOR VIDEO" :P

Allow setting the video streaming aspect ratio.

---

src/MissionEditor/MissionSettingsEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/QmlControls/QGCComboBox.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/ToolStrip.qml

* Increase touch area on ToolStrip buttons
* QGCTextField was setting height instead of implicitHeight which was causing it the be resized smaller when used in a GridLayout
* QGCComboBox and QGCTextField use same height semantics for mobile

Control sizing on mobile

---

src/QmlControls/DropPanel.qml
src/QmlControls/ToolStrip.qml

Previous mechanism was exposing possible bug in Qt which would prevent
clicks from work on ToolStrip buttons after cancel MouseArea was hidden.
Fix for #4641

Modified DropPanel cancel MouseArea creation

---

src/ui/MAVLinkDecoder.cc

I'm seeing some bogus messages coming across (that's another issue for another PR). MAVLinkDecoder was not testing their validity and crashing. This puts a NULL pointer guard before using it.

Test message info before using it.

---

src/FactSystem/FactControls/FactTextField.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemEditor.qml
src/QmlControls/QGCTextField.qml
src/QmlControls/ToolStrip.qml

* FactTextField/QGCTextField: Drop focus after done on Virtual Keyboard. This is because some versions of android show a big IP arrow when a control has focus. This gets really annoying if you just entered a new value.
* Increase touch area on mission item editor hamburger
* ToolStrip control now automatically determine if it should show/hide text base on available screen real estate. it will adjust as you resize window as well. Previously it based this on ScreenTools.isSmallScreen but that was turning off text too early. This new way it's always just right.

Small Screen and Touch usability changes

---

src/FactSystem/ParameterManager.cc
src/Vehicle/Vehicle.cc

This adds some information about the autopilot firmware that would be useful in troubleshooting issues on user forums, among other things.
Here are some examples of what the parameter file header looks like:
APM:
```
#
#
```
PX4:
```
#
#
```

Add firmware information to parameter file header

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/CompassRing.qml
src/FlightMap/Widgets/QGCAttitudeWidget.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/ValuesWidget.qml
src/FlightMap/qmldir
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h

* New style combined compass and attitude instrument. Reason is to take less space, leaving more for instrument values if wanted.
* Controlled by setting available from Gear thingy. Defaults to new visuals. Check Show large compass to go back to old style.
* Also changed heading display in new and old style to always 3 digits.
Consider this a WIP. 
Fix for #4691

Default to new Compass Ring style

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h
src/ui/toolbar/MainToolBarIndicators.qml

In response to #4701 
The list of indicators is now provided by the FirmwarePlugin. The base class defines the default list of indicators. I went ahead and implemented a "specialized" implementation for the ArduSub plugin. I only removed the GPS, just to show where to add/change/remove indicators for a specific firmware/vehicle.
See ArduSubFirmwarePlugin.cc/h for how to implement your own list.

Moved toolbar indicator list from QGCCorePlugin to FirmwarePlugin.

---

src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionManager/FixedWingLandingComplexItem.cc
src/QmlControls/ToolStrip.qml

Fixes for #4706:
* ToolStrip toggle buttons now correctly uncheck themselves when a button with a DropPanel is clicked
* FW Landing Pattern: Fix loiter point rotation when changing landing heading from item editor

FixedWing Landing Pattern fixes

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h

This dynamically sets the param load retry timeout based on the measured param receiving rate. The previous fixed timeout did not account for different link speeds, resulting in unnecessary high waiting times.
I tested with different HW (SITL, Pixracer, Pixhawk), different connections (UDP, USB, Pixracer WiFi), and various param drop scenarios (none, single, burst of 50, every second param).
Even with 50% drops, I still got an acceptable param load time.
Results: the timeout is large enough so that it never triggered too early. For a usb connection I got 60ms, for a pixracer via WiFi 200ms timer timeout.
@DonLakeFlyer The default timeout of 30s is incredibly high. I see that it has been recently changed due to some problems with APM (https://github.com/mavlink/qgroundcontrol/pull/4687). …

dynamic param load timeout

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h

* Main issue was a bad push (by me: testing change slipped through) which bumped to initial request timeout from 3 seconds to 30 seconds
* Created new initial request retry mechanism for when initial index based parameters are missing from initial load. This leads to the fastest possible initial param load even when params are missing from initial request. When you hit this case:
* The initial timeout will fire (takes 3 seconds)
* A batch of 10 params will be requested
* As responses are received for those the the queue is immediately brought back up to 10 by requesting a new index without waiting for the timeout to fire.
* All of the existing retry logic for 5 retries and so forth stays the same
Fix for #4716

Faster initial request param retry logic

---

src/FactSystem/SettingsFact.cc
src/QGCApplication.cc

* Calls to QSettings.clear() were not in the right place
* New settings versions not alway written out
* Core plugin settings overrides which are hidden are now forced to always come from default value

Fix settings clearing and plugin overrides

---

qgroundcontrol.qrc
src/FlightMap/MapItems/MissionItemIndicatorDrag.qml
src/MissionEditor/MissionItemEditor.qml
src/QmlControls/QGCMouseArea.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/ScreenTools.qml
src/QmlControls/ToolStrip.qml
src/ui/toolbar/MainToolBar.qml

To Recap: The QGC UI is almost completely based on using ratios of default font pixel width/height for sizing and positioning. This all works fine on desktop builds where you are using a mouse to click on things. The problem is on mobile touch screen all you have is your finger. Which is way less accurate and requires larger touch areas to be usable. The touch areas which work on desktop don't work on mobile.
Before these changes:
* The font sizing on mobile devices was bumped up such that the whole UI got larger which in turn provided larger touch areas.
* The QGC set of controls adjust their sizing to be larger on mobile to provide larger touch areas.
* Things like drag areas were also increased in size when running on mobile to improve touch areas.
All of the above sort of works but in …

New mechanism for better "touch-ability" of controls on mobile

---

src/MissionEditor/MissionItemEditor.qml
src/MissionEditor/SimpleItemMapVisual.qml
src/QmlControls/MissionItemIndexLabel.qml
src/QmlControls/QGCMouseArea.qml

Just specify fillItem property and the mouse area will fill to that as well as handle touch expansion on mobile.

Automatic sizing support in QGCMouseArea

---

src/QGCApplication.cc
src/QGCApplication.h
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/ui/preferences/GeneralSettings.qml

No more user prompting. You have to set the telemetry save directory before you use it. Files are named: YYYY-MMM-DD HH-MM-SS.mavlink
Fix for #4494, #3112.

Telemetry logs are now saved with generated file name

---

src/FlightMap/MapItems/PolygonEditor.qml

Touch to set first point show point indicator:
Touch to set second point of polygon shows line segmemnt
Remaining points work as before showing polygon:

Better mobile visuals for polygon draw

---

qgroundcontrol.pro
src/FlightMap/MapItems/MissionItemIndicatorDrag.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionEditor/SurveyMapVisual.qml
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/QGCQGeoCoordinate.cc
src/QGCQGeoCoordinate.h
src/QmlControls/QmlObjectListModel.h

Now when you add a Survey item a 4 sided polygon is added automatically:
You can now always use the drag handles (no "+" sign) to adjust the polygon:
Click the "+" splitter to split a segment in two:
Click on a drag handle to remove a polygon vertex:
And I now win the award for writing the most crazy-ass qml in the world! Yikes.

Major rework of polygon editing

---

build_ios.sh
src/FlightMap/Widgets/QGCPitchIndicator.qml

The font size for the Attitude Indicator was still using a proportional size system. That does not work on devices with non default font sizes.

Tweaking Attitude Indicator

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h

Previous version would require plugin to override all the isFooFlightMode methods to work correctly. Now just change mode name and regular plugin code works correctly.

PX4FirmwarePlugin: Rework flight mode override mechanism

---

src/MissionEditor/MissionEditor.qml

This closes out all value editing before the new item is added. Fixes the bug where you enter a new altitude in last waypoint, don't press enter and then add a new one. In that case altitude would be set after new item was added. Hence it would not carry to new item.
There's an issue in here somewhere about that. Will find and mark fixed later.

Plan - Mission Item Editors: Clear current item before adding new one

---

src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h

* Fix degenerate case wher landing point is inside loiter radius. Tangent moves to loiter coordinate.
* Correct setting of dirty bit (#4768)
* Loiter radius visualization using wrong value (would use feet incorrectly)

Fixed wing landing pattern fixes

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/VehicleSetup/SetupView.qml

If another panel is controlling vehicle connection/disconnection, we need a way to skip the panel from switching away from underneath you.

Allowing to skip going to the Summary page.

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/MapItems/MissionItemView.qml
src/MissionEditor/FWLandingPatternEditor.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemEditor.qml
src/MissionEditor/MissionSettingsEditor.qml
src/MissionEditor/MissionSettingsMapVisual.qml
src/MissionEditor/SectionHeader.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionSettings.FactMetaData.json
src/MissionManager/MissionSettingsComplexItem.cc
src/MissionManager/MissionSettingsComplexItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/MissionManager/VisualMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/Vehicle/Vehicle.cc

The Mission Settings Item in the Plan view is not a complex item which supports settings various mission defaults for waypoint height, flight speed and camera/gimbal settings. It also shows a work in progress on sections within a larger mission item editor. Here is what you see at first:
You can click to open up sections:
On short screens the sections act like radio buttons such that only one is open at a time.
All of this new section show/collapse stuff is WIP and will be refined as I apply to more item editors.

Plan: New MissionSettingsComplexItem

---

src/AutoPilotPlugins/AutoPilotPlugin.h
src/MissionEditor/MissionEditor.qml
src/QmlControls/ToolStrip.qml
src/VehicleSetup/SetupView.qml
src/api/QGCOptions.h

* Allow QGCOptions to hide Firmware page.
* Allow vehicleComponents to signal change. This allows plugins to changes pages based on advanced mode.
* Plan: Animate opacity of Sync button when dirty

Core plugin changes

---

src/FirmwarePlugin/APM/MavCmdInfoFixedWing.json
src/FirmwarePlugin/APM/MavCmdInfoMultiRotor.json
src/FirmwarePlugin/PX4/MavCmdInfoFixedWing.json
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionSettingsComplexItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SurveyMissionItem.h
src/MissionManager/VisualMissionItem.h

Mission items which do not specify a coordinate, but do specify an altitude now handled correctly.
Fix for #4787.

MissionCmdUIInfo: New support for specifiesAltitudeOnly

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/api/QGCOptions.h

New method in QGCOptions:
```
/// If returned QString in non-empty it means that firmware upgrade will run in a mode which only
/// supports downloading a single firmware file from the URL. It also supports custom install through
/// the Advanced options.
virtual QString firmwareUpgradeSingleURL        () const { return QString(); }
```
This allows the core plugin to use Firmware Upgrade in a mode which only has a single URL to download from. It also causes the Firmware Upgrade UI to modify itself to fit this mode. The UI modification part is a work in progress. But the actual single firmware mode upgrade capability is working.

Add new single firmware mode from QGCOptions

---

src/QtLocationPlugin/QGCMapEngineData.h
src/QtLocationPlugin/QGCMapTileSet.cpp
src/QtLocationPlugin/QGCMapTileSet.h
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGCTileCacheWorker.h
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h
src/VehicleSetup/SetupView.qml

This is the fist part of Import/Export of map tiles sets.
This PR implements export and import from disk. You can select what sets you want to export and these will be saved into a file. You can then "import" this file into another instance of QGC.

Map Tile Set Import/Export

---

src/FlightMap/MapItems/MissionItemIndicator.qml
src/MissionEditor/SimpleItemMapVisual.qml
src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/ComplexMissionItem.h
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/MissionManager/MissionSettingsComplexItem.cc
src/MissionManager/MissionSettingsComplexItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/MissionManager/VisualMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/QmlControls/MissionItemIndexLabel.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

This is about 90% complete:
* In order for the gimbal yaw to show up you need to specify a gimbal yaw in either mission settings or a waypoint. From the first time you set a gimbal yaw, the indicators will show up on subsequent waypoints.
* I changed the waypoint indicator graphics yet again to be able to better show gimbal yaw
* The new waypoint indicators don't work well with long labels. I'll fix that.
* It currently assume the vehicle yaw will stay in the direction of the next waypoint. I'll fix that.

Show gimbal yaw on map

---

qgroundcontrol.qrc
src/MissionEditor/MissionEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/PlanToolBar.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/ui/MainWindowInner.qml

Now when you go to plan view you see this:
@dogmaphobic  Had the fantastic idea to do this. I just implemented it:
* Reuses toolbar real estate to show mission stats
* If the mission is dirty a button will show up on the right saying either "Upload" or "Save" depending on whether you are connected to a vehicle.
* When you click the Fly button to go back to Fly view you will be prompted to Upload/Save if your mission is dirty before you leave.
Hoping this makes the user model of needing to send the vehicel to the vehicle a little more understanable. It's work in progress from a standpoint of user model but everything there is working.

New toolbar and user model for plan view

---

src/MissionEditor/MissionEditor.qml
src/VehicleSetup/VehicleComponent.h
src/api/QGCCorePlugin.h
src/ui/toolbar/MainToolBarIndicators.qml

* Added confirmation dialog to turning and advanced mode
* QGCCorePlugin can override advanced mode confirmation message
* Add signal VehicleComponent::setupSourceChanged. This allows plugins to show component panels in summary not not show the full setup page.
* Fixed big where current item not set correctly after adding complex item

CorePlugin changes

---

src/MissionManager/MissionManager.cc

Code was incorrectly sending altitudes in MISSION_ITEM_INT integer format.
Fix for: https://github.com/PX4/Firmware/issues/6884. And probably has something to do with bad altitude in #4787.

MISSION_ITEM Altitude is not in _INT format

---

src/MissionEditor/PlanToolBar.qml
src/ui/MainWindowInner.qml

- Eat mouse events within the plan toolbar, preventing them from reaching the main toolbar, which is underneath it.
- Making the main toolbar transparent when the plan toolbar is visible.
- Using the same translucent color as the main toolbar.

Plan toolbar tweaks

---

src/ui/MainWindowInner.qml

There was a bug where you went to plan and then a vehicle connected which required setup. This then automatically took you to Setup. But the plan toolbar was still there.

Hide plan toolbar when switching views

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

* Starts/Stops on arm/disarm
* It's in the Vehicle FactGroup so it's available in the instrument pane

Add flightDistance to Vehicle FactGroup

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/QmlControls/QGCSlider.qml
src/VehicleSetup/JoystickConfig.qml

This pull request changes the Joystick._exponential property from bool to float. It also replaces the exponential checkbox in the joystickConfig.qml with a slider allowing the user to set the exponential as they please.

Exponential Slider

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionSettings.FactMetaData.json
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsItem.h
src/PlanView/MissionItemEditor.qml
src/PlanView/MissionSettingsEditor.qml
src/PlanView/PlanToolBar.qml
src/PlanView/PlanView.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QFileDialogController.cc

The way you work with missions in QGC has changed massively. There is no longer the concept of "Sync". In fact there is no Sync button at all any more. Let me walk you through it. Let's walk through and example where you are connected to a vehicle which has no current mission on it. It starts out with the mission editor looking like this:
You can either load an existing mission or create a new one. When you load an existing mission by clicking one of the mission files, the mission will be loaded and also sent automatically to the vehicle.
You can create a new mission by just started to add way points. New missions can be named as well. In this example I've named my mission. You can see that the list of mission to load is now gone.
Here I've added a bunch of waypoints. That's all the same. …

New Plan a mission sync/save user model

---

src/FirmwarePlugin/PX4/MavCmdInfoCommon.json
src/FirmwarePlugin/PX4/MavCmdInfoFixedWing.json
src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/MissionController.cc
src/ui/MainWindow.cc
src/ui/MainWindow.h
src/ui/MainWindow.ui

* The ui info was incorrect for PX4 MAV_CMD_NAV_LAND definition. This was preventing the fly view from shows land items correctly.
* You can now roundtrip a FW Landing Pattern through the vehicle and it will come back as a complex item
* Fixed a bug in FW Landing mission file loading where heading would get screwed up
Plus:
* Fix broken zoom buttons on Fly view
* File and Widgets menu only shown in advanced mode

Fixed Wing Landing Pattern Bug Fixes

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/PlanView/PlanView.qml
src/api/QGCOptions.h

* sensorsHaveFixedOrientation - true: don't show orientation ui diring calibration, false: default
* wifiReliableForCalibration - true: don't warn abot flaky wifi calibration, false: default
* removed showSensorCalibrationOrient
Made code changes to use these new values.

QGCOptions changes

---

src/Joystick/Joystick.cc

This pull does two things.
1: it removes a section of code that made it so that the output of an axis (manual control signal) reached 100% when the input from that axis was only at ~75%. This means that the last 25% of axis movement was useless. I'm not sure what the intended purpose of this code was.
2: Previously, if an axis had deadband applied then the maximum output on that axis would be 100%-percentDeadband. To give an example, if an axis had 40% deadband then moving the stick all the way over would only result in 60% at the output. This pull causes the sensitivity of each axis to scale with deadband so that 100% input always results in 100% output.

Improve deadband

---

src/AutoPilotPlugins/PX4/CameraComponent.qml
src/QmlControls/VehicleSummaryRow.qml

* Increased width of Combo boxes to prevent most clipping
* Middle column text had fixed width which would not work on all screen size, font combinations
* Because of above middle column change, was unable to maintain trigger period field matching fields in group box above. I may figure out a way to do this when I move to the Safety page and do the same fixups.

Camera setup sizing/position combo sizes

---

src/FlightMap/Widgets/CenterMapDropButton.qml
src/PlanView/PlanToolBar.qml
src/QtLocationPlugin/QMLControl/OfflineMap.qml

If the Rectangle containing the Add New Set options is a child of Map, mouse commands bleed through to the map.
Aldo made the slider button slightly larger for mobile (but not Tiny Screens as these have a proper larger font size)
Also cleared up a couple of JavaScript exceptions.

Moving Add New Set as a sibling of Map rather than a child.

---

src/PositionManager/PositionManager.cpp
src/PositionManager/PositionManager.h
src/api/QGCCorePlugin.h

When creating a position source, check if custom plugin provides one. If it does, it will return an instance of its own `QGeoPositionInfoSource` position source. Otherwise QGC will use the default position source.

Allow custom plugin to provide its own position source.

---

src/MissionManager/CameraSection.FactMetaData.json
src/MissionManager/CameraSection.cc
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/Survey.SettingsGroup.json
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/PlanView/SurveyItemEditor.qml

Although internally there is support to not turn images off in turnaround. It is not exposed in the ui. Mainly because I couldn't think of a good case where this was a good thing.
Also set up scaffolding for Hover and Capture support.

Plan: Support for images in turnaround on/off

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/PlanToolBar.qml

Firmware plugin can now support battery information:
```
/// Returns the data needed to do battery consumption calculations
///     @param[out] mAhBattery Battery milliamp-hours rating (0 for no battery data available)
///     @param[out] hoverAmps Current draw in amps during hover
///     @param[out] cruiseAmps Current draw in amps during cruise
virtual void batteryConsumptionData(Vehicle* vehicle, int& mAhBattery, int& hoverAmps, int& cruiseAmps) const;
```
Plan view then uses this information to display number of batteries needed and first battery change waypoint in the Plan toolbar.

Plan: Support battery calculations

---

qgcresources.qrc
qgroundcontrol.pro
qgroundcontrol.qrc
src/AnalyzeView/AnalyzeView.qml
src/AnalyzeView/MavlinkConsoleController.cc
src/AnalyzeView/MavlinkConsoleController.h
src/AnalyzeView/MavlinkConsoleIcon.svg
src/AnalyzeView/MavlinkConsolePage.qml
src/QGCApplication.cc
src/QmlControls/ScreenTools.qml
src/QmlControls/ScreenToolsController.cc
src/QmlControls/ScreenToolsController.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

This PR adds mavlink console support to the analyze page. 
I have tested it over USB with recent PX4 firmware and it seems to do decent job. Very basic ANSI code handling is done so that top(like) applications work as expected. As of right now I don't have command history; you just type your command into the text field at the bottom and press enter to issue it over mavlink. 
Action shot:
Would be happy to get feedback and improve this so we can get it merged.

Add mavlink console support

---

src/QmlControls/QGCComboBox.qml
src/QmlControls/ScreenTools.qml

Starting with Qt 5.7+ (5.5 worked correctly) combo boxes on Android have the following bugs:
* At random time the items in the dropdown would get created out of order. Thus breaking all references to currentIndex. This is caused by a bug in Instantiator which sometimes caused the object from the model to be added out of order.
* At random times the dropdown would be placed in the wrong spot. This is caused by same random bug in the usage of Control as the base for ComboBox.
After close to a full day of trying to find workarounds I gave up and wrote my own QGCComboBox from scratch using parts of the Qt implementation. It doesn't screw up order. And it gets the dropdown position more right than the Qt implement. I can't get it fully right because it depends on some crazy internal C++ stuff …

Fix the stupid )(&*@#$)*(& android combox box problem

---

src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGeoMapReplyQGC.cpp
src/QtLocationPlugin/QGeoMapReplyQGC.h
src/QtLocationPlugin/QGeoTileFetcherQGC.cpp

QGC's QtLocation plugin monitors Internet availability and only actually makes requests if Internet is available. This is to avoid Qt flooding us with requests, which make take up to 30 seconds to timeout if the network is active but no WAN access exists.
This fixes the case where there is a transition from available to NOT available. The code would only work if you started off with no Internet and later gained access. Now it handles any case.
In addition, the plugin would return a fake tile (*No Tile Found*) to fulfill the request so you would have something other than just a white nothingness on the screen. Well, even though we handle the cache ourselves, Qt will still cache a little bit. Enough to "cache" those fake tiles and never ask for them again, even if the Internet connection is …

Handle network availability transitions.

---

qgroundcontrol.qrc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionsController.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/MainWindowInner.qml
src/ui/toolbar/ArmedIndicator.qml
src/ui/toolbar/MainToolBar.qml

It's not very pretty but functionally it works:
* This shows up in the toolbar if a vehicle has auto-disarm turned off or if the vehicle is a fixed wing. Still discussing whether this should always be there. The reason for fixed wing is that a fixed wing vehicle doesn't spin props like multi-rotor so it isn't very clear whether the vehicle is armed or not.
* If you click on it you can arm/dismarm with a confirmation. Clicking does nothing if you are flying (still thinking about what to do here).

New Arm/Disarm toolbar indicator

---

src/FirmwarePlugin/PX4/MavCmdInfoCommon.json
src/FirmwarePlugin/PX4/MavCmdInfoMultiRotor.json
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MavCmdInfoFixedWing.json
src/MissionManager/MissionCommandUIInfo.cc
src/MissionManager/MissionCommandUIInfo.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SurveyMissionItem.cc
src/PlanView/SimpleItemEditor.qml

* Added new setting for MissionCmdParamInfo: nanUnchanged. This indicates that this CMD_LONG parameter supports NaN to signal the value is unchanged.
* Use this new settings on the heading params for the appropriate commands. Also fixed up a bunch of problems with PX4 MavCmdInfo capabilities being out of date.
* Update SimpleItemEditor to support NaN fields.
Here is what it looks like:
* Check the box for Heading to specify a heading
* Leave unchecked to set as NaN which means leave heading alone
Fixes for: #4905, #4902

Add support for NaN in mission command params

---

src/FlightDisplay/FlightDisplayView.qml
src/QmlControls/ToolStrip.qml

@jaxxzer I reversed to initial state of the toolstrip. If there is no vehicle the ToolStrip always shows. It's only after the vehicle shows up that it used guided mode to hide. I don't like that fact that for the majority use case (guided mode supported) it comes and goes which is strange visually. So I've switched the strangeness to the minority use case.e

Fix ToolStrip sizing/visability

---

src/MissionManager/QGCMapPolygon.cc

Without that it will crash when you load a mission.

Generate polygon model when loading from json

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml

With the "Set Info" dialog hidden, there was no way to "Delete" a set.

Fix offline map where “Set Info” was hidden under “Add New Set”.

---

QGCCommon.pri
tools/get_xcode_version.sh

For example:
```
crc_accumulate(crc_extra, &msg->checksum);
```
in https://github.com/mavlink/c_library_v2/blob/fb411385d5f00300ab5d04c5adb08e7e17670d58/mavlink_helpers.h#L245
You would end up with a warning:
```
<...>/qgroundcontrol/libs/mavlink/include/mavlink/v2.0/mavlink_helpers.h:467:21: warning: taking
address of packed member 'checksum' of class or structure '__mavlink_message' may result in an
unaligned pointer value [-Waddress-of-packed-member]
crc_accumulate(c, &msg->checksum);
^~~~~~~~~~~~~
```

Xcode 8.3 has issues on how MAVLink accesses message structure members.

---

qgroundcontrol.pro
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/Widgets/MapFitFunctions.qml
src/JsonHelper.cc
src/JsonHelper.h
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/PlanElementController.cc
src/MissionManager/PlanElementController.h
src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointController.h
src/PlanView/MissionItemEditor.qml
src/PlanView/PlanToolBar.qml
src/PlanView/PlanView.qml
src/QGCApplication.cc
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/Vehicle/Vehicle.cc

This is the first pull in a sequence of pulls which eventually will fix the incredibly nasty user model problem which is that if you start planning a mission offline and then you connect a vehicle. The mission you were planning just mysterisouly disappears. Needless to say that can be quite annoying. I had "forgotten" about this. Mainly I think because it was such a royal pain to fix.
* The first major change is to the user model of dealing with missions, geo fences and rally points. Previously these were treated as individual elements. Each needing there own file load/save, upload/download and so forth.
* The new model is that there is just one top level thing call a "Plan". A Plan file (file extension .plan) contains a mission, geo-fence and rally points in a single file. When you …

Use a master controller for all Plan elements

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/MissionManager/MissionController.cc
src/MissionManager/PlanMasterController.cc
src/PlanView/PlanToolBar.qml
src/PlanView/PlanView.qml

* Added new FirmwarePlugin::hasGimbal method:
```
/// Used to determine whether a vehicle has a gimbal.
+    ///     @param[out] rollSupported Gimbal supports roll
+    ///     @param[out] pitchSupported Gimbal supports pitch
+    ///     @param[out] yawSupported Gimbal supports yaw
+    /// @return true: vehicle has gimbal, false: gimbal support unknown
+    virtual bool hasGimbal(Vehicle* vehicle, bool& rollSupported, bool& pitchSupported, bool& yawSupported);
```
* If vehicle is known to have gimbal pitch support and a Survey is added the gimbal will automatically be pitched straight down in Mission Settings.

Plan: Survey gimbal

---

src/PlanView/MissionItemEditor.qml
src/QGCPalette.cc
src/QGCPalette.h
src/QmlControls/QGCToolBarButton.qml
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h

* QGCCorePlugin can now override the color palette on a case by case basis. ```QGCCorePlugin::paletteOverride(QString colorName, QGCPalette::PaletteColorInfo_t& colorInfo)```
* Added a new palette entry for the misison item editor backgrounds

Allow core plugin to override palette

---

src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h
src/ui/preferences/GeneralSettings.qml

For Video Streaming usecase, QGroundControl doesnt support changing of
Video Source or URI settings. Restart of QGroundControl application was
required for the changes to get applied. The issue is now resolved by
restarting the video receiver pipeline with new video source/setting.
Signed-off-by: lbegani <lalit.kumar.begani@intel.com>

Support Video Source & Setting Changes Runtime

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/MissionManager/MissionController.cc
src/MissionManager/SimpleMissionItem.cc

When editing offline assumption is the most permissive in that it assume multi-rotor will NOT yaw to next waypoint. This always showing the Heading value while offline editing.

Plan: Show/Hide Heading in waypoint item based on yaw to next wpt setting

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/MissionManager/SpeedSection.cc
src/Settings/App.SettingsGroup.json

I was trying to be a little too fancy to and pull hover/cruise speeds from actual vehicle params when connected. Unfortunately it all got too complicated and wasn't working correctly. So I backed off to only using the values from settings.
The code I chanaged was buggy and could have cause a hover speed of 0 to set set in settings. If you are in this state you can fix with a settings clear.

Plan: Default hover/cruise speed, stop trying to pull from vehicle

---

src/FactSystem/Fact.cc
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/FlightMap/Widgets/ValuesWidgetController.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h

* Flight Time is now available from the Values Widget: Vehicle.flightTime
* Default Values Widget setup includes Flight Time
Existing QGC users who have already modified the Values Widget will need to add Flight Time manually if they want it.

Flight timer

---

src/Settings/App.SettingsGroup.json

Decided to back to the max altitude of 400ft. Instead third parties can set as they like in their versions using settings override.

Mission settings: No max altitude

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/AutoPilotPlugins/Common/SyslinkComponent.cc
src/AutoPilotPlugins/Common/SyslinkComponent.h
src/AutoPilotPlugins/Common/SyslinkComponent.qml
src/AutoPilotPlugins/Common/SyslinkComponentController.cc
src/AutoPilotPlugins/Common/SyslinkComponentController.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/QGCApplication.cc
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/LinkManager.cc
src/comm/QGCSerialPortInfo.cc
src/comm/USBBoardInfo.json

- Adding support for flashing the Crazyflie 2
- Also adds a basic GUI for reconfiguring the radio on it
- So far supported via reflashing with PX4 (http://dev.px4.io/hardware-crazyflie2.html)
@dagar  I set up the firmware paths to point to px4-travis. Can you set it up to upload the build for the `crazyflie_default` target?

CF2 Support

---

src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/MissionController.cc
src/PlanView/CameraSection.qml

* Camera section only includes Mode if FirmwarePlugin reports support for MAV_CMD_SET_CAMERA_MODE
* Plan - Mission Settings: Photo mode only set automatically for Survey is FirmwarePlugin reports support for MAV_CMD_SET_CAMERA_MODE
Fix for #5120

Optional camera mode support

---

qgroundcontrol.pro
src/AnalyzeView/ExifParser.cc
src/AnalyzeView/ExifParser.h
src/AnalyzeView/GeoTagController.cc
src/AnalyzeView/GeoTagController.h
src/AnalyzeView/PX4LogParser.cc
src/AnalyzeView/PX4LogParser.h
src/AnalyzeView/ULogParser.cc
src/AnalyzeView/ULogParser.h
src/Vehicle/Vehicle.cc

@LorenzMeier @DonLakeFlyer I removed the major Survey command changes, and added a tiny mod to allow retraction of camera lenses when mission is complete. It will not affect any existing setups, but still allow fully featured support on the autopilot side till we can phase in the new commands.
Open concerns : 
1. With default Survey settings, we should be capturing images even on turnarounds to optimize 3D reconstruction. This is currently not the case, and I don't see a way to change it from the UI.
2. The camera is not enabled till the 1st survey waypoint. For cameras supporting power control, this means ~3s for them to bring the lens out and start shooting. Therefore, 3-4 triggers are missed at the beginning. (e.g on our QX1 + MAP2 reference setup)
3. The PR doesn't build in one CI …

ULog Geotagging Support v2

---

localization/README.md
localization/gen_translation_source.sh
localization/qgc.ts
src/AnalyzeView/GeoTagController.cc
src/AnalyzeView/LogDownloadController.cc
src/AnalyzeView/ULogParser.cc
src/QGCQFileDialog.h

This is an initial, token start of localizing QGC.
I've added a script that collects all the strings that are set to be localized and creates the localization source file to be sent to crowding for translation. This is just the beginning of the work. There is a great deal of work to be done before all strings used throughout QGC are ready for exporting by that script. 
Localization is a complex task. It's not just a matter of translating every instance of a string, but things need to be in context. In addition, strings that are built from parts or used for comparison, need special handling as well and this is the case in several places throughout the code.
For instance, take this [example](https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/APM/APMPowerComponentContr …

Initial localization work.

---

src/Vehicle/Vehicle.cc

This is a bug. Why not be able to change the flying flag to false when we are disarmed?
I think the intention was to not set the flag to true when we are disarmed, but that is [handled by the caller](https://github.com/mavlink/qgroundcontrol/blob/master/src/FirmwarePlugin/APM/APMFirmwarePlugin.cc#L437).

Set flying flag regardless of armed status

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FlightDisplay/GuidedAltitudeSlider.qml
src/Settings/Guided.SettingsGroup.json
src/Settings/GuidedSettings.cc
src/Settings/GuidedSettings.h
src/Settings/SettingsManager.cc
src/Settings/SettingsManager.h

Problems:
* The range of the altitude slider for multi-rotor was too small (10m up and down from current altitude)
* Using a large linear range slider on a small screens creates large jumps in altitude for small movement of the slider
* Multi-Rotor can tend to live closer to the ground more safely than a fixed-wing from a standpoint of minimum altitude
* Third parties want to set min/max for altitude slider for their custom builds
Solutions:
* Use a cubic range on the slider. This allows for fine adjustment around the current altitude, but also allows the upper/lower end of the range to hit a full range adjustment. Thanks to @lvale for the suggestion. I tried a number of exponent and cubic seems to provide the best adjustment.
* Have separate min/max range for multi-rotor and fixed wing. …

Cubic altitude slider

---

src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapEngine.h
src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/Settings/FlightMapSettings.cc

Moved offline map tokens to AppSettings.
Before you ask, it won't work for them to be part of FlightMapSettings because the tokens are used within the FlightMapSettings constructor, at which point things are not yet ready :P
What really needs to be done is to consolidate QGCMapEngine with FlightMapSettings. That's what QGCMapEngine was written for when I first added map management.

Offline map Tokens

---

src/JsonHelper.cc

Loading plan files which have NaNs in param 5/6/7 slots would fail.

Plan load: Fixes for NaNs in param 5/6/7

---

qgroundcontrol.pro
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsTest.cc
src/MissionManager/MissionSettingsTest.h
src/MissionManager/SimpleMissionItemTest.cc
src/MissionManager/SimpleMissionItemTest.h
src/qgcunittest/UnitTestList.cc

Dirty bits for Camera and Flight Speed sections not being cleared when parent item cleared dirty bit. This was causing incorrect Upload Required state.

Mission Settings: Fix section dirty bit handling

---

src/MissionManager/Survey.SettingsGroup.json
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/PlanView/SurveyItemEditor.qml

This allows you to specicy the entry location you want for the survey grid. Important for:
* Creating shortest distance survey flight path from takeoff to land
* Moving entry point to work around obstacles in path
Implementing this was a royal PITA. It really needs a comprehensive unit test to make sure it is all working which will come next. Wouldn't be suprised by boundary case problems.

Survey: Settable entry location

---

src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp

Basic tests on macOS seems to be all fine.
QGeoMapType has an extra argument in its constructor, allowing one plugin to implement more than one plugin. This is a NOP for Qt < 5.9

Add support for Qt 5.9 (QtLocation)

---

src/VideoStreaming/VideoReceiver.cc

Otherwise you will get a compiler error if you don't have GStreamer installed (or have it disabled).

Exclude method when not building with video streaming support.

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/MissionManager/Survey.SettingsGroup.json
src/MissionManager/SurveyMissionItem.h
src/MissionManager/SurveyMissionItemTest.cc
src/MissionManager/SurveyMissionItemTest.h

While writing unit tests for grid angle and entry location (in this pull) I realized that the concept of TopLeft, TopRight, BottomLeft, BottomRight for specifying entry location just didn't make sense when you rotate the grid to say 45 degrees. Although each location did move the the entry location to a unique spot. Relating it to that specific wording wasn't working. So Instead I changes naming to be generic Position 1, Position 2, Position 3, Position 4. Which will allow you to select between the four possible positions.

Survey: Entry location changes

---

src/MissionManager/CameraSection.cc
src/MissionManager/CameraSectionTest.cc
src/MissionManager/VisualMissionItem.cc

Trigger time was not handled when loaded back from a camera section

More fixes for MAV_CMD_IMAGE_START_CAPTURE spec change

---

src/MissionManager/PlanMasterController.cc
src/PlanView/PlanToolBar.qml

* Upload button is correctly disabled when sync in progress
* When sync completes, the plan toolbar will change to large font "Done" for 5 seconds and then revert back

Plan: Better upload progress indication

---

src/Settings/AutoConnect.SettingsGroup.json
src/Settings/AutoConnectSettings.cc
src/Settings/AutoConnectSettings.h
src/comm/LinkManager.cc
src/comm/UDPLink.cc
src/comm/UDPLink.h

This is to allow core plugin to be able to override the autoconnect udp port as well as set a single target host.

Allow UDP auto connect to be controlled through settings

---

src/MissionManager/CameraSection.FactMetaData.json
src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/CameraSectionTest.cc
src/MissionManager/CameraSectionTest.h
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItemTest.cc

* New Take Photo action added to camera section
* Set camera mode is always first command added to mission from camera section
* Change multi-rotor turnaround distance default to 5 meters. This way it is stable when entering grid.

Camera Section: Add support for Take Photo

---

src/FlightDisplay/FlightDisplayView.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsItem.h

* If the mission ends in an RTL then there will be a waypoint line which links back to home
* The Mission End dialog now have a "Leave mission on vehicle" button to reduce confusion that you don't need to remove the mission from the vehicle
* The Mission End dialog doesn't show for ArduPilot vehicles since the ability to remove a mission from the vehicle is flaky

Plan fixes: RTL waypoint line, Mission End dialog

---

src/MissionManager/MissionSettingsItem.h
src/PlanView/MissionSettingsEditor.qml

There is confusion around what the camera commands do in Mission Settings. The key is that they take affect immediately. So if you turn on the camera you are going to get photos/video from the ground on up.
Default visuals:
Camera section manually opened:

Mission Settings: Work on usability

---

qgroundcontrol.qrc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FlightMap/Widgets/ValuesWidget.qml
src/Vehicle/SubmarineFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

This will add some valuable information for Sub operation in the vehicle values widget. Because these options are sub-specific, they are allocated at runtime if the vehicle is MAV_TYPE_SUBMARINE.
I think the way the options are created could use a rework in general to be firmware-specific, but maybe that should wait till after 3.2. In the meantime, I can rework the implementation in this PR if it is not appropriate; I am open to alternative approaches.

Add firmware-specific factgroups

---

src/FlightMap/FlightMap.qml

Qt 5.9 has added a few more map gestures, some of which QGC doesn't yet handle (rotation, tilt, etc.) To avoid these, I'm now explicitly defining the desired (enabled) gestures for maps.

Enable only the gestures we're interested in.

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h
src/QGCApplication.cc
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h
src/ui/MainWindowInner.qml

When video streaming was first added to QGC, it was all based on the assumption one single stream was ever in use. The `VideoManager` class provided all the methods for controlling this one single stream.
This PR decouples `VideoReceiver` from `VideoManager`. Now, all the properties, methods and ancillary classes needed for a video stream are built solely within `VideoReceiver`.
The original video stream, the one that existed until now, will continue to exist and work in the exact same way. That's the video stream exposed by `VideoManager`. What is different is that now you can create separate instances of `VideoReceiver` for additional video streams.

Decouple VideoReceiver from VideoManager.

---

.travis.yml

If not, we may have to do the framework relocation ourselves.

Bump up Xcode to see if the Mac installer build runs properly.

---

src/AnalyzeView/GeoTagController.cc

This fixes the case where the log doesn't contain a particular trigger packet (logging dropout), but the image has been captured correctly. 
Without this fix, a missing log entry would throw off geotagging for all the subsequent frames. Critical fix, so should go into the release.

GeoTagController : Handle logging dropouts correctly

---

QGCInstaller.pri
deploy/qgroundcontrol_installer.nsi
qgroundcontrol.pro

This allows custom builds which have overriden things like application name and so forth have those overrides flow through to the installers.

Support for custom build installers for Windows/OSX

---

QGCExternalLibs.pri

Add switch to QGCExternalLibs.pri to check whether 32bit or 64bit version of SDL should be used on windows

ExternalLibs: Fix compilation on windows 64bit

---

qgroundcontrol.pro

While testing custom installed changed I changed app name to "QGroundControl Foo" for testing. Then I left that in and merged it!

Put back correct app name

---

QGCInstaller.pri

Yet another attempt at the macOS relocation issue:
For some unknown reason, `macdeployqt` is messing the relocation of some frameworks during the build phase. This appears to only happen on Travis (I have never been able to reproduce this on a local build).
The "fix" is to let it run (it saves a boatload of work in picking the needed various Qt frameworks and plugins) but run a subsequent, wholesale relocation afterwards. This will guarantee that all frameworks are properly relocated.

Deal with macdeployqt relocation issues

---

src/FlightDisplay/VideoManager.cc
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/VideoStreaming/VideoReceiver.cc
src/ui/preferences/GeneralSettings.qml

Video streaming source now defaults to *Disabled*. This is just the default, initial source option. Once set to something else, it will persist.
Having a default to anything doesn't really make much sense as there is nothing _standard_ about video streaming to default to.
Note that this will only be noticeable for new installations. If you already have QGC installed, it will pick up whatever source you had defined last. You can always select *Video Stream Disabled*, under General Settings, to disable video streaming.
Fixes #5380

Set default video streaming to Disabled.

---

src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp

It took me quite a while to figure this one out. Even though there is a MapEngine class handling all mapping services, the main map view uses its own, hardcoded set of maps and types, which is a subset of the available maps. The issue with Statkart was that it was named "Statkart Topo2" and the main map view uses hardcoded types (Street, Satellite, Hybrid or Terrain). The "Topo2" part wasn't one of those and therefore, it would not "find" it.
The "Fix" was to rename "Statkart Topo2" to "Statkart Terrain Map".
Note that *Offline Maps* uses MapEngine. That means it will allow you to create map tile sets from any available map source but it also means some of those, specifically those not named "Street Map", "Satellite Map", "Hybrid Map" or "Terrain Map" won't ever match and cannot be used. …

Work around FlightMap weirdness

---

src/MissionManager/Survey.SettingsGroup.json
src/PlanView/SurveyItemEditor.qml

Getting correct coverage over a survey polygon is a bit of black magic due to waypoint acceptance causing trigerring to start/stop too early. Due to this I'm adding back to option in Survey to take images throughout the entire survey. This gets better coverage, but you need to deal with possibly tilted images in the turnaround on fixed wing.

Survey: Option to take images in turnarounds

---

src/FirmwarePlugin/CameraMetaData.cc
src/FirmwarePlugin/CameraMetaData.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/PlanView/SurveyItemEditor.qml

Camera meta data now includes minimum trigger interval. If the survey goes below this minimum a warning will be displayed to the user.

Support for camera min trigger interval validation

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/Vehicle/Vehicle.cc

The mode switching for PX4 was generating excessive feedback hiding the user-facing error message and was leaving the vehicle potentially in an unintended armed state.

Fix mode switching

---

src/MissionManager/Survey.SettingsGroup.json

10% is really not workable for any stitching engine.

Survey settings: Default to 70% overlap as sane default

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionsController.qml
src/FlightDisplay/MultiVehicleList.qml
src/comm/MockLink.cc
src/comm/MockLink.h

New Multi-Vehicle view support:
You can now Pause and Start Mission on all connected vehicles. They will bring up guided confirmation sliders. Start Mission on all vehicles example:
What it looks like after all mission have begun:
Note: The commands which apply to a specific vehicle: Pause, RTL, Take Control in this example are not currently plumbed through the guided framework. So they will work, but they take affect immediately with no confirmation sliders. I will be moving the guided action support to the C++ Vehicle  side from qml to make that work.

More support in multi-vehicle view

---

src/FlightMap/MapItems/VehicleMapItem.qml
src/Vehicle/Vehicle.cc

* Inactive vehicles are shown with opacity to distinguish from active vehicle
* When multi-vehicle, vehicle ids are shown below vehicle

Better display of vehicle indicators for multi-vehicle

---

src/FlightMap/MapItems/VehicleMapItem.qml
src/Vehicle/Vehicle.cc
src/comm/MockLink.cc

* ADS-B Vehicles will be remove from display are they are no longer heard from
* Altitude and callsign are stacked visually

ADS-B vehicle timeout and stacked callsign

---

src/qgcunittest/UnitTestList.cc
src/ui/MainWindow.cc

This re-enables FTP now that Beat has fixed some underlying issues. The main motivation for it is that even high-bandwidth data links tend to only support UDP or even just a single data channel. Having a tunnelled, packetised file transfer is actually appropriate. MAVLink also ensures data integrity (via authentication in MAVLink 2) and therefore offers a viable solution.
The only caveat we need to add (@bkueng) is immediate re-transmission when something drops. It has to work on an unreliable link.
There are a number of use cases where having the ability to get / set files is powerful. This includes:
* Terrain data
* Camera meta data (we should reconsider going to JSON instead of XML @dogmaphobic)
* Vehicle meta data (would avoid the common issue we're having right now with param meta) …

Re-enable FTP in menu

---

qgroundcontrol.pro
src/MissionManager/MissionController.cc
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsItem.h
src/MissionManager/SimpleMissionItem.h
src/MissionManager/VisualMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/PlanView/MissionItemStatus.qml
src/Terrain.cc
src/Terrain.h

This is a WIP so expect some quirks, also the implementation is not super performant from a network traffic standpoint. Uses AirMap terrain apis.
Red terrain indicator shows flight below terrain:

Plan: Terrain display in MissionItemStatus

---

src/MissionManager/MissionManager.cc

Getting some reports of vehicle not requesting all mission items. Did some visual inspection and there seems to be a remote possibility of the index list not clearing correctly (although I can't find the code path). So although this may not really be needed it will make it clear that the QGC side is doing the right thing.

Mission upload: Extra paranoia around write index list

---

src/FlightDisplay/FlightDisplayView.qml

We had a disappointing report of someone loosing a lot of footage they thought they were recording because they had accidentally set their hand on the touchpad or something and didn't notice they turned it off. In an effort to prevent these types of happenings, we are trying to make it more obvious when recording is active/inactive. This makes the recording button visibility toggle at 1Hz. I thought it might be distracting to do it this way, but I don't think it is after seeing it.

Make recording status more obvious

---

src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h
src/Settings/Video.SettingsGroup.json
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/VideoStreaming/VideoReceiver.cc
src/ui/preferences/GeneralSettings.qml

This adds Mpeg2 Transport stream over TCP support as a possible video feed in the gstreamer pipeline.
This is used in cases where a local ground station receives the video feed from the aircraft, and rebroadcasts it out to multiple ground stations or devices over a wireless link.   Since the network is local and broadcast to more than a single client, occasional packet drops between the ground station and devices occur, which TCP helps to mitigate.
It is not recommended to use TCP/MPEG2_TS as a datalink to directly to the aircraft, since the re transmits that occur over TCP can build up during a loss of link condition causing additional bandwidth overhead and latency issues.

Add TCP-Mpeg2TS support to available video feeds

---

.gitmodules
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/comm/LinkManager.cc
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/comm/ProtocolInterface.h
src/comm/SerialLink.h

This extension allows to negotiate with all connected vehicles the highest possible MAVLink version supported by all. It is compatible with legacy vehicle software (interprets NACK and timeouts as v1.0 requests). This allows to have the best possible version enabled without any user configuration.
Before connecting QGC:
```
instance #0:
mavlink chan: #0
no telem status.
flow control:	OFF
rates:
tx: 23.215 kB/s
txerr: 0.000 kB/s
rx: 0.000 kB/s
rate mult: 1.000
accepting commands: YES
MAVLink version: 1
transport protocol: UDP (14556)
```
After connecting QGC with this extension:
```
instance #0:
GCS heartbeat:	988721 us ago
mavlink chan: #0
type:		GENERIC LINK OR RADIO
flow control:	OFF
rates:
tx: 30.495 kB/s
txerr: 0.000 kB/s
rx: 0.021 kB/s
rate mult: 1.000
accepting commands: YES
MAVLink …
```

Automatic protocol version handshake

---

src/VehicleSetup/JoystickConfig.qml

Limits the maximum number of joystick buttons for which functions can be added on vehicle settings, joystick setup page, to 16.
Prevents issues of unconfigurable buttons outside the range 0~15 from appearing to be configurable, such as: https://cdn-business2.discourse.org/uploads/bluerobotics/original/2X/8/886612ffc44d2d46447e44976e857bec158ec7f3.png
Closes bluerobotics/qgroundcontrol#21

Add joystick button limit

---

src/Joystick/JoystickSDL.cc

Also handle a segfault issue that has been plaguing me for a while by commenting out call to SDL_JoystickClose

Handle joysticks with duplicate names

---

src/FlightMap/Widgets/InstrumentSwipeView.qml
src/FlightMap/Widgets/QGCInstrumentWidget.qml
src/FlightMap/Widgets/VehicleHealthWidget.qml
src/FlightMap/Widgets/VibrationWidget.qml

I think that automatically switching the page in the instrument panel every time the sensors_health flag changes is heavy-handed and obnoxious.
This pr changes the behavior to show a warning icon opposite the gearthingy beneath the attitude indicator. Click the warning icon to quickly switch to the sensors health page. The warning icon goes away until another sensors_health bit changes.

Rework vehicle sensors_health alert

---

src/ui/MAVLinkDecoder.cc

There is no reason to run it at any other priority, since its only for UI / inspection.

MAVLink decoder: Run at lowest priority

---

src/AnalyzeView/MavlinkConsoleController.cc
src/AnalyzeView/MavlinkConsoleController.h
src/AnalyzeView/MavlinkConsolePage.qml

This is for #5430. To test for yourself start a mavlink console session and run the help command a few times to generate a bunch of lines, then run top. Before this change rewriting the console lines is a huge drag on QGC and generates way more CPU utilization than is reasonable. 
With this change there is barely a perceptible performance impact. The only disadvantage to this PR is the console text is no longer available for copy/paste.

Switch over to model based storage for the mavlink console

---

src/FactSystem/FactControls/FactTextField.qml
src/QmlControls/ParameterEditorDialog.qml

Changes to custom build parameter editing only. No affect on mainline QGC. Two problems:
* Force save is only available in advanced mode
* Reset to default only available in advanced mode. This is due to the fact that custom vehicle have way more parameter defaults tweaked in there autostart script. Which in turn causes defaults to be invalid.

Parameter force save and default disabled in non-advanced mode

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml

This way:
* GCS location is shown
* It uses centering semantics of FlightMap: centere same as flight map , center to gcs locaiton if available
* Center on Location works
* Note: Vehicle is not shown
Fix for #5554

Offline map: Use FlightMap as base

---

src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGCTileCacheWorker.h

To test if you have Internet connection, the code used to test a connection to 8.8.8.8:53 (google DNS). It appears that some routers are now blocking TCP connections to port 53. So instead, we started using a TCP connection to "github.com" (80). The problem with using a host name rather than an IP address is that the code must first do a name look up before it can attempt a connection. The lookup itself may take up to a minute on some devices. If you were to attempt to exit QGC while that thread was attempting a connection, it would lock the thread until the call returned. There is no way to cancel a connection attempt.
This PR splits the DNS lookup from the connection. The lookup, unlike the "look up and connect" call, can be canceled.
Why bother with the connection if the lookup …

Split internet test into separate DNS lookup and connection.

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/MapItems/CustomMapItems.qml
src/FlightMap/qmldir
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h
src/api/QmlComponentInfo.cc
src/api/QmlComponentInfo.h

* Allow custom builds to add items to the Fly view map
* Also rename QmlPageInfo to QmlComponentInfo to cover more use cases

QGCCorePlugin::customMapItems support

---

src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml
src/AutoPilotPlugins/Common/SetupPage.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/SetupView.qml

The aim is to make sure the setup pages disable/enable themselves appropriately when they are active and visible during transitions of the armed state.
The current behavior is a bug and safety issue.
This is a rework of https://github.com/mavlink/qgroundcontrol/pull/5525.

Rework disabling of setup pages

---

src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/MissionManager.cc

* Generation of resume mission would crash if resuming from the latter half of a mission
* New logic for the index to resume from. If the resume index mission command was not a waypoint command it will now back up to the previous waypoint command. This preserves survey transect lane commands fully.
* Resume rebuild logic fixed such that it no longer loses part of the mission if you hit there case where you did not crash towards the end of a mission.
* Simplified prefix'ed command de-dup logic
This has been tested tover verify the crash no longer exists. It has also been verified against various survey scenarios. There may still be some problems lurking for more custom mission setups but I'm getting this in ASAP to allow for testing of it's current state. Next thing to do is to create a …

Resume mission fixes

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/MissionManager.cc
src/MissionManager/MissionSettingsItem.cc
src/Vehicle/Vehicle.cc

This centralizes common guided action support into APMFirmwarePlugin such that it does not need to be repeated for each vehicle type (Copter/Plane/Rover). The following guided actions are now supported across all vehicles and the left side action tools work for these: 
* RTL
* Pause - Puts the vehicle in the appropriate Pause flight mode
* GoTo Location - Click in map to go to location
* Change Altitude - Available from Action tool
@khancyr This is going to clash with your pull #5597 since it centralizes most guided support. Hence there is no longer need for specific Rover support. Once this goes through you'll need to rebase and fix up. Should be pretty easy. Mostly just pulling stuff out.

Better Guided Action support for ArduPilot

---

src/FlightMap/Widgets/ValuePageWidget.qml

Instrument widget:
Indicators on the values page use enumerated strings when available for small indicators but always display the raw string value for large indicators.  This fix uses the enumerated strings for both large and small indicators.  See "GPS Lock" below:
|![screen shot 2017-08-31 at 9 35 57 am](https://user-images.githubusercontent.com/10507633/29934469-29426f82-8e30-11e7-905e-9397c5015241.png)|![screen shot 2017-08-31 at 9 35 18 am](https://user-images.githubusercontent.com/10507633/29934471-2bc5b25a-8e30-11e7-92a6-487d9eda7ea3.png)|
| --- | --- |
| Current (integer) | This PR (enumString) |

Use enumString for large indicators on instrument widget

---

src/VideoStreaming/VideoReceiver.cc

QGC is not able to receive the RTSP video stream from the drone, when the Ubuntu machine which runs QGC is disconnected from the Internet. This issue can be resolved by setting no-proxy for the TCP socket used for video-streaming. Please refer the issue #5577 for details.

Set NoProxy for the TCP Socket used for Videostreaming

---

src/MissionManager/MissionController.cc

This would cause uneeded "Upload Required" state.

Plan: If vehicle updates home position don't mark plan dirty

---

src/MissionManager/SurveyMissionItem.cc

This provides for better stable images on entry/exit of survey area.

Survey: Bump multi-rotor turnaround distance

---

src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlightDisplayView.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

All ArduPilot vehicle support MANUAL_CONTROL now so no need to:
* Pop the joystick warning
* Have a plugin mechanism to signal MANUAL_CONTROL support
Fix for #5644

Assume all vehicles support MANUAL_CONTROL

---

src/AnalyzeView/LogDownloadController.cc

On PX4, under certain circumstances and in rare cases, there can be log
files with 0 size. In that case QGC ignored the entry and tried to
re-request the entry indefinitely.
@MaEtUgR you can approve here :)

LogDownloadController: only skip entry if size==0 && APM firmware

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h

Bugfix in behavior when joystick is connected after app launch: TX mode was always 2 regardless of saved settings or vehicle default.

Fix joystick tx mode initialization

---

src/FlightDisplay/FlightDisplayViewWidgets.qml

On large/high DPI screens, the whole UI scales nicely when increasing the
font size, except for the attitude widget, that was limited to 200 pixels.
Before:
Now:
It's better, but IMO it could still be a bit larger.

FlightDisplayViewWidgets: increase the maximum widget size from 200 to 400

---

src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h

This PR adds a "mobileDefaultValue" JSON key that mobile builds will use in place of "defaultValue" when available.  If the "mobileDefaultValue" key is not available for a given fact, mobile devices will instead default to the "defaultValue" key's value.
Non-mobile builds will ignore the "mobileDefaultValue" key.
This allows developers to set different default fact values for mobile/desktop users.

Add JSON key for mobile-specific default values

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCViewDialog.qml

UX improvements that have bothered me (and others too) for quite some time now:
- activate the keyboard focus to the parameter value when start to edit a parameter
- accept numpad enter key to change a param
- allow to search for multiple independent words in parameter names & descriptions.
There's one more thing I wanted to do: set the focus to the mavlink console text input when opening the console view. But I could not get that to work. @DonLakeFlyer would be great if you could do that.

Some smaller UX improvements

---

src/VehicleSetup/VehicleSummary.qml

For custom builds which hide setup pages but still show the summary page for the component:
* Click on summary box does nothing
* Setup red/green indicator is hidden

Setup View: No click/indicator for hidden pages

---

src/MissionManager/QGCMapPolygon.cc

Replacement for #5684.
@patrickelectric Can you run this and make sure it handles the cases you tried? I believe it works now with no double signalling. It's just a variant of you pull.
Also there seems to be a possible Qt bug where the center indicator sometimes disappears. Just noticed that. I wonder if that is new with 5.9. Never saw that before. Happens on master.

Fix polygon center updates

---

src/MissionManager/MissionManager.cc
src/MissionManager/PlanManager.cc
src/MissionManager/PlanManager.h

Reverts mavlink/qgroundcontrol#5701. This pull caused more problems than it fixed. I'm reverting which leaves current mission item updates broken. But that is less broken then the other bugs this pull caused.

Revert "Fix current mission item updates"

---

src/Vehicle/Vehicle.cc

this hack forces the numeric display of heading to roll over properly from 359 to 0 degrees
see https://github.com/mavlink/qgroundcontrol/issues/2971

fix issue #2971

---

src/MissionManager/PlanManager.cc
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/MissionManager/StructureScan.SettingsGroup.json
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/PlanView/StructureScanEditor.qml
src/PlanView/StructureScanMapVisual.qml
src/comm/MockLinkMissionItemHandler.cc
src/comm/MockLinkMissionItemHandler.h

* The polygon you manipulate now represents the actual structure.
* You can specify the Scan distance from the sructure. This will generate the flight path/
* Green filled polygon is structure
* White polygon outline is flight path
Note: Still not quite ready to fly but almost. This pull gives me the backend functionality to implement things like structure scan based on camera image resolution like Survey.
Related to #5694.

Structure scan: Support for scan distance from structure polygon

---

src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/Vehicle/Vehicle.cc

Resume mission was relying on a flight mode update happening before a mission index update for RTL handling. This would require HEARTBEAT flight mode change message to come through before the MISSION_CURRENT index update in order to work correctly.
This led to flaky behavior in that it would work sometimes and sometimes now. This change essentially orders the handling to always be in the order HEARTBEAT -> MISSION_CURRENT.

Fix Resume Mission race condition

---

src/Settings/Video.SettingsGroup.json
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/VideoStreaming/VideoReceiver.cc
src/ui/preferences/GeneralSettings.qml

Rework of #5693.
This PR adds the option to enable/disable the video auto-delete feature.  Said feature is enabled by default for mobile builds.  For non-mobile builds, it defaults to disabled.
Max storage limits are also adjusted.  Mobile builds will default to 2 GB (same as current versions), whereas non-mobile builds, when auto-delete is enabled, will default to 10 GB.

Add option to disable video auto-delete

---

src/AnalyzeView/LogDownloadController.cc

The timer was only started in _logData(), which was called after receiving
the first chunk of data (and only if that was successful), which means
if the first request failed or timed out, the UI would never switch to
a timed out state.
Fixes the 2. bug described in https://github.com/mavlink/qgroundcontrol/issues/5610.

LogDownloadController: start the timeout timer when requesting the first chunk

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.3.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.4.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.5.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.3.5.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.3.7.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.3.8.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Rover.3.0.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Rover.3.2.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Sub.3.4.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Sub.3.5.xml

Change from BATT_VOLT_PIN to BATT2_VOLT_PIN.

APMParameterFact: Solve typo in BATT2_VOLT_MULT description

---

.travis.yml
Vagrantfile

PX4 Firmware metadata (airframes and params) is now auto updated by jenkins. http://ci.px4.io:8080/job/mavlink/job/qgroundcontrol_px4_metadata/

travis-ci and vagrant don't fetch latest PX4 metadata

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FirmwarePlugin/CameraMetaData.h
src/MissionManager/CameraCalc.FactMetaData.json
src/MissionManager/CameraCalc.cc
src/MissionManager/CameraCalc.h
src/MissionManager/CameraSpec.FactMetaData.json
src/MissionManager/CameraSpec.cc
src/MissionManager/CameraSpec.h
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/PlanView/CameraCalc.qml
src/PlanView/StructureScanEditor.qml
src/QGCApplication.cc
src/QmlControls/QGroundControl.Controls.qmldir

The new CameraCalc object and CameraCalc.qml are reusable code and ui which encapsulates all of the things associated with supporting survey style image capture based on camera specs. Structure Scan is the first to use this. Survey will be converted over to it in a subsequent pull. Having this as reusable code now makes adding other survey types like Corridor Scan (or whatever) way easier and consistent.
Note: Structure Scan is still not ready to be flow yet.
Here are visuals from Structure Scan. The "Camera" section is where you see it being used as a reuable control:

New CameraCalc reusable code for complex items

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/MissionItemStatus.qml
src/PlanView/PlanView.qml
src/QGCApplication.cc

This moves the current selected mission item (Plan View) away from QML and to c++. It can now be accessed from anywhere.

Move plan view index control to MissionController

---

src/MissionManager/CameraCalc.cc
src/MissionManager/CameraCalc.h
src/MissionManager/CameraSpec.cc
src/MissionManager/CameraSpec.h
src/MissionManager/MissionController.cc
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/PlanView/StructureScanEditor.qml
src/PlanView/StructureScanMapVisual.qml

* Add support for load/save
* Fix up mission item generation for camera triggers
Structure Scan should be in a flyable state now. It will currently only work with a gimbal which has yaw support. I need to invent some new mavlink magic to make it work with fixed cameras.
Example structure scan:
KML output for above plan:
Related to #5694

Structure Scan persistence and mission creation

---

src/FlightMap/MapItems/MissionItemIndicatorDrag.qml
src/MissionManager/QGCMapPolygonVisuals.qml

Polygon tool now supports creation of circular polygon. This will work anywhere polygons are allowed: Structure Scan, Survey, ...
You can now click on the center drag tool of a polygon to bring up a menu. Click Circle to get a circle, click Polygon to get back a polygon.
When you have a Circle you can set the Radius:
Note: Load KML coming soon...

Polygon: Create circular polygon

---

src/VideoStreaming/README.md

The ball pattern do not work in all cases, this new example add the basic video input with size information.

README.md: Add new gstreamer example

---

src/FirmwarePlugin/PX4/MavCmdInfoCommon.json
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/SimpleMissionItem.cc
src/PlanView/PlanView.qml
src/PositionManager/PositionManager.cpp
src/PositionManager/PositionManager.h

* Allows you to click in map to set ROI. Turns off are single ROI add.
* Note: Waypoints only mode only supported for custom builds

Support ROI tool button in WaypointsOnly mode

---

.travis.yml
qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml
src/FlightMap/Widgets/VideoPageWidget.qml
src/QmlControls/PageView.qml
src/QmlControls/QGCSwitch.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/Settings/Video.SettingsGroup.json
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/Vehicle/Vehicle.cc
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h
src/api/QGCCorePlugin.cc
src/ui/preferences/GeneralSettings.qml

Added a widget for controlling the video stream. For now it provides two functions:
* Enable/Disable the stream
* Stream recording control (moved from the screen into this control)
Video Enabled:
Video Disabled:

Video Stream Control Widget

---

.appveyor.yml

5.9.1 is no longer there so we switch to 5.9.2. At least for Windows for now.
Closes #5862

Switch Appveyor to Qt 5.9.2

---

src/QGCGeo.h

The failure got triggered by 3c55e2b0f7dfc48cfe7eb086bc3a30d6a6166905, but it is seems not to be guilty.
This is fixing "error: expected unqualified-id before ‘{’ token
#define sincos(th,x,y) { (*(x))=sin(th); (*(y))=cos(th); }"
errors. Not sure if the    #ifndef sincos   might be needed in addition on some platform.

fix compile with glibc 2.26

---

qgroundcontrol.pro
src/comm/LinkManager.cc

For now, QGC will build "Native" QML on mobile and "Hybrid" otherwise. This PR is to allow to build a native QML on desktop (for testing) until there is a proper switch over to native QML.
The first change is to simply add `serialport` and the second is to skip RTK as it is not available on mobile (and it would be too much work to fix that for the purpose of this test).

Allow pseudo mobile builds (Native QML on Desktop)

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h

Hello @dagar 
The test is done on Windows and Android. Version 3.2.5
When a Mavlink UAV is connected, with the activated USB joystick there is a very strong boost of the program. This causes a constant loss of communication with the UAV and the message: manual control lost.
Each time the user moves the map, the central coordinate and zoom level are stored in the configuration file, and this is read every time to change the position of the map on the screen. When you move the map then this reading / writing is performed many times per second and the system is working incorrectly.
If you redefine these functions in such a way that the map coordinate and zoom level are stored simply in the variable, then the speed grows several times and the map becomes comfortable. And in the configuration …

'manual control lost' when connected joystick with armed UAV

---

src/QmlControls/QGroundControlQmlGlobal.cc

The PR #5867 was setting the initial zoom level to 17, which would leave you zoomed in in the middle of the Atlantic (0,0).

Properly handle default (initial) map coordinates and zoom level.

---

src/FirmwarePlugin/FirmwarePlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Needed to support different indicators for advanced/non-advanced modes.

Allows FirmwarePlugin::toolbarIndicators to signal change

---

src/FlightMap/MapItems/PlanMapItems.qml
src/MissionManager/CameraSectionTest.cc
src/MissionManager/GeoFenceManager.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/PlanManager.cc
src/MissionManager/PlanManager.h
src/MissionManager/SectionTest.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SimpleMissionItemTest.cc
src/MissionManager/SpeedSectionTest.cc

On tablet devices with smaller memory available large Plans could cause QGC to run out of memory while uploading from Plan to Fly. This was due to amoung other things current code shares most visuals and object code between the Plan and Fly views. But the Plan implementation is expensive since it needs to be editable. The Fly view was using these same implementations even though editing is not allowed. Great way to share code but also great way to chew huge amounts of memory.
Made the following changes to reduce memory footprint:
* Reuse MissionItems when upload to vehicle instead of duping them between Controllers and Manager.
* Add a non edit mode to SimpleMissionItem which skips Fact and meta data setup since this isn't needed for Fly.
* Use of deleteLater in PlanManager during upload …

Reduce memory footprint of Plan/Fly mission handling

---

src/MissionManager/PlanManager.cc

@DonLakeFlyer the groundstation is receiving ACK messages from the onboard computer and does not inspect target_system. Can we suppress this message (only one found) until the system IDs are properly checked?

Suppress mission ack error until target_system is properly handled

---

src/GPS/RTCM/RTCMMavlink.cc
src/GPS/RTCM/RTCMMavlink.h

sequence numbers are only increased after a new RTCM message, while only
the fragment id is incremented within a fragmented message.
Only relevant for APM vehicles, but I do not have an APM vehicle to test this.

RTCMMavlink: fix sequence numbers

---

QGCExternalLibs.pri
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MockLink.cc

You can now override the MAVLink dialect and optionally, disable all references to ardupilot specific messages.
If nothing is done intentionally (the default), the build behaves exactly as it was, using the ardupilot dialect.

Allow disabling the Ardupilot MAVLink dialect 

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactMetaData.cc
src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/PlanView/FWLandingPatternEditor.qml

Also added new Fact contructor:
```
/// Creates a Fact using the name and type from metaData. Also calls QGCCorePlugin::adjustSettingsMetaData allowing
/// custom builds to override the metadata.
Fact(FactMetaData* metaData, QObject* parent = NULL);
```
Used when you want a metadata driven Fact that can be overriden by QGCCorePlugin but does not store values in settings like SettingsFact.

Fixed Window landing pattern defaults override support

---

src/comm/LinkManager.cc
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h
src/comm/SerialLink.cc

These two commits prevent two bad things on app boot:
- We stop connecting to ports that are part of the system or are already open under a different alias
- We continue to run the event loop while connecting
Combined this makes the boot / connect experience of QGC much better and much more responsive. At least on my machine with multiple serial devices connected.

Serial connect fixes

---

src/FirmwarePlugin/FirmwarePlugin.cc

Pretty self explanatory I hope! I did a double check with Mission Planner for the same survey, getting same results for time between photos, number of photos, lanes, etc..

Add camera definitions for Parrot Sequioa RGB and Monochrome sensors
