mavlink/qgroundcontrol

src/FlightDisplay/FlightDisplayViewWidgets.qml

https://github.com/mavlink/qgroundcontrol/pull/4216

guided mode altitude slider better maximum

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoStreaming.pri
src/ui/preferences/GeneralSettings.qml

Added configuration allowing a build with video recording disabled.

Allow disabling video recording

---

qgroundcontrol.qrc

Remove duplicate resources

---

src/QmlControls/QGCButton.qml
src/QmlControls/QGCComboBox.qml

Make buttons and comboboxes square again.

---

src/Vehicle/GPSFact.json

Add new Static fix type

---

src/AutoPilotPlugins/APM/APMPowerComponent.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml

Correct check for bad value from parseFloat

---

src/Vehicle/MultiVehicleManager.cc

Don't start Vehicles for things which aren't Vehicles

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

This aren't currently implemented for PX4 fixed wing.

PX4 hide FOLLOW and OFFBOARD

---

src/MissionManager/ComplexMissionItemTest.cc
src/MissionManager/SurveyMissionItem.cc

Fix ComplexMissionItemText unit test crash

---

src/MissionEditor/SimpleItemEditor.qml

Fix for #4418. Replacement for #4498

Plan-Simple Item: Use all remaining width for text fields

---

src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
src/QGCApplication.cc

Copter 3.5 has removed this param

Prevent crash from missing FRAME param

---

src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h

Chicken and the egg problem. I need this on this end so I can test the firmware side. This is just the beginning of what will eventually become video / photo control.

Experimenting with Video / Photo commands

---

src/FactSystem/FactControls/FactTextField.qml

Causing data loss. Fix for #4502

DoubleValidator causing problems with regional settings

---

src/MissionEditor/MissionEditor.qml

Fix position of children of complex items

---

src/FactSystem/FactSystemTest.qml
src/FactSystem/FactSystemTestBase.cc
src/Vehicle/Vehicle.cc
src/comm/MockLink.cc

Ignore heartbeats from non-default component

---

src/AutoPilotPlugins/APM/APMAirframeComponent.qml
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/FactSystem/ParameterManager.cc

ArduPilot: Load params from new Airframe page

---

src/MissionManager/RallyPointController.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SimpleMissionItemTest.cc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/QmlControls/QGroundControlQmlGlobal.json
src/ui/preferences/GeneralSettings.qml

Support for default mission item altitude setting

---

src/FactSystem/FactControls/FactTextField.qml
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/FactSystem.cc
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/SettingsManager.cc
src/SettingsManager.h
src/SettingsManager.json
src/Vehicle/Vehicle.cc
src/ui/preferences/GeneralSettings.qml

Converted mission auto load directory settings to a string based SettingsFact as test case.

FactSystem: String support

---

src/FactSystem/Fact.h
src/FactSystem/FactControls/FactCheckBox.qml
src/FactSystem/FactControls/FactTextField.qml
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/SettingsFact.cc
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/GAudioOutput.cc
src/GAudioOutput.h
src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/SettingsManager.cc
src/SettingsManager.h
src/SettingsManager.json
src/comm/MAVLinkProtocol.cc
src/ui/MainWindow.cc
src/ui/MainWindow.ui
src/ui/preferences/GeneralSettings.qml

Convert bool settings to SettingsFact.

Add bool support to FactSystem

---

src/comm/QGCSerialPortInfo.h

These are now stored in json file. Fix for #4499

Remove serial ids

---

qgroundcontrol.qrc
src/MissionEditor/FWLandingPatternEditor.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/MissionController.cc

More WIP:
What works:
* You can add on and get an item editor for the values
* Modifying the values will update the landing pattern
* Send to Vehicle works
What doesn't work:
* When you add the item the point for the landing point is map center. Ability to click first to set that still coming.
* You cannot interact directly with the visuals on the map. Only the values in the editor.
* When you reload from a vehicle to see the individual items something goes wrong with the Loiter and Land editors. They don't show any values.
* Relative altitude checkbox is missing.
* File persistance is NYI
The specifics of the landing pattern mission items is in this code:
```
MissionItem* item = new MissionItem(seqNum++,                           // sequence number
MAV_CMD_DO_LAND_START,              // …
```

Complex Item: Fixed Wing Landing Pattern

---

qgroundcontrol.qrc
src/Vehicle/TemperatureFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Temperature fields coming through SCALED_PRESSURE messages can be viewed with the vehicle values widget.

Put temperature readings in vehicle values widget

---

src/api/QGCOptions.h

These are covered by SettingsGroups now

Remove deprecated methods

---

src/MissionEditor/FWLandingPatternEditor.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/SurveyComplexItem.qml
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/MissionController.cc

* You are now prompted to click to set landing point
* You can drag around landing and loiter points and all values update live correctly
Still much work to do, but getting closer:
* Persistance format
* Better visuals
* Support for other complex item methods which calc distance/time and so forth
* Some NaNs in the calculations still. You'll see --.-- once in a while depending on heading angle.

Complex Item: More work in Fixed Wing Landing Pattern

---

src/MissionManager/SimpleMissionItem.cc

SimpleMissionItem: Correct init of _editorQml

---

src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h

Handle videoSource changes correctly

---

src/MissionEditor/FWLandingPatternEditor.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc

FixedWing Landing Pattern: More work on visuals

---

src/AutoPilotPlugins/Common/MixersComponent.cc
src/api/QGCOptions.h

Replaced by new settings support

QGCOptions: Remove deprecated methods

---

qgroundcontrol.qrc
src/AutoPilotPlugins/PX4/PowerComponent.qml
src/QmlControls/QGCGroupBox.qml
src/QmlControls/QGroundControl.Controls.qmldir

Converted PowerComponent.qml to use it as the new example of how to more easily create the centered shaded area style of setup pages.

New QGCGroupBox control

---

qgroundcontrol.qrc
src/FlightMap/Widgets/CameraWidget.qml
src/FlightMap/Widgets/InstrumentSwipeView.qml
src/FlightMap/Widgets/ValuesWidget.qml
src/FlightMap/Widgets/VehicleHealthWidget.qml
src/FlightMap/Widgets/VibrationWidget.qml
src/FlightMap/qmldir
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Sends a MAV_CMD_DO_DIGICAM_CONTROL with param5=1 to trigger camera.

Trigger camera in instrument panel page

---

src/FlightDisplay/FlightDisplayViewVideo.qml
src/Settings/Video.SettingsGroup.json
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/ui/preferences/GeneralSettings.qml

Along with the option to turn it on or off.

Add grid lines to video view

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/Widgets/CenterMapDropPanel.qml

Show Follow Vehicle checkbox on Fly view

---

src/MissionManager/FixedWingLandingComplexItem.cc

Mission send to vehicle was failing on PX4. Related to #4635

Fixed Wing Landing Pattern: Use MAV_FRAME_MISSION for DO_LAND_START

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/MissionItemIndicator.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/SurveyComplexItem.qml
src/QmlControls/MissionItemIndexLabel.qml

Still some small quirks on drag/click but good enough for pull. Related to #4635:

New waypoint coordinate indicators

---

src/Vehicle/Vehicle.cc

Consider any message from vehicle comm lost restart

---

src/FlightMap/FlightMap.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionEditor/SimpleItemMapVisual.qml
src/QmlControls/MissionItemIndexLabel.qml

Make selection/dragging easier for:
* Mission item indicators
* Survey polygon adjustment

Improve touch support for map item dragging

---

src/AutoPilotPlugins/Common/RadioComponentController.cc
src/AutoPilotPlugins/Common/RadioComponentController.h
src/VehicleSetup/JoystickConfig.qml
src/VehicleSetup/JoystickConfigController.cc
src/VehicleSetup/JoystickConfigController.h

I also moved the deadband indicators to the right side column and added an explanation of how to calibrate the deadband. Also corrected a misspelled function.

Changed joystick indicators to show output rather than input

---

src/FactSystem/ParameterManager.cc

Handle ArduPilot param behavior

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/MissionController.cc
src/MissionManager/SimpleMissionItem.h

* Landing distance defaults to 300m
* Heading is now from loiter to landing (previous: landing to loiter)
* Fixed bug with removing an item from a mission #4689
Related to #4635

Fw landing updates

---

src/MissionManager/FixedWingLandingComplexItem.cc

Fix loiter altitude value send to vehicle

---

src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/MavCmdInfoCommon.json

* Correct cross track value loiter to be tangent exit for item sent to vehicle
* Visuals shows tangent flight path
* Fix mission item editor command json for xtrack enum

Fixed Wing Landing Pattern

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/MissionCommandTree.cc
src/MissionManager/MissionCommandTree.h

* #4459 - Zoom map buttons don't show on mobile
* #4692 - Survey: Cancel polygon edit when item changes
* #3944 - Mission Item command picker: Add "All commands" category

Number of small bug fixes

---

src/MissionManager/MissionController.cc

Uninitialized variable warning.

---

src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/MissionController.cc

* File Save/Load support for landing pattern
* Mission distance and max telemetry distance values calculated correctly for complex item
Related to #4635

Support Fixed Wing Landing Pattern file persistence

---

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Following Don's suggestion, making the toolbar indicator list private and the method returning it const.

Making toolbar indicator list private.

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h

Reverts mavlink/qgroundcontrol#4717

Revert "dynamic param load timeout"

---

src/AutoPilotPlugins/PX4/PowerComponent.qml
src/QmlControls/QGCGroupBox.qml

- Fix imports to support 5.7
- Move properties to correct location

Power: Page not loading correctly

---

src/MissionEditor/MissionEditor.qml

Plane: After a remove all leave map position/zoom alone

---

src/MissionEditor/MissionSettingsEditor.qml

Mission Settings: Better visuals for mobile and connected vehicle

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/Images/compassInstrumentArrow.svg
src/FlightMap/Images/vehicleArrowOpaque.svg
src/FlightMap/Images/vehicleArrowOutline.svg
src/FlightMap/Widgets/QGCCompassWidget.qml
src/MissionEditor/MissionEditor.qml

Adjusting vehicle icon and making it consistent with Compass Widget

---

custom
src/MissionEditor/SurveyMapVisual.qml

Otherwise things go haywire when points are added

Polygon draw: Fix binding to repeater index

---

src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h

Should be all working now except for distance < radius cases. I forgot to put that back in and all the geometry was making my eyes cross. So had just about enough with this for now!
* The heading and distance are based on the tangent point, not the loiter point.
* If you drag the loiter or land coordinate the tangent, heading and distance are updated
* If you change the radius only the loiter point is updated
* If you change heading or distance from values the loiter and tangent point are updated

More fun with FW landing pattern geometry

---

src/AutoPilotPlugins/Common/RadioComponentController.cc

Setup - Radio: Fix crash from bogus param values

---

src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Add support for MISSION_ITEM_INT

---

src/MissionEditor/MissionItemStatus.qml

Two decimals for these values is overkill

Mission Item Status: Only 1 decimal place for values

---

src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h

I had added this just to test. Camera control will come as a proper module attached to the FirmwarePlugin and exposed through Vehicle.

Removing camera control experiment.

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml

While looking at #4780, I run into these and took care of it while at it.
The JavaScript exception was just the code trying to access the current selected set when nothing was selected. The other UI tweaks were just minor spacing adjustments for "non tiny" screens. Things were a bit way too jammed together.

JavaScript exception and minor UI tweaks.

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QGCPalette.h
src/ui/MainWindowInner.qml
src/ui/toolbar/BatteryIndicator.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml
src/ui/toolbar/MessageIndicator.qml

Also cleaning up unused variables and some JavaScript exceptions.

Eliminating dependencies from MainToolBar

---

src/MissionEditor/SurveyItemEditor.qml
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/MissionController.cc

Fixes for #4767, #4765. Also Waypoint lines were not connecting correctly to Fixed Wing landing pattern loiter coordinate.

Plan: Fix various complex item bugs

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/MissionItemIndicatorDrag.qml
src/FlightMap/MapItems/PolygonEditor.qml
src/FlightMap/MapScale.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionEditor/MissionEditor.qml
src/MissionEditor/SurveyItemEditor.qml
src/MissionEditor/SurveyMapVisual.qml
src/MissionManager/SurveyMissionItem.cc
src/QtLocationPlugin/QMLControl/OfflineMap.qml

* Fixed some signalling bug with Portrait/Landscape
* Fixed item editor initial load setup bug with respect to fixed camera orientations
* Make sure to use clipToViewPort=false everywhere on Map.fromCoordinate, Map.toCoordinate

Survey bugs

---

src/MissionEditor/MissionSettingsEditor.qml
src/ui/preferences/GeneralSettings.qml

Fix show hide states for fields.

Plan: Mission Settings - Vehicle info

---

src/FlightDisplay/FlightDisplayViewMap.qml

* No longer locks map pan
* When vehicle has a valid gps position and follow vehicle is on
* You can still pan the map
* 5 seconds from the last map pan the map will snap back to vehicle position

Fly: Changed follow vehicle user model

---

src/AutoPilotPlugins/PX4/PowerComponent.qml
src/FactSystem/ParameterManager.cc
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/GeoFenceController.cc
src/MissionManager/MissionController.cc
src/MissionManager/SurveyMissionItem.cc
src/QGCApplication.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Settings/App.SettingsGroup.json
src/Settings/Video.SettingsGroup.json
src/Vehicle/MultiVehicleManager.cc
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/SetupView.qml
src/comm/LinkManager.cc
src/comm/MAVLinkProtocol.cc
src/comm/QGCFlightGearLink.cc
src/ui/MainWindowInner.qml
src/ui/preferences/GeneralSettings.qml

Instead of hardcoded "QGroundContorl" strings

Use QCoreApplicationName::applicationName()

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc

Plan: Various bugs

---

src/MissionEditor/GeoFenceMapVisuals.qml
src/MissionEditor/SurveyMapVisual.qml

Fix: Initial survey polygon smaller each time you add a survey

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Only show gimbal yaw if vehicle points to next waypoint

---

src/MissionEditor/MissionEditor.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

* Pattern button wil not drop panel, it will just add item
* Also Fixed Wing Landing Pattern only available on fixed wings

Handle case where there is only one complex item

---

src/MissionManager/CameraSection.FactMetaData.json
src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/MavCmdInfoCommon.json

Added:
* Stop taking video
* Stop taking photos

Plan: Add support for stop camera actions

---

src/MissionEditor/PlanToolBar.qml

* Plus minor repositioning for better readability
* Battery is placeholder only at this point. Real values coming soon.

Plan toolbar: Add battery space

---

src/FlightMap/MapItems/MissionItemIndicator.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionEditor/MissionItemEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/MissionSettingsMapVisual.qml
src/MissionEditor/SimpleItemMapVisual.qml
src/MissionEditor/SurveyMapVisual.qml
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/QmlControls/MissionItemIndexLabel.qml

Better mission item indicators, fix click to set waypoint

---

src/FlightMap/MapItems/MissionItemIndicator.qml
src/MissionEditor/FWLandingPatternMapVisual.qml
src/MissionEditor/MissionItemEditor.qml
src/MissionEditor/MissionItemStatus.qml
src/MissionEditor/MissionSettingsEditor.qml
src/MissionEditor/MissionSettingsMapVisual.qml
src/MissionEditor/SimpleItemMapVisual.qml
src/MissionEditor/SurveyMapVisual.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionSettingsComplexItem.cc
src/MissionManager/MissionSettingsComplexItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/QmlControls/MissionItemIndexLabel.qml

Plan: Support for Mission End Actions

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/FlightMap.qml

* Vehicle stays centered in map when Video is primary display
* Vehicle does not stay centered in map when Map is primary display
* Beyond that it gets kind of complicated and hard to explain to other semantics

New Follow Vehicle user model

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/PlanToolBar.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/api/QGCOptions.h

All of these will automatically arm the vehicle and then do the requested action.
Still working out support for these with ArduPilot.

New Takeoff, Start Mission, Resume Mission

---

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml

DeltaQuad meta data

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/FactSystem/FactControls/FactTextField.qml
src/PlanView/MissionItemEditor.qml
src/QGCPalette.cc
src/QGCPalette.h
src/QmlControls/QmlTest.qml

Promoted indicator colors to actual QGCPalette (editable) colors
Changed (selected) mission item color to primaryButton instead of buttonHighlight
Adjusted some colors for better contrast
Added indicator colors to QMLTest
Removed a few JavaScript exceptions caused by the order of object destruction

Palette adjustments

---

src/FlightMap/Widgets/CenterMapDropPanel.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsItem.h
src/PlanView/MissionItemEditor.qml
src/PlanView/MissionSettingsEditor.qml
src/PlanView/PlanToolBar.qml
src/PlanView/PlanView.qml
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h

Changing according to feedback

More work on Plan sync user model

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/MissionSettingsEditor.qml
src/PlanView/PlanToolBar.qml
src/PlanView/PlanView.qml

I'll detail here: https://github.com/mavlink/qgroundcontrol/issues/4868

More work on Plan user model

---

src/ui/preferences/GeneralSettings.qml

This fixes broken path selection.

Fix video save path in general settings

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionSettings.FactMetaData.json
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/PlanView/MissionSettingsEditor.qml
src/PlanView/PlanToolBar.qml
src/PlanView/PlanView.qml

I decided I was playing whack-a-mole with trying to fix usability/understandability problems with try to create an auto-save and auto-sync model at the same time. I'll explain what I did in #4868.

Change Plan sync model yet again

---

src/QGCPalette.cc
src/QGCPalette.h
src/QmlControls/QmlTest.qml
src/ui/MainWindowInner.qml

Adding colors for alert messages:
- alertBackground
- alertBorder
- alertText
I've also added some macros for color declaration and definition to make it simpler to create new colors.
A color is now defined (header file) as:
```
DEFINE_QGC_COLOR(window, setWindow)
```
The definition (cc file):
```
DECLARE_QGC_COLOR(window, "#ffffff", "#ffffff", "#222222", "#222222")
```
That's all there is to it.

QGCPalette work

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml

Added a custom slider so the touch area is larger on mobile devices.

Tweaks with the offline maps slider.

---

src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/SafetyComponent.qml

* Also made edit/combo width wider to fit most text
You'll see that it's not 100% exactly the same as before. Mostly more dense horizontally, but I think that's good since it was really tall and required a lot of scrolling to get to bottom.

Setup-Safety: sizing and positining for all font and screen size possibilities

---

android.pri
android/AndroidManifest.xml
android/src/com/hoho/android/usbserial/driver/FtdiSerialDriver.java
android/src/org/mavlink/qgroundcontrol/QGCActivity.java
android/src/org/mavlink/qgroundcontrol/UsbIoManager.java
libs/qtandroidserialport/src/qserialport_android.cpp
libs/qtandroidserialport/src/qserialportinfo_android.cpp
src/GAudioOutput.cc
src/MobileScreenMgr.cc

Also renamed main activity class with a more appropriate name as "UsbDevice" is now one of many functions provided by it, not to mention the fact the class is an Activity class.

Fixed android package hierarchy to match package name.

---

src/FlightDisplay/FlightDisplayViewWidgets.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h

I will detail how it works here: https://github.com/mavlink/qgroundcontrol/issues/4883

Add resume mission support

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/FlightMap.qml
src/FlightMap/qmldir
src/MissionManager/SimpleMissionItem.cc
src/QmlControls/QGCSlider.qml
src/QmlControls/ScreenTools.qml
src/QmlControls/SliderSwitch.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

* Much cleaner state handling to hide actions which don't really make sense
* Change altitude slider is now relative to current position. You can go up and down from there.
* Confirmation prompts are more helpful

Major cleanup to Guided Bar: visuals, states, bugs

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightMap/FlightMap.qml
src/FlightMap/MapItems/VehicleMapItem.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionManager.cc
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/SimpleMissionItem.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Plus low battery announce changes

Pile of bugs fixes around map positioning

---

src/PlanView/PlanToolBar.qml

Plan toolbar: Layout fixes to keep things from moving around

---

src/PlanView/MissionItemEditor.qml
src/PlanView/PlanView.qml
src/api/QGCOptions.h

Also added insert pattern support to hamburger

Add support for QGCOptions::waypointsOnlyMode

---

src/PlanView/MissionSettingsEditor.qml
src/PlanView/PlanToolBar.qml
src/QmlControls/QGCFileDialog.qml

Fixing plan toolbar positioning issues
Adding proper time formatting for mission time
Fixing some JavaScript exceptions while at it

Plan toolbar

---

src/PlanView/PlanView.qml

I broke Pattern button in a previous pull to add Insert pattern from hamburger menu. One step forward. one step back...

Fix add pattern

---

src/PlanView/PlanToolBar.qml

Figured out better animation for Upload button

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FlightDisplay/FlightDisplayView.qml
src/QmlControls/ToolStrip.qml

* ToolStrip recalc fixes
* Prevent Takeoff/Land buttons from showing up at the same time
* Unknown flight modes now should custom and base modes

Tool strip fixes

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

Landing velocity using wrong field text

Safety: Fix bad field

---

src/AnalyzeView/AnalyzeView.qml
src/AnalyzeView/GeoTagPage.qml
src/AnalyzeView/LogDownloadPage.qml

Make AnalyzeView controllers persistent

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/MissionManager/SurveyMissionItemTest.cc
src/MissionManager/SurveyMissionItemTest.h
src/PlanView/SurveyMapVisual.qml
src/QmlControls/QGroundControl.Controls.qmldir
src/qgcunittest/UnitTestList.cc

Repalcement for #4941 which I closed incorrectly.

Support survey polygon drag

---

src/QmlControls/ParameterEditorDialog.qml

Addresses https://github.com/mavlink/qgroundcontrol/issues/4534

Add manual entry option for enumerated and bitmask parameters

---

src/PlanView/MissionItemStatus.qml
src/PlanView/PlanView.qml
src/PlanView/SurveyMapVisual.qml
src/QmlControls/MissionItemIndexLabel.qml

* Initial survey polygon size limited to 3000mx3000m
* Plan: Altitude display at bottom wasn't showing up due to recent parenting changes

Survey size

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h

Revised changes to ArduCopter flight modes

Revised changes to ArduCopter Flight Modes

---

src/audio/QGCAudioWorker.cpp

To improve the way that TTS engines say ADSB

Exception created to improve TTS saying ADSB

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/VisualMissionItem.h
src/PlanView/PlanToolBar.qml

Also work on plan toolbar readability

Add vehicle heading to plan toolbar

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/SimpleMissionItem.cc
src/PlanView/MissionItemEditor.qml
src/PlanView/PlanView.qml

* Regeneration of mission for resume is now much more intelligent in filtering in/out the right things
* Fixed a pile of bugs around resume mission and guided actions as well

Better resume mission generation

---

qgroundcontrol.qrc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedAltitudeSlider.qml
src/FlightDisplay/qmldir
src/QmlControls/QGCSlider.qml

* Fixed wing tends to fly higher so it has a full range slider
* Other vehicle still have a 10m up or down range slider
* Slider not shows what the actual altitude you will end at is

Usability changes to guided altitude slider

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionConfirm.qml
src/FlightDisplay/GuidedActionList.qml
src/FlightDisplay/qmldir

* When appropriate the Start/Resume mission confirmation dialogs pop up. You can cancel if that isn't what you want to do
* The Actions buttons remains the same as before and this will still show up there as appropriate

Guided: Start/Resume Mission automatically pop up

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/MissionController.cc

* All sorts of start/resume mission fixes
* Show remove mission from vehicle dialog even if showing video view

Guided fixes

---

src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/FactSystem/ParameterManager.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FollowMe/FollowMe.cc
src/MissionManager/MissionManager.cc
src/Vehicle/Vehicle.cc
src/comm/MockLinkMissionItemHandler.cc

Must memset structures before use. Fix for #4911

Fix encode_chan usage

---

src/PlanView/PlanView.qml

Zoom buttons fixed on planning screen. 

---

src/PlanView/PlanView.qml

New user model for upload while actively flying a mission

---

src/AutoPilotPlugins/PX4/SensorsComponent.qml

#4989 issued problem resolved.

Fixed calibration predialog text collapse problem.

---

src/MissionManager/Survey.SettingsGroup.json
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/PlanView/SurveyItemEditor.qml

* When using hover and capture the trigger distance was not being saved to file
Fix for #4985

Trigger distance not always being written out

---

qgroundcontrol.pro
src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/CameraSectionTest.cc
src/MissionManager/CameraSectionTest.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsItem.h
src/MissionManager/Section.h
src/MissionManager/SectionTest.cc
src/MissionManager/SectionTest.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SimpleMissionItemTest.cc
src/MissionManager/SimpleMissionItemTest.h
src/MissionManager/SpeedSection.cc
src/MissionManager/SpeedSection.h
src/MissionManager/SpeedSectionTest.cc
src/MissionManager/SpeedSectionTest.h
src/MissionManager/VisualMissionItemTest.cc
src/MissionManager/VisualMissionItemTest.h
src/qgcunittest/UnitTestList.cc

* The code around the new "Sections" support was a bug farm. Sections are the new camera section and flight speed settings which show up in Mission Settings and Waypoints. Section code is not only responsible for adding mission items appropriately but it also slurps up section items from a stream of mission command to reconstitute them back into user friendly sections as opposed to a big pile of individual mission commands.
* Instead of just manually finding the bugs I wrote a set of comprehensive unit tests for Sections to find the bugs and keep them out.
* Those unit tests in turn found a pile of bugs which I then fixed.
* File save/load should be more stable now.
* Unfortunately some of the bugs where on the write side, so you may still have saved mission which don't quite load back …

Big investment in Plan oriented unit tests

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FlightMap/MapItems/MissionItemIndicator.qml
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionControllerTest.h
src/MissionManager/MissionSettingsItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItemTest.cc
src/MissionManager/SimpleMissionItemTest.h
src/MissionManager/VisualMissionItem.h
src/MissionManager/VisualMissionItemTest.cc
src/MissionManager/VisualMissionItemTest.h

Unit testing around gimbal visuals

---

src/FirmwarePlugin/FirmwarePlugin.cc

Add Canon G9 X PowerShot

---

src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionsController.qml
src/FlightMap/FlightMap.qml
src/PlanView/PlanView.qml

* New Continue Mission action which is valid when you are in the air and have a mission
* Commits describe the rest

More fixes

---

src/FactSystem/ParameterManager.cc
src/FlightDisplay/FlightDisplayView.qml

Some fixes

---

src/comm/MAVLinkProtocol.cc

Following the same logic in #3151

RC noise is defined as “unsigned”. Handle them as such.

---

src/FlightMap/Widgets/MapFitFunctions.qml
src/MissionManager/CameraSection.FactMetaData.json
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h

* Discovered more strangeness with ardupilot and empty missions Changed removeAll to use MISSION_CLEAR_ALL to work around.
* Fixed a reference to invalid home position
* Camera  section: Gimbal pitch min/min = -90:0

Mission remove all change, plus fixes

---

src/QmlControls/QGCFileDialog.qml

Mobile file save: Show existing files to save to

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/GPS/GPSManager.cc
src/GPS/GPSProvider.cc
src/GPS/GPSProvider.h
src/Settings/RTK.SettingsGroup.json
src/Settings/RTKSettings.cc
src/Settings/RTKSettings.h
src/Settings/SettingsManager.cc
src/Settings/SettingsManager.h
src/ui/preferences/GeneralSettings.qml

Configurable survey in from Settings/General page

---

src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoSurface.cc

This fixes an issue as described here: https://github.com/mavlink/qgroundcontrol/issues/4513

Video sink sync

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/PlanView/PlanToolBar.qml
src/ui/toolbar/MainToolBar.qml

Progress bar for mission upload/download

---

src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceManager.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionManager.cc
src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointManager.cc
src/MissionManager/RallyPointManager.h

* Change upload/download mechanism to not choke out the comm pipe

Plan: Sequential upload/down of individual managers

---

src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMRallyPointManager.cc
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.cc
src/MissionManager/GeoFenceManager.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/MissionManagerTest.cc
src/MissionManager/PlanElementController.cc
src/MissionManager/PlanElementController.h
src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointController.h
src/MissionManager/RallyPointManager.cc
src/MissionManager/RallyPointManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

* Plan and Fly view shows now update and not update at the right times among other things
This should be the last of the major changes. Now just testing and bug fixing.

Plan: More major re-architecture

---

src/MissionManager/GeoFenceController.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionManager.cc
src/MissionManager/RallyPointController.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/toolbar/ArmedIndicator.qml

* Load wouldn'y work correctly id vehicle didn't return capabilities bits
* Support ArduPilot home positiion update coming from mission item index 0

Fix initial plan loading from vehicle

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

* User panning of fly view map wasn't working correctly.
* Continue/Resume Mission was popping up at wrong times

Various Fixes

---

src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMRallyPointManager.cc
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.cc
src/MissionManager/GeoFenceManager.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionControllerManagerTest.cc
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointController.h
src/MissionManager/RallyPointManager.cc
src/MissionManager/RallyPointManager.h

If new upload to vehicle fails, continue showing previous mission in Fly.

Plan: Correctly handling of failed upload

---

src/VehicleSetup/Bootloader.cc
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/USBBoardInfo.json

This adds support for the full-sized FMUv4PRO design and the FMUv5 STM32F7 based generation.

Add support for FMUv4PRO and FMUv5 boards

---

src/JsonHelper.cc
src/JsonHelper.h
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionCommandUIInfo.cc
src/MissionManager/MissionItem.cc
src/MissionManager/SimpleMissionItem.cc
src/VehicleSetup/Bootloader.cc
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/USBBoardInfo.json

* Heading items no correctly defaulted to NaN
* File load/save supports read/write of NaN

Plan: Support load/save/default of NaN for command param

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionsController.qml

* This fixes a bug where you could have the action list and goto location confirm dialogs open at the same time

Fly-Guided: Fixed support for closing all guided dialogs

---

src/PlanView/GeoFenceEditor.qml
src/PlanView/RallyPointEditorHeader.qml
src/PlanView/RallyPointItemEditor.qml
src/PlanView/RallyPointMapVisuals.qml
src/QmlControls/QGCRadioButton.qml

Rally point drag

---

src/Vehicle/Vehicle.cc

Only mobile limits line length for fly view trajectory lines

---

src/AutoPilotPlugins/APM/APMCameraComponent.qml
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc

Fix for #5078 
@jaxxzer Can you review this?

ArduPilot Camera Setup:  Fix parameter mapping

---

src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h

Survey area is always convex polygon

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h

Correctly place firmware plugin instance data with Vehicle

---

src/ui/QGCMAVLinkLogPlayer.cc

Trying to get this thing working again

Some simple fixes to LogReplay

---

src/FlightMap/Widgets/InstrumentSwipeView.qml
src/FlightMap/Widgets/VehicleHealthWidget.qml

The view was switching to the camera controls view.

Bugfix for vehicle health instrument view

---

src/MissionManager/SurveyMissionItem.cc

Plan: More fixes for line sorting

---

src/MissionManager/MissionManager.cc

Plan upload: Better error reporting for unknown command

---

src/MissionManager/PlanMasterController.cc
src/Vehicle/Vehicle.cc

Fix PlanMasterController:sendPlanToVehicle

---

src/QGCQFileDialog.h
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h

* Removed unused/unimplemented Import/Export from Device
* Fix state when exporting and immediately importing again
* Fix file picker default *Options*

Fixes to offline maps import/export.

---

src/PlanView/PlanView.qml

Remove unnused variables in PlanView

---

src/PlanView/SurveyItemEditor.qml

* Fix positioning #5134
* Fix visibility (was showing up for multi-rotor)

Wind Rose fixes

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

Fix Safety layout

---

src/comm/LogReplayLink.cc
src/ui/QGCMAVLinkInspector.cc
src/ui/QGCMAVLinkLogPlayer.cc

Make LogReplay actually work!

---

src/PlanView/MissionSettingsEditor.qml

Mission Settings: Show disabled vehicle info when multiple firmware

---

src/GPS/GPSManager.h

Allow disconnect/reconnect of RTK GPS

---

src/ui/MainWindowInner.qml

Disarm while in air will pop Emergency Stop

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/ui/preferences/MockLink.qml

This allows for better multi-vehicle testing

Stop one MockLink at a time

---

src/AutoPilotPlugins/PX4/CameraComponent.qml

Camere trigger button for testing

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h

Fixes for #5061, #5020
It's still a little quirky in that it will pop some intermediate states of start/continue but then it will work fine. I'm think I"m going to leave it that way for the release. Fixing it ends up being too complex at this point.

ArduPilot: Add start mission support

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

Fixes for #5186. Takeoff should work better now on ArduPilot.

Better retries on arming, flight mode change and APM guided

---

src/FlightDisplay/GuidedActionsController.qml

Temp hack which adds console logging to debug guided command enable/disable state problems.

Hack to debug guided enabled problem

---

src/MissionManager/MissionSettingsItem.cc

Discard bogus home position

---

src/ui/linechart/LinechartWidget.cc
src/ui/linechart/LinechartWidget.h

Analyze: Add timeout to filter changes

---

qgroundcontrol.pro

Doing so in order to allow plugins to override it.

Change target definitions order

---

src/FlightDisplay/FlightDisplayView.qml
src/MissionManager/MissionController.cc
src/MissionManager/SurveyMissionItem.cc
src/PlanView/PlanToolBar.qml
src/PlanView/SurveyItemEditor.qml

Plan fixes

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h
src/Settings/Video.SettingsGroup.json
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h
src/VideoStreaming/VideoStreaming.cc
src/VideoStreaming/VideoStreaming.pri
src/ui/preferences/GeneralSettings.qml

Adding mp4 and mov files types in addition to mkv
Adding mux GStreamer plugin libraries to Android (to enable video recording on Android)
Adding an option to limit the amount to disk used for saving videos
Adding an option to show/hide the REC button (allowing plugins to handle the recording in their own way)

Work on Video Streaming (mostly related to recording it)

---

localization/qgc.ts

These have been uploaded to crowdin and are ready for people to start translating.
https://crowdin.com/project/qgroundcontrol

Updating localization strings

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/AutoPilotPlugins/Common/RadioComponent.qml
src/AutoPilotPlugins/PX4/SensorsComponent.qml
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

ArduPilot: Support perflight barometer/airspeed calibration

---

src/MissionManager/MissionManager.cc
src/MissionManager/SurveyMissionItem.cc

* Grid entry location was writing out the incorrect value in .plan files
* For Resume Mission pull any DO_CHANGE_SPEED commands from the front of the mission for generated resume mission

Survey fixes

---

src/MissionManager/CameraSection.cc
src/MissionManager/CameraSectionTest.cc

Fix MAV_CMD_VIDEO_START_CAPTURE usage

---

src/PlanView/CameraSection.qml

Bug introduced by recent change to add Take Photo. Time and Distance fields not showing up at correct times.

Camera Section: Fix Time/Distance value visibility

---

src/VehicleSetup/Bootloader.cc
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareImage.cc
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/VehicleSetup/PX4FirmwareUpgradeThread.cc

@dagar Can you code review? I don't have any V3 boards so I can't test fully. Do you have a V3 board to test as well?

Support for V3 flashing

---

src/MissionManager/SurveyMissionItem.cc

If the result of the grid generation and polygon intersection leads to less then two transects (includes 0 transects case) use a single transect which goes through the center of the polygon instead.

Survey: Handle case of transects < 2

---

src/PlanView/PlanToolBar.qml

* Upload button is not shown while plan is uploading
* Upload button is not shown on Done screen

Plan: Better user model for Upload button

---

src/PlanView/SurveyItemEditor.qml

Solve error in survey input via windrose

---

src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/CameraSectionTest.cc
src/MissionManager/CameraSectionTest.h

* Section scanning was failing depending on command order/combination.
* Added unit test to prevent it from happening again

CameraSection: Scanning fixes plus unit test

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FirmwarePlugin/FirmwarePlugin.cc
src/GPS/GPSManager.cc
src/GPS/GPSManager.h
src/GPS/GPSProvider.cc
src/GPS/GPSProvider.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/GPSRTKFact.json
src/Vehicle/GPSRTKFactGroup.cc
src/Vehicle/GPSRTKFactGroup.h
src/ui/toolbar/GPSRTKIndicator.qml

This is not yet ready for review / testing, but shows the direction I'm trying to take it into. @DonLakeFlyer If you beat me to it it would be fantastic to have an indicator in the toolbar representing the local RTK unit.

[WIP] First stab at GPS RTK indicator

---

HackAndroidFileDialog.qrc
HackFileDialog.qrc
qgroundcontrol.pro
src/QmlControls/HackAndroidFileDialog.qml
src/QmlControls/HackFileDialog.qml
src/QmlControls/QGCFileDialog.qml
src/QmlControls/QGroundControl.Controls.qmldir

https://bugreports.qt.io/browse/QTBUG-61424

Hack workaround to 5.9 android FileDialog Qt bug

---

src/MissionManager/MissionItem.cc
src/MissionManager/MissionItem.h
src/MissionManager/MissionItemTest.cc
src/MissionManager/MissionItemTest.h

Moves all params into param array instead of using GeoCoordinate for param 5/6/7

New V3 format for mission items

---

src/QmlControls/QGCComboBox.qml

Fix coloring of QGCComboBox dropdowns

---

src/QmlControls/ScreenTools.qml

Don't drop point-size on Linux

---

src/MissionManager/MissionSettingsItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItemTest.cc
src/MissionManager/SimpleMissionItemTest.h
src/MissionManager/VisualMissionItem.h

Fixes for relative altitude signalling

---

src/MissionManager/CameraSectionTest.cc

CameraSection: Fixup unit test to new NaN usage

---

qgcresources.qrc
src/QmlControls/QGroundControlQmlGlobal.cc
src/Vehicle/GPSRTKFact.json
src/ui/toolbar/GPSRTKIndicator.qml
src/ui/toolbar/Images/RTK.svg

Still some WIP and testing to do on this

RTK Indicator updates

---

src/QmlControls/ScreenTools.qml

Small screen, fall back to font based sizing

---

src/AnalyzeView/LogDownloadController.cc

Change to log file extension handling

---

android/src/org/mavlink/qgroundcontrol/QGCActivity.java
src/MobileScreenMgr.cc

Keep Android screen from sleeping while QGC is running.

---

src/Vehicle/Vehicle.cc

Allow RADIO_STATUS message to pass through to vehicle

---

src/FirmwarePlugin/APM/APMGeoFenceManager.cc
src/FirmwarePlugin/APM/APMRallyPointManager.cc
src/MissionManager/PlanMasterController.cc
src/Vehicle/Vehicle.cc

Fix bad signalling when fence/rally not supported

---

src/api/QGCCorePlugin.cc
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/ui/preferences/GeneralSettings.qml

* Support telemetry logging on mobile builds. Defaults to off.
* Fix android vehicle shutdown problem
* Fix for #5276
* Replacement for #5357

Mobile telemetry logging

---

src/MissionManager/PlanMasterController.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Attempting a hack to fix problem where fly view doesn't show plan correctly.

Fly view fixes

---

src/MissionManager/SurveyMissionItem.cc

Caused transect intersection failure in some cases

Survey: Bounding extension was too short

---

src/ui/MainWindow.cc
src/ui/MainWindow.h

Helps battery life. For for #5374

Delay creation of MAVLinkDecoder until it is needed

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/px4_custom_mode.h

@dagar This is rebased and future-proofed. Also in sync with upstream PR.

PX4 copy current custom modes

---

src/PlanView/SurveyItemEditor.qml

Hide wind rose until bugs are fixed

---

src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygonTest.cc
src/MissionManager/QGCMapPolygonVisuals.qml

* Use centroid for polygon center instead of boundary center
* Fix center position updating

New polygon center calc

---

src/MissionManager/Survey.SettingsGroup.json
src/ui/MainWindow.cc

Stable fixes

---

src/MissionManager/MissionController.cc
src/Vehicle/Vehicle.cc

Handle bogus lat/lon from ArduPilot

---

ios/iOSForAppStore-Info-Source.plist
qgroundcontrol.pro
src/api/QGCCorePlugin.cc
src/ui/MainWindow.cc

Stable merge

---

src/FlightDisplay/GuidedActionsController.qml

Resume mission shows up at wrong times

---

src/VehicleSetup/FirmwareUpgradeController.cc

Update for ArduCopter 3.5 release

---

src/QmlControls/FactSliderPanel.qml

FactSliderPanel.qml: Correct brackets position

---

src/MissionManager/GeoFenceController.cc

GeoFenceManager: Add missing signals

---

qgcresources.qrc
qgroundcontrol.pro
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/Images/adsbVehicle.svg
src/FlightMap/MapItems/VehicleMapItem.qml
src/PlanView/PlanView.qml
src/Vehicle/ADSBVehicle.cc
src/Vehicle/ADSBVehicle.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MockLink.cc
src/comm/MockLink.h

ADSB vehicles shown in blue, with altitude under:

Add support for ADSB vehicle display

---

QGCSetup.pri

Fix for #5454. Fingers crossed.

Linux: Add missing lib

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/MapItems/VehicleMapItem.qml
src/Vehicle/ADSBVehicle.cc
src/Vehicle/ADSBVehicle.h

Flight display: Add callsign to transponders

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewVideo.qml

This removes the recording button from view when there is no gstreamer available.

Fixups for building without gstreamer/videostreaming support

---

src/AutoPilotPlugins/PX4/SafetyComponent.qml

This allows average users to flick their setup into HITL mode.

PX4 Safety settings: Expose HITL param

---

src/QGCApplication.cc
src/QGCApplication.h
src/QtLocationPlugin/QGCTileCacheWorker.cpp

* Switch test from `8.8.8.8:53` to `www.github.com:80`
* Route Internet test function to main app.
```
bool QGCApplication::isInternetAvailable()
```

Internet Test

---

src/Vehicle/Vehicle.cc

Fixes https://github.com/mavlink/qgroundcontrol/issues/5522

Fix for missing altitude updates on APM

---

src/QGCApplication.cc
src/QGCApplication.h
src/QtLocationPlugin/QGCTileCacheWorker.cpp

Internet availability test fixes

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h

If the upload of the modified resume mission fails you will now get this:
You will still also get the specific error the mission upload failure as well.

Better handling of resume mission upload failures

---

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h

For https://github.com/bluerobotics/qgroundcontrol/issues/29

Add missing sub modes

---

src/PlanView/SurveyItemEditor.qml

This will not allow the scroll of PlanView while using wind rose

Wind rose solution

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/GuidedActionsController.qml
src/FlightMap/MapItems/PlanMapItems.qml
src/FlightMap/qmldir
src/comm/MockLinkMissionItemHandler.cc

This is the precursor to having Fly view should flight plans for all vehicles when in multi-vehicle view mode.

Encapsulate Fly view map items into PlanMapItems control

---

src/uas/UAS.cc
src/uas/UAS.h

Cherry picked #5504 from master to try to fix #4328. Unfortunately it does not fix #4328. But is is a real problem nonetheless.

Stable: Buffer overrun in UAS.cc

---

src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml

Intrument Widget alternate control: Fix broken settings dialog display

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/MapItems/PlanMapItems.qml
src/PlanView/PlanView.qml
src/QGCApplication.cc

Fly: Show missions from all vehicles

---

src/MissionManager/CameraSection.FactMetaData.json
src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/CameraSectionTest.cc
src/MissionManager/CameraSectionTest.h
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc

* Add support for new CAMERA_SET_MODE. CAMERA_MODE_IMAGE_SURVEY
* Survey now sets camera mode to CAMERA_MODE_IMAGE_SURVEY

CAMERA_MODE_IMAGE_SURVEY support

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

Add distance to home to Vehicle FactGroup

---

src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/CameraSection.cc
src/MissionManager/CameraSection.h
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SpeedSection.cc
src/MissionManager/SpeedSection.h

* So for example Survey camera shot interval time would not update
* Also put back GuidedActionsController logging to track down Resume Mission state problem

Flight Speed changes were not flowing through rest of mission items

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.5.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.3.7.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.3.8.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Rover.3.2.xml
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h

Initial support for Arducopter Safe RTL

Initial support for ArduCopter SafeRTL

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Sub.3.5.xml

Update Sub 3.5 parameter metadata

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml

All subs are wired to the network.

Disable sensor calibration warning for sub

---

src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/PlanView/FWLandingPatternEditor.qml

 -DoAdd Fall rate percent in Landing Pattern editor [DO NOT MERGE till 3.3]

---

src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc
src/PlanView/FWLandingPatternEditor.qml

* Change name "Fall Rate" -> "Descent Rate"
* Fixed field alignment
Related to #5178

Fixed Wing Landing Pattern: Descent rate changes

---

src/MissionManager/VisualMissionItemTest.h

VisualMissionItemTest.h: Remove lost trailing spaces

---

src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/JoystickConfig.qml

Hello ! 
This address https://github.com/mavlink/qgroundcontrol/issues/5069. But I never use Qt before, so I am not sure of the button logic.
It has been tested with https://github.com/ArduPilot/ardupilot/pull/6128 on SITL successfully!

Joystick: add a button to support negative thrust

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FlightDisplay/GuidedActionsController.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

* Rework guided takeoff to be a capability bit
* Restructure ArduPilot guided takeoff support to work for vtol

Guided takeoff

---

CodingStyle.h
qgroundcontrol.pro
src/audio/QGCAudioWorker.cpp
src/audio/QGCAudioWorkerTest.cc
src/audio/QGCAudioWorkerTest.h
src/qgcunittest/UnitTestList.cc

Correct speech for numbers like: -10.5m

Numeric speech: Negative numbers and "m" postfix

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

Added for testing https://github.com/PX4/Firmware/pull/7939
@ndepal FYI

PX4 Firmware add DO_SET_ROI

---

src/comm/MockLinkFileServer.cc
src/comm/MockLinkFileServer.h
src/qgcunittest/FileManagerTest.cc
src/qgcunittest/FileManagerTest.h
src/uas/FileManager.cc
src/uas/FileManager.h

This adds retransmission & requesting missing parts for burst downloads.
Tested with up to 20% packet drops in both directions.
PR for the Firmware: https://github.com/PX4/Firmware/pull/7979

Make FTP more robust

---

src/PlanView/MissionItemStatus.qml
src/PlanView/PlanView.qml

MissionItemStatus: Make waypointValuesDisplay with variable width

---

src/MissionManager/MissionManager.cc
src/MissionManager/PlanManager.cc
src/MissionManager/PlanManager.h

Fix current mission item updates

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/MissionManager/StructureScan.SettingsGroup.json
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/SurveyMissionItem.cc
src/PlanView/StructureScanEditor.qml
src/PlanView/StructureScanMapVisual.qml

Related to #5694.
* Mission generation/upload does work
* File load/save not working
* Various stats, like distance, camera shots and so forth are still not calculated
* Requires a gimbal which supports yaw. This is due to parameters which force vehicle yaw while flying a mission. Working on a solution for this.

Initial Structure Scan support

---

qgroundcontrol.qrc

My Structure Scan pull screwed up Surey item resource

Put back resource from bad change

---

qgroundcontrol.pro
src/api/QGCSettings.cc
src/api/QGCSettings.h

Allow custom plugins to define their own list of settings panels

Custom Settings

---

src/ui/preferences/GeneralSettings.qml

Can't change save path on mobile

---

src/FirmwarePlugin/FirmwarePlugin.cc

Add cameras

---

qgroundcontrol.pro
src/Audio/AudioOutput.cc
src/Audio/AudioOutput.h
src/Audio/AudioOutputTest.cc
src/Audio/AudioOutputTest.h
src/QGCApplication.cc
src/QGCApplication.h
src/QGCToolbox.cc
src/QGCToolbox.h
src/Vehicle/Vehicle.cc
src/qgcunittest/UnitTestList.cc
src/uas/UAS.cc
src/ui/MainWindow.cc

Also hand carried text to speech changes from Stable to master. Plus
unit tests for that.
Fix for #5756

AudioOuput class restructuring

---

src/Camera/QGCCameraControl.cc
src/Camera/QGCCameraControl.h

* Enable time lapse photo mode
* Handle survey mode state

Camera Modes

---

src/AnalyzeView/LogDownloadController.cc
src/AnalyzeView/LogDownloadController.h

Fixes log download if there are more than 256 logs

fix LogDownloadController: id is uint16

---

src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/MissionManager/PlanManager.cc
src/MissionManager/PlanManager.h

Also fixed bug with ArduPilot guided waypoint write which would trash existing mission.
Fixed for #5557, #5775

Fix MISSION_CURRENT handling

---

ISSUE_TEMPLATE.md

Improve the template that is displayed for new issues with clearer direction on what information is required when a bug is posted.

Improved issue template text

---

src/MissionManager/SurveyMissionItem.cc

Add missing _cameraTriggerInTurnaroundFact.rawValue persistence

---

src/PlanView/PlanToolBar.qml

PlanToolBar: Make heading and azimuth to range 0-359

---

src/Vehicle/Vehicle.cc

Fix battery announce for battery change

---

QGCSetup.pri

Linux: Add missing XML lib

---

Jenkinsfile

http://ci.px4.io:8080/blue/organizations/jenkins/mavlink%2Fqgroundcontrol/activity

initial Jenkinsfile

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/GuidedActionsController.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Specify altitude for guided takeoff

---

src/PlanView/PlanView.qml

Fix #5812
Show an error message when creating a KML without 2 items at least

PlanView: Solve KML error

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/MissionManager/CameraCalc.FactMetaData.json
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/PlanView/StructureScanEditor.qml

* Photo count now working
* Put initial code in for vehicle yaw versus gimbal yaw. Which made me realize I need some new mavlink support to make that work correctly.

Structure scan: Photo count working, initial vehicle yaw support

---

src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/Survey.SettingsGroup.json
src/MissionManager/SurveyMissionItem.cc

Survey bounding rect intersection fix

---

UnitTest.qrc
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/MissionManager/QGCMapPolygonTest.cc
src/MissionManager/QGCMapPolygonTest.h
src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/UnitTest/BadCoordinatesNode.kml
src/MissionManager/UnitTest/BadXml.kml
src/MissionManager/UnitTest/GoodPolygon.kml
src/MissionManager/UnitTest/MissingPolygonNode.kml
src/PlanView/FWLandingPatternMapVisual.qml
src/PlanView/MissionItemMapVisual.qml
src/PlanView/PlanView.qml
src/PlanView/SimpleItemMapVisual.qml
src/PlanView/StructureScanMapVisual.qml
src/PlanView/SurveyMapVisual.qml

Click center widget in Polygon to get menu. Related to #5752

KML support for Polygons

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

Finally, in response to https://github.com/mavlink/qgroundcontrol/issues/4506
Added access to a string containing the vehicle's hobbs meter.

Adding access to the vehicle hobbs meter

---

android/AndroidManifest.xml

This reverts commit cc1fa95942fdc31a8445275b75ec88b19dba0b88.
Fixes #5787

Revert "Add debuggable to manifest"

---

qgroundcontrol.qrc
src/QmlControls/QGCView.qml
src/QmlControls/QGCViewDialog.qml
src/QmlControls/QGCViewDialogContainer.qml
src/QmlControls/QGroundControl.Controls.qmldir

This in turn allows you to use FactTextFields in QGCViewDialogs as well.

QGCViewDialog controls can now call QGCView.showDialog to stack dialogs

---

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/MissionManager/MissionController.cc

MissionController: Add takeoff only with supported vehicles

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/MissionManager/QGCMapPolygonVisuals.qml
src/PlanView/MissionItemEditor.qml
src/QGCApplication.cc
src/QGCGeo.cc
src/QGCGeo.h
src/QmlControls/EditPositionDialog.FactMetaData.json
src/QmlControls/EditPositionDialog.qml
src/QmlControls/EditPositionDialogController.cc
src/QmlControls/EditPositionDialogController.h
src/QmlControls/QGroundControl.Controls.qmldir
src/UTM.cpp
src/UTM.h

Available from mission item editor and polygon tools. Details in update daily builds features: https://docs.qgroundcontrol.com/en/releases/daily_build_new_features.html

Support for detailed Geo and UTM position editing

---

src/MissionManager/MissionController.cc
src/MissionManager/PlanManager.cc
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItemTest.cc
src/MissionManager/StructureScanComplexItemTest.h
src/MissionManager/SurveyMissionItem.cc
src/MissionManager/SurveyMissionItem.h
src/MissionManager/SurveyMissionItemTest.cc
src/MissionManager/SurveyMissionItemTest.h
src/PlanView/PlanToolBar.qml

* Added unit tests for checking last sequence number generation in complex items
* Fixed bugs found by unit tests
* Removed display of battery swap point number since calc was not working

Plan: Sequence number fixes

---

src/MissionManager/VisualMissionItem.cc

VisualMissionItem: Remove terrain altitude information for sub and boat

---

src/FlightDisplay/FlightDisplayView.qml
src/QmlControls/QGCPipable.qml

- popup don't work with map
- improve popup visible logic

QGCPipable: Only show popup icon in video

---

qgroundcontrol.qrc
src/FactSystem/FactGroup.h
src/Vehicle/ClockFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Add clock facts to widget

---

QGCInstaller.pri

The original, one step process was causing Travis to barf.

Simplify Mac package creation

---

src/MissionManager/CameraCalc.cc
src/MissionManager/CameraCalc.h
src/MissionManager/MissionController.h
src/MissionManager/PlanMasterController.cc
src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/StructureScanComplexItemTest.cc
src/PlanView/CameraCalc.qml
src/PlanView/StructureScanEditor.qml

* Fix for #5905 Structure Scan loading bug
* Added versioning to CameraCalc section
* Added support for loading old format CameraCalc sections

Fixes to CameraCalc loading plus versioning

---

src/QmlControls/QGCFileDialog.qml
src/api/QGCOptions.h

... regardless of the actual platform.

Allow custom plugins to define the use of mobile file dialog 

---

src/FlightDisplay/qmldir
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.h

This is the new QGeoMapType constructor.
```
QGeoMapType();
QGeoMapType(const QGeoMapType &other);
QGeoMapType(MapStyle style, const QString &name, const QString &description, bool mobile,
bool night, int mapId, const QByteArray &pluginName,
const QGeoCameraCapabilities     &cameraCapabilities,
const QVariantMap &metadata = QVariantMap());
```
Code tested and working :)

Code correction, Qt5.10 compatibility 

---

src/VehicleSetup/FirmwareImage.cc
src/VehicleSetup/FirmwareUpgrade.qml

Fix wording in *Firmware Upgrade* when using a single, custom firmware.

Single firmware

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.5.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.3.7.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.3.8.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Rover.3.2.xml
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc

Correction on the definitive naming of the new Flight Mode

Renaming new flight mode to SmartRTL

---

src/FirmwarePlugin/APM/MavCmdInfoCommon.json
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionCommandTreeTest.cc
src/MissionManager/MissionCommandUIInfo.cc
src/MissionManager/MissionCommandUIInfo.h
src/MissionManager/MissionItem.cc
src/MissionManager/SimpleMissionItem.cc

Defaults for MODE_ROI field (param 1) of command were not being set properly.

Plan: ROI fixes

---

src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.h
src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml
src/AutoPilotPlugins/PX4/SensorsSetup.qml

Respect FW_ARSP_MODE value for airspeed cal display

---

src/AutoPilotPlugins/PX4/SensorsSetup.qml
src/FactSystem/ParameterManager.cc

* Fix Level Horizon indicator parameter value referencing bug: #5941
* Fix confusing autopilot orientation text: #5938

Calibration fixes

---

src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygonTest.cc
src/QGCGeo.cc

This would show up in the UI as this: #5716

Fix NaN in convertGeoToNed

---

qgroundcontrol.qrc
src/FirmwarePlugin/FirmwarePlugin.cc
src/FlightDisplay/GuidedActionsController.qml
src/FlightMap/Widgets/ValuePageWidget.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/MainWindowInner.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/VTOLModeIndicator.qml

Support VTOL transition

---

QGCCommon.pri
QGCSetup.pri
qgroundcontrol.pro

This gets it closer to working. I think there are still some bundle identifier problems which require manual futzing. But this is a lot closer.

Fix iOS build

---

src/MissionManager/PlanManager.cc

ArduPilot: Fix GoTo Location

---

src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h

ArduPlane: Add missing paramNameRemapMajorVersionMap method

---

src/MissionManager/MissionController.cc

Fix fly view waypoint line generation

---

src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/VehicleSetup/VehicleComponent.h
src/VehicleSetup/VehicleSummary.qml

Fix AutoPilotPlugin::setupCompleteChanged signalling

---

src/VideoStreaming/README.md

Update gstreamer install instructions to work with Ubuntu 16.04

---

src/Vehicle/Vehicle.cc

Make VTOL transition work

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/GuidedActionsController.qml
src/FlightDisplay/GuidedAltitudeSlider.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Use default minimum takeoff alt for guided takeoff

---

src/comm/LinkManager.cc
src/comm/LinkManager.h
src/ui/preferences/GeneralSettings.qml

I think this will do it. I'm not set up to build for iOs.

Remove nmea serial port for mobile builds

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/LinkInterface.cc
src/comm/LinkInterface.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/ui/preferences/MockLinkSettings.qml

High Latency Link bit support

---

src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml

PX4 Firmware: Update param meta

---

src/QmlControls/FactSliderPanel.qml

Fix Android slider

---

src/Settings/AutoConnectSettings.cc
src/ui/preferences/GeneralSettings.qml

Fix AutoConnect settings for iOS

---

src/ViewWidgets/CustomCommandWidget.qml
src/ViewWidgets/CustomCommandWidgetController.cc
src/ViewWidgets/CustomCommandWidgetController.h

Custom Command Widget: Fix all the horribly broken stuff

---

localization/gen_translation_source.sh
localization/qgc.ts

These strings have been uploaded to crowdin and ready to be translated.

Updating strings for localization [ci skip]

---

src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/StructureScanComplexItemTest.cc
src/PlanView/StructureScanEditor.qml

This option will never be enabled since it isn't the way the new ROI commands work.

Remove disabled yawVehicleToStructure option

---

src/ui/preferences/GeneralSettings.qml

Fix NMEA settings layout

---

localization/qgc.ts
src/Vehicle/Vehicle.cc

Missing localization handling in Vehicle
Updating localization sources

Localization update

---

src/FactSystem/ParameterManager.cc
src/MissionManager/PlanMasterController.cc
src/MissionManager/VisualMissionItem.cc
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/SetupView.qml
src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h
src/comm/MockLink.cc
src/comm/MockLink.h

* Flight modes still not implemented. Waiting on message change.
* Vehicle are created from HIGH_LATENCY2 messages.
* Also includes various cauterization of UI things which should not be available on high latency link:
* Parameter and mission are not requested.
* No parameter list diplay.
* Mission upload/download not allowed

Add support for HIGH_LATENCY2

---

src/MissionManager/MissionSettingsItem.cc
src/MissionManager/VisualMissionItem.h
src/Terrain.cc
src/Terrain.h

Support batching terrain requests

---

src/MissionManager/MissionSettingsItem.cc
src/MissionManager/VisualMissionItem.h
src/Terrain.cc
src/Terrain.h

Batch terrain requests

---

QGCSetup.pri
deploy/create_linux_appimage.sh

This should fix setting up TTS correctly for AppImage. Still not sure if that will fix the crash though.

Fixes for TTS on Linux

---

src/Vehicle/Vehicle.cc

The change translates from HIGH_LATENCY2.failure_flags to standard SYS_STATUS handling for  onboard_control_sensors_present, onboard_control_sensors_enabled and onboard_control_sensors_health.
@acfloria, @dagar Can you guys check this?
Comments:
* It would be way easier if these things used the same naming as used in the MAV_SYS_STATUS_SENSOR_*. Different naming gets really confusing.
* Not sure why there a MAV_FAILURE_FLAG's which dont' map to anything. If they don't map to anything when running in non high latency mode why include them at all?

Support HIGH_LATENCY2.failure_flags

---

src/AutoPilotPlugins/Common/RadioComponentController.cc

Allow loc of radios string

---

src/MissionManager/MissionController.cc
src/Terrain.cc
src/Terrain.h

Terrain crash

---

Jenkinsfile
qgroundcontrol.pro

TODO
- run tests on Linux and OSX
- build OSX installer
- build Linux AppImage (and test it!)
- Android builds
- iOS builds

Jenkins add Linux debug

---

qgroundcontrol.pro
src/MissionManager/CameraCalc.cc
src/MissionManager/CameraCalc.h
src/MissionManager/CameraCalcTest.cc
src/MissionManager/CameraCalcTest.h
src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/CorridorScanComplexItemTest.cc
src/MissionManager/CorridorScanComplexItemTest.h
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h
src/MissionManager/TransectStyleComplexItemTest.cc
src/MissionManager/TransectStyleComplexItemTest.h
src/qgcunittest/UnitTest.cc
src/qgcunittest/UnitTest.h
src/qgcunittest/UnitTestList.cc

Complex item unit test work

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItemTest.cc
src/MissionManager/TransectStyleComplexItemTest.h

More work on better unit tests

---

src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/StructureScanComplexItemTest.cc
src/MissionManager/StructureScanComplexItemTest.h
src/PlanView/StructureScanEditor.qml

Also remove custom gimbal support.
This pull completes work on Stable 3.3.

Switch to using ROI_WPNEXT_OFFSET

---

QGCInstaller.pri

package directory was showing up in dmg file

Fix package generation

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/CorridorScanComplexItemTest.cc
src/PlanView/CorridorScanEditor.qml

Plus various bug fixes from flight testing.

Corridor Scan: applyNewAltitude support

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

Buggy and no longer needed. Related to #6142

Remove usage of PREFLIGHT_STORAGE

---

src/PlanView/MissionSettingsEditor.qml

You can bring it back in advanced mode

Hide camera section when in waypoints only mode

---

src/ui/MainWindowHybrid.qml

MainWindowHybrid: Close app if something goes wrong with item

---

README.md

These packages are needed to solve the issue described in https://github.com/mavlink/qgroundcontrol/issues/6165

added additional packages needed to build QGC

---

src/QmlControls/QGCButton.qml
src/QmlControls/QGCCheckBox.qml

This forces a commit on any uncommitted TextFields.
Related to #6150 and #6190

Set focus on button and checkbox click

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h

Also fixed shutdown crash related to joystick

Add support for VTOL transition from joystick buttons

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/Widgets/MapFitFunctions.qml
src/MissionManager/QGCMapPolygonVisuals.qml
src/PlanView/PlanView.qml

This tends to get "close". May require additional manual panning to get the fully into view. Setting a visible region for a Map in Qml is buggy as hell. Going to try to create a simple app to report to Qt.

Reposition map after KML load

---

src/MissionManager/MissionController.cc

Add missing VTOL cases

---

src/Terrain.cc

Update to new terrain url

---

src/Audio/AudioOutput.cc

AudioOutput: Create text to speech in constructor

---

src/Terrain/TerrainQuery.cc
src/Terrain/TerrainQuery.h

Also simplified error reporting, prepping for query abstraction. This completes the set of Terrain query apis: coordinate list, path, path list, carpet.
Next step: Abstract out query calls so @birchera can connect to offline.

Add TerrainCarpetQuery

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/CorridorScanComplexItem.h
src/MissionManager/CorridorScanComplexItemTest.cc
src/MissionManager/CorridorScanComplexItemTest.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h
src/MissionManager/TransectStyleComplexItemTest.cc
src/MissionManager/TransectStyleComplexItemTest.h
src/MissionManager/VisualMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/PlanView/CorridorScanMapVisual.qml
src/Terrain/TerrainQuery.cc

Tolerance filtering is still basic so you end up with more terrain adjustment waypoints than theoretically needed. But it all works.
Related to #6204

Corridor Scan Terrain: Add support for max rates and tolerance

---

src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolyline.cc
src/MissionManager/QGCMapPolyline.h
src/MissionManager/QGCMapPolylineVisuals.qml
src/MissionManager/TransectStyle.SettingsGroup.json
src/MissionManager/TransectStyleComplexItem.cc

Can be used to set Corridor Scan corridor

PolyLine load kml support

---

src/MissionManager/PlanMasterController.cc
src/ui/QGCMapRCToParamDialog.cpp

Random fixes

---

qgroundcontrol.qrc
src/PlanView/CorridorScanEditor.qml
src/PlanView/TransectStyleComplexItemStats.qml
src/QmlControls/QGroundControl.Controls.qmldir

Converted Corridor Scan to use it.

Make reusable Stats control for TransectStyleComplexItem

---

src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/PlanView/FWLandingPatternEditor.qml

Important Note: Setting different values for relative altitude for landing and loiter point is no longer supported.
Change for #5952

Fixed Wing Landing pattern: Change from Descent Rate to Glide slope

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/QGCMapPolygon.cc

Corridor Scan: Fix bad Vertex reference

---

src/Terrain/TerrainQuery.cc

Terrain Query: Better logging

---

src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/SimpleMissionItemTest.cc

Fix Corridor Scan crash

---

src/AutoPilotPlugins/APM/APMPowerComponent.h
src/AutoPilotPlugins/Common/SetupPage.qml
src/AutoPilotPlugins/PX4/PowerComponent.h
src/VehicleSetup/VehicleComponent.cc
src/VehicleSetup/VehicleComponent.h

Power components allow setup while armed but not flying

---

src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointManager.cc
src/MissionManager/RallyPointManager.h

Adds the ability to upload rally points to and download from the vehicle.

rally point upload and download functionality

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

ArduPlane Start Mission support

---

src/AnalyzeView/GeoTagController.cc
src/AnalyzeView/ULogParser.cc

GeoTag fixes

---

src/Terrain/TerrainQuery.cc
src/Terrain/TerrainQuery.h

Terrain: Better debugging support

---

QGCSetup.pri
qgroundcontrol.pro
src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml

Qt Charts doesn't work with our mobile code at the moment

PID Tuning: Make QtCharts usage desktop only

---

src/FlightMap/Widgets/ValuePageWidget.qml

* Uses SectionHeader control for each group so you can expand/collapse
* Section start out closed if no values in that section are used

Values Page: Value picker UI

---

qgroundcontrol.qrc
src/FactSystem/FactGroup.cc
src/FactSystem/FactGroup.h
src/Vehicle/DistanceSensorFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Provides values display for level orientation (not all) distance sensors in Values instrument page.
Related to #6169

Add DISTANCE_SENSOR support to Vehicle FactGroup [WIP]

---

src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

This PR need ardupilot/ardupilot#7716 modification.

Set vehicle time when finishing initial parameters read

---

src/AnalyzeView/GeoTagController.cc
src/AnalyzeView/GeoTagController.h
src/AnalyzeView/GeoTagPage.qml
src/AnalyzeView/ULogParser.cc
src/AnalyzeView/ULogParser.h

Geo Tag: Much better error reporting

---

src/VideoStreaming/gstqtvideosink/painters/videonode.cpp

Fix bluerobotics/qgroundcontrol#164
Signed-off-by: Patrick J.P <patrickelectric@gmail.com>

[WIP] videonode: Do not finish if material is different

---

src/QtLocationPlugin/QGCMapUrlEngine.cpp

maps: Statkart update to v4

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/MissionSettingsItem.h
src/MissionManager/MissionSettingsTest.cc
src/PlanView/MissionItemEditor.qml
src/QmlControls/MissionItemIndexLabel.qml

Trying this out. Not sure if better or not. Related to #6371

Different visuals for Planned Home in Plan View

---

src/MissionManager/MissionCommandTree.cc

Don't allow user to add settings item command

---

src/MissionManager/SimpleMissionItem.cc

Update terrain alts when user drags mission item

---

qgroundcontrol.pro
src/MissionManager/CorridorScanComplexItemTest.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionItem.h
src/MissionManager/QGCMapPolygonTest.h
src/MissionManager/SectionTest.cc
src/MissionManager/SurveyComplexItem.cc
src/MissionManager/SurveyComplexItem.h
src/MissionManager/SurveyComplexItemTest.cc
src/MissionManager/SurveyComplexItemTest.h
src/qgcunittest/UnitTestList.cc

Getting some name changes into a separate pull prior to cutting over to TransectStyleComplexItem

SurveyMissionItem -> SurveyComplexItem

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Fix for #6329. @mhkabir Can you check for correctness?

Support PING response

---

src/MissionManager/TransectStyleComplexItem.cc

First and last points in transects did not have altitudes set correctly

Fix bug in terrain transect adjustment

---

src/Audio/AudioOutput.cc
src/Audio/AudioOutputTest.cc

EKF was spoken something crazy like Ekkfaa. 4.2 was getting spoken as April Second.

Handle EKF and 4.2m correctly

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h
src/comm/LogReplayLink.cc
src/comm/LogReplayLink.h
src/ui/QGCMAVLinkLogPlayer.cc
src/ui/QGCMAVLinkLogPlayer.h
src/ui/QGCMAVLinkLogPlayer.ui

* Status Bar shows current time in log
* Parameter Manager no longer complains about timeouts

Slightly better Log Replay

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/SurveyComplexItem.cc
src/MissionManager/SurveyComplexItem.h

Implemented mission features in new Survey code:
* Camera shot count
* Refly at 90 degrees
This leaves:
* Hover and Capture
* Compass rose grid angle adjustment control

Refly and camera shot count support

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/VideoManager.h
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h
src/VideoStreaming/gstqtvideosink/painters/videonode.cpp

This is a weird issue, and very inconsistent, this patch **appears** (we are talking about windows, nothing is for sure) to solve the problem.
Besides me, someone can test and confirm ?
Also, replace #6365.
[AppVeyor download link.](https://ci.appveyor.com/api/buildjobs/rsrnqcvg8pk71q3e/artifacts/QGroundControl-installer.exe)

Fix video popup on windows

---

src/MissionManager/TransectStyleComplexItem.cc
src/Terrain/TerrainQuery.cc
src/Terrain/TerrainQuery.h

* Non-terrain transect style complex item were being generated with 0 Altitude. Really bad bug.
* Terrain query batching was broken. Wasn't fully clearing batch queue.

Terrain batch fix, transect style generation fix

---

src/PlanView/SurveyItemEditor.qml

Don't recalc for manual grid

---

android/build.gradle

modify the build repo to http://repo1.maven.org/maven2

modify android build repo

---

src/FactSystem/FactControls/FactValueSlider.qml
src/MissionManager/SimpleMissionItem.cc

Fix altitude change signalling

---

src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/QGCFenceCircle.cc
src/MissionManager/QGCFenceCircle.h
src/MissionManager/QGCFencePolygon.cc
src/MissionManager/QGCFencePolygon.h
src/MissionManager/QGCMapCircle.cc
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointController.h
src/PlanView/GeoFenceMapVisuals.qml

GeoFence persistence was missing!
Fix for #6439.

Implement GeoFence persistence

---

src/QmlControls/DropPanel.qml

Allow DropPanel dynamic sizing

---

src/MissionManager/CameraCalc.FactMetaData.json
src/MissionManager/CameraCalc.cc
src/MissionManager/CameraCalc.h
src/MissionManager/CameraCalcTest.cc
src/MissionManager/CameraCalcTest.h
src/MissionManager/StructureScan.SettingsGroup.json
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/StructureScanComplexItemTest.cc
src/MissionManager/SurveyComplexItem.cc
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h
src/PlanView/CameraCalc.qml

Survey, Corridor Scan, Structure Scan now save last settings. This also allows custom builds to override all these values.

Save fact settings for new Transect code

---

src/MissionManager/SurveyComplexItem.cc
src/MissionManager/SurveyComplexItem.h
src/MissionManager/SurveyComplexItemTest.cc
src/PlanView/SurveyItemEditor.qml

* Use Rotate Entry Point button instead of combo box
* Entry point location no longer saves setting

Survey: Rotate survey entry

---

src/PlanView/FWLandingPatternMapVisual.qml

Fixed Wing Landing Pattern: Visualize landing area

---

src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionController.cc

Fix standalone coords affecting time/distance

---

src/MissionManager/SimpleMissionItem.cc
src/PlanView/SimpleItemEditor.qml

Better help for alt mode

---

src/PlanView/PlanToolBar.qml
src/ui/toolbar/MainToolBar.qml

Mission Upload/Download progress is impossible to see outdoor. Now uses giant version of progress bar like parameter download on Outdoor theme.

Plan: Large progress bar in Outdoor theme

---

src/FlightDisplay/CheckList.qml
src/QmlControls/QGCCheckListItem.qml

This is 90% coding style. There are two real changes in here:
* Using properties to name states
* A couple places where boolean logic was changed to make it easier to understand
Should be a no-op from a functionality standpoint.

Pre-Flight Checklist: Coding style cleanup

---

qgroundcontrol.qrc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/PreFlightCheckList.qml
src/FlightDisplay/qmldir
src/QmlControls/PreFlightCheckButton.qml
src/QmlControls/QGroundControl.Controls.qmldir

* QGCCheckListItem -> PreFlightCheckButton
* CheckList -> PreFlightCheckList

PreFlight Check List: Control renaming

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/PreFlightBatteryCheck.qml
src/FlightDisplay/PreFlightCheckList.qml
src/FlightDisplay/PreFlightRCCheck.qml
src/FlightDisplay/PreFlightSensorsCheck.qml
src/FlightDisplay/PreFlightSoundCheck.qml
src/QmlControls/DropPanel.qml
src/QmlControls/PreFlightCheckButton.qml

* Added support for sat count to Sensors check control. Default checklist does not check sat count.

PreFlight: Style cleanup and changes

---

src/PlanView/CameraCalc.qml

More commonly known terminlogy

CameraCalc: Image Density -> Ground Res

---

src/MissionManager/CorridorScanComplexItem.cc
src/PlanView/SurveyItemEditor.qml

Also fixed bug in Corridor Scan time between shots calculation.

Survey: Allow VTOL vehicles to fly alternat transects

---

src/PlanView/FWLandingPatternEditor.qml
src/PlanView/SectionHeader.qml

* Allow custom build to hide relative alt checkbox
* Fixed SectionHeader drop arrow positioning

Fixed Wing Landing Pattern: Relative alt checkbox override

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/QGCXPlaneLink.cc
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h

Also moved the code from UAS to Vehicle.

Remove usage of ATTITUDE in favor of ATTITUDE_QUATERNION

---

src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h
src/MissionManager/TransectStyleComplexItemTest.cc
src/MissionManager/TransectStyleComplexItemTest.h
src/PlanView/CorridorScanEditor.qml
src/PlanView/StructureScanEditor.qml
src/PlanView/SurveyItemEditor.qml

Warning about time between shots lower than camera mimimum was broken.

cameraMinTriggerInterval now comes from CameraCalc

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

Fix ArduCopter Start Mission support

---

qgroundcontrol.pro
src/KMLFileHelper.cc
src/KMLFileHelper.h
src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/CorridorScanComplexItem.h
src/MissionManager/CorridorScanComplexItemTest.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolyline.cc
src/MissionManager/SectionTest.cc
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/StructureScanComplexItemTest.cc
src/MissionManager/SurveyComplexItem.cc
src/MissionManager/SurveyComplexItem.h
src/MissionManager/SurveyComplexItemTest.cc
src/MissionManager/TransectStyleComplexItem.cc
src/PlanView/PlanView.qml
src/QGCApplication.cc

This makes the user model for creating complex mission items from KML files much easier:
If needed you are prompted for which type of item you want to create from the KML:

Support for Sync - Load KML

---

QGCSetup.pri
android/build.gradle
src/ui/MainWindowHybrid.qml

Also, add test for an existing window before attempting to close it. This is for when the main window isn't created because of some error and when you attempt to close it, the code tries to call a function within it. As it's not there, the application can never exit.

Add missing libraries to Linux build

---

qgroundcontrol.pro
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMHeliComponent.cc
src/AutoPilotPlugins/APM/APMHeliComponent.h
src/AutoPilotPlugins/APM/APMHeliComponent.qml
src/FactSystem/FactControls/FactCheckBox.qml
src/FirmwarePlugin/APM/APMResources.qrc

ArduCopter: Initial Heli Setup page

---

src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml

ArduCopter Tuning - Remove Hover Throttle from tuning

---

qgroundcontrol.qrc
src/FlightDisplay/BuiltInPreFlightCheckModel.qml
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/qmldir
src/QmlControls/PreFlightCheckList.qml
src/QmlControls/PreFlightCheckModel.qml
src/QmlControls/QGroundControl.Controls.qmldir

PreFlight: Reorganize to retain state

---

src/FlightDisplay/VideoManager.cc
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h

Expose VideoReceiver allowing plugins to override it.

---

Jenkinsfile

Jenkins docker linux & android switch to 2018-06-08 tag

---

src/FlightMap/Widgets/ValuePageWidget.qml

Fix for vehicle widget bug

---

src/FlightDisplay/FlightDisplayView.qml
src/Vehicle/Vehicle.cc

This can block a high latency link. In addition due to the latency it does not make sense to send control commands anyway over that link.

Do not send virtual joystick commmands over high latency links

---

src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/StructureScanComplexItemTest.cc

Structure Scan: Fix lastSequenceNumber calc

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/GuidedActionsController.qml
src/FlightMap/MapItems/MissionItemIndicatorDrag.qml
src/MissionManager/QGCMapCircleVisuals.qml
src/QGCApplication.cc

Draggable radius adjustment for Orbit

---

src/MissionManager/PlanManager.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Change Orbit to use COMMAND_INT

Vehicle send COMMAND_INT support

---

src/AnalyzeView/ULogParser.cc
src/FollowMe/FollowMe.cc
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGeoCodeReplyQGC.cpp
src/QtLocationPlugin/QGeoCodingManagerEngineQGC.cpp
src/QtLocationPlugin/QGeoMapReplyQGC.cpp
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
src/VideoStreaming/VideoStreaming.cc
src/VideoStreaming/gstqtvideosink/painters/openglsurfacepainter.cpp
src/qgcunittest/TCPLinkTest.cc
src/qgcunittest/TCPLoopBackServer.cc
src/ui/MainWindow.cc

I'm not sure if I _can_ update qwt related code.

More random corrections around the code

---

QGCInstaller.pri

Fix TTS deployment on OSX

---

src/Settings/App.SettingsGroup.json
src/ui/preferences/GeneralSettings.qml

After a ridiculous amount of time fighting with Qml Layout I finally have a Settings page which works at any windows/font size. It's not quite as pretty as the previous one, but pretty close.
iPhone 5s:

Settings page which works at any size

---

src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/QGCMapPolylineVisuals.qml
src/PlanView/FWLandingPatternMapVisual.qml
src/PlanView/RallyPointMapVisuals.qml
src/PlanView/SimpleItemMapVisual.qml

Add missing mapControl property setting

---

src/MissionManager/SimpleMissionItem.cc

Fix _LAND altitude

---

src/FlightDisplay/GuidedActionsController.qml

This is a partial workaround to testing using SITL where plane never lands

No continue mission when disarmed

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/Vehicle/Vehicle.cc
src/comm/LinkInterface.cc

Ardu pilot reboot

---

qgroundcontrol.pro
src/Vehicle/Vehicle.cc
src/comm/LinkInterface.cc
src/comm/LinkInterface.h
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/comm/MavlinkMessagesTimer.cc
src/comm/MavlinkMessagesTimer.h

- Reset the comm lost timer with every mavlink message instead of the heartbeat
- Fix the link fallback in case of multiple links

Comm lost fixes

---

src/AutoPilotPlugins/APM/APMHeliComponent.qml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.6.xml

More Heli setup

---

qgcresources.qrc
resources/helicoptericon.svg
src/AutoPilotPlugins/APM/APMHeliComponent.cc

Adding helicopter icon to Heli Setup (Ardupilot)

---

src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/VisualMissionItem.cc
src/QmlControls/AppMessages.qml
src/Terrain/TerrainQuery.cc
src/Terrain/TerrainQuery.h

Fix: Terrain path query

---

src/PlanView/PlanView.qml

* Load Plan
* Save to KML
* Load Plan (it tries to load KML instead)

Plan: Fix load bug

---

src/FactSystem/FactControls/FactValueSlider.qml
src/FactSystem/FactValueSliderListModel.cc
src/FactSystem/FactValueSliderListModel.h

FactValueSlider: Fix element sizing

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

This looks to be the minimum I needed to do to fix the segfault.

Buxfix-segfault - Added board ID for NXPHlite

---

.appveyor.yml
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/USBBoardInfo.json

From #6679 
@davids5 I've added the info for auto connect. I didn't mess with the firmware upload.

Add auto connect support for the PX4 NXPHlite v3.x

---

QGCExternalLibs.pri
QGCSetup.pri
libs/airmapd/include/airmap/date_time.h
libs/airmapd/macOS/Qt.5.9/libairmap-qt.0.0.1.dylib
libs/airmapd/macOS/Qt.5.9/libairmap-qt.dylib
src/Airmap/AirMapAdvisoryManager.cc
src/Airmap/AirMapFlightPlanManager.cc

Update QGC to work with the latest master of airmapd (i.e. without depending on boost).
Note that the airmapd binaries for macOS are in the repo. Should I update them, or should they not be versioned in the first place?
@dogmaphobic: FYI

Remove boost dependency from airmap public interface

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightDisplay/GuidedActionsController.qml

Radius was not being passed correctly to Orbit command. Leading to radius always being 30.
Related to https://github.com/PX4/Firmware/pull/9434.

Fix orbit radius

---

src/MissionManager/PlanManager.cc
src/MissionManager/PlanManager.h

Same as #6718 but on Stable_V3.4 branch

Carryover ArduPilot changes from stable

---

qgroundcontrol.pro
src/GPS/GPSManager.cc
src/GPS/GPSManager.h
src/GPS/GPSProvider.cc
src/GPS/GPSProvider.h
src/GPS/vehicle_gps_position.h
src/comm/LinkManager.cc
src/comm/USBBoardInfo.json
src/ui/preferences/GeneralSettings.qml
src/ui/toolbar/GPSRTKIndicator.qml

Rebased version of #6713.
Let's see if CI passes...

Add Trimble MB-Two GPS support #2

---

src/MissionManager/StructureScan.SettingsGroup.json
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/PlanView/StructureScanEditor.qml

Structure Scan: Add ability to set Gimbal Pitch on manual scan

---

src/MissionManager/QGCMapPolygonVisuals.qml

Fixed issue where the "Set Circle Radius" menu entry was trying to affect the visibility of an item within a component.
Fixes #6725

Circle Radius

---

src/FlightMap/FlightMap.qml
src/MissionManager/QGCMapPolygonVisuals.qml
src/PlanView/MissionItemEditor.qml
src/Settings/App.SettingsGroup.json

* Change Edit Position Dialog button from Cancel to Close which makes more sense
* Update help text to Hover/Flight Speed in Mission Start to better explain what they are for

Random changes

---

src/Audio/AudioOutput.cc
src/AutoPilotPlugins/APM/APMSensorsComponent.qml

* Fix reboot
* Fix PreArm speech

ArduPilot setup fixes

---

src/FirmwarePlugin/FirmwarePlugin.cc

* Sentera NDVI Single Sensor
* Sentera Double 4K Sensor

Add Sentera cameras

---

src/FactSystem/FactValueSliderListModel.cc
src/FactSystem/FactValueSliderListModel.h
src/QmlControls/QGCViewMessage.qml

* Fix for #6740
* QGCViewMessage uses flickable

Fix FactValueSlider initial value calcs

---

src/Vehicle/Vehicle.cc

WIND_COV: Fix negative wind direction

---

src/PlanView/FWLandingPatternEditor.qml

Insert item with vehicle connected:
You can also adjust after creation:

FW Landing Pattern: Allow set position/heading from vehicle

---

src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.h
src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
src/Settings/FlightMap.SettingsGroup.json
src/Settings/FlightMapSettings.cc
src/Settings/FlightMapSettings.h

Hi, 
I implemented the new map for Korea. It is clearer and has more information for Korea. 
I think it is very useful for Korea drone guys.
Thanks in advance
Best Regards,
SungTae Moon

create new vworld map for Korea

---

src/MissionManager/CameraCalc.cc
src/MissionManager/CameraCalc.h
src/MissionManager/CameraSpec.cc
src/MissionManager/CameraSpec.h
src/QtLocationPlugin/QMLControl/OfflineMap.qml

Wrap text in Offline Map Options

---

qgroundcontrol.qrc
src/api/QGCCorePlugin.cc
src/ui/preferences/HelpSettings.qml

Dirt simple but gets the job done:
Fix for #6643

Add new Help page under Settings

---

qgcresources.qrc
resources/chevron-down.svg
resources/chevron-up.svg
resources/clockwise-arrow.svg
resources/counter-clockwise-arrow.svg
src/FlightDisplay/VirtualJoystick.qml
src/QmlControls/JoystickThumbPad.qml

Minor tweak to the virtual joystick graphics suggested by @dagar

Virtual joystick graphics

---

src/MissionManager/QGCMapPolygonVisuals.qml

Respect app units in setting polygon circle radius

Polygon Circle: Respect app units

---

src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.h
src/AutoPilotPlugins/PX4/SensorsSetup.qml

Prompt for Reboot after compass cal

---

src/PlanView/MissionItemEditor.qml

Plan: Change Command only supported for Simple Items

---

src/MissionManager/TransectStyleComplexItem.cc

This change is for Stable only and let the query object leak to prevent the crash. The real fix is way more complex. These objects are quite small so they won't lead to running out memory for a really long time. Also discovered they were already leaking in the normal case as well.
Related to #6781

Hack fix for terrain crash when new query comes through before old query is complete

---

src/MissionManager/TransectStyleComplexItem.h
src/Terrain/TerrainQuery.cc

Terrain fixes

---

ChangeLog.md
src/FlightDisplay/GuidedActionsController.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/QGCLoggingCategory.cc
src/QGCLoggingCategory.h
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h

Fix Resume Mission item count bug

---

ChangeLog.md
src/MissionManager/MissionController.cc
src/MissionManager/MissionSettingsItem.cc

Plan: Fix terrain NaN making it all the way to Planned Home altitude.

---

ChangeLog.md
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionsController.qml

Multi-Vehicle Start/Pause Fixes

---

src/QGCApplication.cc
src/QGCApplication.h
src/QmlControls/ScreenToolsController.h

Remove unused code

---

src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/PX4/PowerComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FlightDisplay/FlightDisplayViewWidgets.qml
src/QGCApplication.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h
src/uas/UASMessageHandler.cc

Move ArduPilot preflight check handling to generic QGC

---

ChangeLog.md
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/MissionManager/GeoFenceController.cc

* Turn off unsupported Orbit support

Plan GeoFence: Fix loading of files saved from version prior to Stable 3.4

---

src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc
src/VehicleSetup/Bootloader.cc
src/VehicleSetup/FirmwareImage.cc
src/comm/QGCJSBSimLink.cc
src/ui/MAVLinkDecoder.cc

Use `QString QString::arg(const QString &a1, const QString &a2, const QString &a3) const` in place of multiple arg calls.
This makes the strings to be replaced in one pass.

Use QString::arg and not multiple arg calls

---

ChangeLog.md
src/FlightMap/FlightMap.qml
src/PositionManager/PositionManager.cpp
src/PositionManager/PositionManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

Add Distance to GCS to Vehicle FactGroup

---

src/MissionManager/PlanManager.cc
src/comm/MockLinkMissionItemHandler.cc

Use MAV_COMP_ID_AUTOPILOT1 instead of MAV_COMP_ID_MISSIONPLANNER

---

ChangeLog.md
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

Heading to Home on Vehicle FactGroup

---

src/PlanView/PlanView.qml
src/ui/MainWindowInner.qml

Fix Plan save message on exit

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/SurveyComplexItem.cc

Fix for #6916. All compex items were broken.

Fixed camera shot count when trigger distance == 0

---

ChangeLog.md
src/FactSystem/ParameterManager.cc

Fix multi-component parameter loading

---

ChangeLog.md
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/MissionManager/QGCMapPolygonVisuals.qml

Allows you to set a polygon vertex from entered lat/lon/utm value or current vehicle position.

Polygon editing: Edit position available on vertices

---

src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummarySub.qml
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc

Update sub components to use new battery failsafe parameters

---

src/AutoPilotPlugins/APM/APMPowerComponent.qml
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc

Add renamed battery parameters to parameter maps

---

src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h

ArduPilot: Update Rover flight modes

---

src/Vehicle/ADSBVehicle.cc

ADSB: Fix flag checks

---

src/PlanView/SimpleItemEditor.qml
src/Vehicle/VehicleFact.json

Use correct terminology for Altitude values

---

src/AutoPilotPlugins/APM/APMCameraComponent.cc
src/AutoPilotPlugins/APM/APMCameraSubComponent.qml
src/FirmwarePlugin/APM/APMResources.qrc

It is based on the existent APMCameraComponent.qml, with some changes:
- Added slider for tilt speed
- No input channel
- "Gimbal settings" and roll/pan panels hidden by default

Create simplified camera page for sub

---

android/AndroidManifest.xml

This is a Google Play store requirement as of November 1st, 2018.
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

AndroidManifest.xml increase targetSdkVersion 19 -> 26

---

src/AutoPilotPlugins/Common/RadioComponent.qml
src/comm/MockLink.cc
src/ui/MainWindow.cc
src/ui/MainWindow.ui

Radio setup: Rework ui

---

src/PlanView/SurveyItemEditor.qml

Survey item editor: Layout fixes

---

qgroundcontrol.qrc
src/AutoPilotPlugins/APM/APMTuningComponent.cc
src/AutoPilotPlugins/APM/APMTuningComponentSub.qml
src/FactSystem/FactControls/FactTextFieldSlider.qml
src/FactSystem/FactControls/qmldir
src/FirmwarePlugin/APM/APMResources.qrc

This adds a tuning page for submarines:

Add tuning page for Sub

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h

ArduPilot: Don't starts streams from QGC side. Assume firmware side does the right thing

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Based on the current procedures and discussions with developers on the #qgroundcontrol channel on Slack

Add bug report issue template

---

src/FlightDisplay/FlightDisplayViewUVC.qml
src/FlightDisplay/VideoManager.cc
src/FlightDisplay/VideoManager.h
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h

Some long overdue UVC code clean up and properly handling multiple UVC sources.

Fix UVC handling

---

src/SHPFileHelper.cc
src/SHPFileHelper.h
src/UTM.cpp
src/UTM.h

@antiheavy I tested with a fake file I hand created. Can you test with real files once this is merged in?

Support UTM SHP files

---

src/comm/MAVLinkProtocol.cc
src/comm/MAVLinkProtocol.h

Malvink radio mismatch: Prevent counter overflow

---

src/QmlControls/PageView.qml

Fix Values Widget gear color based on new combo box colors

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/ui/preferences/MavlinkSettings.qml

Default is on.
Related to #7017, #7014

ArduPilot option to not start mavlink streams

---

.appveyor.yml

@dagar Does this look right? YAML is new to me.

AppVeyor: Store symbol artifacts only for Stable builds

---

src/ui/QGCMAVLinkInspector.cc
src/ui/QGCMAVLinkInspector.h

Mavlink Inspector: Fix support for single vehicle coming and going

---

src/Vehicle/Vehicle.cc

Fix connections to offline vehicle

---

src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h
src/MissionManager/RallyPointController.cc
src/MissionManager/RallyPointController.h
src/MissionManager/RallyPointManager.cc
src/MissionManager/RallyPointManager.h

AutoLoad: Not loading GeoFence or Rally points correctly

---

src/Airmap/AirmapSettings.qml
src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionManager/QGCMapCircleVisuals.qml
src/QmlControls/ScreenTools.qml
src/QmlControls/ScreenToolsController.h
src/comm/BluetoothLink.cc
src/comm/BluetoothLink.h
src/comm/LinkConfiguration.h
src/comm/LogReplayLink.h
src/comm/MockLink.h
src/comm/SerialLink.h
src/comm/TCPLink.h
src/comm/UDPLink.h
src/ui/preferences/BluetoothSettings.qml
src/ui/preferences/LinkSettings.qml
src/ui/preferences/LogReplaySettings.qml
src/ui/preferences/MockLinkSettings.qml
src/ui/preferences/SerialSettings.qml
src/ui/preferences/TcpSettings.qml
src/ui/preferences/UdpSettings.qml

Tackling the comm link configuration dialogs. These have been in a "WIP" state since first written a few years ago. Preparing for a new link in a following PR.

Comms cleanup

---

.travis.yml
QGCCommon.pri
src/VideoStreaming/VideoStreaming.pri

... and enabling the daily build.

Moving Android to GStreamer 1.14.4

---

src/MissionManager/FixedWingLandingComplexItem.cc

I did a code inspection to try to find bugs related to #7107. Found a couple minor problems but nothing that would cause it.

FW Landing Pattern: Scan fixes

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/api/QGCCorePlugin.h

This way custom builds can remove the ones they don't want.

Plan: Support custom build override of available complex items

---

src/PlanView/SimpleItemEditor.qml

Related to #7125 which I will finish up the write up on. This pull is slightly different than the current state of the write-up. But I think it's significantly better than what is currently in there. So I'm going to merge this in once it passes. Then I'll finish up the write up and start the discussion.

Plan: Altitude modes rework

---

src/QmlControls/DropPanel.qml

Sizing of panel and positioning of items in panel wasn't quite correct.

DropPane: Size/Position fixes

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/QmlControls/ToolStrip.qml

Toolstrip tweaks

---

src/MissionManager/MavCmdInfoCommon.json

Default abort alt = 0. This works around problems between multi-rotor and fixed wing

---

qgcresources.qrc
resources/DropArrow.svg
src/PlanView/SimpleItemEditor.qml

Plan: AltMode visual tweaks

---

src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightMap/Widgets/VideoPageWidget.qml

* Add video stream screen fit options (Fit Width, Fit Height or Stretch)
* Added camera zoom control using pinch action on the video window

Video fit and camera pinch zoom

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Firmware Update: add PX4 Omnibus F4 SD

---

src/FactSystem/FactSystem.h
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/MissionManager/FWLandingPattern.FactMetaData.json
src/MissionManager/FWLandingPatternTest.cc
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/PlanView/FWLandingPatternEditor.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MockLink.cc
src/ui/MAVLinkDecoder.cc

Replacement for #7152

---

android/src/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java
android/src/com/hoho/android/usbserial/driver/UsbId.java

Android USB: Add VID/PID for ArduPilot ChibiOS and DragonLink

---

src/PlanView/SurveyItemEditor.qml

Survey: Remove Split Polygon support since it causes crashes

---

.travis.yml

Move Linux to Qt 5.11.3

---

src/QmlControls/AppMessages.qml

Bad position on small tablet sizing

Console: Fix GStreamer Debug positioning

---

src/PlanView/MissionSettingsEditor.qml
src/PlanView/PlanView.qml

* Hide ROI
* Show camera section in Mission Start

Plan: Tweaks to custom build waypoints only mode

---

android/AndroidManifest.xml
src/QmlControls/AppMessages.cc
src/QmlControls/AppMessages.qml
src/main.cc

Android: Fix write storage permission problem

---

android/src/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java
android/src/com/hoho/android/usbserial/driver/CommonUsbSerialDriver.java
android/src/com/hoho/android/usbserial/driver/Cp2102SerialDriver.java
android/src/com/hoho/android/usbserial/driver/FtdiSerialDriver.java
android/src/com/hoho/android/usbserial/driver/ProlificSerialDriver.java
android/src/com/hoho/android/usbserial/driver/UsbSerialDriver.java
android/src/com/hoho/android/usbserial/driver/UsbSerialProber.java
android/src/org/mavlink/qgroundcontrol/QGCActivity.java
libs/qtandroidserialport/src/qserialport_android.cpp

Fix android USB permissions

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/CorridorScanComplexItem.h
src/MissionManager/SurveyComplexItem.cc
src/MissionManager/SurveyComplexItem.h
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h
src/MissionManager/TransectStyleComplexItemTest.cc
src/MissionManager/TransectStyleComplexItemTest.h

Plan Load: Save camera shot count and complex distance in .plan file

---

Jenkinsfile

These won't pass until docker hub finishes. https://hub.docker.com/

Jenkins update to latest containers (2019-02-03)

---

src/MissionManager/MissionController.cc

Use correct QT_TRANSLATE_NOOP to prevent crash

---

src/Camera/QGCCameraManager.cc
src/Camera/QGCCameraManager.h

Fix crash bug that could occur when disconnecting/reconnecting a camera.

Fix crash bug that could occur when reconnecting a camera.

---

CodingStyle.qml

Fix typo in CodingStyle.qml

---

src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/Joystick/JoystickManager.cc

Also:
* Move HITL setting on Safety page to bottom
* Hide HITL section if param is not available

PX4: Warn if HITL is enabled on vehicle

---

ChangeLog.md
src/MissionManager/StructureScan.SettingsGroup.json
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/StructureScanComplexItemTest.cc
src/PlanView/StructureScanEditor.qml

Structure Scan had a large number of Issues. I've had to make some mahor changes to it to make it work better. Document for the new version is here: https://github.com/mavlink/qgc-user-guide/blob/master/en/PlanView/pattern_structure_scan_v2.md

Structure scan fixes (V2)

---

src/QGCApplication.cc
src/QmlControls/QGCCheckBox.qml

Same as https://github.com/mavlink/qgroundcontrol/pull/7243

Check box update

---

src/api/QGCOptions.h
src/ui/preferences/MavlinkSettings.qml

The option flag is accessible from QGCOptions

Feature: add option to hide MAVLink Logging from settings

---

src/FirmwarePlugin/FirmwarePlugin.cc

* Added a few more Sony and Yuneec cameras 
* Made camera description indicate lens focal length and aperture
* For zoom lenses, the indicated focal length (and the data) is the lens in its widest focal length

Added more cameras

---

src/VehicleSetup/SetupView.qml

Don't show _Click Firmware on the left_ if firmware upgrade is disabled.

Don't show "Click Firmware on the left"

---

QGCSetup.pri
deploy/create_linux_appimage.sh

Add optional support to source binaries names, title and icon from ENV
Also copy all dependencies of ICU libs to cover all configurations
please review: @dogmaphobic @DonLakeFlyer @dagar

Add support for AppImage customization

---

src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorController.h

You can now select to only show the changed ones (different from their default value)

Allow filtering parameters

---

qgroundcontrol.pro
src/AnalyzeView/MavlinkConsolePage.qml
src/QGCApplication.cc
src/ui/MainWindowInner.qml
src/ui/toolbar/MainToolBar.qml

The console will replace the entire `Analyze` view
TODO: Improve the experience

WIP: Enable mavlink dev console in expert mode for mobile devices

---

android/src/org/mavlink/qgroundcontrol/QGCActivity.java

**Description:**
QGC is periodically probing for new accessories instead of detecting a plug in event.
Current period is set at 3 seconds. Sometimes the question "Do you allow ... " appears twice.
This is also unnecesarrily taking away CPU and battery time.
**To Reproduce**
- Uninstall QGC
- Install it again
- Plugin Taisync accessory
- A question "Do you allow ... " appears. Do not confirm or cancel immediately.
- Another question pops up
**Expected behavior**
- Detect the event of plugging accessory in and act only once
**Description of solution**
Android does not create event USB_ACCESSORY_ATTACHED as expected, but it was found that event onResume is generated, so we can limit accessory probing to onresume instead on timer.
https://stackoverflow.com/questions/19770788/intent-filter-not- …

Taisync - remove probing timer, use onResume as plug in detection event

---

src/AnalyzeView/AnalyzeView.qml
src/AnalyzeView/MavlinkConsolePage.qml

Complete previous WIP commit that brings mavlink console to mobile devices

Fix mavlink console

---

QGCCommon.pri
qgroundcontrol.pro
qgroundcontrol.qrc
src/Microhard/MicrohardHandler.cc
src/Microhard/MicrohardHandler.h
src/Microhard/MicrohardManager.cc
src/Microhard/MicrohardManager.h
src/Microhard/MicrohardSettings.cc
src/Microhard/MicrohardSettings.h
src/Microhard/MicrohardSettings.qml
src/QGCToolbox.cc
src/QGCToolbox.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/api/QGCCorePlugin.cc

Added Microhard configuration panel.
When enabled it offers Microhard modem configuration and display of connection status & RSSI values.

PR Configuration for microhard pMDDL modems

---

ChangeLog.md
src/AutoPilotPlugins/Common/SetupPage.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.cc
src/comm/QGCSerialPortInfo.cc
src/comm/QGCSerialPortInfo.h
src/comm/USBBoardInfo.json

* Related to #7261, #7318
* Also includes support for Flashing ChibiOS Bootloader from the Firmware page
Missing support for autoconnect to boards with ChibiOS bootloader, but PX4 Pro Firmware.

Full ChibiOS bootloader support, plus autoconnect for ChibiOS builds

---

src/Camera/QGCCameraControl.cc
src/Vehicle/Vehicle.cc

Fixes https://github.com/mavlink/qgroundcontrol/issues/7323

Make sure video streaming is running before accessing it.

---

src/FirmwarePlugin/PX4/MavCmdInfoCommon.json
src/MissionManager/MavCmdInfoCommon.json

Hack around ArduPilot problems with unsupported NaN in Loiter commands

---

src/comm/USBBoardInfo.json

Wildcard connect to all Hex boards

---

src/MissionManager/MavCmdInfoCommon.json

Heading: Switch from Radians to Degrees

---

src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/ui/preferences/MockLink.qml

Also verified that Simple mode already there and working.
Fix for #7358

ArduPilot: Add Follow mode to Rover

---

src/PlanView/FWLandingPatternEditor.qml

Use standard (Rel)/(AMSL) labeling

Fixed Wing Landing Pattern: Use standard Altitude Mode labeling

---

src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h

Add distance calculation of structure scan.

the battery and distance of structure scan always show 0

---

ChangeLog.md
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/comm/SerialLink.h

https://discuss.cubepilot.org/t/sb-0000002-critical-service-bulletin-for-cubes-purchased-between-january-2019-to-present-do-not-fly

ArduPilot: Cube black service bulletin check

---

.appveyor.yml
ChangeLog.md
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/comm/SerialLink.h

Biggest thing this does is puill across ArduPilot Cube Black service bulletin check

Upstream stable merge

---

qgroundcontrol.qrc
src/MissionManager/BreachReturn.FactMetaData.json
src/MissionManager/GeoFenceController.cc
src/MissionManager/GeoFenceController.h
src/MissionManager/GeoFenceManager.cc
src/MissionManager/RallyPointManager.cc
src/PlanView/GeoFenceEditor.qml
src/PlanView/GeoFenceMapVisuals.qml
src/PlanView/PlanView.qml

* You can drag the "B" indicator around to change location.
* Also fixed a bunch of bugs in geofence/rally support.

Add support for geofence return point. 

---

ChangeLog.md
QGCSetup.pri

Ubuntu startup: Revert library install changes

---

src/AutoPilotPlugins/APM/APMPowerComponent.qml
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/GuidedActionConfirm.qml
src/FlightDisplay/GuidedActionsController.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Smart RTL is available from guided actions:
ESC Calibration is available on Power setup page:

ArduPilot: Smart RTL and ESC Calibration support

---

src/QGCApplication.cc
src/QmlControls/QGCHoverButton.qml
src/QmlControls/QmlTest.qml
src/QmlControls/ToolStrip.qml

Pr tweaks toolstrip qmltest

---

ChangeLog.md
src/AutoPilotPlugins/APM/APMAirframeComponent.cc
src/AutoPilotPlugins/APM/APMAirframeComponent.h
src/AutoPilotPlugins/APM/APMAirframeComponent.qml
src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
src/AutoPilotPlugins/APM/APMAirframeComponentController.h
src/AutoPilotPlugins/APM/APMAirframeComponentSummary.qml
src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml
src/FactSystem/FactControls/FactPanelController.cc

ArduPilot: Rover Frame setup support, Copter advanced tuning

---

ChangeLog.md
src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml

PX4: Pid tuning - fix missing param MC_YAW_FF

---

ChangeLog.md
src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml
src/QmlControls/PIDTuning.qml

ArduCopter PID tuning support

---

ChangeLog.md
src/PlanView/GeoFenceMapVisuals.qml
src/Terrain/TerrainQuery.cc

Geo fence polygon vertex crash

---

src/FactSystem/FactGroup.cc
src/FactSystem/FactGroup.h
src/QmlControls/PIDTuning.qml

* Bump update rates for vehicle values used in charts to make them useful
* Tweaks to charting to make tick marks better

PID tuning usability

---

src/MissionManager/MissionCommandTree.cc
src/MissionManager/MissionCommandTree.h

Command Tree contains all commands

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/Vehicle/Vehicle.cc

ArduPilot: Visual accel cal

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

Fix for #4290
@antiheavy @AndKe Could use some testing to make sure this is working.

Add Throttle % as vehicle fact

---

src/Vehicle/Vehicle.cc

Update throttle % fact from VFR_HUD message

---

src/VideoStreaming/VideoReceiver.cc

This solves the issue where the video is lost for a few seconds after clicking record as the pipelines waits for the filesink to preroll but it does not receive a valid buffer because the probe is dropping anything that is not an I-frame, stalling the whole pipeline. 
This issue is mostly noticeable in videos with larger intervals between I-frames.
I tested with this pipeline:
```gst-launch-1.0 videotestsrc pattern=ball ! video/x-raw,width=1920,height=1080,framerate=30/1 !  videoconvert ! x264enc bitrate=5000 ! video/x-h264, profile=baseline ! rtph264pay ! udpsink host=127.0.0.1 port=5600```
Before:
After:

Delay adding filesink to recording branch until after an I-frame arrives

---

ChangeLog.md
src/Camera/QGCCameraControl.cc
src/Camera/QGCCameraControl.h
src/FlightMap/Widgets/CameraPageWidget.qml

Following [this conversation](https://github.com/mavlink/qgroundcontrol/issues/7434).
Closes #7434

Check and respect camera storage status

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc

With the switch to QtQuick, all file dialogs from the c++ side no longer work. This was marked as _TODO_ and fell through the cracks.

Switch custom firmware file picker to QtQuick

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Experimenting with gimbal control

Add gimbal control command to Vehicle

---

src/comm/LogReplayLink.cc
src/comm/LogReplayLink.h

Code which determined final timestamp in file only worked some of the time.
Fix for #7474

Log replay: Fix log file reading

---

src/FlightMap/Images/ZoomMinus.svg
src/FlightMap/Images/ZoomPlus.svg
src/QmlControls/QGCHoverButton.qml
src/QmlControls/ToolStrip.qml

Tweaking toolstrip layout

---

src/PlanView/MissionSettingsEditor.qml

Switch to clearer property usage

---

src/MissionManager/MissionCommandTree.cc
src/QmlControls/ParameterEditorDialog.qml

Crash and typo fixes

---

ChangeLog.md
deploy/qgroundcontrol_installer.nsi

* Change crash dumps to mini-dumps
* Prepping changelog for 3.5.3 release

Windows: Always install PX4 Drivers

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h

Missed another case like #7498

Firmware Flash: Fix crash caused by NULL vehicle

---

ChangeLog.md
deploy/qgroundcontrol_installer.nsi

Reverts mavlink/qgroundcontrol#7522

Revert "Windows: Always install PX4 Drivers"

---

ChangeLog.md
deploy/qgroundcontrol_installer.nsi

New drivers weren't getting installed at the right time

Windows: Change USB driver detection logic

---

ChangeLog.md
src/Settings/RTK.SettingsGroup.json

Fix for https://github.com/PX4/Devguide/issues/809

Change Survey-In min accuracy

---

src/AutoPilotPlugins/APM/APMHeliComponent.qml

ArduCopter Heli: Support 8 servos

---

ChangeLog.md
src/FlightDisplay/VideoManager.cc
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/Taisync/TaisyncManager.cc
src/Vehicle/Vehicle.cc
src/VideoStreaming/README.md
src/VideoStreaming/VideoReceiver.cc
src/ui/preferences/GeneralSettings.qml

Adding RTP UDP h.265

---

src/Vehicle/Vehicle.cc

Fix for #7541. @dogmaphobic Can you reivew this?

Fix ADSB vehicle timeout

---

src/comm/LogReplayLink.cc
src/comm/LogReplayLink.h
src/ui/MainWindow.cc
src/ui/QGCMAVLinkLogPlayer.cc
src/ui/QGCMAVLinkLogPlayer.ui

Pull across from master:
* Full width status bar
* Better scrubbing support

Log replay cherry pick

---

android/src/org/mavlink/qgroundcontrol/QGCActivity.java

Fixes to Stable for #7444 and #7445

Cherry-pick android joystick crash fixes from master

---

QGCSetup.pri

We don't support any other msvc anyway

Remove mentions to MSVC < 2015

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Firmware support was added here: https://github.com/PX4/Firmware/pull/12440

Firmware update: add KakuteF7 support

---

ChangeLog.md
src/VideoStreaming/VideoItem.cc
src/VideoStreaming/VideoItem.h

Video item crash

---

.appveyor.yml

Windows: Switch to 1.14.4 gstreamer

---

ChangeLog.md
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/USBBoardInfo.json

Cherry pick FMUK66 updates from master to Stable

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Rover.3.5.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Rover.3.6.xml

Rover 3.5 generated at Ardupilot tag Rover-3.5.1
Rover 3.6 generated at Ardupilot master
Tested with SITL:
Fix #7596

Update APMRover metadata

---

custom-example/res/Custom/Widgets/CustomVehicleButton.qml
custom-example/res/CustomFlyView.qml
custom-example/src/CustomPlugin.cc
src/comm/MockLink.cc
src/comm/MockLink.h

Custom multi-vehicle indicators/selector. Only visible when more than one vehicle is connected.

Custom tweaks

---

custom-example/res/Custom/Widgets/CustomVehicleButton.qml
custom-example/res/CustomCameraControl.qml
custom-example/res/CustomFlyView.qml

Multi-vehicle now moved to the left of **vehicleIndicator**
Shutter button - fixed radius and border

Custom theme - Multi vehicle and Camera Shutter fixes

---

src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h

Fixes issue with AirMap plugin flight planning features not showing up

Fix AirMap

---

custom-example/res/CustomCameraControl.qml
custom-example/res/MainToolbar/CustomModeIndicator.qml
custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc

* Narrow the flight mode options
* Use a custom selector for flight modes
* Fix logic deciding to show quick thermal options.

Custom flight modes

---

src/Camera/QGCCameraManager.cc
src/Camera/QGCCameraManager.h
src/Joystick/Joystick.cc
src/Joystick/Joystick.h

* Handle _Button Up_ state (Joystick)
* Process Start/Stop zoom within camera manager.

Joystick button state

---

custom-example/res/CustomCameraControl.qml
custom-example/res/CustomFlyView.qml

Fix gimbal state getting out of the limits.
Fix palette button not working if not in thermal mode.
Increase zoom buttons

Custom Example: Minor fixes for custom build controls

---

custom-example/res/Custom/Camera/ZoomControl.qml
custom-example/res/CustomCameraControl.qml

Fix gimbal indicator so that angle values match the markers
Highlight thermal mode on thermal menu item selection

Fix gimbal indicator display

---

custom-example/res/CustomCameraControl.qml

Fix for thermal camera which doesn't provide a palette

custom-example: Fix gimbal view and an edge case for thermal options

---

src/Camera/QGCCameraControl.cc

Put camera back to Idle if no response.
Better debugging message to identify camera issues.

Photo idle

---

src/FlightDisplay/FlightDisplayView.qml

Disable preflight checklist if vehicle is armed.

---

src/MissionManager/FWLandingPattern.FactMetaData.json
src/PlanView/FWLandingPatternEditor.qml

FW Landing Pattern: Use clearer "Approach Altitude" terminology for loiter altitude.

---

src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/comm/TCPLink.cc

Remove deprecated warnings while building the software.

Remove deprecated

---

.travis.yml

Fix for android builds

---

src/MissionManager/MissionManager.cc

This memset seems to create an issue with GotoLocation on Ardupilot : https://github.com/ArduPilot/ardupilot/issues/12085
@DonLakeFlyer

MissionItem memset to 8 instead of 0

---

src/AnalyzeView/GeoTagController.cc
src/PlanView/SimpleItemMapVisual.qml

Current waypoint is draggable in Fly view

---

src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.cc

Use correct parameter based on firmware type not vehicle type.

ArduRover Flight Mode setup fixes

---

qgroundcontrol.qrc
src/MissionManager/QGCMapPolylineVisuals.qml
src/PlanView/CorridorScanMapVisual.qml
src/PlanView/SurveyMapVisual.qml
src/PlanView/TransectStyleMapVisuals.qml
src/QmlControls/QGroundControl/Controls/qmldir

* Corridor scan now works like #7746
* Created new TransectStyleMapVisuals control which is the base for both Survey and Corridor

Corridor scan visuals

---

qgroundcontrol.qrc
src/MissionManager/MapLineArrow.qml
src/PlanView/TransectStyleMapVisuals.qml
src/QmlControls/QGroundControl/FlightMap/qmldir

* Simplify entry/exit points
* Use arrows to show flight direction

Survey visuals

---

src/PlanView/MissionItemEditor.qml
src/QmlControls/MissionItemIndexLabel.qml

If you really need to know an item number it's available from the hamburger.

Plan: Hide sequence numbers

---

src/QGCApplication.cc
src/ui/preferences/GeneralSettings.qml

Correct Qml engine shutdown

---

src/FlightDisplay/FlightDisplayView.qml
src/ui/MainRootWindow.qml

Move Log Replay bar to Window footer

---

src/FlightMap/MapItems/MissionLineView.qml
src/MissionManager/MapLineArrow.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/PlanView.qml
src/PlanView/TransectStyleMapVisuals.qml

More work on direction arrows

---

src/PlanView/FWLandingPatternMapVisual.qml

Working on making it clearer how a fixed landing works. Specific problem is the possibility of hitting obstacles ont he way down the glide slope. Still a WIP, but pushing first set of changes through now.

FW Landing Pattern: Updated visuals

---

src/FlightDisplay/FlightDisplayViewVideo.qml
src/Settings/VideoSettings.h

Comments on Loader added to FlightDisplayViewVideo explains it.

Disable video workaround for gstreamer crashes

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/FlightMap/MapScale.qml
src/PlanView/PlanView.qml
src/QtLocationPlugin/QMLControl/OfflineMap.qml

Plan: Add Terrain toggle to MapScale control

---

qgroundcontrol.qrc
src/PlanView/FWLandingPatternMapVisual.qml
src/PlanView/StructureScanMapVisual.qml
src/PlanView/TransectStyleMapVisuals.qml
src/QmlControls/QGCDynamicObjectManager.qml
src/QmlControls/QGroundControl/Controls/qmldir

Provides a set of tools for dynamic qml object create/add/destroy:
```
function createObject(sourceComponent, parentObject, parentObjectIsMap)
function createObjects(rgSourceComponents, parentObject, parentObjectIsMap)
function destroyObjects()
```

New QGCDynamicObjectManager support

---

qgroundcontrol.qrc
src/PlanView/FWLandingPatternMapVisual.qml
src/QmlControls/HeightIndicator.qml
src/QmlControls/QGroundControl/Controls/qmldir

FW Landing glide slope heights display

---

src/FlightDisplay/FlightDisplayViewMap.qml
src/MissionManager/MissionController.cc
src/QmlControls/CoordinateVector.cc
src/QmlControls/CoordinateVector.h

Fly View direction arrows

---

qgroundcontrol.qrc
src/FlightMap/MapItems/SplitIndicator.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/PlanView.qml
src/QmlControls/QGroundControl/FlightMap/qmldir

Plan: Allow split of current flight segment

---

src/FlightMap/MapItems/SplitIndicator.qml
src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/QGCMapPolylineVisuals.qml
src/PlanView/CorridorScanMapVisual.qml
src/PlanView/SurveyMapVisual.qml
src/PlanView/TransectStyleMapVisuals.qml

Use new SplitIndicator control

---

src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/PlanView/MissionItemEditor.qml
src/QmlControls/MissionCommandDialog.qml

Correctly handle command changes from no-coordinate item to coordinate

---

qgroundcontrol.qrc
src/FactSystem/FactControls/FactCheckBox.qml
src/FirmwarePlugin/APM/MavCmdInfoCommon.json
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h
src/PlanView/PlanView.qml
src/PlanView/SurveyItemEditor.qml
src/QmlControls/QGCOptionsComboBox.qml
src/QmlControls/QGroundControl/Controls/qmldir

Here it is being used in Survey Item:

New QGCOptionsComboBox control

---

src/PlanView/CorridorScanEditor.qml
src/QmlControls/QGCComboBox.qml
src/QmlControls/QGCOptionsComboBox.qml

* Also fixed Combo Box dropdown indicator color

Use Options control in Corridor scan

---

.travis.yml
src/Audio/AudioOutput.cc
src/Audio/AudioOutput.h
src/PositionManager/PositionManager.cpp
src/QGCApplication.cc
src/QtLocationPlugin/QGCTileCacheWorker.cpp

They are clean now so good to keep them clean.

QT_FATAL_WARNINGS on for unit tests

---

src/PlanView/SimpleItemMapVisual.qml

Only hide generic waypoint indicators

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/PlanView.qml

Plan: Fix SplitSegment mission item insertion

---

src/MissionManager/MissionController.cc

A bug was added while rebasing. Here a fix

Rename i in VisualItemIndex

---

ChangeLog.md
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlightDisplayViewMap.qml
src/FollowMe/FollowMe.cc
src/FollowMe/FollowMe.h
src/PositionManager/PositionManager.cpp
src/PositionManager/PositionManager.h
src/PositionManager/SimulatedPosition.cc
src/PositionManager/SimulatedPosition.h
src/QGCApplication.cc
src/QGCApplication.h
src/Settings/App.SettingsGroup.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Reworked follow me:
* Plugin'ized Follow Me support so QGC mainline doesn't have PX4 stuff in it
* Changed code to limit signalling when not needed
* Added support for ArduCopter/Rover follow me
* Updated position simulator such that it can be used to test Follow Me
Fix for #7811

Follow Me work

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

Stream HOME_POSITION on ArduPilot

---

qgroundcontrol.qrc
src/PlanView/CameraCalcCamera.qml
src/PlanView/CameraCalcGrid.qml
src/PlanView/CorridorScanEditor.qml
src/PlanView/StructureScanEditor.qml
src/PlanView/SurveyItemEditor.qml
src/QmlControls/QGroundControl/Controls/qmldir

Plan: Use TabBar in Complex Item UI

---

src/AutoPilotPlugins/APM/APMAirframeComponent.qml
src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
src/AutoPilotPlugins/APM/APMAirframeComponentController.h
src/VehicleSetup/FirmwareUpgrade.qml

* No longer allows selection of unsupported frame/class combinations
* Fixed problems where flying saucer image was shown for unselected classes
* Fixed Firmware Upgrade to make it scrollable and fixed broken combo box

ArduPilot: Airframe Setup

---

src/QGCApplication.cc
src/QGCApplication.h

Remove duplicates from missing parameter reporting

---

ChangeLog.md
qgroundcontrol.qrc
src/MissionManager/QGCMapPolygonVisuals.qml
src/MissionManager/QGCMapPolyline.cc
src/MissionManager/QGCMapPolyline.h
src/MissionManager/QGCMapPolylineVisuals.qml
src/PlanView/CorridorScanEditor.qml
src/PlanView/CorridorScanMapVisual.qml
src/PlanView/PlanEditToolbar.qml
src/QmlControls/QGroundControl/Controls/qmldir

New corridor editing tools:
* Corridor Scan starts with no polyline set
* New Corridor Tools toolbar
* Ability to trace a polyline by clicking
* New PlanEditToolbar custom control to hold the shape editing tools (Polygon, Polyline, ...). Handles flickable if screen width is too small to hold all content.

Corridor edit toolbar

---

src/PlanView/PlanEditToolbar.qml
src/QmlControls/QGCComboBox.qml

I screwed up some imports and code which works with 5.12 but not 5.11
Fix for #7878

ComboBox: Update for Qt 5.11

---

src/PlanView/PlanStartOverlay.qml
src/comm/MAVLinkProtocol.cc

* Also found another bad import which would prevent ui from displaying
Fix for #7865, #7878

Use MAV_COMP_ID_MISSIONPLANNER for QGC component id

---

tools/update_android_version.sh

Still fighting with the damn android 32/64 bit stuff!

Android: Fix versionCode

---

src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.cpp
src/QtLocationPlugin/QGCMapUrlEngine.h
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
src/Settings/FlightMapSettings.cc

Add MapType: Google Hybrid

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/FlightDisplay/FlightDisplayViewMap.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MultiVehicleSelector.qml

* Change order of toolbar indicators to keep visual ones together follow by combo box ones
* Fix spacing on toolbar to get rid of strange gap
* Fix Fly View white screen problem #7875
* Change Multi-Vehicle selector to a combo box

Toolbar changes plus other stuff

---

src/FlightDisplay/FlightDisplayViewMap.qml

Fix scoping of visibility changes

---

src/FactSystem/FactControls/FactPanelController.cc

Missing Parameters: Translate to actual component id

---

src/FactSystem/SettingsFact.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/PlanMasterController.h
src/PlanView/PlanView.qml

* Fix #7907 - Show correct terrain or incomplete data warnings
* Fix #7899 - New... is always enabled. Clicking New will bring up Create Plan overlay

Plan: Create Plan overlay and friends

---

src/Settings/FlightMap.SettingsGroup.json

Fix : 
The default value for MapType / MapProvider was not defined

Fix initial Map Provider setting

---

android/AndroidManifest.xml

Still working on weeks of fighting with Google Play requirements

Set target SDK to 28 to make Google Play happy

---

ChangeLog.md
src/ui/toolbar/ArmedIndicator.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/MainToolBarIndicators.qml
src/ui/toolbar/ModeIndicator.qml
src/ui/toolbar/MultiVehicleSelector.qml
src/ui/toolbar/VTOLModeIndicator.qml

Toolbar was clipped on small mobile screens. There is also a slight change in less spacing between the view buttons. Other than that this should work/look exactly like it did before.

Restructure toolbar to make it Flickable

---

src/FlightDisplay/VideoManager.cc
src/Settings/Video.SettingsGroup.json
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h
src/ui/preferences/GeneralSettings.qml

Bringing changes from downstream

Downstream update

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/VirtualJoystick.qml

Fix to keep joysticks centered and throttle output

WIP: Throttle gimbal joystick

---

src/Vehicle/Vehicle.cc

This is a follow up for the MAVLink update https://github.com/mavlink/mavlink/pull/1247.
A new field `repr_offset_q` was added to the message ATTITUDE_QUATERNION to indicate that the attitude have to be rotated before it is displayed to the user.
This is useful for example for tailsitters, which rotate their reference frame by 90 between hover mode and fixed wing mode. This leads to discontinuities in the euler representation (see screenshots in the MAVLink PR).
With this new field, a correct attitude can be displayed in QGC in both modes.
Changes:
- Update MAVLink version
- If not supported, the new field is [0, 0, 0, 0] (norm==0), and the current behaviour is preserved.
- If supported, the new field is a rotation quaternion (norm==1). The attitude and rates are then rotated before they …

Vehicle: rotate ATTITUDE_QUATERNION with repr_offset_q (fixes tailsitters attitude display)

---

src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/FlightDisplayViewWidgets.qml

Rework mission complete dialog state checks. Wasn't popping up for ArduPilot due to bad state logic. Hence broke the ability to do a Resume Mission.

Mission Complete dialog rework

---

ChangeLog.md
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

Fix supported version check

---

src/QmlControls/PageView.qml

Instrument PageView: Palette based coloring for gear icon

---

src/Vehicle/TrajectoryPoints.cc

Replacement for #8019. The clear method was not resetting internal state correctly. Causing an incorrect reference into an empty list.

Fix crash caused by clear method not resetting internals correctly

---

resources/TrashDelete.svg
src/PlanView/MissionItemEditor.qml
src/PlanView/PlanView.qml

Related to https://github.com/mavlink/qgroundcontrol/pull/8009 and https://github.com/mavlink/qgroundcontrol/pull/7982
- Insert on the current element of the list and not at the end ( "insert Waypoint" / "insert Pattern" from the Hamburger are issued by the left-hand toolbar )
- Change Trash Icon
- Change Hamburger Menu ( "Delete", "Change Command" and "Insert*" handled by MissionItem list )

Simplify mission item list 2

---

QGCExternalLibs.pri
QGCSetup.pri
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/PairingManager/PairingManager.cc
src/PairingManager/PairingManager.h
src/PhotoGallery/PhotoGalleryVehicleGlue.h
src/QGCApplication.cc
src/QGCApplication.h
src/Vehicle/VehicleObjectAvoidance.cc
src/VehicleSetup/JoystickConfigButtons.qml

Bringing changes and/or fixes from downstream.

Downstream merge

---

Jenkinsfile

This won't pass until docker hub updates (likely a couple hours from now).
- https://hub.docker.com/r/mavlink/qgc-build-android/tags
- https://hub.docker.com/r/mavlink/qgc-build-linux/tags

Jenkins: update to new containers 2019-11-08 and build Android 32 + 64

---

src/QmlControls/QGCComboBox.qml

Reduce height of items in combo dropdown

---

src/MissionManager/CorridorScanPlanCreator.cc
src/MissionManager/StructureScanPlanCreator.cc
src/MissionManager/SurveyPlanCreator.cc
src/PlanView/MissionItemEditor.qml
src/PlanView/PlanView.qml

Takeoff tool changes broken the Plan Creators in that they were not adding Takeoff items correctly

Plan creator: Fix insertion of takeoff item

---

src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml
src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml
src/AutoPilotPlugins/PX4/PX4TuningComponentPlane.qml

Advanced tuning hidden due to crash from Qt problem

---

src/FlightMap/MapItems/MissionItemIndicatorDrag.qml
src/MissionManager/QGCMapPolygonVisuals.qml

QGCMapPolygon: Fix center drag and split side

---

src/MissionManager/MissionController.cc

Fix incorrect usage of _settingsItem causing crashes

---

src/PlanView/SimpleItemEditor.qml

Better wordings for Takeoff item

---

qgroundcontrol.pro

Build custom extension for CustomQGC on `srr-qgc` branch

Build custom by default

---

src/PlanView/TakeoffItemMapVisual.qml

Plan Takeoff Item: Fix show/hide of click to set Launch location

---

src/Camera/QGCCameraManager.cc

Reverting the changes done in https://github.com/mavlink/qgroundcontrol/commit/598d1464314c5ad4574c087d0b4e588bf99fde2f
When handling MAVLink messages within the camera manager, we must filter them based solely on the component ID.

We can only filter by component ID

---

src/VideoStreaming/VideoReceiver.cc

This fix is critical if you plan to use 3rd party video sink (renderer) with QoS - it may not work with current code (and does not work in my case) because current video recording code is changing time offset for base clock, affecting whole graph, including video sink. My patch avoids touching anything else except video recording pipeline.

Non-invasive media file offset adjusting

---

ChangeLog.md
src/FlightMap/MapItems/MissionLineView.qml
src/MissionManager/CorridorScanPlanCreator.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/StructureScanPlanCreator.cc
src/MissionManager/SurveyPlanCreator.cc
src/PlanView/MissionItemEditor.qml
src/PlanView/MissionItemStatus.qml
src/PlanView/PlanView.qml
src/QmlControls/CoordinateVector.cc
src/QmlControls/CoordinateVector.h

* ROI button will change to Cancel ROI and back at appropriate times
* When an ROI item is selected the flight path lines which are affected by the ROI change color
Fix for #8080

Plan: Cancel ROI, ROI visual indication

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/PlanView/MissionItemEditor.qml

Plan: Support move item to previous item position

---

src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml
src/AutoPilotPlugins/PX4/SafetyComponent.qml
src/FlightDisplay/GuidedActionsController.qml
src/FlightMap/Widgets/CenterMapDropButton.qml
src/FlightMap/Widgets/CenterMapDropPanel.qml
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionSettings.FactMetaData.json
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/SimpleMissionItem.cc
src/PlanView/FWLandingPatternEditor.qml
src/PlanView/MissionSettingsEditor.qml
src/PlanView/SimpleItemEditor.qml
src/QmlControls/ToolStrip.qml

Launch naming

---

src/PlanView/MissionItemEditor.qml
src/QmlControls/MissionItemIndexLabel.qml

Fixes for #8096:
* Slight increase in small item index size to fit label text better
* Fix visual for Command Picker in mission items

Visual tweaks

---

src/MissionManager/ComplexMissionItem.h
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/StructureScanComplexItem.h
src/MissionManager/TransectStyleComplexItem.cc
src/PlanView/PlanView.qml

Fix for #8023. Not pretty but workable for next Stable. Will likely come back to it again later.

Plan: Add support for incomplete segment visuals

---

QGCCommon.pri
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Distance sensor

---

src/MissionManager/PlanManager.cc
src/comm/MockLinkMissionItemHandler.cc
src/comm/MockLinkMissionItemHandler.h

Fix for #8086. Safer change than #8122 this close to stable.

Always send MISSION_ITEM_INT to ArduPilot

---

src/FirmwarePlugin/APM/APMParameterFactMetaData.Plane.4.0.xml

ArduPlane meta data update

---

src/PlanView/PlanView.qml
src/Settings/PlanView.SettingsGroup.json
src/Settings/PlanViewSettings.cc
src/Settings/PlanViewSettings.h

Persist MissisonItemStatus visibility

---

src/MissionManager/MissionController.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/VisualMissionItem.h

Plan View: Update vehicle heading from possible item change

---

src/PlanView/FWLandingPatternEditor.qml
src/PlanView/FWLandingPatternMapVisual.qml
src/QmlControls/HeightIndicator.qml
src/QmlControls/MissionItemIndexLabel.qml

* Height indicators was not using Map Pallete coloring so didn't show correctly on all map types
* Use less wordy text for caution
Related to #8069

FW Landing visuals

---

localization/qgc_tr.ts
localization/qgc_zh_CN.ts

Closes https://github.com/mavlink/qgroundcontrol/issues/8095

Update localization files

---

deploy/qgroundcontrol_installer.nsi

* Install to Program Files
* Uninstall either 32 or 64 bit

Windows: 64 bit installer changes

---

src/PlanView/CameraSection.qml
src/QmlControls/DropPanel.qml

Vehicle clear failure

---

src/MissionManager/CameraSection.cc
src/MissionManager/CameraSectionTest.cc

Fix MAV_CMD_IMAGE_START_CAPTURE usage

---

src/comm/USBBoardInfo.json

This will fix autoconnect for boards which report this

Add new ArduPilot VID/PID

---

src/AutoPilotPlugins/APM/APMFollowComponent.qml

Fix Follow X/Y calc from distance/angle

---

src/AnalyzeView/MAVLinkInspectorController.cc

In response to https://github.com/mavlink/qgroundcontrol/pull/8199#issuecomment-572904278

Sort messages by name instead of ID.

---

src/Joystick/CMakeLists.txt

Joystick: Use find_package for mac and linux

---

src/FollowMe/FollowMe.cc

Follow Me logging

---

CMakeLists.txt

This helps to improve the QML performance with COMPILE_QML and debug QML problems with DEBUG_QML
@dagar more cmake updates

cmake: Add COMPILE_QML and DEBUG_QML options

---

CMakeLists.txt
cmake/Git.cmake
src/CMakeLists.txt

Move from hardcoded git binary to git module

cmake: Add and use git module 

---

CMakeLists.txt

cmake: Remove lost code since COMPILE_QML option

---

cmake/QGCDeploy.cmake

libs/lib/Framework does not exist anymore

cmake: QGCDeploy: Update old rsync command

---

src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h

The vehicle's coordinate is kept within the Vehicle class. When the vehicle disconnects/closes, all that information is reset/lost. I've added a "current vehicle's last known location" property to the MultiVehicleManager class. That allows to present it within the UI.

Keep track of current vehicle's last known location.

---

android/build.gradle

maven url need to be set to https

set maven url to https

---

src/PlanView/PlanToolBarIndicators.qml

Fix for https://github.com/mavlink/qgroundcontrol/issues/7696

Fix Done in Toolbar when switching to Plan View

---

src/VideoStreaming/CMakeLists.txt

After the commit https://github.com/mavlink/qgroundcontrol/commit/700fab73a5d0dc8cb29e95a8aee2068083d47e93#diff-5038a9cfa5cef4b8f57c0064572b51a2
CMakeLists.txt hasn't been updated

Fixed cmake for VideoStreaming library

---

src/AutoPilotPlugins/APM/APMFollowComponent.qml

Fix for #8291 
I'm waiting to here back from folks as to whether this fix is correct. I don't quite understand how this parameter has any affect.

ArduPilot Follow Me: Support both relative and absolute FOLL_ALT_TYPE

---

src/QmlControls/QGCComboBox.qml

ComboBox: Fix sizeToContents support

---

QGCSetup.pri

Linux setup: Add missing install lib

---

CMakeLists.txt
qmlglsink.cmake
src/VideoStreaming/CMakeLists.txt

FYI @andrewvoznytsa @tcanabrava @patrickelectric

cmake add qmlglsink support (gst-plugins_good)

---

.travis.yml

To see if it's possible to manually upload 32/64 bit versions into a single release

Disable play store upload

---

src/FlightDisplay/PreFlightCheckList.qml

* Sizing to window height was not working correctly
* Added scrolling support back in
* Fix for #8289

Pre-Flight checklist: Fix sizing/scrolling

---

src/AnalyzeView/MAVLinkInspector.svg

Updated MAVLink Inspector icon to indicate it contains charting.

---

qgroundcontrol.pro
src/VideoStreaming/VideoStreaming.pri

This patch fixes https://github.com/mavlink/qgroundcontrol/issues/8281

Fix DISABLE_VIDEOSTREAMING handling

---

src/PlanView/SurveyItemEditor.qml

If the user has saved Presets then there is a second step to wizard mode.
First step continues to be polygon setup:
But if you have any presets defined then when you click Done With Polygon you go here:
(yellow button is a fluke of where I had the mouse when I captured).
Then when you click Done Adjusting you have completed the wizard.
Fix for #8296 (Survey only at this point).

Survey: Preset selection in wizard mode

---

src/ui/toolbar/MainToolBar.qml

Easter Egg was not working anymore since the last changes.

Fix EasterEgg overlayed by Flickable item

---

src/FlightDisplay/PreFlightCheckList.qml

Fixes issue where the checklist is marked as **(passed)** when only a single group has passed.
With this PR the checklist will only be marked as **(passed)** once every group in the checklist has passed.

Fix checklist (passed) header

---

src/Vehicle/Vehicle.cc

Fix placement of Vehicle::_sendNextQueuedMavCommand

---

src/FlightDisplay/VideoManager.cc
src/VideoStreaming/VideoStreaming.cc
src/VideoStreaming/VideoStreaming.pri
src/VideoStreaming/gstqgc.c
src/VideoStreaming/gstqgcvideosinkbin.c

This patch is yet another step to move things toward multiple video stream support and custom pipelines. From technical point of view it is refactoring and it could go into v4.0 after simple testing on all platforms (works/does not work is enough).

Repackage video sink into GstQgcVideoSinkBin

---

src/VideoStreaming/VideoReceiver.cc
src/VideoStreaming/VideoReceiver.h

This patch fixes https://github.com/mavlink/qgroundcontrol/issues/8321 and simplifies file recording and pipeline handling.

MKV file recording fix

---

src/MissionManager/TakeoffMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/PlanView/SimpleItemEditor.qml

Fix for #8221
First step:
Second step:

Plan: Make PX4 VTOL takeoff work like fixed wing

---

src/VideoStreaming/VideoReceiver.cc

Fixes https://github.com/mavlink/qgroundcontrol/issues/8281

Fix DISABLE_VIDEOSTREAMING (once more)

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionSettingsItem.cc
src/PlanView/PlanView.qml

Plan: Takeoff/Land insertion fixes, fix current item update after delete, fix crash

---

src/MissionManager/QGCMapPolygon.h
src/MissionManager/QGCMapPolygonVisuals.qml
src/PlanView/SurveyItemEditor.qml

Track trace mode in polygon so we can use it to exit wizard mode

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Vehicle only performs stable fw version check one time
