mavlink/qgroundcontrol

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
_loadSettings should not be called in the Vehicle constructor, it may enable/disable the joystick for the active vehicle when a new vehicle connects.
_loadSettings should be called when the active vehicle changes.
=> Bugfix joystick input handling with multi-vehicle scenario

src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
Videos are recorded in the path set within settings with a hardcoded filename (time stamp). This change allows one to specify an alternate path and filename. By default, nothing changes. Only if you write your own code to start recording video will this have any effect.
=> Allow setting a path and filename for the recorded video (optional)

android/AndroidManifest.xml
I'm not sure if this is the right way to do this, but apparently the only reason QGC isn't already available to Chromebook's (with the Play store) is the location.GPS requirement.
https://github.com/mavlink/qgroundcontrol/issues/5967
=> AndroidManifest.xml update to enable ChromeOS support

src/QtLocationPlugin/QGCTileCacheWorker.cpp, src/VideoStreaming/VideoReceiver.cc
I have no way to test this. This is an attempt in dealing with proxy issues reported in #5925. Based on the documentation, this is all you need to do. In my case, with no proxy, it all worked as before.
Fix #5925
=> Attempt at using default proxy settings.

src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
In Qt 5.10 QGeoMapType need QGeoCameraCapabilities as argument
E.g: https://github.com/qt/qtlocation/blob/2b230b0a10d898979e9d5193f4da2e408b397fe3/src/plugins/geoservices/osm/qgeotiledmappingmanagerengineosm.cpp#L167
Fix #5916
=> (Fix #5916) QGeoTiledMappingManagerEngineQGC: Use cameraCaps in QGeoMapType

src/Vehicle/MultiVehicleManager.cc
Requires PX4 Flow to remain at default vehicle id = 81 and component id = 50.
Fix for #5550
=> Special case handling of PX4 Flow connect

src/PlanView/MissionItemStatus.qml, src/PlanView/PlanView.qml
Will now hide itself on mobile if it is taking up more than 25% of the screen height.
Fix for #5528
=> Mission Item Status (Terrain/Alt): Hide based on amount of screen real estate

src/PositionManager/PositionManager.cpp, src/PositionManager/PositionManager.h, src/Settings/AutoConnect.SettingsGroup.json, src/Settings/AutoConnectSettings.cc, src/Settings/AutoConnectSettings.h, src/comm/LinkManager.cc, src/comm/LinkManager.h, src/ui/preferences/GeneralSettings.qml
This will allow the use of USB/Serial GPS for computers or mobile devices without built in positioning. The user must specify the serial port and baudrate for reading data.
=> Add NMEA GPS support for GCS position

src/FlightDisplay/FlightDisplayViewWidgets.qml, src/FlightMap/Widgets/ValuePageWidget.qml, src/QmlControls/ScreenTools.qml
Currently indicator widgets look funny on laptops with 4k screens.
=> Formatting fixes

src/FactSystem/Fact.cc, src/FactSystem/Fact.h, src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/FactSystem/ParameterManager.cc, src/FactSystem/ParameterManager.h, src/FirmwarePlugin/APM/APMParameterMetaData.cc, src/FirmwarePlugin/APM/APMParameterMetaData.h, src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc, src/PlanView/SectionHeader.qml, src/QmlControls/ParameterEditor.qml, src/QmlControls/ParameterEditorController.cc, src/QmlControls/ParameterEditorController.h
* New category level of hierarchy implemented
* ArduPilot uses existing category data in meta data
* PX4 is coded from QGC side, requires firmware side to complete and meta data update to fully flow through. Without that everything ends up in Standard/Other for now.
Related to #5965 and https://github.com/PX4/Firmware/issues/8568
=> Parameter Editor Category->Group hierarchy support

src/FirmwarePlugin/FirmwarePlugin.cc
Add camera definition for Sony NEX-5R. This camera has an APS-C sensor and is very popular for orthophoto missions, especially with the 20mm lens.
=> Add camera definition for Sony NEX-5R with 20mm lens

src/AutoPilotPlugins/PX4/AirframeComponentController.cc, src/FactSystem/Fact.cc
* Fact::forceSetRawValue was broken by change in Fact system signalling.
* Airframe Config wait cursor would get stuck due the vehicle disconnecting before the code to restore wait cursor was called.
Fix for #5986
=> ParameterManager/FactSystem: Fix force save usage pattern

src/QtLocationPlugin/QGCTileCacheWorker.cpp, src/QtLocationPlugin/QGCTileCacheWorker.h
* Fixed an issue when importing a tile set that already exists would cause an error. When an imported set has a same name, it is renamed so the name is unique. The original logic had an error and was allowing the "new" set to be added with the same name, which would cause an error. In addition, if a new tile set brings no new unique tiles, it is now ignored.
* Fixed an issue where the progress was based on the total number of incoming tiles but this total can change if a given tile already exists in the database (it is not added).
=> Offline map fixes

src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/FirmwarePlugin/APM/APMParameterMetaData.cc
It did not like the use of the tr() macro within a static QString in the constructor.
The fix may be overkill but I didn't have the time to try different things (it takes forever to get a Windows build running for me)
Fixes #5996
=> Fixed crash in FactMetadata constructor.

src/FactSystem/Fact.cc, src/FactSystem/Fact.h, src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/FactSystem/ParameterManager.cc, src/FactSystem/ParameterManager.h, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc, src/FirmwarePlugin/PX4/PX4ParameterMetaData.h
This allows for Parameters to be volatile which are not part of the calculated parameter set crc for cache hits.
=> Add support for volatile Facts/Parameters

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/MissionManager/MavCmdInfoCommon.json, src/comm/MockLink.cc
* Switch PX4 to use them
* ArduPilot still uses old ROI command
* These will not work until PX4 firmware side completes implementation
* I did not cut over Structure Scan to use ROI_WPNEXT_OFFSET yet. I will do that once firmware side ROI is fully implemented and tested to work correctly.
=> Update to new mavlink ROI commands

src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h
Fly view now slurps up additional sections like CameraSection. Without that the gimbal angle changes come after the waypoint item they related to. Which then shows incorrectly on the view.
With this change, gimbal angles show correctly. Consequence is that slurped in mission items not longer show in fly view. Which I think is sort of a good thing.
=> Fly view: Gimbal angles show on wrong items

src/MissionManager/SurveyMissionItem.cc
This prevents intersection misses on more cases. Fix for #6007
=> Use a much larger fudge factor to increase initial transect length

src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml, src/AutoPilotPlugins/Common/SetupPage.qml, src/AutoPilotPlugins/PX4/PowerComponent.qml, src/VehicleSetup/SetupView.qml
Instead of blocking all settings if the vehicle is armed, check the provided `VehicleComponent::allowSetupWhileArmed()` method. This change not only disables the settings button, but also shows @jaxxzer's overlay only when appropriate.
=> Handle settings when armed

src/PlanView/PlanView.qml, src/api/QGCOptions.h, src/ui/MainWindow.cc
Instead of checking for "Mobile" or screen percentage (when mobile), compute the available space on the fly to determine if the Mission Status and Map Scale should be shown in the Plan View. For mobile devices, that means it will be shown or not based on the device's screen size. For desktop, the decision to show them or not is dynamically computed based on the current window height.
Also added an option for plugins to determine if mission status should be shown or not.
Plan View on a "short" mobile device (room for the scale but not for the Mission Status):
Plan View on a "large enough" desktop window:
Plan View on a desktop window where it can't fit either the Scale or the Mission Status:
=> Compute plan view items visibility on the fly.

src/MissionManager/CameraCalc.h, src/MissionManager/MissionSettingsItem.cc, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/StructureScanComplexItem.h, src/PlanView/CameraCalc.qml, src/PlanView/StructureScanEditor.qml
While discussing Structure Scan with users the issue came up that a structure scan needs to be specify structure height when using a camera spec as opposed to a layer count. Without that the user needs to manually calculate the layer count based on camera image footprints which is a real PITA.
Fixing this required some fundamental changes to how structure scan works with respect to layers and camera placement. This also requiredbumping the persistence version number such that old saved structure scans will need to be recreated.
* You specify the altitude of lower bound of the bottom-most layer. The actual height of the flight path for the first layer will be above this to center the camera within the first layer.
* You specify the height of the structure
* From these two values the number …
=> Structure Scan: Structure height support

src/QGCApplication.cc, src/QmlControls/AppMessages.qml, src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoStreaming.cc, src/VideoStreaming/VideoStreaming.h
This adds a combobox to the 'Console' page next to the 'Set Logging' button, where the [gstreamer debug log leve](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html)l can be selected. When video is streaming, dot file will be output to show the pipeline graph structure regardless of debug level setting.
The files will go in to savePath setting/Logs/gst.
=> Add gstreamer debug log option, and dot file output

.appveyor.yml, src/Camera/QGCCameraControl.cc, src/Camera/QGCCameraIO.cc, src/Camera/QGCCameraIO.h, src/FactSystem/Fact.cc, src/FactSystem/Fact.h, src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/VideoStreaming/VideoStreaming.cc
Set a "Write Only" attribute to define parameter is only writable and not readable (password for example).
Updated camera control to use the updated `MAV_PARAM_EXT_TYPE_xxx` types.
=> Write only metadata

src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h
It was broken when temperature translation was added in #5903
The system wasn't quite setup to handle anything other than speed and distance. Changed so any arbitrary unit type can be converted to another.
While at it, I also found that some metadata entries have the unit set to "meter" as opposed to "meters" and it was not finding a match.
=> Fix unit translators

src/Vehicle/MultiVehicleManager.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
* Command ack timeout based on normal/high latency link (2 minute timeout for high latency)
* Correctly update ack timeout and high latency bit at correct times
* Fix altitude values from HIGH_LATENCY2. Absolute altitude will display correctly. Relative altitude is NaN'ed to get good display of no value there.
Related to #6072
=> More work in high latency

src/QGC.cc
=> QGC: Solve problem with limitAngleToPMPId when angle is bigger than PI

src/MissionManager/PlanManager.cc, src/MissionManager/PlanManager.h
This is the result of 2 days debugging mission upload and download over a lossy link.
The way I debugged this was to filter out some of the mavlink mission messages on the firmware side.
For more information, please check the commit messages.
Tested with current PX4/Firmware master but also with https://github.com/PX4/Firmware/pull/8750.
=> Robustify mission upload/download

qgroundcontrol.pro, qgroundcontrol.qrc, src/MissionManager/CameraCalc.cc, src/MissionManager/CameraCalc.h, src/MissionManager/CorridorScan.SettingsGroup.json, src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/CorridorScanComplexItem.h, src/MissionManager/CorridorScanComplexItemTest.cc, src/MissionManager/TransectStyle.SettingsGroup.json, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h, src/PlanView/CorridorScanEditor.qml, src/PlanView/CorridorScanMapVisual.qml
This pulls out the common parts of Survey and CorridorScan complex items into a base class which supports any horizontal surface transect flight style survey.
This in turns adds support to Corridor Scan for:
* Absolute altitude surveys (manual camera only)
* Turnaround support
* Rotate entry point
* Full stats
Related to #5695
=> New TransectStyleComplexItem base class

src/VehicleSetup/JoystickConfig.qml, src/VehicleSetup/JoystickConfigController.cc, src/VehicleSetup/JoystickConfigController.h
This makes it so that joystick deadband for each axis can be adjusted by clicking on the corresponding axis on the right side of the screen and dragging vertically. I have also added a short explanation of the deadband setting process which will appear below the deadband checkbox when it is enabled.
While the current method of setting works pretty well I've found that it often times doesn't end up quite right. This will make it easy to adjust the settings without going through the whole calibration process again.
=> Clickable deadzone

src/QmlControls/OfflineMapButton.qml, src/QtLocationPlugin/QMLControl/OfflineMap.qml
On mobile devices, if you have enough map tile sets that you need to scroll, you could end up with multiple buttons in selected state. It was a combination of lack of exclusive group and hover state management, which is not applicable to mobile/touch devices.
I've also made the buttons slightly larger for mobile devices.
=> Fix multiple selected state for offline maps buttons.

src/MissionManager/MissionController.cc, src/MissionManager/SurveyMissionItem.h, src/QGC.cc, src/Terrain.cc, src/Terrain.h, src/comm/UDPLink.cc, src/comm/UDPLink.h
The UDP link keeps a list of every host that sends a message and when replying on that link, it sends all messages to every host it received messages from (the client list).
The problem was that up to now, the list was a map (`host["address"] = port`). That meant if a vehicle had a component that sends messages from a different port, it would replace the port on the existing host (in the map). When QGC would sent any message to the vehicle, it would only get sent to the port of whichever component sent a message last.
This fix replaces the map with an actual list of address/port pairs. A vehicle with one or more components sending UDP messages from different ports will all be added to the "client list" and when QGC sends a message, it now gets sent to all components within a same address …
=> UDP Change

src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/FirmwarePlugin/PX4/px4_custom_mode.h, src/Vehicle/Vehicle.cc, src/comm/MockLink.cc, src/comm/MockLink.h
* Flight mode now works
* Changed to new FLAGS
**Important note for PX4 firmware**
Although PX4 only uses 16 bits for custom_mode flags. They are in the high 16 bits of the 32 bit custom_mode value of HEARTBEAT. This means that you cannot directly copy between HEARTBEAT.custom_mode and HIGH_LATENCY2.custom_mode and expect it to work. In order to do this I'm using the following structure which needs to be matched on the PX4 implementation of HIGH_LATENCY2.custom_mode when sending the message. Or in other words something like HIGH_LATENCY2.custom_mode = cm.custom_mode_hl.
```
union px4_custom_mode {
struct {
uint16_t reserved;
uint8_t main_mode;
uint8_t sub_mode;
};
struct {
uint16_t reserved_hl;
uint16_t custom_mode_hl;
};
uint32_t data;
float data_float;
};
```
=> Support remainder of HIGH_LATENCY2 fields

src/FlightMap/Widgets/CameraPageWidget.qml, src/QmlControls/QGCSlider.qml
Added a few things to the camera control:
* Time lapse mode (allows to switch between single and time lapse)
* Camera free storage space left
* Shutter counter (Photo Mode) / Running time (Video Mode)
Yes, basic camera support is now in Gazebo :P
=> Camera Control

src/Vehicle/Vehicle.cc
* Also handles correct prioritization of high latency links
Replacement for #4564.
@acfloria Can you take a look at this. I believe this fixes the leaking shared pointer. I can now disconnect two links on the same vehicle. It also makes the code way more understandable. The previous code was making my head hurt.
=> Fix bugs in updating priority link

src/FlightDisplay/GuidedActionConfirm.qml, src/FlightDisplay/GuidedActionsController.qml
This prevents incorrect confirmation slider to display for very short periods of time.
=> Add delay to guided commands to catch up with multiple state changes

src/comm/LinkConfiguration.cc, src/comm/LinkConfiguration.h, src/comm/LinkInterface.cc, src/comm/SerialLink.h, src/comm/TCPLink.h, src/comm/UDPLink.h, src/ui/preferences/SerialSettings.qml, src/ui/preferences/TcpSettings.qml, src/ui/preferences/UdpSettings.qml
- Add a highLatency variable to the LinkConfiguration and set the variable in the LinkInterface accordingly.
- Wenn manually connecting a link there is now a checkbox for UDP, TCP, and serial links to specify if the new link is a high latency link.
=> Add highLatency property to LinkConfiguration

src/Joystick/Joystick.cc, src/Joystick/Joystick.h, src/VehicleSetup/JoystickConfig.qml, src/VehicleSetup/JoystickConfigController.cc
The current Joystick implementation uses a tristate enumerator to indicate the calibration state of the joystick. However it seems that the state is never set to CalibrationModeOff except sometimes when the Joystick is first plugged in. This makes the use of this tristate enumerator confusing and results in a situation where disabling the joystick not only stops sending out ManualControl packets but also stops processing input from the joystick all together.
This pull request replaces the tri-state enumerator with two boolean values. One to indicate whether the joystick is currently being calibrated and another to indicate whether the joystick should be transmitting ManualControl packets. This allows the user to monitor the value of each joystick axis in QGroundControl even when joystick …
=> Joystick axes can now be monitored even when joystick control is disabled

src/MissionManager/QGCMapPolygonVisuals.qml
Don changed something with the file picker on mobile (to work around some Android issues). In the process, I think he forgot to update the call to the file picker from when loading KML files (on mobile). It was not defining the file extension to look for. Or it wasn't using the method expected by QGCFileDialog.
@DonLakeFlyer, the call was specifying `nameFilters` but the dialog was only evaluating `fileExtension`. You might want to take a closer look and see what else may be calling this with the wrong property.
=> Missing file extension for QGCFileDialog when loading KML files.

src/AnalyzeView/LogDownloadController.cc
For mobile, save log downloads next to where everything else is saved instead of straight into the home directory (which is anybody's guess when it comes to mobile platforms).
=> Mobile Log Download

src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/FlightDisplayViewWidgets.qml, src/api/QGCOptions.h
Allow a plugin to define a left placement for its custom flight widget.
When placed on the left, the action tool strip is placed on the right side.
=> Flight Widget

QGCExternalLibs.pri, qgroundcontrol.pro
I propose to add this small change to the qgroundcontrol project file in order to allow setting a different MAVLINK dialect in user_config.pri by adding a line ```MAVLINK_CONF = dialect```
Otherwise, it either needs to be set as a qmake argument (might get lost when setting up qt project from scratch), or hard-coded into QGCExternalLibs.pri, which might cause merge conflicts at some point.
=> Allow setting MAVLINK dialect in user_config.pri

src/FactSystem/ParameterManager.cc, src/FactSystem/ParameterManager.h
Used to debug cache CRC misses. Turn on the logging category and this will happen:
* A popup will show when CRC cache misses
* Debug output will tell you why
* values differ from cache to vehicle
* Cache has param which vehicle does not (or vice versa)
=> Add ParameterManagerDebugCacheFailureLog support

src/VehicleSetup/FirmwareUpgrade.qml, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h
* Custom, single firmware upgrades were fixed to "stable", even if the user selected "custom".
* The code, when selecting the firmware type was using the combo box model index instead of the actual type defined by the list model. This would only work for when updating the standard flight stack. If you were trying to flash a custom firmware for "SingleFirmwareMode" (custom builds) or for PX4 Flow, the _index_ would point to _Beta_ instead.
@DonLakeFlyer, unrelated to this fix, while looking, I noticed this error:
`qrc:qml/FirmwareUpgrade.qml:127: ReferenceError: hideDialog is not defined`
It comes from here: https://github.com/mavlink/qgroundcontrol/blob/firmwareUpgrade/src/VehicleSetup/FirmwareUpgrade.qml#L127
I don't quite understand how these dialogs work and what this is trying to …
=> Firmware Upgrade Fixes

src/MissionManager/QGCMapPolygon.cc, src/MissionManager/QGCMapPolygon.h, src/MissionManager/SurveyMissionItem.cc, src/MissionManager/SurveyMissionItem.h, src/QmlControls/QmlObjectListModel.cc, src/QmlControls/QmlObjectListModel.h
* Fixed dog slow loading of complex KML
* Complicated concave KML loads for generating survey grids was causing bad transect generation
* Change survey grid generation such that the polygon is no longer converted to convex
* New transect intersection algorithm which works with convex polygons
Examples:
This .mov shows how it all work while dynamically changing the grid angle of a survey generated from a complex concave KML load:
https://s3-us-west-2.amazonaws.com/qgroundcontrol/DonLakeFlyer/ConvexGrid.mov
=> Convex survey support

src/MissionManager/MissionManager.h
Remove all wasn't clearing resume mission index. Causing Resume Mission slider to pop up at wrong times.
=> Clear resume mission index

src/Joystick/Joystick.cc, src/Joystick/Joystick.h, src/VehicleSetup/JoystickConfig.qml
Some digital joysticks have already this correction
Add habilit to add or remove circle correction
=> Joystick: Add circle correction option

src/JsonHelper.cc, src/JsonHelper.h, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/PlanMasterController.h, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItem.h, src/MissionManager/SimpleMissionItemTest.cc, src/MissionManager/SimpleMissionItemTest.h, src/MissionManager/VisualMissionItem.h, src/PlanView/PlanView.qml, src/PlanView/SimpleItemEditor.qml, src/Terrain.cc
The above example shows a plan which was done with all waypoints 20 meters above a varied terrain. You can see this as the consistent delta from the terrain bar for waypoints 2-4 at the bottom of the screen.
* Simple mission items can now specify an altitude to be above terrain
* Altitude mode is specified by a dropdown which has the options: Alt (rel), AMSL, Above Terrain
* If you select Above Terrain the altitude you specify is the height above terrain
* Creating/Updating plans which use Above Terrain altitude mode require an internet connection to communicate with the terrain server
* Once the plan is saved you no longer need an internet connection
* Below the Altitude field you will see the actual AMSL altitude for the item
* Until the terrain query returns Actual AMSL Alt will show …
=> Simple mission terrain support

src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/CorridorScanComplexItem.h, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h, src/MissionManager/TransectStyleComplexItemTest.cc, src/MissionManager/TransectStyleComplexItemTest.h
How complex items work now:
* Only the meta data is stored in the plan file. The actual mission items are not.
* This means that when a complex item is loaded from a plan file it must regenerate the actual mission items from the meta data.
This is a problem because:
* If the algorithm for item generation changes from release to release the complex item may generate a mision which is slightly different from when it was created.
* If the complex item contains terrain references then it would need internet access to re-generate the mission items. This would not work if you are trying to load a plan onto a vehicle at the field with no internet access.
The solution:
* Store the generated mission data in the plan file as well as the meta data.
* When you load a plan with a complex item, the …
=> Corridor Scan: Store/Load generated items from Plan file

src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/CorridorScanComplexItem.h, src/MissionManager/CorridorScanComplexItemTest.cc, src/MissionManager/MissionController.cc, src/MissionManager/TransectStyle.SettingsGroup.json, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h, src/PlanView/CorridorScanEditor.qml, src/Terrain/TerrainQuery.cc, src/Terrain/TerrainQuery.h
* Terrain follow checkbox is live
* The various terrain follow settings Tolerance, ... are NYI
* Current implemenation only adjusts existing waypoints for terrain heights. It does not add additional waypoints in between yet.
The end result looks like this. A little hard to see, but you can see all points adjusted for 10m over terrain. If you look closely you can also see why just this is inadequate where the one transect goes through terrain:
Related to #6204
=> Corridor Scan initial terrain support

src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/VisualMissionItem.cc, src/MissionManager/VisualMissionItem.h, src/Terrain/TerrainQuery.cc, src/Terrain/TerrainQuery.h
This restructures the terrain query code such that all queries go through a TerrainQueryInterface abstract base class definition. This way the actual terrain query mechanism can be coded without the upper level client code changes affecting it. I have implemented the AirMap version. Then the offline code just needs to implement another version of this interface and change the code in the three places that instantiates TerrainAirMapQuery to the offline implementation. Should be fairly straightforward.
```
/// Base class for offline/online terrain queries
class TerrainQueryInterface : public QObject
{
Q_OBJECT
public:
TerrainQueryInterface(QObject* parent) : QObject(parent) { }
/// Request terrain heights for specified coodinates.
/// Signals: coordinateHeights when data is available …
```
=> Restructure for TerrainQueryInterface abstract base class

src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h, src/comm/MockLink.cc
* Tolerence based terrain follow generation is working now. 
* Next up: Terrain waypoints need to be adjust for max climb/descent rates
* Screenshots from extreme example of 10m above terrain with 5m tolerance.
Corridor Scan:
Loaded back from vehicle so you can see all the generated points:
KML:
Related to #6204
=> Corridor Scan: Tolerance based terrain follow

README.md, src/VideoStreaming/README.md, src/VideoStreaming/VideoStreaming.pri
Changes in latest Ubuntu 16.04 were causing them to fail.
@barzanisar When you created #6166 was there a reason you didn't update the instructions to match what you found to work in #6165?
@dogmaphobic Can you take a look.
=> Update gstreamer Linux install instructions

src/FlightDisplay/FlightDisplayViewWidgets.qml
We don't want average users to disable the arming check. If the problem is trigger, it is generally because there is a problem so the check shouldn't be advice to be disable.
=> FlightDisplay : Remove sentence about disabling arming check

src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml, src/AutoPilotPlugins/PX4/SensorsSetup.qml
Previous code was broken due to no type coercion from int to bool. Without it, possible breaks due to meta data changes.
=> Allow type coercion for FW_ARSP_MODE param

src/AutoPilotPlugins/PX4/PowerComponent.h
This should fix the OSX build failing on Jenkins.
=> PX4 PowerComponent add missing override

src/AutoPilotPlugins/PX4/PowerComponent.h
Reverts mavlink/qgroundcontrol#6280
This was already fixed in pulls that were sitting in the queue. Easier to revert this than fix the merge conflicts in multiple pulls. Ends up doing the same thing.
=> Revert "PX4 PowerComponent add missing override"

qgroundcontrol.qrc, src/AutoPilotPlugins/Common/SetupPage.qml, src/AutoPilotPlugins/PX4/PX4TuningComponent.h, src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml, src/Vehicle/SetpointFact.json, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/Vehicle/VehicleFact.json
This is a pretty major working in progress from a user model standpoint. Mostly trying thing out at this point. Here are the possibly non-obvious things:
* You get to it from Tuning and then check Advanced
* When the page loads it saves the parameter values for the current tuning set internally. The idea is as you futz with them you have an "oh shit" button to get you back to what are hopefully good values by clicking the Reset button.
* As you adjust and get better values you can save them as new reset values by clicking the Save Values button.
* The +/- buttons increment the values by the amount specified in the Increment/Decrement % combo box. This way you can start by futzing with the 15% changes and then as you fine tune you can drop to 10% or 5% increments.
* You can start/stop and …
=> PX4 PID tuning support

src/Joystick/Joystick.cc, src/Joystick/Joystick.h, src/Vehicle/Vehicle.cc, src/VehicleSetup/JoystickConfig.qml
This fixes issue #6264 which was caused in PR #6117.
This pull request removes the `outputEnabled` member of the `joystick` class as it serves a reduntant function to the `joystickEnabled` member of the `vehicle` class.
It also changes the `vehicle` class to separate the enabling/disabling of the joystick from the starting/stopping of the thread that polls the joystick. This way we can still monitor the joystick even when it is disabled.
=> Fix joystick activation

src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
Fix #5436.
This needs some testing and review, but appears to do the trick. I have one issue in that dropping frames or blocking on a pad probe in the recording branch, also appears to drop/block in the live stream branch. Though, from everything I have read, they should be independent. I must be missing something. The result is that when recording starts, the live stream stops until the next keyframe arrives, but only the recording branch should be waiting for the keyframe. @NaterGator @dogmaphobic, any clue?
=> Correct video file timestamping issues

src/Vehicle/MAVLinkLogManager.cc, src/Vehicle/MAVLinkLogManager.h
In response to #6289 
QGC now keeps a flag telling it logging has been denied. If set, it won't try to start (ulog) streaming again.
Note that I can't test this as I don't have anything (working) that "denies" logs.
=> Don't try to start logging if it's been denied.

src/AnalyzeView/GeoTagController.cc, src/AnalyzeView/ULogParser.cc
* Fix ulog file format parsing (fix for #6234)
* Fix crash when image count is less than trigger image indices
@dogmaphobic @birchera Can you guys look at this? I don't really know much about the log file format. But the logic for an A tag defining the camera_trigger id follow by the actual data seemed wrong. And this change makes it work as far as I can tell.
=> GeoTag Fixes

src/Joystick/Joystick.cc
=> Joystick: Make circle correction on by default

src/Joystick/Joystick.cc, src/Joystick/Joystick.h, src/VehicleSetup/JoystickConfig.qml
In response to #6297
Added a configurable joystick message rate (frequency). The default is as it's always been (25Hz). I've arbitrarily limited it to a range of 0.25Hz to 100Hz for sanity's sake.
P.S. This UI is in desperate need of some TLC.
=> Allow defining Joystick message frequency

src/FlightDisplay/GuidedActionsController.qml
The Pause command was only half useful as an "Oh shit!" button. To make it more useful it now allows you to changed altitude at the same time. This way you could say duck over or under something that was coming at you while flying a mission.
=> Allow altitude change with Pause command

src/FirmwarePlugin/PX4/MavCmdInfoCommon.json, src/MissionManager/CameraSection.cc, src/MissionManager/CameraSection.h, src/MissionManager/CameraSectionTest.cc, src/MissionManager/MavCmdInfoCommon.json
When setting up a mission using video capture (as opposed to image capture), tell the autopilot to send capture updates (every 5 seconds). This will tell the UI to update the current status as the video "recording" started by an autopilot command instead of an user command.
=> Set video capture status for missions

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/FirmwarePlugin/PX4/px4_custom_mode.h
Corresponding PX4 PR: https://github.com/PX4/Firmware/pull/9261.
The question is: should this mode be settable by the user? Regular `LAND` mode can't be set as a mode, only by a button on the left panel.
=> Add PX4 Precision Land flight mode

src/QmlControls/EditPositionDialog.qml, src/QmlControls/EditPositionDialogController.cc, src/QmlControls/EditPositionDialogController.h
Allows you to change the position of a mission item to the current vehicle position
=> Plan/Edit Position: Change position to vehicle position

qgroundcontrol.qrc, src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentVTOL.qml, src/FactSystem/Fact.cc, src/FactSystem/Fact.h, src/FactSystem/FactControls/FactValueSlider.qml, src/FactSystem/FactControls/qmldir, src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/QmlControls/FactSliderPanel.qml
Currently only in use on the px4 tuning page. The old ui just had standard sliders here. If you actually tried to use them on mobile outside they were pretty much useless. Your finger is right over the slider so you can't really see if you are actually sliding it, especially for small incrememts. You also had no idea how much you were sliding since there were no values. So trying to tune hover throttle say was a royal PITA.
The new UI shows values. You can click on the values to left/right to adjust. You can flick the control left/right to get to more values.
This control is the starting point for replacing all value input ui in QGC.
Note: This image shows strange values for units of these properties. @dagar We had talked about cleaning up the tuning property meta data. Could you look at …
=> New FactValueSlider control

src/QGCApplication.cc, src/QGCApplication.h, src/QmlControls/AppMessages.cc, src/QmlControls/AppMessages.h, src/main.cc
```--log-output``` on the command line will log console otuput to CrashLogs\QGCConsole.log
More work to help with debugging crashes.
=> Allow logging console output to file from command line

src/comm/BluetoothLink.cc, src/comm/SerialLink.cc, src/comm/TCPLink.cc, src/comm/UDPLink.cc
In looking through Stable 3.3 android crash reports. There are quite a few in readBytes of various link types. These changes guard against possible null pointer references.
=> Link read/write: Better guarding against crashes

src/TerrainTile.cc
Fixing the problem when reading in incomplete terrain data.
If the bytearray does not contain all data, the isValid flag never gets set to true, which should prevent any related crashes.
=> Guard terrain tile from reading beyond the bytearray end

src/FactSystem/FactControls/FactCheckBox.qml
Also restore `checkedValue` and `uncheckedValue` properties, which are used by `APMCameraComponent.qml`
=> Fixed checked state logic 

src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/MissionManager/MissionSettingsItem.cc, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItem.h, src/MissionManager/SimpleMissionItemTest.cc, src/PlanView/SimpleItemEditor.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
* New **TerrF** radio for altitude mode. This supports MAV_FRAME_GLOBAL_TERRAIN_ALT.
* TerrF radio will only show up for firmwares which support it: currently ArduPilot only
* Also fixed height calculations for alt/terrain display when switching between alt modes
Fixes for #6342 and #6387
=> Mission Item: Mavlink MAV_FRAME_GLOBAL_TERRAIN_ALT support

src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/Vehicle/BatteryFact.json
This is some refactoring for readability, as well as a bugfix for temperature units to get the proper translator (checking toLower vs checking both toLower and raw string). There is one outstanding (preexisting) issue:
The units settings work fine for the Temperature category, but not battery.temperature. I do not see why, this should be determined by the json, and they specify the same units:
https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/BatteryFact.json#L35
https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/TemperatureFact.json#L7
=> UnitsSettings: rework/bugfix metadata translators setup

src/AutoPilotPlugins/APM/APMAirframeComponentSummary.qml, src/AutoPilotPlugins/APM/APMCameraComponentSummary.qml, src/AutoPilotPlugins/APM/APMFlightModesComponentSummary.qml, src/AutoPilotPlugins/APM/APMLightsComponentSummary.qml, src/AutoPilotPlugins/APM/APMPowerComponentSummary.qml, src/AutoPilotPlugins/APM/APMRadioComponentSummary.qml, src/AutoPilotPlugins/APM/APMSensorsComponentSummary.qml, src/AutoPilotPlugins/APM/APMSubFrameComponentSummary.qml, src/AutoPilotPlugins/Common/ESP8266ComponentSummary.qml, src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml, src/AutoPilotPlugins/PX4/CameraComponentSummary.qml, src/AutoPilotPlugins/PX4/FlightModesComponentSummary.qml, src/AutoPilotPlugins/PX4/PX4RadioComponentSummary.qml, src/AutoPilotPlugins/PX4/PowerComponentSummary.qml, src/AutoPilotPlugins/PX4/SafetyComponentSummary.qml, src/AutoPilotPlugins/PX4/SensorsComponentSummary.qml
Example with all value shown:
I also removed all of the ":"s from the summary labels. To better match the rest of the UI which doesn't use that model.
Fix for #6062
=> Safety summary: Rework to better match Safety Page

src/MissionManager/CameraSpec.cc, src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/CorridorScanComplexItem.h, src/MissionManager/MissionController.cc, src/MissionManager/SurveyComplexItem.cc, src/MissionManager/SurveyComplexItem.h, src/MissionManager/SurveyComplexItemTest.cc, src/MissionManager/SurveyComplexItemTest.h, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h, src/PlanView/CorridorScanEditor.qml, src/PlanView/SurveyItemEditor.qml, src/PlanView/SurveyMapVisual.qml
This is a massive change to the Survey complex item to convert it to the user same new transect generation  and camera calculation code as Corridor Scan (TransectStyleComplexItem, CameraSpec, CameraCalc). The most important thing this does for Survey is add Terrain support.
I can pretty much guarantee that I introduced bugs to Survey whether you are using terrain following or not. Most likely problem areas:
* Terrain generated surveys. Be careulf with using this to start. Verify by saving to KML. Also verify by round trippping through the vehicle and double checking generated waypoints.
* Loading old Survey files. This conversion also massively changes the Survery json file format. The good news is that it matches Corridor Scan and provides common objects for camera and grid information. …
=> Convert Survey complex item to use TransectStyleComplexItem

src/AutoPilotPlugins/PX4/SensorsComponentController.cc, src/AutoPilotPlugins/PX4/SensorsComponentController.h, src/AutoPilotPlugins/PX4/SensorsSetup.qml
This makes is easier to understand what happened on success.
Fix for #6333
=> Don't clear results for airspeed/level calibration

src/ui/toolbar/MainToolBar.qml
Fix for #5769. This was making me crazy as well so I finally did something about it:
* Only visible if using Outdoor theme
* Only visible while parameters are downloading
* You can click it to hide it if you want to move on to do something else.
=> Large parameter progress on outdoor theme

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h
Replacement for #6425.
* Fixes a bug in #6425 
* Handles possible errors coming back from connect. When we specifically know what are connected to a Solo show the error if a video start fails. When we are unsure of Solo connection don't show errors from video start, since these will popup when the vehicle is not a Solo.
=> ArduPilot: Start possible Solo video

README.md
Most of these instructions have now moved into the DevGuide, so this README can be simplified to point to key project resources.
This follows on from https://github.com/mavlink/qgc-dev-guide/pull/36
=> Simplify README with links to devguide

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
Related to #6364. FYI @philipoe 
The various bits from the mavlink SENSOR_STATUS message are now available from the Vehicle object in Qml using .sensorsPresentBits, .sensorsEnabledBits, .sensorsHealthBits. Including an enum for the bit values. So you can write code like this:
```
import QGroundControl.Vehicle 1.0
property bool magEnabled: _activeVehicle.sensorsEnabledBits & Vehicle.SysStatusSensor3dMag
```
Also Phillip: If you want I can make a set of unhealthy bits like there are on the c++ side, which is a combination of enabled & healthy if you want as well.
=> Vehicle. Expose sensor status to Qml

qgcresources.qrc, qgroundcontrol.qrc, resources/check.svg, src/FlightDisplay/CheckList.qml, src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/qmldir, src/QmlControls/DropPanel.qml, src/QmlControls/QGCCheckListItem.qml, src/QmlControls/QGroundControl.Controls.qmldir, src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/Vehicle/Vehicle.h, src/ui/preferences/GeneralSettings.qml
This PR adds automated preflight checklists. This was discussed in https://github.com/mavlink/qgroundcontrol/issues/4119 . I'll quickly copy and paste the main points here:
The GUI below is the current (default) setup for a fixed-wing vehicle. Directly after startup, not many tests run yet:
A bit further into startup for indoor and outdoor scheme with some automatic and some manual checks passed already (automatic battery check fails because i am running on USB):
- Designed to use as many automatic checks as possible. In cooperation with @dagar, we've been working on getting the [MAV_SYS_SENSOR_STATUS flags ](https://mavlink.io/en/messages/common.html#MAV_SYS_STATUS_SENSOR) in the [SYS_STATUS  message](https://mavlink.io/en/messages/common.html#SYS_STATUS) filled with something meaningful …
=> Automated preflight checklists

src/PlanView/MissionItemStatus.qml
The terrain bars in mission item status display at bottom of Plan will show full yellow while terrain data is downloading or missing. This does two things:
* The indicators switching from yellow to normal terrain value display provides a progress indicator for terrain download.
* If the indicators stay yellow they show missing data.
=> Show indicator for mission terrain data

src/Vehicle/Vehicle.cc
Not sure why it did that. But it cause takeoff to no work when using optical flow for guidance.
=> Don't go into Hold before takeoff

src/MissionManager/CameraCalc.cc
If a custom build overrode the default camera setting, the camera specs were not updated correctly to the new camera spec.
=> Update camera specs on creation

qgroundcontrol.qrc, src/FlightDisplay/PreFlightAHRSCheck.qml, src/FlightDisplay/PreFlightBatteryCheck.qml, src/FlightDisplay/PreFlightCheckList.qml, src/FlightDisplay/PreFlightRCCheck.qml, src/FlightDisplay/PreFlightSensorsCheck.qml, src/FlightDisplay/PreFlightSoundCheck.qml, src/FlightDisplay/qmldir
This makes them much easier to reuse. Other than the ability to define failureVoltage for the battery check this is just packaging changes. Functionality stays exactly the same.
=> Create standalone controls for PreFlight CheckList

src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/PreFlightAHRSCheck.qml, src/FlightDisplay/PreFlightBatteryCheck.qml, src/FlightDisplay/PreFlightCheckList.qml, src/FlightDisplay/PreFlightRCCheck.qml, src/FlightDisplay/PreFlightSensorsCheck.qml, src/FlightDisplay/PreFlightSoundCheck.qml, src/QmlControls/PreFlightCheckButton.qml
* New implementation makes it easier to implement check buttons
* Changed visuals such that they are readable outdoors on a tablet
* Checklist is only available when you have a vehicle connected
* Should be a mostly no-op functionality wise except for manual checks only support single step now.
Known work left:
* I've tested but I'm sure I still broke something. I'll be continuing on this right away. So I'll find anything as I go along.
* Move the color usage into QGCPalette
* Support double manual steps
=> Simplify PreFlightCheckButton implementation

src/AnalyzeView/LogDownloadPage.qml, src/AnalyzeView/MavlinkConsolePage.qml, src/AutoPilotPlugins/PX4/CameraComponent.qml, src/AutoPilotPlugins/PX4/PowerComponent.qml, src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/MultiVehicleList.qml, src/PlanView/PlanToolBar.qml, src/PlanView/SectionHeader.qml, src/PlanView/SurveyItemEditor.qml, src/QmlControls/QGCTextField.qml, src/VehicleSetup/SetupView.qml, src/ui/AppSettings.qml, src/ui/preferences/GeneralSettings.qml, src/ui/toolbar/MainToolBar.qml
There were several layout errors throughout the program that went unnoticed until I built it with Qt 5.11. 
In summary: Don't use `anchor` anything within a layout control.
@DonLakeFlyer I didn't test 5.10 but 5.11 is working fine on macOS, iOS, Android and Windows (I have not yet tested on Linux).
=> Cleanup layout issues throughout QGC

src/MissionManager/SurveyComplexItem.cc, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItemTest.cc, src/MissionManager/TransectStyleComplexItemTest.h, src/PlanView/CorridorScanEditor.qml, src/PlanView/SurveyItemEditor.qml
* When turning off Terrain Follow the item should change to Relative Altitude
* When going from a manual camera to a custom camera should change to Relative Altitude
* Added support for custom build hiding of Relative Altitude checkbox in Survey and Corridor Scan
* Wrote unit tests to verify all the above so it never breaks again
=> Transect alt mode fixes

src/Vehicle/MultiVehicleManager.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/VehicleSetup/FirmwareUpgrade.qml, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h, src/VehicleSetup/SetupView.qml, src/comm/LinkInterface.cc, src/comm/LinkInterface.h, src/comm/LinkManager.cc, src/comm/LinkManager.h, src/comm/SerialLink.cc, src/comm/SerialLink.h
* Support flashing either PX4 or ArduPilot firmware. Defatult firmware selection is based on previous default autopilot firmware setting.
* Change PX4 Flow detection be be based on board id. This works for more cases.
* Turn off Mission/Geo/Rally download when connected to Flow
Fix for #5212.
=> PX4 Optical Flow fixes

src/FactSystem/Fact.cc, src/FactSystem/SettingsFact.cc, src/FactSystem/SettingsFact.h, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/api/QGCCorePlugin.cc, src/api/QGCCorePlugin.h
The api for QGCCorePlugin::adjustSettingsMetaData which incorrect in that it only take the meta data as a parameter. In order to fully qualify which settings this is about you also need the settings group name. Without it there can be namespace collisions on the name which currently exist between Survey and Corridor Scan settings.
Note that this is a breaking change to an API for custom builds. Easy to deal with but all the less breaking.
=> Add settingsGroup qualifer to settings override

Jenkinsfile
Currently an overall pipeline agent is assigned to the whole build, essentially blocking the assigned slave from performing any build steps as the individual stages define the agent to use. The blocking prevents it from doing other jobs in the queue until the whole QGC build is done. This fixes that, and adds small formatting fixes.
The images below shows how slaves are blocked when there are other tasks to do in the build queue.
FYI @dagar
=> jenkins: agent fix

src/FlightMap/MapItems/MissionItemIndicatorDrag.qml, src/MissionManager/QGCMapPolygonVisuals.qml, src/MissionManager/QGCMapPolylineVisuals.qml, src/PlanView/CorridorScanEditor.qml
When editing a survey polygon, clicking on a vertex would delete that vertex. It was too easy to click/touch it by mistake. This changes it to a double click for deleting a vertex.
In addition:
For corridor scans, the same double click applies when you want to delete a vertex. When you single click however, you get the menu asking if you want to delete that particular vertex or load a KML file. Also, the "Delete Vertex" menu item only shows if there are more than 2 vertices.
Also fixed a layout/anchor issue within corridor scan.
=> Use a menu to delete a vertex

QGCSetup.pri
Linux seems to be working fine with Qt 5.11. This library was in the "copy list" but it doesn't exist in Qt 5.11. I'm not sure who added it in the first place and what was the reason behind it. It may require some investigation.
=> Remove unused (and non-existing) library

src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml, src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.3.6.xml, src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
Related to #6503.
This tracks the renames of these parameters:
```
remapV3_6["PSC_ACCZ_P"] =       QStringLiteral("ACCEL_Z_P");
remapV3_6["PSC_ACCZ_I"] =       QStringLiteral("ACCEL_Z_I");
```
It also supports both ```RC_FEEL_P``` on older firmwares and ```ATC_INPUT_TC``` on newer firmwares.
I'm no longer sure whether the way this page implements Roll/Pitch/Climb Sensitivity is valid. It seems odd. To describe:
Roll/Pitch Sensitivity Slider
* The slider position is initially set from ATC_RAT_RLL_P
* When the user changes the slider the ATC_RAT_RLL_P, ATC_RAT_RLL_P, ATC_RAT_PIT_P and ATC_RAT_PIT_I values are all set to the slider value.
Climb Sensitivity Slider
* The slider position is initially set from PSC_ACCZ_P
* When the user changes the slider the PSC_ACCZ_P value is set to the …
=> ArduCopter 3.6 tuning page fixes

src/FlightDisplay/FlightDisplayView.qml, src/ui/preferences/GeneralSettings.qml
@dogmaphobic I found these other two references to QtMultimedia which don't seem to be needed.
=> Remove QtMultimedia import when not needed

src/FlightDisplay/GuidedActionConfirm.qml, src/FlightDisplay/GuidedActionList.qml, src/FlightDisplay/GuidedActionsController.qml, src/PlanView/SimpleItemEditor.qml, src/QmlControls/SliderSwitch.qml, src/ui/MainWindowInner.qml
* Better pallete usage for Guided Actions confirm to make it usable outdoors.
* Emergency Stop now has different visuals from other actions in order to prevent accidental confirm. Fix for #6545.
* Remove visibility of terrain frame option unless mission already contains it. Since QGC does not yet support ArduPilot terrain tile send, this was too confusing to expose. Fix for #6553
* Changed application exit message when vehicles connected to "There are still active connections to vehicles. Are you sure you want to exit?". Fix for #6548.
=> Various fixes

src/FlightDisplay/FlightDisplayViewMap.qml
Was allow vehicle to go under toolstrip on left and instrument panel on right. Fix for #6508
=> Vehicle recenter takes into account correct viewport

src/QmlControls/QGCFileDialog.qml
On windows the translation of file urls for FileDialog.folder is broken. From looking a Qt bug reports it seems like this has been broken about a hundred time in each release and nobody in Qt land seems to care. We can work around this by always making the url fully qualified. Which works since currently all folders passed to QGCFileDialog are fully qualified.
=> QGCFileDialog: Specify fully qualified in folder url

src/comm/HeartbeatTimer.cc, src/comm/HeartbeatTimer.h, src/comm/LinkInterface.cc
Previously the first activeChanged signal got lost because it was not connected yet to the LinkInterface which resulted in a link incorrectly shown as inactive.
=> Split constructor of HeartbeatTimer up in two functions

qgroundcontrol.pro
=> qgroundcontrol: Use qtquickcompiler by default

src/QtLocationPlugin/QMLControl/OfflineMap.qml
* Export should always be enabled since you can export default tile set
* Fix Select All/None problem
=> Offline Maps: Import/Export fixes

src/comm/QGCXPlaneLink.cc
Quite a nice feature for realistic testing in my opinion. Tested with X-Plane 10.64 and current pixhawk master. Obviously, in X-Plane's plane maker you need to configure your aircraft model to support flaps.
=> HIL (X-Plane): Allow to control aircraft flaps in XPlane

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
In looking at #5832 realized the switch highlighting was pretty broken. I think threshold parameters showed up some time after this was implemented. Fixing the switch highlighting was pretty involved so for now I turned that off. Wihch is better than being wrong. I also noticed that a pile of switches were missing. Added them.
=> Fix flight mode switch setting

src/MissionManager/PlanMasterController.cc, src/MissionManager/PlanMasterController.h, src/PlanView/PlanView.qml, src/QmlControls/DropPanel.qml, src/QmlControls/ToolStrip.qml, src/api/QGCOptions.h
First stab at reworking the _Sync_ menu:
The _Sync_ menu within the Plan View tool strip is basically a regular _File_ menu. As such, let's call it what it is.
* Renamed _Sync_ to _File_
* Moved it to the top of the list as this is the standard for _File_ menus
* Renamed _Remove All_ to _New_ (and moved it to the top of the list as this is the standard)
* Renamed _Load_ to _Open_
* Added a _Save_ (current) and renamed the existing one to _Save As_ (to new file)
* Hide both _Download_ and _Upload_ buttons if you are not connected (offline)
* Disable the _New_ button if the plan is empty
* Disable save options if there is nothing to save
In addition, I've adjusted the width of the tool strip so long words such as _Waypoint_ or _Checklist_ would fit within it.
Blank mission and not connected …
=> Turn "Sync" menu into a proper "File" menu

src/QmlControls/ScreenTools.qml, src/api/QGCOptions.h
I bumped into a custom Android tablet (CrystalSky), which even though it has a high density display, it reports otherwise. At least Qt thinks that's the case. `Screen.devicePixelRatio` returns 1 instead of 2. The pixel density is also slightly off as they probably measured the entire width of the device instead of the screen area.
As there is no way to find this at runtime, and this happens to be a "custom" case, I've added an API where a plugin can override both the pixel ratio and pixel density.
While at it, I found that `minTouchPixels` was being computed without taking in consideration the pixel ratio. For a given size, it was computing the pixel count using density only:
`minTouchPixels = Math.round(minTouchMillimeters * Screen.pixelDensity)`
Where it should also take into account …
=> Allow plugin to override pixel ratio and density

src/comm/UDPLink.cc
This patch fixes a bug when UDP target hosts list was empty in connection edit screen. One had to add new host in order to display existing entries.
Here is a screenshot of the screen which I mean https://imgur.com/ajmqbfu
=> Update hosts list on UDP Configuration creation

src/FlightDisplay/FlightDisplayViewMap.qml
The code was not testing to see if there was a valid `instrumentWidget` before trying to access one of its properties. If it happens to be NULL, you would end up with a never ending stream of these:
```
qrc:///qml/QGroundControl/FlightDisplay/FlightDisplayViewMap.qml:104: TypeError: Cannot read property 'widgetPosition' of null
```
=> Skip custom instrument widget test if none exists.

src/MissionManager/FixedWingLandingComplexItem.cc
=> FW Landing Pattern: Use setLoiterCoordinate for correct triggering of terrain query

src/PlanView/FWLandingPatternMapVisual.qml
Fixes the ability to set landing point to be in the same place as an existing mission item
=> FW Landing Pattern: Z order for landing click is above map items

src/MissionManager/PlanManager.cc, src/MissionManager/PlanManager.h
QGC assumes that when it gets a mission ack with an error during an upload/download sequence that the entire transaction has errored out. That isn't the case with how ArduPilot sends MAV_MISSION_INVALID_SEQUENCE errors. It will sends this in the middle of the sequence and then continue the transaction. Since these can happen easily when dealing with noisy comm links that caused a problem of failed missions uploads. Specifically with vehicles like ht SkyViper which has an incredibly awful wifi connection with tons of packet loss. So for now I'm hacking in an ArduPilot specific change to deal with this.
Also in this pull is a bump in upload timeouts since the SkyViper is also dog slow when uploading missions and would hit the overall message timout quite often. I still does, but not as …
=> ArduPilot: Deal with seemingly incorrect protocol support of MAV_MISSION_INVALID_SEQUENCE

qgroundcontrol.pro
It increases build time considerably for no real benefit during development.
=> Disable QtQuick compiler for Debug builds

src/FactSystem/FactControls/FactTextField.qml, src/PlanView/SurveyItemEditor.qml
This is in addition to the existing text edit control. You can either enter a numeric value directly or use the slider.
=> Adding a slider to set the mission path angle

src/QmlControls/ParameterEditor.qml, src/QmlControls/ParameterEditorController.cc
If user doesn't specify a file extension .params is added as file extensions. This matches other file save code.
=> Set parameter file extension if needed

src/PlanView/PlanView.qml
If the vehicle type was fixed wing loading a KML file with a polygon would create two Survey items.
=> Survey: Fix double load from KML

src/FactSystem/FactControls/FactValueSlider.qml, src/QmlControls/ParameterEditorDialog.qml
For the ParameterEditorDialog which pops up from FactValueSlider the focus will not be set.
=> Work around android Qt bug where wrong virtual keyboard is displayed

src/MissionManager/QGCMapPolylineVisuals.qml
alow position edit in polyline。
in EditPositionDialog  
if use  coordinate = mapPolyline.path[menu._removeVertexIndex]
there will be bind loop  property
=> alow Polyline position edit

src/MissionManager/VisualMissionItem.cc, src/Terrain/TerrainQuery.cc, src/Terrain/TerrainQuery.h, src/TerrainTile.cc
Turn internal errors (elevation == -1) into failed query to prevent bogus elevation from reaching upper layers. Related to #6723
=> Terrain: Better error handing

src/QtLocationPlugin/QGCMapUrlEngine.h, src/TerrainTile.cc, src/TerrainTile.h
This prevents float<->double precision different from causing tile loads to fail. Previously lat/lon which was exactly at the edge of a tile would fail load.
Note: This change bumps to terrain tile format version thus invalidating all previously stored terrain tiles.
Related to #6723
=> Terrain Tiles: Persist header info as doubles

src/VehicleSetup/FirmwareImage.cc, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h, src/comm/QGCSerialPortInfo.cc, src/comm/USBBoardInfo.json
Note: Support for non-pixhawk family boards is NYI.
Related to #6760
=> ArduPilot: ChibiOS flash support for Pixhawk family boards

src/AutoPilotPlugins/PX4/SensorsSetup.qml
=> Compass Cal: Don't show compass orientations for fixed orientation vehicles.

src/AnalyzeView/ExifParser.cc
Change geotagging gpsAltRef type from string to uint8. This fixes: https://github.com/mavlink/qgroundcontrol/issues/6800
=> Change Geotagging gpsAltRef field type

src/QmlControls/ScreenTools.qml
The fixes in #6782 is not enough for Windows when using a "high DPI" display (aka 4k/5k monitors). The pixel ratio value returned by the system is only available on macOS and iOS. Pixel density however, seems to be a bit more reliable and I am using that instead.
This makes two assumptions:
* A "tablet" can't be larger than 300mm wide (The DJI CrystalSky for instance reports a huge resolution with a pixel ratio of 1. Its pixel density however is accurate enough.)
* A "huge monitor" is one greater than 27" instead of a fixed number of pixels.
=> Dealing with pixel density on Windows and iOS

src/MissionManager/MissionController.cc, src/MissionManager/PlanMasterController.cc, src/MissionManager/PlanMasterController.h, src/api/QGCCorePlugin.cc, src/api/QGCCorePlugin.h
Allow plugin to add its own keys to plan files.
When a plan is saved, a call is made to the plugin (if present) before and after the plan is saved. This allows the plugin to save its own entries into the plan file (before or after the plan is saved, allowing the plugin to modify preemptively and/or after the fact.)
The same is true for when a plan file is loaded.
=> Custom Plan Save/Load

ChangeLog.md, qgroundcontrol.qrc, src/FactSystem/Fact.cc, src/FactSystem/FactMetaData.cc, src/FlightDisplay/FlightDisplayViewWidgets.qml, src/Vehicle/EstimatorStatusFactGroup.json, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
These are now available to display in the instrument panel:
Final step is creating a custom estimator status instrument page.
=> Add Vehicle FactGroup for ESTIMATOR_STATUS values

ChangeLog.md, src/MissionManager/MissionItem.cc, src/MissionManager/MissionItem.h, src/MissionManager/MissionManagerTest.cc, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItemTest.cc
This could lead to missions being save with param7=0 but the ui shows a good altitude value.
Fixes #6823
=> SimpleMissionItem::setCoordinate was screwing up altitude/param7 syncronization

src/comm/USBBoardInfo.json
=> USBBoardInfo.json: add U-Blox F9P USB device

src/QmlControls/QmlObjectListModel.cc
Fixes https://github.com/mavlink/qgroundcontrol/issues/6770
I don't think it makes sense to insert the objects at location `i` (`i` stays constant,  `j`  is changed).
Note that  `insert` is called from `append` with `i == _objectList.count()`
=> [QmlObjectListModel] fix list insert

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/comm/MAVLinkProtocol.cc, src/comm/MAVLinkProtocol.h, src/comm/ProtocolInterface.h, src/ui/preferences/MavlinkSettings.qml
* Fixed the core MAVLink receiver. Among other things, it wasn't accounting for fragmented messages.
* Fixed code that monitors messages received (and lost)
* Added a section within the MAVLink panel to show the current status (for the current vehicle)
* Remove some old, unused exposed interfaces
This is an initial step in adding a way for the ground station to send message received updates (feedback) upstream (repeater/camera/autopilot/etc.)
The idea is to allow for data throttling if there are issues with the link. For instance, when using links such as WiFi, the further away the vehicle is, the lower the bandwidth. If the vehicle is aware of the link conditions, it will be able to throttle down bandwidth usage.
Something that was immediately obvious as a result of this is that when QGC …
=> MAVLink Status

src/QGCApplication.cc, src/QGCApplication.h
This will look for localization strings defined as resources. None exist yet. Once languages are added, they should be submitted into the `localization/` directory and added as a resource. For example:
```
<qresource prefix="/localization">
<file alias="qgc_de_DE.qm">localization/qgc_de_DE.qm</file>
<file alias="qgc_fr_FR.qm">localization/qgc_fr_FR.qm</file>
<file alias="qgc_zh_CN.qm">localization/qgc_zh_CN.qm</file>
</qresource>
```
This is in response to 
https://github.com/mavlink/qgroundcontrol/issues/3961#issuecomment-419467723. That work seems to have been done outside crowdin and must be added directly as a PR. It can be added to this branch directly or wait until it's merged.
=> Adding code to actually load localization strings.

ChangeLog.md, src/QGCApplication.cc, src/QGCApplication.h, src/api/QGCCorePlugin.cc, src/api/QGCCorePlugin.h
This is a dirt simple implementation but it gets the job done. If version is out of date it shows this:
For custom builds this feature defaults to off. Custom build can override to turn on. From QGCCorePlugin.h:
```
/// Returns the url to download the stable version check file. Return QString() to indicate no version check should be performed.
/// Default QGC mainline implemenentation returns QGC Stable file location. Default QGC custom build code returns QString().
/// Custom builds can override to turn on and provide their own location.
/// The contents of this file should be a single line in the form:
///     v3.4.4
/// This indicates the latest stable version number.
virtual QString stableVersionCheckFileUrl(void) const;
/// Returns the user visible url to show user where to download …
```
=> Stable desktop version check

src/ui/MAVLinkDecoder.cc
For context, see https://github.com/PX4/Firmware/issues/7770
This is the continuation of https://github.com/mavlink/qgroundcontrol/pull/5268, now that DEBUG_FLOAT_ARRAY was added to MAVLink (see https://github.com/mavlink/mavlink/pull/734).
This was tested with PX4 Firmware on this branch: https://github.com/PX4/Firmware/pull/10585
=> Add support for message DEBUG_FLOAT_ARRAY

QGCCommon.pri, libs/airmapd/include/airmap/traffic.h
* Disable the zillion warnings that come out from mavlink.h (macOS)
* Fix warning from error within the Airmap SDK. This is at best temporary until we get a properly functional SDK from Airmap. This was causing the Jenkins build to fail.
=> House keeping

ChangeLog.md, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/MissionControllerTest.cc
Takeoff items for ArduPilot have not coordinate associated with them. Which then confused the code which adds the planned home position if it is not already there.
Fix for #6840
=> ArduPilot: Fixed planned home position creation when not connected to vehicle

src/FactSystem/Fact.cc, src/FactSystem/Fact.h, src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/FactSystem/ParameterManager.cc, src/FirmwarePlugin/APM/APMParameterMetaData.cc, src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc, src/Settings/App.SettingsGroup.json, src/Settings/RTK.SettingsGroup.json, src/Settings/UnitsSettings.cc, src/ui/preferences/GeneralSettings.qml
* Works just like previous rebootRequired meta data support for vehicle reboot on param change
* Update various settings facts to use this
* Updated General Settings page to no longer mark restart required in text
* FactMetaData json loader support "qgcRebootRequired" field
=> Added support for qgcRebootRequired Fact meta data value.

ChangeLog.md, QGCCommon.pri, src/GPS/GPSManager.cc, src/GPS/GPSManager.h, src/GPS/GPSProvider.cc, src/GPS/GPSProvider.h, src/QGCApplication.cc, src/QGCApplication.h, src/QmlControls/ParameterEditorDialog.qml, src/QmlControls/QGroundControlQmlGlobal.cc, src/QmlControls/QGroundControlQmlGlobal.h, src/Settings/RTK.SettingsGroup.json, src/Settings/RTKSettings.cc, src/Settings/RTKSettings.h, src/Vehicle/GPSRTKFact.json, src/Vehicle/GPSRTKFactGroup.cc, src/Vehicle/GPSRTKFactGroup.h, src/ui/preferences/GeneralSettings.qml
This allows you to specify a fixed RTK base position and skip survey-in. If you have a valid survey-in "Save Current Base Position" will enable allowing you to copy the values from the survey-in to setttings.
Replacement for #6868. Related to #6621.
=> Add support for specifying fixed RTK base position

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/Vehicle/Vehicle.cc
This warns the user when the running firmware is not the latest stable.
The objective is to help the users keep an up-to-date firmware and reduce the incidence of problems due to incompatibility with older firmware versions.
=> Warn when not using latest stable version of Ardupilot.

src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml
Latest auto generated PX4 airframe metadata. Adds the X-UAV Mini Talon.
=> Update PX4 Firmware metadata Mon Oct 15 13:47:56 UTC 2018

src/AutoPilotPlugins/APM/APMSubFrameComponent.qml
This adds a new button to load the default parameters for the BlueROV2 Heavy
=> Add BlueROV2 heavy default parameter configuration

src/AutoPilotPlugins/Common/RadioComponentController.h, src/Camera/QGCCameraControl.h, src/MissionManager/CameraSection.h, src/QGCPalette.h, src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h, src/QtLocationPlugin/qtlocation/src/location/maps/qgeoserviceprovider.h, src/QtLocationPlugin/qtlocation/src/positioning/qgeoareamonitorsource.h, src/QtLocationPlugin/qtlocation/src/positioning/qgeopositioninfosource.h, src/QtLocationPlugin/qtlocation/src/positioning/qgeosatelliteinfosource.h, src/QtLocationPlugin/qtlocation/src/positioning/qgeoshape.h, src/Settings/UnitsSettings.h, src/VehicleSetup/FirmwareUpgradeController.h, src/api/QGCOptions.h, src/comm/LinkConfiguration.h
Q_ENUMS is deprecated and should not be used.
=> Move from Q_ENUMS to Q_ENUM

src/FactSystem/ParameterManager.cc
Warns when using the 3-arg `QObject::connect` that takes a lambda.
The recommendation is to use the 4-arg overload, which takes a context object
so that the lambda isn't executed when the context object is deleted.
=> ParameterManager: Use 3rd parameter in connect

src/QGCQFileDialog.cc, src/QtLocationPlugin/QGCMapUrlEngine.cpp, src/comm/BluetoothLink.cc, src/comm/TCPLink.cc, src/comm/UDPLink.cc
This removes unnecessary build of empty strings before copy.
=> Do not call QString(char*) to build empty string. 

src/Camera/QGCCameraControl.cc
Adding support for decimal places within XML definition file:
```
<parameter name="CAM_EMISS" type="float" min="0" max="1" default="0" step="0.05" decimalPlaces="2">
<description>Emissivity</description>
</parameter>
```
=> CP - Add support for decimal places

src/AutoPilotPlugins/APM/APMSafetyComponentSummary.qml, src/AutoPilotPlugins/APM/APMSensorsComponent.qml, src/VehicleSetup/FirmwareUpgradeController.cc
If COMPASS_AUTO_ROT is set to automatically set orientations don't show user orientation setting ui.
=> ArduPilot: Compass auto rot support

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
This disables the guided functions in QGC for sub, such as the "fly" toolbar.
=> Add ArduSub capabilities

CMakeLists.txt, qgroundcontrol.pro, src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc, src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h, src/AutoPilotPlugins/APM/APMMotorComponent.cc, src/AutoPilotPlugins/APM/APMMotorComponent.h, src/AutoPilotPlugins/APM/APMSubMotorComponent.qml, src/AutoPilotPlugins/Common/MotorComponent.h, src/FirmwarePlugin/APM/APMResources.qrc, src/QmlControls/APMSubMotorDisplay.qml, src/QmlControls/QGroundControl.Controls.qmldir, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
This adds a motor test interface for Sub. This interface is important to test individual motors to check if they are connected correctly, diagnose issues and reverse motor direction when necessary.
This is what it looks like:
=> Add motor test page for sub

src/QGCApplication.cc, src/comm/MAVLinkProtocol.cc, src/comm/MAVLinkProtocol.h, src/ui/preferences/GeneralSettings.qml
This fixes the crash on boot on Android (any mobile actually).
This would only happen the first time you were to run QGC on a device. 
Also getting rid of some build warnings while at it.
=> Android crash fix

src/comm/MAVLinkProtocol.cc, src/comm/MAVLinkProtocol.h
This fix more than 8k warnings messages.
https://api.travis-ci.org/v3/job/446387610/log.txt
=> MavLinkProtocol: Fix constructor warnings

src/comm/USBBoardInfo.json
This alows you to autoconnect to ChibiOS only boards.
=> Support new ArduPilot bootloader PID/VIDs

ChangeLog.md, qgroundcontrol.pro, src/MissionManager/CameraSection.cc, src/MissionManager/CameraSection.h, src/MissionManager/CameraSectionTest.cc, src/MissionManager/CameraSectionTest.h, src/MissionManager/FWLandingPattern.FactMetaData.json, src/MissionManager/FWLandingPatternTest.cc, src/MissionManager/FWLandingPatternTest.h, src/MissionManager/FixedWingLandingComplexItem.cc, src/MissionManager/FixedWingLandingComplexItem.h, src/MissionManager/SectionTest.cc, src/MissionManager/SectionTest.h, src/PlanView/FWLandingPatternEditor.qml, src/qgcunittest/UnitTest.cc, src/qgcunittest/UnitTest.h, src/qgcunittest/UnitTestList.cc
* Added Stop photo/video options. Default to on. This way if the vehicle RTLs from within a mission the camera will stop and you don't get crap images all the way to landing.
* Created unit test for FW Landing Pattern.
=> FW Landing Pattern: Support for stop photo/video. Plus item unit test.

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc, src/AutoPilotPlugins/APM/APMLightsComponent.qml, src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml, src/AutoPilotPlugins/APM/APMSafetyComponentSummarySub.qml, src/AutoPilotPlugins/APM/APMSubFrameComponent.qml, src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
This is to simplify cases where both major, minor, and patch versions had to be checked independently, which resulted in hard to read code
=> Create Helper functions to simplify version checking

src/FlightDisplay/VideoManager.cc, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
Moving the timeout to a (protected) variable so derived classes can access it.
Cleaning up some c++ warnings while at it.
=> RTSP UDP timeout

ChangeLog.md, src/MissionManager/Survey.SettingsGroup.json, src/MissionManager/SurveyComplexItem.cc, src/MissionManager/SurveyComplexItem.h, src/PlanView/SurveyItemEditor.qml, src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h
This PR adds a new mode for planning a survey which makes the planned flight path stay within concave polygons.
This is achieved by splitting the polygon into concave sub polygons and treating each as an independent area to be surveyed. Because this introduces additional turns, the flight time might be increased. Hence, the original (current) mode that does not support concave polygons is preserved to give user the option to chose the mode they like.
Original mode (stays default after this PR):
New mode that splits polygons:
The UI work for toggling between the modes was done by @dogmaphobic 
@dogmaphobic this is a cherrypick of the original branch on top of master
Fixes #5830 #5215
=> Feature: Concave Polygon Support by Splitting into Sub-Polygons

src/FirmwarePlugin/FirmwarePlugin.cc, src/QmlControls/PreFlightCheckGroup.qml, src/QmlControls/PreFlightCheckList.qml
It would leave the last group expanded. 
@Williangalvani In this pull I turned off version checks for everythiong other than stable firmware builds. It was popping up all over the place with various SITL testing. Reason being non stable builds tend to have version strangeness.
=> PreFlight: Reset not working correctly

src/VideoStreaming/VideoReceiver.cc
Set port to 554 if none is given.
=> If using RTSP and no port is defined, make sure to set default.

src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/GuidedActionsController.qml
The current Resume Mission / Battery Change sequence is confusing a lot of people for various reasons. The new sequence place Resume Mission in the Flight Plan complete dialog instead of using confirm sliders:
And then if you do rebuild the mission, afterwards you just get the regular Start Mission slider.
=> New Resume Mission sequence

src/VideoStreaming/VideoStreaming.cc, src/VideoStreaming/VideoStreaming.pri, src/VideoStreaming/gstqtvideosink/utils/glutils.h, src/VideoStreaming/iOS/gst_ios_init.h, src/VideoStreaming/iOS/gst_ios_init.m
It used to share the initialization with Android, which missed some things specific to iOS.
=> Properly initialize GStreamer on iOS

src/FlightDisplay/FlightDisplayView.qml, src/MissionManager/CameraCalc.cc
If connection is lost on active vehicle and there is the possibility of a Resume Mission you get this:
Which achieves two things:
* Even more hinting as to how to do a Resume Mission
* Prevents user from clicking on the Flight Plan complete buttons while there is not vehicle really there
If the connect comes back it will go back to normal Flight Plan Complete stuff. If the connection closes the Flight Plan Complete dialog closes as well.
=> Flight Plan Complete: Better handling of comm last sequence

src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h
If the board shows up using the ArduPilot port naming scheme then that will determine the board type as well as the firmware directly to load from. Otherwise it falls back to the board id detection mechanism.
This pull also changes the order of the ArduPilot firmware list to show ChibiOS build first.
=> Flash: Add support for board/firmware detection using ArduPilot port naming

src/FlightDisplay/FlightDisplayViewUVC.qml, src/Settings/VideoSettings.cc
* Check the proper place to see if a saved video source is no longer available.
I was looking in the wrong place and the video source was being reset on each boot. 
* Clip video rectangle so when aspect ratio is adjusted, the image is not larger than the containing (window) rectagle.
This for when the video is within the PIP window (main view is map).
=> UVC Video Work

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h
APM uses 0-255 to indicate RSSI while QGC expects a range of 0-100 (%). QGC also expects 255 to indicate the lack of RSSI altogether but this is not available on APM.
I have no way to test this so it would help if people gave a closer look.
Fixes #7013
=> Handle mismatched range for RSSI values.

src/FactSystem/ParameterManager.cc, src/FactSystem/ParameterManager.h
I believe this is the fix for #7046 and #7032. The timeframe of that code change looks right from a standpoint of when Android crashes started popping up.
=> Initialization of Fact prior to Qt init causes crash.

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
Reverts mavlink/qgroundcontrol #7017. Needs a different change.
=> Revert "ArduPilot: Don't starts streams from QGC side. Assume firmware side does the right thing"

.travis.yml
Fixes #7032. Hoping this will fix the crash. I can repro crash now using pre-built daily build.
=> Android: Switch to sdk 25

src/FlightDisplay/FlightDisplayViewMap.qml, src/MissionManager/QGCMapCircleVisuals.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
Example above shows a vehicle which is partially through it's first orbit. Still would like an indicator in the center to say this is an orbit but that will come later. This is at least enough to test telemetry working.
* Orbit circle is drawn on map from orbit telemetry values
* Orbit circle will go away after 3 seconds of no orbit telemetry
Related to https://github.com/PX4/Firmware/pull/10989
=> Show Orbit telemetry on map

src/Vehicle/Vehicle.cc
Since video is required to control a sub, this sets the video to UDP when a Sub vehicle connects if the video is disabled.
=> Set videoSource to UDP if connected to an ArduSub vehicle and video is disabled.

src/FlightDisplay/GuidedActionsController.qml, src/Vehicle/Vehicle.cc
* Orbit was always sending negative values for radius no matter what orientation set. Related to #7066
* Fixes #7072
=> Fix Orbit rotation as passed to vehicle

src/MissionManager/MissionController.cc
Bug:
* Plan a mission while not connected to a vehicle
* Don't save the Plan so dirty bit is set
* Connect to vehicle
* Dirty bit gets cleared incorrectly
=> Plane: Fix handling of dirty bit when home position changes from vehicle side

src/Joystick/JoystickAndroid.cc
When connecting these (such as the Ipega BT gamepads) and trying to calibrate, a single stick would end up moving two channels simultaneously.
=> Some Android joysticks have axis mapped to multiple channels.

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/FirmwarePlugin/PX4/px4_custom_mode.h, src/FlightDisplay/FlightDisplayViewMap.qml
I've changed the px4 flight mode header according to what I think will be done here: https://github.com/PX4/Firmware/pull/10989#issuecomment-445849668. If that ends up being wrong I will adjust before I merge this.
=> Orbit: Show center point telemetry and flight mode

src/FactSystem/ParameterManager.cc, src/FactSystem/ParameterManager.h
Logging was not showing component id in some important places. Related to #7049
=> ParameterManager: Fix cases of _logVehiclePrefix usage with missing componentId

src/ViewWidgets/CustomCommandWidget.qml
The Url in custom command widget has been moved to
https://docs.qgroundcontrol.com/en/app_menu/custom_command_widget.html
---
name: Fix Bug
about: The url in CustomCommandWidget.qml is invalid
---
Previously it is pointed to
https://dev.qgroundcontrol.com/en/tools/custom_command_widget.html
**To Reproduce**
Steps to reproduce the behavior:
1. Click Menu Widget
2. Click Custom Commands
3. Click select qml file
4. Click Reset.
And there you go. Invalid link, pointed to :
https://dev.qgroundcontrol.com/en/tools/custom_command_widget.html
**Expected behavior**
Show this link https://docs.qgroundcontrol.com/en/app_menu/custom_command_widget.html instead.
Phew, it's just a small fix. I hope it described enough 😄 .
=> CustomCommandWidget.qml:Fix URL

src/AutoPilotPlugins/Common/SetupPage.qml, src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
* ArduPilot: Assume non-autopilot components follow current PARAM_VALUE spec. Related to #7049
* PX4: Hack to allow Rover setup pages to display. Related to https://github.com/PX4/Firmware/issues/10969
=> PARAM_VALUE parsing changes, Rover hack fix

src/AutoPilotPlugins/Common/SetupPage.qml, src/QGCApplication.cc, src/QGCApplication.h, src/VehicleSetup/FirmwareImage.cc, src/VehicleSetup/FirmwareImage.h
* Fix the fixf or #7094
* Add --clear-cache command line options. This will erase the parameter value cache for all vehicles as well as the parameter and airframe meta data cached files.
=> Rover isFlying check fix

src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/FlightDisplay/FlightDisplayViewMap.qml, src/FlightDisplay/GuidedActionConfirm.qml, src/FlightDisplay/GuidedActionsController.qml, src/QmlControls/SliderSwitch.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
* If you cancel the guided confirmation dialog the Orbit/Goto indicator will go away
* If you perform a GoTo and then after the vehicles changes away from the flight mode which performs the goto the GoTo Indicator will go away
About as good as it's going to get given the vehicle telemetry I have available to base things on.
Fixes for #6720
=> Better handling of guided map indicator show/hide

src/MissionManager/CameraCalc.FactMetaData.json, src/MissionManager/CameraCalc.cc
When you changed to manual camera it would set valueSetIsDistance to false instead of true. This would in turn cause a default Survey item when changed to a specific camera to have a really high GSD causing the survey to be flown way up in the air.
New/correct behavior keeps survey item specific as altitude even when you switch to camera. Which then sets a resonable GSD as well.
=> Camera Calc: Incorrectly setting valueSetIsDistance to false

src/FlightDisplay/VideoManager.cc, src/FlightDisplay/VideoManager.h, src/Settings/VideoSettings.cc, src/Settings/VideoSettings.h, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoStreaming.cc, src/ui/preferences/GeneralSettings.qml
More work on auto video stream discovery.
Updated the code so it now handles different stream types (originally it would only handle RTSP). The Stream Info message now tells QGC the type of stream it contains and QGC will build a proper pipeline to handle it.
In addition, I've added a new stream type. One which uses h.264 encapsulated with MPEG-TS over UDP.
=> Auto Stream Discovery

src/FlightDisplay/FlightDisplayView.qml, src/MissionManager/QGCMapCircle.Facts.json, src/PlanView/GeoFenceEditor.qml, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanView.qml, src/PlanView/RallyPointItemEditor.qml, src/PositionManager/PositionManager.cpp, src/QmlControls/QGCCheckBox.qml, src/QmlControls/QGCMouseArea.qml, src/QmlControls/QGCRadioButton.qml, src/QmlControls/ToolStrip.qml
Big pile of changes for better visuals/layout on Mobile. 
Largest obvious visual change is a major simplification of the radio button and checkbox code. On mobile the checkboxes are larger for better touch targets. This also increased the sise of the checkmark image inside to indicate checked. Which in turn looked like crap when blown up in size. Instead of fighting with it I simplified the check box visuals in a way which works well at any size:
The set of changes make mobile look much better and also lets QGC run much better on smaller screens.
=> Mobile visual cleanup

src/VideoStreaming/VideoReceiver.cc
This was causing a crash on exit on Android. The app is nullified before video streaming is shutdown.
=> Check if qgcApp() actually exists before using it.

src/Camera/QGCCameraControl.cc, src/Camera/QGCCameraControl.h, src/Camera/QGCCameraManager.cc, src/Camera/QGCCameraManager.h, src/FlightDisplay/FlightDisplayViewVideo.qml, src/FlightDisplay/VideoManager.cc, src/FlightDisplay/VideoManager.h, src/QGCApplication.cc, src/Settings/VideoSettings.cc, src/Settings/VideoSettings.h, src/ui/preferences/GeneralSettings.qml
Moved the video stream API into the camera API (as opposed to a stand alone API, which you could not query stream options and no easy way to associate a camera with a camera/vehicle).
QGC already supported the full camera API where each vehicle may expose one or more cameras. Now each camera may expose one or more video streams. The discovery and configuration is automatic. No need to go into General Settings and type URI, aspect ratio, etc. (though that is still supported for cameras/vehicles, which do not implement this API).
Documentation is already under way and can be found here: https://mavlink.io/en/services/camera.html
@DonLakeFlyer The Travis unit test is failing in `FactSystemTestGeneric` on Android (core dump). I don't know what could be causing that.
=> Camera and Video Streams

src/FactSystem/Fact.cc, src/FactSystem/Fact.h, src/QmlControls/ScreenTools.qml, src/ui/MainWindow.cc
Fix for #7144
The initiall setting of the font size was caused a QGC Reboot Required message to pop too early in the boot sequence.
=> Fix startup crash on initial font change signalling qgc reboot required

qgroundcontrol.qrc, src/FactSystem/FactControls/AltitudeFactTextField.qml, src/FactSystem/FactControls/qmldir, src/MissionManager/MissionController.cc, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItem.h, src/MissionManager/SimpleMissionItemTest.cc, src/MissionManager/SimpleMissionItemTest.h, src/PlanView/SimpleItemEditor.qml, src/QmlControls/QGroundControlQmlGlobal.h
This control supports the additional Rel, AMSL, Abv Terr, ... labels for altitude mode. This will then be used in the other places where altitudes are entered: Survey, Corridor Scan and so forth. Those changes will come later though. So for now this results in an internal change only. No user visible change.
=> Support for new AltitudeFactTextField

src/Camera/QGCCameraControl.cc, src/Taisync/TaisyncSettings.qml
* Disable network settings on Android and iOS as they use a different link type (USB).
* Skip video stream auto configure if using Taisync Video (it's inherently "auto configured")
=> Taisync Tweaks

qgroundcontrol.pro, src/GPS/GPSManager.cc, src/GPS/GPSProvider.cc, src/GPS/GPSProvider.h, src/GPS/definitions.h, src/comm/USBBoardInfo.json
Septentrio base station is recognized by QGC and configured to send RTCM RTK messages to the flight controller.
Tested on the actual hardware by https://github.com/bkueng
=> Support for Septentrio base station RTK

src/Joystick/Joystick.cc
Related to #4293.
@jaxxzer Does this affect you guys. Down Zero makes way more sense as default for fixed wing and multi-rotor.
=> Joystick: Default to ThrottleModeDownZero

QGCExternalLibs.pri
This is necessary to avoid problems with others Qt versions.
=> QGCExternalLibs: Test Qt version before adding AirMap

src/Camera/QGCCameraControl.cc, src/Camera/QGCCameraControl.h, src/Camera/QGCCameraManager.cc, src/Camera/QGCCameraManager.h
Expose common parameter names so derived classes can use them.
I've also changed the QMap used for handling camera connections. It went from:
```c++
QMap<int, CameraStruct*> _cameraInfoRequest;
```
To:
```c++
QMap<QString, CameraStruct*> _cameraInfoRequest;
```
The reason was that if you were to:
```c++
int compID = 100;
_cameraInfoRequest[compID] = new CameraStruct();
```
It would create a list with 101 items (and assign the pointer to the 101st element)
Now if you instead use:
```c++
QString compID = "100";
_cameraInfoRequest[compID] = new CameraStruct();
```
It properly creates one single entry in the QMap.
=> Expose Common (camera) Parameters

src/MissionManager/ComplexMissionItem.h, src/MissionManager/CorridorScanComplexItem.h, src/MissionManager/FixedWingLandingComplexItem.h, src/MissionManager/MissionSettingsItem.h, src/MissionManager/StructureScanComplexItem.h, src/MissionManager/SurveyComplexItem.cc, src/MissionManager/SurveyComplexItem.h, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItemTest.h
Plan time was incorrect when using Hover and Capture in Survey
=> Survey: Fix Survey additionalTimeDelay as it relates to hover and capture

src/KMLFileHelper.cc, src/MissionManager/QGCMapPolygon.cc, src/MissionManager/QGCMapPolygon.h, src/MissionManager/QGCMapPolygonVisuals.qml
QGC expects all polygons to have clockwise winding.
=> QGCMapPolygon: Preserve clockwise winding when adjusting vertices

src/Settings/AutoConnect.SettingsGroup.json
With clean settings, QGC is defaulting to lower-case "disabled", when it should be "Disabled" (an option in the combo box) instead.
Before:
After:
=> Fix default option for UDP NMEA Device

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.h, src/FlightMap/Widgets/ValuePageWidget.qml, src/Vehicle/Vehicle.cc
This enables vehicle-specific fact jsons to take care of things like displaying "depth" instead of altitude and "dive time" instead of "flight time".
Also added headingToGCS fact.
=> Allow custom fact json files for different vehicles

ChangeLog.md, src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc, src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h
If you created a new tile set and included elevation data the tile counts stored in the two separate tile sets would be the total tile count for both image and elevation tiles. This would cause the system to think download was incomplete if you left the offline maps page and went back to it.
The fix is to maintain the tile counts separately for image and elevation tile sets and to store the appropriate value for each in the database.
=> OfflineMaps: Fix tile set counts

Custom-Info.plist
I got an error when running a master build today due to the lack of this:
```
<key>NSCameraUsageDescription</key>
<string>QGC uses UVC camera devices for FPV</string>
```
It's there now...
=> Make Apple happy

ChangeLog.md, Custom-Info.plist, QGCCommon.pri, android.pri, android/AndroidManifest.xml, android/res/xml/device_filter.xml, android/src/org/mavlink/qgroundcontrol/QGCActivity.java, android/src/org/mavlink/qgroundcontrol/TaiSync.java, src/Camera/QGCCameraManager.cc, src/Camera/QGCCameraManager.h, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml, src/FlightMap/Widgets/ValuePageWidget.qml, src/Joystick/JoystickAndroid.cc, src/Joystick/JoystickAndroid.h, src/Joystick/JoystickManager.cc, src/Joystick/JoystickManager.h, src/MissionManager/MissionController.cc, src/MissionManager/SimpleMissionItem.cc, src/QmlControls/QGCTextField.qml, src/Vehicle/Vehicle.cc, src/VideoStreaming/README.md, src/VideoStreaming/VideoReceiver.cc
Bugfix: Joystick is not visible if connected after start of QGC
On Android the Joysticks are probed only at the start of QGC. If the Joystick is connected after QGC is started it never appears in the system.
Steps to reproduce the behavior:
Drone switched on
QGC is started and connected to the drone
Bluetooth joystick or gamepad is connected to the system
Joystick tab does not appear in configuration
Expected behavior:
Joystick should appear when it is available to the system regardles even after QGC is up and running
Fix:
Android joysticks are periodically checked and probed in the same was as SDL joysticks on other platforms.
=> PR android joystick improvement v2

CMakeLists.txt, src/Joystick/CMakeLists.txt
---
name: Fix building with Cmake
---
**Steps to fix building**
1. Remove -Werror compiler flag (not in qmake file and cause build to fail)
2. Correctly detect and link SDL2 on Linux
=> Fix cmake building

src/MissionManager/StructureScan.SettingsGroup.json, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/StructureScanComplexItem.h, src/PlanView/StructureScanEditor.qml
How structure scan works was causing confusion. Specifically the concept of layes when using known cameras as well as the altitude that the vehicle enters the structure scan at. In order to try to make that better:
* Include Layer count and Layer height in Stats
* Add option for "Start Scan From Top/Bottom" which is useful as an option by itself. But also I hope indicates a little better that the vehicle will enter the scan from either the top or bottom of the defined structure.
=> Structure Scan: Add support for Start From Top/Bottom, plus more helpful stats

QGCSetup.pri
Application will not link to versions of libicu other then version 56
**To Reproduce**
Steps to reproduce the behavior:
1. Remove icu version 56
2. Install another version of icu
3. Build..
4. Run.. oh wait, missing libicudata.so.56
**Expected behavior**
Should run with my system icu lib.
=> Use any libicu version

src/comm/LinkManager.cc
This prevents the crash. Related to #7225. The max number of vehicles supported by QGC is 7.
=> Use correct number of available channels

src/QGCApplication.cc, src/QmlControls/QGCCheckBox.qml
Make checkbox colors consistent with radio buttons (and other UI elements)
While at it, I've also added code to output the current locale out to console (to see why some people are getting Turkish localization)
`System reported locale: QLocale(English, Latin, United States) "en_US"`
=> Check box colors

src/Vehicle/Vehicle.cc
This could cause crashes if you were unlucky on say a Mission download timeout retry in between Vehicle delete phase1 and phase2.
=> Vehicle: Do not clear priority link if it is the last link

ChangeLog.md, qgroundcontrol.pro, qgroundcontrol.qrc, src/FactSystem/FactGroup.cc, src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/JsonHelper.cc, src/JsonHelper.h, src/QmlControls/QGroundControlQmlGlobal.cc, src/QmlControls/QGroundControlQmlGlobal.h, src/Settings/APMMavlinkStreamRate.SettingsGroup.json, src/Settings/APMMavlinkStreamRateSettings.cc, src/Settings/APMMavlinkStreamRateSettings.h, src/Settings/App.SettingsGroup.json, src/Settings/SettingsManager.cc, src/Settings/SettingsManager.h, src/ui/preferences/MavlinkSettings.qml
In Settings/Mavlink:
This pull also contains support to essentially create DEFINE macros for enumValues and enumStrings elements in FactMetaData json. This way you don't need to specify common settings over and over and over again. Here is an example usage snippet from this pull:
```
{
"QGC.MetaData.Defines": {
"StreamRateEnumStrings": "Controlled By Vehicle,0 hz,1 hz,2 hz,3 hz,4 hz,5 hz,6 hz,7 hz,8 hz,9 hz,10 hz,50 hz,100 hz",
"StreamRateEnumValues": "-1,0,1,2,3,4,5,6,7,8,9,10,50,100"
},
"QGC.MetaData.Facts": [
{
"name": "streamRateRawSensors",
"shortDescription": "Stream rate for MAVLink Raw Sensors telemetry stream.",
"type": "int32",
"enumStrings": "QGC.MetaData.Defines.StreamRateEnumStrings",
"enumValues": "QGC.MetaData.Defines.StreamRateEnumValues",
"defaultValue": 2
},
...
]
}
```
=> ArduPilot: Configurable stream rate support

src/FirmwarePlugin/FirmwarePlugin.cc
Revert the camera names to their original names to avoid messing up old plan files, which use the camera name string to match the camera to the plan.
=> Revert Camera Names

QGCExternalLibs.pri, qgroundcontrol.pro, src/Settings/SettingsManager.cc, src/Settings/SettingsManager.h
Excluding ArduPilot specific code for when ArduPilot is disabled.
@dagar This needs to be reflected in cmake as well.
=> Exclude ArduPilot code when not used

qgroundcontrol.pro
Adding a custom/customQGCInstaller.pri file will override installer steps in QGCInstaller.pri.
However, the QGCInstaller.pri can be imported in the custom one. In this way
a custom build can add pre and post installer steps.
=> Add support for custom installer steps

src/Taisync/TaisyncManager.cc
Taisync supports 14 channels not 13. Communication was tested in this newly available channel.
Fingers crossed ;-)
=> Taisync has 14 channels available

ChangeLog.md, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
In response to #7292 
Making the camera API available to all firmwares, not just PX4.
This could use some testing with Ardupilot as I don't have anything running it.
Closes #7292
=> Camera API for all firmware types

src/QGCApplication.cc, src/QGCApplication.h, src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/ui/preferences/GeneralSettings.qml
You can now select the localization of QGC. By default, it will try to use the locale given by the underlying OS.
=> Add a language selector to the General Settings

src/AutoPilotPlugins/PX4/AirframeComponentSummary.qml
Previously only the px4 version was displayed which will help identifying the custom firmware version while keeping track of the upstream version as well.
=> Display FW custom version in the summary page

src/Camera/QGCCameraControl.cc, src/Camera/QGCCameraControl.h, src/FlightDisplay/VideoManager.cc, src/FlightMap/Widgets/CameraPageWidget.qml
Adding support for multiple video streams. 
If a camera offers more than one video stream, you can now select the one to show.
=> Multiple Video Streams

.gitignore
These exclusions aren't needed as the build system enforces shadow builds. The rules were excluding necessary files.
Fixes #7334
=> Removing overzealous exclusions.

src/MissionManager/StructureScanComplexItem.cc
Bug fix:
When scanning a structure from the top the starting altitude shall be equal to the structure height.
=> StructureScanFix: Starting altitude

src/FirmwarePlugin/APM/MavCmdInfoCommon.json, src/FirmwarePlugin/APM/MavCmdInfoFixedWing.json, src/FirmwarePlugin/PX4/MavCmdInfoCommon.json, src/MissionManager/FixedWingLandingComplexItem.cc, src/MissionManager/MavCmdInfoCommon.json, src/PlanView/FWLandingPatternEditor.qml
Previous change to handle #6783 was not completely correct. This fixes that:
* PX4: Fixes handling back to spec
* ArduPilot
* Maintains multi-rotor heading defaulting to 0 instead of NaN
* Fixed wing now shows correct x-track options
* Fixed Wing Landing Pattern item does not show camera options and defaults them to off.
=> Better handling of NaN in LOITER_* commands

src/FactSystem/FactControls/AltitudeFactTextField.qml, src/PlanView/CameraCalc.qml, src/PlanView/CorridorScanEditor.qml, src/PlanView/StructureScanEditor.qml, src/PlanView/SurveyItemEditor.qml, src/QmlControls/QGCCheckBox.qml, src/QmlControls/QGCRadioButton.qml, src/QmlControls/QGCTextField.qml
Also:
* Slight reduction in space between graphic and text for Radio Button and Checkbox
* QGCTextField supports small font extraUnitsLabel
* AltitudeTextField uses new extraUnitsLabel to show altitude mode
=> Consistent Altitutude Mode labelling in all complex items

qgroundcontrol.pro, qgroundcontrol.qrc, src/Airmap/AirMapSettings.cc, src/QtLocationPlugin/QMLControl/OfflineMap.qml, src/Settings/APMMavlinkStreamRateSettings.cc, src/Settings/AppSettings.cc, src/Settings/AutoConnectSettings.cc, src/Settings/BrandImageSettings.cc, src/Settings/CMakeLists.txt, src/Settings/FlightMapSettings.cc, src/Settings/FlyViewSettings.cc, src/Settings/OfflineMaps.SettingsGroup.json, src/Settings/OfflineMapsSettings.cc, src/Settings/OfflineMapsSettings.h, src/Settings/PlanViewSettings.cc, src/Settings/RTKSettings.cc, src/Settings/SettingsGroup.cc, src/Settings/SettingsManager.cc, src/Settings/SettingsManager.h, src/Settings/UnitsSettings.cc, src/Settings/VideoSettings.cc
Converted these values to an OfflineMaps SettingsGroup. The settings themselves are for custom build override only and not exposed to the user.
=> Offline Maps: Allow custom build override of min/max zoom levels, max tile download

ChangeLog.md, src/MissionManager/CameraCalc.cc, src/MissionManager/CameraCalc.h, src/MissionManager/ComplexMissionItem.cc, src/MissionManager/ComplexMissionItem.h, src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/SurveyComplexItem.cc, src/MissionManager/SurveyComplexItem.h, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h, src/PlanView/CameraCalc.qml, src/PlanView/SurveyItemEditor.qml
This allows you to save settings for a Pattern item as a named reusable preset. So for example if you fly a lot of say NDVI surveys at the same altitude and overlap settings you can save that as a preset. Then you create a new survey for a new area, you just select that Preset and you are done setting up the Survey.
Althought the internal archiecture for this is set up to work with all pattern types it is only supported by Survey now. Once we work through the usability of this on Survey then I'll implement in other Patterns.
=> Pattern Preset support

src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml, src/QmlControls/FactSliderPanel.qml, src/QmlControls/PIDTuning.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
* QGC will increase stream rates on ATTITUDE and ATTITUDE_TARGET messages for usable graphs. If you are running with low bandwidth telemetry you may need to adjust the vehicle settings further to make bandwidth room for these faster rates.
* Add "Automatic Flight Mode Switching". If you try to tune a vehicle in Stabilize mode while trying to capture the charts with Start/Stop on the ui it can become quite a handful for one person. The concept here is you turn this mode on. Then for example in PX4 you start in Positionor or Hold mode so the vehicle is stable. When you click Start, the vehicle switches to Stabilized, you then twitch to a side to generate data in Stablized mode and when you click Stop the vehicle goes to Hold flight mode. That way it's isn't running off on you while you are …
=> Pid Tuning: Stream rate adjustment, Automatic flight mode switching

src/comm/LogReplayLink.cc, src/comm/LogReplayLink.h, src/ui/MainWindow.cc, src/ui/QGCMAVLinkLogPlayer.cc, src/ui/QGCMAVLinkLogPlayer.ui
A few changes to make Log Replay a little less crappy:
* The status bar takes up the full width of the window. Making the time slider larger.
* You can drag the time slider while playing back. It will pause and adjust time.
* While dragging time slider the actual time in the log updates.
Related to #7412
=> Log replay changes

src/VehicleSetup/Bootloader.h, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h, src/comm/USBBoardInfo.json
Rename NXPhlite to FMUK66 everywhere, as was already done in PX4 and the PX4 Bootloader.
Related:
mavlink/qgroundcontrol#7360
PX4/Bootloader#133
=> Rename NXPhlite to FMUK66

src/VehicleSetup/FirmwareUpgradeController.cc
Firmware urls for FMUK66 were not defined yet.
Related to mavlink/qgroundcontrol#7360
=> Add NXP FMUK66V3 firmware urls

src/Microhard/MicrohardManager.cc, src/Microhard/MicrohardManager.h, src/Microhard/MicrohardSettings.qml
Found out that ground and air unit IPs are not needed. Remote can send UDP packets to Microhard address 192.168.168.255:14550 and they're broadcasted and received by QGC listening on standard port.
=> PR Remove Microhard configuration for air and ground unit IPs as they're not needed.

qgroundcontrol.pro, qgroundcontrol.qrc, src/Settings/FirmwareUpgrade.SettingsGroup.json, src/Settings/FirmwareUpgradeSettings.cc, src/Settings/FirmwareUpgradeSettings.h, src/Settings/SettingsManager.cc, src/Settings/SettingsManager.h, src/Vehicle/Vehicle.cc, src/VehicleSetup/FirmwareUpgrade.qml, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h
The manifest of available firmwares is downloaded from the ArduPilot web site. This then gives you the list of available firmwares which can be flashed to the board.
The UI is reworked such that you can pick ChibiOS/NuttX and then vehicle type followed by the actual firmware.
If the board leads to a single firmware (like when the ArduPilot bootloader indicates specific board type) you get that specific firmware to flash:
If it is a generic board like an old Pixhawk then you have to pick the firmware you want:
I would consider this a bit of a WIP since I'm not still too happy with all the choices the user has to make in some cases (for example the old Pixhawk 2 case aboce). But I need to put some more though into that first to figure out what to do about it.
=> Firmware Upgrade: Use ArduPilot manifest to get firmware listings

src/Camera/QGCCameraManager.cc
In response to #7433 
Check for camera info when receiving heartbeats from camera component IDs only. 
The original code would send a camera info request to any component ID other than the autopilot itself. This was done as at the time, there was one single `MAV_COMP_ID_CAMERA` and vehicles with multiple cameras had to resort to arbitrary component IDs. Now that we have a set of 6 predefined component IDs, I'm limiting the search to those only.
In practicality it makes little difference. Components that don't support the message would simply ignore and QGC would stop asking for it. On the other hand, limiting to the predefined set of component IDs makes it less confusing.
Closes #7433
=> Camera info requests

src/VehicleSetup/JoystickConfig.qml
This changes the deadband adjustment from dragging vertically to dragging horizontally.
Fix #7214
=> Change joystick deadband adjustment to dragging horizontally

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h
Fix for #7431 (I hope)!
* Watch heartbeats which come through the system from components. If they come through with HEARTBEAT.autopilot == MAV_AUTOPILOT_ARDUPILOTMEGA then assume they are running ArduPilot code. If not, assume it is not ArduPilot code and they are coded conform to mavlink spec.
* Since the ESP8266 doesn't send heartbeats it need sto be hardcoded to confirming to mavlink spec. There was already code in for this, but it wasn't quite correct.
* If the component doesn't sent a heartbeat then it is assumes to be ArduPilot code (which it may or may not be). But there is apparently no way to handle this correctly.
=> Handle ArduPilot strangeness with respect to components and mavlink spec for params

src/VehicleSetup/FirmwareUpgrade.qml, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h, src/comm/QGCSerialPortInfo.cc, src/comm/QGCSerialPortInfo.h
The user does not have any feedback around how many devices are connected and what kind of device should be removed.
QGC also detects normal FTDIs and Arduinos as SiK radios.
**Expected behavior**
This PR add a human friendly message warning the user that multiple devices are connected and need to be removed before performing the firmware upgrade.
=> Warn user when multiple devices are connected while doing the firmware upgrade

src/Microhard/MicrohardSettings.qml
Microhard configuration panel contained password fields that showed passwords in full text.
This PR makes those fields hidden.
When echoMode is set to TextInput.Password also inputMethodHints is set automatically to Qt.ImhHiddenText.
=> Made Microhard password fields hidden

src/VehicleSetup/FirmwareUpgrade.qml
This had been done before but there were so many changes that it was easier to give up trying to merge and do it again.
=> Don't offer Ardupilot firmware if support for it is not available.

src/Joystick/JoystickAndroid.cc, src/Joystick/JoystickAndroid.h, src/main.cc
Bug report: #7445
The problem could not be reproduced on my devices but I found that the joystick native methods were not registered at the same point of time as the serial port native methods so it is very likely that they were not registered yet when this crash happens.
Solution registers joystick native methods from JNI_OnLoad - in the same way as serial port JNI methods.
=> Set Android Joystick native methods from JNI_OnLoad

android/src/org/mavlink/qgroundcontrol/QGCActivity.java
Bug reported in #7444
Caused by: java.lang.NullPointerException:
at org.mavlink.qgroundcontrol.QGCActivity.openAccessory (QGCActivity.java:674)
I could not reproduce it in my environment but few commits agot line 674 was 
Log.i(TAG, "openAccessory: " + usbAccessory.getSerial());
which means that usbAccessory was null when openAccessory was called.
This PR makes sure that usbAccessory is checked for null before being used.
=> Fix for java open accessory crash

src/Camera/QGCCameraControl.cc, src/Camera/QGCCameraControl.h, src/FlightDisplay/VideoManager.cc, src/FlightDisplay/VideoManager.h, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
- Add camera parameters for video stream bitrate, frames per second and encoding.
- When these parameters where changed from QGC, the video stream was not restarted properly and sometimes it was started twice
- If H265 encoding is used change pipeline so that H265 decode is used.
=> Restart video stream after change

src/QmlControls/QGCRadioButton.qml, src/QmlControls/ScreenTools.qml
CheckBox is not centralized correctly if the size of the outside and inside circle are even numbers.
old:
new:
=> Fix CheckBox centralization 

src/QGCApplication.cc
We have specific fonts for Korean, which were being loaded when the user selected "Korean" from the list of languages. However, when QGC was set to "System" locale, no test was done to see if System == Korean.
=> Load Korean fonts when needed

src/FlightDisplay/FlightDisplayViewVideo.qml, src/FlightMap/Widgets/CameraPageWidget.qml, src/FlightMap/Widgets/VideoPageWidget.qml, src/api/QGCCorePlugin.cc, src/api/QGCCorePlugin.h
If a camera supports the full camera API, including the video streaming API, both camera and video streaming and handled through one same interface. In this case, the "Video" widget is disabled as it becomes redundant.
=> Handle auto video stream

qgroundcontrol.pro, src/FlightDisplay/VideoManager.cc, src/FlightDisplay/VideoManager.h, src/VideoStreaming/CMakeLists.txt, src/VideoStreaming/SubtitleWriter.cc, src/VideoStreaming/SubtitleWriter.h, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
This patch allows QGC to record a data overlay while recording the video. This is implemented by producing an independent subtitle file for use with each video that is recorded to file.  The subtitle file is a text file in the [SubStation Alpha](https://en.wikipedia.org/wiki/SubStation_Alpha) format. This is supported by your usual media players, where you can control if the overlay is displayed on playback, or optionally combine the video and subtitle file and export a single video file with the subtitles 'burned in'.
This patch will close #7286. No additional UI elements or user configuration/options are introduced. The values that will be recorded are the same as those that are selected for display in the vehicle values widget (telemetry display). Telemetry values are sampled and …
=> Implement overlay on recorded videos by using subtitle files

src/MissionManager/RallyPointManager.cc
Frame is incorrect; altitudes used are relative.
=> MissionManager: correct frame on Rally mission items

qgroundcontrol.pro, qgroundcontrol.qrc, src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/FlightDisplayViewMap.qml, src/QGCApplication.cc, src/QmlControls/LogReplayStatusBar.qml, src/QmlControls/QGroundControl/Controls/qmldir, src/Settings/FlyView.SettingsGroup.json, src/Settings/FlyViewSettings.cc, src/Settings/FlyViewSettings.h, src/VideoStreaming/SubtitleWriter.cc, src/comm/LinkConfiguration.cc, src/comm/LinkConfiguration.h, src/comm/LinkManager.cc, src/comm/LinkManager.h, src/comm/LogReplayLink.cc, src/comm/LogReplayLink.h, src/ui/preferences/GeneralSettings.qml
Note the Log Replay Status Bar on/off setting has moved to Fly View Settings. Because of this your previous setting will not be preserved.
Also a benefit of this new code is that Log Reaply is now available on Mobile as well.
=> Support Log Replay in new Qml only system

src/FirmwarePlugin/FirmwarePluginManager.cc, src/FirmwarePlugin/PX4/PX4FirmwarePluginFactory.cc, src/PlanView/MissionSettingsEditor.qml, src/QmlControls/QGroundControlQmlGlobal.cc, src/QmlControls/QGroundControlQmlGlobal.h
Show vehicle options when offline editing missions.
The original code would only show the list of options if multiple firmware types was supported instead of looking at the number of vehicle types a given firmware supports.
=> Multiple vehicle types

src/FactSystem/ParameterManager.cc, src/FirmwarePlugin/APM/APMParameterMetaData.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc, src/FirmwarePlugin/PX4/PX4ParameterMetaData.h
Fix problems with parameter meta data methods not conforming to spec as well as using incorrect vehicle type.
Replacement for #7481, #7480, #7476
=> Parameter meta data cleanup

src/AnalyzeView/LogDownloadPage.qml, src/AutoPilotPlugins/APM/APMPowerComponent.qml, src/AutoPilotPlugins/APM/APMSensorsComponent.qml, src/AutoPilotPlugins/APM/APMSubFrameComponent.qml, src/AutoPilotPlugins/Common/RadioComponent.qml, src/AutoPilotPlugins/PX4/AirframeComponent.qml, src/AutoPilotPlugins/PX4/PowerComponent.qml, src/AutoPilotPlugins/PX4/SensorsSetup.qml, src/FactSystem/FactControls/FactTextField.qml, src/FactSystem/FactControls/FactValueSlider.qml, src/FlightDisplay/FlightDisplayView.qml, src/FlightMap/FlightMap.qml, src/FlightMap/Widgets/CameraPageWidget.qml, src/FlightMap/Widgets/ValuePageWidget.qml, src/MissionManager/QGCMapPolygonVisuals.qml, src/MissionManager/QGCMapPolylineVisuals.qml, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanView.qml, src/PlanView/SurveyItemEditor.qml, src/QmlControls/AppMessages.qml, src/QmlControls/LogReplayStatusBar.qml, src/QmlControls/ParameterEditor.qml, src/QmlControls/QGCFileDialog.qml, src/QtLocationPlugin/QMLControl/OfflineMap.qml, src/VehicleSetup/FirmwareUpgrade.qml, src/ui/MainRootWindow.qml
Renamed `showDialog()` to `showComponentDialog()`.
There are two globally accessible message dialogs: A simple Title/Message one (with an automatic Ok button) and a complex, `QGCViewDialogContainer` based message dialog where you pass a component with the dialog contents (and define the buttons to show). This makes it unambiguous which one is which.
Also fixed a couple of instances where `showDialog()` was been called with wrong arguments. One was defining a button and the other was missing a title.
Fixes #7501
=> Disambiguate showComponentDialog

deploy/qgroundcontrol_installer.nsi
Switch to collecting mini dump instead of full dump. Full dumps are just too large.
=> Windows: Switch to mini dump

src/ui/toolbar/MainToolBarIndicators.qml
* Fix branding logo size
* Handles branding logo visibility according to available space.
Fixes #7509
=> Branding Logo Fixes

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
Changes made to use current mavlink spec for writing parameters to non-ArduPilot components broke normal ArduPilot param write.
=> ArduPilot: Fix parameter write broken by non-ArduPilot component changes

android/src/org/mavlink/qgroundcontrol/QGCActivity.java, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h, src/VideoStreaming/VideoStreaming.cc, src/VideoStreaming/VideoStreaming.pri, src/main.cc
GStreamer is setup to always use software video decoding which is consuming more CPU power and battery.
This change introduces hardware video decoding on Android using Android Media gstreamer plugin which is always optimized for particular platform.
If hardware decoding fails for some reason the system falls back to software decode.
=> User hardware video decoding on Android

android/src/org/mavlink/qgroundcontrol/QGCActivity.java, android/src/org/mavlink/qgroundcontrol/TaiSync.java
How to reproduce:
Make a clean install on Android and attach Taisync
A window asking for association of QGC with Taisync pops up.
When user accepts it QGC crashes and restarts.
Fix:
Do not request permission on accessory in a probe accessories timer.
=> Bugfix: QGC crashes when Taisync is attached for the first time

src/Audio/AudioOutput.cc, src/Audio/AudioOutput.h, src/QGCApplication.cc, src/QGCApplication.h, src/Vehicle/Vehicle.cc, src/uas/UAS.cc
In response to #7517 
This sets the Text to Speech engine to the current locale. I'm not sure how this will work as 99% of the spoken sentences are in English and are not localized. @ArkadiuszNiemiec could please test this and see how it behaves? This "fix" might be the opposite of what is required. I'm thinking it makes more sense to set the TTS engine to always use English regardless of the current locale as that's the only source of text it will ever see. If that's the case, let me know and I will switch to "always use English" instead.
I can't really test as my system is set to its default (en_US). If I switch the language in QGC, the spoken text is obviously still English but with a weird accent.
=> Handle text to speech locale

src/FlightDisplay/FlightDisplayView.qml, src/QmlControls/PreFlightCheckButton.qml, src/QmlControls/PreFlightCheckList.qml
I don't quite grok the over-complexity/hardcoded dependencies of that Preflight Checklist. I will deal with that when I find the time. In the mean time, I've made it into a proper, modal dialog using current QtQuick controls.
=> Moved the preflight checklist to a proper, modal dialog.

ChangeLog.md, src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePluginFactory.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
This is just the beginning. Currently, a lot of the variables that define a vehicle type are specified on a per firmware plugin type. That works for APM given that it has different firmwares for each vehicle type but not so much for PX4 where one single firmware supports everything.
This change assigns a vehicle type during the creation of an instance of `FirmwarePlugin`. It further implements `supportsNegativeThrust()` based on the vehicle type (for PX4 only).
Now we just need to do the other 99.9% of missing rover support :P
@DonLakeFlyer, @dagar The whole Joystick/Radio setup is hardcoded for full, 3 axis attitude in addition to throttle. We need to sort out how to handle just "steering" and "throttle" (and a button for brake, etc.)
=> Initial support for PX4 Rover

qgroundcontrol.qrc, src/QGCApplication.cc, src/QGCApplication.h, src/main.cc, src/ui/ExitWithErrorWindow.qml
There were a couple of places in the code where `QMessageBox` was still being used. As these don't work with a QtQuick application, it was causing a crash when used. Primarily on Linux (the only place where these were being called).
The code now loads a specific error QML "main window" showing the error message, which can be used for other fatal errors to be shown before the main QML window is shown.
This replaces #7479
=> Replace usage of QMessageBox with a QML window.

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
Related to #7427
Fixed protocol negotation when the vehicle does not support MAV_CMD_REQUEST_PROTOCOL_VERSION.
Here is how the negotation now works:
* Start with the assumption that the capability bits are known
* Send MAV_CMD_REQUEST_PROTOCOL_VERSION to the vehicle
* Start a timeout on the COMMAND_ACK for MAV_CMD_REQUEST_PROTOCOL_VERSION
* If GCS receives COMMAND_ACK.result != MAV_RESULT_ACCEPTED or times out waiting for the COMMAND ACK then set the link to Mavlink 2 if the capability bits say it is supported
* If GCS receives COMMAND_ACK.result == MAV_RESULT_ACCEPTED start a timeout waiting to receive a PROTOCOL_VERSION messsage
* If PROTOCOL_VERSION is never received then set the link to Mavlink 1
* If PROTOCOL_VERSION message is received set the link accordingly to 1 or 2
=> Mavlink protocol version negotiation fixes

src/FlightDisplay/FlightDisplayViewMap.qml, src/MissionManager/QGCMapPolygonVisuals.qml, src/MissionManager/QGCMapPolylineVisuals.qml, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanView.qml, src/PlanView/RallyPointItemEditor.qml, src/PlanView/SimpleItemEditor.qml, src/QmlControls/FlightModeMenu.qml, src/QmlControls/ParameterEditor.qml, src/QmlControls/QGCFileDialog.qml, src/QmlControls/QmlTest.qml, src/ui/toolbar/LinkIndicator.qml, src/ui/toolbar/ModeIndicator.qml, src/ui/toolbar/MultiVehicleSelector.qml
Update all files that use a QML Menu item to QtQuick.Controls 2.4 to solve the issue of a menu showing up in random places on Android.
=> QtQuick.Controls 2.4

custom-example/src/CustomPlugin.cc, src/QmlControls/ParameterEditor.qml
In response to #7547
I had to revert `ParameterEditor` to QtQuick.Controls 1.x as it makes use of `ExclusiveGroup`, which no longer exists in newer versions of QtQuick.Controls. I will need to take a closer look at these and find a way around it.
Closes #7547 
P.S. These errors, when they occur, are all shown in the console:
```
qrc:/qml/SetupParameterEditor.qml:18:1: Type ParameterEditor unavailable
qrc:/qml/QGroundControl/Controls/ParameterEditor.qml:41:5: ExclusiveGroup is not a type
```
That would immediately tell me what went wrong.
=> Revert ParameterEditor to QtQuick.Controls 1.x

src/main.cc
---
name: QGC fails silently when it fails to initialize 
about: There is no user feedback when it fails to start
---
This patch provides two feedback if QGC fail to initialize, one as a system error number with the return and a critical message with a human string for the user.
=> main: Returning critical messsage and an error code when QGC is alredy running

src/Vehicle/Vehicle.cc
Because of `_cameras` QML bindings check for `nullptr` won't work in the binding pipeline. The dangling pointer access will cause a runtime fault
=> Fix dangling pointer access

src/FlightDisplay/GuidedAltitudeSlider.qml, src/QmlControls/QGCSlider.qml
Make guided altitude slider zero-based when vehicle is on the ground (positive values only). Once you are airborne, it goes back to -1 to 1 as you may go up or down.
=> Guided Altitude Slider

CMakeLists.txt, cmake/CompileOptions.cmake, cmake/QGCDeploy.cmake, cmake/Qt5QGCConfiguration.cmake, src/CMakeLists.txt, src/Settings/CMakeLists.txt, src/Vehicle/CMakeLists.txt, src/VideoStreaming/CMakeLists.txt
VideoStreaming is not enabled while building using CMake, we missed the gstreamer libraries and a few other things. I also took the time to make cmake a bit more easy to handle.
=> CMake updates: Enable VideoStreaming while using CMake as buildsystem

src/AutoPilotPlugins/PX4/AirframeComponent.cc, src/AutoPilotPlugins/PX4/AirframeComponent.qml
Have a separate panel for Airframe Setup if the firmware is using a custom type:
=> Airframe Setup (custom types)

qgroundcontrol.qrc, src/FlightDisplay/FlightDisplayViewMap.qml, src/MissionManager/QGCMapPolygonVisuals.qml, src/MissionManager/QGCMapPolylineVisuals.qml, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanView.qml, src/PlanView/RallyPointItemEditor.qml, src/PlanView/SimpleItemEditor.qml, src/QmlControls/FlightModeMenu.qml, src/QmlControls/ParameterEditor.qml, src/QmlControls/QGCComboBox.qml, src/QmlControls/QGCFileDialog.qml, src/QmlControls/QGCMenu.qml, src/QmlControls/QGCMenuItem.qml, src/QmlControls/QGCMenuSeparator.qml, src/QmlControls/QGroundControl/Controls/qmldir, src/QmlControls/QmlTest.qml, src/ui/toolbar/LinkIndicator.qml, src/ui/toolbar/ModeIndicator.qml, src/ui/toolbar/MultiVehicleSelector.qml
A roundabout way to make sure all QML Menus are using QtQuick.Controls 1.x. Using QtQuick.Controls 2.x, you end up with weird artifacts when the menus are over a map. 
Closes #7562
=> Use QtQuick.Controls 1.x menus

src/AutoPilotPlugins/APM/APMPowerComponent.qml
This exposes the BATT_AMP_OFFSET parameter for ArduPilot vehicles and adds an entry for the [Blue Robotics Power Sense Module R2](https://www.bluerobotics.com/store/comm-control-power/elec-packages/psm-asm-r2-rp/)
=> Expose BATT_AMP_OFFSET and add Blue Robotics power sense module

src/Microhard/MicrohardHandler.cc, src/Microhard/MicrohardHandler.h, src/Microhard/MicrohardManager.cc, src/Microhard/MicrohardManager.h, src/Microhard/MicrohardSettings.cc, src/Microhard/MicrohardSettings.qml
Addresses point 1 from  #7580 Microhard issues
Added possibilty to set Configuration user name.
Display "Login error" status message in case of wrong configuration username/password.
=> Microhard improvements

src/Camera/QGCCameraControl.cc
When stream configuration changed QGC restarted the video receiver which resulted in double video restart thus taking longer for the new video to reappear.
Specifically this happened when changing between video and photo mode on Sony cameras.
We don't have to restart video streaming receiver when we receive video stream configuration message. When source changes the video is restarted automatically.
=> We don't have to restart video when stream config changes

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
In response to #7621 
For PX4, don't hide heading if vehicle is multi-rotor. No longer checks for a parameter.
Closes #7621
=> Show heading on waypoint if multi-rotor.

src/Joystick/Joystick.cc, src/Joystick/Joystick.h
When using a button for controlling the gimbal, you cannot send an absolute position (angle) unless you know the current position. For that I was incrementing/decrementing the current position as received by the MAVLINK_MSG_ID_MOUNT_ORIENTATION message for every button press. Ideally, we need a new _message_ (not command) to stream “steps”. That way we can simply stream these messages while these buttons are down and not incur the overhead of a command nor having to rely on receiving an updated gimbal position so we can increment/decrement it on a subsequent command.
For the moment, what I am doing is keeping a local gimbal “range” (an arbitrary range of -90° to 35° pitch and -180° to 180° yaw). As you move it about, I’m using these values instead of the values returned by the …
=> Keep track of gimbal position locally.

custom-example/res/CustomCameraControl.qml, custom-example/res/CustomFlyView.qml, custom-example/src/CustomQuickInterface.cc, custom-example/src/CustomQuickInterface.h, src/FlightDisplay/VideoManager.cc, src/QmlControls/JoystickThumbPad.qml
Showing how to implement a custom gimbal control (re-using the virtual joystick control)
Also adding a setting so the user can enable/disable the control.
=> Custom gimbal control

src/MissionManager/MavCmdInfoCommon.json, src/MissionManager/MissionCommandList.cc, src/MissionManager/MissionCommandTree.cc, src/MissionManager/MissionCommandUIInfo.cc, src/MissionManager/SimpleMissionItem.cc, src/PlanView/SimpleItemEditor.qml
A couple of camera mission commands have no editable parameters. As a result, QGC was presenting a raw list of all 7 parameters to edit:
By flagging the parameters as `friendlyEdit`, this is skipped and nothing is shown (as it should be):
=> Camera mission commands

CentOS.md
Thanks to @dogmaphobic for providing these useful steps to get QGC working under CentOS. I changed/added all the main points I found out while setting it all up in a VM, and a toughpad in a UAV Components Micronav device. This is supposed to save other people a lot of time since CentOS behaves quite different compared to Ubuntu.
=> Improve CentOS instructions

custom-example/res/MainToolbar/CustomMainToolBar.qml, src/AnalyzeView/MAVLinkInspectorController.cc, src/Joystick/Joystick.cc, src/Joystick/Joystick.h, src/ui/MainRootWindow.qml, src/ui/preferences/MockLink.qml
* Handle full screen (for mobile or tiny screens) at the root window level.
* Build (Joystick) action list when we have a vehicle assigned
* Hide APM Mocklinks if APM support is not built.
* Fix Mocklink UI
=> Custom fixes

src/QmlControls/PreFlightCheckList.qml
This allow a custom preflight action to temporarily disable Reset capability
=> PreFlight Checklist: Expose reset button enable/disable

qgroundcontrol.pro
I followed the Getting Started page, I've got Qt 5.11.3 with MSVC 2015 32 bit on Windows 8.1 Pro, and I got this error.  The solution was simple.
=> Fix MSVC 2015 "fatal error C1060: compiler is out of heap space"

custom-example/custom.pri, custom-example/src/CustomPlugin.cc, custom-example/src/CustomPlugin.h, custom-example/src/CustomVideoManager.cc, custom-example/src/CustomVideoManager.h, custom-example/src/FirmwarePlugin/CustomCameraControl.cc, custom-example/src/FirmwarePlugin/CustomCameraControl.h, src/Camera/QGCCameraControl.cc, src/Camera/QGCCameraControl.h, src/FlightDisplay/VideoManager.cc, src/FlightDisplay/VideoManager.h, src/VideoStreaming/VideoReceiver.cc, src/api/QGCCorePlugin.cc, src/api/QGCCorePlugin.h
This shows how to implement a custom VideoManager. It handles a custom camera parameter (`CAM_ENC`), which defines the video stream encoding, which is then parsed and handled by the video manager.
=> Show how to implement custom video manager

src/FlightDisplay/VideoManager.cc, src/FlightDisplay/VideoManager.h
This fixes an edge case where if you were in full screen video mode, lost a connection to an uncalibrated vehicle and regained connection, QGC would go straight into Vehicle Setup with no main toolbar allowing you to switch away from it.
=> Disable full screen video if no vehicle or connection lost

src/QGCApplication.cc
Mobile builds were not showing pop up errors.
Caused by sequence of changes sort of doc'ed here: https://github.com/mavlink/qgroundcontrol/issues/2829. 
I believe there was an initial problem with error messages popping up before the main window was created either causing crashes or a strange race condition on main window creation. There was a fix for that which went in which screwed thing up. Then a fix for that screw up went in which only worked on desktop builds.
Mobile builds don't really have the same race condition crash problems. But even so I changed the code to match enabling popup errors to only display after the main qml window was created.
=> Turn on popup errors for mobile builds

src/FlightDisplay/FlightDisplayViewMap.qml
Related to #7646
Default is set to previous Stable default of 1k to maintain back compat. That said, not sure if 1K is still a too small value for generic QGC.
=> Configurable maximum distance on Go To Location

src/Vehicle/CMakeLists.txt
Fixes build
A recent patch added a new file but forgot to add on the CMake project file.
=> CMake: Add missing source on CMake

CMakeLists.txt
Mavlink fails terribly on the check for -Waddress-of-packet-member
but this is not a problem of QGC, if I don't remove this warning
it's impossible to look at the terminal for QGC warnings.
This needs to be fixed however, but this is not the place.
=> CMake: Set warning level and disable -Waddress-of-packet-member

custom-example/src/CustomPlugin.cc, custom-example/src/CustomVideoManager.cc, src/Airmap/AirMapAdvisoryManager.cc, src/Airmap/AirMapFlightPlanManager.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/Taisync/TaisyncManager.cc, src/Vehicle/MultiVehicleManager.cc, src/Vehicle/VehicleObjectAvoidance.cc, src/comm/BluetoothLink.cc, src/comm/LinkConfiguration.cc, src/comm/LinkManager.cc, src/comm/LogReplayLink.cc, src/comm/MockLink.cc, src/comm/SerialLink.cc, src/comm/TCPLink.cc, src/comm/UDPLink.cc, src/uas/UAS.cc
Remove dynaic casts thru the software for objects that inherti from QObject.
qobject_cast does not use RTTI and thus is much faster. Also, use `auto` keyword to not repeat class names when the class name is explicit.
=> Remove dynamic cast

custom-example/res/CustomCameraControl.qml
Video running time (when recording video)
Shutter count (when capturing photos)
=> Enable video running time and shutter count

custom-example/res/CustomFlyView.qml, custom-example/src/CustomQuickInterface.cc, custom-example/src/CustomQuickInterface.h
Add one row at the top of the Custom Vehicle Indicator control to show: lat, lon and hdop
=> custom-example: Add GPS info to the Vehicle Indicator

src/Camera/QGCCameraControl.cc, src/QtLocationPlugin/QGCMapEngine.cpp, src/QtLocationPlugin/QGCMapEngine.h
QGCCameraControl::storageFreeStr(): use QGCMapEngine::storageFreeSizeToString()
new string conversion routine for improved displaying of available memory in CameraManager GUI
* the _storagefree variable has a resolution of MB, it thus makes no sense to display no unit or KB, and for the unit MB it makes no sense to have a fraction
* for GB and TB it shows two fraction digits
* adds a blank between value and unit for better visibility
* didn't modify the existing bigSize conversion function, since it's used in several other places, and the unit thing is specific to _storagefree
=> CameraManager, improve displayed available memory

custom-example/res/MainToolbar/CustomMainToolBarIndicators.qml, custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc, src/QmlControls/QGroundControlQmlGlobal.h, src/ui/preferences/GeneralSettings.qml, src/ui/toolbar/PairingIndicator.qml
If pairing is not supported (or disabled manually), make sure all UI elements related to it are not shown.
=> Remove all references to Pairing if it's not supported.

QGCCommon.pri, QGCExternalLibs.pri, src/QmlControls/QGroundControlQmlGlobal.cc, src/QmlControls/QGroundControlQmlGlobal.h
* There are now ```__androidArm32__``` and ```__androidArm64__``` defines available for source code.
* Version string returned by Qml QGroundControl object.version adds "32/64 bit" to the end so you can see which version you are running. Android only.
=> More android bitness

src/FlightDisplay/FlightDisplayViewMap.qml, src/FlightMap/MapScale.qml, src/PlanView/PlanView.qml, src/QtLocationPlugin/QMLControl/OfflineMap.qml
* Zoom buttons are now part of the MapScale control (instead of toolstrip)
* Added zoom buttons to Fly view
* Zoom buttons are still not shown on mobile
=> Zoom buttons move to MapScale control

src/AutoPilotPlugins/APM/APMFlightModesComponentSummary.qml, src/AutoPilotPlugins/APM/APMSafetyComponent.qml, src/AutoPilotPlugins/APM/APMSafetyComponentSummary.qml
You can't use rover as a vehicle type to check for parameter differences since a boat uses ArduRover firmware variant as well.
=> Fix problems with ArduRover firmware parameter differences

src/PlanView/SurveyMapVisual.qml
Working to simplify Plan/Fly views and make things easier to use. This is just the start of a long set of changes...
Full Survey visuals are not only show when the item is selected.
When the Survey item is not selected you get partials visuals. This makes thing like working on other Plan items which are within the survey way easier.
=> Simplify Survey visuals

src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/Joystick/Joystick.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
* Add access to all (unfiltered) flight modes.
* Have joystick use the unfiltered list of flight modes for button assignment.
=> Flight Modes

src/ui/MainRootWindow.qml
Fix application hanging on windows for 1.5s when closing.
The PR removes the old workaround that's not needed anymore.
=> Windows UX improvement: improve the windows 1.5s closing workaround

custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc, custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/Joystick/Joystick.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
Follow up on https://github.com/mavlink/qgroundcontrol/pull/7753
* Allow plugins to define what modes are available for joystick button assignment.
* Sort button action list
The API now has two methods for returning the flight modes. The original one, which is used for controlling what is displayed in the flight mode selector/indicator, and a new `FirmwarePlugin:: joystickFlightModes()`, which controls what modes are available for joystick button assignment.
The default implementation returns the same list. Custom plugins can have a different set of modes for each as shown below (it includes modes that are not usually available for selection from the flight mode menu).
=> Joystick flight modes

src/Joystick/Joystick.cc, src/VehicleSetup/JoystickConfigController.cc
* Load joystick settings whenever there is a vehicle change.
The original code would load the settings on boot and never again. This would cause the button mapping to be loaded before QGC knows what modes are available for a given vehicle. Note that there is no way currently to have a same joystick with different settings for different vehicles. There is no standard way to ID a vehicle and tag a set of joystick settings to that vehicle.
* Disable gimbal control using joystick analog channels.
That code was experimental and incomplete. The joystick calibration is hardwired to only work with the four, vehicle attitude controls. It will need to be properly modified to handle further channels.
=> Joystick settings

src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/ui/preferences/GeneralSettings.qml
This makes each vehicle log it's facts to a `.csv` file named as `<timestamp> vehicle<vehicle_ID>.csv`
This is a sample file:  [2019-05-21 18-22-17_vehicle2.txt](https://github.com/mavlink/qgroundcontrol/files/3228873/2019-05-21.18-22-17_vehicle2.txt)
This requires **no interaction of the user whatsoever**, the .csv will be created automatically just like the .tlogs.
This allows users to easily open the data with any spreadsheet software or Matlab, without going through the hassle of using mavlogdump or Mission Planner to deal with a tlog, for example.
close #7322
=> Add csv logging of telemetry

src/MissionManager/GeoFenceController.cc, src/MissionManager/GeoFenceController.h, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/PlanMasterController.cc, src/MissionManager/PlanMasterController.h, src/MissionManager/RallyPointController.cc, src/MissionManager/RallyPointController.h
Fix for #7760.
The bug/complexity here relates to this case:
* User creates a Plan while offline
* User connects to vehicle
* We don't want to blow away the Plan the user created while offline with the Plan from the vehicle
The fix I made makes this sequence better in that it fixes #7760. But still not fully correct. There are still problems if the Plan the user created say has no fence, but the vehicle does have a fence in the scenario above.
=> Fix initial load of fence/rally for Plan view

src/PlanView/SimpleItemMapVisual.qml
Items which have no lat/lon no longer display in views.
=> Plan/Fly: Remove child item display

src/FlightDisplay/FlightDisplayViewMap.qml, src/FlightMap/MapItems/PlanMapItems.qml, src/PlanView/MissionItemMapVisual.qml, src/PlanView/SimpleItemMapVisual.qml, src/QmlControls/QGCDynamicObjectManager.qml
Here is what we have now:
That's a massive amount of crap in front of the users faces most of which has no value.
So instead we hide the waypoint indicators except for the one the vehicle is travelling towards:
The waypoints indicators show up if you Pause the vehicle. This allows you to then do a GoTo Waypoint by clicking on one:
Next step: Direction Arrows like I have working in Plan view.
=> Fly: Hide waypoint indicators unless they are really needed

src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/MissionControllerTest.cc, src/MissionManager/MissionControllerTest.h, src/QmlControls/QmlObjectListModel.cc, src/QmlControls/QmlObjectListModel.h
* Fixes #7778
* Use external begin/endReset calls on QmlObjectListModels when making major changes to them. This keeps Qt from blowing it's brains out.
* Also fixed Plan View arrows which I broke with last Fly View arrow pull
=> Mission controller recalc

ChangeLog.md, src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc, src/AutoPilotPlugins/APM/APMMotorComponent.cc, src/AutoPilotPlugins/APM/APMMotorComponent.h, src/AutoPilotPlugins/APM/APMMotorComponent.qml, src/FirmwarePlugin/APM/APMResources.qrc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/VehicleSetup/SetupView.qml
I implemented this something like two years ago. But I've been hoping that ArduPilot would support motor testing by motor output number as opposed to the letter thing which just seems really odd to me. Anyway, that still hasn't happened and it's a key setup element which is missing. So I just switched the existing code over to the motor letter model.
Along with it I fixed up the motor test page to be safer. Which hopefully at some stage can be used to support PX4 motor testing as well.
=> Enable ArduPilot motor testing

src/MissionManager/VisualMissionItem.cc
Related to #7774. Terrain data as being queried for items which had not coordinate. Causing failures due to bad lat/lon values.
=> Don't query terrain if no location

src/MissionManager/MissionController.cc
Fixes #7799
As it's done for SimpleItem insertion, add a SimpleItem with TakeOff command before the ComplexItem
=> Add Takeoff SimpleItem if first item is complex

qgroundcontrol.pro
There is a long list of issues against this with nobody looking at them. I'm tired of fighting with this on my own builds as well. Until this can be made to work on all OS and verified to be working correctly and run correctly on virgin installs of all OS it needs to stay off.
Related to #7743 and all the other Pairing issues
=> Disable pairing

src/comm/BluetoothLink.cc, src/comm/LinkInterface.h, src/comm/LinkManager.cc, src/comm/MAVLinkProtocol.cc, src/comm/MAVLinkProtocol.h, src/comm/SerialLink.cc, src/comm/TCPLink.cc, src/comm/UDPLink.cc
It appear really useful to have both messages sent and received in the telemetry log from QGC :
- To have the complete story of which order trig which response from the drone
- To analyze all messages sent/received
- To retrieve all orders sent while replaying a mission
Here the changes I propose : 
- Add a signal emitted by writeBytes of each LinkInterface (TCP/UDP for the moment)
- Connect this signal to MAVLinkProtocol::logSentBytes in LinkManager
- MAVLinkProtocol::logSentBytes will log messages sent from
QGC
=> Add oucoming messages in tlog

ChangeLog.md, qgroundcontrol.pro, src/FlightDisplay/FlightDisplayViewMap.qml, src/QGCApplication.cc, src/Vehicle/TrajectoryPoints.cc, src/Vehicle/TrajectoryPoints.h, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/uas/UASMessageHandler.h
Problems with previous algorithm:
* Performance was crap. Too many points were added. Mobile builds had to limit path length due to perf problems.
* Run SITL it higher speed or replay log at higher speed an the flight path was really bad.
New algorithm is distance and azimuth change based with tolerances set to reduce point count yet still show high quality fligh path. This new code reduces point count for lines on the map by 80%+. But if you compare old to new the flight path shown is actually closer to the true flight path.
=> New flight trajectory display algorithm

src/Microhard/MicrohardManager.cc, src/Microhard/MicrohardManager.h, src/Microhard/MicrohardSettings.cc, src/Microhard/MicrohardSettings.h, src/Microhard/MicrohardSettings.qml, src/PairingManager/PairingManager.cc
Add a setting in Microhard settings for the channel used during communication.
During pairing phase a different pairing channel is used which is by default set to 78. The channel that is set in Microhard settings panel is then transfered to pairing-manager on companion computer side and in order to establish a connection both sides have to switch to this user selected channel.
=> Setting for microhard channel/frequency

src/FlightMap/MapItems/MissionItemIndicator.qml, src/MissionManager/MissionController.cc, src/PlanView/SimpleItemMapVisual.qml, src/QmlControls/MissionItemIndexLabel.qml
Getting closer to being happy with this. But still lots of futzing to go before I consider it done.
* Waypoints show small indicators if not selected. As opposed to nothing.
* Labels for things like Takeoff and so forth show up more than before. These were missing at some key points.
* Transtion from unselected to selected item has an animation on size change. Have to have fun somewhere!
=> More work on mission item indicators

src/FlightDisplay/FlightDisplayView.qml
Left hand toolstrip on Fly View was positioning incorrectly.
=> Fly View: Fix Toolstrip positioning

src/PlanView/SurveyItemEditor.qml, src/PlanView/TransectStyleComplexItemStats.qml, src/Settings/PlanView.SettingsGroup.json, src/Settings/PlanViewSettings.cc, src/Settings/PlanViewSettings.h
* This allows you to complete a Survey setup all from the Presets tab
* Added a setting which specifies whether the Presets or Grid tab is shown as initial selection. Default is show Grid. Custom builds can override to show Presets for situations where most customers will use presets.
=> Plan: Presets - tweak settings from tab

src/Vehicle/Vehicle.cc
=> Treat VHR_HUD.throttle as int16 for reverse throttle

src/AutoPilotPlugins/APM/APMCameraComponent.qml, src/AutoPilotPlugins/APM/APMCameraSubComponent.qml, src/AutoPilotPlugins/APM/APMLightsComponent.qml, src/AutoPilotPlugins/APM/APMPowerComponent.qml, src/QmlControls/PIDTuning.qml, src/VehicleSetup/FirmwareUpgrade.qml, src/ui/preferences/MavlinkSettings.qml
Since the switch to Qt Quick Controls2 all the combo boxes which used a ListModel which had multiple named roles in it were broken. In that case textRole must be explicitly set to "text".
=> Fix textRole usage for QGCComboBox

ChangeLog.md, qgroundcontrol.qrc, src/FlightMap/MapItems/MissionItemIndicatorDrag.qml, src/FlightMap/MapItems/MissionLineView.qml, src/MissionManager/QGCMapPolygon.cc, src/MissionManager/QGCMapPolygon.h, src/MissionManager/QGCMapPolygonVisuals.qml, src/PlanView/PlanView.qml, src/PlanView/SurveyItemEditor.qml, src/PlanView/SurveyMapVisual.qml, src/QmlControls/KMLOrSHPFileDialog.qml, src/QmlControls/QGCDynamicObjectManager.qml, src/QmlControls/QGroundControl/Controls/qmldir
* New UI for polygon editing. Makes features much more visible to users.
* New Trace Polygon support for creating polygons. Allows you to trace areas of the map by clicking to add vertices.
* Circular polygon now allows you to drag radius interactively.
* Survey in initialized with no polygon to start
Basic Polygon
Circular Polygon (white drag handle on edge of circle allows resize)
Trace Polygon (in the middle of tracing)
Initial add of Survey
=> Polygon tools, Survey changes

src/QmlControls/QGCComboBox.qml, src/ui/toolbar/ArmedIndicator.qml, src/ui/toolbar/ModeIndicator.qml
Users didn't realize they could click on the flight mode and arm text in the toolbar since it didn't really look like something clickable. Caused a safety problem with respect to Disarming with an Emergency Stop from these controls. Changed theb to be a ComboBox variant instead:
* Modified QGCComboBox for new features:
* Font is settable
* QGCComboBox.alternateText - show this text instead of the combo selection
* QGCComboBox.sizeToContents - set to true, don't set width: combo will automatically size the fit the width of the largest item in the dropdown
* Changed Flight Mode and Armed toolbar indicators to use the new QGCComboBox + features
=> Mode/Arm indicators, new QGCComboBox features

src/QmlControls/QGCToolBarButton.qml
New toolbar broke button width sizing. Toolbar buttons were too narrow and were clipped. Mostly noticable on high-dpi mobile devices.
=> Fix toolbar button sizing

src/QGCMapPalette.h
CentOS startup stack dump:
```
#0  __base_ctor (this=<optimized out>, acolor=...) at /home/user/Qt/5.12.4/gcc_64/include/QtGui/qcolor.h:302
#1  thumbJoystick (this=<optimized out>) at moc/../../qgroundcontrol/src/QGCMapPalette.h:57
#2  QGCMapPalette::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>, _a=<optimized out>, _id=<optimized out>, _c=<optimized out>, _o=<optimized out>) at moc/moc_QGCMapPalette.cpp:122
#3  0x000000000044df3b in QGCMapPalette::qt_metacall (this=0x35dd8a0, _c=QMetaObject::ReadProperty, _id=1, _a=0x7fffbeff2650) at moc/moc_QGCMapPalette.cpp:178
```
=> Fix uninitialized variable that might cause an undefined behavior

src/Audio/AudioOutput.cc
Force TTS engine to English as all incoming messages from the autopilot are in English and not localized.
=> For TTS to use English

src/MissionManager/CorridorScanPlanCreator.cc, src/MissionManager/CustomPlanCreator.cc, src/MissionManager/FixedWingLandingComplexItem.cc, src/MissionManager/FixedWingLandingComplexItem.h, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItem.h, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/StructureScanPlanCreator.cc, src/MissionManager/SurveyPlanCreator.cc, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/VisualMissionItem.cc, src/MissionManager/VisualMissionItem.h, src/PlanView/CorridorScanEditor.qml, src/PlanView/FWLandingPatternEditor.qml, src/PlanView/FWLandingPatternMapVisual.qml, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanView.qml, src/PlanView/SimpleItemEditor.qml, src/PlanView/StructureScanEditor.qml, src/PlanView/SurveyItemEditor.qml
The new Create Plan UI now puts the mission items into a "Wizard Mode" which will step you through what you need to do next. All of the automatic Wizard stuff only works from Create Plan. If you create a Plan by hand using the tools, things work like they used to without these "Done..." buttons.
Here is an example sequence for Create Survey on a Fixed Wing:
After you click Survey you end up here, where you futz with the Takeoff item. Once you are happy with it, you click "Done Adjusting" which will take you to the Survey item.
This is where you end up after you clicked "Done Adjusting" on the Takeoff item. The image shows what it looks like after I added a polygon. Once you have your survey to where you want it you click "Done With Polygon". Which will take you to the Fixed Wing Landing …
=> Wizard Mode for Create Plan

CodingStyle.cc
Decided that Q_UNUSED is crap. Problem is that you can start to use the th argument and leave Q_UNUSED in there. Instead comment out the argument name as show in the style. This leaves as much information possible still in file for readability and future use. Don't remove the argument name entirely.
Correct:
```void _foo(Foo /* foo */)```
Incorrect:
```void _foo(Foo)```
=> Coding Style: Unused arguments

src/ui/toolbar/MainToolBarIndicators.qml
There is a chicken and egg situation with the Easter Egg :-)
showAdvancedUI needs to be true prior to confirmation.
Probably an old typo from : e55deea4d3a127bb532a630f745b6da84659954b
=> Fix EasterEgg

src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/CorridorScanComplexItem.h, src/MissionManager/SurveyComplexItem.cc
If you let the transect spacing get too small you end up with way too many transects and QGC will blow up from perf problems. In order to prevent this the minimum transect spacing is set internally to 0.5 meters. Anything lower than that will automatically just generate a single transect.
Fix for #7870
=> Plan Patterns: Minimum transect spacing of 0.5 meters

src/FlightDisplay/FlightDisplayView.qml
Remove leftover deprecated Resume Mission Guided action code. This could cause an empty action item to be added when clicking "Action".
=> Guided: Resume mission

ChangeLog.md, src/FlightDisplay/GuidedActionsController.qml
This prevents the user from possibly causing the plane to loiter much too low to the ground.
=> Fly: Disable Pause button if fixed wing on approach

src/FlightDisplay/GuidedActionsController.qml, src/ui/toolbar/ArmedIndicator.qml, src/ui/toolbar/BatteryIndicator.qml, src/ui/toolbar/GPSIndicator.qml, src/ui/toolbar/GPSRTKIndicator.qml, src/ui/toolbar/LinkIndicator.qml, src/ui/toolbar/MainToolBarIndicators.qml, src/ui/toolbar/MessageIndicator.qml, src/ui/toolbar/ModeIndicator.qml, src/ui/toolbar/MultiVehicleSelector.qml, src/ui/toolbar/RCRSSIIndicator.qml, src/ui/toolbar/TelemetryRSSIIndicator.qml, src/ui/toolbar/VTOLModeIndicator.qml
Fix problem with extra empty space on iOs toolbar. Toolbar indicators now require a showIndicator property to determine whether the parent Loader item should be visible or not. Ths indicators themselves no longer set the visible property nor do they set width to 0 with invisible.
=> Toolbar: Indicator spacing

src/comm/LinkManager.cc, src/ui/preferences/LinkSettings.qml
When creating a new link, if you named it and then switched type (e.g. from Serial to UDP), the name would revert to "Unnamed".
Also, when editing a link name, the name change was not being signaled and the UI was not reflecting the new, edited name.
=> Persist link name when switching types.

src/AutoPilotPlugins/Common/MotorComponent.qml, src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
@DonLakeFlyer it only took the firmware several years to get it done :D
But here it is: https://github.com/PX4/Firmware/pull/13240
I changed the logic a bit. Previously, when moving a slider all the way down or when disabling the safety switch, the motors would still turn until the timeout triggered (of 1s). This does not inspire confidence, so I updated it to as long as the switch is enabled, the command is sent.
Remaining issues:
- QGC shows the wrong image: instead of x it showed me a + configuration on a quad.
- it works well on USB and wifi. But via telemetry (I used a holybro link), commands get buffered on the QGC side, and arrive with an increasing delay (when you wait a bit after enabling the safety slide, I experienced something like 20s).
=> PX4: enable motor test UI

src/MissionManager/GeoFenceController.cc, src/MissionManager/RallyPointController.cc
Both Geofence and Rally tests for support check not only the flight controller capability field but also the (MAVLink) protocol version. However, there was nothing keeping track of version changes. If you were to start QGC with no connections, QGC creates a dummy vehicle in order to handle mission planning. If later you were to connect to a real vehicle, the handing over between dummy and real vehicle was not updating the protocol version. You ended up with protocol version "0" and the test for Geofence and Rally would return false.
@DonLakeFlyer Do we really need to check protocol version if the capability flag is set? Also, that signal name (`Vehicle::requestProtocolVersion()`) is not exactly in line with the use in this context. I didn't spend a great deal of time trying to make sense …
=> Fix test for rally and geofence support.

QGCExternalLibs.pri
Pairing not supported under Windows
Remove zlib dependency for Windows.
Fixes https://github.com/mavlink/qgroundcontrol/issues/7954
=> Windows build fix

src/Camera/QGCCameraManager.cc
currently the CameraManager identifies a camera component by checking if it's component ID is a default camera ID, i.e. in range MAV_COMP_ID_CAMERA to MAV_COMP_ID_CAMERA6.
This is incorrect, it doesn't comply with the MAVLink specification.
The MAVLink specification suggests that a camera component should use one of the IDs MAV_COMP_ID_CAMERA ... MAV_COMP_ID_CAMERA6, but it does not require it! Instead the camera component should identify itself by it's MAV_TYPE, i.e. heartbeat fields autopilot = MAV_AUTOPILTO_UNDEFINED and type = MAV_TYPE_CAMERA.
This PR is doing this. I have checked it and it is working for me.
=> CameraManager: identify camera component by MAV_TYPE, not by compID

src/FlightMap/Widgets/CameraPageWidget.qml
CameraPageWidget.qml is a bit of a wild coding. This PR attempts to streamline it a bit.
1) bug: QGCCameraControl.CAMERA_MODE_UNDEFINED is not existing, hence changed to QGCCameraControl.CAM_MODE_UNDEFINED.
(I must admit I'm "surprised" that such an error doesn't trigger any compiler warning/error)
2) QGCCameraControl.CAMERA_MODE_VIDEO,  QGCCameraControl.CAMERA_MODE_PHOTO used instead of plain 1 and 0
3) once _camera has been checked there is no need to do _dynamicCameras.cameras.get(_curCameraIndex).cameraMode, replaced by _camera.cameraMode
4) _camera && _camera && _camera.hasModes changed to _camera && _camera.hasModes
5) _cameraPhotoIdle renamed to _photoIdle:  Unlike the other _cameraXXXX variables which relate to the _camera.cameraMode variable, _cameraPhotoIdle relates to a …
=> CameraManager: bug, cleanups in CameraPageWidget.qml

src/QGCApplication.cc, src/QGCApplication.h
Fix for https://github.com/mavlink/qgroundcontrol/issues/7962
It seems that QtCharts require `QApplication` instance instead of current used `QGuiApplication` even that we use only QML controls without initializing QWidgets. See `Note: ` for the hint: https://doc.qt.io/qt-5.12/qtcharts-index.html
Then crash stack in QT looks unrelated to the issue
=> Fix enabling Advanced Tuning crash

src/AutoPilotPlugins/PX4/SafetyComponent.qml, src/Vehicle/VehicleObjectAvoidance.cc
Sync collision prevention parameters with Firmware https://github.com/PX4/Firmware/pull/13135
FYI @baumanta
=> rename collision prevention parameters to match Firmware

src/AnalyzeView/MAVLinkInspectorController.cc, src/AnalyzeView/MAVLinkInspectorController.h, src/AnalyzeView/MAVLinkInspectorPage.qml, src/QmlControls/MAVLinkMessageButton.qml
You can now filter the messages in the MAVLink inspector by Component ID:
The component ID is now shown in the list in order to identify a message when multiple component ID are being displayed at once:
Note that the filter is only available if more than one Component ID is actually found:
=> Filter mavlink messages by component ID

src/QmlControls/ParameterEditor.qml
In the ParameterEditor, if one is clicking a 2nd time on an already selected group button, the rectangle in the parameter listview is reduced back to a width of 10, and therewith also the mouse area. The user then can't edit the parameter anymore (except she clicks in this small area of width 10). See picture below (note the very short underline below each parameter).
This happens here:
https://github.com/mavlink/qgroundcontrol/blob/master/src/QmlControls/ParameterEditor.qml#L205-L210
_rowWidth is reset to 10, without the dynamic adjustment in 
https://github.com/mavlink/qgroundcontrol/blob/master/src/QmlControls/ParameterEditor.qml#L262-L265
The PR solves this by resetting the width only if the group button wasn't clicked before.
cheers, Olli
=> Bug in ParameterEditor: 2nd click on group button shrinks mouse area

src/ui/MainRootWindow.qml
Those dialogs are supposed to be `Popup.NoAutoClose` if the dialog has a Close/Cancel/Ignore/etc. button. I found it by clicking outside it during a firmware update and having the dialog dismissed on me.
=> Fix inverted close policy logic.

src/MissionManager/KML.cc
Msision waypoints that saved in kml file cannot be opened in Android Google earth .
=> kml saved file cannot be opened in Google earth

src/MissionManager/QGCMapPolygonVisuals.qml, src/MissionManager/QGCMapPolylineVisuals.qml, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanEditToolbar.qml
* Polygon/line toolbar changes
* Centered
* Only as big as it needs to be
* Same background coloring as left toolstrip
* Incomplete data indication changes
* Entire item is borded in red if incomplete
* Text to explain why incomplete
Shows new toolbar and incomplete data visuals:
Incomplete due to terrain data:
Related to #7957
=> Plan: Incomplete visuals, Polygon/line toolbar

src/FactSystem/ParameterManager.cc, src/FactSystem/ParameterManager.h, src/QGCApplication.cc, src/QGCApplication.h, src/QmlControls/ParameterEditor.qml, src/ui/MainRootWindow.qml
* Initial parameter download progress works like it always did
* You will now get a progress bar for parameter writes. It shows up as soon as a parameter is updated and will go away when it gets a response back from the vehicle. If multiple writes are batched up like with a file load, then you get a progress bar whose length matches the batch count. And it will go away once all writes are acked.
* You will now get a progress bar for parameter reads just like writes. This shows up in some of the calibration ui where sets of params are redownloaded after a calibtation.
* If there are pending parameter writes and you try to close QGC you will get a warning with a yes/no close option.
* Fixed the parameter load errors display when loading from a file.
=> Param progress bar and other stuff

src/PlanView/MissionItemEditor.qml
* Add Delete icon
* Rework command picker visuals to be more understandable as something to click on. Only visuals are changed. Clicking still goes to command picker dialog.
* No changes to hamburger
Related to #7982
=> Plan mission item editor: Delete icon and Command Picker ui

src/AnalyzeView/MAVLinkInspectorPage.qml, src/QmlControls/MAVLinkMessageButton.qml
* Dynamically size message buttons based on max message name width
* Comp id and Hz columns are fixed width, message name is variable
* Also reduced left/right insets on Button to use less space.
Replacement for #8001
=> Mavlink Inspector: Dynamic sizing of message buttons

src/PlanView/FWLandingPatternEditor.qml, src/PlanView/FWLandingPatternMapVisual.qml
* Intermediate glide slope alttitudes are rounded down
* Added "Warning WIll Robinson" stuff
* Fix for #7958
=> FW Landing Pattern: Warn about glide slope altitudes

src/QmlControls/QGCComboBox.qml, src/QmlControls/ScreenTools.qml
Related to #8021 
Before:
After:
=> Tweak combobox visuals

qgroundcontrol.pro, qgroundcontrol.qrc, src/Camera/QGCCameraManager.cc, src/FlightMap/MapItems/MissionItemIndicator.qml, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/MissionControllerTest.cc, src/MissionManager/MissionControllerTest.h, src/MissionManager/MissionSettingsItem.cc, src/MissionManager/MissionSettingsItem.h, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItem.h, src/MissionManager/TakeoffMissionItem.cc, src/MissionManager/TakeoffMissionItem.h, src/MissionManager/VisualMissionItem.cc, src/MissionManager/VisualMissionItem.h, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanView.qml, src/PlanView/SimpleItemEditor.qml, src/PlanView/TakeoffItemMapVisual.qml
* Add contextual Takeoff tool button which will enabled/disabled at appropriate times
* The Takeoff item is now special cased with functionality and visuals
* When a takeoff item is selected it allows you to drag both the Launch (home) and Takeoff locations
* Multi-Rotor will always attempt to keep the Launch and Takeoff location at the same place. They will both update as you drag.
* Fixed-Wing which supports a Takeoff position (PX4 only) will show both Launch and Takeoff draggable locations.
* There is also a massive pile of semantics around home position, when to use the vehicle home position and when not and how to keep them in sync if appropriate
* I've left out a massive list of nuances as to how this works since it's a mile long. Folks will just have to try it out and see if it …
=> Plan: Takeoff tool and Takeoff item support

src/FlightDisplay/GuidedActionsController.qml, src/MissionManager/CorridorScanPlanCreator.cc, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/MissionSettingsItem.cc, src/MissionManager/MissionSettingsItem.h, src/MissionManager/StructureScanPlanCreator.cc, src/MissionManager/SurveyPlanCreator.cc, src/PlanView/MissionSettingsEditor.qml, src/PlanView/PlanView.qml
* Add contextual Land tool
* For fixed wing it adds a Landing Pattern
* For anything else it adds an RTL
* Name is Land or RTL based on context
* FW Landing Pattern removed from Pattern drop down
* KML load removed from Pattern drop down
* Removed 'Mission End RTL' from Mission Start item
* Cleaned up a bunch of waypoint line calc code:
* Rover lines will now link correctly to home as appropriate
* No more waypoint lines after an RTL
* Various link start/end to home fixes
=> Plan: Land tool

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc, src/AutoPilotPlugins/APM/APMHeliComponent.qml
@DonLakeFlyer this updates the Heli Setup for Copter 4.0
=> APMHeliComponent - update for Copter 4.0

src/MissionManager/MissionCommandTree.cc, src/MissionManager/MissionCommandTree.h, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/SimpleMissionItem.cc, src/PlanView/MissionItemEditor.qml, src/PlanView/PlanView.qml, src/QmlControls/MissionCommandDialog.qml, src/QmlControls/ToolStrip.qml
* Waypoint button is contexual and only enabled when appropriate
* Made ROI tool visible. This was always there but hidden behind a magic flag
* Fixed a bunch on other contextual enable/disable bugs
* Fixed a bunch of bugs which related to managing the check state on the Plan ToolStrip
=> Plan: More work on contextual Plan tools

src/FirmwarePlugin/APM/APMParameterMetaData.cc, src/FirmwarePlugin/APM/APMParameterMetaData.h
For ArduPilot there is no reason to dump these into an "Other" category. Since ArduPilot uses the name prefix as the group for parameters with no metadata use the same prefix group and set the category to Advanced.
=> ArduPilot: Group parameters with no metadata correctly

ChangeLog.md, src/FlightMap/MapItems/MissionLineView.qml, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/MissionSettingsItem.cc, src/MissionManager/MissionSettingsItem.h, src/MissionManager/TakeoffMissionItem.cc, src/MissionManager/TakeoffMissionItem.h, src/PlanView/FWLandingPatternMapVisual.qml, src/PlanView/PlanToolBarIndicators.qml, src/PlanView/SimpleItemEditor.qml, src/PlanView/TakeoffItemMapVisual.qml
Given how different firmwares and vehicles deal with takeoff items which do or don't include a location. Trying to explain how this all works now is next to impossible since it's so complicated. The simplest way to explain how it works now is:
* The user is asked to click in the map to set initial location when appropriate. Sometimes that sets launch location, sometimes takeoff location, sometime both!
* The editor drops in/out of wizard mode appropriately
* A fixed wing takeoff which requires a coordinate sets the takeoff item coordinate to be at a 30% climb out from the launch location
=> PLan: Takeoff item user model changes

src/MissionManager/CameraSection.cc, src/MissionManager/MissionController.cc, src/MissionManager/MissionItemTest.cc, src/MissionManager/VisualMissionItemTest.cc
Fixes for #8033:
* Unchecking gimbal yaw changes will correctly update gimbal visuals
* ROI commands will cancel the display of gimbal visuals. Note: This leads to some quirky behavior. Specifically that the waypoint item prior to the ROI command will continue to show gimbal angle display. Which technically is correct, but from and end user standpoint may be confusing.
=> Plan: Fix gimbal yaw visual problems

src/MissionManager/RallyPoint.FactMetaData.json, src/MissionManager/RallyPoint.cc, src/MissionManager/RallyPoint.h, src/MissionManager/RallyPointController.cc
The Rally Point default value is taken from user settings `Default Mission Altitude`.
This PR does the following:
- Take the default value from the `Fact`'s default value if NOT fixed wing. Otherwise use the same behaviour `Default Mission Altitude`
- Rename the misleading `Altitude` to `Relative Altitude` (relative to home altitude)
- Set the default value to `0.0` (use home altitude by default)
=> Set Rally Point default value to 0.0 and get it from Fact's default

src/VideoStreaming/README.md
This small patch fixes gstreamer's command lines for local testing (tested on Ubuntu 18.04/Qt 5.11.3/gstreamer 1.14.4).
=> Fix VideoStreaming/README.md

Jenkinsfile
This is slow, but at least it won't fail due to lack of memory on the build slave.
=> Jenkinsfile: Linux Release (qmake) prevent parallel build

src/QGCApplication.cc
This little change allows QGCApplication::mainRootWindow() to return root window. Until now it was always returning NULL.
=> Fix QGCApplication::mainRootWindow()

src/ui/MainRootWindow.qml
In some cases QGC hangs at exit (on my side - with VA API H.264 decoder on Ubuntu 18.04/Qt 5.11.3/Gstreamer 1.14.5). This little fix changes video manager de-initialization context and that's enough to keep everything happy and working.
=> Fix gstreamer's deadlock on QGC exit

src/VideoStreaming/gstqtvideosink/painters/videomaterial.cpp, src/VideoStreaming/gstqtvideosink/painters/videomaterial.h
This patch fixes YUV 4:2:0 buffer layout handling issue which is visible as green or colored bars on the screen in certain cases. On my side it is easy to reproduce if VA API H.264 decoder is used in 1080p mode (Ubuntu 18.04/Qt 5.11.3/Gstreamer 1.14.5).
=> Fix YUV 4:2:0 plane rendering in certain cases

src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentPlane.qml, src/QGCApplication.cc, src/QGCApplication.h, src/QmlControls/QmlObjectListModel.cc
Brings back fix for the advanced tuning crash without the side effect of application closing on MessageBox closing.
It seems that the `QGuiApplication::lastWindowClosed` signal is triggered in our QML application if we spawn an widget (DialogBox) from QML. This PR disconnects the signal from `QCoreApplication::quit` slot.
Also enable advanced tuning option that was removed temporary
Condition to keep using `QGuiApplication` on mobile is due to untested behaviour for some corner cases on mobile with `QApplication`. However, Advanced Tuning with charts works on mobile 
Original PR that had side effects: https://github.com/mavlink/qgroundcontrol/pull/7978
Fixed side effects: https://github.com/mavlink/qgroundcontrol/issues/7962
=> Fix advanced tuning without side effects

.vagrantconfig.yml, Vagrantfile
Big usability improvement is the writing out of scripts to do the install.
Running `./do-make.sh` allows easy incremental building for those that don't do it every day.
=> Vagrant updates

src/VehicleSetup/Bootloader.h, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h, src/comm/USBBoardInfo.json
Added support for the ModalAI FC v1 (this will also will cover VOXL-Flight board).
Tested with boot loader update: https://github.com/PX4/Bootloader/commit/d83169d50c333ab33d8206a8a29f6efc9605c39b
=> Add support for ModalAI FC v1 FW Update

src/FactSystem/FactControls/AltitudeFactTextField.qml, src/Settings/PlanView.SettingsGroup.json, src/Settings/PlanViewSettings.cc, src/Settings/PlanViewSettings.h
Reduce confusion with vehicle based terrain following mavlink support:
Related to #8087.
=> Warn about Above Terrain usage

src/FirmwarePlugin/FirmwarePlugin.cc, src/ui/toolbar/VTOLModeIndicator.qml
* Order is now Arm/Disarm, Flight Mode, VTOL, ...
* VTOL Indicator is changed to be a combo to match other controls. Also changed wording to use less space.
Fix for #8085
=> Toolbar indicators: Change order, Change VTOL indicator

src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/FlightDisplayViewMap.qml, src/FlightDisplay/FlightDisplayViewWidgets.qml, src/PlanView/PlanView.qml, src/QmlControls/ToolStrip.qml
* Toolstrip is now flickable. Need this for PlanView since it was getting so tall. Would never fit on small laptops/tablet/... Fixed maxHeight values in Plan/Fly usage to make it work correctly.
* Fixed up a bunch of inconsistent margins for tools on the edge of views.
* Made the tool boundary margins a tad smaller
* Fixed #8103. Terrain and Map Scale panel now anchor to the right of the tool strip so they access to full height for visuals
=> Make Toolstrip flickable, fix maxHeight, fix bunch of margins

src/QmlControls/QGCToolBarButton.qml, src/QmlControls/SubMenuButton.qml, src/VehicleSetup/SetupView.qml, src/ui/AppSettings.qml, src/ui/MainRootWindow.qml, src/ui/toolbar/MainToolBar.qml
Previously the right side dialogs were parented to the child window the came from. Now they are parented to the main window. This causes a new problem when the right dialog pops up from a validation error. The same basic problem has always existed though when changing pages within a view like Settings pages. The nice thing is that the new way right dialogs are rooted to mainWindow makes it way easier to fix.  For example this sequence:
* App Settings/General
* Type -10 into Default Mission Altitude. Don't move focus away
* Click on any other App Settings button (or switch views from the toolbar)
* The view will switch and you will be left with a either a screwed up validation dialog or a validation dialog showing over the wrong view
In order to fix this there is a new …
=> View switch prevention support

src/VehicleSetup/SetupView.qml, src/ui/AppSettings.qml, src/ui/MainRootWindow.qml, src/ui/toolbar/MainToolBar.qml
The prevent view switching methods are all on mainWindow:
* pushPreventViewSwitch() - Call to prevent a view switch, should have a matched popPreventViewSwitch
* popPreventViewSwitch() - Matching call to pop the prevent view switch stack
* preventViewSwitch() - Return true if view switching should be prevented. This is already used in all the right places to prevent view switching. Implementors of things like individual setup pages shouldn't need to call this.
I've changed the current usage over to these new methods. But I have not used them inside any of the setup pages yet. Example usage would be:
* Radio Component
* When the user starts a calibration pushPreventViewSwitch() should be called
* When the user finishes/cancels the calibration popPreventViewSwitch() should be called
Support …
=> Prevent view switching apis support a stack

src/FlightDisplay/FlightDisplayView.qml, src/PlanView/PlanView.qml
These were added for a specific custom build. I'm wrapping up stable and they need to go now since they still have not been implemented correctly. I've commented out what I could so they can be put back correctly.
=> Remove Fly/Plan from toolstrips

src/QGCConfig.h, src/ui/preferences/GeneralSettings.qml
This: https://github.com/mavlink/qgroundcontrol/commit/5683020f93611b0ed99f2ba8cde10087a1d0002f
It changed the map type from a number to a string. This causes QGC to not know what to load as a default map type when launching with an old settings file.
=> Bump settings version

src/AnalyzeView/AnalyzeView.qml
Otherwise, "Log Download" remains the only selected button:
=> Must manually check the button when clicked.

src/FlightMap/MapItems/MissionItemIndicator.qml, src/MissionManager/MissionController.cc, src/MissionManager/VisualMissionItem.cc, src/MissionManager/VisualMissionItem.h
Fix for #8096.
This way if you have a command which does not specify a location after a waypoint and you select that command as current, the waypoint before will show as selected. This allows you to figure out where that command takes place in the mission flow.
=> Plan: When a child item is current show the parent as selected

src/PlanView/MissionItemStatus.qml, src/PlanView/PlanView.qml, src/QmlControls/MissionItemIndexLabel.qml
* The bottom status panel in the Plan View shows sequence number. This can be used if you get a warning about a specific item number to know which one it is.
* You can click on the items in the panel to set the current item
Related to #8098, #8119
=> MissionItemStatus: Show seq nums, clickable selection

src/AutoPilotPlugins/APM/APMHeliComponent.qml, src/FirmwarePlugin/APM/APMParameterFactMetaData.Copter.4.0.xml
@DonLakeFlyer this PR is for a change in heli parameter name from IM_STAB_COL_x to IM_STB_COL_x for the heli setup that was done by @bnsgeyer for ArduPilot.
The current XML database for APM Copter 4.0 does not have that change pulled into it yet. But I am submitting the PR to reflect that change in the ArduPilot code so it is compatible when the XML is updated.
These are the reference commits in ArduPilot that this PR is based on:
https://github.com/ArduPilot/ardupilot/commit/c8572502aacd83fea16d47ccf8a42095df6069ec
https://github.com/ArduPilot/ardupilot/commit/e10e63698fec2dad109db680ff087dc174b12edf
=> APM Heli Setup change for parameter name

src/FlightMap/FlightMap.qml, src/PositionManager/PositionManager.cpp, src/PositionManager/PositionManager.h
The quality of a GCS heading which comes from a calculated location and/or an internal GPS is low quality unless the GCS is moving position above a certain speed. When below that heading is just random. We don't want to random gcs headings to be displayed on the Fly view.
This will eventually be fixed to do possibly both of these things:
* Detect movement speed above a certain threshold at which point the heading is valid.
* Use a devices compass (if available) for gcs heading
=> Don't show GCS heading unless it comes from plugin

QGCCommon.pri, src/AnalyzeView/MAVLinkInspectorController.cc, src/AnalyzeView/MAVLinkInspectorController.h
* Enable charting on Android 32-bit
* Skip message parsing if the message is not being consumed.
* Work around message disassembly issue on ARM 32-bit.
* Fix memory leaks.
Two charts, six series running on a 6-year-old, dual core Nexus 9 (Android 32-bit):
=> Continue work on MAVLink Graphing

src/FirmwarePlugin/FirmwarePlugin.h, src/Joystick/Joystick.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
You can implement ```FirmwarePlugin::extraJoystickFlightModes``` to support this. The usage case is where a custom build limits the flight modes availbel to the user from the Fly View but wants to add more modes for joystick buttons. This typically happens for vehicles which normally fly without a controller. For the Fly View you don't want any flight modes shown which are controller oriented. But then when you use a Joystick you want some of those back
=> Allow plugin to add flight modes to joystick button actions

src/ShapeFileHelper.cc, src/ShapeFileHelper.h
Got this error while compiling master branch with Qt 5.14.0 in macOS
=> ShapeFileHelper: Fix incomplete type QVariant error

CMakeLists.txt
=> cmake: Include Qt5QGConfiguration before QT_VERSION variable usage

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
QGC will now wait 30 seconds before issuing a new (spoken) low battery warning. When the low battery reaches 50% of the threshold, the delays go down to every 15 seconds.
The original code had the announcement go out for every percentage change, which could turn into a stream of spoken messages on top of each other.
Closes #8232
=> Add a timer in between low battery warning messages.

src/uas/UAS.cc, src/uas/UAS.h
The joystick messages (set_attitude_target, set_position_target_local_ned, etc.) were being throttled by the `UAS::setExternalControlSetpoint()` function when the sending functions are also controlling the frequency rate. That was causing issues where the message rate was all over the place. These message should go out on a constant rate, regardless if things changed or not.
=> Let the sender control the joystick message rate.

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
You don't always have the "home" position coordinates. This keeps track of the position where the vehicle was armed.
=> Keep track of armed position

src/QmlControls/QGCComboBox.qml, src/QmlControls/ScreenTools.qml, src/Settings/App.SettingsGroup.json, src/ui/preferences/GeneralSettings.qml
All sizing in QGC is based off the size of a single character using the system default font. The logic being that the size, in pixels of a same letter using a same font should be equivalently readable in all platforms.
Under General Settings, you can change this value, which in turn scales the entire UI up or down. The original entry under General Settings was "Font Size". From a user perspective, that doesn't make a whole lot of sense as nobody knows the intrinsic relationship between the font size and UI size.
This PR changes the terminology from _Font Size_ to _UI Scaling_. It also changes what the user sees. Instead of changing the font size (one integer at a time), the UI now shows a percentage value. When the current font size matches the default (for that given platform), you will …
=> UI Scaling

src/Vehicle/TrajectoryPoints.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
Update from within the new TrajectoryPoints handler.
This was lost when moving the handling the the trajectory points from within the vehicle.
Fixes #8253
=> Update flight distance

src/VideoStreaming/VideoReceiver.cc
This trivial patch fixes not obvious double EOS handling issue. It was visible as constant RTSP stream restart after changing streaming URL (UDP => RTSP for example).
=> Fix double EOS handling

src/FlightMap/Widgets/VideoPageWidget.qml
Since gstreamer is enable, we can record and do mostly everything
=> VideoPageWidget: Enable camera control if using gstreamer

src/QGCApplication.cc, src/VideoStreaming/VideoStreaming.cc, src/VideoStreaming/VideoStreaming.h
Every single line of this function is commented out, and the
documentation of GStreamer says that it's uneeded.
=> Remove unused function

src/VideoStreaming/VideoStreaming.cc
It is quite useful if you set your gstreamer debug settings in QtCreator or environment and do not want to depend on QGC settings state (they are reset to default sometimes, for example).
This small change greatly simplifies my life. If other guys find it useful too then why not to have that in master?
=> Allow developers (or advanced users) to override gstreamer debug settings

src/AirspaceManagement/AirspaceManager.cc, src/AnalyzeView/LogDownloadController.cc, src/Camera/QGCCameraControl.cc, src/FlightDisplay/VideoManager.cc, src/QtLocationPlugin/QGCMapEngine.cpp, src/QtLocationPlugin/QGCMapEngineData.h, src/QtLocationPlugin/QGCMapTileSet.cpp, src/Vehicle/MAVLinkLogManager.cc, src/VideoStreaming/VideoReceiver.cc
Fix #8247 
> The C++ language guarantees that delete p will do nothing if p is null. Since you might get the test backwards, and since most testing methodologies force you to explicitly test every branch point, you should not put in the redundant if test.
=> Remove unnecessary pointer check before delete 

qgroundcontrol.qrc, src/FlightDisplay/DefaultChecklist.qml, src/FlightDisplay/FixedWingChecklist.qml, src/FlightDisplay/MultiRotorChecklist.qml, src/FlightDisplay/PreFlightCheckList.qml, src/FlightDisplay/RoverChecklist.qml, src/FlightDisplay/SubChecklist.qml, src/FlightDisplay/VTOLChecklist.qml, src/api/QGCOptions.h
It's back and it's no longer generic. There is a model for each vehicle type:
* Fixed Wing
* Multirotor
* Rover
* Submarine
* VTOL
If these checks fail, it will load a generic preflight checklist.
Note that I've only trimmed the "Generic" check list when creating the individual models. Someone with actual experience using those should come and properly fill in the required/desired check list items.
A custom build can override the (QGCCorePlugin) method collecting the URI to the checklist (the main loader) and completely customize it if they want.
=> Bringing preflight checklist to mainline QGC

src/Vehicle/BatteryFact.json, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
This is a fix for #8190.
* Fixed support for usage of BATTERY_STATUS and SYS_STATUS messages to get correct battery 1 and battery 2 values.
* Remove cellCount as a value available to BatteryFactGroup since it can't be calculated correctly.
=> Battery status fixes

.gitmodules
I'm having issues cloning https://gitlab.freedesktop.org/andrew.voznytsa/gst-plugins-good. There seems to be a github mirror (https://github.com/GStreamer/gst-plugins-good), but it's missing the commit qgc is currently pointing at (9d782fad9dc). https://github.com/GStreamer/gst-plugins-good/compare/9d782fad9dc0384ba86ecae64511c193f6149f93...c00796eaa5fb5fde271fd1081f5fab57b970e428
When it's possible to clone https://gitlab.freedesktop.org/andrew.voznytsa/gst-plugins-good again let's get it pushed to a branch on a fork we can control (https://github.com/mavlink/gst-plugins-good).
=> use mavlink fork of gst-plugins-good

CMakeLists.txt
Should this be tied to actual requirements?
=> cmake enable mavlink inspector by default

src/comm/MAVLinkProtocol.cc
Fix for #8203
MAVLinkProtocol had code which would downgrade the link to mavlink 1 based on the firmware of the MAVLINK_MSG_ID_RADIO_STATUS packet. This doesn't work because ArduPilot SiK Radio firmware always sends MAVLINK_MSG_ID_RADIO_STATUS as a mavlink 1 packet, even if the vehicle is sending mavlink 2.
=> Disable SiK Radio mavlink 1 downgrade code

src/AnalyzeView/LogDownloadController.cc, src/AnalyzeView/LogDownloadController.h
Change log download to infinite retries on data download. If things go haywire and data stops coming across the data transfer rate will fall to 0 and the user can cancel. This should make it work even on really lossy connections.
Fix for #5950
=> Infinite retries to log download

src/Vehicle/Vehicle.cc
This sets the datetime format to a format easier for the spreadsheet software to interpret.
Before this patch, it prints "tue sep 3 11:32:36 2019"
=> Vehicle: Change date format in csv output

qgroundcontrol.pro, src/AutoPilotPlugins/APM/APMMotorComponent.cc, src/AutoPilotPlugins/APM/APMSubMotorComponent.qml, src/AutoPilotPlugins/APM/APMSubMotorComponentController.cc, src/AutoPilotPlugins/APM/APMSubMotorComponentController.h, src/AutoPilotPlugins/CMakeLists.txt, src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
This adds support for the new ArduSub 4.0 feature of automatically detecting the thrusters directions and reverting the corresponding motor output if necessary.
It currently looks like this:
=> Support automatic Thruster direction detection in Ardusub

src/QmlControls/PreFlightCheckModel.qml
Added a property to the PreFlightCheckModel to enforce checklist order.
This can be set to `false` by a custom build that wishes to see all checklist subsections and complete them in any order.
=> Enforce checklist order property

src/QmlControls/MainWindowSavedState.qml, src/api/QGCOptions.h
Expose API to prevent QGC from saving the application window size and position on close (or restoring it on open). This is used on custom builds where the window position and size is controlled elsewhere (running Linux on a tablet for instance).
=> Control main window size/position save/restore.

src/QGCPalette.cc, src/QGCPalette.h, src/QmlControls/PreFlightCheckButton.qml, src/QmlControls/PreFlightCheckGroup.qml, src/QmlControls/SectionHeader.qml
This PR adds 3 new colors to the QGC palette:
- statusFailedText
- statusPassedText
- statusPendingText
These colors default to the standard `text` color, but are provided such that a custom build can override them. This PR also adds a small amount of logic to differentiate passed, failed, and pending checklist groups by introducing a `failed` property to the `PreFlightCheckGroup` QML type.
=> Support for checklist status text color

src/FlightMap/FlightMap.qml
This happens when using some QtQuick.Controls 2.x controls. I filed a bug with Qt and got a "work around" from it:
https://bugreports.qt.io/browse/QTBUG-82185
Fixes https://github.com/mavlink/qgroundcontrol/issues/7976
Fixes https://github.com/mavlink/qgroundcontrol/issues/8293
I'm starting with this PR alone. Subsequent to this I will be pushing another PR restoring proper QtQuick versions to something more current.
=> Work around for random rectangles over maps

.travis.yml
* I created custom tarballs for armv7 and adm64 android gstreamer install and pushed them up to S3.
* Individual tarballs for each version speed up download times.
* There is a script to do this: https://qgroundcontrol.s3-us-west-2.amazonaws.com/dependencies/gstreamer-1.0-android-universal-1.14.4.tar.bz2
* Fix for #8283
Contents of script:
```
#!/bin/bash
#
#
set -e
mkdir gstreamer-1.0-android-universal-1.14.4
#wget https://gstreamer.freedesktop.org/data/pkg/android/1.14.4/gstreamer-1.0-android-universal-1.14.4.tar.bz2
tar -jxf gstreamer-1.0-android-universal-1.14.4.tar.bz2 -C gstreamer-1.0-android-universal-1.14.4
mkdir gstreamer-1.0-android-armv7-1.14.4
cp -r gstreamer-1.0-android-universal-1.14.4 gstreamer-1.0-android-armv7-1.14.4/.
rm -rf …
```
=> Use new tarballs for android gstreamer

src/comm/QGCMAVLink.h
mavlink as submodule contains more warnings than particles in the universe.
This results in a terrible experience for developers, since it makes harder to find
real warning messages for QGC.
=> QGCMAVLink: Remove mavlink warnings

src/AutoPilotPlugins/APM/APMFollowComponent.FactMetaData.json, src/AutoPilotPlugins/APM/APMFollowComponent.qml, src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FollowMe/FollowMe.cc
Initial starting point is this:
When you click Enable for the first time you get this:
This is due to the fact that the default value set by the firmware are not usable by QGC setup. You can also end up here if you futz parameters in the parameter editor and then to go this page. Clicking 'Reset To Supported Settings' will set things up to a decent set of workable defaults.
Which then gets you here:
I'm hoping this is all self explaining.
Then to active Follow Me you change to Follow Me flight mode.
Some important things to note:
* The height you are specifying is a relative height above launch/home position.
* If you are using a mode which requires a heading from the gcs then you may need to walk in a specific direction for a short distance such that the gcs gps has a valid heading to …
=> ArduPilot: Change follow to work above home altitude only

src/FlightDisplay/PreFlightBatteryCheck.qml
When no battery is connected PX4 reports NaN as the battery percent remaining. This causes the preflight battery check to pass when it shouldn't. This fixes it.
=> Fix PreFlightBatteryCheck issue with NaN

src/comm/QGCMAVLink.h
MSVC warns about not identified pragmas, Clang shares the same pragma as GCC
=> QGCMAVLink: Add compiler check to avoid pragma warnings

src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
ArduSub doesn't have this parameter, this gets rid of the "missing param" warning.
Fix #8319
=> Don't report missing parameter FRAME_CLASS

src/comm/QGCMAVLink.h
=> QGCMavlink: Add GCC version check to use address-of-packed-member

src/QGCApplication.cc, src/VideoStreaming/README.md, src/VideoStreaming/VideoStreaming.cc, src/VideoStreaming/VideoStreaming.h
Trying to make VideoReceiver stuff more QGC-like/consistent - switched gstreamer to use QT logging system if GST_DEBUG and other debug related environment variables are not set (also works on Android/iOS without any extra efforts - just use UI to tweak logging).
If GST_DEBUG is set then gstreamer can be configured to log in its native way. This mode is useful for these who work with gstreamer or who is helping to trace gtsreamer issue.
=> Switch gstreamer to use Qt log API by default

src/AutoPilotPlugins/APM/APMSubMotorComponent.qml
timer.start() and timer.stop() were breaking the 'running' binding of
the timer, so the timers could still run when switching to the fly view.
With these changes, changing view properly disables the timers.
=> APMSubMotorComponent.qml: fix broken timer binding

src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/GuidedActionsController.qml, src/FlightDisplay/PreFlightCheckList.qml
This PR accomplishes 3 things:
1. Checklist logic for `_canArm` when using **enforceChecklist** has moved to the GuidedActionsController. This allows the Flight View to properly catch the signals that depend on the preflight checklist (canArm, startMission, etc)
2. Updating of the `Vehicle.checkListState` in the PreFlightCheckList from the `onAllChecksPassedChanged` signal, as opposed to the `onVisibleChanged` signal. 
3. Added a timer with a 1 second delay to forcing opening the checklist when navigating to the Flight View if using **enforceChecklist**. This timer also triggers closing the checklist once complete.
=> Fixed interactions between PreFlightCheckList and the FlightView

src/VideoStreaming/VideoStreaming.cc
It had to be a part of https://github.com/mavlink/qgroundcontrol/pull/8363 ...
Fixes https://github.com/mavlink/qgroundcontrol/issues/8281
=> Fix DISABLE_VIDEOSTREAMING build (again)

src/MissionManager/MissionController.cc
Arrow draw starts from second segment instead of first. This prevent a random arrow being drawn between the home position and a takeoff item which might be right above it. Leading to an flight direction arrow which points in a random direction.
=> Plan: Avoid arrow positioning with takeoff item

src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoStreaming.cc, src/VideoStreaming/VideoStreaming.pri
This is critical to get MPEG-2 TS support on Android and iOS (bug in latest 3.x stable).
=> Fix MPEG-2 TS support on Android and iOS

src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoStreaming.cc
This patch aims to clean up logging at video receiver side and match with scheme used by QGC.
=> Use VideoReceiverLog category for video streaming stuff

Vagrantfile
xenial fails with this error:
default: Project ERROR: gstreamer-gl-1.0 development package not found
bionic64 just works.  So move to it :-)
=> Vagrant: move to bionic64

src/FirmwarePlugin/FirmwarePlugin.h, src/PlanView/PlanView.qml
This makes Plan view using the same capability bit as Fly view for ROI support. I've left the bit set on only for multi-rotor which isn't technically correct. But closer to vehicle majority usage.
Replacement for #8337.
@dakejahl So to turn off ROI support fully in Sentera custom you remove the ROI capability in the Sentera firmware plugin override.
=> Drive Plan view ROI support from firmware capability bits

src/MissionManager/CameraCalc.cc, src/MissionManager/SurveyComplexItem.cc
* Call was made to isManualCamera before the camera name was loaded. Causing it to base decisions on previous camera name. Which would in turn cause Manual camera Preset load to fail.
* Added Internal Error message display for preset load failures.
* Fix for #8398
=> Fix CameraCalc loading

src/FactSystem/FactControls/AltitudeFactTextField.qml, src/PlanView/CorridorScanEditor.qml, src/PlanView/SurveyItemEditor.qml
* Most folks live in relative altitudes. So it's very noisy to show that all the time.
* Now only the non relative modes will show a special label.
* Fixed bugs in Survey/Corridor with respect to correctly setting altitude mode
=> Altitude Text fields: Don't show (Rel) additional units label all the time

src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
This patch fixes two issues:
1. handle gstreamer signals on main QGC thread to avoid deadlock (and removes TCP probe workaround which did not really work well for Microhard modems)
2. removes video sink from pipeline if pipeline failed to start, to allow next streaming start attempt succeed
=> TCP probe and pipeline re-initialization fix

src/FlightMap/Widgets/MapFitFunctions.qml
* When an item is in an intermediate state (wizard not complete) the coordinate for it may be NaN. Which was confusing the map fit functions causing the map to zoom fully out and move to 0,0 to fit it.
* Fix for #8415
=> Map Fit: Skip invalid coords

src/MissionManager/ComplexMissionItem.cc, src/MissionManager/ComplexMissionItem.h
This allows developers to optionally save a Survey Preset as a JSON file when selecting "Save preset" in the Survey Plan. 
This JSON files end up in the "Missions" directory, where you can just copy/paste them into your source tree and include them in your custom build.
```
<qresource prefix="/foo">
<file alias="bar.json">patch/bar.json</file>
</qresource>
```
The from C++ file load code is `":/foo/bar.json"`
=> Compiler switch for Survey Preset JSON generation

src/FlightDisplay/PreFlightCheckList.qml
Rather than using the DefaultChecklist when no vehicle is connected, we can first check to see if we have an idea about which vehicle type is expected by first checking **QGroundControl.settingsManager.appSettings.offlineEditingVehicleType**
=> Preflight checklist when no vehicle is connected

src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
This patch reverts https://github.com/mavlink/qgroundcontrol/pull/8406 due to https://github.com/mavlink/qgroundcontrol/issues/8436 - at least things won't be worse than before. Proper fix (will be available in 2-3 days) will change many things in radical way. I'm not yet sure that it will be good to merge proper fix into 4.0.
=> Revert PR #8406

deploy/qgroundcontrol_installer.nsi
The uninstall step prior to install was not waiting to complete. Which led to the uninstaller running at the same time as the installer. Which could lead to some files missing from the install.
=> Windows uninstall race condition

src/QGCApplication.h, src/Settings/VideoSettings.cc, src/Settings/VideoSettings.h, src/VideoStreaming/VideoManager.cc, src/VideoStreaming/VideoManager.h, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h
The VideoReceiver should work 'as is', without depending on the
whole application or in the settings. This patch removes all the
hard dependencies on QGroundControl, FactSystem and Settings system
so it's easier to isolate and test the code.
=> Remove QGCApplication and VideoSettings from the VideoReceiver

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
* Fix protocol negotation to handle setting mavlink v2 from capability bits when appropriate
* Add retries if AUTOPILOT_VERSION message is not received.
Related to #8440
=> Added correct handling of mavlink 2 change based on capability bits

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
ArduPilot takes a full 5 seconds before it will send AUTOPILOT_VERSION. Previous code used a retry count which wasn't high enough hence it would fail out. Change to wait for 10 seconds and then fail.
=> Give up on getting AUTOPILOT_VERSION based on time now retry count.

CMakeLists.txt, src/VideoStreaming/VideoStreaming.pri
This small patch fixes https://github.com/mavlink/qgroundcontrol/issues/8282
Also updated cmake files - works for me on Linux but not sure about something else like Windows - IMO they won't work without full msys environment.
=> Parallels build fix

src/MissionManager/MissionManagerTest.cc, src/MissionManager/MissionManagerTest.h, src/MissionManager/PlanManager.cc, src/MissionManager/PlanManager.h, src/Vehicle/Vehicle.cc, src/comm/MockLink.cc, src/comm/MockLink.h, src/comm/MockLinkMissionItemHandler.cc, src/comm/MockLinkMissionItemHandler.h
* Now includes item sequence number as well as command name
* Better structuring of the error string information for readability
* Create unit test to test the error string output
Above is an example of the current sate of mission transfer error reporting. It is pretty much useless. No information on which item this applies to. No clue as to what the command is that is causing the problem. And that's just a start.
=> Plan: Much better error reporting for mission transfer errors

src/Vehicle/CMakeLists.txt
CMake failed because of lack of TerrainFactGroup and TerrainProtocolHandler
=> Add new files to the cmake so project builds

src/MissionManager/CameraSectionTest.cc, src/MissionManager/FWLandingPatternTest.cc, src/MissionManager/MissionController.cc, src/MissionManager/MissionItemTest.cc, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItem.h, src/MissionManager/SimpleMissionItemTest.cc, src/MissionManager/TakeoffMissionItem.cc, src/MissionManager/TakeoffMissionItem.h, src/MissionManager/TransectStyleComplexItem.cc
The terrain ready indication was incorrect when you loaded back a Plan file a file which included terrain based heights. This is incorrect since the Plan file has all the information needed including terrain heights and absolute heights. Since it was wrong, it would prevent you from uploading until the terrain heights were downloaded again. Which could be a real problem if you are at the field with no internet.
=> Plan: Correct handling of terrain ready when loading back from file

src/Camera/QGCCameraControl.cc, src/FlightDisplay/FlightDisplayViewVideo.qml, src/FlightMap/Widgets/VideoPageWidget.qml, src/VideoStreaming/SubtitleWriter.cc, src/VideoStreaming/SubtitleWriter.h, src/VideoStreaming/VideoManager.cc, src/VideoStreaming/VideoManager.h, src/VideoStreaming/VideoReceiver.cc, src/VideoStreaming/VideoReceiver.h, src/VideoStreaming/gstqgcvideosinkbin.c
This patch switches VideoReceiver to new API according to https://docs.google.com/document/d/1ln5vHZwMtRqzatwW2gQ9whNk8Vd9D7_GsRSeQNCXXbA/edit#
In addition to new API it brings fixes (MPEG2-TS recording; will bring it into 4.0 as separate patch), better watchdog (less useless restarts if streams is connected, less video flickering), no code duplication between VideoManager and VideoReceiver, a bit simplified SubtitleWriter and many other minor tweaks.
This patch is squashed version of https://github.com/andrewvoznytsa/qgroundcontrol/commits/wip-video-receiver-api-update
Known issues/notes:
1. Due to dynamic video sink handling (add/remove in run time) I had to disable video synchronization. You may see strange effects if you receive video with enabled frame reordering. I need to check …
=> Switch VideoReceiver to new API (big refactoring)

src/VideoStreaming/VideoReceiver.cc
1. Fixes H.265 handling (https://github.com/mavlink/qgroundcontrol/pull/8527)
2. Fixes MPEG-2 TS recording (part of https://github.com/mavlink/qgroundcontrol/pull/8529 work)
=> Backported fixes

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
If the vehicle failed to change flight mode it would say: "Unable to start mission. Vehicle not ready." which is worse than useless. Change to say ".. Vehicle not changing to Mission flight mode."
I just tran into this case in SITL testing.
=> Start Mission: Better error message

src/Terrain/TerrainQuery.cc
It seems there is a typo in TerrainAirMapQuery::_parseCarpetData, maxHeight should be initialized by the 'max' value from json.
=> Fixed typo in TerrainAirMapQuery::_parseCarpetData

src/MissionManager/VisualMissionItem.cc
In existing code there is no need to check specifiesCoordinate() and coordinate().isValid(), because they are always true. I assume the correct logic should be like that (start timer if expression is true or set _terrainAltitude to NaN otherwise).
=> Fixed suspicious if-expression

src/Settings/Video.SettingsGroup.json, src/Settings/VideoSettings.cc, src/Settings/VideoSettings.h, src/Vehicle/Vehicle.cc, src/VideoStreaming/VideoManager.cc, src/VideoStreaming/VideoManager.h, src/VideoStreaming/VideoReceiver.cc, src/ui/preferences/GeneralSettings.qml
This setting disables the rtpjitterbuffer and sets the videosink to non-sync (assynchronous? mode. This reduces the latency here from ~380ms to ~200ms.
@jaxxzer can you please test?
=> Add Low latency mode for video

src/MissionManager/VisualMissionItem.h
terrainCollision property is a boolean value, but signal's parameter is double - it has to be bool too.
=> Set correct parameter type for signal

src/MissionManager/VisualMissionItem.cc
Using != operator is not a way to go for comparing double values. Moreover, qFuzzyCompare is already widely used in the file, so the fix would be good for keeping consistency too.
=> Replaced not equal operator for double values to qFuzzyCompare

src/PlanView/MissionItemStatus.qml
Been meaning to do this for ages:
* Item indices are vertical so they don't overlap
* You can click anywhere in vertical area to select item
* Fix for #8559
=> Plan - Terrain Status: Vertical index display. Click anywhere in bar.

src/FlightMap/MapItems/MissionItemIndicator.qml, src/QmlControls/MissionItemIndexLabel.qml
* After feedback from multiple sources on the reason why sequence numbers need to be shown in the map items I brought them back. They now show like they used to for items in the map. 
* The main complaint which isn't solvable in some other way it that the numbering is needed for discussion around
* The Plan item editors continue to not show item numbers.
=> Bring back visual sequence number in map item indicators

src/FollowMe/FollowMe.cc
Currently it looks like GCS motion reports will only be sent to vehicles that are in the appropriate "Follow" mode even when the "Stream GCS Position" setting is "Always". I've confirmed that GCS motion reports (FOLLOW_TARGET mavlink messages) aren't received using 4.0.4, whereas they were in version 3.5.6, when in a non-follow mode.
This PR should fix the issue. I haven't been able to fully test it as I'm not set up to build on Android and don't have a GPS I can use on my development machine.
=> FollowMe: Fix "Always" settings for streaming GCS position

src/MissionManager/PlanManager.cc
=> ArduPilot: Only force MISSION_ITEM_INT if vehicle support bit is set

src/ui/MainRootWindow.qml
In response to https://github.com/mavlink/qgroundcontrol/issues/8486
I'm using an arbitrary minimum size where the UI _mostly_ fits. Needs testing on other platforms. Especially when connected to low DPI monitors.
Closes #8486
=> Adjust minimum application window size

src/MissionManager/MissionController.cc, src/MissionManager/TransectStyleComplexItem.cc
* This essentially backs out the change to fix #8023. The correct fix for this is way more complex than I originally thought. And the existing code was buggy and causing crashes. Not possible to deal with in current stable. Will have to wait for point release.
* Fixed item sequence numbering problem for incomplete items. This could cause more than one item to have the same sequence number. Which would in turn cause things like multiple items being marked as current at the same time.
=> Plan: Remove display of incomplete item line connections

src/qgcunittest/MultiSignalSpy.cc
Result of 'new' operator can't be nullptr - we don't need to check that.
=> Removed checking pointer after 'new' operator

src/comm/QGCJSBSimLink.h, src/comm/QGCXPlaneLink.h
Originally sensorHilChanged() was emitted every time enableSensorHIL() was called.
However, we need to emit signal only when the value was changed.
=> Emit sensorHilChanged signal only if it was really changed

src/AutoPilotPlugins/APM/APMCompassCal.cc
The 'rejected' variable is always false, so code under if (rejected) will be never executed.
=> Removed unreachable code

src/VehicleSetup/Bootloader.h, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h, src/comm/USBBoardInfo.json
- UVify Core board support is implemented.
=> Add UVify Core in the firmware downloader.

src/VideoReceiver/GStreamer.cc
From Qt docs: https://doc.qt.io/qt-5/qtglobal.html#qEnvironmentVariableIsEmpty
=> Removed unnecessary memory allocation

src/AutoPilotPlugins/Common/RadioComponentController.cc, src/AutoPilotPlugins/Common/RadioComponentController.h, src/Vehicle/Vehicle.h, src/VehicleSetup/Bootloader.cc, src/VehicleSetup/JoystickConfigController.h
Warning message:
```
warning: 'start' is deprecated: Use QElapsedTimer instead
```
=> Remove deprecated QTime::start function and use QELapsedTimer

src/MissionManager/FixedWingLandingComplexItem.cc, src/MissionManager/FixedWingLandingComplexItem.h, src/MissionManager/MissionController.cc, src/PlanView/FWLandingPatternMapVisual.qml
* Dragging Landing position will maintain distance and heading
* Dragging Loiter position will only adjust angle
* Distance/Glide Slope is now only adjust from the item editor values
Fix for #8623
=> Plan FW Landing: Drag of land/loiter maintains land distance/heading as appropriate

src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/CorridorScanComplexItem.h, src/MissionManager/QGCMapPolygon.cc, src/MissionManager/QGCMapPolygon.h, src/MissionManager/QGCMapPolyline.cc, src/MissionManager/QGCMapPolyline.h, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/StructureScanComplexItem.h, src/MissionManager/SurveyComplexItem.cc, src/MissionManager/SurveyComplexItem.h, src/PlanView/CorridorScanEditor.qml, src/PlanView/FWLandingPatternEditor.qml, src/PlanView/MissionItemEditor.qml, src/PlanView/SimpleItemEditor.qml, src/PlanView/StructureScanEditor.qml, src/PlanView/SurveyItemEditor.qml
How things used to work:
* When you created a plan from a template say like survey...
* You would get a red Takeoff item (and others) which indicated it was incomplete. It told you what to futz and then to click "Done Adjusting" when done. At which point the editor switches back to normal editing mode.
* Same thing for items which required you to set up a Polygon/Polyline. 
* When you clicked "Done Adjusting" it would automatically move you to the next incomplete item as well. In this case that would be the Survey item
Problems:
* When you clicked to position the takeoff item. You then clicked "Done Adjusting" which in fact wasn't correct. You may need to still adjust the altitude for example. So you aren't really "Done Adjusting".
* Also the fact that when you clicked "Done Adjusting" it …
=> Plan: New wizard done model

src/QGCToolbox.cc
`QGCCorePlugin` is currently constructed with a `QGCToolbox* toolbox` parameter of null. This is because at the time `QGCCorePlugin` (or an actual custom plugin) is constructed app->toolbox() is null.
`QGCCorePlugin` is created in `_scanAndLoadPlugins()`, which is called as part of the QGCToolbox constructor where all toolbox classes use the same format:
`_class = new Class(app, this);`
The creation of `QGCCorePlugin `should follow the same pattern.
The practical issue I had with this is that because the parent is not set correctly, `QGCCorePlugin `is not destructed when the app is closed. This means any code in the destructor is not run. (QGCCorePlugin itself has as a destructor which is currently not being called).
=> Correctly set parent of QGCCorePlugin

src/QtLocationPlugin/QGCMapEngine.cpp, src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc, src/comm/TCPLink.cc
from the warning message:
```
note: 'sprintf' has been explicitly marked deprecated here
QT_DEPRECATED_X("Use asprintf(), arg() or QTextStream instead")
```
=> Remove deprecated QString::sprintf

ChangeLog.md, qgroundcontrol.pro, qgroundcontrol.qrc, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/TakeoffMissionItem.cc, src/MissionManager/VTOLLandingComplexItem.cc, src/MissionManager/VTOLLandingComplexItem.h, src/MissionManager/VTOLLandingPattern.FactMetaData.json, src/PlanView/FWLandingPatternMapVisual.qml, src/PlanView/VTOLLandingPatternEditor.qml, src/PlanView/VTOLLandingPatternMapVisual.qml
Added new VTOL Landing Pattern complex item:
* Works very similarly to FW Landing Pattern
* Sequence is: DO_LAND_START, camera futzing (optional), MAV_CMD_NAV_LOITER_TO_ALT, VTOL_LAND
* Modified VTOL default takeoff straight up distance to takeoff point to be 30 meters. Would like opinions on the the correct default for this value.
* VTOL loiter exit to land point also defaults to 30 meters. Would like opinions on the the correct default for this value.
There is an issue somewhere I can't find asking to set FW Landing Pattern heading to match the heading set on takeoff climbout. Under the assumption climbout was set to go into the wind. I would think the same thing applies to VTOL Landing Pattern loiter to land path. Once I figure out how to do that this will happen for VTOL as well. …
=> Plan: VTOL landing pattern

qgroundcontrol.qrc, src/FactSystem/FactGroup.cc, src/FactSystem/FactGroup.h, src/FlightMap/Widgets/ValuePageWidget.qml, src/FlightMap/Widgets/ValuesWidgetController.cc, src/FlightMap/Widgets/ValuesWidgetController.h, src/QmlControls/QGCPopupDialog.qml, src/QmlControls/QGCPopupDialogContainer.qml, src/QmlControls/QGroundControl/Controls/qmldir, src/api/QGCCorePlugin.cc, src/ui/MainRootWindow.qml
New QGCPopupDialog support:
* Works just like right hand QGCViewDialog except creates a centered modal Popup
* Popup is centered on the screen
* Popup is ensured to not exceed window bounds
* Size of Popup is determined by size of inner QGCPopupDialog content
* Flickable is automatically included for scrolling when QGCPopupDialog content exceeds main window bounds
* Create using mainWindow.showPopupDialog(...)
* mainWindow.showPopupDialog can be called from within QGCPopupDialog content to stack dialogs
New value editing dialogs for Instrument Values using the new capability above:
* Since the new dialogs don't overlap the instrument display you can see the effects of your changes as you make them. 
* Still some quirks on right side margins, but tired of fighting with Qt Layout bugs. I'll …
=> Value edit dialog

src/QmlControls/QGCPopupDialogContainer.qml
Some minor visual tweaks to make the dialogs more visually distinct when you stack them.
=> Tweaks to Popup visuals

qgroundcontrol.pro, qgroundcontrol.qrc, src/QGCApplication.cc, src/QmlControls/QGroundControl/Specific/BaseStartupWizardPage.qml, src/QmlControls/QGroundControl/Specific/StartupWizard.qml, src/QmlControls/QGroundControl/Specific/UnitsWizardPage.qml, src/QmlControls/QGroundControl/Specific/qmldir, src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/Settings/UnitsSettings.cc, src/api/QGCCorePlugin.cc, src/api/QGCCorePlugin.h, src/ui/MainRootWindow.qml
Set the default metric system based on user preferences. Use the user locale settings to decide between imperial and metric. If user changes any of the metric units to other value that takes precedence and it is used instead.
Give user the chance to accept or change the metric system at the first start using a generic first-time setup wizard that can be extended in the custom build by overriding QGCCorePlugin::startupPages() in order to provide other required first time setup experience e.g.: internet services login.
Changing the metric system will prompt user to restart QGC as it is in the settings.
Previously, the default metric system, if it was never changed in general settings, was set to metric system.
=> Change default metric system based on user locale

src/FlightMap/Widgets/ValuePageWidget.qml, src/QmlControls/QGCPopupDialogContainer.qml
I've been fighting with this for days now. I finally found the magic order which puts the flickable in the right place for scrolling dialogs which don't fit in the window.
=> Fix QGCPopupDialog automatic flickable parenting

src/Settings/AppSettings.cc
=> Always generate AppSettings::savePath at runtime for mobile builds

src/Joystick/Joystick.cc, src/VehicleSetup/JoystickConfigButtons.qml
Related to discussion in #8601
=> Add support for multi-press joystick buttons

src/Joystick/Joystick.cc, src/Joystick/Joystick.h
This commit adds the emergency stop as button action to the joystick.
Enables a user to map emergency stop to a button of the joystick.
=> add emergency stop as joystick button action

src/Vehicle/Vehicle.cc
This fixes a bug where a URL containing a hashtag (#) was displayed without the hashtag.
This is untested, feed forward programming :smile:.
=> Vehicle: fix removal of hashtag in statustext

src/FirmwarePlugin/FirmwarePlugin.cc
I added Flir Duo R as an option for survey (https://www.flir.com/support/products/duo-r/#Overview).
I got values from its spec listed on the guide (https://www.flir.com/globalassets/imported-assets/document/flir-duo-user-guide.pdf) and asked the Flir customer support team for the focal length.
=> Add Flir Duo R config

src/QGCApplication.cc
I can only imagine this was a stray debug message
and is so, this is a perfect material for my warmup PR.
=> remove stray debug messages

QGCCommon.pri, src/QGCApplication.cc, src/QGCApplication.h, src/QmlControls/InstrumentValueArea.cc
* This allows you to better use Daily Builds side by side with Stable builds on the same machine without the Daily Build trashing your Stable settings.
* There is a new define DAILY_BUILD which is triggered by the StableBuild CONFIG option being missing.
* CI builds will set StableBuild to on for tagged builds. All other builds have it off, hence daily builds creation.
=> Separate daily build settings space

src/QmlControls/AppMessages.qml
- Add Set all button
- Add search category
Video: https://streamable.com/0k4gf9
=> Improve category log menu

src/FlightMap/MapItems/MissionItemIndicator.qml, src/FlightMap/MapItems/MissionItemIndicatorDrag.qml, src/MissionManager/QGCMapPolygonVisuals.qml, src/MissionManager/QGCMapPolylineVisuals.qml, src/PlanView/CorridorScanMapVisual.qml, src/PlanView/FWLandingPatternMapVisual.qml, src/PlanView/GeoFenceMapVisuals.qml, src/PlanView/MissionItemMapVisual.qml, src/PlanView/PlanView.qml, src/PlanView/RallyPointMapVisuals.qml, src/PlanView/SimpleItemMapVisual.qml, src/PlanView/StructureScanMapVisual.qml, src/PlanView/TakeoffItemMapVisual.qml, src/PlanView/TransectStyleMapVisuals.qml
Show mission items in geofence and rally edit mode.
Add interactive flag to the mission items that don't have it and disable interactions in Geofence and Rally edit mode.
Propagate transparency to the mission items in order to enable it in non-mission edit mode.
Mission edit mode
Geofence edit mode
Rally Points edit mode
Mission from the screenshots
[geofence_test.zip](https://github.com/mavlink/qgroundcontrol/files/4527610/geofence_test.zip)
=> Show mission items in Geofence edit mode

custom-example/res/CustomFlyViewOverlay.qml, qgroundcontrol.pro, src/AutoPilotPlugins/APM/APMFollowComponent.qml, src/AutoPilotPlugins/PX4/SafetyComponent.qml, src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/FlightDisplay/GuidedAltitudeSlider.qml, src/FlightMap/MapItems/VehicleMapItem.qml, src/FlightMap/MapScale.qml, src/MissionManager/KMLPlanDomDocument.cc, src/PlanView/FWLandingPatternMapVisual.qml, src/PlanView/PlanToolBarIndicators.qml, src/PlanView/StructureScanEditor.qml, src/PlanView/TerrainStatus.qml, src/PlanView/TransectStyleComplexItemStats.qml, src/QmlControls/QGroundControl/Specific/UnitsWizardPage.qml, src/QmlControls/QGroundControlQmlGlobal.h, src/QmlControls/QmlUnitsConversion.h, src/Settings/UnitsSettings.cc, src/Settings/UnitsSettings.h, src/Vehicle/Vehicle.cc, src/ui/preferences/GeneralSettings.qml, src/ui/toolbar/GPSRTKIndicator.qml
Sooner or later drones will start carrying payload and this PR introduces units of weight.
It also separates distance units from altitude units as this is often a practice (e.g.: US military always measures altitude in feet, but often measure distance in "km" - we've all seen in Hollywood movies when they say "clicks" - it's true).
=> Introduce weight unit and separate distance unit from altitude

src/QmlControls/QmlObjectListModel.cc, src/QmlControls/QmlObjectListModel.h
Often necessary to move/reorder objects within the list for example in ListView dragging, waypoints reordering, etc etc. And `move()` method should be added and organized properly to allow above and work correctly.
=> Allow to move/reorder objects within QmlObjectListModel

qgroundcontrol.pro, src/QGCApplication.cc
QGC appears broken when compiled in linux environment that does not provide QT_QUICK_CONTROLS_STYLE
Without this patch, that is what I have here:
=> Fix Qt environment style in linux systems

qgroundcontrol.qrc, src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/FlyViewToolStrip.qml, src/FlightDisplay/GuidedActionConfirm.qml, src/FlightDisplay/GuidedActionList.qml, src/FlightDisplay/GuidedActionsController.qml, src/QmlControls/QGroundControl/FlightDisplay/qmldir
This is a cleanup of FlightDisplayView.qml and the control within it. The goal is to move the business logic out of the main FlightDisplayView.qml file and into the controls use within that ui. That in turn should make this ui more easily customizable.
=> Fly View: Move business logic inside controls

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h, src/MissionManager/RallyPoint.FactMetaData.json, src/MissionManager/RallyPoint.cc, src/Vehicle/SubmarineFact.json
This will allow sub users to see if the ROV is in the Roll/pitch toggle
mode using the APMSubInfo section in the info widget
needs to wait for https://github.com/ArduPilot/ardupilot/pull/13630
Fix #8360 
Fix #8705
=> Sub: Add fact for roll/pitch toggle, remove spaces from fact names

qgroundcontrol.qrc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FlightDisplay/FlyViewCustomLayer.qml, src/FlightDisplay/FlyViewMap.qml, src/FlightDisplay/FlyViewWidgetLayer.qml, src/PlanView/PlanToolBar.qml, src/PlanView/PlanToolBarIndicators.qml, src/QmlControls/QGCToolBarButton.qml, src/QmlControls/QGroundControl/Controls/qmldir, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/api/QGCCorePlugin.cc, src/api/QGCCorePlugin.h, src/api/QGCOptions.cc, src/api/QGCOptions.h, src/ui/MainRootWindow.qml, src/ui/toolbar/MainToolBarIndicators.qml, src/ui/toolbar/ToolBarBase.qml
* Common base view toolbar for all views
* Branding and communication status information is consistent across all views
* If a vehicle is connected you can still see critical tool indicators like say battery even though you may be changing a parameter
* Ability to show tool indicators when not connected to a vehicle. A good example of this is RTK. If you have an RTK device connected you can now see survey in without a vehicle connected.
* Plan view now uses standard view switching mechanism instead of the "You only get to go back to the Fly View" thing.
* New view switching ui uses less real estate. Provide space for the next phase of work which is to add an instrument value section to the toolbar for critical values.
* I'll be writing up dev guide docs for how to customize.
RTK with no …
=> Re-architect toolbar for better customization, features, real estate

src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h
If the mission contains a MAV_CMD_NAV_VTOL_TAKEOFF item then the VTOL calculations start in hover mode. If not, then the best assumption we can do is assume cruise mode.
Replacement for #8735.
=> Fix VTOL hover determination

qgroundcontrol.pro, src/QGCApplication.cc
Just backporting @patrickelectric 's changes to stable. This fixes at least the first issue in #8484 (text not fitting in the widget)
=> Stable: Fix Qt environment style in linux systems

ChangeLog.md, src/FlightMap/Widgets/VideoPageWidget.qml, src/QGCApplication.cc
* Fix video page widget control usage and sizing
* Always apply "Default" style to Qml Controls. In general this shouldn't be needed since we have our own custom control set. But there are a few like sliders which use the vanilla control. By forcing to Default style it prevents the QT_QUICK_CONTROLS_STYLE from randomly changing the QGC ui.
Replacement for #8747 and friends.
=> Video widget

src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h
FactMetaData:
```
// Custom function to validate a cooked value.
//  @return Error string for failed validation explanation to user. Empty string indicates no error.
typedef QString (*CustomCookedValidator)(const QVariant& cookedValue);
```
```
/// Sets a custom cooked validator function for this metadata. The custom validator will be called
/// prior to the standard validator when convertAndValidateCooked is called.
void setCustomCookedValidator(CustomCookedValidator customValidator) { _customCookedValidator = customValidator; }
```
This then ties into the normal Fact validation system. Such that the users get an explanation and an error popup dialog when validation fails.
Related to #8721
=> FactMetaData: Add custom validator support

.appveyor.yml, .travis.yml, QGCCommon.pri, qmlglsink.pri, src/AutoPilotPlugins/APM/APMCompassCal.cc, src/Camera/QGCCameraIO.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/MissionManager/SimpleMissionItem.cc
Compiler warnings as errors was pretty majorly screwed up. As discovered by #8696. I won't go into the gory details. But as it stands now all warnings are errors on all OS.
=> Compiler warnings clean up

src/Joystick/Joystick.cc, src/VehicleSetup/JoystickConfigButtons.qml
The load settings for joystick buttons was validating the action against the currently known set of available actions. Tossing the actions which were not in the list. At the time load settings is called there isn't a vehicle yet hence the flight modes aren't in the list. Hence all flight mode assignments were being dropped.
I think it's better to just leave these in there in any case. It is possible to set up joystick for Vehicle A which has a different set of flight modes available than Vehicle B. It's better to have the flight mode change just fail with an error in that case.
The new way it works from a ui perspective is that if a button is truly assigned to a flight mode which currently does not exist then it shows "No Action" which isn't quite correct. But good enough I think then …
=> Fix disappearing flight mode button assignments

.travis.yml, doc/README, doc/dot
Updated the documentation to indicate correct packages for "apt" to import to build documentation.
Fixed dot errors (hardcoded path for dot)  in script building doxygen docs on Ubuntu 
Fixes TravisCI errors since Trusty has been replaced with xenial.
=> Debian doc updates

src/MissionManager/MissionController.cc
* VTOL_TAKEOFF command wasn't considered as a transition to FW
* Fix for #8735
Also keep in mind for time calcs that in general QGC doesn't consider vertical distance in calcs, only horizontal distance. Except for takeoff which is special cased and will account for the takeoff from ground to straight up in hover. Land doesn't do this, which is odd, but it is what is is for now.
=> VTOL Takeoff should be considered a transition to FW

ChangeLog.md, src/FlightDisplay/FlightDisplayView.qml, src/FlightDisplay/FlightDisplayViewWidgets.qml, src/FlightDisplay/VirtualJoystick.qml, src/QmlControls/JoystickThumbPad.qml, src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/ui/preferences/GeneralSettings.qml
* Fix for #8774. Related to #7375
* Fixes right stick auto-center
* Adds reverse support for rover/sub which sends correct negative thrust values for reverse
* Fixes throttle auto-center with respect to reverse as well
=> Rework reverse/center throttle support. Fix right stick centering bug.

QGCSetup.pri, custom-example/custom.pri, custom-example/custom_deploy.pri, custom-example/deploy/qgroundcontrol-start.sh, custom-example/deploy/qgroundcontrol.desktop
2 fixes proposed for custom build:
=> Deploy custom start script for custom build

ChangeLog.md, src/QmlControls/LogReplayStatusBar.qml, src/QmlControls/QGCCheckBox.qml
Wasn't showing the list of telemetry files even though they were there in the file system
=> Mobile Log Replay: Fix file dialog

ChangeLog.md, src/comm/QGCSerialPortInfo.cc
The Orange and Yellow Cubes expose a composite usb device over a single usb physical connections. The first of the ports is the mavlink connection. The second connection by default is SLCAN and QGC should not auto-connect to it.
=> Cube orange yellow

src/MissionManager/CorridorScanComplexItem.cc, src/MissionManager/CorridorScanComplexItemTest.cc, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/StructureScanComplexItem.h, src/MissionManager/SurveyComplexItem.cc, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h, src/MissionManager/VisualMissionItem.cc, src/MissionManager/VisualMissionItem.h
* No need to call setMissionFlightStatus on newly created items. Correct handling will happen during recalc
* TransectStyleCompleteItem now correctly rebuilds transects when vehicle speed changes. Terrain calc is specific to vehicle speed to do climb/descent rate based calc.
* Related to #8846
=> Mission flight status

QGCExternalLibs.pri, src/VehicleSetup/FirmwareUpgradeController.cc
* Get zlib support working on all platforms
* Switch to using gzip version of ArduPilot manifest
This is the first test case of inflating a gzip file. I will now turn this into a more generic gzip decompress and use for COMPONENT_INFORMATION gzipped json as wlel.
=> Gzip ArduPilot manifest support

src/Camera/QGCCameraControl.cc, src/FactSystem/FactGroup.cc, src/FactSystem/FactGroup.h
The camera module uses PARAM_EXT, which is case sensitive. Changing the case at runtime causes the parameters not to be found.
=> Add option to ignore camel case in FactGroup.

src/VideoReceiver/README.md
Update to README.md. When installing the gstreamer-dev packages on Linux, excluding the
doc packages saves disk space and bandwidth.
=> Doc: Linux gstreamer install, exclude doc packages

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/VehicleSetup/PX4FirmwareUpgradeThread.cc
* Remove handling of `RC_CHANNELS_RAW` relying o n`RC_CHANNELS` only. Handling both was causing incorrect channel counts to be sent to Radio Cal. This fixes *#8853 
* Fixed flash find board loop
=> Remove RC_CHANNELS_RAW support

src/MissionManager/MissionController.cc, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItemTest.cc, src/MissionManager/TransectStyleComplexItemTest.h, src/Terrain/TerrainQuery.cc, src/Terrain/TerrainQuery.h
This PR introduces one, basic, not awfully valuable, but first nonetheless test that puts `TransectStyleComplexItem::_followTerrain` under stress. 
It does so by introducing two fake regions around [Point Nemo](https://oceanservice.noaa.gov/facts/nemo.html), where they have little chance of colliding with real terrain - should that ever needed to be put under test and checked in as a terrain tile:
-  [flat region at 10m above ASL](https://github.com/mavlink/qgroundcontrol/pull/8846/files#diff-3c691d138cca295bea62f8d66ae860abR317);
- [slope region](https://github.com/mavlink/qgroundcontrol/pull/8846/files#diff-3c691d138cca295bea62f8d66ae860abR329) rising (east to west) from -100 to 1000m above ASL.
Each region is a bounding box 0.1 x 0.1 degrees across (about 11km x 11km if it were on the …
=> Add a follow terrain test

qgroundcontrol.pro, qgroundcontrol.qrc, src/FirmwarePlugin/APM/APM-MavCmdInfoCommon.json, src/FirmwarePlugin/APM/APM-MavCmdInfoFixedWing.json, src/FirmwarePlugin/APM/APM-MavCmdInfoMultiRotor.json, src/FirmwarePlugin/PX4/PX4-MavCmdInfoCommon.json, src/FirmwarePlugin/PX4/PX4-MavCmdInfoFixedWing.json, src/FirmwarePlugin/PX4/PX4-MavCmdInfoMultiRotor.json, src/MissionManager/MavCmdInfoCommon.json, src/MissionManager/MavCmdInfoFixedWing.json, src/MissionManager/MavCmdInfoMultiRotor.json, src/MissionManager/MissionCommandTreeEditorTest.cc, src/MissionManager/MissionCommandTreeEditorTest.h, src/MissionManager/MissionCommandTreeEditorTestWindow.qml, src/MissionManager/SimpleMissionItemTest.cc, src/PlanView/SimpleItemEditor.qml, src/QGCApplication.cc, src/comm/QGCMAVLink.cc, src/comm/QGCMAVLink.h, src/qgcunittest/UnitTest.cc, src/qgcunittest/UnitTest.h, src/qgcunittest/UnitTestList.cc
* Created standalone unit test which outputs bitmaps of all command editors so you can review whether json is correct or not
* You can create unit tests which can be run from command line but are not run with you specify to run all tests using the new `UT_REGISTER_TEST_STANDALONE` macro. This allows you to run it with `--unitest:Foo`, but it doesn't run when you just do `--unitest` to run all tests.
* Fixed up various problems in command json. Still much work to do here. The unit test gives me he foundation to fix things up further and verify.
* Related to #8923
Here is example output from the new unit test for the PX4 Pro - MultiRotor case:
=> Plan: Command editor json clean, unit test

src/VehicleSetup/Bootloader.h, src/VehicleSetup/FirmwareUpgradeController.cc, src/VehicleSetup/FirmwareUpgradeController.h, src/comm/USBBoardInfo.json
I forgot how awful this was, we should add support for a manifest file.
=> support mRo Control Zero with PX4

src/VehicleSetup/FirmwareUpgrade.qml, src/VehicleSetup/FirmwareUpgradeController.cc
=> Fix Flow custom flash

src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/MissionControllerTest.cc, src/MissionManager/MissionControllerTest.h
* Found/fixed a pile of bugs related to MissionController::_recalcMissionFlightStatus
* Gimbal/Vehicle yaw calc/display was buggy
* Current plan flight speed was being applied one mission item too early. Throwing off things like time calcs
* Current VTOL state was being applied on mission item too early
* Related to #8923
=> Plan: Fix recalc bugs associated with vtol state, speed, vehicle/gimbal yaw

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/MissionManager/CameraSectionTest.cc, src/MissionManager/KMLPlanDomDocument.cc, src/MissionManager/MavCmdInfoFixedWing.json, src/MissionManager/MavCmdInfoMultiRotor.json, src/MissionManager/MissionCommandTree.cc, src/MissionManager/MissionCommandTree.h, src/MissionManager/MissionCommandTreeTest.cc, src/MissionManager/MissionController.cc, src/MissionManager/MissionManager.cc, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/SimpleMissionItem.h, src/MissionManager/SimpleMissionItemTest.cc, src/MissionManager/SimpleMissionItemTest.h, src/MissionManager/TakeoffMissionItem.cc, src/MissionManager/VisualMissionItem.cc, src/MissionManager/VisualMissionItem.h, src/QGC.cc, src/QGC.h, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
* Related to #8923
Example Plan with transitions:
* Plan starts with VTOL takeoff so QGC knows current state after that is FW
* Here you can see the Loiter to Alt editor which is showing fixed wing values
* After that there is a transition to MR
* And here you can see Loiter to Alt after that showing MR values
=> Plan: Show correct item editor based on current VTOL state in mission

src/ADSB/ADSBVehicle.cc, src/MissionManager/MissionController.cc, src/MissionManager/MissionSettingsItem.cc, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/VisualMissionItem.cc, src/QmlControls/FlightPathSegment.cc, src/QmlControls/InstrumentValueData.cc, src/QmlControls/TerrainProfile.cc, src/Vehicle/Vehicle.cc, src/qgcunittest/UnitTest.cc, src/qgcunittest/UnitTest.h
Qt's qFuzzyCompare has all sort of quirks:
* Double values cannot be NaN. This was known and handled with extra code in most places.
* Nor can they be 0. This was unknown and still seems incorrect. But whatever...
In those cases it doesn't work correctly. There were a pile of places in QGC code using it and due to the above problems I create a new QGC::fuzzyCompare which can be used on double which works in all cases.
=> Replace qFuzzyCompare with better functioning QGC::fuzzyCompare

src/QtLocationPlugin/ElevationMapProvider.cpp, src/QtLocationPlugin/ElevationMapProvider.h, src/Terrain/TerrainQuery.cc, src/TerrainTile.cc, src/TerrainTile.h
* Double value imprecision/rounding erros for lat/lon value could cause validation failures in terrain tile lookups
* Related to #8946
=> Terrain data: Deal with double imprecision errors in elevation tile calculations

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc, src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/MissionManager/CameraSection.cc, src/MissionManager/MissionCommandTree.cc, src/MissionManager/MissionCommandTreeEditorTest.cc, src/MissionManager/MissionController.cc, src/MissionManager/TransectStyleComplexItem.cc, src/PlanView/PlanView.qml
* You will now only get commands to pick from which are relevant to your vehicle class
* So for example VTOL commands no longer show up as available for a multi-rotor vehicle
* Related to #8923
=> Plan: supportedMissionCommands is vehicle class sensitive

src/FirmwarePlugin/CameraMetaData.cc, src/FirmwarePlugin/CameraMetaData.h, src/FirmwarePlugin/FirmwarePlugin.cc, src/MissionManager/CameraCalc.FactMetaData.json, src/MissionManager/CameraCalc.cc, src/MissionManager/CameraCalc.h, src/MissionManager/CameraCalcTest.cc, src/MissionManager/StructureScanComplexItemTest.cc, src/MissionManager/SurveyComplexItem.cc, src/MissionManager/TransectStyleComplexItemTest.cc, src/PlanView/CameraCalcCamera.qml
* Problems with picking a camera: 
* Names were long and getting clipped
* List was long, not easy to pick from
* Solved by changing to separate Brand/Model camera selection
* Problem: The camera name saved in Plan files was the translated camera name. This made plan files language dependant which is wrong.
* Fixed by stored canonical english camera name in plan file
* Only Brand/Model are translated
* Requires back compat code to support loading plan files with translated names. Also means CameraMetaData needs to include deprecated translated camera names for previously added cameras.
* From here on out newly added cameras should leave the deprecated translation name blank
Brand/Model combos:
Known cameras now show specs so you can see what you are using:
=> Plan: Camera brand/model support. Use canonical camera names in Plan files.

src/AnalyzeView/AnalyzeView.qml, src/FlightDisplay/FlyViewToolStripActionList.qml, src/PlanView/PlanView.qml, src/VehicleSetup/SetupView.qml, src/ui/AppSettings.qml, src/ui/MainRootWindow.qml, src/ui/toolbar/MainToolBar.qml
Views:
* Fly
* Plan
* You change views using the Fly/Plan button at the top of the left toolstrip
Tools:
* Application Settings
* Vehicle Setup
* Analyze Tools
* You show a tool by clicking the "Q" and picking it from the Tool drawer
* Selecting a tool has no effect on the current view. When you close the tool, the view you were looking at before is still there.
* Tools are full window and slide out from the left edge. Close button to close.
Note the "Plan" button in the top of the toolstrip:
Tool Drawer:
Application Settings tool:
=> Split into Views and Tools

src/AnalyzeView/AnalyzePage.qml, src/AnalyzeView/AnalyzeView.qml, src/AnalyzeView/MAVLinkInspectorController.cc, src/AnalyzeView/MAVLinkInspectorController.h, src/AnalyzeView/MAVLinkInspectorPage.qml, src/ui/MainRootWindow.qml
* Here is an example of a log replay. You can see the system combo shows up with two entries. 255 is QGC outgoing telemetry, and 1 is the incoming vehicle telemetry.
* Also fixed a problem where values for a message were not updated unless the message was selected in the ui. This made analyzing logs not super useful. Since you couldn't see the last value for the message. And in fact if you selected a message, new values came in for that message, selected some other message, new values came in on the previous message and then you went back to select the previous message it would show you stale data with no indicator of that.
=> Mavlink Inspector: Support displaying messages from multiple systems

src/ui/MainRootWindow.qml
* Tool select drawer supports escape, click outside, switch right to close
* Tool drawer should not support interactive close methods, just the Close button
=> Fly: Fix Drawer closePolicy/interactive

src/AnalyzeView/MAVLinkInspectorController.cc, src/AnalyzeView/MAVLinkInspectorController.h
* Only update fields once the item becomes selected
* Fixed some over signalling of QmlObjectListModel changes and used new begin/endReset bracketing for major changes
=> Mavlink Inspector: Performance changes

src/QtLocationPlugin/MapboxMapProvider.h
Selecting map type as "Mapbox Hybrid" produces error and map is not shown:
> Fetch tile error: "Error transferring https://api.mapbox.com/v4/mapbox.hybrid/8/147/87.jpg80?access_token=pk.eyJ1IjoiYWlybWFwIiwiYSI6InhIMVMxeHcifQ.-5KWsUSR1cTbqUhTRpGkgQ - server replied: Not Found"
> QGeoTileRequestManager: Failed to fetch tile (147,87,8) 5 times, giving up. Last error message was: 'Error transferring https://api.mapbox.com/v4/mapbox.hybrid/8/147/87.jpg80?access_token=pk.eyJ1IjoiYWlybWFwIiwiYSI6InhIMVMxeHcifQ.-5KWsUSR1cTbqUhTRpGkgQ - server replied: Not Found'
This PR fixes this.
=> Mapbox hybrid map name API fix

qgroundcontrol.pro, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/Vehicle/VehicleClockFactGroup.cc, src/Vehicle/VehicleClockFactGroup.h, src/Vehicle/VehicleDistanceSensorFactGroup.cc, src/Vehicle/VehicleDistanceSensorFactGroup.h, src/Vehicle/VehicleEstimatorStatusFactGroup.cc, src/Vehicle/VehicleEstimatorStatusFactGroup.h, src/Vehicle/VehicleGPSFactGroup.cc, src/Vehicle/VehicleGPSFactGroup.h, src/Vehicle/VehicleSetpointFactGroup.cc, src/Vehicle/VehicleSetpointFactGroup.h, src/Vehicle/VehicleTemperatureFactGroup.cc, src/Vehicle/VehicleTemperatureFactGroup.h, src/Vehicle/VehicleVibrationFactGroup.cc, src/Vehicle/VehicleVibrationFactGroup.h, src/Vehicle/VehicleWindFactGroup.cc, src/Vehicle/VehicleWindFactGroup.h, src/ui/toolbar/BatteryIndicator.qml
This finishes the work of refactoring all the fact group source out of Vehicle to separate source files. It used the `FactGroup::handleMessage` routing which was put in place in the previous battery fact group pull.
=> Vehicle fact group refactor

src/MissionManager/LandingComplexItem.cc, src/MissionManager/LandingComplexItem.h, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/PlanView/FWLandingPatternEditor.qml, src/PlanView/FWLandingPatternMapVisual.qml, src/PlanView/VTOLLandingPatternEditor.qml, src/PlanView/VTOLLandingPatternMapVisual.qml
For **VTOL** and **FW** set default landing heading to takeoff heading when `TakeoffMissionItem` is added in `PlanView`.
VTOL:
FW:
@DonLakeFlyer, please take a look and let me know if anything is missing.
=> Set default landing heading to takeoff heading

src/comm/QGCMAVLink.h
It's necessary to include QOBject to inherit
=> comm: Add missing QObject include for QGCMAVLink

HackAndroidFileDialog.qrc, HackFileDialog.qrc, qgroundcontrol.pro, src/MissionManager/QGCMapPolylineVisuals.qml, src/PlanView/PlanView.qml, src/QmlControls/AppMessages.qml, src/QmlControls/HackFileDialog.qml, src/QmlControls/KMLOrSHPFileDialog.qml, src/QmlControls/LogReplayStatusBar.qml, src/QmlControls/ParameterEditor.qml, src/QmlControls/QGCFileDialog.qml, src/QmlControls/QGCFileDialogController.cc, src/QmlControls/QGCFileDialogController.h, src/QtLocationPlugin/QMLControl/OfflineMap.qml
* These were causing bugs when they got out of sync with `nameFilters`
* Now mobile works from `nameFilters` as well
=> QGCFileDialog remove separate mobile fileExtension properties

src/Vehicle/CompInfoParam.cc, src/Vehicle/CompInfoParam.h, src/comm/MockLink.Parameter.MetaData.json
* Original support didn't work
* You now specify a group regex pattern in the name `.../(regex)/...` to match on param names
* You can refer to the captured text from the regex in `shortDesc` and `longDesc` using the `/1` tag which will be replaced
* Example:
```
{
"name": "CAL_ACC/(\\d+)/_EN",
"type": "Int32",
"group": "Sensor Calibration",
"category": "System",
"shortDesc": "Accelerometer /1 enabled",
"default": 1,
"decimalPlaces": 3,
"minValue": -2.14748e+09,
"maxValue": 2.14748e+09
},
```
=> COMPONENT_INFORMATION:COMP_METADATA_TYPE_PARAMETER Changed parameter name regex support

src/ui/MainRootWindow.qml
* The Close button was confusing
* Changed to move of a "back" model for tools
* Example of opening Settings from Plan. Click anywhere in plan icon/back to go back to Plan View.
=> Change tool close to more of a "Back" model

src/FlightDisplay/VirtualJoystick.qml
activeVehicle - >_activeVehicle
caused the virtual joystick to malfunction
=> fixed typo in VirtualJoystick.qml

src/QtLocationPlugin/GenericMapProvider.cpp, src/QtLocationPlugin/GenericMapProvider.h, src/QtLocationPlugin/QGCMapUrlEngine.cpp
I am a QGC customer in Japan.
I would like to use the maps provided by the Geographical Survey Institute of Japan.
I would add five different types of maps.
standard map
photo map
elevation map by color
anaglyph
inclination diagram
=> QtLocationPlugin: Add Japan Map

qgroundcontrol.pro, src/MissionManager/CameraSection.h, src/MissionManager/CameraSectionTest.cc, src/MissionManager/CameraSectionTest.h, src/MissionManager/FWLandingPattern.FactMetaData.json, src/MissionManager/FWLandingPatternTest.cc, src/MissionManager/FWLandingPatternTest.h, src/MissionManager/FixedWingLandingComplexItem.cc, src/MissionManager/FixedWingLandingComplexItem.h, src/MissionManager/LandingComplexItem.cc, src/MissionManager/LandingComplexItem.h, src/MissionManager/LandingComplexItemTest.cc, src/MissionManager/LandingComplexItemTest.h, src/MissionManager/MissionController.cc, src/MissionManager/VTOLLandingComplexItem.cc, src/MissionManager/VTOLLandingComplexItem.h, src/MissionManager/VTOLLandingPattern.FactMetaData.json, src/MissionManager/VisualMissionItemTest.cc, src/MissionManager/VisualMissionItemTest.h, src/PlanView/FWLandingPatternEditor.qml, src/PlanView/FWLandingPatternMapVisual.qml, src/PlanView/VTOLLandingPatternEditor.qml, src/PlanView/VTOLLandingPatternMapVisual.qml, src/qgcunittest/MultiSignalSpy.cc, src/qgcunittest/UnitTest.cc, src/qgcunittest/UnitTest.h, src/qgcunittest/UnitTestList.cc
* Turning off loiter to alt will cause the landing pattern to start final approach with a regular waypoint
* The default is to use loiter to alt
* Custom builds can override the default as well as hide to checkbox option
* VTOL landing pattern now locks distance while dragging like the FW pattern does
=> Landing Pattern: Loiter to alt optional support

QGCPostLinkCommon.pri
We have `QMAKE_POST_LINK += echo "Post Link Common"` in line 12 already.
=> QGCPostLinkCommon: Remove duplicate echo

src/QmlControls/QGroundControlQmlGlobal.cc
function "QLineF::IntersectionType QLineF::intersects(const QLineF &line, QPointF *intersectionPoint) const" was introduced in Qt 5.14, and QLineF::intersect is obsolete.
see also:
https://doc.qt.io/qt-5.14/qlinef-obsolete.html
https://doc.qt.io/qt-5.14/qlinef.html#intersects
=> Enable QLineF::intersects on Qt version 5.14.0

src/QtLocationPlugin/GoogleMapProvider.cpp
=> QtLocationPlugin: GoogleMapProvider: Remove deprecated usage of QByteArray::append(QString)

ChangeLog.md, src/AutoPilotPlugins/APM/APMPowerComponent.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
This fixes problems on boards which support multiple power modules and the power module that is in use isn't the first one.
=> Move to BATTERY_STATUS only for info. Don't assume first battery is id=0

src/AutoPilotPlugins/PX4/PowerComponent.qml
Broken by previous multi-battery pull
=> PX4 Setup - Power: Fix broken voltage/current divider calculators

src/comm/BluetoothLink.cc, src/comm/SerialLink.cc, src/comm/TCPLink.cc, src/comm/UDPLink.cc
This fixes various crashes where slots are called on deleted objects. In reality all of the LinkInterface, FooLinks and MAVLinkProtocol code needs to be thrown out re-written using a proper consistent threading model. But I don't have time for that right now so I'm just sticking fingers in the dyke.
=> Links: Prevent stale readBytes signalling to call into deleted objects

src/AutoPilotPlugins/AutoPilotPlugin.cc, src/Terrain/TerrainQuery.cc, src/Vehicle/CompInfoParam.cc, src/Vehicle/CompInfoVersion.cc
These are necessary to get master to compile with Clang 12. At first sight it might look like a naive fix - what was initially a reference is now a copy. However, if you trace the code path in the inner loop, you will find that in all of these cases either the inner loop already created a local copy, and/or discarded the const modifier (which requires again taking a copy).
So based on my quick assessment the new compiler version keeps us more honest about the invariants.
=> Clang 12 compile error fixes

src/ADSB/ADSBVehicleManager.cc, src/FactSystem/ParameterManager.cc, src/FactSystem/ParameterManager.h, src/Vehicle/MultiVehicleManager.cc, src/Vehicle/VehicleLinkManager.cc, src/comm/BluetoothLink.cc, src/comm/BluetoothLink.h, src/comm/LinkInterface.h, src/comm/LinkManager.cc, src/comm/LogReplayLink.h, src/comm/MockLink.h, src/comm/SerialLink.cc, src/comm/SerialLink.h, src/comm/TCPLink.cc, src/comm/TCPLink.h, src/comm/UDPLink.cc, src/comm/UDPLink.h
* Remove mutexes from ParameterManager. They should not be needed since it all runs on the UI thread.
* Cleanup LinkInterface removing unnecessary methods/signals
* Fix connect calls which should have been disconnect
=> Param crash

src/Vehicle/CompInfoParam.cc, src/Vehicle/ComponentInformationManager.cc, src/Vehicle/FTPManager.cc, src/Vehicle/FTPManager.h, src/Vehicle/FTPManagerTest.cc, src/Vehicle/FTPManagerTest.h, src/Vehicle/Vehicle.cc, src/comm/MockLink.Parameter.MetaData.json, src/comm/MockLinkFTP.cc
* This is a full rewrite of the FTPManager code to a proper state machine. Previous code was ancient and became too unwieldy to patch up bugs.
* Only burst download is supported
* Also includes fixes to ComponentInformationManager and friends
* FTPManager and ComponentInformationManager together are verified to work correctly with the firmware pull which lights up COMPONENT_INFORMATION: https://github.com/PX4/Firmware/pull/16039
=> FTP Manager rewrite, COMPONENT_INFORMATION fixes

src/Vehicle/Vehicle.cc
Step to reproduce:
(1) Connect QGC with PX4 and Airsim, wait until QGC show "Connected" on UI
(2) Shutting down PX4, wait until QGC show "Communication Lost" with a "Disconnect" button.
(3) Click on the button, the crash happened.
Crash:
Debugging:
Stack Trace:
```
1  std::_Ptr_base<LinkConfiguration>::_Incref                                 memory          767  0x7ff722c011ee 
2  std::_Ptr_base<LinkConfiguration>::_Copy_construct_from<LinkConfiguration> memory          728  0x7ff722c000b8 
3  std::shared_ptr<LinkConfiguration>::shared_ptr<LinkConfiguration>          memory          980  0x7ff722c00f27 
4  LinkInterface::linkConfiguration                                           LinkInterface.h 53   0x7ff722c016ac 
5  Vehicle::sendJoystickDataThreadSafe …
```
=> fix issue of read access violation exception(access nullptr)

QGCCommon.pri, android/AndroidManifest.xml, src/AnalyzeView/ULogParser.cc, src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
Fixed 5.15 build on Android - removed deprecated API: `QLatin1Literal() -> QLatin1String()`.
**P.S. BTW**, Why Android build on 5.15 have multiple link errors? Any ideas how to fix? Update AndroidManifest.xml, @patrickelectric : https://wiki.qt.io/Qt_for_Android_known_issues ?
=> Fixed 5.15 build on Android (removed deprecated API)

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/Settings/VideoSettings.cc, src/Settings/VideoSettings.h, src/VideoManager/VideoManager.cc
* Fix for #9125
* Previous handshake was based on flaky parsing of status text messages to determine if you were connected to a Solo
* Now works based on selecting 3DR Solo as you video source
* Also added Parrot Discovery as a video source
* Both Solo and Parrot set up the internal video source and ports automatically without needing to know the specifics
* Solo video handshake occurs at vehicle connect time only. So you need to have video source set to 3DR Solo prior to vehicle connection for it to work
=> New Solo video handshake sequence

src/Vehicle/Vehicle.h, src/Vehicle/VehicleLinkManager.h
Building QGC with visual studio 2019 ver 16.6(with x86-windows-msvc2017-64bit)(not vs2017) on Windows 10, it stop with warning C5208.
As state in Microsoft doc(https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5208?view=vs-2019), the  fix is simple: add a name to struct typedef.
=> fix warning C5208 on windows(stop the build process)

src/MissionManager/PlanManager.cc, src/comm/MockLink.cc, src/comm/MockLinkMissionItemHandler.cc, src/comm/MockLinkMissionItemHandler.h
* MockLink is now always MISSION_ITEM_INT
* Unit tests now catch this bug: https://github.com/mavlink/qgroundcontrol/pull/9150#pullrequestreview-521211041
* Fix PlanManager MISSION_ITEM_INT bug
=> Change unit test to use MISSION_ITEM_INT to catch bugs

src/AnalyzeView/LogDownloadController.cc, src/AnalyzeView/MavlinkConsoleController.cc, src/AutoPilotPlugins/APM/APMSensorsComponentController.cc, src/AutoPilotPlugins/PX4/SensorsComponentController.cc, src/Camera/QGCCameraControl.cc, src/Camera/QGCCameraIO.cc, src/FactSystem/ParameterManager.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/FirmwarePlugin.cc, src/GPS/RTCM/RTCMMavlink.cc, src/MissionManager/MissionManager.cc, src/MissionManager/PlanManager.cc, src/MissionManager/PlanManager.h, src/MissionManager/PlanMasterController.cc, src/Vehicle/ComponentInformationManager.cc, src/Vehicle/FTPManager.cc, src/Vehicle/InitialConnectStateMachine.cc, src/Vehicle/TerrainProtocolHandler.cc, src/Vehicle/Vehicle.cc, src/Vehicle/VehicleLinkManager.cc, src/Vehicle/VehicleLinkManager.h, src/Vehicle/VehicleLinkManagerTest.cc, src/VehicleSetup/SetupView.qml, src/uas/UAS.cc
* There are race conditions with respect to a primary link going away before the Vehicle itself is fully destroyed. During this time primaryLink can be null.
* Change the method signature of VehicleLinkManager::primaryLink to return a weak reference. This makes it clearer that it is possible for this value to be null.
* Change all usage of VehicleLinkManager::primaryLink to correctly do null checks
=> Fix primaryLink null reference problems

src/AnalyzeView/GeoTagPage.qml, src/MissionManager/PlanMasterController.cc, src/QmlControls/ParameterEditor.qml
* If we don't know the file type by extension we attempt a json load. Fix for #9164
* Fixed "All Files" wildcard specification in file pickers from `*.*` to * which actually catches "all" files!
=> Fix plan load fallback for unknown file type

src/comm/QGCMAVLink.cc
This fixes features that check for a sub not working, such as the "lights" and "frame" tabs in vehicle setup
=> QGCMAVLink: add missing class for Sub

src/FlightDisplay/FlyViewMap.qml, src/FlightDisplay/FlyViewWidgetLayer.qml
- Fix scale showing in video when map is in windowState
- Show scale when map is in windowState
old version:
new version:
=> Fix map scale behaviour

src/MissionManager/MissionControllerTest.cc
This test has been failing on our custom QGC as we have a different default for `showGimbalOnlyWhenSet`
=> Ensure showGimbalOnlyWhenSet as custom builds may have different defaults

src/FirmwarePlugin/FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/Joystick/Joystick.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/qgcunittest/MavlinkLogTest.cc
* Retries on arming lead to safety issue with arming happening after a possible delay
* Fixed getting multiple popups about arming failures from guided actions
* Fixes #7993, #9078
=> Guided command: Don't retry arming. Remove double error popups for arming errors.

src/QmlControls/ParameterEditor.qml
We had users pressing that and hoping the vehicle would still be operational. This makes it a little clearer that it won't.
=> ParameterEditor: mention that it resets sensors calibration and frame setup

src/FlightDisplay/FlyView.qml
=> FlyView: Fix pipoverlay logic when widget goes in window state

src/QmlControls/JoystickThumbPad.qml, src/Settings/App.SettingsGroup.json
* This is a safer option for multi-rotor/rover/sub. It's isn't necessarily the best option for fixed wing, but I'd question the sanity of someone flying a fixed wing with their thumbs anyway. They can always turn it off.
* There is a problem with respect to arming the vehicle with auto-center which are firmware specific:
* PX4: Allows you arm with the throttle centered in modes like Position. It does not allow it in Stabilize. To me this makes a lot of sense since most joysticks virtual or not auto-center both axes.
* ArduPilot: Require throttle to be low no matter what if you try to arm. So for vehicles which don't support reverse throttle auto-center doesn't really work. The reason being you can't hold the virtual joystick throttle down and click in the toolbar to arm. I'm going to post …
=> Virtual joystick defaults to auto-center

src/Vehicle/VehicleBatteryFactGroup.cc
Fix bug reported here: https://discuss.ardupilot.org/t/qgc-android-daily-decimap-point-on-the-battery-current-displayed-is-wrong/63868
=> Adjust battery_current from cA to A

src/Vehicle/ComponentInformationManager.cc, src/Vehicle/ComponentInformationManager.h, src/Vehicle/FTPManager.cc, src/Vehicle/FTPManager.h, src/Vehicle/VehicleLinkManagerTest.cc, src/comm/MockLink.cc
* From `mavlinkftp://` to `mftp://` to save characters in message packet
* Add support for specifying component id in uri. Format `mftp://[;comp=<id>]<path>`. This allows the component which delivers the metadata files to differ from the component you are requesting it from. So for example you could store all the metadata on a companion computer.
=> COMPONENT_INFORMATION change ftp spec

src/QmlControls/MainWindowSavedState.qml
`src/QmlControls/MainWindowSavedState.qml` used to restore window state if it finds saved parameters in `%AppData%/QGroundControl.org/QGroundControl.ini`
This leads to bugs if, for example, the saved window position is on a screen which is no longer connected.
This PR adds a simple `if` clause which lets the main window open with Qt default geometry in case the saved geometry is found to be invalid.
=> #9202 Bugfix : Only restoring saved window state if parameters make sense on current screen configuration

qgroundcontrol.pro
Project is not using QPrint* classes or QPageSetupDialog and QAbstractPrintDialog
=> qgroundcontrol: Remove print support

VideoReceiverApp/android/build.gradle
It's not possible to use http anymore, maven repository should use https.
=> VideoReceiverApp: Fix gradle file and use https over http

src/VideoReceiver/GstVideoReceiver.cc
Extracting video size from decoderValve is more guaranteed.
Fix #9177 
=> GstVideoReceiver: Fix video size signal

src/AutoPilotPlugins/APM/APMMotorComponent.qml, src/AutoPilotPlugins/APM/APMSubMotorComponent.qml, src/AutoPilotPlugins/Common/MotorComponent.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
- Stops the timer when it shouldn't be sending motor tests messages. This fixes some "motor test command failed" after user clicked the motor test toggle to stop the test/disarm, but the vehicle state in qgc hasn't received a disarmed heartbet yet
- Disables showError for sub, fixing #9234
=> Sub motor test fixes

src/AnalyzeView/MavlinkConsoleController.cc
And removes the extra expired() call (less atomic ops).
=> fix mavlink shell: weakLink.expired() logic was inverted

src/MissionManager/MissionController.cc, src/QmlControls/TerrainProfile.cc, src/QmlControls/TerrainProfile.h
This would lead to confusing differences in the Terrain Profile display depending in what happened before a Plan was loaded.
=> Terrain Profile: Fix min amsl alt calculation

deploy/create_linux_appimage.sh
I discovered the issues with this script while using it to build an AppImage containing a modified application binary of [CustomQGC](https://github.com/mavlink/qgroundcontrol/blob/master/custom-example/custom.pri). I am working for one of several teams that got involved with [US Defense drone-related initiatives](https://www.defense.gov/Newsroom/Releases/Release/Article/2318799/defense-innovation-unit-announces-suas-product-availability-to-provide-secure-c/) recently.
For now, this issue is only pertinent to those who **deploy** QGC. That probably isn't even a majority of the developers. So this isn't affecting a lot of people.
However, I do think you should add `set -Eeuxo` to your bash script A.S.A.P.  The next time a depended-upon URL goes offline, it may not be as innocuous for your …
=> create_linux_appimage.sh: stop trying to wget from not-found URL(s)

src/FactSystem/FactMetaData.cc, src/FactSystem/FactMetaData.h, src/QmlControls/ScreenTools.qml, src/Settings/Video.SettingsGroup.json, src/Settings/VideoSettings.cc, src/Settings/VideoSettings.h, src/VideoManager/VideoManager.cc, src/VideoReceiver/GStreamer.cc, src/VideoReceiver/GStreamer.h, src/VideoReceiver/GstVideoReceiver.cc, src/VideoReceiver/GstVideoReceiver.h, src/ui/preferences/GeneralSettings.qml
- nvidia's hardwre code - tested by me
- vaapi hardware decode AMD - tested by @Williangalvani 
The older video implementation was using a specific pipeline, with the new video backend, now QGC is hostage of `decodebin` to take the decisions about the pipeline construction. 
Moving to `decodebin3` and enabling the hardware decode creates a much better scenario with a modern `decodebin` alternative that can handle a better construction and decision about the pipeline and elements that is used.  
Fix #8631
Needs #9099 to work under windows
=> Enable and configure hardware decode priority 

src/AnalyzeView/MavlinkConsoleController.cc, src/AnalyzeView/MavlinkConsoleController.h, src/AnalyzeView/MavlinkConsolePage.qml
Changes:
- revolutionary feature: user can select & copy output (to be fair there is a caveat, see below)
- auto-scrolling: update is paused when scrolling up, any key input will scroll to the bottom
- feel is more like a shell w/o extra text field.
(on mobile there's still a separate text field as input is handled differently)
- handle multi-line commands from clipboard
- coloring of ERROR's and WARNing's
- set text focus to shell input on init
- some fixes around cursor + newline handling (see commits)
The use of a `TextArea` is quite slow when the output grows. This is mitigated by:
- limit update rate to 30hz
- limit history to 500 lines
With this I'm seeing a CPU load increase for QGC from idle ~22% to ~28% with continous updates (running `top`), vs. 22% to 24% on master.
The only …
=> UX improvements around MAVLink Console

src/FactSystem/FactGroup.h, src/TerrainTile.cc, src/Vehicle/FTPManager.cc, src/Vehicle/FTPManager.h, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/comm/BluetoothLink.h, src/comm/LinkManager.cc, src/comm/LinkManager.h, src/comm/LogReplayLink.h, src/comm/MAVLinkProtocol.cc, src/comm/MockLink.h, src/comm/SerialLink.h, src/comm/TCPLink.h, src/comm/UDPLink.h
When rebooting the vehicle from param editor, the vehicle would call `VehicleLinkManager::closeVehicle()` from `Vehicle::_mavlinkMessageReceived`. The link was then removed, and deleted as the ref count went to 0. If `MAVLinkProtocol::receiveBytes` was then parsing further messages, the same link was accessed again, leading to invalid memory access.
This PR fixes it by checking the validity of the link object after message handling. It could be solved differently, e.g. by closing the connection outside of the `MAVLinkProtocol::receiveBytes` call.
See individual commits for details.
Fixes #9260
Debugging output:
```
VehicleLinkManagerLog: _removeLink: "5b59370"
LinkManagerLog: LinkManager::_linkDisconnected "PX4 FMU V5 on ttyACM0 (AutoConnect)" 3
Thread 1 "QGroundControl" received signal …
```
=> Fix Segfault on vehicle reboot

src/main.cc
QProces::execute(QString) was deprecated, QProcess::execute(QString, QStringList) should be used
=> main: Fix mac build when running Qt 5.15

src/MissionManager/ComplexMissionItem.h, src/MissionManager/MissionSettingsItem.cc, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/StructureScanComplexItem.h, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/TransectStyleComplexItem.h
* Fixed more bug relating to the terrain profile clipping the flight path since min/max alt was incorrect
* Found while trying to reproduce #9272
=> Terrain Profile: Fix bugs relating to incorrect complex item min/max amsl alt

src/QmlControls/FlightPathSegment.cc
* This could cause FW takeoff to show incorrect collision right at takeoff point
* Fix #9273
=> Terrain Profile: Fix off by 1 on terrain collision detection

src/AutoPilotPlugins/PX4/PX4TuningComponent.cc, src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml, src/QmlControls/FactSliderPanel.qml, src/QmlControls/PIDTuning.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
This brings the PID tuning page into a minimally working state.
And over a telemetry link:
Unfortunately the update rate is not sufficient (around 10Hz) for it to be useful.
I removed the attitude, since that is generally not required to be tuned for MC.
Before merging:
-  [x] make the advanced the default, remove hover & min throttle sliders
-  [x] make sure things are still corrrect for other vehicle types
-  [x] fix overlapping text for slider
-  [ ] descriptions can probably be improved
For later:
- disable graph over telemetry link (e.g. if update rate is < 20Hz)
- keep data when switching between axis (graph + clipboard)
- add ability to lock roll+pitch sliders together
- start graph on arming if not already running
- mouse zooming might be useful
- potentially show …
=> PX4 MC PID tuning page

src/QtLocationPlugin/QGCTileCacheWorker.cpp
If TileDB is bigger than 2GB, 
--- sq = QString("SELECT COUNT(size), SUM(size) FROM Tiles WHERE tileID IN (SELECT A.tileID FROM SetTiles A join SetTiles B on A.tileID = B.tileID WHERE B.setID  ---
This query holds so long time QGCTileCache Worker.
I solved my problems with adding an index like that.
=> Add indexes to prevent Query Blocking with full search for Big offline map.

src/AutoPilotPlugins/PX4/SensorsSetup.qml, src/QmlControls/IndicatorButton.qml
* Sensor setup indicators only show when red. This is a better user model for buttons which are either red or show no indicator since they are fine. It also matches how the Setup page buttons works in that they go red when setup is needed and then just normal buttons when setup is good.
* PX4 Level Horizon never shows a red indicator
* Replacement for #9283
=> Level horizon indicator

src/AutoPilotPlugins/APM/APMPowerComponent.qml
The power screen in the APM vehicle setup didn't properly show the current voltage and current.
I'm not much of a Qt developer, but looking at other pieces of the code i found something that seems to fix the problem.
Please advice if this is the correct way to fix this. Happy to adjust the PR if needed.
Environment:
* Mac OS X Big Sur
* Drone running ArduCopter 4.0.5
* Single battery installed in Drone
=> Fix APM PowerComponent to use the battery FactGroups

src/Camera/QGCCameraControl.cc
QTime::msec only returns the msec component. Replaced with msecsTo to get the actual elapsed time in msec.
Environment:
* Mac OS X Big Sur
* Drone running ArduCopter 4.0.5
* Single battery installed in Drone
* Custom camera adapter in Basic Mavlink mode
=> Fix video recording time when camera provides recording_time_ms

src/AutoPilotPlugins/APM/APMSensorsComponent.qml, src/FactSystem/FactMetaData.cc, src/FirmwarePlugin/APM/APMSensorParams.qml
This introduces a Magnetic Declination field for Subs:
Two possible discussion points:
- ~Should we show it as degrees instead of radians ? Is something already there in the fact system that could help with the conversion?~
- Having the checkbox inverted (user clicks "Manual declination" instead of "Automatic Declination") makes more sense from a user perspective. This could be done by adding an "inverted" property to FactCheckBox, but [this binding](https://github.com/mavlink/qgroundcontrol/blob/master/src/FactSystem/FactControls/FactCheckBox.qml#L18) would double in size.
Fix #7310
=> Create field for manual Magnetic Declination setup for Submarines

src/QGCLoggingCategory.cc, src/QGCLoggingCategory.h, src/VideoReceiver/GStreamer.cc, src/VideoReceiver/GStreamer.h
* Created new VideoAllLog category which can be used to turn on all the individual video logging categories instead of having to do them one by one
* Separated logging from QGC GStreamer and GStreamer api debug level logging into their own categories. This way you can more easily tell what comes from where
So now customer support is something along these lines:
* Turn on VideoAllLog
* Set GStreamer debug output level to `Debug`
Trying to make QGC GStreamer support more easily remotely debuggable
=> Make GStreamer debugging simpler/clearer from an end user support perspective

src/AutoPilotPlugins/APM/APMFlightModesComponent.qml, src/AutoPilotPlugins/APM/APMFlightModesComponentController.cc, src/AutoPilotPlugins/APM/APMFlightModesComponentController.h
* The ui indication for whether an rc channel switch function was triggered was off by one
* Channel 16 rc function would never show correct ui indicator
* Replacement for #9305
=> ArduPilot - Flight Mode Setup page: Fix multiple off by ones in channel function code

src/VideoManager/SubtitleWriter.cc, src/VideoManager/SubtitleWriter.h
First commit fixes #8766 and the second updates the code to work with the new values widget.
=> Fix text overlay for recorded videos

src/Vehicle/Vehicle.cc
Fixed an issue where MSG_ID_PING of type response get parsed assuming ping type request.
The expected ping sequence is shown https://mavlink.io/en/services/ping.html
Current implementation wrongly respond to MSG_ID_PING which contain a ping response, with another ping response.
=> Fixed an issue where MSG_ID_PING are incorrectly handled

src/PlanView/PlanToolBarIndicators.qml
For missions of less than 1 hour this indicator was showing 1 hour plus the minutes of the mission. Also for missions longer than 24 hours we had overflow here. 
This commit fixes those issues, and now missions longer than 24 hours are indicated dd hh mm ss.
=> PlanToolBarIndicators: Fix mission time representation

src/QtLocationPlugin/MapboxMapProvider.cpp, src/QtLocationPlugin/MapboxMapProvider.h, src/QtLocationPlugin/QGCMapUrlEngine.cpp
Since **1st of June 2020** Mapbox migrated to new API and no longer supports requests to Legacy Maps and Legacy Static Images APIs. See blog post and deprecated style list as well as new map styles: 
- https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4
- https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/#which-classic-styles-are-being-deprecated
- https://docs.mapbox.com/api/maps/styles/#mapbox-styles
So since June all Mapbox maps show blank tiles. This PR fixes this.
=> Migrated to new Mapbox provider API

ChangeLog.md, src/AutoPilotPlugins/Common/RadioComponentController.cc
=> Fix double send of MAV_CMD_PREFLIGHT_CALIBRATION

src/MissionManager/MissionManager.cc, src/MissionManager/MissionManager.h
High latency messages provide wp_num field, which is meant to be used instead of MISSION_CURRENT when we are under high latency link. 
This PR provides support in mission manager so it takes the currentMissionIndex from high latency as well, so the highlighting of the active Waypoint over the map works under High latency as well.
=> MissionManager: get currentMissionIndex from High_lat messages

src/main.cc
This way we can run at the same time regular QGC and custom QGC and runguard will not block the execution of each other.
This was talked in slack a few months back, and it was suggested to use the executable name for the runguard. This way the runguards of daily and stable will block each other, but custom builds would be able to run independently.
I wasn't able to get the executable name, but with the approach of this commit we have the same effect, only Custom will be compatible with non custom, but stable and daily will still have same runguard and thus won't be able to run at the same time.
=> main.cc: Different runguard names for custom builds

src/Joystick/Joystick.cc, src/Joystick/Joystick.h, src/Joystick/JoystickManager.cc
This fixes a pure virtual method call exception during exit when a joystick is connected.
The problem was that ~Joystick() waited for the thread to exit, while the
thread called the virtual method _close(). But at this point the destructor
of the derived class (JoystickSDL in my case) was already called.
To resolve the problem a separate stop() method is added that is called
before deleting the object.
=> joystick: fix crash on app exit

deploy/create_linux_appimage.sh
When running the script and providing a local path as an argument for the release directory, the `rsync` command would fail, because `rsync` changes the directory and the relative path no longer applies. This only happens when `rsync` is ran inside the script. If I run the exact same command in the command line, it works. I'm not a bash ninja, so I don't know why. But canonicalizing the path fixes the problem :smile: 
- fixes errors when providing path arguments as local paths
- fixes error when output directory does not already exist
=> linux_appimage: canonicalize release_dir argument

cmake/Qt5QGCConfiguration.cmake, src/CMakeLists.txt, src/Compression/CMakeLists.txt, src/Vehicle/CMakeLists.txt, src/VehicleSetup/CMakeLists.txt, src/VideoReceiver/CMakeLists.txt
- use any Qt 5.12.x or 5.15.x version found
- prefers 5.12 over 5.15
- overridden by setting QT_VERSION
- add Compression (and XZ_EMBEDDED) to build
=> cmake updates and fixes

qgroundcontrol.pro, src/Vehicle/CMakeLists.txt, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/Vehicle/VehicleGPS2FactGroup.cc, src/Vehicle/VehicleGPS2FactGroup.h, src/Vehicle/VehicleGPSFactGroup.h
This PR adds support for GPS2_RAW messages, implemented within the factgroup system so the new field GPS2 can be selected in the main custom telemetry widget.
I've inherited vehicleGPSfactgroup totally and reimplemented the handle message function. This has been tested in v4.1.1, master isn't compiling to me right now. For the PR I rebased to master.
It has been tested with Ardupilot SITL and it works fine.
This PR addresses part of #9435, the airspeed part probably requires development of autopilot firmware as well, I can't see where mavlink is sending the second airspeed values.
=> Support for mavlink GPS2_RAW message

src/Vehicle/FTPManager.h
This fix a warning message in clang 11.
Moves from C struct definition to C++ standard style.
=> FTPManager: Fix struct definition

src/FlightDisplay/TelemetryValuesBar.qml, src/Settings/App.SettingsGroup.json, src/Settings/AppSettings.cc, src/Settings/AppSettings.h, src/ui/preferences/GeneralSettings.qml
Under some basemaps the default alpha value for this panel was too transparent for the user to see clearly the values. This commit makes this alpha channel variable by a setting under appsettings.
This addresses the issue #9433
=> TelemetryValuesBar: custom transparency by settings

src/VideoReceiver/README.md
Fix doc issue of commit 6afd4178d46a181bc3bcfdf9197179b478c193fc  and 465836c4bcd5e61be1b9c9aa4220b53a6552adba
NOTE: Since there are no update to gstreamer in IOS, i'm keeping the doc of IOS section remain still.
=> update Gstreamer version in readme to 1.18.1

src/Vehicle/Vehicle.cc
Joystick::_activeVehicle was still pointing to a vehicle after it got destroyed (e.g. on disconnect) and the thread continued to access it.
Ideally Joystick::_activeVehicle would be changed to a weak pointer.
@DonLakeFlyer your assessment in https://github.com/mavlink/qgroundcontrol/issues/9263 is correct, there was no protection. I did not see a crash, but I saw the pointer being dereferenced after free.
This should fix https://github.com/mavlink/qgroundcontrol/issues/9263
=> fix joystick: avoid accessing invalid pointer after vehicle is destroyed

src/FlightDisplay/VehicleWarnings.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
Fix #9380
With this, "No GPS Lock for Vehicle" will only show if the vehicle reports a GPS connected.
PX4 seems to always report a GPS. if there is none connected at boot, it's reported with an "error" status.
ArduPilot only reports a GPS after it is connected.
=> Vehicle: hide 'No GPS Lock' message if GPS is not present

src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
following the discussion in https://github.com/mavlink/qgroundcontrol/pull/9437 this PR removes the handling functions in vehicle for GPS2_RAW, so this mavlink message only updates the gps2 factgroup but does not affect the _coordinate of the vehicle.
=> Vehicle: don't update _coordinate from GPS2

src/ui/MainRootWindow.qml, src/ui/toolbar/MainToolBar.qml
* Using a Drawer to select Tools after clicking the Q icon was quirky from a user model standpoint. See #9396 for various problems.
* Changed to just use a regular dialog. I'm not super happy with that either but it is way less quirky and obvious as to how it works. I'll get back to this at some point when I get back to looking at the toolbar.
=> Change Tool Drawer to Dialog

src/Vehicle/Vehicle.cc
Backport https://github.com/mavlink/qgroundcontrol/pull/9378 to stable 4.1
=> [BACKPORT] fix joystick: avoid accessing invalid pointer after vehicle is destroyed

src/FlightDisplay/TelemetryValuesBar.qml
Following the discussion in https://github.com/mavlink/qgroundcontrol/issues/9433 this PR makes the panel opaque. It already includes the revert PR : https://github.com/mavlink/qgroundcontrol/pull/9450
Let me know if something additional is needed. Thanks!
=> Make telemetryvaluesbar opaque

src/MissionManager/MavCmdInfoCommon.json, src/MissionManager/MavCmdInfoFixedWing.json, src/MissionManager/MavCmdInfoMultiRotor.json
* Default Takeoff.Pitch value of 15 will only be set for Fixed Wing vehicles
* Adjust json command tree for correct usages of Pitch/Yaw by vehicle type
* Related to #9443
=> Fix Takeoff.Pitch/Yaw usage by vehicle type

src/FlightDisplay/TelemetryValuesBar.qml
Following the request from #9452, this is a cherry-pick of that fix over Stable v4.1.
=> TelemetryValuesBar: change panel from transparent to opaque

src/MissionManager/SimpleMissionItem.cc
* Altitude value not being set correctly when using terrain frame
* Caused incorrect missions to be generated
* Caused terrain display to not update correctly
* Fix #9408
=> Fix altitude setting for terrain frame mode

src/MissionManager/ComplexMissionItem.cc, src/MissionManager/ComplexMissionItem.h, src/MissionManager/FixedWingLandingComplexItem.cc, src/MissionManager/LandingComplexItemTest.cc, src/MissionManager/MissionController.cc, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/TransectStyleComplexItem.cc, src/MissionManager/VTOLLandingComplexItem.cc, src/QmlControls/FlightPathSegment.cc, src/QmlControls/FlightPathSegment.h
* The start/end of takeoff/land segments are ignored with respect to terrain collision. The distance ignored is 30 meters from beginning/end.
* Fix #9466, #9425
=> Ignore terrain collision on beginning/end of takeoff/land segments

qgroundcontrol.pro, qgroundcontrol.qrc, src/AutoPilotPlugins/PX4/PX4TuningComponent.cc, src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentCopterAll.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentCopterAttitude.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentCopterPosition.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentCopterRate.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentCopterVelocity.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentPlane.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneAll.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneTECS.qml, src/AutoPilotPlugins/PX4/PX4TuningComponentVTOL.qml, src/FirmwarePlugin/PX4/PX4Resources.qrc, src/QmlControls/PIDTuning.qml, src/Vehicle/LocalPositionFact.json, src/Vehicle/MAVLinkStreamConfig.cc, src/Vehicle/MAVLinkStreamConfig.h, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/Vehicle/VehicleLocalPositionFactGroup.cc, src/Vehicle/VehicleLocalPositionFactGroup.h, src/Vehicle/VehicleLocalPositionSetpointFactGroup.cc, src/Vehicle/VehicleLocalPositionSetpointFactGroup.h, src/Vehicle/VehicleSetpointFactGroup.cc
This continues the work from #9256:
- makes the plots + mavlink streams more generic
- adds mouse wheel zooming
- adds all MC controllers (attitude, velocity + position)
- adds MC_AIRMODE + THR_MDL_FAC params
- with links to docs (opening the external link did not work for me though, due to a Qt vs. system lib mismatch)
- adds MPC_POS_MODE for velocity + position controllers (this could possibly be set automatically, but we need to avoid user confusion and ensure it's always restored)
- adds vtol
- adds fw (not finished yet)
This is the MC rate controller page for a VTOL:
Basic FW TECS plot:
~Known issue: there is no scrollbar shown when the page overflows the vertical window size. @DonLakeFlyer I'd appreciate if you can have a look.~ fixed
Thanks to @dagar @MaEtUgR @RomanBapst for your …
=> PX4 PID tuning page continued

src/QmlControls/JoystickThumbPad.qml
It looks quite strange and was probably added for debugging purposes.
Before:
After:
=> JoystickThumbPad: remove red virtual joystick border

.github/workflows/buildQGCandDeploy.yml
**Problem**
We were having issues building and deploying for macOS via Travis.
**Solution**
Implement  build and deploy via Github Actions.
An action is created which triggers every time a tag is pushed. It will then proceed to build and deploy the artifacts generated by the build (in this case just the .dmg) as assets of the release of the same name as the tag pushed.
**Additional context**
Probably all deployments could be implemented in this same action, so every release could automatically create the assets for windows, android and macOS
=> Mac os build action

src/QtLocationPlugin/QGCLocationPlugin.pri
apparently when QGC used qt 5.5.1 there was some issue with qtlocation and this was included here as a workaround for that qt bug. We've been out of that conflicting version for a long time, so it should be safe to remove this now. I haven't removed the actual folder that instruction was pointing to, I don't know if it is interesting to keep it for code navigation purposes. Let me know if you consider that should be removed as well and I will add it to this PR. Thanks!
=> QGCLocationPlugin.pri: remove unused condition for old workaround:

cmake/Qt5QGCConfiguration.cmake
It'll use the system installation if there is no Qt installation under home
=> cmake: Qt5QGCConfiguration: Check for FOUND_QT_VERSIONS before continue

src/VideoReceiver/GstVideoReceiver.cc
This fixes https://github.com/mavlink/qgroundcontrol/issues/9440 (at least for me, Ubuntu 20.10, gstreamer 1.18.0).
=> Filter non-video streams before linking with parser

src/FlightMap/MapItems/CameraTriggerIndicator.qml
There were performance issues when too many icons of this kind were displayed on the map, probably because of the old image based nature of the icon. This commit changes it to a qml rectangles based icon. 
As discussed in issue #9501, the optimal way of addressing this would be by openGL shaders. This commit paints a camera icon based on qml rectangles instead, I am not familiarized with the openGL shaders approach right now, and I thought this could be a nice provisional fix.
The performance of QGC is not affected apparently anymore with this new icon. Some screenshots of the change:
Old icon:
New icon:
Let me know your thoughts, I will be happy to change the PR if needed. Thanks!
=> CameraTriggerIndicator: use a qml based icon instead:

src/PlanView/SimpleItemMapVisual.qml
* If the command was changed from a command which specified a coordinate to a command which did not it was not tracked correctly. This caused param5/6 to get screwed up on the mission item.
* Fix #9468
=> Simple mission item: Fix add/remove of drag area onSpecifiesCoordinateChanged

src/MissionManager/ComplexMissionItem.cc, src/MissionManager/LandingComplexItem.cc, src/MissionManager/SimpleMissionItem.cc, src/MissionManager/StructureScanComplexItem.cc, src/MissionManager/TransectStyleComplexItem.cc
* Home position updates where not flowing through to the individual items in all cases. This in turn caused the AMSL altitude for them to be incorrect.
* Related to #9495
=> Plan: Fix home position change singaling

src/Terrain/TerrainQuery.cc, src/Terrain/TerrainQuery.h
`TerrainQueries` typically don't work in the test cycle, but a while back i have contributed [special areas around Point Nemo](https://github.com/mavlink/qgroundcontrol/blob/master/src/Terrain/TerrainQuery.h#L301) where testing terrain-following `TransectStyleComplexItems` works.
Yet, we were missing a hill to verify transects are breaking on its top as expected and for LoS analysis. This only adds another useful region next to ones that are already there.
=> Add a hill region to testable TerrainQueries.

deploy/create_linux_appimage.sh
`$(_)` is used for commands, for variables the correct is `${_}`
=> deply: create_linux_appimage: Fix usage of QGC_CUSTOM_APP_NAME

QGCExternalLibs.pri
Basically unextracting the deb-file with ar and tar as dpkg would do, too.
Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com>
=> QCGExternalLibs: Getting independent of dpkg

src/FlightMap/MapItems/VehicleMapItem.qml
Noticed at some point the active vehicle map icon kept being transparent instead of fully opaque. After investigating found that it relied on an old property `Vehicle.active` which got removed in 66753e2111b1b7139664f8e354f2919c5b2e37f2
This PR fixes that and brings back the opaque icon.
Current:
Fix:
Fix (with mutliple vehicles):
=> Fix vehicle map item opacity

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/FirmwarePlugin/FirmwarePlugin.h, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc, src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h, src/Vehicle/Vehicle.cc
hobbs meter was working only for PX4. In ardupilot the parameter for this matter is STAT_FLTTIME. This PR adds support for this.
I separated the debug log messages for each of the cases, let me know if any change is needed here. Thanks!
=> Vehicle.cc: Support Ardupilot in hobbsMeter()

src/PositionManager/PositionManager.cpp, src/PositionManager/PositionManager.h
Addresses: https://github.com/mavlink/qgroundcontrol/issues/9471
Ubuntu location services are powered by [geoclue](https://gitlab.freedesktop.org/geoclue/geoclue/-/wikis/home), a service and framework that doesn't radiate with an aura of maturity:
```
$ cat /var/log/syslog | grep geoclue
...
Feb 24 07:17:35 remek-XPS-2 geoclue[6935]: Failed to query location: Forbidden
Feb 24 07:18:23 remek-XPS-2 systemd[1]: geoclue.service: Succeeded.
Feb 24 07:18:54 remek-XPS-2 dbus-daemon[1205]: [system] Activating via systemd: service name='org.freedesktop.GeoClue2' unit='geoclue.service' requested by ':1.43' (uid=125 pid=1688 comm="/usr/bin/gnome-shell " label="unconfined")
Feb 24 07:19:00 remek-XPS-2 whoopsie-upload-all[2637]: /var/crash/_usr_libexec_geoclue.122.crash already marked for upload, …
```
=> Only accept sufficiently accurate location updates

src/QtLocationPlugin/QGCTileCacheWorker.cpp, src/QtLocationPlugin/QGCTileCacheWorker.h
Hi, I'm working on fixing some stability issues that are popping up. This is a small pull request that fixes a couple of them. This PR aims to only fix issues which could cause undefined behavior. It does not fix a logic problem identified which could cause tasks queued quickly after starting the `QGCCacheWorker` to have spurious `Database Not Initialized` errors.
This fixes racey access on `QGCCacheWorker::_taskQueue` and `QGCCacheWorker::_valid`. It also has some slight refactoring to help readability and help ensure that exceptions thrown don't cause leaks in SQLite -- the refactoring was done while tracking down these issues.
I have drawn two sequence diagrams. They will be attached in comments to this PR next to one of the changes that the diagram represents.
The first diagram shows …
=> QGCCacheWorker Stability Fixes

src/comm/BluetoothLink.cc
For increased type safety, some enums have been changed to
scoped enums in Qt 6.2, see
https://codereview.qt-project.org/c/qt/qtconnectivity/+/336678
This patch adapts qgroundcontrol to this change.
Since C++11, enums inject their symbols in both their own
and their parent namespace, so this patch can be merged right
now.
Signed-off-by: Andreas Buhr <andreas.buhr@qt.io>
=> Use QtBluetooth enums from their namespace

src/QtLocationPlugin/QGCTileCacheWorker.cpp, src/QtLocationPlugin/QGCTileCacheWorker.h
* Fix racey access of `QGCCacheWorker::_taskQueue`
* `QGCCacheWorker::_valid` needs to be atomic
* Use `QScopedPointer<QSqlDatabase>` for safety
* Some refactoring for readability & debugging
(`git cherry-pick ac9b745a828a8be13c31f804fbe92e75717ec6cc`)
per https://github.com/mavlink/qgroundcontrol/pull/9588#issuecomment-824177632
=> QGCCacheWorker fixes (cherry-pick for Stable_V4.1)

src/Vehicle/InitialConnectStateMachine.cc
The initial connect state machine could get stuck prior to downloading parameters.
=> Fix state machine not being advanced in all cases

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc, src/FirmwarePlugin/APM/APMFirmwarePlugin.h, src/Vehicle/InitialConnectStateMachine.cc, src/Vehicle/Vehicle.cc, src/Vehicle/VehicleLinkManager.cc, src/Vehicle/VehicleLinkManager.h, src/Vehicle/VehicleLinkManagerTest.cc, src/comm/LinkInterface.cc, src/comm/LinkInterface.h, src/comm/LinkManager.cc, src/comm/LinkManager.h, src/comm/MAVLinkProtocol.cc, src/comm/MockLink.cc, src/comm/MockLink.h
This PR aims to fix [#9346](https://github.com/mavlink/qgroundcontrol/issues/9346). For AirMap, the JIRA ticket [BOSS-616].
Several issues identified and fixed.
* Many racey uses of [`if (weak_ptr::expired()) {... weak_ptr::lock() ... }`](https://en.cppreference.com/w/cpp/memory/weak_ptr/expired)
* `MockLink` had its own `_mavlinkChannel` shadowing the inherited `LinkInterface::_mavlinkChannel`. So `MockLink` always used channel 0 for lots of work which caused `VehicleLinkManagerTest::_multiLinkSingleVehicleTest` to fail very frequently when its two links would use the same mavlink buffer to parse a reply to the vehicle. Its failure would poison subsequent tests. 
That diagram is huge and hard to follow because it reflects how deep the two call stacks are with signals. This table might be …
=> Stability Fixes - Vehicle Link Manager Test

qgcimages.qrc, src/AutoPilotPlugins/Common/Images/Vectored6DofUUV.svg
Followed the [user guide](https://docs.px4.io/master/en/dev_airframes/adding_a_new_frame.html#adding-a-new-airframe-group) to complete the "new" airframe group for the vectored 6 DOF UUV airframe.
Related PRs:
- PX4/PX4-Autopilot#17434
- PX4/PX4-user_guide#1213
=> added svg for vectored 6 dof uuv airframe

src/Vehicle/ComponentInformationManager.h
Small fix for deprecated API build error (especially necessary for Qt 5.15). Build error fixed is:
```
.../src/Vehicle/ComponentInformationManager.cc:348:40: error: 'start' is deprecated: 
Use QElapsedTimer instead [-Werror,-Wdeprecated-declarations]
_downloadStartTime.start();
note: expanded from macro 'QT_DEPRECATED_X'
```
=> QTimer deprecated API build error fix

src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
Before this change it is not allowed to set up the flight modes unless all sensor calibrations are completed.
I don't think that makes sense because it is possible to calibrate RC without having the sensors calibrated, and it's the logical next step right after that.
It is also a problem if HITL (hardware-in-the-loop) is used where the sensors are not marked as calibrated but you still need to be able to configure the flight modes. This is what prompted me to suggest this change.
=> PX4: allow flight mode setup without sensors calibrated

qgroundcontrol.pro, src/MissionManager/MissionManagerTest.h, src/MissionManager/PlanManager.cc, src/MissionManager/PlanManager.h, src/Vehicle/InitialConnectStateMachine.cc, src/Vehicle/InitialConnectStateMachine.h, src/Vehicle/InitialConnectTest.cc, src/Vehicle/InitialConnectTest.h, src/Vehicle/RequestMessageTest.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/comm/MockLink.cc, src/comm/MockLink.h, src/qgcunittest/UnitTest.cc, src/qgcunittest/UnitTest.h, src/qgcunittest/UnitTestList.cc
The initial connect sequence had bugs in it with respect to lost responses to things like `AUTOPILOT_VERSION` or 'PROTOCOL_VERSION'. This could cause the connect sequence to hang and never complete. Made a pile of changes to fix this up as well as create MockLink support and units tests to validates the failure conditions. 
* MockLink - Support REQUEST_MESSAGE:AUTOPILOT_VERSION, REQUEST_MESSAGE:PROTOCOL_VERSION
* Fix bugs in Vehicle::requestMessage
* Switch to all INT mission items
* Create unit tests to exercise Initial Connect state mache state failure conditions
* Change initial connect sequence state machine to use REQUEST_MESSAGE for `AUTOPILOT_VERSION` or 'PROTOCOL_VERSION' states
=> Hardening of inital connect sequence to boundary conditions

.gitmodules, QGCExternalLibs.pri, libs/libevents/definitions.cpp, libs/libevents/libevents_definitions.h, qgroundcontrol.pro, src/Vehicle/CompInfoEvents.cc, src/Vehicle/CompInfoEvents.h, src/Vehicle/ComponentInformationManager.cc, src/Vehicle/ComponentInformationManager.h, src/Vehicle/EventHandler.cc, src/Vehicle/EventHandler.h, src/Vehicle/HealthAndArmingChecks.cc, src/Vehicle/HealthAndArmingChecks.h, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h
It will replace the `STATUSTEXT` mavlink messages with event ID's + metadata.
Full details: https://docs.google.com/document/d/18qdDgfML97lItom09MJhngYnFzAm1zFdmlCKG7TaBpg/edit
PR for PX4: https://github.com/PX4/PX4-Autopilot/pull/16293
@DonLakeFlyer @dogmaphobic can you go through it to check if you miss something?
In particular:
- event descriptions can contain URL's which should eventually be clickable and open the link.
- event descriptions can contain params (they can be tagged as a URL). Clicking on those should open the param edit dialog and I believe this is possible with custom URL handlers.
- for health reporting you get this information: https://github.com/mavlink/qgroundcontrol/commit/0aa362be6ca1024b08c59abb861f0d1d6c055f93#diff-2a76975fc3bdcd8b6958c58a3db89aa591bc14ce457863bf …
=> Events interface (first iteration)

.travis.yml
* Linux debug no longer built
* Linux, OSX Installer only built for merged pulls since GitHub Action S3 Upload still not working
=> Deprecate some travis builds, replaced by GitHub Actions

deploy/docker/Dockerfile-build-linux
Fixes two problems:
- Fix and use default user to avoid the creation/modification of files as root
- Remove git commands since it breaks git internals when running inside docker
=> Fix build problems with docker

QGCExternalLibs.pri, qgroundcontrol.qrc, src/MissionManager/MissionController.cc, src/MissionManager/MissionController.h, src/MissionManager/MissionControllerTest.cc, src/MissionManager/SimpleMissionItem.cc, src/PlanView/CorridorScanEditor.qml, src/PlanView/GeoFenceEditor.qml, src/PlanView/MissionSettingsEditor.qml, src/PlanView/SimpleItemEditor.qml, src/PlanView/SurveyItemEditor.qml, src/QmlControls/AltModeDialog.qml, src/QmlControls/QGroundControl/Controls/qmldir, src/QmlControls/QGroundControlQmlGlobal.cc, src/QmlControls/QGroundControlQmlGlobal.h
* I'm working my towards support Terrain Frame (MAV_FRAME_GLOBAL_TERRAIN_ALT) in Surveys
* First step was taking another cleanup pass through the "Altitude Mode" concept
* Changed naming of "Above Terrain" to "Calculated Above Terrain" to be more specified
* Change Alt Mode selection from Combo dropdown to full dialog to provide better information on each possibility
* If you always use Relatative Alts and don't know anything about what I'm talking about then the UI for you will look exactly like it did before
Mission Start
* New Alt Mode picker dialog
* You also get this dialog when picking Alt Mode from a simple item if you are using Mixed Modes
Simple Item Editor
* New ui for altitude value display. Showing non-relative example. Relative Alts ui is still as before.
=> Rework altitude mode internals/ui

.gitignore, libs/CMakeLists.txt, libs/shapelib/CMakeLists.txt, libs/zlib/CMakeLists.txt, src/CMakeLists.txt
ignore typical IDE folders (CLion, VSCode)
exclude none windows compiler flags, make zlib include/linker files available
- cl : Command line error D8021 : invalid numeric argument '/Wno-missing-braces'
- ..\src\VehicleSetup\FirmwareUpgradeController.cc(29): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
=> fix cmake issues on windows
