mavlink/qgroundcontrol

qgroundcontrol.pro

Title says it all. These two modules were added but have not been maintained. Disabling both until they are properly finished and tested.

Disable both Taisync and Microhard until they are properly finished.

---

src/FlightMap/Widgets/VideoPageWidget.qml
src/VideoStreaming/VideoReceiver.cc

Save the video files with the specified configuration name

Record video with name

---

src/VideoStreaming/CMakeLists.txt

It had to be a part of https://github.com/mavlink/qgroundcontrol/pull/8348 ...

Fix CMake build (src/VideoStreaming/CMakeLists.txt)

---

src/AnalyzeView/LogDownloadPage.qml
src/QmlControls/QGCViewDialogContainer.qml

QGCViewDialog: Remove close dialog from click handlers

---

src/MissionManager/MissionController.cc

Plane: Fix waypoint linkage to first item

---

src/FlightDisplay/FlightDisplayView.qml

Clicking on the checklist no longer closes any open action dialogs, e.g Start Mission

Clicking on checklist no longer closes action dialog

---

src/FlightDisplay/FlightDisplayView.qml
src/ui/MainRootWindow.qml

Added function to FlightView to show the checklist if switching view from a view other than FlightView and if checklist should be shown.

Show checklist if needed

---

src/MissionManager/QGCMapPolyline.h
src/MissionManager/QGCMapPolylineVisuals.qml
src/PlanView/CorridorScanEditor.qml
src/PlanView/StructureScanEditor.qml

Plan: Structure/Corridor Fix Done Tracing <-> Done PolyFoo in wizard relationship

---

.github/ISSUE_TEMPLATE/feature_request.md

github: Add feature request

---

src/VideoStreaming/VideoStreaming.cc
src/VideoStreaming/VideoStreaming.pri

Fixes TCP video source for Android and iOS.

Fix TCP for Android and iOS

---

src/MissionManager/ComplexMissionItem.cc
src/PlanView/SurveyItemEditor.qml
src/api/QGCOptions.h

* Built in presets cannot be deleted. Not pretty but simple enough for this late in the game with Stable.
* Deleting a preset pops an Are you sure? dialog

Preset work: Allow custom build to specify which presets are built in

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h

Remove some more Follow stuff

---

src/VideoStreaming/VideoReceiver.cc

Same as https://github.com/mavlink/qgroundcontrol/pull/8416 but against Stable_V4.0

GStreamer ref counting

---

src/QmlControls/ToolStrip.qml

Fix auto-display of Plan/File

---

src/VehicleSetup/FirmwareUpgradeController.cc

Better logging for ArduPIlot manifest lookup

---

src/VehicleSetup/FirmwareUpgradeController.cc

Even better manifest logging

---

src/Vehicle/Vehicle.cc

Fix broken ADSB vehicle code

---

src/MissionManager/MissionController.cc

Fix ArduPilot fake home position handling

---

src/FlightMap/Widgets/MapFitFunctions.qml
src/MissionManager/SurveyComplexItem.cc

* Need to make sure to turn off alternate transects for non fixed wing style vehicle

Plan: Fix alternate transects

---

src/FlightMap/Widgets/MapFitFunctions.qml

Fix for #8462. Someday I'll get this code right!

MapFitFunctions: Fix even more bugs

---

.travis.yml

Still fighting with OSX github release upload failure

Travis: Add missing V2 provider

---

.travis.yml

It just causes the whole build to fail

Travis: Don't push tagged OSX build to GitHub

---

src/FlightDisplay/FlightDisplayView.qml

Closes https://github.com/mavlink/qgroundcontrol/issues/8437

Move the pre-flight checklist to the upper left corner of the screen.

---

src/QmlControls/ToolStrip.qml

Fix empty Plan File dropdown display

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml

fixed bug: the highlight mode is not the actually mode

fixed bug: the highlight mode is not the actually mode

---

src/MissionManager/TakeoffMissionItem.cc

Takeoff item wizard mode fix

---

src/FlightDisplay/PreFlightSensorsHealthCheck.qml

Fixes preflight sensors check passsing when no vehicle is connected

fixed preflight sensors check

---

src/ui/preferences/GeneralSettings.qml

Add note about ADSB server settings

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml

Cherry pick of #8483 to Stable_V4.0

Flight mode fix, cherry picked from master

---

CMakeLists.txt
src/VideoStreaming/VideoStreaming.pri

Cherry-picked 26a897bb4995f3859066277dfa186c8564154fa3 from Stable_4.0 (https://github.com/mavlink/qgroundcontrol/pull/8522)

Add EGL to gstreamer dependecies

---

src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

More changes to ArduPilot manifest lookup

---

src/Terrain/TerrainQuery.cc

Cherry pick from master

---

src/Vehicle/Vehicle.cc

Fix bad cast causing loss of precision with sequence numbers

---

src/PlanView/MissionItemEditor.qml
src/PlanView/PlanView.qml

* Better alignment of header items
* Smaller margins to give more space to important ui bits
Before:
After:

Plan: Visual tweaks for mission items

---

src/AutoPilotPlugins/APM/APMSafetyComponent.qml
src/AutoPilotPlugins/Common/RadioComponent.qml

Fixes: #8571, #8572
Also reworked Copter RTL settings to make more sense:

Fix Radio button problems

---

src/QmlControls/QGCFileDialogController.cc

Mobile File Dialog: Fix file extension appending

---

src/VideoStreaming/VideoManager.cc
src/VideoStreaming/gstqgcvideosinkbin.c

1. Add "sync" option to gstqgcvideosinkbin (from Stable 4.0 PR)
2. Small cosmetics tweak

gstqgcvideosinkbin update

---

src/ui/MainRootWindow.qml

Same as https://github.com/mavlink/qgroundcontrol/pull/8590

Adjust minimum application window size

---

src/FirmwarePlugin/PX4/MavCmdInfoMultiRotor.json
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MissionCommandUIInfo.cc
src/MissionManager/MissionCommandUIInfo.h
src/MissionManager/MissionController.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/TakeoffMissionItem.cc
src/MissionManager/VisualMissionItem.h
src/PlanView/PlanView.qml
src/PlanView/SimpleItemEditor.qml

This is a replacment for #8497 which will go into master.

VTOL Fixes

---

.travis.yml

Working towards fixing google play upload. Or at least trying yet again over and over and over again.

Travis: Turn google play upload back on

---

src/GPS/GPSPositionMessage.h
src/GPS/GPSProvider.h
src/GPS/vehicle_gps_position.h

To be consistent with PX4, for more context see https://github.com/PX4/Firmware/pull/14447
FYI @bkueng

Update GPS struct name to match PX4

---

src/AutoPilotPlugins/APM/APMCompassCal.cc

Removed 'rejected' variable (see #8583)

Removed unused variable

---

src/PlanView/MissionItemEditor.qml

Item editor hamburger was missing

Plan: Fix hamburger positioning

---

qgroundcontrol.pro
src/KMLDomDocument.cc
src/KMLDomDocument.h
src/KMLHelper.cc
src/KMLHelper.h
src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/KMLPlanDomDocument.cc
src/MissionManager/KMLPlanDomDocument.h
src/MissionManager/MissionController.cc
src/MissionManager/QGCMapPolygon.cc
src/MissionManager/QGCMapPolygon.h
src/MissionManager/QGCMapPolyline.cc
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h
src/PlanView/TransectStyleMapVisuals.qml
src/QGCPalette.cc
src/QGCPalette.h
src/ShapeFileHelper.cc

Plan: Output Survey polygons with KML save

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

Adds current WP index as a Vehicle Fact for use to display in the values widget.

WP index to the values widget

---

ChangeLog.md
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FlightDisplay/FlightDisplayView.qml
src/FlightDisplay/GuidedActionsController.qml

Replacement for #8621 
@samuelctabor After a bunch of testing I believe this is the fix for the problem you reported. It incorporates part of your pull as well as other changes.

Fly: Fix display of Continue Mission/Change Alt after Pause

---

src/QmlControls/QGCFileDialog.qml
src/QmlControls/QGCFileDialogController.cc
src/QmlControls/QGCFileDialogController.h

Mobile QGCFileDialog: Show dir location

---

src/FlightMap/Widgets/ValuePageWidget.qml
src/QmlControls/QGCFileDialog.qml
src/QmlControls/QGCLabel.qml

Some strange Qt layout bug causing text to not display even though it was all there in correct placement.

Fix blank instrument values page after changing to another page

---

src/FlightMap/Widgets/ValuePageWidget.qml
src/FlightMap/Widgets/ValuesWidgetController.cc
src/FlightMap/Widgets/ValuesWidgetController.h

Instrument Values: Icon picker support

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/FlightMap/Widgets/ValuePageWidget.qml
src/QGCApplication.cc
src/QmlControls/ParameterEditor.qml
src/QmlControls/ParameterEditorController.cc
src/QmlControls/ParameterEditorController.h
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCPopupDialog.qml
src/QmlControls/QGCPopupDialogContainer.qml
src/QmlControls/QGroundControl/Controls/qmldir
src/QmlControls/RCToParamDialog.FactMetaData.json
src/QmlControls/RCToParamDialog.qml
src/QmlControls/RCToParamDialogController.cc
src/QmlControls/RCToParamDialogController.h
src/QmlControls/ScreenTools.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MockLink.cc
src/comm/MockLink.h
src/uas/UAS.cc
src/uas/UAS.h
src/uas/UASInterface.h
src/ui/MainRootWindow.qml

* Fixes: #8585, #8382
* Also includes some changes to showPopupDialog:
* No need to pass in title and buttons. You now set them in the component itself.
* Ability to pass additional dialog properties from the showPopupDialog call. This allow you to provide external context to the dialog if needed.

Set RC To Param support

---

src/FactSystem/ParameterManager.cc

Fixes for https://github.com/PX4/Firmware/issues/11072, #4485

Cache new metadata if versions are equal

---

src/FlightDisplay/PreFlightCheckList.qml

See https://github.com/mavlink/qgroundcontrol/pull/8633#event-3236058051 for reference.

Fix magic reference to vehicle in PreFlightChecklist

---

src/FactSystem/FactControls/AltitudeFactTextField.qml
src/MissionManager/CameraCalc.cc
src/MissionManager/CameraCalc.h
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/TransectStyle.SettingsGroup.json
src/MissionManager/TransectStyleComplexItem.cc
src/PlanView/CameraCalcCamera.qml
src/PlanView/CameraCalcGrid.qml
src/PlanView/CorridorScanEditor.qml
src/PlanView/StructureScanEditor.qml
src/PlanView/SurveyItemEditor.qml

* Tolerance adjustment step was leaving unecessary waypoints within transects
* Plus a bunch of smaller visual tweaks

Plan - Terrain Follow: Fix tolerance adjustment step

---

src/QGCApplication.h

QGCApplication: Use forward declaration in QQmlApplicationEngine

---

.gitmodules
VideoReceiverApp/README.md
VideoReceiverApp/main.cpp
custom-example/res/CustomCameraControl.qml
custom-example/src/CustomPlugin.cc
custom-example/src/CustomPlugin.h
custom-example/src/CustomVideoManager.cc
custom-example/src/CustomVideoManager.h
src/FlightDisplay/FlightDisplayViewVideo.qml
src/FlightMap/Widgets/VideoPageWidget.qml
src/VideoManager/VideoManager.cc
src/VideoManager/VideoManager.h
src/VideoReceiver/GStreamer.cc
src/VideoReceiver/GstVideoReceiver.cc
src/VideoReceiver/GstVideoReceiver.h
src/VideoReceiver/README.md
src/VideoReceiver/VideoReceiver.h
src/api/QGCCorePlugin.cc
src/api/QGCCorePlugin.h

This PR
- fixes build issues for Android and iOS
- updates video receiver docs according to latest changes
- fixes many state tracking issues (video reconnect/(re)start/etc)
- enables better video receiver customization support
- adds low latency mode introduced in v4.0.5

Small video tweaks

---

src/MissionManager/CMakeLists.txt

Fix MissionManager (cmake)

---

src/Camera/QGCCameraControl.cc
src/Camera/QGCCameraManager.h
src/Joystick/Joystick.h
src/Vehicle/Vehicle.h
src/comm/MockLink.h

- This fix a bunch of warning messages related to QTime functions that will be deprecated

Fix more QTime deprecated functions

---

qgroundcontrol.pro
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/LandingComplexItem.cc
src/MissionManager/LandingComplexItem.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/VTOLLandingComplexItem.cc
src/MissionManager/VTOLLandingComplexItem.h
src/QmlControls/TerrainProfile.cc

* LandingComplexItem is new base class for FixedWingLandingPattern and VTOLLandingPattern
* Still more refactoring to the base class to do. This first pass creates a single piece of code where I was finding bugs in both side to fix.

New LandingComplexItem base class for landing patterns

---

src/FactSystem/FactMetaData.cc

I missed a spot when addressing review comments last time round - sorry.

Vertical units - fix omission

---

src/MissionManager/MissionController.cc

Fix logic of when adding Landing item is allowed

---

custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc

remove warning caused build failure

Add return in CustomFirmwarePlugin::hasGimbal

---

src/VideoStreaming/VideoReceiver.cc

Video Settings: Case insensitive protocol string matching

---

src/VideoReceiver/GstVideoReceiver.cc

Video Settings: Case insensitive protocol detection

---

ChangeLog.md
src/Vehicle/Vehicle.cc

Fix ADSB vehicle setup

---

src/comm/QGCMAVLink.cc

Fix boat classification as a Rover

---

ChangeLog.md
src/FlightDisplay/FlyViewWidgetLayer.qml
src/FlightDisplay/VirtualJoystick.qml
src/QmlControls/JoystickThumbPad.qml
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/ui/preferences/GeneralSettings.qml

Cherry pick virtual joystick fix from Stable

---

ChangeLog.md
ios/iOS-Info.plist
src/Settings/AppSettings.cc
src/api/QGCCorePlugin.cc

* This allows for management of QGC files on iOS devices
* Fix for #8770

Tweaks to iOS storage location to support display in new Files app

---

ChangeLog.md
ios/iOS-Info.plist
src/Settings/AppSettings.cc
src/api/QGCCorePlugin.cc

Cherry pick to master of #8799

Tweaks to iOS storage location to support display in Files app

---

QGCCommon.pri

Also includes initial work for `WarningsAsErrorsOff` support

Fix up windows warnings as errors

---

ChangeLog.md
src/MissionManager/SimpleMissionItem.cc

Use specifiesAltitude instead of specifiesCoordinate in correct places

---

src/FactSystem/FactControls/AltitudeFactTextField.qml
src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h
src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h
src/MissionManager/SimpleMissionItem.cc
src/PlanView/CameraCalcGrid.qml
src/PlanView/MissionSettingsEditor.qml
src/PlanView/SimpleItemEditor.qml
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Initial support for global plan-wide altitude mode setting

---

src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/QmlControls/QmlUnitsConversion.h

`appSettingsSpeedUnitsString()` method added to `QmlUnitsConversion` class.

appSettingsSpeedUnitsString() method added

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/FirmwarePlugin/APM/APMSensorParams.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

ArduPilot: Compass priority support

---

ChangeLog.md
src/comm/QGCSerialPortInfo.cc

Special case handling for Cube Orange/Yellow

---

.travis.yml
QGCPostLinkInstaller.pri

Code signing off for now

---

qgroundcontrol.pro
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/APM/APMParameterMetaData.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/FirmwarePlugin/PX4/PX4ParameterMetaData.h
src/Vehicle/CompInfo.cc
src/Vehicle/CompInfo.h
src/Vehicle/CompInfoParam.cc
src/Vehicle/CompInfoParam.h
src/Vehicle/CompInfoVersion.cc
src/Vehicle/CompInfoVersion.h
src/Vehicle/ComponentInformationManager.cc
src/Vehicle/ComponentInformationManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/FirmwareImage.cc
src/comm/MockLink.Parameter.MetaData.json

* As is the fallback to the old system if it's not available through COMPONENT_INFORMATION
* Only thing left to support is:
* http json download
* json caching
* Related to https://github.com/mavlink/mavlink/issues/1346

Parameter metadata from COMPONENT_INFORMATION is working

---

src/VehicleSetup/SetupView.qml

Cherry pick to Stable of #8870

Fix Summary button check state

---

src/MissionManager/MissionController.cc
src/comm/QGCMAVLink.cc
src/comm/QGCMAVLink.h

Plan: Upload pre-check must be vehicle-class based

---

src/ADSB/ADSBVehicleManager.cc

Fix ADSB crash

---

src/VehicleSetup/Bootloader.cc
src/VehicleSetup/Bootloader.h

Fix Bootloader crash

---

src/VehicleSetup/Bootloader.cc
src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/VehicleSetup/PX4FirmwareUpgradeThread.cc
src/VehicleSetup/PX4FirmwareUpgradeThread.h

Major rework of flash to prevent SiK radio bricking in bootloader mode

---

src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
src/AutoPilotPlugins/APM/APMAirframeComponentController.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/QGCApplication.cc
src/QGCApplication.h
src/QGCFileDownload.cc
src/QGCFileDownload.h
src/Vehicle/ComponentInformationManager.cc
src/Vehicle/ComponentInformationManager.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/MockLink.cc

Related to https://github.com/mavlink/mavlink/issues/1346

COMPONENT_INFORMATION http download support

---

src/AutoPilotPlugins/Common/RadioComponentController.cc
src/AutoPilotPlugins/Common/RadioComponentController.h
src/QmlControls/RCChannelMonitorController.cc
src/QmlControls/RCChannelMonitorController.h

Radio Cal/Monitor: Handle max channel correctly

---

src/FlightDisplay/FlyViewMap.qml
src/FlightDisplay/GuidedActionsController.qml

Fix ROI, Orbit, Goto handling

---

src/PlanView/PlanToolBarIndicators.qml

Related to #8873
Needs to be fixed in master as well

Gradient units are degrees

---

src/FlightDisplay/FlightDisplayViewMap.qml

Fixes for ROI, Orbit, Goto

---

src/comm/QGCSerialPortInfo.cc

Serial number based composite usb check

---

src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGCTileCacheWorker.h

Delete bogus Bing no data tiles from cache

---

src/MissionManager/MissionController.cc

* Also fixes some incorrect profile display when there is no takeoff item
* Fix #8908

Plan: Fix item initialization problems leading to crashes and incorrect profile display

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionControllerTest.cc
src/MissionManager/MissionControllerTest.h
src/MissionManager/SimpleMissionItem.cc

* Includes unit test to prevent it coming back
* Fix for #8910

Plan: Fix global alt mode support

---

src/QmlControls/VerticalFactValueGrid.qml

* You can now add as many columns as you want but if you add too many you'll need to scroll to get to them
* Fix for #8819

Horizontal scrolling as needed

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MAVLinkProtocol.cc

Add HIGH_LATENCY message handle

Add high latency handle

---

src/comm/UDPLink.cc
src/comm/UDPLink.h

* Add mutex on _sessionTargets access
* Remove all C++ range_for usage
* General coding style cleanup
* Fix for #8934

Udp link mutex

---

src/MissionManager/PlanMasterController.cc
src/MissionManager/PlanMasterController.h
src/PlanView/PlanView.qml

Better handling of vehicle change state transitions

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/USBBoardInfo.json

Add X7 support

---

qgroundcontrol.qrc
src/QmlControls/QGCViewDialog.qml
src/QmlControls/QGCViewDialogContainer.qml
src/ui/MainRootWindow.qml

Support stacked component dialogs

---

src/FlightDisplay/FlyView.qml
src/FlightDisplay/FlyViewInstrumentPanel.qml
src/FlightDisplay/FlyViewMap.qml
src/FlightDisplay/FlyViewMissionCompleteDialog.qml
src/FlightDisplay/FlyViewToolStrip.qml
src/FlightDisplay/FlyViewToolStripActionList.qml
src/FlightDisplay/FlyViewWidgetLayer.qml
src/FlightDisplay/GuidedActionActionList.qml
src/FlightDisplay/GuidedActionLand.qml
src/FlightDisplay/GuidedActionPause.qml
src/FlightDisplay/GuidedActionRTL.qml
src/FlightDisplay/GuidedActionTakeoff.qml
src/FlightDisplay/GuidedToolStripAction.qml
src/FlightDisplay/MultiVehicleList.qml
src/FlightDisplay/MultiVehiclePanel.qml
src/FlightMap/MapItems/PlanMapItems.qml
src/ui/MainRootWindow.qml

Fixes bug in Resume Misssion where resume mission button was blank

Move GuidedActionsController references to global

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Fix C++ 20 compiler warning

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/QmlControls/FlightModeMenu.qml
src/QmlControls/QGCMenu.qml
src/Vehicle/TrajectoryPoints.cc
src/ui/MainRootWindow.qml
src/ui/toolbar/BatteryIndicator.qml
src/ui/toolbar/GPSIndicator.qml
src/ui/toolbar/GPSRTKIndicator.qml
src/ui/toolbar/JoystickIndicator.qml
src/ui/toolbar/MainStatusIndicator.qml
src/ui/toolbar/MainToolBar.qml
src/ui/toolbar/RCRSSIIndicator.qml
src/ui/toolbar/ROIIndicator.qml
src/ui/toolbar/TelemetryRSSIIndicator.qml

VTOL example:
Arm/Disarm/Emergency stop are in main status dropdown:

Fly: Move flight mode, vtol mode, armed into main status

---

ChangeLog.md
src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml
src/AutoPilotPlugins/APM/APMTuningComponentCopter.qml
src/AutoPilotPlugins/APM/APMTuningComponentSub.qml
src/FlightDisplay/GuidedActionsController.qml
src/PlanView/CameraCalcCamera.qml
src/QmlControls/ParameterEditor.qml
src/QmlControls/QGCButton.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/AppSettings.qml
src/ui/MainRootWindow.qml
src/ui/preferences/BluetoothSettings.qml
src/ui/preferences/LinkSettings.qml
src/ui/preferences/UdpSettings.qml
src/ui/toolbar/MainStatusIndicator.qml

* Press and hold on Arm button will change it to Force Arm. Click again to Force Arm
* Switched QGCButton to Controls 2 version in order to get pressAndHold support
* Fix for #6624

Force arm support

---

src/PlanView/TerrainStatus.qml

Terrain Status: Convert to app units as needed

---

src/PlanView/TerrainStatus.qml

Terrain Status: Fix typo

---

src/VehicleSetup/Bootloader.cc

https://github.com/PX4/Firmware/pull/15542

bootloader avoid syncing multiple times if first succeeded

---

src/QGCApplication.cc
src/Settings/App.SettingsGroup.json

Add Azerbaijani language

---

src/Vehicle/CompInfoParam.cc
src/Vehicle/CompInfoParam.h
src/comm/MockLink.Parameter.MetaData.json

* 'FOO<#>_BAR' name will match 'FOO1_BAR', 'FOO12_bar', ...
* Reduces file size by reducing duplication

COMPONENT_INFORMATION: Parameter json metadata - support 'FOO<#>_BAR' param name metadata

---

src/FirstRunPromptDialogs/OfflineVehicleFirstRunPrompt.qml
src/PlanView/MissionSettingsEditor.qml

* Remove mission speed settings from first run prompt since nobody understands what these are
* Add note about mission speeds in Plan:Mission Start about these not affect mission flight speed

Mission speeds

---

src/comm/LinkManager.cc

This way you can tell if QGC is trying to connect to the right thing

Vehicle Not Responding: Include port name

---

qgroundcontrol.qrc
src/FactSystem/Fact.cc
src/FactSystem/FactGroup.cc
src/FactSystem/FactGroup.h
src/FlightDisplay/FlyViewVideo.qml
src/FlightDisplay/ProximityRadarValues.qml
src/FlightDisplay/ProximityRadarVideoView.qml
src/FlightMap/MapItems/ProximityRadarMapView.qml
src/QGCApplication.cc
src/QmlControls/QGCFileDialog.qml
src/QmlControls/QGroundControl/FlightDisplay/qmldir
src/Vehicle/DistanceSensorFact.json
src/Vehicle/VehicleBatteryFactGroup.cc
src/Vehicle/VehicleClockFactGroup.cc
src/Vehicle/VehicleDistanceSensorFactGroup.cc
src/Vehicle/VehicleDistanceSensorFactGroup.h
src/Vehicle/VehicleEstimatorStatusFactGroup.cc
src/Vehicle/VehicleSetpointFactGroup.cc
src/Vehicle/VehicleTemperatureFactGroup.cc
src/Vehicle/VehicleVibrationFactGroup.cc
src/Vehicle/VehicleWindFactGroup.cc

* Started out as fixing the fact that proximity distance value wasn't showing correct number of decimal places
* Ended up with a big refactor and fixes
* I added is a new FactGroup::telemetryAvailable property which if false tells you that there hasn't been any telemetry associated with these facts yet

Refactor/fixes for ProximityRadar and friends

---

src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/TransectStyleComplexItem.h

Store terrain follow flight speed in Plan file to prevent recalcs on Load

---

src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/LandingComplexItem.cc
src/MissionManager/LandingComplexItem.h
src/MissionManager/VTOLLandingComplexItem.cc
src/MissionManager/VTOLLandingComplexItem.h

Moved more code from Fixed Wing/VTOL landing complex item classes to base class

Plan: More refactoring to LandingComplexItem base class

---

CMakeLists.txt
QGCCommon.pri
custom-example/res/CustomFlyView.qml
src/Camera/QGCCameraManager.cc
src/Camera/QGCCameraManager.h
src/Joystick/Joystick.cc
src/Joystick/Joystick.h

Bringing changes and additions from downstream.

SRR Updates

---

QGCCommon.pri
src/Vehicle/MultiVehicleManager.cc
src/comm/QGCSerialPortInfo.cc

Fix composite USB detection

---

src/MissionManager/TransectStyleComplexItem.cc

TransectStyleComplexItem-Terrain: Fix min/max AMSL alt calc

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

FirmwarePlugin: APM: Update link for stable version

---

src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h

This mode was just added to ArduPlane, [PR](https://github.com/ArduPilot/ardupilot/pull/15358) .

ArduPlaneFirmwarePlugin: Add THERMAL mode.

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h
src/comm/USBBoardInfo.json

Add Nora support

---

custom-example/res/CustomCameraControl.qml

Bringing updates from downstream.

SRR Update

---

src/AutoPilotPlugins/Common/RadioComponentController.cc

Fix the useless code in RadioComponentController.cc

Remove useless codes 

---

src/MissionManager/PlanManager.cc
src/Vehicle/Vehicle.cc

Fix problem with incorrect futzing of x/y params.

Fix MISSION_ITEM_INT bugs

---

src/QmlControls/QGCTabButton.qml

QGCTabButton: Display fixes

---

src/QmlControls/AppMessages.qml

Console: Fix filter dialog clipping

---

src/ui/toolbar/MultiVehicleSelector.qml

* Fix for #9135
* I don't have a great way of simulating this yet so I'm just doing it from code inspection. But I think I found it.

Multi-Vehicle Selector: Fix combo box updating

---

src/AutoPilotPlugins/PX4/BatteryParams.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml

PX4 Pro Power - Add support for BAT#_SOURCE

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h

* Removed WiFi cal warning since this is no longer valid
* Related to https://github.com/ArduPilot/ardupilot/issues/3333

ArduPilot: Calibration no longer uses text messages for state machine

---

src/QmlControls/FactValueGrid.h
src/QmlControls/HorizontalFactValueGrid.cc
src/QmlControls/HorizontalFactValueGrid.h

* Also move telemetry bar to non WIP. This unfortunately requires a settings name change so telemetry bar setup will need to be redone.
* Related to #8915

Changes to FactValueGrid usage for reading settings only

---

src/VehicleSetup/Bootloader.cc
src/VehicleSetup/FirmwareUpgrade.qml
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Fix SiK Radio flash

---

src/FlightDisplay/FlyViewPreFlightChecklistPopup.qml
src/FlightDisplay/FlyViewWidgetLayer.qml
src/FlightDisplay/PreFlightBatteryCheck.qml
src/FlightDisplay/PreFlightCheckList.qml
src/FlightDisplay/PreFlightRCCheck.qml
src/QmlControls/PreFlightCheckButton.qml

* Completely broken by control changes to Controls 2
* Move to use QGCPopupDialog
* Fix for #9187

Fix Pre-Flight checklist

---

src/Settings/VideoSettings.cc

Give user hint about Solo needs app restart

---

android/AndroidManifest.xml
android/src/org/mavlink/qgroundcontrol/QGCActivity.java

Workaround for QTBUG-73138
fixes #8365

Take MulticastLock on Android to ensure broadcast packets can be received

---

.travis.yml
src/VideoReceiver/README.md

travis: Update gstreamer version to 1.18.1 for mac

---

src/FlightMap/Widgets/PhotoVideoControl.qml
src/QmlControls/FactValueGrid.cc
src/QmlControls/HorizontalFactValueGrid.qml

Fact value grid fixes

---

src/FlightDisplay/VirtualJoystick.qml

Sub currently handles throttle in the 0-1000 range
https://github.com/ArduPilot/ardupilot/issues/8818

VirtualJoystick: remove sub from yAxisPositiveRangeOnly condition

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h

Addresses: https://github.com/mavlink/qgroundcontrol/issues/9219

Save coordinates on every, settled viewport change

---

src/Vehicle/MultiVehicleManager.cc

Attempted fixes for #9210 
See #9228 for more context.

Fix sendGCSHeartbeat() crash

---

src/comm/UDPLink.cc

UDPLink: Remove lost debug code

---

.travis.yml
android/AndroidManifest.xml

Android Target SDK 28->29

---

src/MissionManager/MissionSettingsItem.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/VisualMissionItem.cc
src/QmlControls/TerrainProfile.cc
src/TerrainTile.cc

Fix fuzzyCompare boolean comparison

---

.travis.yml
src/VideoReceiver/README.md
src/VideoReceiver/VideoReceiver.pri

Update android to use gstreamer 1.18.1

---

.appveyor.yml

appveyor: Fix download links for gstreamer

---

src/MissionManager/TransectStyleComplexItemTest.cc
src/MissionManager/TransectStyleComplexItemTest.h
src/QtLocationPlugin/QGCMapTileSet.cpp
src/QtLocationPlugin/QGeoMapReplyQGC.cpp
src/Terrain/TerrainQuery.cc
src/Terrain/TerrainQuery.h
src/TerrainTile.cc
src/TerrainTile.h

Still lots more work needed here. But better than having it off.

Terrain unit test back on

---

src/Vehicle/InitialConnectStateMachine.cc

Don't query fence/rally on high latency links

---

src/MissionManager/CameraSectionTest.cc
src/MissionManager/MissionController.cc
src/MissionManager/MissionSettingsItem.cc
src/MissionManager/TransectStyleComplexItem.cc
src/PlanView/TerrainStatus.qml
src/QmlControls/TerrainProfile.cc
src/QmlControls/TerrainProfile.h
src/ui/preferences/GeneralSettings.qml

* Pile of fixes for #9236
* This should transition terrain profile display from hopelessly broken to just kind of buggy
* I still have a list of things I found while testing which are screwed up I'm working on

Terrain profile fixes

---

src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/FixedWingLandingComplexItem.h
src/MissionManager/LandingComplexItem.cc
src/MissionManager/LandingComplexItem.h
src/MissionManager/LandingComplexItemTest.cc
src/MissionManager/LandingComplexItemTest.h
src/MissionManager/MissionController.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/VTOLLandingComplexItem.cc
src/MissionManager/VTOLLandingComplexItem.h
src/MissionManager/VisualMissionItem.h

Fix Takeoff/Landing item flight profile segment generation

---

src/MissionManager/VTOLLandingComplexItem.cc

Fix VTOL Landing yaw param

---

src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItemTest.cc

Fix signalling causing broken flight path bugs

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/VehicleSetup/JoystickConfigAdvanced.qml
src/VehicleSetup/JoystickConfigCalibration.qml
src/VehicleSetup/JoystickConfigController.cc
src/VehicleSetup/JoystickConfigController.h
src/VehicleSetup/JoystickConfigGeneral.qml

* There was a bunch of UI code related to gimbal joystick setup which did nothing other than confuse users.
* This pull can be reverted if anyone wants to resurrect.
* Not sure how something which completely didn't work go merged into the repo in the first place
* Fix #9255

Joystick: Remove incomplete gimbal code

---

src/MissionManager/TransectStyleComplexItem.cc

* Terrain ready was being signaled too early
* Fix #9244

TransectStyleComplexItem - Fix terrain ready signaling

---

src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/Vehicle/ComponentInformationManager.cc
src/ui/preferences/GeneralSettings.qml

Control COMPONENT_INFORMATION query from app setting

---

deploy/create_linux_appimage.sh

Move to latest AppImage tool which works on Ubuntu 20.04

---

translations/qgc-json.ts
translations/qgc-lupdate-json.py
translations/qgc-lupdate.sh
translations/qgc.ts

Updates .ts files to latest source for stable

Translation update

---

src/PlanView/PlanToolBarIndicators.qml

* I still can't reproduce this, but I've changed the code to hopefully work around what seems like a Qt bug
* Fix for #7416

Fix plan time display

---

custom-example/custom.qrc
custom-example/qgroundcontrol.qrc
custom-example/res/CustomFlyViewOverlay.qml
custom-example/updateqrc.py

Custom example update

---

src/FlightMap/MapItems/MissionLineView.qml

Hack out ROI segment indication since it is broken

---

.travis.yml
tools/update_android_version.sh

Fix Android versionCode generation

---

.travis.yml
tools/update_android_version.sh

* Fix Google Play upload
* Related to #9334

Android store version

---

.appveyor.yml
src/qgcunittest/MultiSignalSpyV2.cc

Windows: Fix Stable or Daily build determination

---

.appveyor.yml

#9348 didn't work. Hoping this will

Windows: Fix Stable/Daily build setup

---

ChangeLog.md
src/comm/TCPLink.cc
src/comm/TCPLink.h

Fix TCP Link comms

---

src/MissionManager/TransectStyleComplexItem.cc

Fix crash on descent rate calc

---

src/AutoPilotPlugins/APM/APMSubFrameComponent.qml

Backport of #9330
Allows loading default param files for Sub 4.0

(backport) Refactor sub default param loading, allow loading params for sub 4.0

---

src/PlanView/PlanToolBarIndicators.qml

This is a simpler version of #9362 for Stable

Fix mission time display

---

src/Vehicle/Vehicle.cc

Cherry pick of #9366 to stable

Fix PING support

---

src/VideoManager/SubtitleWriter.cc
src/VideoManager/SubtitleWriter.h

Fix overlay for recorded videos on stable

---

.travis.yml

Don't update Android version on pulls

---

src/QtLocationPlugin/MapboxMapProvider.cpp
src/QtLocationPlugin/MapboxMapProvider.h
src/QtLocationPlugin/QGCMapUrlEngine.cpp

Migrated to new Mapbox provider API

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/Joystick/JoystickManager.cc
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/main.cc

Cherry picks from master to stable: #9377, #9361, #9359

Cherry pick master

---

QGCPostLinkCommon.pri
tools/setup/arch.sh

Finally I get into QGC development let's see where that leads.
FYI @julianoes 
- I added the setup script for the installations I had to do and am planning to extend the documentation with the workflow I'm using.
- The icu 56 specific version staging seems to be required for Ubuntu version 16.04 but on distributions that don't stock this version anymore it leads to an error. So I added a condition that just takes it if it exists and otherwise the existing version. This should ensure that as long as our deployment CI has the library it deploys and for any other person who builds it this should not lead to an error.

Arch setup script

---

qgroundcontrol.pro
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/AutoPilotPlugins/PX4/PX4FlightBehavior.cc
src/AutoPilotPlugins/PX4/PX4FlightBehavior.h
src/AutoPilotPlugins/PX4/PX4FlightBehaviorCopter.qml
src/FirmwarePlugin/PX4/PX4Resources.qrc
src/QmlControls/FactSliderPanel.qml

From https://github.com/PX4/PX4-Autopilot/pull/16744
- A different logo would be nice
- Tab is only shown when the new parameter exists

MC PX4: add flight behavior config page

---

src/FlightDisplay/TelemetryValuesBar.qml
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/ui/preferences/GeneralSettings.qml

Reverts mavlink/qgroundcontrol#9436

Revert "TelemetryValuesBar: custom transparency by settings"

---

src/MissionManager/ComplexMissionItem.cc

MissiongManager: ComplexMissionItem: Save preset as CborValue variant

---

ChangeLog.md
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/GuidedActionsController.qml
src/Vehicle/RequestMessageTest.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

* Change to no longer queue commands broke pause and change alt support
* Fix #9397

Fix pause and change alt command sequencing

---

src/QmlControls/FlightModeMenu.qml
src/ui/toolbar/MainStatusIndicator.qml
src/ui/toolbar/MainToolBar.qml

Changes for #9399. Discussion on change on visual changes are in there.

Tool bar cleanup

---

src/PlanView/SimpleItemEditor.qml

Plan: Fix mixed modes

---

src/FlightDisplay/FlyViewWidgetLayer.qml
src/FlightMap/Widgets/PhotoVideoControl.qml
src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml

Fix vertical instruments

---

src/ui/MainRootWindow.qml
src/ui/toolbar/MainToolBar.qml

Change Tool Drawer to Dialog

---

ChangeLog.md
src/AutoPilotPlugins/Common/RadioComponentController.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/FlightDisplay/FlyViewWidgetLayer.qml
src/FlightDisplay/GuidedActionsController.qml
src/FlightMap/Widgets/PhotoVideoControl.qml
src/FlightMap/Widgets/QGCInstrumentWidgetAlternate.qml
src/MissionManager/MavCmdInfoCommon.json
src/MissionManager/MavCmdInfoFixedWing.json
src/MissionManager/MavCmdInfoMultiRotor.json
src/MissionManager/TransectStyleComplexItem.cc
src/PlanView/SimpleItemEditor.qml
src/QmlControls/FlightModeMenu.qml
src/Vehicle/RequestMessageTest.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/ui/toolbar/MainStatusIndicator.qml
src/ui/toolbar/MainToolBar.qml

#9464, #9457, #9456, #9454, #9451, #9382, #9368

Cherry picks from Stable to master

---

src/MissionManager/LandingComplexItem.cc
src/MissionManager/LandingComplexItem.h
src/MissionManager/LandingComplexItemTest.cc
src/MissionManager/LandingComplexItemTest.h

* Fix missing signaling caused by change to move more of the pattern code to base class
* Fix #9424

Fix missing signaling

---

src/MissionManager/ComplexMissionItem.cc
src/MissionManager/ComplexMissionItem.h
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/LandingComplexItem.cc
src/MissionManager/LandingComplexItem.h
src/MissionManager/LandingComplexItemTest.cc
src/MissionManager/LandingComplexItemTest.h
src/MissionManager/MissionController.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/VTOLLandingComplexItem.cc
src/QmlControls/FlightPathSegment.cc
src/QmlControls/FlightPathSegment.h

Cherry pick from Stable to master: #9476, #9474, #9473

Cherry pick to master

---

src/ui/toolbar/MainStatusIndicator.qml

* Fix max sizing
* Make is flickable
* Move arm/disarm button to top for usability
* Fix #9428

Sensor Status: Correct sizing, flickable

---

src/QmlControls/ToolStrip.qml

Plan: Fix auto-show of File panel

---

src/QmlControls/FactValueGrid.cc

Values Panel: Don't trash settings for missing Facts

---

src/QmlControls/FactValueGrid.cc

Don't trash settings for missing Facts

---

src/QmlControls/ToolStrip.qml

Fix auto-show of File panel

---

src/AutoPilotPlugins/PX4/PX4FlightBehaviorCopter.qml

Expose another commonly used parameter.
@bresch fyi

PX4FlightBehaviorCopter: add NAV_ACC_RAD to configure mission turning radius

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

Plan: Fix supported commands list

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/PlanView/SimpleItemMapVisual.qml

Cherry pick stable to master

---

src/QmlControls/ParameterEditorController.cc

Improve code readability and maintainability

QmlControls: ParameterEditorController: Simplify shouldShow logic

---

src/MissionManager/MissionManager.cc
src/Vehicle/Vehicle.h

* Fix VTOL Takeoff item not being put back into the generated mission
* Fix #9505

Fix VTOL resume mission

---

src/MissionManager/MissionManager.cc
src/Vehicle/Vehicle.h

Cherry pick stable

---

src/MissionManager/ComplexMissionItem.cc
src/MissionManager/LandingComplexItem.cc
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/TransectStyleComplexItem.cc

Plan: Fix home position change signalling

---

src/Vehicle/VehicleLinkManager.cc

No modal popup on comm lost/ergained

---

src/MissionManager/LandingComplexItem.cc

* One form of recalc code wasn't taking into account loiter direction setting
* Fix #9514

Plan: Fix Loiter directions

---

src/MissionManager/LandingComplexItem.cc

Plan - FW Landing: Fix Loiter directions

---

custom-example/qgcresources.exclusion
custom-example/qgroundcontrol.exclusion
custom-example/qgroundcontrol.qrc

* Exclusion was in the wrong place
* Fix for #9551

Custom build: Fix exclusion for CustomFlyViewOverlay

---

src/FactSystem/FactControls/FactCheckBox.qml
src/MissionManager/TransectStyleComplexItem.cc
src/PlanView/TransectStyleComplexItemTerrainFollow.qml

Plan: Fix Follow terrain preset

---

android/AndroidManifest.xml

Android: Use legacy storage system to keep QGC save locations working

---

src/FactSystem/FactControls/FactCheckBox.qml
src/MissionManager/TransectStyleComplexItem.cc
src/PlanView/TransectStyleComplexItemTerrainFollow.qml

Cherry pick master to stable

---

CMakeLists.txt
deploy/qgroundcontrol-clean.desktop
libs/shapelib/CMakeLists.txt

Basically needed for my flatpak build to work.
What you see is what you get.

CMake: Bundle of fixes

---

android/AndroidManifest.xml
custom-example/qgcresources.exclusion
custom-example/qgroundcontrol.exclusion
custom-example/qgroundcontrol.qrc

Cherry pick from stable to master

---

src/FlightMap/MapItems/VehicleMapItem.qml

Cherry pick https://github.com/mavlink/qgroundcontrol/pull/9572 to Stable

Fix vehicle map item opacity (Stable)

---

src/Vehicle/InitialConnectStateMachine.cc

Fix state machine not being advanced in all cases

---

src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/QGCApplication.cc

Signed-off-by: numan.uyar <numan.uyar@titra.com.tr>
related to issue: #9539

RadioComponentController fix for Custom builds

---

src/VehicleSetup/FirmwareUpgradeController.cc
src/comm/USBBoardInfo.json

Adds FMUv6U to the list of supported boards within QGC

Add support for PX4 FMUv6U.

---

src/QmlControls/QGCFileDialog.qml
src/comm/LinkConfiguration.cc
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/ui/preferences/BluetoothSettings.qml
src/ui/preferences/LinkSettings.qml
src/ui/preferences/LogReplaySettings.qml
src/ui/preferences/MockLinkSettings.qml
src/ui/preferences/SerialSettings.qml
src/ui/preferences/TcpSettings.qml
src/ui/preferences/UdpSettings.qml

* Rework old crufty link settings ui code to use Qml Layouts which in turn makes it way simpler and easier to work with
* Also some additional general cleanup related to Link Settings to simplify
* Related to discussion in #9502

Link settings cleanup

---

.github/workflows/compile_test_release.yml
.travis.yml

* Turns on S3 upload for daily builds
* Turns off travis S3 uploads for daily

GitHub Actions S3 upload

---

.github/workflows/compile_test_release.yml

Reverts mavlink/qgroundcontrol#9656

Revert "Rework shadow build dir"

---

src/AutoPilotPlugins/Common/RadioComponentController.cc
src/AutoPilotPlugins/Common/RadioComponentController.h

Better radio calibration logging

---

qgroundcontrol.pro
src/QmlControls/QGCImageProvider.cc
src/QmlControls/QGCImageProvider.h
src/Vehicle/ImageProtocolManager.cc
src/Vehicle/ImageProtocolManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/uas/UAS.cc
src/uas/UAS.h

Rewrite Mavlink image protocol support and fix bugs

---

src/FlightDisplay/FlyViewVideo.qml

Show how to exit video fullscreen mode when mouse hovers on the video view (https://github.com/mavlink/qgroundcontrol/issues/9563#issuecomment-808545622)
https://user-images.githubusercontent.com/82586164/115717387-1912c280-a3b5-11eb-97cc-c534cf12b950.mov

Show message to exit video fullscreen mode

---

src/AutoPilotPlugins/PX4/PowerComponent.qml
src/QmlControls/QGCPopupDialog.qml
src/QmlControls/QGCPopupDialogContainer.qml
src/comm/MockLink.cc
src/ui/MainRootWindow.qml

Dialogs would stack up over each other

PX4: Fix ESC Calibration dialog sequencing

---

src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc
src/AutoPilotPlugins/PX4/PX4RadioComponent.cc

fix for range-loop-construct

---

src/PlanView/PlanView.qml

fix typo "alititude" to "altitude"

fix typo  planview qml

---

src/Vehicle/Vehicle.cc

RC to Param: Fix swapped values

---

src/Vehicle/Vehicle.cc

Fix swapped values

---

src/PlanView/TransectStyleComplexItemEditor.qml

* Replacement for #9113
* Fix #8654
* Validates preset names for blanks and "/" char
* Trims preset name os leading/trailing blanks
* Uses new dialog system

Validate preset name, use new dialog system

---

src/MissionManager/MissionItemTest.cc

Mavlink update

---

src/MissionManager/LandingComplexItem.cc

FW Landing Pattern: Fix json key name

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h

Restart ArduPilot streams as needed

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml

* Fix for #9590 
* Switch parameter names were screwed up

Fix switch mapping parameter names

---

src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml

Fix switch parameter names

---

src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc
src/Vehicle/Vehicle.h

No Sensor cal for HIL

---

src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc
src/AutoPilotPlugins/PX4/PX4RadioComponent.cc

AutoPilotPlugins: PX4: Fix bind to temporary constructor

---

src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc

There is no sub without camera

APM: APMAutoPilotPlugin: Fix parameters check

---

src/AutoPilotPlugins/APM/APMPowerComponent.qml

APMPowerComponent: Fix combobox layout

---

src/AutoPilotPlugins/APM/APMSubFrameComponent.qml

- Use frame option as parameter source
- Remove the duplicated step when the usuer need to select frame and load parater and again the frame

WIP: APMSubFrameComponent: Improve Sub frame selection

---

src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml

APMSafetyComponentSub: Improve layout and code 

---

src/FirmwarePlugin/FirmwarePlugin.cc

Update Sony trigger time settings and add Flir Duo Pro R

Update Sony trigger time settings and add Flir Duo Pro R

---

src/VehicleSetup/JoystickConfigButtons.qml

Improve joystick webpage 

---

src/QmlControls/QGCComboBox.qml

QGCComboBox: Check for model before iterating over it

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml

APMSensorsComponent: Enable gyro calibration for sub vehicle

---

src/AutoPilotPlugins/APM/APMSubFrameComponent.cc
src/AutoPilotPlugins/APM/APMSubFrameComponent.qml
src/QmlControls/QGCButton.qml

https://user-images.githubusercontent.com/1215497/127672323-fb5111fa-9592-4a36-9558-ac8595870527.mp4

APMSubFrameComponent: Add confirmation dialog

---

src/VehicleSetup/SetupView.qml

SetupView: Add joystick icon to joystick page

---

src/QGCApplication.cc

QGCApplication: Remove lost includes

---

src/AutoPilotPlugins/APM/APMPowerComponent.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml
src/AutoPilotPlugins/APM/APMSafetyComponentSummarySub.qml
src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/Vehicle/SubmarineFact.json
src/VehicleSetup/JoystickConfigButtons.qml
src/VehicleSetup/SetupView.qml

Move:
#9779 
#9780 
#9786 
#9787
#9788
#9790
#9791
#9796
#9803

Move to stable a couple of PRs that are sub related

---

src/VehicleSetup/JoystickConfigButtons.qml

JoystickConfigButton: Disable joystick buttons that can't be used with vehicle

---

src/comm/USBBoardInfo.json

Update to the proper vendor ID
cc @davids5

BoardInfo: update FMUv5X vendor ID

---

README.md

README: Remove trailing spaces

---

src/ui/toolbar/JoystickIndicator.qml

https://user-images.githubusercontent.com/1215497/129396320-abf9cd30-04c6-4ec1-b5c0-6a7b02d14264.mp4

toolbar: JoystickIndicator: Turn joystick yellow if it's not enabled

---

src/QmlControls/QGCComboBox.qml
src/VehicleSetup/JoystickConfigButtons.qml

Move to stable

---

.github/workflows/linux_release.yml
.github/workflows/macos_release.yml
.github/workflows/windows_release.yml

actions: Add github actions to stable build

---

.github/workflows/android_build.yml

Github action to help us to debug and test qgc development for android (PRs and branches)

github: Add android build

---

.github/workflows/linux_debug.yml
.github/workflows/linux_release.yml

we previously made the mistake of only targeting ubuntu 20.04 leaving a lot of users behind, this PR hopefully fixes that.

Update Action to target ubuntu 18.04

---

src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml
src/GPS/GPSProvider.cc
src/GPS/GPSProvider.h
src/GPS/vehicle_gps_position.h

This PR is for updating QGC with recent updates of submodule GPS/Drivers

Pr update gps driver

---

src/VehicleSetup/FirmwareUpgradeController.cc
src/comm/USBBoardInfo.json

Added SmartAP board USB identifier to support the hardware detection properly.

Added SmartAP board USB identifier

---

.gitmodules
QGCExternalLibs.pri
libs/CMakeLists.txt
libs/qmdnsengine_export.h
src/Settings/AutoConnect.SettingsGroup.json
src/Settings/AutoConnectSettings.cc
src/Settings/AutoConnectSettings.h
src/comm/CMakeLists.txt
src/comm/LinkManager.cc
src/comm/LinkManager.h
src/ui/preferences/GeneralSettings.qml

Find vehicles that uses mavlink type:
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=mavlink
Supports both tcp and udp connections.

Find vehicles on the network with zero-conf (mdns)

---

src/MissionManager/MissionController.cc

No wizard mode for VTOL landing pattern

---

src/MissionManager/MissionController.cc
src/MissionManager/MissionController.h

Fix Split Segment handling

---

.github/workflows/linux_release.yml
.github/workflows/macos_release.yml
.github/workflows/windows_release.yml

This should get daily build uploads working again for Linux, Mac, Windows

Turn on S3 Upload

---

.github/workflows/linux_release.yml
.github/workflows/macos_release.yml
.github/workflows/windows_release.yml

Fix S3 upload command

---

src/MissionManager/MissionController.cc
src/QGCApplication.cc
src/QGCApplication.h
src/VideoManager/VideoManager.cc

* Fix #10004
* Might fix #10007 as well. It looks the same.

OSX: Fix crash on close

---

src/AnalyzeView/GeoTagPage.qml
src/AnalyzeView/MavlinkConsolePage.qml
src/AutoPilotPlugins/APM/APMCameraSubComponent.qml
src/AutoPilotPlugins/Common/ESP8266ComponentSummary.qml
src/AutoPilotPlugins/Common/SyslinkComponent.qml
src/AutoPilotPlugins/PX4/CameraComponentSummary.qml
src/AutoPilotPlugins/PX4/PX4FlightBehaviorCopter.qml
src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
src/FactSystem/FactControls/FactTextFieldSlider.qml
src/FlightDisplay/MultiVehicleList.qml
src/MissionManager/MissionSettingsItem.h
src/PlanView/PlanToolBarIndicators.qml
src/QmlControls/HeightIndicator.qml
src/QmlControls/PIDTuning.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/RCChannelMonitor.qml
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/VehicleSetup/FirmwareUpgrade.qml
src/ui/preferences/MavlinkSettings.qml
src/ui/toolbar/JoystickIndicator.qml

Support for various languages

---

src/AutoPilotPlugins/PX4/PX4FlightBehaviorCopter.qml

Fix typo vertial > vertical in UI string

---

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc

This add the MultiVehicleSelector for ArduSub
Fix https://github.com/mavlink/qgroundcontrol/issues/9861

Add MultiVehicleSelector to ArduSubFirmwarePlugin

---

deploy/docker/Dockerfile-build-linux
deploy/docker/install-qt-linux.sh

Switch docker to Qt 5.15

---

src/QmlControls/QGCViewDialogContainer.qml

Fix #9833 
https://user-images.githubusercontent.com/28136137/131616675-400e376d-ee9a-4a76-9f1e-a02741398797.mp4

Fix getting stuck when returning to the main screen while the parameter editor is open

---

src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/QmlControls/ParameterEditor.qml

Show a list of selected bit and the string value for each one over the "Unknown: X" string
https://user-images.githubusercontent.com/1215497/126830106-ae5157a0-c66d-454e-917c-e0886db4ea0f.mp4

Improve parameter bitmask value on parameter widget

---

custom-example/qgroundcontrol.qrc
qgroundcontrol.pro
qgroundcontrol.qrc
src/Vehicle/CMakeLists.txt
src/Vehicle/HygrometerFact.json
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleHygrometerFactGroup.cc
src/Vehicle/VehicleHygrometerFactGroup.h

move https://github.com/mavlink/qgroundcontrol/pull/9841 to here.

FactGroup: Add HygrometerFactGround

---

src/VehicleSetup/Bootloader.h
src/VehicleSetup/FirmwareUpgradeController.cc
src/VehicleSetup/FirmwareUpgradeController.h

Support 1060 based SiK radios

---

.github/workflows/android_32_release.yml
.github/workflows/android_64_release.yml
.github/workflows/linux_release.yml
.github/workflows/windows_release.yml

More S3 upload work

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Implement SimpleAccelCal for Ardupilot Vehicles

---

src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h

Implement fast compass calibration for Ardupilot Vehicles

---

src/AnalyzeView/VibrationPage.qml

changed from geotagpage to vibrationpage

Fix vibrationPage id

---

src/comm/QGCMAVLink.cc

Adds mav_sys_status_sensor_propulsion and resolves the missing sensor message

Add missing sensor

---

Vagrantfile

now required for a QGC build, it seems...

Vagrantfile: install patchelf package

---

.github/workflows/macos_release.yml
.travis.yml
QGCPostLinkInstaller.pri
src/VideoManager/VideoManager.cc
src/VideoReceiver/VideoReceiver.pri

4.1: Fix video mac issue

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h

ardupilot follow mode has been stable for a long time, so enable
also added other missing flight modes

allow follow to work with ardupilot copter and rover

---

src/PlanView/StructureScanEditor.qml

Fix Structure Scan Editor Layout

---

src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc

this works with ArduPilot 4.1/4.2

APM: enable Follow mode for rovers/boats

---

src/Settings/AppSettings.cc

Locale: fix translation of Japanese

---

src/Vehicle/Vehicle.cc

ArduPilot DO_MOUNT_CONTROL values are centi-degrees

---

src/Joystick/JoystickSDL.cc

Using the macro for gamecontroller button count is incorrect because the enum includes buttons not on every gamecontroller ex: `SDL_CONTROLLER_BUTTON_TOUCHPAD, /* PS4/PS5 touchpad button */`

Fix Joystick Button Count

---

.github/workflows/macos_release.yml
QGCPostLinkInstaller.pri
src/VideoManager/VideoManager.cc
src/VideoReceiver/VideoReceiver.pri

Mac video fix v4.2

---

src/AutoPilotPlugins/APM/APMPowerComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponent.qml
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h
src/AutoPilotPlugins/APM/APMSensorsComponentSummary.qml
src/AutoPilotPlugins/APM/APMSubFrameComponent.qml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Rover.4.1.xml
src/FirmwarePlugin/APM/APMParameterFactMetaData.Sub.4.1.xml
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/APM/APMParameterMetaData.h
src/FirmwarePlugin/APM/APMResources.qrc
src/FirmwarePlugin/APM/APMSensorIdDecoder.qml
src/FirmwarePlugin/APM/APMSensorParams.qml
src/FirmwarePlugin/APM/QGroundControl.ArduPilot.qmldir
src/FlightMap/Widgets/PhotoVideoControl.qml
src/Joystick/JoystickSDL.cc
src/QmlControls/ParameterEditorController.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/VehicleSetup/JoystickConfigButtons.qml

this should include #10295 and #10296 once they are in.

Sub backports for 4.2

---

src/ui/preferences/MavlinkSettings.qml

This cleans up the mavlink settings when they aren't usable

Show firmware specific settings based on active firmware

---

.github/workflows/macos_release.yml
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/Vehicle/Actuators/Actuators.cc

I could not build on MacOS due to compile errors. I adapted the code to avoid those compiler issues. The CI for the MacOS target on github was broken because Qt did not install. I updated the Qt install script version. I also removed an unused variable in an attempt to fix the android build but there are some more errors remaining. The fixes should not change the functional behaviour.

MacOS: fix compile errors and github CI setup

---

src/ui/preferences/GeneralSettings.qml

This adds additional common baudrates to the nmea source baudrates
dropdown menu.

GeneralSettings: Add additional baudrates for nmea GPS source

---

src/Vehicle/EventHandler.cc
src/Vehicle/EventHandler.h
src/Vehicle/HealthAndArmingCheckReport.cc
src/Vehicle/Vehicle.cc

From https://github.com/mavlink/libevents/pull/3

Vehicle: update HealthAndArmingCheck

---

src/Vehicle/InitialConnectStateMachine.cc

Fix MAVLink PROTOCOL_VERSION request

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/MissionManager/MavCmdInfoCommon.json

Coresponding PX4 PR: https://github.com/PX4/PX4-Autopilot/pull/20325

PX4FirmwarePlugin: add MAV_CMD_DO_SET_ACTUATOR to supported mission commands

---

src/QmlControls/LogReplayStatusBar.qml

Another user requested this feature here:
https://github.com/mavlink/qgroundcontrol/issues/8557
And actually tested it for a year.

LogReplayStatusBar: Implement 10x log replay speed

---

.github/workflows/android_release.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release.yml
.github/workflows/macos_release.yml
.github/workflows/windows_release.yml

This updates the github actions to newer versions that do not depend on nodejs 12 or other deprecated features.
In the debug action one dependency still uses nodejs 12 but a fix is already pending as pull request. As soon as the dependency is updated I create a follow PR for that.

Update GitHub actions

---

QGCExternalLibs.pri
QGCPostLinkCommon.pri
src/Airmap/AirMapAdvisoryManager.cc
src/Airmap/AirMapRulesetsManager.cc
src/Airmap/services/advisory.cpp
src/Airmap/services/aircrafts.cpp
src/Airmap/services/airspaces.cpp
src/Airmap/services/authenticator.cpp
src/Airmap/services/flight_plans.cpp
src/Airmap/services/flights.cpp
src/Airmap/services/pilots.cpp
src/Airmap/services/rulesets.cpp
src/Airmap/services/status.cpp
src/Airmap/services/telemetry.cpp
src/Airmap/services/traffic.cpp

This addresses: https://github.com/airmap/platform-sdk/issues/182
and thus allows building QGC with AirMap support for ARM

Upgrade AirMap support to 2.0.1 to allow building for ARM

---

src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc

ArduSubFirmwarePlugin: add GuidedModeCapability to Sub vehicles

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

The current code would set the vehicle to guided, then arm, and if fixed wing, then switch to auto.
This small time it remained in guided, until QGC received feedback of vehicle armed and changed to auto, was enough to provoke dangerous situations, because when arming in guided mode, if the vehicle is a tilt rotor vtol, it would arm the rotors in forward flight position, and some airframes are not designed for this situation, leading to a dangerous situation.
This commit changes the behavior of start mission, so if it is an Ardupilot fixed wing or VTOL it will set auto mode, and then arm, which is the intended way of dealing with this in Ardupilot.
For the rest of vehicles the behavior keeps being the same.

Fix issue for Ardupilot Vtols and start mission action:

---

src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h

FactSystem: ParameterManager: Remove unused variables

---

src/FlightDisplay/FlyViewVideo.qml

src: FlyViewVideo: Remove Double-click text after 10 seconds

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

this adds the option to display the telemetry data from RANGEFINDER.distance 
tested, works fine.

Display Rangefinder Distance

---

src/QtLocationPlugin/GenericMapProvider.cpp
src/QtLocationPlugin/GenericMapProvider.h
src/QtLocationPlugin/QGCMapUrlEngine.cpp

Added another map by Statkart - with topographic maps of Svalbard.

Topomap of Svalbard

---

src/VideoReceiver/GstVideoReceiver.cc
src/VideoReceiver/GstVideoReceiver.h

Replaces #9838, apply corrections from the code review.

fix android udp h264 video record

---

src/VideoReceiver/GstVideoReceiver.cc
src/VideoReceiver/GstVideoReceiver.h

[BACKPORT] 4.2 fix android udp h264 video record

---

src/VehicleSetup/FirmwareUpgradeController.cc

This is according to https://github.com/PX4/PX4-Bootloader/blob/main/board_types.txt

FirmwareUpgrade: add thepeach board

---

src/VehicleSetup/FirmwareUpgradeController.cc
src/comm/USBBoardInfo.json

This adds support for the ARKV6X in stable 4.2.

Stable 4.2 - Add ARKV6X

---

UnitTest.qrc
qgroundcontrol.pro
src/CMakeLists.txt
src/QGCCachedFileDownload.cc
src/QGCCachedFileDownload.h
src/QGCFileDownload.cc
src/QGCFileDownload.h
src/Vehicle/CMakeLists.txt
src/Vehicle/CompInfo.h
src/Vehicle/CompInfoActuators.cc
src/Vehicle/CompInfoActuators.h
src/Vehicle/CompInfoEvents.cc
src/Vehicle/CompInfoEvents.h
src/Vehicle/CompInfoGeneral.cc
src/Vehicle/CompInfoGeneral.h
src/Vehicle/CompInfoParam.cc
src/Vehicle/CompInfoParam.h
src/Vehicle/ComponentInformationManager.cc
src/Vehicle/ComponentInformationManager.h
src/Vehicle/ComponentInformationTranslation.cc
src/Vehicle/ComponentInformationTranslation.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/qgcunittest/CMakeLists.txt
src/qgcunittest/ComponentInformationTranslationTest.cc
src/qgcunittest/ComponentInformationTranslationTest.h
src/qgcunittest/TranslationTest.json
src/qgcunittest/TranslationTest_de_DE.ts
src/qgcunittest/UnitTestList.cc

This implements https://github.com/mavlink/mavlink/pull/1934

Metadata translation support

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

Enable ROIModeCapability for ArduPilot vehicles

---

CMakeLists.txt
src/QmlControls/CMakeLists.txt
src/Settings/CMakeLists.txt
src/Vehicle/CMakeLists.txt

-Increase C++ standard to C++17 as for qmake build
-Add missing files for remote id
-Add missing files for custom action

Fix cmake build

---

src/Camera/QGCCameraControl.cc
src/comm/LinkManager.cc

src: Improve debug messages on the camera stream logic

---

src/Camera/QGCCameraManager.cc

Camera: don't decode unused heartbeat

---

src/VideoReceiver/GstVideoReceiver.cc
src/VideoReceiver/GstVideoReceiver.h

This fixes regular segfaults on exit for me.

VideoReceiver: call stop and cleanup teeProbe

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleFact.json

It could be interesting to have in the displayable values IMU temperature.

Vehicle: Add RAW_IMU to displayable telemetry

---

src/FlightDisplay/FlyView.qml

Fix Fly View Typo

---

src/QmlControls/JoystickThumbPad.qml

Resolve of https://github.com/mavlink/qgroundcontrol/issues/10666

Issue #10666 solved

---

QGCCommon.pri

QGCCommon: Disable AIRMAP

---

android/AndroidManifest.xml
android/src/AndroidInterface.cc

#10748 only worked some of the time. This change makes it work all of the time. (I hope!)
Android is never my friend.

Fix sd card permission

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/VehicleSetup/JoystickConfig.qml
src/VehicleSetup/SetupView.qml
src/api/QGCOptions.h

For example a Herelink controller custom build will use this.

Support custom builds with joysticks which are buttons only

---

src/AnalyzeView/LogDownloadPage.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCMouseArea.qml
src/QmlControls/QGCToolBarButton.qml
src/ui/MainRootWindow.qml
src/ui/toolbar/FlightModeMenuIndicator.qml
src/ui/toolbar/MainStatusIndicator.qml

There were all discovered through my Herelink work but are basic android build problems. The commit text describes the changes in detail.

Android fixes

---

src/AutoPilotPlugins/APM/APMSafetyComponent.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

These changes had been made on the Herelink repo only when in fact they are general QGC features:
* Better ArduCopter fence support
* Support mavlink FENCE_STATUS messaging. Nothing fancy here now. At some point an App Setting to turn on/off as well as the timeout time would be good.

Geofence updates

---

src/FlightDisplay/FlyViewMap.qml
src/FlightMap/MapItems/VehicleMapItem.qml

The code in VehicleMapItem.qml and FlyViewMap.qml was fighting with each other for vehicle sizing.

Fly View: Fix normal and adsb vehicle sizing

---

src/QmlControls/InstrumentValueEditDialog.qml
src/QmlControls/InstrumentValueLabel.qml
src/QmlControls/InstrumentValueValue.qml

In fly view, set instrument values have custom color same as labels
Fix instrument panel editor layout properly according to selected Range type.

Fix instrument panel and editor layout

---

CMakeLists.txt
cmake/Git.cmake
deploy/org.mavlink.qgroundcontrol.metainfo.xml
deploy/org.mavlink.qgroundcontrol.metainfo.xml.in

Backport fixes for the metadata file:
- https://github.com/mavlink/qgroundcontrol/pull/10615
- https://github.com/mavlink/qgroundcontrol/pull/10653

backport metadata fixes

---

QGCExternalLibs.pri
custom-example/custom.pri

There were some changes missing to support this

Fix up support for Mavlink All dialect

---

android.pri

This addresses the matters discussed in https://github.com/mavlink/qgroundcontrol/pull/10826. @DonLakeFlyer I tested and it works on my custom build as well, so feel free to merge if you are fine with it. Thanks!

Fix setup of ANDROID_PACKAGE_SOURCE_DIR

---

src/AutoPilotPlugins/APM/APMCameraSubComponent.qml
src/FactSystem/FactControls/FactTextFieldSlider.qml
src/QmlControls/FactSliderPanel.qml
src/QmlControls/QGCSlider.qml

minimumValue/maximumValue -> from/to

Updates for changes to Qml Slider in Qt6

---

docs/en/qgc-dev-guide/command_line_options.md
docs/en/qgc-dev-guide/getting_started/index.md
docs/en/qgc-dev-guide/tools/index.md
docs/en/qgc-user-guide/getting_started/download_and_install.md
docs/en/qgc-user-guide/index.md
docs/en/qgc-user-guide/releases/stable_v3.2_long.md
docs/en/qgc-user-guide/settings_view/console_logging.md

When this was two libraries the links were URLs. This makes them local links.
Also some layout tidy.

[Docs] Fix up internal links as external links

---

src/QmlControls/QGCTextField.qml
src/QmlControls/ScreenTools.qml

This in turn fixes the size of the search field in the parameter list

Fix implicit text field width

---

src/AnalyzeView/LogDownloadController.cc
src/AnalyzeView/LogDownloadController.h
src/AnalyzeView/LogDownloadPage.qml
src/QmlControls/QGCListView.qml
src/qgcunittest/UnitTest.cc

Log download fixes for Qt6

---

src/FirmwarePlugin/PX4/PX4FlightModeIndicator.qml
src/ui/MainRootWindow.qml
src/ui/toolbar/BatteryIndicator.qml
src/ui/toolbar/FlightModeIndicator.qml
src/ui/toolbar/GPSIndicator.qml
src/ui/toolbar/GPSRTKIndicator.qml
src/ui/toolbar/MainStatusIndicator.qml
src/ui/toolbar/MessageIndicator.qml

Center tool indicator popup to tool button

---

src/Vehicle/CMakeLists.txt

fix linking errors in 4.3

---

src/FactSystem/FactControls/FactTextField.qml
src/QmlControls/EditPositionDialog.qml
src/QmlControls/ParameterEditorDialog.qml
src/QmlControls/QGCPopupDialog.qml
src/QmlControls/QGCTextField.qml
src/ui/MainRootWindow.qml

Closing a popup dialog with a click outside would not trigger validation

Fact text field validation

---

src/MissionManager/MavCmdInfoCommon.json

@booo - I made this a separate commit, as you requested in https://github.com/mavlink/qgroundcontrol/pull/10555
:)

Condition yaw options default

---

QGCPostLinkInstaller.pri

Remove hardcoded reference to "QGroundControl" naming

Fix android custom builds

---

src/VideoReceiver/README.md

Add example video stream

---

src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Replacement for #10325. I hand carried this stuff across to a new pull.

Add joystick landing gear button support

---

src/Settings/UnitsSettings.cc

Allow units strings to be localized

---

src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/Settings/AppSettings.cc
src/Settings/AppSettings.h

Replacement for #10867, fix for #10591

Fix exported tile sets file extension

---

src/FlightDisplay/FlyViewMap.qml
src/FlightDisplay/GuidedActionsController.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/comm/MockLink.cc

Replacement for #10127. @Williangalvani Seems to have disappeared so I cleaned this up myself.
Differences from original pull:
* Uses "Estimator" naming instead of "EKF"
* Only shows up when visible has no GPS

Set estimator origin

---

CMakeLists.txt
src/ui/preferences/VideoSettings.qml

* Reworked video settings to better fix new style
* Fix for video build on OSX. @zdanek Can you take a look at the CMakeLists.txt change

Reworked Video settings

---

qgroundcontrol.qrc
src/Settings/App.SettingsGroup.json
src/ui/AppSettings.qml
src/ui/SettingsPagesModel.qml
src/ui/preferences/CMakeLists.txt
src/ui/preferences/GeneralSettings.qml
src/ui/preferences/MavlinkSettings.qml
src/ui/preferences/TelemetrySettings.qml

Telemetry settings

---

src/QmlControls/QGCPopupDialog.qml

Close outside without button was not working. Just causing confusion.

Back to original close dialog handling

---

.github/workflows/videoapp_linux.yml

It's confusing otherwise when looking at the test results

Rename video app workflow

---

qgroundcontrol.pro
qgroundcontrol.qrc
src/QmlControls/QGroundControl/Controls/qmldir
src/QmlControls/SettingsGroupLayout.qml
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCMapEngine.h
src/QtLocationPlugin/QMLControl/OfflineMap.qml
src/QtLocationPlugin/QMLControl/OfflineMapEditor.qml
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h
src/Settings/CMakeLists.txt
src/Settings/Maps.SettingsGroup.json
src/Settings/MapsSettings.cc
src/Settings/MapsSettings.h
src/Settings/SettingsManager.cc
src/Settings/SettingsManager.h
src/ui/SettingsPagesModel.qml
src/ui/preferences/CMakeLists.txt
src/ui/preferences/GeneralSettings.qml
src/ui/preferences/MapSettings.qml
src/ui/preferences/OfflineMapInfo.qml

Also converted to the new Settings ui style

Reworked Offline Maps to be Maps settings

---

src/VehicleSetup/FirmwareUpgradeController.cc

Control Zero Classic Board ID and target added

Update FirmwareUpgradeController.cc to add mRo Control Zero Classic board

---

src/AutoPilotPlugins/PX4/ActuatorComponent.qml
src/QmlControls/QGCSlider.qml
src/QmlControls/ScreenTools.qml
src/QmlControls/ToolStrip.qml
src/ui/preferences/LinkSettings.qml

Also some changes for sizing on mobile. Previously it was next to impossible to slide a slider on mobile since the touch area was too small.

Comm links settings updated to new ui style

---

.gitmodules
CMakeLists.txt
QGCCommon.pri
QGCExternalLibs.pri
libs/README.md
src/Vehicle/Vehicle.cc

The Eigen functionality is provided internally by Qt, this removes an unnecessary submodule.

Remove external Eigen lib

---

src/QGCApplication.cc

QGC doesn't have to be used with USB, so there is no reason insufficient serial permissions should be fatal. Also, only show the error if not building with `NO_SERIAL_LINK`.

Linux: do not make usb permissions fatal

---

.github/workflows/android_release.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release.yml
.github/workflows/macos_release.yml
.github/workflows/videoapp_linux.yml
.github/workflows/windows_release.yml

When checking the ccache results output, this actually has cache hits now.
Edit: @DonLakeFlyer can you delete all the extra caches created under Actions? I changed the names multiple times.

Fix CI CCache

---

CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

Should be included for known target

Fix incorrect precompiled header including for cmake

---

src/AnalyzeView/MavlinkConsolePage.qml

Mavlink Console fixes

---

src/AutoPilotPlugins/PX4/ActuatorComponent.qml
src/VehicleSetup/SetupView.qml
src/ui/preferences/HelpSettings.qml
src/ui/toolbar/MainStatusIndicator.qml
src/ui/toolbar/MessageIndicator.qml

Also added QGC discord server to Help page

Fix more Qt6 signal parameter stupidity

---

src/ui/toolbar/TelemetryRSSIIndicator.qml

Telemetry toolbar indicator: Updated to new style indicator ui

---

src/QmlControls/QGCFileDialogController.cc
src/QmlControls/QGCFileDialogController.h

Fix #11083
Some sort of strange change in Qt6

File Dialog: Fix url conversion

---

src/ui/toolbar/TelemetryRSSIIndicator.qml

Some debugging changes were left in a commit

Telemetry Indicator: Put back correct code

---

cmake/MacOSXBundleInfo.plist.in
src/PositionManager/PositionManager.cpp
src/PositionManager/PositionManager.h

Fix #11096. Note this currently only works in cmake builds.

Request location permissions

---

src/FlightMap/FlightMap.qml

Map: Add pinch support

---

android/src/org/mavlink/qgroundcontrol/QGCActivity.java

App crashes on startup on Android 12.
https://developer.android.com/privacy-and-security/risks/pending-intent
Exception

PendingIntent needs IMMUTABLE flag from Android12

---

src/FlightDisplay/FlyViewToolStripActionList.qml

@DonLakeFlyer 
I have just fixed the error.

3D View: Fixing the error in FlyViewToolStripActionList

---

docs/en/qgc-dev-guide/getting_started/index.md
tools/setup/ubuntu.sh

See doc changes for how it works

Added shell script to setup ubuntu tools for building

---

.github/workflows/macos_debug.yml

I have literally no idea how to use a mac but at least this should build with cmake.

Add macos debug workflow

---

.github/workflows/android_release.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release.yml
.github/workflows/macos_debug.yml
.github/workflows/videoapp_linux.yml
.github/workflows/windows_debug.yml
.github/workflows/windows_release.yml

Uses the new ubuntu setup script to install all dependencies
Builds android using the latest ubuntu
Moves saving PDB to windows debug
Corrects some variable usage
Fixes some cmake usage
Updates the visual studio shell action to an actively maintained one

Update CI Workflows

---

src/FlightDisplay/FlyViewMap.qml
src/FlightMap/FlightMap.qml

Rework Map drag/pinch/click

---

src/CMakeLists.txt
src/QtLocationPlugin/CMakeLists.txt
src/QtLocationPlugin/QGeoServiceProviderPluginQGC.cpp

I renamed the library because internally it adds another plugin target so it was QtLocationPluginplugin or something like that

Create QtLocationPlugin in CMake

---

cmake/Qt6QGCConfiguration.cmake
src/CMakeLists.txt

Remove winrt from cmake

---

src/PlanView/PlanToolBarIndicators.qml
src/PlanView/PlanView.qml
src/ui/MainRootWindow.qml
src/ui/toolbar/PlanViewToolBar.qml

* Fix plan view upload progress bar
* Fix Fly<->Plan view transitions
* Fix #11170

Plan view fixes

---

src/MissionManager/MissionController.cc
src/MissionManager/PlanManager.cc
src/MissionManager/PlanManager.h
src/PlanView/PlanToolBarIndicators.qml
src/PlanView/PlanView.qml
src/Vehicle/InitialConnectStateMachine.cc
src/ui/MainRootWindow.qml
src/ui/toolbar/PlanViewToolBar.qml

First of all it's crap coding. Second it was causing bugs with progress bar updates.

Remove globals.planMasterControllerPlanView

---

src/QmlControls/EditPositionDialog.qml

Decided I didn't like the visuals. New:

Edit Position Dialog: Rework visuals

---

CMakeLists.txt

These should be some of the last properties/variables that need to be set for android deployment

Cmake: Set some deploy properties

---

src/FlightDisplay/GripperMenu.qml
src/QmlControls/QGCButton.qml
src/QmlControls/QGCColumnButton.qml

Fix support for icons in buttons

---

src/FlightMap/FlightMap.qml
src/ui/MainRootWindow.qml

Not sure wht. Went back to old way of panning map. Fix #11193

DragHandler for map was bleeding through to lower controls

---

src/FlightDisplay/FlyView.qml
src/ui/MainRootWindow.qml

Fix code to drop message indicator

---

.github/workflows/android_debug.yml
CMakeLists.txt
cmake/Qt6QGCConfiguration.cmake

This includes the translations into the executable, which were missing w/ cmake build

CMake: add translations

---

src/comm/LinkManager.cc
src/comm/LinkManager.h
src/ui/preferences/LinkSettings.qml
src/ui/toolbar/LinkIndicator.qml

* Fix #10815
* Added autoconnect settings to Comm Links page
* Modified the LinkManager autoconnect so that it doesn't spew continuous autoconnect wait logging

Fix comm link switching

---

.github/workflows/android_debug.yml

This fix is related to [this](https://github.com/jurplel/install-qt-action/issues/224) and should just be temporary.

CI: Fix Debug Android Build

---

docs/en/qgc-user-guide/releases/privacy_policy.md

Added a comprehensive privacy policy for Google Play compliance on their app store. Please note that this is a standard agreement, and we don't collect any data outside the device.

Privacy Policy Updates

---

src/ui/preferences/LinkSettings.qml
src/ui/toolbar/MainStatusIndicatorOfflinePage.qml

Add missing RTK auto-connect setting

---

src/QmlControls/SliderSwitch.qml

Rework space bar confirmation support

---

src/QmlControls/QGCColoredImage.qml

Reverts mavlink/qgroundcontrol#11308

Revert "Fix colorized icon with Qt5Compat.GraphicalEffects instead MultiEffet from Qt6"

---

.github/workflows/android_debug.yml
.github/workflows/android_release.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release.yml
.github/workflows/macos_debug.yml
.github/workflows/macos_release.yml
.github/workflows/windows_debug.yml
.github/workflows/windows_release.yml
CMakeLists.txt
QGCPostLinkCommon.pri
deploy/docker/Dockerfile-build-linux
qgroundcontrol.pro
src/CMakeLists.txt
src/QmlControls/QGCColoredImage.qml

https://github.com/mavlink/qgroundcontrol/pull/11308

Revert usage Qt5Compat module for QML ColorOverlay

---

android/src/AndroidInit.cpp
src/CMakeLists.txt
src/main.cc

Move Android Init code to its own file

Android: Separate Out Init

---

.github/actions/upload/action.yml
.github/workflows/docs_deploy.yml

Small fix and formatting in upload action,
Minor formatting improvements to Docs workflow and update nodeJS to 20.

CI Docs and Upload Fixes

---

custom-example/res/Custom/Widgets/CustomAttitudeWidget.qml
custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc

Description
-----------
Custom build example does not compile. This merge request fixes small compilation errors.
Test Steps
-----------
- Copy `custom-example` folder to `custom`
- Run `cd custom && python ./updateqrc.py`
- Build the application normally
Checklist:
----------
- [X ] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [X ] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [ X] I have tested my changes.

Fix custom build example

---

src/Vehicle/FTPManager.cc

FTP Manager - List directory ack - Remove offset check

---

.github/workflows/docs_deploy.yml

Vitepress config uses this environment variable

CI: Fix Docs Deploy

---

.github/workflows/linux.yml

Makes Vulkan available for Linux at build time

CI: Install Vulkan SDK

---

CMakeLists.txt
src/Audio/AudioOutput.cc
src/Audio/AudioOutput.h
tools/setup/ubuntu.sh

Install the dependencies needed for linux speech to text and reformat AudioOutput like the rest of QGC.

AudioOutput: Formatting and Dependencies

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Only run changed workflows in pull requests

CI: Ignore Paths to Other Workflows

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Adjust paths of previous commit

CI: Adjust ignore paths

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

CI: Add caching again

---

.github/workflows/android-windows.yml

Adds a CI Workflow to build Android from Windows. Does not run automatically.

CI: Add Android Windows Build Workflow

---

.github/workflows/android-macos.yml

Adds CI workflow for building Android with MacOS. Does not run automatically.

CI: Add Android MacOS Workflow

---

src/comm/CMakeLists.txt

CMake: Fetch Mavlink

---

qgroundcontrol.pro
src/QtLocationPlugin/QGCLocationPlugin.pri

Reverts mavlink/qgroundcontrol#11402

Revert "QMake: Remove remaining build files"

---

QGCCommon.pri
QGCExternalLibs.pri
QGCPostLinkCommon.pri
QGCPostLinkInstaller.pri
android.pri
custom-example/custom.pri
custom-example/custom_deploy.pri
libs/qtandroidserialport/src/qtandroidserialport.pri
qmlglsink.pri
src/VideoReceiver/VideoReceiver.pri
test/QGCTest.pri

Reverts mavlink/qgroundcontrol#11401

Revert "QMake: Remove old build system"

---

QGCExternalLibs.pri
android.pri
qgroundcontrol.pro

Fixes linking to several files that have changed.

QMake: Fix linking to files

---

.github/workflows/windows.yml

Install Vulkan SDK on Windows for build

CI: Windows Install Vulkan Headers

---

.github/workflows/windows-arm.yml

Create a manual Windows Arm64 Workflow. This platform is still Technical Preview in Qt6.6.

CI: Add Windows Arm Workflow

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Installing the newest ccache/sccache first yields better results.

CI: Caching Updates

---

src/Utilities/CMakeLists.txt
src/Vehicle/LibEvents/CMakeLists.txt
src/comm/CMakeLists.txt

Failing to fetch specified commits

CMake: Fix FetchContent

---

cmake/DownloadGStreamer.cmake
cmake/FindGStreamer.cmake

Android wasn't downloading gstreamer when environment variable was set

CMake: Fix Downloading GStreamer

---

.github/workflows/docker.yml

CI: Add Docker Workflow

---

resources/opengl/buglist.json
src/main.cc

Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Video: Use Default OpenGL Buglist

---

deploy/multipass/run-multipass.sh

Adds multipass as a method of deployment

Deploy: Add Multipass Deployment

---

deploy/multipass/run-multipass.sh

Retrieve the appimage from the build

Deploy: transfer multipass appimage

---

.github/ISSUE_TEMPLATE/question.md

Try to limit random unrelated questions

Issues: Add Question Template

---

src/UTMSP/CMakeLists.txt

Otherwise executable can't find them.

CMake: Make UTMSP Resources Public

---

qgroundcontrol.pro
test/CMakeLists.txt
test/QGCTest.pri
test/UnitTestList.cc
test/Vehicle/InitialConnectTest.cc

Changes in cmake were not reflected in qmake.

qmake: fix building

---

src/Settings/AppSettings.cc
src/Settings/CustomMavlinkActionsSettings.cc
translations/README.md
translations/qgc-json.ts
translations/qgc.ts

* Fix up some tr usage problems
* Add Ukrananian as Test Only language
* Update translation string set to latest source
Related to #10340

Translations update

---

docs/en/qgc-dev-guide/getting_started/index.md

Dev guide: Switch build to cmake

---

src/AnalyzeView/LogDownloadPage.qml
src/FirmwarePlugin/APM/APMBatteryIndicator.qml
src/QGCApplication.cc

* Fix #11411
* Fix #11371
* Fix #11424
New batter indicator. @HTRamsey More understable?

Log download, ArduPilot Battery Indicator, QGC version check not on for daily builds

---

qgroundcontrol.pro
src/AnalyzeView/MavlinkConsoleController.h
src/AutoPilotPlugins/APM/APMFlightModesComponentController.h
src/AutoPilotPlugins/PX4/PX4SimpleFlightModesController.h
src/Geo/QGCGeo.cc
test/QGCTest.pri

Error Output and fix error catching type

qmake build fixes

---

src/Settings/FlyView.SettingsGroup.json
translations/qgc-json.ts
translations/qgc-lupdate-json.py
translations/qgc.ts

Xlat update

---

src/QmlControls/QGroundControl/Controls/qmldir
src/QmlControls/QGroundControl/FlightMap/qmldir

Needed to move these resources in qmldir too

Qml: Fixup qmldir

---

src/Comms/LinkManager.cc
src/Comms/MAVLinkProtocol.cc
src/FactSystem/FactSystem.cc
src/Joystick/JoystickManager.cc
src/MissionManager/MissionCommandTree.cc
src/PositionManager/PositionManager.cpp
src/QGCApplication.cc
src/QGCToolbox.cc
src/Vehicle/MultiVehicleManager.cc
src/Viewer3D/Viewer3DManager.cc
src/Viewer3D/Viewer3DManager.h

These will be removed anyways, but clean up a little now.

Clean up some old method Qml Registrations

---

QGCPostLinkCommon.pri
src/Utilities/DeviceInfo.cc

Need a backup to QNetworkInformation if there is a permissions issue.

Add Missing Plugin for QNetworkInformation on QMake 

---

qgroundcontrol.pro

Need this when not including QGCTest.pri

include QtTest for signals on qmake

---

docs/en/qgc-dev-guide/getting_started/index.md

Fixes #11586
@hamishwillee is this all that is needed? Do the other language folders need to be kept in parity with en? I suppose the bot is meant to handle that?

Docs: Add Qt Sensors

---

.github/workflows/android-macos.yml
.github/workflows/android-windows.yml
.github/workflows/android.yml
.github/workflows/ios.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows-arm.yml
.github/workflows/windows.yml

We don't need to build it manually anymore now that they have updated the release version.
Closes #11285

CI: Update Install Qt Action

---

src/AutoPilotPlugins/APM/APMSensorsComponent.cc

APM: Fix APMSensorsComponent Compass Triggers

---

tools/setup/install-dependencies-debian.sh

We had some extra stuff and were missing a few things (although they were probably dependencies to other installed libs).

Tools: Update Linux Dependencies

---

src/AnalyzeView/CMakeLists.txt
src/AnalyzeView/GeoTagWorker.cc
src/AnalyzeView/PX4LogParser.cc
src/AnalyzeView/PX4LogParser.h
src/AnalyzeView/ULogParser.cc
src/AnalyzeView/ULogParser.h
test/AnalyzeView/CMakeLists.txt
test/AnalyzeView/PX4LogParserTest.cc
test/AnalyzeView/PX4LogParserTest.h
test/AnalyzeView/ULogParserTest.cc
test/AnalyzeView/ULogParserTest.h
test/CMakeLists.txt
test/UnitTestList.cc

Just need someone to provide sample logs

AnalyzeView: Add ULogParser UnitTest

---

src/Audio/AudioOutput.cc
src/Audio/AudioOutput.h

This is a test of auto-generating documentation.

AudioOutput: Add Documentation

---

CMakeLists.txt

We can marginally reduce build size through this

CMake: Exclude Unused Plugins

---

src/ADSB/ADSBTCPLink.cc
src/ADSB/ADSBTCPLink.h
src/ADSB/ADSBVehicle.h
src/ADSB/ADSBVehicleManager.cc

Related to #11598. Converts the QThread subclassing to use timed signal/slot processing.

ADSB: Convert Threading to Signals/Slots

---

android/src/AndroidInit.cpp
android/src/AndroidInterface.cc
android/src/AndroidInterface.h

Provides a java class finder helper and performs minor code quality maintenance

Android: Update Interface

---

translations/qgc_json_zh_CN.ts

I did a full build on Crowdin and brought all files down to here. These are the only differences. So hopefully after this this will flow through smoothly.

Tranlsations: Bring up to date with Crowdin

---

.github/actions/docker/action.yml
.github/workflows/linux.yml
deploy/docker/Dockerfile-build-ubuntu
deploy/docker/run-docker.sh
tools/setup/install-dependencies-debian.sh
tools/setup/install-qt-debian.sh

Linux: Update Deployment Tools

---

src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
src/VideoManager/VideoReceiver/GStreamer/GLVideoItemStub.h

Fix parenting of GLVideoItemStub

VideoReceiver: Fix GLVideoItemStub Constructor

---

src/VehicleSetup/JoystickConfigCalibration.qml

Joystick cal: Fix  jscript injection

---

qgroundcontrol.pro
src/Comms/MAVLinkProtocol.cc
src/MAVLink/CMakeLists.txt
src/MAVLink/MAVLinkLib.h
src/MAVLink/MAVLinkSigning.cc
src/MAVLink/MAVLinkSigning.h
src/MAVLink/QGCMAVLink.cc
src/MAVLink/QGCMAVLink.h
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/UI/preferences/TelemetrySettings.qml
src/Utilities/DeviceInfo.cc
src/Utilities/DeviceInfo.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
test/CMakeLists.txt
test/MAVLink/CMakeLists.txt
test/MAVLink/SigningTest.cc
test/MAVLink/SigningTest.h
test/UnitTestList.cc

Todo: Probably should disable the enable switch until a valid key is entered? 
Closes #8958

MAVLink: Add Signing

---

cmake/Git.cmake
deploy/linux/org.mavlink.qgroundcontrol.metainfo.xml.in

Configure would fail in forks without any tags

CMake: Fix Git Version Without Tag

---

deploy/windows/nullsoft_installer.nsi
src/main.cc

This should hopefully fix running windows and the shortcuts not working.
Edit: I just realized this will mess up the qmake install, so maybe this has to wait until we get rid of qmake?

Windows: Fix Install

---

CMakeLists.txt

Windows Icon wasn't being set correctly and possible MacOS

CMake: Fix Icons

---

src/AirLink/AirlinkLink.cc
src/Comms/BluetoothLink.cc
src/Comms/BluetoothLink.h
src/Comms/LinkConfiguration.cc
src/Comms/LinkConfiguration.h
src/Comms/LinkInterface.cc
src/Comms/LinkInterface.h
src/Comms/LinkManager.cc
src/Comms/LogReplayLink.cc
src/Comms/LogReplayLink.h
src/Comms/MockLink/MockLink.cc
src/Comms/MockLink/MockLink.h
src/Comms/SerialLink.cc
src/Comms/SerialLink.h
src/Comms/TCPLink.cc
src/Comms/TCPLink.h
src/Comms/UDPLink.cc
src/Comms/UDPLink.h

Initial prep for work involving #11598 (such as #11655) by cleaning up LinkInterface & LinkConfiguration classes
Fixes documentation format

Comms: Update LinkInterface & LinkConfiguration

---

src/AutoPilotPlugins/APM/APMRadioComponent.cc
src/AutoPilotPlugins/AutoPilotPlugin.cc
src/AutoPilotPlugins/AutoPilotPlugin.h
src/AutoPilotPlugins/PX4/SensorsComponent.cc
src/AutoPilotPlugins/PX4/SensorsComponent.h
src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml
src/AutoPilotPlugins/PX4/SensorsSetup.qml
src/VehicleSetup/VehicleComponent.cc
src/VehicleSetup/VehicleComponent.h
src/VehicleSetup/VehicleSummary.qml

Backport of https://github.com/mavlink/qgroundcontrol/pull/11425

[BACKPORT v4.4] Rework PX4 airspeed cal due to parameter name/functionality changes

---

.github/workflows/android.yml
.github/workflows/linux.yml

This action removes a bunch of stuff we don't need such that there is a lot of free space now.

CI: Fix Running out of Space

---

.github/workflows/android_release.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release.yml
.github/workflows/macos_release.yml
.github/workflows/windows_release.yml
android/AndroidManifest.xml

As recommended by @HTRamsey, let's see!

[v4.4] CI: fix Android build

---

src/MissionManager/BlankPlanCreator.cc
src/PlanView/PlanView.qml
src/QmlControls/SectionHeader.qml

* Fix for #11544
* Related to #11691
* Also fixed bugs related to SectionHeader

Plan: Change Create Plan/Blank to Create Plan/Empty Plan

---

docs/en/qgc-dev-guide/release_branching_process.md

This confused me last time, so we should probably add it to the docs.

docs: Mention how cloudfront links work

---

src/AnalyzeView/LogDownloadController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/PX4/SensorsComponentController.cc
src/Camera/QGCCameraIO.cc
src/Camera/VehicleCameraControl.cc
src/FactSystem/ParameterManager.cc
src/FirmwarePlugin/FirmwarePlugin.cc
src/GPS/RTCMMavlink.cc
src/MissionManager/MissionManager.cc
src/MissionManager/PlanManager.cc
src/MissionManager/PlanMasterController.cc
src/Vehicle/Components/ComponentInformationManager.cc
src/Vehicle/FTPManager.cc
src/Vehicle/TerrainProtocolHandler.cc

Fix race condition on link pointer going away and then causing crashes

Fix incorrect usage of weak pointers

---

ChangeLog.md
src/Comms/LinkInterface.cc
src/Comms/LinkInterface.h
src/Comms/LinkManager.cc
src/Comms/LinkManager.h
src/Comms/SerialLink.cc
src/Comms/SerialLink.h
src/Comms/TCPLink.cc
src/Comms/TCPLink.h
src/Comms/UDPLink.cc
src/Comms/UDPLink.h
src/MAVLink/MAVLinkSigning.cc
src/MAVLink/MAVLinkSigning.h
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/UI/preferences/TelemetrySettings.qml
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleLinkManager.cc
test/MAVLink/SigningTest.cc

This fixes the problem of using the correct signing callback on secure/insecure connection

New secure connection identification for mavlink signing

---

src/QtLocationPlugin/QGCCacheTile.h
src/QtLocationPlugin/QGCCachedTileSet.cpp
src/QtLocationPlugin/QGCCachedTileSet.h
src/QtLocationPlugin/QGCMapTasks.h
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc

Update this class in accordance with recent changes to the QtLocationPlugin code and perform code maintenance.

QtLocationPlugin: Cleanup QGCCachedTileSet

---

src/Comms/LinkConfiguration.cc
src/Comms/LinkConfiguration.h
src/Comms/LinkInterface.cc
src/Comms/LinkInterface.h
src/Comms/MAVLinkProtocol.cc
src/Comms/MAVLinkProtocol.h
src/Comms/MockLink/MockLink.cc
src/Comms/SerialLink.cc
src/Comms/TCPLink.cc

Comms: Fix Private Variable Naming

---

src/AutoPilotPlugins/PX4/BatteryParams.qml
src/AutoPilotPlugins/PX4/PowerComponent.qml

This param is removed in newer PX4 firmwares
Fix #11716

Conditional support for BAT#_V_LOAD_DROP

---

src/AnalyzeView/CMakeLists.txt
src/AnalyzeView/ULogParser.cc
src/AnalyzeView/ULogParser.h

Use [ulog_cpp](https://github.com/PX4/ulog_cpp) to parse ulogs. This greatly simplifies our code and provides an easy & quick way to extend our implementation

AnalyzeView: Add ulog_cpp dependency

---

src/FlightDisplay/GuidedActionsController.qml
src/Settings/FlightMode.SettingsGroup.json
src/UI/toolbar/FlightModeIndicator.qml

Flight mode confirmation

---

src/Camera/QGCCameraManager.cc
src/Camera/QGCCameraManager.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
test/Vehicle/RequestMessageTest.cc

@julianoes Can you look at the changes to the camera manager?
@HTRamsey Can you sanity check the Vehicle changes to support multiple message requests in play at one time

Better request message support, change camera manager to use existing Vehicle methods

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

v1.13.1 requires sdk 35 instead of 34

Android: Use older androidx.core version

---

src/CMakeLists.txt
src/QGCApplication.cc
src/QGCApplication.h
src/RunGuard.cc
src/RunGuard.h
src/main.cc

Reverts mavlink/qgroundcontrol#11597
Seems to be issues reopening if the app doesn't close cleanly. Probably RunGuard needs to be updated instead for now

Revert "Replace RunGuard with SingleApplication"

---

deploy/docker/Dockerfile-build-ubuntu
deploy/docker/run-docker.sh

Closes #11808
fatal: detected dubious ownership in repository at '/project/source'
To add an exception for this directory, call:
git config --global --add safe.directory /project/source

Docker: Fix git error during configure

---

src/AnalyzeView/ULogParser.cc

In the event that the keys change

ULogParser: catch access exceptions

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

It sets some environment variables and such

CI: Use Qt's CMake Setup

---

src/FlightDisplay/GuidedActionConfirm.qml

Fix centering of launch card

---

src/Comms/LinkManager.cc
src/Comms/LinkManager.h
src/Comms/QGCSerialPortInfo.cc
src/Comms/QGCSerialPortInfo.h
src/Comms/SerialLink.h
test/CMakeLists.txt
test/Comms/CMakeLists.txt
test/Comms/QGCSerialPortInfoTest.cc
test/Comms/QGCSerialPortInfoTest.h
test/UnitTestList.cc

Fixes #11500 and adds unit test, one small update pending until after seriallink is updated

Comms: Update QGCSerialPortInfo

---

src/FlightDisplay/FlyViewVideo.qml
src/VideoManager/VideoManager.cc
src/VideoManager/VideoManager.h

It was attempting to delete QtMultimediaReceiver even if not being used

VideoManager: Fix crash on exit

---

src/Audio/AudioOutput.cc
src/Audio/AudioOutput.h
src/Audio/CMakeLists.txt
src/QGCApplication.cc
src/Vehicle/Vehicle.cc

This way QTextToSpeech isn't required to link against everything

Audio: Remove QTextToSpeech Inheritance

---

cmake/FindGeographicLib.cmake
src/Geo/CMakeLists.txt
src/Geo/QGCGeo.cc
src/Geo/QGCGeo.h
src/Joystick/CMakeLists.txt

Find from system first if available

Geo: Update CMake GeographicLib Inclusion

---

src/Comms/LinkManager.cc

Comms: Fix Serial Autoconnect

---

src/AutoPilotPlugins/PX4/SensorsComponent.cc

Airspeed cal: Fix version check

---

src/CMakeLists.txt
src/Gimbal/CMakeLists.txt
src/Joystick/CMakeLists.txt
src/Settings/CMakeLists.txt
src/Vehicle/CMakeLists.txt

Fixes to CMakeFiles in order to build v4.4.2 with cmake.

v4.4.2 fix cmake

---

src/UI/toolbar/RTKGPSIndicator.qml

RTK: Fix hiding indicator which vehicle is present

---

.github/workflows/cache-cleanup.yml

Allows us to delete all the extra actions caches easily

CI: Add Cache Cleaning Workflow

---

src/UI/preferences/FlyViewSettings.qml

Fix visibility support for 3d view settings

---

src/QtLocationPlugin/CMakeLists.txt
src/QtLocationPlugin/QGCMapEngine.cpp
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGCTileCacheWorker.h

Minor cleanup and changes to link Qt SQL privately

QtLocationPlugin: Link SQL Privately

---

src/QmlControls/HorizontalFactValueGrid.qml
src/QmlControls/InstrumentValueEditDialog.qml
src/QmlControls/LabelledComboBox.qml
src/QmlControls/QGCRadioButton.qml

Related to #11895
Before:
After:

Telemetry display update

---

.github/actions/upload/action.yml

If there is no aws credentials secret, then don't try to upload to aws

CI: Fix Building in Forks

---

src/Comms/CMakeLists.txt
src/Comms/LinkManager.cc
src/Comms/LinkManager.h

Missed a few things on the first time through

Comms: Finish LinkManager Cleanup

---

src/Settings/AutoConnectSettings.cc

AutoConnect settings - Rename group name

---

src/QmlControls/InstrumentValueEditDialog.qml

Group/Value combo not being initialized. Not sure why currentIndex wasn't working...

Telemetry Edit Dialog: Fix combo init

---

src/QmlControls/LabelledComboBox.qml

QmlControls: Fix LabelledComboBox Text

---

.github/workflows/macos.yml
CMakeLists.txt
cmake/find-modules/FindShapelib.cmake
src/Utilities/CMakeLists.txt
tools/setup/install-dependencies-debian.sh

Search for shapelib before building it

CMake: Allow to find Shapelib

---

src/UI/preferences/GeneralSettings.qml

Restore the ability to choose between Never,Always,When in Follow Me Flight Mode for Follow

Follow: Restore Combobox settings

---

src/FirmwarePlugin/APM/APMSensorIdDecoder.qml

I just updated the list from Ardupilot `master`

Update Ardupilot sensor types

---

.github/workflows/linux.yml

https://doc.qt.io/qt-6.7/linux.html

CI: Change Linux GCC Version to 11

---

src/AnalyzeView/LogDownloadPage.qml

Log Download: Fix button layout

---

src/QmlControls/InstrumentValueEditDialog.qml

Fix #11941
Problem was race condition on model and currentIndex. Use actual data directly instead.

Cleaner mechanism for init of currentIndex

---

src/FlightDisplay/GuidedActionsController.qml

Allow ROI while mission is running

---

.github/actions/upload/action.yml
.github/workflows/android-linux.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Temporarily disable continuous release

CI: Fix Continuous Release

---

.github/actions/gstreamer/action.yml
.github/workflows/linux.yml

Builds gstreamer to get video working on ubuntu 20.04

Linux: Build GStreamer

---

src/GPS/GPSProvider.cc

Fix Threading Issues for the GPS Provider

GPS: Threading Fixes

---

docs/en/qgc-dev-guide/getting_started/index.md

**Title**: Video Streaming URL Changed
**Description**  
Updated the video streaming URL in the documentation to improve accessibility and ensure the latest information on setting up video streaming with QGroundControl.
**Test Steps**  
1. Click on the updated **Video Streaming** link.
2. Confirm that it opens the correct information at the updated URL.
3. Verify that the content is accessible and matches the intended information.
**Checklist**  
**Related Issue**  
- None.

Video Streaming URL Changed

---

.github/workflows/linux.yml

xvfb-run is included in the runner now

CI: Remove Linux setup-xvfb Action

---

src/Comms/CMakeLists.txt
src/Comms/LinkManager.cc
src/FollowMe/FollowMe.cc
src/PositionManager/CMakeLists.txt
src/PositionManager/PositionManager.cpp
src/PositionManager/PositionManager.h
src/PositionManager/SimulatedPosition.cc
src/PositionManager/SimulatedPosition.h
src/QGCApplication.cc
src/QGCToolbox.cc
src/QGCToolbox.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/CMakeLists.txt
src/Vehicle/RemoteIDManager.cc
src/Vehicle/RemoteIDManager.h
src/Vehicle/Vehicle.cc
test/FollowMe/FollowMeTest.cc

Convert PositionManager from Tool to Singleton
Also fix variable naming convention

PositionManager: Convert to Singleton

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/MissionManager/KMLPlanDomDocument.cc
src/MissionManager/MissionCommandTree.cc
src/MissionManager/MissionCommandTree.h
src/MissionManager/MissionController.cc
src/MissionManager/MissionManager.cc
src/MissionManager/PlanManager.cc
src/MissionManager/PlanManager.h
src/MissionManager/SimpleMissionItem.cc
src/MissionManager/SimpleMissionItem.h
src/MissionManager/TakeoffMissionItem.cc
src/MissionManager/TransectStyleComplexItem.cc
src/QGCApplication.cc
src/QGCToolbox.cc
src/QGCToolbox.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/Vehicle.cc
test/MissionManager/CameraSectionTest.cc
test/MissionManager/MissionCommandTreeTest.cc
test/MissionManager/MissionCommandTreeTest.h

Convert MissionCommandTree to Singleton

Convert MissionCommandTree to Singleton

---

src/AnalyzeView/MAVLinkConsoleController.cc
src/AnalyzeView/MAVLinkConsoleController.h
src/AnalyzeView/MAVLinkConsolePage.qml

Fix parenting, organize code, and use best practices of modern c++
No logical changes
Tested on Cube Black, PX4 1.15.1

AnalyzeView: Cleanup MAVLinkConsoleController

---

src/MissionManager/PlanManager.cc

Fix PlanManager logging

---

src/Comms/USBBoardInfo.json
src/VehicleSetup/FirmwareUpgradeController.cc

Dear Professors,I just added the support for ZeroOne X6，we are looking forward to your review and merger.

Hardware: Add support for ZeroOne X6

---

src/Comms/USBBoardInfo.json

Thanks for the heads up @HTRamsey

Hardware: Fix USBBoardInfo.json

---

src/Comms/USBBoardInfo.json

Adds support for Tropic-Community VMU running PX4
https://github.com/NXPHoverGames/TropicCommunityVMU
Vendor ID: 0x1FC9
Product ID: 0x0024

Add Tropic-Community VMU board

---

.github/workflows/android-macos.yml
.github/workflows/macos.yml

Should just build from source then if downloading a lib through brew fails

CI: Attempt to continue building if brew fails

---

src/API/CMakeLists.txt
src/CMakeLists.txt
src/Camera/CMakeLists.txt
src/Camera/QGCCameraManager.cc
src/Camera/QGCCameraManager.h
src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h
src/Joystick/CMakeLists.txt
src/MissionManager/CMakeLists.txt
src/MissionManager/MissionManager.cc
src/MissionManager/MissionManager.h
src/PositionManager/CMakeLists.txt
src/QGCApplication.cc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Vehicle/MultiVehicleManager.cc

Small step towards migrating to Qt6 method of registrations
Reduce some CMake linking too

Move some QML registrations to their respective lib

---

src/Comms/QGCSerialPortInfo.cc
src/Comms/QGCSerialPortInfo.h
test/Comms/QGCSerialPortInfoTest.cc

Add a test to verify parsing USBBoardInfo.json works correctly
Also change json parsing to use a higher level helper

Comms: Fix USBBoardInfo Parsing Test

---

src/AnalyzeView/CMakeLists.txt
src/Audio/CMakeLists.txt
src/CMakeLists.txt
src/Comms/CMakeLists.txt
src/QtLocationPlugin/CMakeLists.txt
src/VideoManager/CMakeLists.txt
src/VideoManager/VideoReceiver/QtMultimedia/CMakeLists.txt
src/pch.h

CMake: Update PCH

---

src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/Comms/CMakeLists.txt
src/Comms/LinkInterface.cc
src/Comms/LinkManager.cc
src/Comms/LinkManager.h
src/Comms/LogReplayLink.cc
src/Comms/MAVLinkProtocol.cc
src/Comms/MockLink/MockLink.cc
src/Comms/SerialLink.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/QGCApplication.cc
src/QGCToolbox.cc
src/QGCToolbox.h
src/QmlControls/QGroundControlQmlGlobal.cc
src/Settings/AppSettings.cc
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h
src/Vehicle/VehicleLinkManager.cc
src/Vehicle/VehicleLinkManager.h
src/VehicleSetup/FirmwareUpgradeController.cc
test/Vehicle/InitialConnectTest.cc
test/Vehicle/VehicleLinkManagerTest.cc
test/qgcunittest/UnitTest.cc
test/qgcunittest/UnitTest.h

Convert LinkManager from Tool to Singleton

Convert LinkManager to Singleton

---

src/VehicleSetup/FirmwareUpgradeController.cc

Description
-----------
Add board id for CUAV 7-Nano.

Hardware: Add support for CUAV 7-Nano

---

src/QmlControls/SettingsGroupLayout.qml
src/UI/preferences/RemoteIDSettings.qml

Description
-----------
- Update settings page for remoteID
- Update toolbar indicator for remoteID 
Test Steps
-----------
1) App Settings --> MockLink --> Start Mocklink
2) App Settings --> Remote ID
Related Issue
-----------
https://github.com/mavlink/qgroundcontrol/issues/12018

Remote id UI refactor

---

qgroundcontrol.qrc
src/Vehicle/FactGroups/CMakeLists.txt
src/Vehicle/FactGroups/RPMFact.json
src/Vehicle/FactGroups/VehicleRPMFactGroup.cc
src/Vehicle/FactGroups/VehicleRPMFactGroup.h
src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Add new RPM vehicle FactGroup

---

cmake/find-modules/FindGStreamer.cmake
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt

trying to resolve linking issue for android found by some

CMake: FindGStreamer adjustments

---

.github/workflows/custom.yml

Description
-----------
Added a GitHub workflow to test the custom build functionality, as changes in the firmware or autopilot plugins may break their custom counterparts. The test is performed with a Windows release build.
Checklist:
----------

Add GitHub workflow to test custom builds

---

android/libs/qtandroidserialport/qserialport_android.cpp
android/libs/qtandroidserialport/qserialport_p.h

Some threading fixes for Android serial

Android: Serial Read/Write fixes

---

.github/workflows/custom.yml

@rubenp02 FYI I am removing the upload portion and other unnecessary parts since all we care about is that the custom build actually builds correctly

CI: Don't Upload Custom Build

---

src/Comms/CMakeLists.txt
src/Comms/LinkConfiguration.cc
src/Comms/LinkConfiguration.h
src/Comms/LinkInterface.h
src/Comms/TCPLink.cc
src/Comms/TCPLink.h
src/UI/preferences/LinkSettings.qml

A couple of minor fixes/improvements for tcp link

Comms: Minor TCP Updates

---

src/Comms/CMakeLists.txt
src/Comms/LinkManager.cc
src/Comms/UDPLink.cc
src/Comms/UDPLink.h
tools/setup/install-dependencies-debian.sh

Related to #11598
Also improves zeroconf implementation debugging
Edit: Just realized an AirLink update will have to immediately follow this

Comms: UDPLink Threading Changes

---

src/API/QGCCorePlugin.cc
src/API/QGCCorePlugin.h

Usage of custom map items may vary. They may need to modify themselves.

Remove const

---

src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/VehicleSetup/SetupView.qml

This is an unused option with no real purpose or use

QML: Remove skipSetupPage option

---

src/Comms/UDPLink.cc

Comms: Ignore UDP Link Multicast Failure

---

src/Comms/BluetoothLink.cc
src/Comms/BluetoothLink.h
src/UI/preferences/BluetoothSettings.qml

Related to https://github.com/mavlink/qgroundcontrol/issues/11598

Comms: Prepare Bluetooth for Threading Changes

---

CMakeLists.txt

Forgot to remove this after removing the actual file

CMake: Remove Resource.h for Windows

---

src/Comms/BluetoothLink.cc
src/Comms/BluetoothLink.h
src/Comms/SerialLink.cc
src/Comms/TCPLink.cc
src/Comms/UDPLink.cc

Don't create sockets until the parent has been moved to new thread

Comms: Create Sockets on New Thread

---

src/QGCApplication.cc
src/Settings/VideoSettings.cc
src/Settings/VideoSettings.h
src/VideoManager/VideoManager.cc
src/VideoManager/VideoManager.h
src/VideoManager/VideoReceiver/GStreamer/GStreamer.cc

VideoManager: Minor Cleanup

---

.github/actions/upload/action.yml

This fails occasionally for unknown reasons

CI: Retry MacOS DMG Upload

---

.gitmodules
qgcresources.qrc
src/Joystick/CMakeLists.txt
src/Joystick/Joystick.cc
src/Joystick/Joystick.h
src/Joystick/JoystickAndroid.cc
src/Joystick/JoystickAndroid.h
src/Joystick/JoystickManager.cc
src/Joystick/JoystickManager.h
src/Joystick/JoystickSDL.cc
src/Joystick/JoystickSDL.h
src/Utilities/QGCLoggingCategory.cc
src/Utilities/QGCLoggingCategory.h

Joystick: SDL & Android cleanup

---

src/AnalyzeView/MAVLinkInspectorController.cc
src/AnalyzeView/MAVLinkMessage.cc
src/AnalyzeView/MAVLinkMessage.h
src/AnalyzeView/MAVLinkMessageField.cc
src/AnalyzeView/MAVLinkMessageField.h
src/AnalyzeView/MAVLinkSystem.cc
src/AnalyzeView/MAVLinkSystem.h

Updates and organizes some of the mavlink classes before using them for other purposes

AnalyzeView: Update MAVLink Classes

---

src/AnalyzeView/MAVLinkChartController.cc
src/AnalyzeView/MAVLinkChartController.h
src/AnalyzeView/MAVLinkInspectorController.cc
src/AnalyzeView/MAVLinkInspectorController.h

AnalyzeView: Update MAVLink Controllers

---

src/QmlControls/ValueSlider.qml

Change from Flickable to DragHandler for sliding. Nested flickables in the control hierarchy would prevent touchpad two finger scrolling of the parent container from working .

ValueSlider: Fix slider scrolling

---

src/FactSystem/FactControls/FactComboBox.qml
src/FirmwarePlugin/PX4/PX4FlightModeIndicator.qml
src/QmlControls/FactSlider.qml
src/QmlControls/ValueSlider.qml

* Remove obscure settings
* Added more useful GeoFence settings

PX4: GeoFence settings in Flight Mode Indicator

---

src/Settings/BatteryIndicator.SettingsGroup.json
src/Settings/BatteryIndicatorSettings.cc
src/Settings/BatteryIndicatorSettings.h
src/UI/toolbar/BatteryIndicator.qml

* Better ordering of items vertically
* Fixed incorrect usage of settings visibility

Battery display rework

---

src/UI/MainRootWindow.qml
src/UI/toolbar/APMSupportForwardingIndicator.qml
src/UI/toolbar/GimbalIndicator.qml
src/UI/toolbar/JoystickIndicator.qml
src/UI/toolbar/RCRSSIIndicator.qml
src/UI/toolbar/TelemetryRSSIIndicator.qml

* Convert remaining indicators to new system
* Remove deprecated indicator system

Tool indicators

---

src/Gimbal/GimbalController.cc

one line change. see commit diff

Fix gimbal yaw clipping

---

src/Comms/BluetoothLink.cc
src/Comms/BluetoothLink.h
src/PositionManager/PositionManager.cpp

Request Bluetooth Permissions, also use static QCoreApplication instance in positionManager.

Comms: Fix Bluetooth Permissions

---

.gitmodules

May as well remove these for now until dependency handling changes

Remove Unused Git Submodules

---

.github/workflows/windows.yml

CI: Update Windows SCCache

---

src/AnalyzeView/CMakeLists.txt

Stay on static commit from last release

AnalyzeView: Set Exiv2 to Release Version

---

.github/actions/upload/action.yml
android/gradle.properties

Also add retry to release action

Android: Enable Gradle Caching

---

.github/workflows/custom.yml
CMakeLists.txt
deploy/ios/iOS-Info.plist
deploy/ios/iOSForAppStore-Info-Source.plist
deploy/mac/MacOSXBundleInfo.plist.in
translations/qgc-json.ts
translations/qgc-lupdate.sh
translations/qgc.ts

add missing entries in plist for QtMultimedia

CMake: Miscellaneous Deployment Updates

---

src/Comms/LinkManager.cc
src/Comms/MockLink/CMakeLists.txt
src/Comms/MockLink/MockConfiguration.cc
src/Comms/MockLink/MockConfiguration.h
src/Comms/MockLink/MockLink.cc
src/Comms/MockLink/MockLink.h

Comms: Update Mocklink Threading

---

cmake/modules/CPM.cmake
cmake/modules/get_cpm.cmake
src/AnalyzeView/CMakeLists.txt
src/FirmwarePlugin/APM/CMakeLists.txt
src/GPS/CMakeLists.txt
src/Joystick/CMakeLists.txt
src/MAVLink/CMakeLists.txt
src/MAVLink/LibEvents/CMakeLists.txt

CMake: Add CPM

---

.github/workflows/macos.yml

OSX Cert secrets now available in GitHub

OSX: Turn on code signing

---

.github/actions/qt-android/action.yml
.github/workflows/android-linux.yml
.github/workflows/android-macos.yml
.github/workflows/android-windows.yml
.github/workflows/ios.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
.gitignore
cmake/CustomOptions.cmake
cmake/modules/vulkan.cmake
src/AnalyzeView/CMakeLists.txt
src/Comms/CMakeLists.txt
src/FirmwarePlugin/APM/CMakeLists.txt
src/GPS/CMakeLists.txt
src/Geo/CMakeLists.txt
src/Joystick/CMakeLists.txt
src/MAVLink/CMakeLists.txt
src/MAVLink/LibEvents/CMakeLists.txt
src/UTMSP/CMakeLists.txt
src/Utilities/CMakeLists.txt
src/Utilities/Compression/CMakeLists.txt

Requires CPM_SOURCE_CACHE environment or variable

Cache dependencies through CPM

---

docs/en/qgc-dev-guide/index.md
docs/en/qgc-user-guide/index.md

Was pointing to wrong release. Will need to go back once 5.0 goes stable

Removed the Releases thingy to reduce confusion

---

docs/en/qgc-dev-guide/getting_started/index.md
docs/en/qgc-dev-guide/index.md

Some more documents cleanup for build instructions

Updates for 5.0 release

---

CMakeLists.txt
cmake/find-modules/FindShapelib.cmake
src/AnalyzeView/CMakeLists.txt
src/Geo/CMakeLists.txt
src/Joystick/CMakeLists.txt
src/Utilities/CMakeLists.txt
src/Utilities/Compression/CMakeLists.txt

Some related to dependencies affecting building windows

Fix Windows Debug Build

---

.github/actions/cache/action.yml
.github/actions/qt-android/action.yml
android/gradle.properties

CI: Android Caching Fixes

---

src/AnalyzeView/CMakeLists.txt

Build Exiv2 as static lib

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
src/main.cc

Should prevent #12372 from sneaking through again

Add simple sanity check on generated release build

---

qgcimages.qrc
src/FlightDisplay/FlyViewAdditionalActionsButton.qml
src/UI/toolbar/Images/HamburgerThin.svg

Switch Actions buttons to hamburger icon

---

src/Vehicle/StandardModes.cc
src/Vehicle/Vehicle.cc

Standard modes protocol now available in all builds

---

cmake/find-modules/FindGStreamer.cmake
src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt

Remove some unneeded code from FindGStreamer

CMake: FindGStreamer Cleanup

---

.github/actions/cache/action.yml
.github/actions/qt-android/action.yml
.github/workflows/android-linux.yml
.github/workflows/android-macos.yml
.github/workflows/android-windows.yml
.github/workflows/custom.yml
.github/workflows/ios.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Error causing workflows not to run

CI: Fix Workflow Paths

---

src/QtLocationPlugin/QMLControl/OfflineMapEditor.qml

Map Settings: Prevent mouse bleed through

---

src/QtLocationPlugin/Providers/GenericMapProvider.cpp
src/QtLocationPlugin/Providers/GenericMapProvider.h

Description
-----------
Updated server URL
Test Steps
-----------
Select statkart while viewing Norway
Checklist:
----------
- [ x] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [x ] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [ x] I have tested my changes.
Related Issue
-----------

Map source for Statkart.

---

src/QtLocationPlugin/Providers/GenericMapProvider.cpp
src/QtLocationPlugin/Providers/GenericMapProvider.h
src/QtLocationPlugin/QGCMapUrlEngine.cpp

Description
-----------
This adds a great map for Svalbard.
Test Steps
-----------
Select Svalbard map when Svalbard is in view.
Checklist:
----------
- [x ] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [ x] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [ x] I have tested my changes.
Related Issue
-----------

Mapsource for Svalbard

---

.github/workflows/android-macos.yml

Will help verify MacOS can build android correctly

CI: Enable android-macos Workflow

---

src/QmlControls/QGCComboBox.qml

Fix #12439
@dakejahl Can you verify this as well once a build pops out?

ComboBox: Fix handling of text role in model data

---

src/UI/MainRootWindow.qml
src/UI/toolbar/BatteryIndicator.qml

* Larger expand button
* Battery page: Slightly larger text fields for percentage
* Related to #12405
@AndKe Can you give this a try once the Action drops an artifact?

Tool indicator changes

---

src/AutoPilotPlugins/PX4/AirframeComponentAirframes.cc
src/AutoPilotPlugins/PX4/PX4AirframeLoader.cc

Fix airframe image resource names

---

src/Vehicle/Vehicle.cc
src/Vehicle/Vehicle.h

Add showError support to sendMavCommandWithLambdaFallback

---

src/QmlControls/QGCComboBox.qml

QGCComboBox: Fix popup sizing

---

qgcimages.qrc
src/UI/SettingsPagesModel.qml
src/UI/toolbar/Images/RidIconManNoID.svg

Following https://github.com/mavlink/qgroundcontrol/pull/12451#issuecomment-2658009229

Fix Remote ID indicator in application settings menu

---

src/FirmwarePlugin/APM/APMFirmwarePlugin.cc

Fix ArduPilot "flying" determination

---

docs/en/qgc-dev-guide/getting_started/index.md
docs/ko/qgc-dev-guide/getting_started/index.md
docs/tr/qgc-dev-guide/getting_started/index.md

Improve QT installation process

---

src/Comms/AirLink/AirLinkLink.cc
src/Comms/AirLink/AirLinkLink.h
src/Comms/BluetoothLink.cc
src/Comms/BluetoothLink.h
src/Comms/CMakeLists.txt
src/Comms/LinkConfiguration.h
src/Comms/LinkInterface.cc
src/Comms/LinkInterface.h
src/Comms/LinkManager.h
src/Comms/LogReplayLink.cc
src/Comms/LogReplayLink.h
src/Comms/MockLink/CMakeLists.txt
src/Comms/MockLink/MockConfiguration.cc
src/Comms/MockLink/MockConfiguration.h
src/Comms/MockLink/MockLink.cc
src/Comms/MockLink/MockLink.h
src/Comms/SerialLink.cc
src/Comms/SerialLink.h
src/Comms/TCPLink.cc
src/Comms/TCPLink.h
src/Comms/UDPLink.cc
src/Comms/UDPLink.h
test/MissionManager/CMakeLists.txt

Comms: Remove LinkInterface QThread Inheritance

---

CMakeLists.txt
resources/qtquickcontrols2.conf

Allows configuring styles/fonts/etc

Add quickcontrol2 style config

---

src/AutoPilotPlugins/APM/CMakeLists.txt
src/AutoPilotPlugins/PX4/CMakeLists.txt
src/Camera/CMakeLists.txt
src/FactSystem/CMakeLists.txt
src/MAVLink/CMakeLists.txt
src/MAVLink/LibEvents/CMakeLists.txt
src/QtLocationPlugin/CMakeLists.txt
src/Utilities/CMakeLists.txt
src/Utilities/Compression/CMakeLists.txt
src/Vehicle/Actuators/CMakeLists.txt
src/Vehicle/CMakeLists.txt
src/Vehicle/ComponentInformation/CMakeLists.txt
src/Vehicle/FactGroups/CMakeLists.txt
src/VehicleSetup/CMakeLists.txt
test/CMakeLists.txt
test/Utilities/CMakeLists.txt
test/Utilities/Compression/CMakeLists.txt
test/Vehicle/CMakeLists.txt
test/Vehicle/ComponentInformation/CMakeLists.txt
test/qgcunittest/CMakeLists.txt

More CMake Linking Simplification

CMake: Simplify Vehicle Linking

---

src/Vehicle/VehicleLinkManager.cc
src/Vehicle/VehicleLinkManager.h
test/CMakeLists.txt
test/UnitTestList.cc
test/Vehicle/VehicleLinkManagerTest.cc
test/Vehicle/VehicleLinkManagerTest.h

Formatting and cleanup
Reenable unit test

Vehicle: Update VehicleLinkManager

---

docs/ko/qgc-dev-guide/command_line_options.md
docs/ko/qgc-dev-guide/getting_started/index.md
docs/ko/qgc-dev-guide/tools/index.md
docs/ko/qgc-user-guide/getting_started/download_and_install.md
docs/ko/qgc-user-guide/settings_view/console_logging.md
docs/tr/qgc-dev-guide/command_line_options.md
docs/tr/qgc-dev-guide/getting_started/index.md
docs/tr/qgc-dev-guide/tools/index.md
docs/tr/qgc-user-guide/getting_started/download_and_install.md
docs/tr/qgc-user-guide/settings_view/console_logging.md
docs/zh/qgc-dev-guide/command_line_options.md
docs/zh/qgc-dev-guide/getting_started/index.md
docs/zh/qgc-user-guide/getting_started/download_and_install.md
docs/zh/qgc-user-guide/settings_view/console_logging.md

New QGC guide Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)

New QGC guide translations (Crowdin)

---

docs/en/qgc-dev-guide/getting_started/index.md

Update docs for using qt-cmake

---

.github/workflows/custom.yml
.github/workflows/windows.yml

CI: Change Windows GStreamer back to 1.22

---

src/FlightDisplay/FlyViewAdditionalCustomActionsList.qml

Gives you better options as to what you can do inside the control

Toolstrip Custom Actions: Switch to using Item

---

src/AutoPilotPlugins/AutoPilotPlugin.cc
src/QGCApplication.cc

Fix switch to Vehicle Configuration on component setup required

---

qgroundcontrol.qrc
src/API/QGCCorePlugin.cc
src/AutoPilotPlugins/APM/APMFollowComponent.qml
src/Comms/LinkInterface.cc
src/Comms/LinkManager.cc
src/Comms/MAVLinkProtocol.cc
src/Comms/MAVLinkProtocol.h
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/QmlControls/QGroundControlQmlGlobal.cc
src/QmlControls/QGroundControlQmlGlobal.h
src/Settings/App.SettingsGroup.json
src/Settings/AppSettings.cc
src/Settings/AppSettings.h
src/Settings/CMakeLists.txt
src/Settings/Mavlink.SettingsGroup.json
src/Settings/MavlinkSettings.cc
src/Settings/MavlinkSettings.h
src/Settings/SettingsManager.cc
src/Settings/SettingsManager.h
src/UI/preferences/TelemetrySettings.qml
src/Vehicle/MultiVehicleManager.cc
src/Vehicle/MultiVehicleManager.h
src/Vehicle/Vehicle.cc

* Some moved from AppSettings
* Some came from ancient code in MavlinkProtocol which did not use new Settings support
* Some came from MultiVehicleManager which did not use new Settings support
* Deprecated settings are moved to new settings
* Fixes problem with old MavlinkProtocol settings not being saved on android

Rework into new MavlinkSettings

---

src/MissionManager/TransectStyleComplexItem.cc

Survey: Fix hover and capture camera triggering

---

.github/workflows/linux.yml

CI: Switch Linux GCC to 11

---

src/Comms/MockLink/CMakeLists.txt
src/Comms/MockLink/MockLink.h

Fix MockLink PX4 Custom Mode Inclusion

---

.github/workflows/macos_release.yml
src/VehicleSetup/FirmwareUpgradeController.cc

This copies the board IDs from the master branch.

[Backport v4.4] Added board ids

---

.github/actions/cache/action.yml
.github/workflows/linux.yml

Trying to fix low linux cache hits

CI: Update ccache

---

.github/workflows/linux.yml
CMakeLists.txt
src/AutoPilotPlugins/PX4/AirframeComponentController.cc
src/CMakeLists.txt
src/Joystick/JoystickManager.cc
src/MissionManager/MissionCommandTree.cc
src/PositionManager/PositionManager.cpp
src/QmlControls/CMakeLists.txt
src/QtLocationPlugin/CMakeLists.txt
src/Viewer3D/Viewer3DManager.cc

CMake: Adjust PCH

---

.github/workflows/android_release.yml

By preventing Android SDK 36 to be used.
Yet again...

[V4.4] CI: try to fix Android

---

custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/Vehicle/StandardModes.cc
src/Vehicle/StandardModes.h
src/Vehicle/Vehicle.cc

* Fixes signalling error on flight mode update
* Adds better logging
* Related to #12549

Cleanup Mavlink Standard Modes Protocol support

---

custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc
custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.h
src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
src/FirmwarePlugin/APM/APMFirmwarePlugin.h
src/FirmwarePlugin/APM/APMFirmwarePluginFactory.cc
src/FirmwarePlugin/APM/APMFirmwarePluginFactory.h
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/APM/APMParameterMetaData.h
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/FirmwarePluginFactory.cc
src/FirmwarePlugin/FirmwarePluginFactory.h
src/FirmwarePlugin/FirmwarePluginManager.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h

Cleanup base FirmwarePlugin class

FirmwarePlugin: Cleanup

---

.github/actions/qt-android/action.yml
.github/workflows/android-linux.yml
.github/workflows/android-macos.yml
.github/workflows/android-windows.yml
.github/workflows/custom.yml
.github/workflows/ios.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
cmake/CustomOptions.cmake
deploy/docker/Dockerfile-build-macos
deploy/docker/Dockerfile-build-ubuntu
deploy/linux/appimagecraft.yml
deploy/vagrant/.vagrantconfig.yml
docs/en/qgc-dev-guide/getting_started/index.md
tools/setup/install-qt-debian.sh
translations/qgc-lupdate.sh

Support Qt 6.8.3

---

src/Gimbal/CMakeLists.txt
src/Gimbal/Gimbal.cc
src/Gimbal/Gimbal.h
src/Gimbal/GimbalController.cc
src/Gimbal/GimbalController.h
src/Vehicle/Vehicle.cc

Gimbal: Separate Gimbal & GimbalController Files

---

CMakeLists.txt
test/ADSB/CMakeLists.txt
test/AnalyzeView/CMakeLists.txt
test/AutoPilotPlugins/CMakeLists.txt
test/CMakeLists.txt
test/Camera/CMakeLists.txt
test/Comms/CMakeLists.txt
test/FactSystem/CMakeLists.txt
test/FollowMe/CMakeLists.txt
test/GPS/CMakeLists.txt
test/MAVLink/CMakeLists.txt
test/MissionManager/CMakeLists.txt
test/QmlControls/CMakeLists.txt
test/Terrain/CMakeLists.txt
test/UI/CMakeLists.txt
test/UI/preferences/CMakeLists.txt
test/Utilities/Audio/CMakeLists.txt
test/Utilities/CMakeLists.txt
test/Utilities/Compression/CMakeLists.txt
test/Utilities/Geo/CMakeLists.txt
test/Vehicle/CMakeLists.txt
test/Vehicle/ComponentInformation/CMakeLists.txt
test/qgcunittest/CMakeLists.txt

CMake: Remove Extra Test Library

---

src/Camera/QGCCameraIO.cc
src/Camera/VehicleCameraControl.cc
src/FactSystem/Fact.cc
src/FactSystem/Fact.h
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/FactControls/FactPanelController.h
src/FactSystem/FactGroup.cc
src/FactSystem/FactGroup.h
src/FactSystem/FactMetaData.cc
src/FactSystem/FactMetaData.h
src/FactSystem/FactValueSliderListModel.cc
src/FactSystem/FactValueSliderListModel.h
src/FactSystem/ParameterManager.cc
src/FactSystem/ParameterManager.h
src/FactSystem/SettingsFact.cc
src/FactSystem/SettingsFact.h
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc
src/MAVLink/QGCMAVLink.cc
src/MAVLink/QGCMAVLink.h
src/MissionManager/SimpleMissionItem.cc
src/QmlControls/QGCMapPolyline.cc
src/Utilities/QGCLoggingCategory.cc

General Cleanup and Formatting

FactSystem: Cleanup

---

src/FactSystem/Fact.cc
src/FactSystem/FactControls/FactPanelController.cc
src/FactSystem/FactGroup.cc
src/FactSystem/FactMetaData.cc
src/FactSystem/FactValueSliderListModel.cc
src/FactSystem/ParameterManager.cc
src/FactSystem/SettingsFact.cc

Had enabled them for testing and forgot to disable them again

FactSystem: Disable Logging Again

---

src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h

Needed for custom firmware plugins to override

FirmwarePlugin: Switch Back Finals to Overrides

---

src/Camera/QGCCameraIO.cc
src/Camera/VehicleCameraControl.cc
src/Camera/VehicleCameraControl.h

I have been testing against a camera manager that I'm bringing up and ran into little issues requesting the messages and displaying the settings correctly initially. See commits for review and more detail.

A few Camera discovery fixes

---

src/QmlControls/InstrumentValueData.h
src/VideoManager/SubtitleWriter.cc
src/VideoManager/SubtitleWriter.h
src/VideoManager/VideoManager.cc

Use Video Size and scale font size

Video: Update Subtitles

---

src/Utilities/QGCLoggingCategory.cc
src/VideoManager/VideoManager.cc
src/VideoManager/VideoManager.h
src/VideoManager/VideoReceiver/GStreamer/GLVideoItemStub.h
src/VideoManager/VideoReceiver/GStreamer/GStreamer.cc
src/VideoManager/VideoReceiver/QtMultimedia/CMakeLists.txt
src/VideoManager/VideoReceiver/QtMultimedia/QtMultimediaReceiver.cc
src/VideoManager/VideoReceiver/QtMultimedia/QtMultimediaReceiver.h
src/VideoManager/VideoReceiver/QtMultimedia/UVCReceiver.cc
src/VideoManager/VideoReceiver/QtMultimedia/UVCReceiver.h
src/VideoManager/VideoReceiver/VideoReceiver.h

Some work to improve usage of QtMultimedia and UVC

VideoManager: QtMultimedia & UVC improvements

---

src/FlightDisplay/GuidedValueSlider.qml
src/FlightMap/FlightMap.qml
src/UI/MainRootWindow.qml

Various fixes for problems found during flight testing

---

src/Settings/FlyView.SettingsGroup.json
translations/qgc-json.ts
translations/qgc-lupdate-json.py
translations/qgc.ts

* Fix #11489
* Updated ts files to latest source

Json TS file generation: Support xml escaping

---

translations/qgc-json.ts
translations/qgc-lupdate-json.py
translations/qgc.ts

Fix json lupdate script to use correct names for short/long description keys

---

cmake/find-modules/FindGStreamer.cmake
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt

Fix MacOS Headers include
Add 1.26.0
Normalize Windows Env Variables
Fix Egl

CMake: FindGStreamer Fixes

---

src/Utilities/Compression/CMakeLists.txt

The develop branch has better cmake support

CMake: Update ZLib

---

src/main.cc

Linux: Add unistd Include

---

src/QtLocationPlugin/QGCMapEngine.h
src/QtLocationPlugin/QGCTileCacheWorker.cpp
src/QtLocationPlugin/QGCTileCacheWorker.h
src/QtLocationPlugin/QGeoMapReplyQGC.cpp
src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc

Cleanup QGCCacheWorker in prep for restructure

QtLocationPlugin: Cleanup TileCacheWorker

---

src/VideoManager/VideoManager.cc
src/VideoManager/VideoReceiver/GStreamer/GStreamer.cc
src/VideoManager/VideoReceiver/GStreamer/GStreamer.h

Normally you would just get the error about tee failing. This makes it more obvious to users what is happening

VideoManager: Verify GStreamer Plugins Initialized

---

src/QtLocationPlugin/Providers/GenericMapProvider.cpp
src/QtLocationPlugin/Providers/GenericMapProvider.h
src/QtLocationPlugin/QGCMapUrlEngine.cpp

Adds OpenStreetMap as a tile provider

QtLocationPlugin: Add OpenStreetMap Provider

---

src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc
src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.h
src/VideoManager/VideoReceiver/QtMultimedia/QtMultimediaReceiver.cc
src/VideoManager/VideoReceiver/QtMultimedia/QtMultimediaReceiver.h
src/VideoManager/VideoReceiver/VideoReceiver.h

Cleanup GstVideoReceiver for future work

Video: GStreamer VideoReceiver Cleanup

---

.github/ISSUE_TEMPLATE/bug_report.yml

Simplify issue report a bit and also force entry of QGC version

Force Entry of QGC Version in Issues

---

src/QGCApplication.cc
src/QGCApplication.h
src/VideoManager/VideoReceiver/GStreamer/GStreamer.cc
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt
src/main.cc

Replacement for #12735 with cleaned up commits

Fix mac gstreamer, update simple boot test to verify gstreamer plugins

---

cmake/find-modules/FindGStreamer.cmake
src/Settings/VideoSettings.cc

Adjust Video Settings Decoder list for new Decoders,

VideoSettings: Fix Decoder Filter List

---

src/AutoPilotPlugins/APM/APMFollowComponentSummary.qml
src/AutoPilotPlugins/APM/APMSensorsComponent.cc
src/FirmwarePlugin/APM/APMFirmwarePluginFactory.h
src/FirmwarePlugin/APM/APMParameterMetaData.cc
src/FirmwarePlugin/APM/APMParameterMetaData.h

Fix APM Compass Callibration

---

src/Vehicle/VehicleSetup/FirmwareUpgradeController.cc

This goes together with https://github.com/PX4/PX4-Autopilot/pull/24669.
FYI @vincentpoont2

Add KakuteH7-Wing board ID

---

src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt

This should hopefully get mac video at least working. It's still laggy which is a separate issues.

Hardwire MAC GST to not use find_package which does not work

---

src/Comms/UDPLink.cc

Fixes https://github.com/mavlink/qgroundcontrol/issues/12754

udplink: fix list contains check to prevent sending packets twice

---

src/VideoManager/VideoReceiver/GStreamer/gstqgc/gstqgcvideosinkbin.cc

Fix mac video lag

---

src/FollowMe/FollowMe.cc

Follow Me: Don't trust update interval from device

---

src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
src/AutoPilotPlugins/APM/APMSensorsComponentController.h

fix #12811
was due to a bad float casting
Also found an old typo from refreshing parameters, but doesn't look like it really mattered

APM: Fix Compass Callibration Progress Bar

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Update & Simplify Issue Templates

---

src/AutoPilotPlugins/APM/APMFollowComponentSummary.qml

Rows were overlaying each other right now

QML: Fix APMFollowComponentSummary Spacing

---

src/VideoManager/VideoManager.cc
src/VideoManager/VideoManager.h

VideoManager: Fix Starting Video

---

src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc

Allow Orbit for fixed wing

---

src/FlightMap/FlightMap.qml
src/QmlControls/DropPanel.qml

Fix DropPanel positioning

---

src/FlightMap/FlightMap.qml

Previous max of 15 was incorrect. Should be global max zoom of 20 as max.
@HTRamsey FYI

Plan: Don't let viewport adjustment go past maxZoomLevel

---

src/FirmwarePlugin/FirmwarePlugin.cc

FirmwarePlugin: Fix Loop Typo

---

src/QmlControls/ParameterEditor.qml

Related to discussion in #12881

Parameter Load: Better wording to indicate vehicle will not be updated immediately

---

.github/workflows/macos_release.yml
src/MissionManager/PlanManager.cc
src/Vehicle/StandardModes.cc
src/Vehicle/Vehicle.cc
src/VideoManager/VideoManager.cc
src/comm/MockLinkMissionItemHandler.cc

This was already working in the Daily Build, so - I think - it makes sense to enable this for v4.4.5.

[V4.4] Enable standard modes

---

src/VideoManager/VideoManager.cc

Noticed the order was wrong when testing QtMultimedia receiver

VideoManager: Fix Getting Widget for QtMultimedia

---

.gitattributes
.github/actions/qt-android/action.yml
android/build.gradle

Attempting to fix windows reading keystore

CI: Fix Android Windows Signing

---

src/Vehicle/VehicleSetup/FirmwareUpgradeController.cc

Add CUAV fmu-v6x board ID
PX4/PX4-Autopilot/pull/24733

Add CUAV fmu-v6x board ID

---

.github/actions/cache/action.yml
.github/workflows/android-linux-qt6.6.3.yml
.github/workflows/android-macos.yml
.github/workflows/android-windows.yml
CMakeLists.txt
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt

This time caching should actually be fixed

CMake: Improve Caching

---

.github/workflows/android_release.yml
.github/workflows/docs_deploy.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release.yml
.github/workflows/macos_release.yml
.github/workflows/windows_release.yml

Related to build failure on #12970

Switch to checkount@v4

---

src/FactSystem/FactMetaData.cc

Add support for Chinese separators on enumString/Values

---

src/UI/AppSettings/SettingsPagesModel.qml

Fix Console display

---

docs/en/qgc-user-guide/getting_started/download_and_install.md
docs/en/qgc-user-guide/troubleshooting/qgc_setup.md

Fix AppImage name

---

custom-example/CMakeLists.txt
src/CMakeLists.txt

@rubenp02 is this all I have to do?

CMake: Use NO_PLUGIN for CustomModule

---

cmake/CustomOptions.cmake
src/AnalyzeView/ExifParser.cc

* Previous code was failing on Mac
* Also previous code was dangerous with respect to random failures caused by full file header searching for byte sequences
* Also changed debug build to always build in unit test code
* Fix #12988

Rewrote Exif parser read code

---

test/MissionManager/CorridorScanComplexItemTest.cc
test/MissionManager/QGCMapPolygonTest.cc
test/MissionManager/QGCMapPolylineTest.cc

QGCMapPolylineTest/QGCMapPolygonTest: Update to handle new queued signals

---

src/QmlControls/QGCMapPolygon.cc
src/QmlControls/QGCMapPolygon.h
src/QmlControls/QGCMapPolyline.cc
src/QmlControls/QGCMapPolyline.h
test/MissionManager/QGCMapPolygonTest.cc
test/MissionManager/QGCMapPolylineTest.cc
test/MissionManager/QGCMapPolylineTest.h

This could create crashes on unit test runs

Fix poly line/gon test cleanup

---

src/AnalyzeView/MAVLinkSystem.cc
src/MissionManager/FixedWingLandingComplexItem.cc
src/MissionManager/MissionController.cc
src/MissionManager/StructureScanComplexItem.cc
src/MissionManager/TransectStyleComplexItem.cc
src/MissionManager/VTOLLandingComplexItem.cc
src/QmlControls/QGCMapPolygon.cc
src/QmlControls/QGCMapPolygon.h
src/QmlControls/QGCMapPolyline.cc
src/QmlControls/QGCMapPolyline.h
src/QmlControls/QmlObjectListModel.cc
src/QmlControls/QmlObjectListModel.h
test/MissionManager/LandingComplexItemTest.cc

Only outermost nested calls to begin/end pairs perform the actual reset
Replacement for #12991

Fix nesting of begin/endResetModel

---

docs/en/qgc-user-guide/setup_view/camera.md
docs/en/qgc-user-guide/setup_view/flight_modes_px4.md
docs/en/qgc-user-guide/setup_view/motors.md
docs/en/qgc-user-guide/setup_view/tuning_px4.md
src/AutoPilotPlugins/PX4/PX4TuningComponentCopterRate.qml

Docs: Fix PX4 Links

---

.github/workflows/linux.yml
CMakeLists.txt
cmake/CreateAppImage.cmake
cmake/Install.cmake

Replaces #12411
They finally updated the qt action for this
TODO: Only run unit tests on one arch

CI: Add Linux Arm64 Release

---

src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc

Related to discussion in #13023

GStreamer: Fix leak of static pad on shutdown

---

src/FlightMap/Widgets/HorizontalCompassAttitude.qml

* Select Horizontal Compass & Attitude
* Reboot and control will be offscreen

5.0: Fix positioning of control within containing RowLayout

---

src/FlightMap/Widgets/HorizontalCompassAttitude.qml

Fix positioning of control within containing RowLayout

---

src/AutoPilotPlugins/Common/RadioComponent.qml

* This makes it fit on small screens like Herelink
* Tried supporting dynamic single/double columns based on size but too complicated

Rework Aux channel config to be single column

---

src/AutoPilotPlugins/PX4/SensorsSetup.qml

Fixes compass rotation setting off by one on rotation param set

Use parameter metadata for rotations

---

src/QmlControls/MAVLinkChart.qml

Hack fix for crash on usb disconnect vehicle removal

---

src/QmlControls/MAVLinkChart.qml

Hack workaround for chart display without gstreamer compiled in

---

src/Android/AndroidSerial.cc

Change this output to debug from warning

Android: Don't warn when no serial devices detected

---

docs/en/qgc-user-guide/releases/daily_builds.md

* includes linux aarch64 download link
* clarifies Linux instructions
Closes #13112

docs: update downloads page

---

src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt

CMake: Fix GStreamer Shaders Alias

---

src/AnalyzeView/MAVLinkMessage.cc

Mavlink Inpector: Fix value updating on selected message

---

docs/en/qgc-user-guide/getting_started/download_and_install.md

Fixes issue with info box, and updates linux instructions

docs: update download instructions

---

src/AnalyzeView/MAVLinkConsoleController.cc

AnalyzeView: Fix Sending Commands (#13189)

---

src/MissionManager/MissionController.cc
src/QmlControls/PlanView.qml

Rovers don't require takeoff item in Plan

---

src/VideoManager/VideoManager.cc

VideoManager: Fix Crash on Vehicle Reboot

---

src/Viewer3D/CMakeLists.txt
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_1/DroneModel_BLDC_1.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_2/DroneModel_BLDC_2.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_3/DroneModel_BLDC_3.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_BLDC_4/DroneModel_BLDC_4.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_Base_Top_1/DroneModel_Base_Top_1.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_Base_bottom_1/DroneModel_Base_bottom_1.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_1/DroneModel_arm_1.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_2/DroneModel_arm_2.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_3/DroneModel_arm_3.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_arm_4/DroneModel_arm_4.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller22_1/DroneModel_propeller22_1.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller22_2/DroneModel_propeller22_2.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller2_2/DroneModel_propeller2_2.qml
src/Viewer3D/Viewer3DQml/Drones/Djif450/DroneModel_propeller2_7/DroneModel_propeller2_7.qml
src/Viewer3D/Viewer3DQml/Drones/DroneModelDjiF450.qml
src/Viewer3D/Viewer3DQml/Models3D/CameraLightModel.qml
src/Viewer3D/Viewer3DQml/Models3D/Line3D.qml
src/Viewer3D/Viewer3DQml/Models3D/Viewer3DModel.qml
src/Viewer3D/Viewer3DQml/Models3D/Viewer3DVehicleItems.qml
src/Viewer3D/Viewer3DQml/Models3D/Waypoint3DModel.qml
src/Viewer3D/Viewer3DQml/Viewer3D.qml
src/Viewer3D/Viewer3DQml/Viewer3DProgressBar.qml

Viewer3D: Fix Imports

---

src/Utilities/JsonHelper.cc

Utilities: Fix JsonHelper TranslateKeys

---

src/Camera/CameraMetaData.cc
src/Camera/CameraMetaData.h
src/Camera/MavlinkCameraControl.cc
src/Camera/MavlinkCameraControl.h
src/Camera/QGCCameraIO.cc
src/Camera/QGCCameraIO.h
src/Camera/QGCVideoStreamInfo.cc
src/Camera/QGCVideoStreamInfo.h
src/Camera/SimulatedCameraControl.cc
src/Camera/SimulatedCameraControl.h
src/Camera/VehicleCameraControl.cc
src/Camera/VehicleCameraControl.h
src/MAVLink/QGCMAVLink.h
src/VideoManager/VideoManager.cc
src/VideoManager/VideoManager.h

No logic change, just cleanup and moving some stuff
Start to deduplicate code between camera classes

Camera: Cleanup

---

.github/actions/upload/action.yml

Fix #13213.
Can you guys verify I got this right?

Cloudfront invalidation for daily/stable

---

src/RunGuard.cc
src/RunGuard.h

There is an issue using the old method on newer Qt versions.

Fix RunGuard For Qt6.6+

---

src/MissionManager/CameraSection.h
test/MissionManager/MissionControllerTest.cc

Wasn't waiting long enough for queued recalcs to flow through

Fix failing MissionController unit test

---

src/QmlControls/ParameterEditorController.cc

Fix crash when loading parameter which does not currently exist

---

.github/actions/upload/action.yml

Fix upload_aws
Fix cloudfront invalidation
Fix not doing aws upload on forks

CI: Fix Upload Action

---

src/MissionManager/CorridorScanComplexItem.cc
src/MissionManager/CorridorScanComplexItem.h

* Also cleaned entry point code to be clearer as to how it works
* Replacement for #12901

Fix entry point rotation when single transect

---

src/Comms/MAVLinkProtocol.cc

Fixes #13250
Uses a QSaveFile and sets file permissions
Also need to look into Android Permissions changes...

Comms: Fix TLOG Permissions

---

src/main.cc

Utilities: Fix RunGuard Lifetime

---

custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
src/Vehicle/StandardModes.cc

Cherry pick of #13357 to Stable

Fix bugs with flight mode names changing from Standared Modes

---

src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h

Remove hardcoded flight mode names

---

.github/workflows/macos.yml
cmake/install/CreateMacDMG.cmake
cmake/install/Install.cmake

Don't use FetchContent in install mode

CMake: Fix MacOS Create DMG

---

docs/en/qgc-user-guide/getting_started/download_and_install.md

Docs: Update supported OS

---

.github/release.yml
docs/en/qgc-dev-guide/contribute/pull_requests.md

Setup for automatic release notes

---

android/src/org/mavlink/qgroundcontrol/QGCUsbSerialManager.java
src/API/QGCCorePlugin.cc
src/QmlControls/BatteryIndicator.qml
src/QmlControls/MainStatusIndicator.qml
src/UI/AppSettings/MockLink.qml
src/UI/MainWindow.qml
src/UI/toolbar/GimbalIndicator.qml

You can see a lot of this on a small mobile screen like 10" where some things are just massive

Fly View: Various visual tweaks related to making this slightly smaller

---

src/Utilities/QGCLogging.cc
src/Utilities/QGCLoggingCategory.cc

Previous format was hard to scan through and read because of important part which is the actual log text being found at variable indent levels.
I also modified to only call out Warning as special
Before:
```
FirmwarePlugin.PX4ParameterMetaData::      0.140 - warning: Invalid max value, name: "VTQ_TELEM_IDS_1"  type: FactMetaData::valueTypeInt32  max: "4294967295"  error: "Value must be within 0 and 2147483647" (PX4ParameterMetaData::loadParameterFactMetaDataFile:279)
FirmwarePlugin.PX4ParameterMetaData::      0.140 - warning: Invalid value for bitmask, bit: 31 (PX4ParameterMetaData::loadParameterFactMetaDataFile:365)
FirmwarePlugin.PX4ParameterMetaData::      0.282 - warning: Invalid max value, name: "VTQ_TELEM_IDS_1"  type: FactMetaData::valueTypeInt32  max: "4294967295"  error: "Value …
```

More readable structure for log messages
