- CMakeLists.txt
- cmake/CompileOptions.cmake
- libs/CMakeLists.txt
- libs/libevents/CMakeLists.txt
- libs/qmlglsink/CMakeLists.txt
- libs/qmlglsink/windows/GL/glext.h
- qt5.natvis
- src/CMakeLists.txt
- src/Microhard/CMakeLists.txt
- src/MissionManager/CMakeLists.txt
- src/QmlControls/CMakeLists.txt
- src/Taisync/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
- src/VideoReceiver/CMakeLists.txt
- src/comm/CMakeLists.txt
- windows/QGroundControl.rc
- windows/resource.h
fix and clean up cmake gstreamer on windows
- move sources of Microhard and Taisync into separate library
- add recently added libevents code
- add resource file that contains the application icon on windows
- fix defines for debug/release builds
- QT_DEBUG was defined even though BUILD_TESTING was OFF,
which lead to the inclusion of test files which then failed to build
- qt5.natvis
- for better Qt variable visualization while debugging with MSVC (b7c1fb873c0cb7973200d1f7548c15e16473306f)
https://code.qt.io/cgit/qt-labs/vstools.git/tree/src/qtvstools/qt5.natvis.xml
- GL/glext.h (add missing OpenGL header on windows)
- https://stackoverflow.com/a/3939495/15862303
- https://www.khronos.org/registry/OpenGL/api/GL/glext.h
> Fix cmake gstreamer on windows

- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
The old behaviour adjusts the takeoff altitude set by the user with a slider to be higher than the minimum takeoff altitude as definied by the param MIS_TAKEOFF_ALT. This can be very confusing (and dangerous) as the slider to enter the altitude does not reflect that. It always goes from 0m to 100m.
For example: the param is set to 10m. Now the user can command a takeoff and set the slider to 1.5m. The drone will then takeoff and climb to 10m completely without warning.
I don't think it makes much sense to magically change the user input without feedback. Therefore, I removed the adjustment.
With this change the drone will just go to the altitude commanded by the slider.
> PX4FirmwarePlugin: ignore minimum takeoff altitude

- src/Vehicle/VehicleBatteryFactGroup.cc
Fix an error in the total battery voltage display after more than 10 batteries.
> Fix an error in the total battery voltage display 

- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
@DonLakeFlyer CrossTrack error is a nice-to-have item during auto-flight.
> Added xTrackError fact

- src/Vehicle/Vehicle.cc
This is an effort to bring in PR #8108 since that branch got stale, and CI wasn't reporting accurately anymore. As soon as CI does its thing, we should be good to go.
@LorenzMeier previously approved this PR on https://github.com/mavlink/qgroundcontrol/pull/8108#issuecomment-757521904
FYI @olliw42 @dagar @DonLakeFlyer @patrickelectric 
As discussed on https://discuss.px4.io/t/qgc-dev-call-june-11-2021/22545
> RESUBMIT #8108 - Only accept ATTITUDE messages from the vehicle

- src/FlightDisplay/VehicleWarnings.qml
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Just getting #9393 to stable.
We are still recommending 4.0 to our users due to this and a couple of other minor issues.
> (cherry-pick to stable) Vehicle: hide 'No GPS Lock' message if GPS is not present

- src/comm/LogReplayLink.cc
> initialize member variables of class LogReplayLink

- src/FlightMap/MapItems/PlanMapItems.qml
When I connected multiple vehicles, I found that the vehicle mission displayed on the screen was not updated properly. I don't know if it's related to this, but I found out that the bug was fixed after applying it. Please review my PR.
> Fix PlanMapItems typo error

- src/MissionManager/QGCMapPolygon.cc
- src/MissionManager/QGCMapPolygonTest.cc
- src/MissionManager/QGCMapPolygonTest.h
When splitting a polygon, the selected vertex needs to be updated. Otherwise the selected vertex won't always be the same one that the user selected prior to the split.
> When splitting a polygon, update the selected vertex index if necessary.

- src/qgcunittest/UnitTest.cc
For AirMap, this is PR related to BOSS-741.
Some signals, events, or objects are outliving the unit test which emits it. Any signals or events which do (including deleting objects marked with `deleteLater()`) may cause segmentation faults or use-after-free errors.
Each unit test shall be isolated and should not pollute later unit tests with incorrect, incomplete, invalid, data nor with signals or events pointed to objects that have already been destroyed. Every unit test should have consistent 
This isn't directly a problem with unit tests (per se) but rather with the design of some of the objects being tested.
Some unit tests leak objects with (wild) pointers pointing to stack- or heap-based objects whose lifetimes exist exclusively within the unit test. The leaked objects make attempts …
> `UnitTest::cleanup()` shall drain any remaining signals or events.

- src/QmlControls/ScreenToolsController.cc
Replacement for #9635 which got hosed up somehow. Tested to verify it works.
> USe correct font family names

- CMakeLists.txt
> cmake: Turn MICROHARD and TAISYNC disabled by default

- src/FlightMap/Widgets/PhotoVideoControl.qml
for some reason the QGCSlider that is assigned to the activesettings of _mavlinkcamera was setting the facts to its minimum value when that menu was instantiated. 
I realized this testing the camera protocol with a Workswell WirisPro  camera. This only seemed to affect some facts instantiated by a facttextfield. The fact that was being reset had the following .xml description:
parameter name="PIP_OPACITY" type="uint8" default="50" min="10" max="100"
but for instance there was another pretty similar that behaved correctly:
parameter name="PALETTE" type="uint8" default="0"
I have not dug deeper than this into all the fact generation from the .xml, maybe the bug is coming from there, but this commit fixes the behaviour.
> PhotoVideoControl.qml: fix Slider setting some facts to minimum:

- src/comm/USBBoardInfo.json
This PR adds the FMUV6X to the USB manifest. Solves https://github.com/mavlink/qgroundcontrol/issues/9738
> Add FMUV6X

- CMakeLists.txt
- src/CMakeLists.txt
- if gstreamer is not found but Microhard or Taisync is enabled
issue an error message and cancel CMake generation
- exclude the target_link_libraries call if Microhard or Taisync
is not enabled
- if Microhard or Taisync is enabled add compile definitions to
enable #defines in the source code, else there are build errors
> fixes #9754

- libs/qtandroidserialport/src/qserialportinfo_android.cpp
Delete the local JNI reference after use to fix possible crashes after some time periodically scanning ports on several android devices:
JNI ERROR (app bug): local reference table overflow (max=512)
https://stackoverflow.com/questions/26685491/jni-error-app-bug-local-reference-table-overflow-max-512
> Android: Serial port fix possible crash

- src/AutoPilotPlugins/Common/Images/YMinus.svg
- src/AutoPilotPlugins/Common/Images/YPlus.svg
Tri airframe config. have been updated in px4 user guide to say that direction of propellers is not taken into account in px4 software. The recommended airframe setup images have been updated too. See https://github.com/PX4/PX4-user_guide/issues/725
This PR updates the images in QGC to correspond with those in px4 user guide.
> update tri airframe images

- src/Settings/VideoSettings.cc
- src/ui/preferences/GeneralSettings.qml
Enables translation of video source setting by utilizing Fact mechanism of having a list of raw values for internal usage and a list of translated (cooked) values for display purposes. During the creation of VideoSettings group, two lists are fed to videoSource metadata. Then during operation raw values are used in code. Translation should be loaded from qt translation system.
> Enable translation of videoSource strings

- src/MissionManager/MissionController.cc
> Clear flight path segments on rebuild. Fixes crash on RTL in middle of items

- src/Vehicle/SubmarineFact.json
Use 'm' over 'meters'
Older version:
New version:
> Vehicle: SubmarineFact: Fix RangeFinder unit

- src/AutoPilotPlugins/APM/APMSafetyComponentSummarySub.qml
Parameter only exists if the battery monitor was configured (not None)
> APMSafetyComponentSummarySub: Add 'Disabled' text when battery monitor is not enabled

- src/AutoPilotPlugins/APM/APMSafetyComponentSummarySub.qml
The parameters will exist if the battery monitor is enabled
> APMSafetyComponentSummarySub: Do not warn if BATT_FS_LOW_ACT and BATT_LOW_* are not available

- src/ui/toolbar/Images/Battery.svg
Fix error Qt xml error: "Namespace prefix inkscape for connector-curvature on path is not defined"
> Images: Fix battery icon xml

- src/VideoReceiver/README.md
I couldn't get the example in the VideoReceiver README.md to work properly on Windows 10.  I found a command that worked for me and so that the next user doesn't lose 2 hours trying to solve the same problem, I'm adding it here.
> add working gstreamer udp sink example to README

- src/FirmwarePlugin/FirmwarePlugin.cc
I added the Workswell Wiris Security as an option for surveys (https://workswell-thermal-camera.com/drone-security-thermal-imaging-camera-night-vision-uav/)
This is the datasheet I got the values for the image dimensions and focal length 
[wws-datasheet-en-210126.pdf](https://github.com/mavlink/qgroundcontrol/files/6939979/wws-datasheet-en-210126.pdf)
The sensor height and width information came from Workswell customer support.
> Settings for the Workswell Wiris Security

- .travis.yml
There is a limited number of credits that can be used in Travis
> travis: Only run build for tags

- src/Camera/QGCCameraControl.cc
- src/QGCApplication.cc
- src/Vehicle/MAVLinkLogManager.cc
- src/VideoManager/SubtitleWriter.cc
It appears [this](https://github.com/mavlink/qgroundcontrol/commit/ce1551ca1a73b886844a708424dd9aa676082ab8) change had made the build process sensitive to enums deprecated going from Qt 5.12->5.15
It's a bit hard to prove, but there are some hints that only starting from C++14 one can deprecate enums:
- [deprecated attribute](https://en.cppreference.com/w/cpp/language/attributes/deprecated)
- deprecated enums are a ["new" thing in C++ (gcc 6+)](https://gcc.gnu.org/gcc-6/changes.html) - i know we way past it, but perhaps they are enabled C++14+ while dormant for when we use the C++11 dialect.
- removing the `CONFIG += c++17` directive **hides** the problem.
> Migrate from deprecated enums (Qt5.15)

- src/Vehicle/InitialConnectStateMachine.cc
- src/Vehicle/InitialConnectTest.cc
- src/Vehicle/InitialConnectTest.h
- src/Vehicle/RequestMessageTest.cc
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/comm/MockLink.cc
- src/comm/MockLink.h
AirMap's custom QGC has features which depend on vehicle characteristics; more than just type/class (fixed wing, copter, etc) we also need particular model information. Currently the user needs to manually select the vehicle type in order to correctly identify the compatible features. We desire to do that automatically (BOSS-751 is relevant for AirMap issues).
I understand mavlink's [`AUTOPILOT_VERSION`](https://mavlink.io/en/messages/common.html#AUTOPILOT_VERSION) allows vehicle firmware to report the `vendor_id` and `product_id` which helps to detect the model information. The information is sent by the vehicle [during the initial connect phase](https://github.com/mavlink/qgroundcontrol/blob/5aa27b5ba5dcd02cdf358bd48cdd95963e05accd/src/Vehicle/InitialConnectStateMachine.cc#L127-L171) …
> `Vehicle` shall make the board vendor and product id from the initial connection available

- src/VideoManager/VideoManager.cc
With this change we support receiving the full URI for a UDP video stream such as udp://127.0.0.1:5600. The previous case where only the port number is sent as "URI" is still handled.
Related to https://github.com/mavlink/qgroundcontrol/issues/9870.
> VideoManager: support receiving the stream URI

- src/main.cc
This catches the signals SIGINT and SIGTERM to shut down QGC.
I find this quite convenient as a user and developer. Any objections?
> main: allow quitting using Ctrl+C on Linux

- src/PositionManager/PositionManager.cpp
- src/PositionManager/PositionManager.h
We would like to implement "Return to Groundstation" feature - i.e.: mid-flight, the pilot presses a button, the mission is aborted and much like returning home, the vehicle returns to hover above the ground control station.
We see there is some "prior art", namely:
- `rtgsFlightMode` in [here](https://github.com/mavlink/qgroundcontrol/blob/master/src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc#L51), but, for some reason it's [not user-settable](https://github.com/mavlink/qgroundcontrol/blob/master/src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc#L88).
- a seemingly stale feature request [here](https://github.com/PX4/PX4-Autopilot/issues/9343) - [a comment](https://github.com/PX4/PX4-Autopilot/issues/9343#issuecomment-382905192) in that feature request makes us suspect `rtgsFlightMode` is not …
> Publish horizontal PositionManager::gcsPositionHorizontalAccuracy

- src/MissionManager/SurveyComplexItem.h
- src/MissionManager/VisualMissionItem.h
- src/PlanView/MissionItemEditor.qml
This fixes the not working editing of the center position of a survey pattern.
With this fix, the user can edit the center position of the survey pattern through the mission item list "Edit position..." mechanism.
This was tested on the stable_v4.1 branch. I cant build on the current master branch due to error #9864 .
**EDIT**: was able to build and test my patch on the master branch (== julled:fixSurveyPosEditMaster) so therefore its tested on current master.
> fix survey center position editing

- src/FlightDisplay/FlightDisplayViewVideo.qml
- src/FlightDisplay/FlyViewMap.qml
- src/FlightDisplay/GuidedActionsController.qml
- src/FlightMap/FlightMap.qml
- src/FlightMap/MapScale.qml
- src/MissionManager/QGCMapCircleVisuals.qml
- src/PlanView/MissionSettingsEditor.qml
- src/PlanView/PlanView.qml
- src/PlanView/SimpleItemMapVisual.qml
- src/QmlControls/FlightModeMenu.qml
- src/QmlControls/InstrumentValueLabel.qml
- src/QmlControls/MainWindowSavedState.qml
- src/QmlControls/QGCFlickableHorizontalIndicator.qml
- src/QmlControls/QGCFlickableVerticalIndicator.qml
- src/QmlControls/QGCPipOverlay.qml
- src/QmlControls/ScreenTools.qml
- src/ui/toolbar/MainToolBar.qml
Implicitly defined properties are deprecated in newer Qt versions.
This changes the syntax of the property functions to the new style.
> fix implicitly defined properties in Connections

- src/QGCLoggingCategory.cc
- src/QmlControls/QGCButton.qml
- src/comm/LinkManager.cc
* Fix button text centering
* Disable logging for deprecated onFoo silliness. We'll deal with all of these when we are forced to.
* Move zero-conf logging to verbose since it was spewing tones of output
> Qt version change cleanup

- src/QmlControls/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
files added in #9904
- AutotuneUI.qml was added twice to src/QmlControls/CMakeLists.txt
- Autotune.cpp was not added to src/Vehicle/CMakeLists.txt
> add missing source files to CMakeLists.txt

- src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
- src/AutoPilotPlugins/Common/RadioComponentController.cc
- src/AutoPilotPlugins/PX4/SensorsComponentController.cc
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
* This sends to radio calibration message to the vehicle for all firmwares
* For the stop calibration case it only shows errors for PX4 Firmwares. For other firmwares they may or may not have support so we can't pop an error.
* Related to https://github.com/ArduPilot/ardupilot/issues/8735
> Send radio cal start to Vehicle in all cases

- src/AnalyzeView/MavlinkConsoleController.cc
The SERIAL_CONSOLE message now includes a target_system and target_component which prevents serial messages being sent to the wrong vehicle in case there are multiple vehicles connected.
More background:
https://github.com/mavlink/mavlink/pull/1725
> MavlinkConsoleController: add target sysid/compid

- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/windows_release.yml
fixes https://github.com/mavlink/qgroundcontrol/issues/10021
As also discussed in https://github.com/mavlink/qgroundcontrol/issues/9946#issuecomment-969176516 CI doesn't drop the artifacts of the latest daily build to the original locations which are linked in the documentation here: https://docs.qgroundcontrol.com/master/en/releases/daily_builds.html
The new presumably erroneous URL is
`https://s3-us-west-2.amazonaws.com/qgroundcontrol/master/*`
while it used to be
`https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/*`
> Correct S3 upload URL with subfolder builds/

- src/FlightMap/Widgets/PhotoVideoControl.qml
The `_mavlinkCameraStorageSupported` currently tests that
_mavlinkCamera.storageStatus === QGCCameraControl.STORAGE_NOT_SUPPORTED
Which is the opposite of what the name of the property suggests.
Two uses of the property expect that it does what it says, while one use expects what it actually does.
This changes the test to make the property actually mean what it says and fixes the use that requires the opposite case.
> PhotoVideoControl.qml: fix storage usage logic

- qgroundcontrol.pro
- src/Joystick/CMakeLists.txt
- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
- src/Joystick/JoystickMavCommand.cc
- src/Joystick/JoystickMavCommand.h
- src/Joystick/JoystickMavCommands.json
In case when you would like to bind some MAV commands
to some joystick's buttons, you can now create a json file
which will be parsed at runtime.
It is usefull when you need to send a custom command from the joystick.
But this command is not supported by the firmware, or not relevant to be included to QGC.
Example:
Create a file JoystickMavCommands.json and place it with a binary:
"commands": [
{
"id":                   31010,
"name":                 "Enable Autonomy",
"param1":               1.0
}
]
After executing the QGC, you will be able to bind "Enable Autonomy" to a button,
by clicking to the button, MAV_CMD_USER_1 (31010) with param1 1.0 will be sent.
If there is no json file, nothing will happen.
> Joystick: Introduce custom MAV commands

- src/AutoPilotPlugins/APM/APMPowerComponent.qml
Revision is not necessary, it does not change the parameters
- Fix https://github.com/mavlink/qgroundcontrol/issues/10027
> APM: APMPowerComponent: Fix Blue Robotics power module name

- src/Joystick/Joystick.cc
It turns out this signal was not called anywhere.
Fixes #10043.
> Joystick: fix visualization

- src/Vehicle/Vehicle.cc
Fix display of cross track error -- was getting subtracted from altitude setpoint before display.
Addresses #10061
> fix xtrackerror display

- src/AnalyzeView/MavlinkConsoleController.cc
mavlink_msg_serial_control_pack_chan expects MAVLINK_MSG_SERIAL_CONTROL_FIELD_DATA_LEN bytes for 'data', but 'chuck' might be smaller than that.
Fixes https://github.com/mavlink/qgroundcontrol/issues/10059
> fix MavlinkConsoleController: avoid buffer out-of-bound access

- src/AutoPilotPlugins/APM/APMAirframeComponent.qml
- src/Vehicle/MultiVehicleManager.cc
If you flash an ArduCopter firmware over a non-previously setup ArduCopter board FRAME_CLASS will be initialized to 0 which in turn causes HEARTBEAT.type=0 which means that QGC does not know this is a copter class vehicle. This is a hack to work around that. Without it QGC doesn't show vehicle ui in this case which leads to a somewhat useless user experience.
Fix for : https://github.com/ArduPilot/ardupilot/issues/19446
> ArduCopter: Hack to set vehicle type when FRAME_CLASS is not set.

- src/Airmap/AirMapFlightPlanManager.cc
- src/Airmap/AirMapSharedState.cc
Fix crash in QGC and report configuration errors to the configuring pilot
For BOSS-899, https://github.com/mavlink/qgroundcontrol/issues/10035
- Fix crash in QGC:
Application key wasn't set and so the AirMap shared state object
hadn't been created.
- Report configuration errors to the configuring pilot:
When attempting to load the flight list, the application key and
pilot's username/password must be set.
> Fix crash in QGC and report configuration errors to the configuring pilot

- src/VehicleSetup/JoystickConfigButtons.qml
This exposes some of QGC's built-in functions to these users, specifically for control of video streams.
The options are filtered so that there are no repeated functions (there are both firmware and QGC implementation for many of the functions).
This is the final result:
Right now this only affects Sub.
> Allow vehicles that have built-in joystick support to also use QGC joystick functions.

- src/FirmwarePlugin/APM/APMParameterMetaData.cc
- src/FirmwarePlugin/APM/APMParameterMetaData.h
- src/QmlControls/ParameterEditorController.cc
The ReadOnly field is already in FactMetaData.h. This populates this field from ardupilot metadata and additionally ignores these parameters when loading a parameter file.
> Do not load Read-only parameters from files, load read-only metadata from ardupilot xmls

- src/AutoPilotPlugins/PX4/ActuatorComponent.qml
- src/Vehicle/Actuators/Actuators.cc
- src/Vehicle/Actuators/Actuators.h
- src/Vehicle/Actuators/GeometryImage.cc
- src/Vehicle/Actuators/GeometryImage.h
- src/Vehicle/Actuators/MotorAssignment.cc
- src/Vehicle/Actuators/MotorAssignment.h
- disable motor assignment button if geometry does not have motors
- increase motor spin timeout to 3s when assigning motors 
So that ESC's can initialize. Note that some are faster than others and 1s is enough in some cases.
I can bring this to stable as well.
> Actuators: minor updates

- src/FactSystem/Fact.cc
- src/FactSystem/FactControls/FactComboBox.qml
- src/Vehicle/Actuators/Actuators.cc
- src/Vehicle/Actuators/Actuators.h
- src/Vehicle/Actuators/Mixer.cc
- src/Vehicle/Actuators/Mixer.h
- remove the mixer functions that are unused with the current configration
(e.g. if 4 motors -> remove motors 5-N)
- use the specific labels
@hamishwillee @MaEtUgR  fyi
> Actuators: update output function parameter metadata

- qgroundcontrol.qrc
- src/AnalyzeView/LogDownloadPage.qml
- src/AutoPilotPlugins/APM/APMPowerComponent.qml
- src/AutoPilotPlugins/APM/APMSensorsComponent.qml
- src/AutoPilotPlugins/Common/RadioComponent.qml
- src/AutoPilotPlugins/PX4/AirframeComponent.qml
- src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml
- src/AutoPilotPlugins/PX4/PowerComponent.qml
- src/FactSystem/FactControls/FactTextField.qml
- src/FirstRunPromptDialogs/FirstRunPrompt.qml
- src/FlightMap/Widgets/PhotoVideoControl.qml
- src/PlanView/MissionSettingsEditor.qml
- src/PlanView/PlanView.qml
- src/PlanView/SimpleItemEditor.qml
- src/PlanView/TransectStyleComplexItemEditor.qml
- src/PlanView/TransectStyleComplexItemTerrainFollow.qml
- src/QGCApplication.cc
- src/QmlControls/AppMessages.qml
- src/QmlControls/AutotuneUI.qml
- src/QmlControls/HorizontalFactValueGrid.qml
- src/QmlControls/InstrumentValueEditDialog.qml
- src/QmlControls/ParameterDiffDialog.qml
- src/QmlControls/ParameterEditor.qml
- src/QmlControls/ParameterEditorDialog.qml
- src/QmlControls/QGCPopupDialog.qml
- src/QmlControls/QGCSimpleMessageDialog.qml
- src/QmlControls/QGroundControl/Controls/qmldir
- src/QtLocationPlugin/QMLControl/OfflineMap.qml
- src/VehicleSetup/FirmwareUpgrade.qml
- src/ui/MainRootWindow.qml
* This is the second phase of the work happening in this area
* Even more work done to make QGCPopupDialog instead of "sort of" work like a standard Qml Dialog it works exactly like it now
* Converted all usage of QGCViewMessage to either `mainWindow.showMessage` or direct `QGCSimpleMessageDialog` usage
* Converted a few more QGCViewDialog usages to the new QGCPopupDialog
* Added new support to `mainWindow.showMessage` to make it way easier to write code which needs to do something based on a simple yes/no style questions. It now has two additional optional parameters to specify buttons and accept function all within the showMessage function call. Example:
```
mainWindow.showMessage(
"title", 
"text", 
StandardButton.Yes | StandardButton.No,
function() { doAcceptStuff here } )
``` …
> More work on QGCPopupDialog, and QGCSimpleMessageDialog usage

- src/FlightMap/Widgets/PhotoVideoControl.qml
- src/QmlControls/QGCComboBox.qml
- src/ui/preferences/MavlinkSettings.qml
This PR fixes a couple things that don't look right.
1. PhotoVideoControl.qml
Outdoor mode before change
Outdoor mode after the change
2. QGCComboBox.qml.qml
Alignment before change
Alignment after change
3. MavlinkSettings.qml
Indoor mode before change
Indoor mode after the change
> Small ui tweaks

- src/ui/toolbar/GPSRTKIndicator.qml
check if QGroundControl.gpsRtk exists before checking if it is connected
> Fix gpsrtkindicator warning

- QGCPostLinkCommon.pri
- deploy/linux-fixup-rpaths.bash
- qgroundcontrol.pro
Time used for incremental build when changing a single .cc file:
- master: 26s
- timestamp check for library update: 9s
- timestamp check + gold linker: 5s
So overal build time reduces from 26s to 5s.
@keith-bennett-airmap
> Linux: incremental build speedup

- src/AutoPilotPlugins/APM/APMSensorsComponentSummary.qml
- src/FirmwarePlugin/APM/APMSensorParams.qml
The BARO1_DEVID parameter seems to have been added in "APM 4.1.0". In earlier versions of APM firmware, it causes a Missing Parameter error. This PR fixes this.
Please review.
> Added exceptions for features not supported by APM 4.1 earlier

- deploy/linux-fixup-rpaths.bash
```
Line 52:
if [ ! -e "$library.stamp" -o "$library" -nt "$library.stamp" ]; then
^-- [SC2166](https://github.com/koalaman/shellcheck/wiki/SC2166) (warning): Prefer [ p ] || [ q ] as [ p -o q ] is not well defined.
```
> linux-fixup-rpaths.bash: fix shellcheck warning

- src/AutoPilotPlugins/PX4/ActuatorComponent.qml
- src/Vehicle/Actuators/Actuators.cc
- src/Vehicle/Actuators/Mixer.cc
- src/Vehicle/Actuators/Mixer.h
- display geometry title if set
- show help url if set
- simplify axis configuration by adding a virtual dropdown if all 3 axis are set, which then sets the individual axis accordingly. Axes can still be configured individually by using Custom:
> Actuators: some smaller updates

- src/MissionManager/CorridorScanComplexItem.cc
**Problem solved by this PR:**
During the return path of a corridor scan no pictures were taken if the survey was configured NOT to take pictures during turnarounds (I believe this is not the default and likely the reason why this bug did not surface).
The reason for this is that when vertices are reversed in a transect, the entry and exit coordinate types were not swapped.
This meant that a leg would start with an exit type and end with an entry type. Since these types basically define camera triggering start and stop points, obviously this could not work.
This is how a corridor scan looked like prior to this fix. Notice that waypoint 12 which is at the exit starts camera triggering.
This is how a corridor scan looks like with this PR. Notice that waypoint 10 starts camera triggering for …
> CorridorScanComplexItem: Fixed camera triggering during return leg

- src/ADSB/ADSBVehicle.cc
- src/ADSB/ADSBVehicle.h
- src/ADSB/ADSBVehicleManager.cc
- src/ADSB/ADSBVehicleManager.h
- src/Vehicle/Vehicle.cc
- src/ui/preferences/GeneralSettings.qml
Hi.
I'm very thrilled that I can push my first PR to QGroundControl. I've spend whole weekend playing with the code. Now I've tidy it up and here it is :)
I have analysed lots of ADSB SBS-1 messages from various sources and despite that protocol description states that Callsign should be present only in MSG type 1, it's also often present in MSG types 5 and 6. So I've included those types as well to increase chances to obtain Callsign ASAP.
I've decreased cleanup (expiry) time do 60s. Previous was 120s. The reasoning behind that is that maybe except for helicopters all aircrafts with ADSB are in constant move with speed expected to be more than 100km/h (small low flying planes). At this speed after 2 mins aircraft should to be further than 4km away (if it's a jet it will be over 30km …
> Fix #10143: ADSB SBS-1 messages parsing and displaying

- src/ui/MainRootWindow.qml
Centers the version text on the Select Tool popup which looks much cleaner
> Center Version on Select Tool popup

- src/AutoPilotPlugins/APM/APMPowerComponent.qml
Resolves TypeError: Cannot read property 'current' of null & TypeError: Cannot read property 'voltage' of null and a couple of other warnings produced during calculations.
> Fix APM Power Component warnings

- src/VehicleSetup/FirmwareUpgradeController.cc
adds the kakute h7 board id 
This should make sure QGC detects the board correctly and installs the proper firmware
cc @vincentpoont2
fixes https://github.com/PX4/PX4-Autopilot/issues/19432
> Hardware: Add support for Holybro Kakute H7

- src/Settings/App.SettingsGroup.json
If the system is non-Japanese, the language choice will be displayed as 日本人.
I change it to 日本語.
I don't see the point in #10249 PR.
#10249 is modifying definitions not used for translation.
> Settings: Set the language option name to 日本語

- src/MissionManager/MissionController.cc
- src/PlanView/TransectStyleComplexItemTerrainFollow.qml
This PR attempts to solve two bugs encountered:
1- The total mission distance in the Plan Toolbar Indicators was not being updated while planning the mission. A signal emission had been commented out in MissionController.cc preventing this value to be updated.
2- Terrain following selector was not opening any options. Again a component was commented out from TransectStyleComplexItemTerrainFollow.qml preventing the correct dialog to open.
> Plan view bug fixes

- src/QmlControls/QGCPipOverlay.qml
This PR solves a bug encountered while toggling from video enabled to disabled.
There is a bug when having the video enabled in fullState while the map is in pip state. If the video is disabled the map is being set to fullState but not to visible. Therefore the map was not being displayed properly, either by showing nothing or by showing the UVC video display if available in the device.
Steps to reproduce the bug:
1- Turn on any video source in "General Settings".
2- In the Fly View, click on the pipable to make the video big (fullState) and the map small (pipState).
3- Turn off video by selecting "video disable" in "General Settings".
4- Go back to "Fly view" to encounter a bug of the map not showing/UVC video being shown.
> Bug fix. Flightmap not properly displayed after video disable if video screen is main.

- src/comm/SerialLink.cc
QSerialPort::error signal is deprecated, use old signal slot syntax because there is both a signal and function named QSerialPort::error
> Fix seriallink error signal connection

- src/comm/USBBoardInfo.json
Add FMUv6C ProductID to QGC USBBoardInfo.Json, so QGC can recognize the board and Holybro can load FW onto QGC offline.
FMUv6C ProductID was created here.
https://github.com/PX4/PX4-Autopilot/blob/b406c86a9caa3f35a0becf245ee6fc4ba673760e/boards/px4/fmu-v6c/nuttx-config/bootloader/defconfig#L33
> Add New Holybro ProductID to QGC USBBoardInfo.Json.

- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
For some commands we don't care about response as much as we care about sending them regularly.
This test avoids commands not being sent due to an ACK not being received yet.
CMD_DO_MOTOR_TEST in ardusub is a case where we need a constant stream of commands so it don't time out.
> Vehicle: create '_commandCanBeDuplicated()', use for MOTOR_TEST

- src/AutoPilotPlugins/APM/APMPowerComponent.qml
This is required because it uses different pins for reading the voltage
and current. This code probably needs a refactor to deal with different boards
> APMPowerComponent.qml: add new entry for BR PM on Navigator

- src/VehicleSetup/FirmwareUpgradeController.cc
Add FMUv6C to FirmwareUpgradeController.cc so user can flash FW using QGC.
FMUv6C ProductID = 0x0038 (Decimal is 56) shown [here.](https://github.com/PX4/PX4-Autopilot/blob/63155b5b0189619276dedea9686d6011d6e05fd5/boards/px4/fmu-v6c/nuttx-config/nsh/defconfig#L50)
v6C was added to PX4 Jenkinsfile-compile [here.](https://github.com/PX4/PX4-Autopilot/blob/9d0e57230a032a537123866f6eb71a1827649921/.ci/Jenkinsfile-compile#L108)
> Add FMUv6C to FirmwareUpgradeController.cc

- src/comm/USBBoardInfo.json
We use the generic vendor id available on the bootloader, which is set to Auterion. We plan to change that to either Dronecode or Pixhawk, we realize it's not ideal, but it will have to do for now until we get a USB Vendor ID approved
cc @vincentpoont2 @davids5
> Update Pixhawk FMUv6C vendor id

- src/AnalyzeView/MavlinkConsoleController.cc
Do not include the null bytes.
> MavlinkConsoleController: set correct data size

- src/AutoPilotPlugins/APM/APMSafetyComponentSub.qml
> APMSafetyComponentSub: deal with missing params in case of improper power module setup

- src/FirmwarePlugin/APM/APMSensorParams.qml
This fixes issues of "missing parameters" for Ardupilot vehicles
> ApmSensorParams.qml: check if ins parameters exist

- src/Joystick/Joystick.cc
Joystick::setAxisFrequency and Joystick::setButtonFrequency has wrong boundary checks. Instead of boundary check value will set to maximum allowed value.
This was referenced in issues #10175
> Fix joystick set*Frequency boundary checks. #10175

- src/FlightDisplay/FlyViewMap.qml
This PR is designed to make the guided mode menu a little more beautiful and unified in style with QGC
Old style menu (Go to location and Orbit at location):
New style menu:
> Rework fly view map guided mode menu

- qgroundcontrol.qrc
- src/QmlControls/QGroundControl/Controls/qmldir
- src/ui/toolbar/CMakeLists.txt
- src/ui/toolbar/FlightModeMenuIndicator.qml
- src/ui/toolbar/MainStatusIndicator.qml
Add a flight mode menu indicator that matches the QGC style
Old menu style:
New menu style:
> Rework flight mode menu for toolbar

- src/QmlControls/HorizontalFactValueGrid.qml
This adds a limit to the number of columns and rows in the telemetry bar, otherwise it gets so big that the buttons go off screen. Also remove Note as the bug has been patched in 5.15.1
> limit telemetry bar size by screen size

- src/PlanView/PlanView.qml
- src/QmlControls/QmlObjectListModel.cc
This fixes a warning about property width of null not existing when all mission items are removed and fixes the QList insert method that produced an invalid index warning from being one index too high each insertion (#10122).
> Fix PlanView warnings

- src/FlightMap/FlightMap.qml
Due to the architecture of the [Map](https://doc.qt.io/qt-5/qml-qtlocation-map.html), it's advised to use the signal emitted for this [property](https://doc.qt.io/qt-5/qml-qtlocation-map.html#mapReady-prop) in place of [Component.onCompleted](https://doc.qt.io/qt-5/qml-qtqml-component.html#completed-signal), to make sure that everything behaves as expected.
> Use recommended mapReady signal

- src/AnalyzeView/VibrationPage.qml
- Vibration page bars were drawn white on background white, which is why they never shown any value
- Fixed the clip count display
- Added bar current value display
- Move indication line into the bar instead of crossing all bars
- Added additional indication line at value 30, similar to MissionPlanner view - https://ardupilot.org/copter/_images/vibration-realtime-mp.png
> Fix vibration page bar and count display

- src/QmlControls/HorizontalFactValueGrid.qml
The newMaxWidth is now the max between all values for a same column in the grid. The index was set to 0 instead of i, hence not checking for every content width of the column.
> HorizontalFactValueGrid: Fix the valuerepeater index

- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QGroundControlQmlGlobal.h
Based on commit d0008a5f307086227197bff1ba72e6ff1090eeab. See #9220.
Added if clauses so prolonged repeated changes don't prevent saves. Fixes the issue for me.
> Save map position using a timer to prevent FPS decrease (#10070)

- src/comm/LinkManager.cc
- src/comm/TCPLink.cc
- src/comm/TCPLink.h
Currently when adding a hostname in string form for tcp connection,
resolving to IP is done immediately, and in case of an error
the host is not stored and used default one instead.
Also the ip might be not known when adding the config, but hostname is known,
which also might be not resolvable at time when the config is being created.
Since hostName in QAbstractSocket::connectToHost
may be an IP address in string form (e.g., "43.195.83.32"),
or it may be a host name (e.g., "example.com").
QAbstractSocket will do a lookup only if required.
So suggesting to totally remove resolving of ip from TCPLink.
Resolving will be performed in QTcpSocket::connectToHost() when actual connection is requested.
> Don't resolve tcp host when adding a config

- src/Camera/QGCCameraControl.cc
- src/Camera/QGCCameraControl.h
- src/Camera/QGCCameraManager.cc
- src/Vehicle/FTPManager.cc
- src/Vehicle/FTPManager.h
This PR heavily reuses the MAVLink FTP capabilities already present in QGroundControl and allows to specify camera definition URLs in `CAMERA_INFORMATION` with the mftp prefix, like `mftp://[;comp=100]infos/camera_info.xml`.
Tested it against the MAVSDK camera manager example PR: https://github.com/mavlink/MAVSDK/pull/1655
TODO:
- re-use component ID from CAMERA_INFORMATION as default for the ftp communication, as this would allow URLs like `mftp://infos/camera_info.xml`
- test / handle communication aborts properly
> QGCCameraControl: allow to read camera information xml via ftp

- src/PositionManager/PositionManager.cpp
"QNmeaPositionInfoSource supports reporting the accuracy of the
horizontal and vertical position. To enable position accuracy reporting
an estimate of the User Equivalent Range Error associated with the NMEA
source must be set with setUserEquivalentRangeError."
Source: https://doc.qt.io/qt-6/qnmeapositioninfosource.html#details
Commit 2a9ecabad86f37ccfcf8de9d0d5853238678ab4c introduced new behaviour
that broke use of external GPS. This change fixes the problem reported
in https://github.com/mavlink/qgroundcontrol/issues/10271.
> PositionManager: set UERE to enable position accuracy reporting

- src/VideoReceiver/gstqgcvideosinkbin.c
Solves #10188 by explicitly casting to `void *`.
> perform explicit void * cast

- libs/libevents/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
This PR fix linking libevents_health_and_arming_checks issue for Vehicle library
> Fix cmake build after add libevents_health_and_arming_checks

- src/VideoReceiver/gstqgcvideosinkbin.c
I found out that video streaming stopped working after this commit 3f479fc8410d3422dc4e27208b17eebcdb0bd617.
The resulting errors are below:
(QGroundControl:238965): GLib-GObject-WARNING **: 15:02:27.061: invalid uninstantiatable type '<unknown>' in cast to 'GstBin'
(QGroundControl:238965): GStreamer-CRITICAL **: 15:02:27.061: gst_bin_add_many: assertion 'GST_IS_BIN (bin)' failed
(QGroundControl:238965): GLib-GObject-WARNING **: 15:02:27.064: invalid uninstantiatable type '<unknown>' in cast to 'GstElement'
(QGroundControl:238965): GStreamer-CRITICAL **: 15:02:27.064: gst_element_add_pad: assertion 'GST_IS_ELEMENT (element)' failed
(QGroundControl:238965): GLib-GObject-CRITICAL **: 15:02:27.064: g_object_set: assertion 'G_IS_OBJECT (object)' failed
VideoReceiverLog: Unable to find sink …
> Fix GInstanceInitFunc for register GtypeIfo

- src/Settings/VideoSettings.cc
This PR activates the dropdown menu to select the video decoder priority for android and enables the "Force Software Decoder" option.
Usecase: On powerful devices (and/or low bitrates streams) this can improve latency.
I don't know the details, but avdec_h264 somehow can handles things different (does not need to wait for a whole frame!?) than a hardware decoder and so has less latency...
> VideoSettings: allow forcing software video decoder on android

- .github/workflows/android_release.yml
* install and use NDK r21e
* update QT install action from v2 to v3
Starting with NDK Version r24 llvm will not accept one-dash
long options anymore. This is bug QTBUG-104580
https://bugreports.qt.io/browse/QTBUG-104580
The r23c NDK version did not work due to issues with
stripping symbols. So I install and use r21e. QT 5.15.2 uses
gradle version 5.6.4 with the default android gradle plugin 3.6.0.
With gradle 6.9.2 and android gradle plugin 4.2.2 the 32bits
build worked. NDK r22b is not compatible with gstreamer 1.18 and
results in a failing 64bit build. Therefore r21e is required for
gstreamer support.
Closes: https://github.com/mavlink/qgroundcontrol/issues/10360
> fix Android CI for 32bit and 64bit builds (#10360)

- src/QmlControls/ParameterEditorController.cc
This lead to a segfault when importing params
> backport to 4.2: ParameterEditorController: fix incorrect cast

- .github/workflows/android_release.yml
- QGCPostLinkInstaller.pri
With commit 0b19305c36ab50c39b01 the android build is working again but the deployment fails.
When building on the master branch, the android keystore password is available. Building on a pullrequest or in a forked repository, the android keystore password is not available.
With the current build structure the "package" directory is created twice when the android keystore password is available resulting in a clash and build failure.
I changed the build structure such that correct builds are created for the two cases with and without the android keystore password.
> android CI: fix deployment of apk files

- src/AutoPilotPlugins/PX4/PX4TuningComponent.cc
- src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneAll.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneAttitude.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneRate.qml
- src/FirmwarePlugin/PX4/PX4Resources.qrc
**Problem Description**
Previously, PID tuning UI only worked for multicopter and VTOL vehicles and would not appear for Fixed wing vehicles.
When trying to tune a fixed wing vehicle using a mavlink inspector, it is not really possible since the `VEHICLE_ATTITUDE` displays the vehicle attitude in quaternions, while the `VEHICLE_ATTITUDE_SETPOINT` is in euler angles.
**Proposed Solution**
This commit adds a pid tuning UI for fixed wing vehicles for attitude and rate controllers by instantiating the qmls properly.
Thanks for @akistanov and @bkueng for the pointers!
@acfloria @tstastny FYI
**Additional Context**
- Fixes https://github.com/mavlink/qgroundcontrol/issues/10194
> Add PIDTuning UI for fixed wing vehicles

- deploy/docker/Dockerfile-build-linux
- deploy/docker/install-qt-linux.sh
`apt` complains loudly:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
We can use `apt-get` instead to avoid this warning.
> deploy/docker: use apt-get instead of apt

- android/AndroidManifest.xml
"android.hardware.usb.accessory" is listed in [1] and therefore should have `android:required="false"`.
[1]: https://chromeos.dev/en/android/manifest#unsupported-hardware-features
> android: don't require "android.hardware.usb.accessory"

- src/Settings/Video.SettingsGroup.json
- src/VideoManager/VideoManager.cc
In #9440 the video streaming failed for some cameras and the bunny example RTSP streaming movie. This worked in 4.0.6 and it did not work anymore in 4.1.0. The same unstable behaviour is observed in #10396.
The gstreamer rtsp source will switch to tcp when no data is received via udp after 5 seconds. The default timeout for the gstreamer video receiver is 2 seconds resulting in a permanent teardown and restart until eventually some data is received. As far as I understood the code 4.0.6 did not have a timeout which is in 4.1.0. I change the timeout for RTSP to 8 seconds and leave it at 2 seconds for the other streams. With 8 seconds timeout I can receive the bunny example without problems.
Closes: #9440
I tested this on MacOS with the changes from #10396 included and on Android.
> Video: increase timeout for RTSP video streaming (#9440)

- src/Vehicle/InitialConnectStateMachine.cc
The progressbar is updated with the actual progress for Mission-, Fence- and Rallypointdownload.
Without the patch the progressbar is only updated for each particular step when it is at 100% and the initial connect statemachine advances. The progress information is already available but it was not used. For slow connections the mission download with many mission items can take quite a while and the progressbar does not indicate the progress without this patch.
> View: Show correct progressbar also for Mission, Fence and Rally

- src/Vehicle/InitialConnectStateMachine.cc
The Ardupilot firmware doesn't seem to handle PROTOCOL_VERSION requests.
It seems to be using the capabilities field in the AUTOPILOT_VERSION message.
So, When connecting the Ardupilot firmware vehicle after #10436, QGC failed to upload rally points and geofences.
Please review this PR.
(I'm not good with English, so I used a translator.)
> Do not send PROTOCOL_VERSION request when using Ardupilot firmware

- src/VehicleSetup/FirmwareUpgradeController.cc
- src/comm/USBBoardInfo.json
This PR adds the ARKV6X PAB form factor flight controller. Starting it as a WIP PR to get CI to build a working version of QGC to test with.
I am currently using Auterions VID, which isn't ideal. Ideally we get a common Pixhawk VID.
https://arkelectron.com/product/arkv6x/
> Add ARKV6X

- src/comm/LinkManager.cc
- src/ui/preferences/LinkSettings.qml
- Fix UI update when a link is disconnected
- Clean up properly if a link fails to connect
We should probably get rid of all of the std::shared_ptr and use QSharedPointer instead. ~A PR for another day.~ I pushed a commit that replace them, let me know if I should revert it. Seems like using Qt smart pointers is probably better for a Qt project. I can go through and change it everywhere in the code base if we want to do that.
> fix: comm link bugs

- .github/workflows/macos_release.yml
- QGCPostLinkCommon.pri
- QGCPostLinkInstaller.pri
- src/VideoReceiver/README.md
- src/VideoReceiver/VideoReceiver.pri
The CI builds on master for MacOS do not work. This PR updates the CI for MacOS and 
* MacOS CI: Use official gstreamer package by picking patches from @patrickelectric from stable
* MacOS CI: Update gstreamer from 1.18.1 to 1.18.6 for MacOS
With GStreamer 1.18.6 the application does not crash anymore from the videofeed
`gst-launch-1.0 videotestsrc ! x264enc ! rtph264pay ! udpsink host=127.0.0.1 port=5600`
Closes: #10393 
Closes: #10408
Closes: #10435
> MacOS: update GStreamer 1.18.1 to 1.18.6 and fix CI (#10393 / #10408) 

- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
- src/MissionManager/MavCmdInfoCommon.json
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- Exposed the Gripper Mission item to the mission planning GUI
- Added Gripper Open/Close command to the Joysticks GUI
This is a QGC support for PX4's new package delivery feature: https://github.com/PX4/PX4-Autopilot/pull/19963
> Add Payload Delivery Gripper Mission item support

- src/comm/USBBoardInfo.json
Hi,
We developed a Flight Controller.
I would like to add USB Board info of our K1/R1 Flight Controller to the QGroundControl.
please check theses PR !
- PX4-user-guide: https://github.com/PX4/PX4-user_guide/pull/2034#event-7336074804
- PX4-Autopilot: https://github.com/PX4/PX4-Autopilot/pull/20176
- PX4-Bootloader: https://github.com/PX4/PX4-Bootloader/pull/219
Thanks
> Add The Peach K1/R1 USB Board info

- src/AutoPilotPlugins/APM/APMHeliComponent.qml
This PR fixes one of the parameters in the heli page for arducopter 4.2
> APM: Tradheli-fix heli setup page for version 4.2

- src/AnalyzeView/LogDownloadPage.qml
This passes the styleData.textColor property from the TableView to the Text items used to populate the rows to ensure the proper color of the text to match the alternating background colors of each row.
This fixes not being able to read the text on macOS where half of the rows were black text on almost black background.
Fixes: #10449
> LogDownloadPage.qml: fix TableView text color

- src/QmlControls/ParameterEditorController.cc
This adds regular expression support to the parameter search function. I added the isValid condition to prevent the contains function to spam the log with messages about invalid regular expressions.
User requested this feature here:
https://github.com/mavlink/qgroundcontrol/issues/10383
> ParameterEditorController: Add regular expressions to parameter search

- src/Camera/QGCCameraControl.cc
title says it
via mftp, compressed camera definition files with extensions .xml.lzma or .xml.xz can be downloaded, are decompressed, and the .xml stored and used. Works also with the caching.
tested using a STorM32 controller as mavlink camera.
:)
EDIT: here a log screenshot showing the thing in action
> QGCCameraControl: support ftp download of .xz .lzma compressed cam files

- src/FlightDisplay/FlyViewWidgetLayer.qml
- src/FlightDisplay/GuidedActionConfirm.qml
- src/FlightDisplay/TelemetryValuesBar.qml
Here is what the current Guided Confirmation slider looks like using Outdoor colors:
There are a number of problems with this:
* Since it is part of the Telemetry Bar when you move the mouse over it to slide the slider the telemetry bar edit tools show up
* When it shows up it causes the telemetry bar to move position
* On a small screen like a 10" tablet, stacking telemetry and slider begin to invade the center of the map which is tried to keep clear as much as possible
* The coloring of the slider in the outdoor colors makes it very hard to see in the sun outdoors
* The text explaining what the slider is about is pretty small once again making it hard to read outdoors which is kind of important for these sliders since they are critical functionality
Here is the new version:
This is …
> Moved Guided Confirm slider to top of window

- src/PositionManager/PositionManager.cpp
Backporting https://github.com/mavlink/qgroundcontrol/pull/10374 to fix external gps support in 4.2
> Stable: Backport external GPS fix

- src/VehicleSetup/FirmwareUpgrade.qml
Ardupilot firmware flash was broken. You couldn't pick the first item in the firmware list. Especially problematic if there was only one firmware option!
> Allow selection of first item in ardupilot firmware list

- src/CMakeLists.txt
> CMakeLists: Add missing compression on QGC link

- src/Camera/QGCCameraControl.cc
- src/FactSystem/ParameterManager.cc
- src/Vehicle/ComponentInformationManager.cc
- src/Vehicle/FTPManager.cc
- src/Vehicle/FTPManager.h
- src/Vehicle/FTPManagerTest.cc
this PR allows to specify a default compId in MAVFtp downloads, which can be different from MAV_COMP_ID_AUTOPILOT1. 
As before, if the uri includes a [;comp=xxx], the compId used in the ftp is ovberrited to be that specified in the uri. However, if the uri does not contain a compId specifier, it is in general not approriate to assume MAV_COMP_ID_AUTOPILOT1. For instance, if it is a camera.
The PR corrects the behavior for the camera's. It leaves the behaviour unchanged for the ftp downloads in the ParameterManager and componentInformationManager.
The PR has a tiny second change, namely lines https://github.com/mavlink/qgroundcontrol/pull/10488/files#diff-3c77d06c121d54cdd5191ae158a04af0095c441da288069469a948a48abdfaaeR174-R175.  The additional check for sysid should make sense.
Tested …
> MAVFtp: Allow proper compId as default

- src/FlightDisplay/FlightDisplayViewUVC.qml
- src/VideoManager/VideoManager.cc
- src/VideoManager/VideoManager.h
- src/VideoReceiver/GstVideoReceiver.cc
- src/ui/preferences/GeneralSettings.qml
This fixes issues covered in Bug report #10348
That is 
* playing video even though source is switched to `Video stream disabled`
* displaying video preview window even though source is switched to `Video stream disabled`
* utilizing UVC and GStreamer even though source is switched to `Video stream disabled`
> Refactor and fix Video manager issues #10348

- translations/qgc_source_zh_CN.ts
Fixes translation issue reported in:
https://github.com/mavlink/qgroundcontrol/issues/10329
Is this the right place to fix this? I only have a rough idea of the translation workflow.
> translation: Fix translation of Item #%1

- .github/workflows/linux_debug.yml
"Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16:
GabrielBB/xvfb-action@v1"
Replaces the obsolete action as suggested by @alisonatwork in
https://github.com/GabrielBB/xvfb-action/issues/30#issuecomment-1335389183
> Github actions: Fix deprecation warning for node12

- src/FactSystem/ParameterManagerTest.cc
Building on Windows in QtCreator results in a warning treated as an error due to initializing a float with a double. This just changes the value to a float to fix the warning.
> initialize float with float value

- README.md
We use github actions for CI now. The travis and appveyor badges are obsolete.
Do people use gitter?
> README: Remove obsolete badges

- src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
Two ZIGZAGs showed up in the flight mode list.
I set it to one.
> APM: Change the ZIGZAG in the flight mode list to one

- src/uas/UASMessageHandler.cc
Messages are displayed in HTML format.
ArduPilot uses "<" for IMU heater temperature notification.
The ArduPilot does not display anything below this symbol.
Converts a plain text string to an HTML string with HTML metacharacters <, >, &, and " replaced by HTML entities.
AFTER
BEFORE
> uas: Converts a plain text string to an HTML string replaced by HTML entities

- src/FlightDisplay/FlyViewVideo.qml
People wants to usue fullscreen without some text on the mididle of the screen,
10 seconds is enough to get the message.
Fix #10334 
> src: FlyViewVideo: Remove Double-click text after 10 seconds

- src/VehicleSetup/FirmwareUpgradeController.cc
Add Kakute H7 v2 & Kakute H7 Mini Board ID to QGC FirmwareUpgradeController.cc
> Add Kakute H7 v2 & Kakute H7 Mini Board ID to QGC

- .github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20230109.1 have added Android SDK Platform android-33-ext4. Something, possible the gradle version bundled with qt does not parse this correctly, and sets androidCompileSdkVersion in android-build/gradle.properties to "ext4" instead of expected "33". This commit is a quick fix to the problem, so the build will revert to android-33 wich was used before 20230109.1.
The documentation for the added package in the image version can be found here:
https://github.com/actions/runner-images/pull/6895
> Fix failing android workflow by removing android-33-ext4 from build image

- src/VehicleSetup/FirmwareUpgradeController.cc
- src/comm/USBBoardInfo.json
This is according to https://github.com/PX4/PX4-Bootloader/blob/main/board_types.txt
FYI @bugobliterator
> FirmwareUpgrade: add CubeOrange+

- src/AnalyzeView/AnalyzeView.qml
- src/ui/MainRootWindow.qml
Do this:
* Analyze View
* Mavlink Inspector
* Pop it out to a window
* Back from Analyze View
* Open Vehicle Setup
* You'll see that that mavlink inspector stops showing values
This was caused by the fact that the popout window was created in the context of the Analyze VIew. When that view went away all it's child objects are killed as well. Changed to create analyze popouts in the context of the main ui window.
> Fix Analyze Page popup ownership

- .github/workflows/linux_debug.yml
All Git Hub Workflow Action Linux Debug unit test runs suddenly started failing. This pull fixes that.
@bpmooch @booo FYI: Here are some details on how I figured this out. Which will hopefully help you with maintenance.
* So only Linux Debug was failing which you can see here: https://github.com/mavlink/qgroundcontrol/actions/workflows/linux_debug.yml
* If you scroll down through that display you see the it start failing between two runs of the same pull! And the pull is a one liner change that has no affect on unit tests at all. All of which is odd.
* It fails with this error:
```
Run xvfb-run -a ./staging/qgroundcontrol-start.sh --unittest
[18](https://github.com/mavlink/qgroundcontrol/actions/runs/4217407205/jobs/7321343057#step:15:19)
qt.qpa.plugin: Could not load the Qt platform …
```
> Fix unit test running

- src/Vehicle/MAVLinkLogManager.cc
- src/Vehicle/Vehicle.cc
asprintf is a static method and does not modify the calling object. This fix assigns the returned QString to the calling object.
Fixes issue #10450
> Fix use of QString::QString.asprintf()

- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
The whole point of COMMAND_INTs is that they have better resolution for coordinates leveraging int32 for degrees*10^7. This resolution is lost if we use float while handling the data instead of double.
> Vehicle: use double precision for COMMAND_INT

- src/FactSystem/FactMetaData.cc
- src/comm/USBBoardInfo.json
Fix #9781
When fact metadata was loaded from json if decimalPlaces was not specified it was defaulting to 0 instead of unknown. Unknown in turn defaults to 3 decimal places.
> FactMetaData: Fix default for decimal places

- src/Camera/QGCCameraManager.cc
- src/FlightMap/Widgets/PhotoVideoControl.qml
There was a bug in photovideocontrol.qml, on the trigger picture widget. It was only checking for video capabilities of the camera. So, if a camera responded with only picture capabilities, but not video recording capabilities, the widget would not allow to trigger simple pictures. 
This fix was confirmed to be working for Phaseone payloads, which are exactly this scenario, photo triggering but not video recording.
The other commit is to increase the amount of camera info requests ( used to be 3 ) to 10. Apparently this is very prone to fail in low bandwidth connections, because it is usually requested at the same time as parameter download, and it fails a lot. I think it would be nice to increase the request attempts to 10, but if you guys consider this is non optimal I can remove that …
> Mavlink camera bug and increase request for camera information

- src/QmlControls/QGCFlickable.qml
* Fix for #10574
* This will affect everywhere which uses the QGCFlickable base control. This is the majority of everywhere but may be mission in some places. If fast scrolling is seen in specific spot it needs to changes to use QGCFlickable instead of Flickable.
> Lower scroll speed

- src/Joystick/Joystick.cc
Releasing a hat button did not lead to _executeButtonAction being called with BUTTON_UP. This adds the hat buttons to lastBbuttonValues, such that the button up transitions for hat buttons are recorded.
> Joystick: Enable button up signal for hat buttons

- src/QtLocationPlugin/QGCMapUrlEngine.cpp
The `_providersTable["Google Labels"]` has been constructed with `GoogleTerrainMapProvider` class as wrongly. It have to construct with `GoogleLabelsMapProvider` class.
> Update QGCMapUrlEngine for wrong new() constructor

- src/FirmwarePlugin/APM/APMSensorParams.qml
`insIdParamsAvailable` -> `ins1IdParamAvailable`
> Fix incorrect property name in APMSensorParams.qml

- src/MissionManager/MavCmdInfoCommon.json
I find myself changing this every time. In almost all scenarios I've been flying, I prefer to change heading to absolute direction, rather than relative (because relative will accumulate any heading error, especially if the command is executed while turning.)
The absolute heading is the most used/typical way of using this mission item.
> Missionitem: Set condition_yaw default to absolute heading

- .github/workflows/windows_release.yml
Used to download files in windows workflow. Update from v1 to v1.3.0 to remove warnings about deprecated set-output command.
> Github actions: update actions-download-file version

- .github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20230313.1 have added Android SDK Platform android-33-ext5. Something, possible the gradle version bundled with qt does not parse this correctly, and sets androidCompileSdkVersion in android-build/gradle.properties to "ext5" instead of expected "33". This commit is a quick fix to the problem, so the build will revert to android-33 which was used before 20230109.1.
This fix was previously added for android-33-ext4 in image 20230109.1 in #10550.
The documentation for the added package in the image version can be found here:
https://github.com/actions/runner-images/pull/7278
Note: Currently 20230313.1 is in progress of being rolled out, making which builds that failes or not pseudo-random.
> Fix failing android workflow by removing android-33-ext5 from build image

- .github/workflows/android_32_release.yml
- .github/workflows/android_64_release.yml
Github workflow image ubuntu-20.04 version 20230313.1 have added Android SDK Platform android-33-ext5. Something, possible the gradle version bundled with qt does not parse this correctly, and sets androidCompileSdkVersion in android-build/gradle.properties to "ext5" instead of expected "33". This commit is a quick fix to the problem, so the build will revert to android-33 which was used before 20230109.1.
This fix was previously added for android-33-ext4 in image 20230109.1 in commit 6f636e7891fb9e204e4c6983eb2724e4d39c4aff.
> Github actions: Remove android-33-ext5 from build image

- qgroundcontrol.pro
- src/FlightDisplay/GuidedActionList.qml
- src/FlightDisplay/GuidedActionsController.qml
- src/QGCApplication.cc
- src/QmlControls/CustomAction.h
- src/QmlControls/CustomActionManager.cc
- src/QmlControls/CustomActionManager.h
- src/QmlControls/CustomActions.json
- src/Settings/AppSettings.cc
- src/Settings/AppSettings.h
- src/Settings/FlyView.SettingsGroup.json
- src/Settings/FlyViewSettings.cc
- src/Settings/FlyViewSettings.h
- src/ui/preferences/GeneralSettings.qml
This PR adds user-customisable action buttons to the Fly View. The buttons are configurable via a user-selected JSON file, and when clicked, will send a MAVLink command to the active vehicle.
The use case for this is when operating a vehicle with capabilities that do not have built-in controls in QGC, such as vehicles with landing gear.
There are two new Fly View settings added:
1. a setting to enable the Custom Actions; and
2. a setting to provide the JSON file used to define the Custom Actions.
When enabled in the Settings, and with an active vehicle connected, the Custom Actions look like the following:
The Custom Actions button will be visible but will be disabled if either:
1. the JSON file is invalid (i.e. is malformed or doesn't contain any action definitions); or
3. there is no …
> Add custom actions to Fly View

- src/Vehicle/RemoteIDManager.cc
we were using the geopositioninfo.isValid() in order to discard GPS and send lat/long/alt 0, but this function returns true even if latest GPS refresh was long time ago, so now instead we are using _gcsGPSGood, which takes into account the 5 seconds timeout as well.
This fixes the issue where unplugging GPS would still show "gps good" because QGC backend would take just the latest good GPS position, so as long as we had good GPS position at some point this was always true. Now after the 5 seconds timeout, if we don't have further "fresher" GPS updates, this flag will evaluate to false, and thus it will work correctly.
> RemoteIDManager: Fix GPS bad not being detected:

- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
This addresses issue #10544. 
When there are multiple vehicles, and you select a vehicle, the joystick should switch over to the newly active vehicle, and _only_ the active vehicle (so that joystick inputs are not sent to a vehicle you do not intend to control). 
In this PR, we achieve this by handling the `MultiVehicleManager::activeVehicleAvailableChanged` and `MultiVehicleManager::activeVehicleChanged` signals and invoking `setJoystickEnabled()` appropriately.
> Joystick input should switch to the active vehicle when the active vehicle changes

- src/QmlControls/CustomActionManager.cc
In #10563, @DonLakeFlyer [wrote](https://github.com/mavlink/qgroundcontrol/issues/10563#issuecomment-1483129619):
> @sypaq-nexton So I just pulled latest master and built/run. I get this error:
> ```
> Custom Actions Internal Error:  "Unable to open file: '', error: No file name specified"
> ```
> 
> If no custom action is set it should log an error. Can you fix this?
This PR addresses the above with updates to the `CustomActionManager` to:
* Use the `GuidedActionsControllerLog` for logging; and 
* Only load JSON in the constructor if we have a path defined.
> Improve warnings for CustomActionManager

- deploy/org.mavlink.qgroundcontrol.metainfo.xml
This adds the tag `content_rating` to the `metainfo.xml` using the interactive form at https://odrs.gnome.org/oars.
The `metadata_license` states `GPL-3.0 AND Apache-2.0`. I assume this only applies to the project and not the metadata, i.e. this `metainfo.xml` itself. Usually, these metadata files use one of the "Creative Commons" licences. I propose to use the "CC0-1.0".
> add content_rating to metainfo and fix metadata_license

- src/ui/toolbar/MessageIndicator.qml
Requested by user here:
https://github.com/mavlink/qgroundcontrol/issues/4503
I'm not sure about the `SelectionColor` and `SelectedTextColor` values.
> MessageIndicator: Enable copy/paste of messages

- src/PlanView/PlanToolBarIndicators.qml
The current implementation displays two different distances by the same name. One of the distances is actually the distance to the privous waypoint. For the user it is "hard" to tell which one is which. I try to resolve this with a more descriptive label for the distance to the privous waypoint.
An alternative is maybe to rename the other distance to total distance or total mission distance.
> PlanToolBarIndicators: Use more descriptive label for distance to WP

- src/comm/USBBoardInfo.json
Updating the firmware on the FlightCore V2 would not work on QGC due to the board not being included on USBBoardInfo.json. After I put the board on USBBoardInfo.json, I could update the firmware like normal. Without its inclusion, commands to the board would time out during update.
> Fixed ModalAi Flight Core V2 Firmware Update Not Working On QGC

- .gitmodules
OpenSSL for android wasn't updated for 3 years. Fetching elevation data in Android wasn't working, it reported a TLS error. Updating to latest openSSL solves the problem.
By the way, openssl for android submodule is pointing to a branch in Auterion repo. That Auterion repo doesn't have any modification at all in this front. Would it make sense to make it point to the original openssl repo Auterion repo is pointing to?
Thank you very much to Arace UAS for reporting this issue!
> libs: OpenSSL update to 1.1.1l_1.0.2u

- CMakeLists.txt
- cmake/Git.cmake
- deploy/org.mavlink.qgroundcontrol.metainfo.xml.in
This adds a `release` tag to the `.metainfo.xml`.
According to the [documentation](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-contents-suggestions), this is only suggested. But it is required for Flathub and would allow using the upstream metainfo file without modifications.
> add release tag to metainfo file

- src/Vehicle/Vehicle.cc
This fixes the warning that I get with GCC 11.3:
```
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:34:
warning: ‘__builtin_strncpy’ writing 50 bytes into a region of size 24 overflows the destination [-Wstringop-overflow=]
95 |   return __builtin___strncpy_chk (__dest, __src, __len,
|                                  ^
/usr/include/x86_64-linux-gnu/bits/string_fortified.h: In member function ‘_handleStatusText’:
../Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h:129:8: note: destination object ‘<anonymous>’ of size 24
129 | struct QTypedArrayData
|        ^
```
> Vehicle: fix odd warning in _handleStatusText

- deploy/windows/nullsoft_installer.nsi
The file was downloaded from
https://firmware.ardupilot.org/Tools/MissionPlanner/driver.msi on 2023-05-08.
This should fix flashing problems of Cube Orange and others on Windows.
Closes https://github.com/PX4/PX4-Autopilot/issues/17352.
> deploy: update driver.msi

- src/MissionManager/TransectStyleComplexItem.cc
Selecting terrain data on surverys was generating an empty survey if the polygon was on an area where QGC doesn't have terrain height info about.
This is because QGC was waiting on terrain info to build the path on such surveys, which is not needed at all, because terrain frame just specifies an altitude above terrain, and relies on the vehicle for being able to calculate that height, by terrain database or by altitude sensors, having terrain height information is not needed at all to generate this kind of surveys.
I think this is heritage of a few time ago where QGC didn't support terrain frame for missions, and it was supporting only what we call now AltitudeModeCalcAboveTerrain, so this comprobation was needed.
I double checked what happens on this situation selecting …
> TransectStyleComplexItem.cc: Fix bug generating empty surveys when no terrain data

- QGCExternalLibs.pri
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
While building for Mavlink common dialect `common`, `mavlink_rangefinder_t` and all supporting functions are undefined as it is defined for only `ardupilotmega` dialect.
Have added flags to check the same. This I faced when I tried building for the custom QGC build with default dialect as `common`
> Ardupilotmega flag added for Mavlink Dialect

- src/Vehicle/VehicleHygrometerFactGroup.cc
Hi, 
[Hygrometer](https://mavlink.io/en/messages/common.html#HYGROMETER_SENSOR) mavlink message uses (is defined) centi-Celsius-degrees units (C*100). But in QGC, the message is currently parasersed as if they were the basic grades of Celsius. 
This PR converts the value from the message to basic unit DegresCelsius.
> Fix parsering of hygrometer message

- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/Vehicle/VehicleFact.json
TimeToHome fact calculates the time in seconds till the UAV reaches the home position. We take the distance to home and divide it by the current ground speed to get the seconds till we arrive at the home point. I did not add any fancy logic to find out if we actually fly towards the home point or are in RTL so the value shows increasing seconds even if we fly away from the home point
> Add Vehicle fact timeToHome

- src/ui/preferences/RemoteIDSettings.qml
- src/ui/toolbar/RemoteIDIndicator.qml
All this remote id feature depends on a device being detected so it makes sense to not show the rest of the flags until a healthy connection has been detected. Now it looks like this until we have healthy connection with RID device ( arm status message received ):
It addresses the issues mentioned here #10654.
> Remote id fronted: hide all indicators if RID comms is not healthy:

- deploy/docker/install-qt-linux.sh
The command "aqt install" is deprecated and marked for removal. It has been replaced with "aqt install-qt".
> install-qt-linux.sh: Remove use of soon to be deprecated aqt install

- src/ui/MainRootWindow.qml
In the edge scenario where we set video view in full screen and for some reason QGC brings us to setup view ( if the vehicle has calibration/setup pending ) the toolbar would dissapear, thus not being able to get out of that state.
> MainRootWindow: fix bug toolbar dissapearing:

- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.h
- src/Vehicle/Vehicle.cc
ArduPilot has supported this command for 5.5 years now.  Probably time to start using it.  Copter 3.6.0 has it, 3.5.x does not.
Selecting a mode which can't be entered right now yields a message now:
> Use MAV_CMD_DO_SET_MODE to change modes on ArduPilot-base vehicles

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/ui/toolbar/RCRSSIIndicator.qml
There was a bug scaling rc rssi from rc_channels mavlink message where it was scaled to 0-100 from 0-255, and this was wrong because 255 is meant to be invalid, and AP uses 0-254 anyway. We must leave 255 as it is so the frontend can understand if we don't have data.
Also, in RCRSSIIndicator, we don't show the indicator anymore if data is not valid, there is no point in showing it when rssi is 255 ( not valid ).
This was causing the rc rssi icon to show on systems where no rc was available at all, which is confusing ( it was showing 100% ) and takes up space in the top toolbar with no reason.
This was only affecting Ardupilot as far as I know.
> APMFirmwarePlugin, RCRSSIIncidator: solve bug where no valid rssi would show indicator:

- src/FlightDisplay/FlyViewMap.qml
- src/FlightDisplay/GuidedActionsController.qml
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/ui/preferences/GeneralSettings.qml
This PR adds support for setting home clicking on map. It is shown as another action in the submenu when we click over the map with an active vehicle online. It needs slider confirmation as usual, with the following message:
As per mavlink specs, this command must use AMSL altitude, so we need to first query terrain altitude, and when received send the command.
Several checks have been implemented, one of them is a sanity check where the terrain altitude must be within a range (-500 - 10000 ) that should cover all places on Earth, in order to discard possible corrupted data, and in case terrain altitude is not available at the selected location a popup will appear indicating there are no terrain data for the specified location:
I also added vehicle logging that reports some messages …
> Master pr/support do set home

- src/QmlControls/ToolStrip.qml
When the toolbar height is smaller than the content height, the elements would protrude a bit, the margins of the flickable were not taken into account for its height ( note the left toolstrip ):
After this commit:
> ToolStrip.qml: Fix Flickable height, it was bigger than panel

- android.pri
- android/src/AndroidInterface.cc
- android/src/AndroidInterface.h
- android/src/org/mavlink/qgroundcontrol/QGCActivity.java
- src/Settings/App.SettingsGroup.json
- src/Settings/AppSettings.cc
- src/Settings/AppSettings.h
- src/api/QGCCorePlugin.cc
- src/ui/preferences/GeneralSettings.qml
* Add setting to General/Misc in the UI to save all application data to the SD card for android builds.
* If option is enabled and no SD card available or write protected user is notified about the problem and that internal storage instead will be used.
This was added to move forward the Herelink version. The current Herelink variant saves video to the SD card. Nice feature, but in reality it makes sense to allow for all data to be on the SD Card which is much easier to work with than the internal storage. Adding this upstream change then allows me to carry it over to the new Herelink version.
> Allow app data to save to sd card on android

- src/AutoPilotPlugins/PX4/PX4SimpleFlightModes.qml
This was introduced in
https://github.com/mavlink/qgroundcontrol/commit/d5dc4f1af17151d7e7f88372847bc12ac499ccb9, and the refactor didn't fix the case for RC_MAP_FLAPS case correctly
Fixes https://github.com/PX4/PX4-Autopilot/issues/21927
I haven't tested it, but with the built artifact it could be great if you could give it a test @benjinne
> [Bugfix] Fix Flight Mode Switch settings box not showing

- QGCCommon.pri
- QGCExternalLibs.pri
- android.pri
- android/AndroidManifest.xml
- qgroundcontrol.pro
QGC has build settings to disable serial port and bluetooth support. The android build was not correctly supporting these settings which respect to updating the AndroidManifest.xml correctly. This is now fixed.
This change was driven by fixing up upstream qgc for Herelink support in ways which require less upstream changes to get a Herelink build to work. In this specific case Herelink does not support usb (serial) or bluetooth.
> Android support for serial/bluetooth disabling

- src/FlightDisplay/TelemetryValuesBar.qml
A change was made a while back to the telemetry values bar to use hover instead of click to show the edit tools to unlock it. This works fine if you have a mouse. But on mobile it doesn't really work at all since there is no concept of "hover". I changed the code such that mobile goes back to the way it was before which is a click will enter edit mode. Non-mobile mouse stays with the same hover behavior.
> Telemetry Bar: Fix turning on edit for mobile

- QGCCommon.pri
- android.pri
- android/AndroidManifest.xml
- qgroundcontrol.pro
* DEFINES+=NO_SERIAL_LINK - to turn off serial support
* DEFINES+=QGC_DISABLE_BLUETOOTH - turn off bluetooth support
* CONFIG+=AndroidHomeApp - App is home app. This is new support
Note: NO_SERIAL_LINK and QGC_DISABLE_BLUETOOTH already existed in the build but were not supported (or correctly supported) in android builds.
Although this is generic support, it is drive by getting a clean Herelink custom build out.
> Android supports no serial/bluetooth build and home app

- src/PositionManager/PositionManager.cpp
- src/comm/LinkManager.cc
- src/comm/QGCSerialPortInfo.cc
While working on getting Remote ID working with Master QGC I encountered a few small problems in using an NMEA GPS.
I am using a Toughbook FZ-G2 running windows 10, which has an internal GPS module which presents as a NMEA stream on a COM port (COM5 in my case).
While I was able to select COM5 in the drop down, and I got a lat lon to show up in the Remote ID Page, it would never show altitude. In digging into the issue, I discovered what was happening.
The dropdown menu in the UI was pulling from LinkManager::serialPorts(), which was pulling from QSerialPortInfo::availablePorts(). However, in the LinkManager::_updateAutoConnectLinks(), where the NMEA port is passed to the position manager, it would iterate through a smaller list provided by QGCSerialPortInfo::availablePorts(), which is a …
> Fix a few issues with NMEA GPS for GCS position

- src/Vehicle/Vehicle.cc
This fixes a bug introduced in b62a533 which, when a joystick was disabled and uncalibrated, caused unbounded recursive calls to Joystick::startPolling. Discussion has been happening about this in #10758
@DonLakeFlyer
> Fix an unbounded loop in the joystick code

- src/AutoPilotPlugins/APM/CMakeLists.txt
- src/AutoPilotPlugins/CMakeLists.txt
This update modifies the CMakeLists.txt files in both the AutoPilotPlugins directory and within the APM subdirectory, adding APMRemoteSupportComponent to the list of components included in the project's build. This change is necessary to ensure that the new APMremoteSupportComponent is compiled when the project is built.
> Fix cmake build after adding APMRemoteSupportComponent

- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
- src/Vehicle/Vehicle.cc
- src/VehicleSetup/JoystickConfig.qml
- src/VehicleSetup/SetupView.qml
- src/api/QGCOptions.h
This reverts commit 48d1441493b3c193bbd2c5fc63c650bf2ae51e48.
This was for Herelink support. Isn't quite what is needed. I will do this a different way.
> Revert "Support custom builds with joysticks which are buttons only"

- src/QGCFileDownload.cc
- src/QGCFileDownload.h
- src/QtLocationPlugin/QGCMapTileSet.cpp
- src/Terrain/TerrainQuery.cc
- src/VehicleSetup/FirmwareUpgradeController.cc
- src/VehicleSetup/FirmwareUpgradeController.h
Some systems (like Ubuntu 22.04) only ship with OpenSSL 3.x, however Qt 5.15.2 links against OpenSSL 1.x.
This results in unresolved symbols for EVP_PKEY_base_id and SSL_get_peer_certificate.
To still get a connection we have to ignore certificate verification (connection is still encrypted but open to MITM attacks)
See https://bugreports.qt.io/browse/QTBUG-115146
It's not a great solution, but the best one I see given the situation.
Thanks to @julianoes for doing all the investigation & bug reporting.
> Handle openssl version mismatch

- src/PlanView/PlanView.qml
- src/PlanView/TerrainStatus.qml
- src/QmlControls/QGroundControlQmlGlobal.h
- src/QtLocationPlugin/ElevationMapProvider.cpp
- src/QtLocationPlugin/ElevationMapProvider.h
- src/QtLocationPlugin/QGCMapEngine.cpp
- src/QtLocationPlugin/QGCMapEngine.h
- src/QtLocationPlugin/QGCMapEngineData.h
- src/QtLocationPlugin/QGCMapTileSet.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.h
- src/QtLocationPlugin/QGCTileCacheWorker.cpp
- src/QtLocationPlugin/QMLControl/OfflineMap.qml
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
- src/Terrain/TerrainQuery.cc
- src/TerrainTile.cc
- src/TerrainTile.h
The Airmap terrain servers (and possibly other Airmap services) are shutting down. The docs  [https://developers.airmap.com/docs/elevation-api](https://developers.airmap.com/docs/elevation-api) are already down while the servers seem still to be running for the time being.
This PR replaces the `Airmap` query with an alternative provider, hosting the [Copernicus GLO-30](https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model) which was compiled and provided by `© Airbus Defence and Space GmbH` dataset. The Copernicus dataset has generally better global coverage and accuracy than the previous SRTM dataset. 
Added a small note in the bottom center of terrain plot:
| Airmap |
:-------------------------:
| Copernicus |
:-------------------------:
| Airmap | …
> feat: replace Airmap terrain data with Copernicus

- src/Joystick/Joystick.cc
- src/Joystick/JoystickManager.cc
- src/Joystick/JoystickManager.h
- src/Vehicle/Vehicle.cc
- src/VehicleSetup/JoystickConfig.qml
- src/VehicleSetup/JoystickConfigGeneral.qml
- src/VehicleSetup/SetupView.qml
- src/api/QGCOptions.h
This allows for two things:
* Joysticks which are buttons only, no sticks. In this case the various parts of joystick config which are associated with stick config are hidden:
* General page: 
* Requirement for calibration prior to setup
* RC modes hidden
* Stick monitor hidden
* Calibration/Advanced pages are hidden when buttons only. Note: Button repeat rate is on the Advanced page. We'll live without that for now.
* New plugin option: QGCOptions::allowJoystickSelection defaults to true. Settings to false will cause the General page of Joystick config to not be shown. This is meant to be used by custom builds which have a known fixed joystick setup that the user should not be allowed to change. The Herelink for example.
> Joysticks buttons only support, allow joystick selection override

- src/MissionManager/GeoFenceController.cc
- src/MissionManager/GeoFenceController.h
On PX4 the circular geofence around the home point is displayed by checking the parameter GF_MAX_HOR_DIST.
This PR adds equivalent functionality for APM by using the parameters "FENCE_RADIUS" "FENCE_ENABLE" and "FENCE_TYPE".
Tested with arducopter 4.3, arduplane, and px4 1.13, all seem to work fine.
I've been using a version of this in my own custom build for a while, but thought it would be useful for enough people to warrant a PR. Happy to rework it if anyone has any suggestions.
> implement use of apm circle geofence from parameters

- src/VehicleSetup/SetupView.qml
The Joystick config button is normally named "Joystick". If a custom build has disallowed joystick selection by the user and the joystick being used is buttons only then change the name of the config button to "Buttons" for better clarity.
> Joystick Config: Change button name when forced to buttons only

- src/FirmwarePlugin/FirmwarePlugin.cc
As the arming flag is set from the heartbeat received at 1Hz, we need to wait a bit longer than 1s.
The 1s timeout sometimes led to this error message when trying to start a mission: "Unable to start mission: Vehicle rejected arming."
Fixes https://github.com/PX4/PX4-Autopilot/issues/22042
> fix FirmwarePlugin: increase arming timeout to 1.5s

- .github/workflows/android_release.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/windows_release.yml
- src/Vehicle/EventHandler.cc
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/uas/UASMessageHandler.cc
- src/uas/UASMessageHandler.h
- src/ui/MainRootWindow.qml
- src/ui/toolbar/MessageIndicator.qml
And allows to use URL's & parameters in messages:
Fixes https://github.com/mavlink/qgroundcontrol/issues/10811
> Fix Richtext message display & html escaping for events

- src/Settings/VideoSettings.cc
otherwise videoManager won't restart the receiver and video won't work properly when configured for Herelink.
> VideoSettings: Flag Herelink streams as configured:

- qgroundcontrol.pro
- src/FirmwarePlugin/FirmwarePlugin.h
- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
- src/Vehicle/CMakeLists.txt
- src/Vehicle/InitialConnectStateMachine.cc
- src/Vehicle/InitialConnectStateMachine.h
- src/Vehicle/StandardModes.cc
- src/Vehicle/StandardModes.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
This brings the MAVLink standard modes protocol from https://github.com/mavlink/mavlink/pull/1750.
It allows the GCS to dynamically request the list of modes.
As the messages are in `development.xml`, they are disabled when doing a release build of QGC.
Implementation on the PX4 side: https://github.com/PX4/PX4-Autopilot/pull/20707
@hamishwillee fyi
> Mavlink standard modes protocol

- src/MissionManager/MavCmdInfoCommon.json
- src/MissionManager/MissionController.cc
So we can program missions with this command, it is meant to become the standard for managing gimbals according to mavlink gimbal manager protocol.
> MissionManager: Support for MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW

- src/FlightMap/Widgets/PhotoVideoControl.qml
I patched this little time ago in order to allow mavlink cameras that only support photo shooting, but the logic was wrong and it malfunctions for simple cameras. This commit should fix it.
> PhotoVideoControl.qml: Fix toggleShotting when no mavlink camera

- src/QtLocationPlugin/QGCMapUrlEngine.cpp
Optimize map provider iteration to prevent app crashes. Fixed application crash due to segmentation fault.
Changed from QHashIterator to using a constant iterator for iterating through the map providers in _providersTable. This change prevents application crashes during a map download session caused by the potential modification of an implicitly shared hash.
> Optimize map provider iteration to prevent app crashes. Fixed application crash due to segmentation fault.

- src/VideoReceiver/GStreamer.cc
Only gstreamer-vaapi plugin modules addressed as in the original code. Possibly need to have va plugin support too, but on a lower rank.
> H.265(HEVC) decoder ranking adjusted for VA-API and libav

- src/Settings/UnitsSettings.cc
Changes Farenheit to Fahrenheit, only in the string.
Should "farenheit" be replaced to "fahrenheit" in other places throughout the code? I'm worried about backwards compatibility with the method names and such.
> Fix typo in Fahrenheit name

- src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
> APM: cope with IN_PROGRESS messages from autopilot

- .github/workflows/android_release.yml
This forces gradle to use android-33 sdk version. Without this CI builds will fail since gradle blows up with newer SDKs.
> Remove android sdks from github runner which are newer than 33

- src/Vehicle/Vehicle.cc
Required because the label of the currently active mode might change.
E.g. when an external mode gets registered but was already selected.
> Vehicle: update mode when StandardModes::modesUpdated is emitted

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
I've tested this in ArduPilot SITL.
The interface used for this testing was click-on-map and select the "Move to" option.
I tested Rover, Copter and Plane which actually implement DO_REPOSITION, and on Sub which doesn't.  All act as expected.
> APMFirmwarePlugin: reposition using MAV_CMD_DO_REPOSITION 

- src/QmlControls/QGCTextField.qml
**Description:**
This pull request addresses an issue with the input method hints that was causing problems with Android devices, specifically related to the use of the virtual numeric keyboard. The problem arose from an inverted condition, which led to incorrect behavior.
**Changes Made**
Reversed the condition to correctly force the use of the virtual numeric keyboard only when numericValuesOnly is true and the device is not an IOS device.
**Problem**
This condition was causing problems on Android devices by not allowing users to search for parameters or create com link names using alphabetic characters.
> QGCTextField: fix forcing the use of virtual numeric keyboard

- custom-example/qgcresources.qrc
- custom-example/qgroundcontrol.qrc
- custom-example/res/CustomFlyViewOverlay.qml
- qgroundcontrol.qrc
- src/FlightDisplay/FlyView.qml
- src/FlightDisplay/FlyViewCustomLayer.qml
- src/FlightDisplay/FlyViewInsetViewer.qml
- src/FlightDisplay/FlyViewMap.qml
- src/FlightDisplay/FlyViewWidgetLayer.qml
- src/QmlControls/QGroundControl/FlightDisplay/qmldir
When I tried to use insets to position a widget on a custom fly view layer, I discovered that the inset system in master QGC is pretty much non functioning. This PR is my attempt to restore what I think the intended functionality of the system is, and it is a work in progress. There are some elements here which are open to interpretation, so I want some input from others on this.
**The inset system is currently not working because:**
- In the widget layer, very few widgets actually have insets passed out through totalToolInsets
- When the insets are passed through the default FlyViewCustomLayer, all the insets get wiped anyway before they are passed to the map layer
- The FlyViewMap only looks at the center insets to determine whether the vehicle has moved under the UI, this can cause it …
> Restore tool inset functionality

- CMakeLists.txt
Switched mavlink include option from 'ardupilotmega' to 'all' in the CMakeLists file. This modification will allow the use of all the functionalities offered by the mavlink library. the range of functionalities that can be utilized from the mavlink library.
@bkueng Please check out this PR because it fixes cmake compilation for StandardModes.
> Use all mavlink includes instead of ardupilotmega for cmake build

- QGCCommon.pri
Building master QGC (or latest stable 4.2.6) on MacOS qmake or qtcreator was failing due to "unused but set variable" errors in QGCTileCacheWorker.cpp and the Eigen library.
My environment is:
- macOS Ventura 13.4.1
- x86_64
- using SDK 13.3 from Xcode 14
Adding -Wno-unused-but-set-variable suppresses the errors and the build succeeds fine.
These errors could be directly resolved in QGCTileCacheWorker.cpp but they would still be in the Eigen lib so I figured suppressing them was the better option but I could be wrong.
Another couple of notes about building QGC on MacOS Ventura which might be helpful for others
- the qt online installer is criminally slow, can use this line to open the online installer using a faster mirror and it will take 20 minutes rather than 20 hours `open …
> Fix compile errors for MacOS Build

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/Vehicle/Actuators/ActuatorActions.cc
- src/Vehicle/Actuators/ActuatorActions.h
- src/Vehicle/Actuators/ActuatorTesting.cc
- src/Vehicle/Actuators/ActuatorTesting.h
- src/Vehicle/Actuators/MotorAssignment.cc
- src/Vehicle/Actuators/MotorAssignment.h
- src/Vehicle/Autotune.cpp
- src/Vehicle/Autotune.h
- src/Vehicle/RequestMessageTest.cc
- src/Vehicle/SendMavCommandWithHandlerTest.cc
- src/Vehicle/SendMavCommandWithHandlerTest.h
- src/Vehicle/SendMavCommandWithSignallingTest.cc
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/comm/MockLink.cc
- src/comm/MockLink.h
Replacement for #10850.
The current problems with Vehicle::sendMavCommandWithHandler in progress support:
* When a MAV_RESULT_IN_PROGRESS ack is received the Vehicle code does the following incorrect things:
* The command entry is removed from the entry list. Since this is only a progress indication to command is still in play and we are still waiting for the real ack so it should be left in the list.
* The timeout for the command ack which is used is left alone. This means that it will fire too early with respect to not getting a completion ack. When an in progress ack is received the timeout should be restarted to give more time for the completion ack to be seen.
* If the command supports retries and we get an in progress we should not retry the command. The reason being we did hear …
> Fix up support for MAV_RESULT_IN_PROGRESS

- src/FactSystem/FactMetaData.cc
- src/FactSystem/FactMetaData.h
- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.cc
- src/FirmwarePlugin/FirmwarePlugin.h
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
- src/FlightDisplay/GuidedActionsController.qml
- src/FlightDisplay/GuidedValueSlider.qml
- src/QmlControls/QmlUnitsConversion.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
This PR adds support for Arduplane to change airspeed. The slider will show ONLY if we are in fixed wing firmware. Under actions tab, a new option available "set airspeed" will be available, and after selecting, we will have a slider to select the desired airspeed. The slider will be automatically scaled using ARSPD_FBWA_MAX and MIN parameters. This is sending a MAV_CMD_DO_CHANGE_SPEED, with:
- param 1 = 0 ( airspeed )
- param 2 = airspeed setpoint
- param 3 = -1 (no throttle change)
- param 4 = 0 (absolute speed, not incremental)
- rest of parameters to 0.
In a different commit I also modified the guided slider so it shows "m/s" instead of "m" when we are dealing with speeds. This is hardcoded and it is not getting system unit settings, this is done on purpose as we don't have …
> Add airspeed guided action support for Ardupilot fixed wing, fix speed change slider

- qgroundcontrol.pro
- qgroundcontrol.qrc
- src/Vehicle/EFIFact.json
- src/Vehicle/GeneratorFact.json
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/Vehicle/VehicleEFIFactGroup.cc
- src/Vehicle/VehicleEFIFactGroup.h
- src/Vehicle/VehicleGeneratorFactGroup.cc
- src/Vehicle/VehicleGeneratorFactGroup.h
EFI and Generator are already in upstream mavlink common.xml, but I just realized EKF one is ardupilotmega.xml only.
Should we implement something through firmwareplugin to workaround it? Or we should just drop it and not include it?
For the rest of it these changes have been working for some time in a custom build.
> Add support for EFI, EKF and Generator telemetry

- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/Vehicle/VehicleFact.json
Add support to have altitude above terrain as displayable telemetry. It queries terrain data when vehicle coordinate is changed to compute the altitude, but it has an elapsed timer to limit the time between those queries to 500ms minimum, because the terrain query system wasn't able to service them at higher rate, and 500ms is fine anyway for this information. This elapsed timer is not super elegant there, if anybody has a nicer idea for it I will be happy to work on it.
Last commit is unrelated, but I realized that function wasn't in the private slot declaration, and it belongs there. Same for first commit.
Thanks to https://araceuas.com for sponsoring this.
> Vehicle: add support for altitude above terrain as fact for telemetry panel

- src/VideoReceiver/VideoReceiver.pri
* Fix for #10861
* Something changed in the github actions windows runner which places everything on the D drive instead of C
> Windows: Look for gstreamer on D drive as well as C

- src/FactSystem/FactMetaData.cc
- src/FactSystem/FactMetaData.h
- src/MissionManager/MavCmdInfoCommon.json
- src/MissionManager/MissionCommandUIInfo.cc
- src/MissionManager/MissionCommandUIInfo.h
- src/MissionManager/SimpleMissionItem.cc
A number of `MAV_CMD`s have minimum and maximum values for the params. For example, [MAV_CMD_NAV_LOITER_TURNS](https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_LOITER_TURNS) has a minimum of 0 for `param1` ("Turns").
This PR adds `"min"` and `"max"` fields to the definitions in `MavCmdInfoCommon.json`, and uses them when setting up the `Fact`s to display when planning a Mission.
> Add range checking to Mission Item params

- src/FlightMap/Widgets/PhotoVideoControl.qml
A minor bug exists where the record button is enabled even before there is an active stream streaming. 
Hitting the record button before there is an active stream will give this error:
`qrc:/qml/QGroundControl/FlightMap/PhotoVideoControl.qml:104: TypeError: Cannot read property 'capturesPhotos' of null`
My change makes the record button disabled until it is possible to record.
> PhotoVideoControl.qml: Fixed TypeError when pressing recording button with no active stream

- src/QGCApplication.cc
Android is no longer in the store where the updates were managed. So turn back on stable version check notifications on mobile builds so users are notified by QGC when a new stable is available.
> Stable version check on mobile builds

- .github/workflows/android_release.yml
- .github/workflows/docs_deploy.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/windows_release.yml
> Test deployment script 1

- src/QGCApplication.cc
- src/main.cc
This avoids a segfault on destruction when no vehicle was ever discovered.
This replaces https://github.com/mavlink/qgroundcontrol/pull/10877
> main: fix Ctrl+C

- src/FactSystem/FactControls/FactTextField.qml
- src/QmlControls/EditPositionDialog.qml
- src/QmlControls/ParameterEditorDialog.qml
- src/QmlControls/QGCPopupDialog.qml
- src/QmlControls/QGCTextField.qml
- src/ui/MainRootWindow.qml
Fixed a pile of problems related to validating fact values from the ui text fields:
* When a validation fails it now shows a tooltip with the error instead of popping up the whole monster parameter editing dialog.
* Created new system for signalling ui validation error which in turn prevents you from moving away to another part of the ui until you resolve the validation error.
* QGCPopupDialog with CloseOnPressOutside would skip the validation step. Leading to all sorts of strange behavior.
* Fixed a bunch of bugs in the Parametedr Editor dialog
Here's an example of the tooltip:
> Fact text field validation

- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/Vehicle/VehicleFact.json
This information is in NAV_CONTROLLER_OUTPUT ( in common.xml ). We were already parsing this message but just not taking into account this field, and it is a nice value to have. It is under vehicle telemetry right under heading to next WP.
> Vehicle: add distance to next WP fact

- src/FlightDisplay/FlyViewMap.qml
- src/FlightDisplay/FlyViewWidgetLayer.qml
The map scale width changes when the zoom up/down buttons are clicked.
When buttons are on the right, and when the user quickly clicks a zoom
up/down button several times, the first click change the scale, which
changes the buttons position. Subsequent clicks are most of the time not
where the user wanted to put them.
Putting buttons on the left of the scale will keep them at a fixed
position, fixing this unfortunate behavior.
Signed-off-by: Julien Olivain <ju.o@free.fr>
> FlightDisplay: put zoom buttons on the left of the scale

- src/QmlControls/ParameterEditor.qml
There are couple of things that can be improved in the Parameters tab:
1. How can the param edit pop-up's width be changed? I tried editing the '_editFieldWidth' value but it doesn't seem to change the width :( https://github.com/mavlink/qgroundcontrol/blob/12d286fb75189f8343851b1bfd603535c9a489cb/src/QmlControls/ParameterEditorDialog.qml#L36
Continuation of  #10277 as it was closed due to the repository begin deleted & re-created in my side!
> Parameters Tab improvements

- src/VehicleSetup/JoystickConfigButtons.qml
- translations/qgc.ts
- translations/qgc_source_az_AZ.ts
- translations/qgc_source_bg_BG.ts
- translations/qgc_source_de_DE.ts
- translations/qgc_source_el_GR.ts
- translations/qgc_source_es_ES.ts
- translations/qgc_source_fi_FI.ts
- translations/qgc_source_fr_FR.ts
- translations/qgc_source_he_IL.ts
- translations/qgc_source_it_IT.ts
- translations/qgc_source_ja_JP.ts
- translations/qgc_source_ko_KR.ts
- translations/qgc_source_nl_NL.ts
- translations/qgc_source_no_NO.ts
- translations/qgc_source_pl_PL.ts
- translations/qgc_source_pt_PT.ts
- translations/qgc_source_ru_RU.ts
- translations/qgc_source_sv_SE.ts
- translations/qgc_source_tr_TR.ts
- translations/qgc_source_zh_CN.ts
This improves readability of the Joystick multi-button assignment warning!
Resolves https://github.com/PX4/PX4-user_guide/pull/2072#issuecomment-1308198119
I had to apply an anchor, as the text was too squashed to the top, and was visually not great (not enough spacing between column items)
> JoyStickButtonAssignment: Fix warning text

- android.pri
- android/AndroidManifest.xml
- android/src/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java
- android/src/com/hoho/android/usbserial/driver/CommonUsbSerialDriver.java
- android/src/com/hoho/android/usbserial/driver/Cp2102SerialDriver.java
- android/src/com/hoho/android/usbserial/driver/FtdiSerialDriver.java
- android/src/com/hoho/android/usbserial/driver/ProlificSerialDriver.java
- android/src/com/hoho/android/usbserial/driver/UsbId.java
- android/src/com/hoho/android/usbserial/driver/UsbSerialDriver.java
- android/src/com/hoho/android/usbserial/driver/UsbSerialProber.java
- android/src/com/hoho/android/usbserial/driver/UsbSerialRuntimeException.java
- android/src/org/mavlink/qgroundcontrol/QGCActivity.java
- android/src/org/mavlink/qgroundcontrol/UsbIoManager.java
- libs/qtandroidserialport/src/qserialport.cpp
- libs/qtandroidserialport/src/qserialport.h
- libs/qtandroidserialport/src/qserialport_android.cpp
- libs/qtandroidserialport/src/qserialportinfo.cpp
- libs/qtandroidserialport/src/qserialportinfo.h
- libs/qtandroidserialport/src/qserialportinfo_android.cpp
- libs/qtandroidserialport/src/qtandroidserialport.pri
- src/GPS/GPSProvider.h
- src/QmlControls/QGCPopupDialog.qml
- src/VehicleSetup/Bootloader.h
- src/VehicleSetup/FirmwareUpgradeController.h
- src/VehicleSetup/PX4FirmwareUpgradeThread.cc
- src/VehicleSetup/PX4FirmwareUpgradeThread.h
- src/comm/LinkManager.cc
- src/comm/SerialLink.cc
- src/comm/SerialLink.h
- src/main.cc
I had thought that Qt6 had android serial port support built in so I removed the custom support during the upgrade. I was wrong about that and had to put the all the old android serial port code back.
Related to #10887
> Add back custom android serial port support

- .github/workflows/android_release.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/windows_release.yml
Also removed paths-ignore for workflows. Previous mechanism installed the NDK manually. This was causes problem in that binaries were not being stripped leading to huge APKs.
> Use github runner default NDK

- src/comm/LinkManager.cc
This was used during Qt6 transtion. No longer needed.
> Remove unused ifdef

- src/MissionManager/QGCMapPolygonVisuals.qml
Replacement for #10477. Differences from that pull:
* Edge lengths only show when a polygon vertex is being dragged
* Edge length distances are translated into the user specified horizontal distance units
* Edge length distance values on have one digit past the decimal point
> Show polygon edge lengths while dragging vertex

- src/AutoPilotPlugins/PX4/PX4TuningComponent.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentCopter.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentCopterAll.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentCopterAttitude.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentCopterPosition.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentCopterRate.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentCopterVelocity.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneAll.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneAttitude.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneRate.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentPlaneTECS.qml
- src/AutoPilotPlugins/PX4/PX4TuningComponentVTOL.qml
- src/FirmwarePlugin/PX4/PX4Resources.qrc
- src/QmlControls/AutotuneUI.qml
- src/QmlControls/PIDTuning.qml
- src/Vehicle/Autotune.cpp
- src/Vehicle/Autotune.h
Previously tuning was turned off in mobile. Fixes #10975. It works exactly like it did before except I changed the AutoTune Enabled slider to radio buttons and a few other tweaks to make it more understandable. At first I couldn't figure out what that slider meant. I think the radio buttons make things more clear. The chart now has a minimum size below which it will not go. After that, the page will scroll to show everything. Given the complexity of this page it required major changes to make it resize nicely. So help with testing is appreciated.
Note: I was unable to test Plane and VTOL since I'm stuck with only jmavsim SITL on OSX arm.
> PX4 PID Tuning: Major rework to support smaller screens/scrolling

- CMakeLists.txt
- src/CMakeLists.txt
- src/UTMSP/CMakeLists.txt
Fixes the error:
qrc:/qml/MainRootWindow.qml:23:1: module "QGroundControl.UTMSP" is not installed
I had to add utmsp_dummy.qrc directly to QGC_RESOURCES, adding it to the UTMSP library wasn't enough.
> fix cmake build: add UTM library

- src/Settings/RemoteID.SettingsGroup.json
- src/Settings/RemoteIDSettings.cc
- src/Settings/RemoteIDSettings.h
- src/Vehicle/RemoteIDManager.cc
- src/Vehicle/RemoteIDManager.h
- src/ui/preferences/RemoteIDSettings.qml
This implements the validation of the operator ID as required for the EU remote ID spec.
The way it works is that:
1. The user enters the operator ID including the checksum and secret.
2. The ID is validated using the secret against the checksum.
3. The secret is removed and the public ID is saved, as well as a flag signalling that the ID has been checked.
This work is sponsored by [bluemark.io.](https://bluemark.io/), https://github.com/BluemarkInnovations.
> RemoteID: validate EU operator ID

- src/QmlControls/ClickableColor.qml
- src/QmlControls/QGCSwitch.qml
After migration to Qt6 these controls were broken
> Fix QGCSwitch  and ClickableColor after migration to Qt6

- android.pri
When building for Android locally, I was getting this error: `Dependency 'androidx.core:core:1.10.1' requires libraries and applications thatdepend on it to compile against version 33 or later of theAndroid APIs.`
Also Qt Creator highlights the variable name after fixing the typo
> Fix variable name typo in Android config

- qgroundcontrol.qrc
- src/FactSystem/FactControls/LabelledFactSlider.qml
- src/FirmwarePlugin/FirmwarePlugin.cc
- src/FirmwarePlugin/FirmwarePlugin.h
- src/FlightMap/Widgets/CMakeLists.txt
- src/FlightMap/Widgets/CompassDial.qml
- src/FlightMap/Widgets/CompassHeadingIndicator.qml
- src/FlightMap/Widgets/IntegratedCompassAttitude.qml
- src/FlightMap/Widgets/QGCCompassWidget.qml
- src/QGCPalette.cc
- src/QGCPalette.h
- src/QmlControls/FactSlider.qml
- src/QmlControls/QGCCheckBoxSlider.qml
- src/QmlControls/QGroundControl/FlightMap/qmldir
- src/QmlControls/SettingsGroupLayout.qml
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Other changes:
* Heading to Home indicator now shown as "L" to match Launch Point item in map
* Other indicators: course over ground, heading to next waypoint, remain the same.
* Position/size of heading degrees text is much more visible than before
* A number of other minor visual fixes
* Custom build note: The Compass Heading Indicator (the red vehicle looking thingy) is now a Qml control which custom build can override using a resource override. Replacing this via FirmwarePlugin C++ code is no longer supported. Reason being, resource override is way simpler than writing C code. In general I'm moving the custom build support from C code overrides to simpler resource overrides where possible.
> Reworked Compass Instrument to be less cluttered

- .github/workflows/android_release.yml
- .github/workflows/docs_deploy.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/videoapp_linux.yml
- .github/workflows/windows_release.yml
There is the issue of older node.js versions being EOL this/next quarter. All of these actions have moved to node.js 20, which removes all of those version warnings when running the workflows.
> Update Workflow Actions due to EOL Node.js

- src/QGCApplication.cc
Fix
Changed QGCApplication method to invoke "showVehicleSetupTool" instead of incorrect "showSetupTool".
The previous code attempted to invoke the "showSetupTool" method within the QGCApplication class. This has been corrected to "showVehicleSetupTool".
> Fix QML method showVehicleSetupTool invokation from c++ 

- .github/workflows/android_release.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/videoapp_linux.yml
- .github/workflows/windows_release.yml
This will build on whichever is the newest patch version available. From [Qt docs](https://wiki.qt.io/Qt-Version-Compatibility), "Patch releases are both backwards and forwards binary and source compatible."
> Allow newer Qt 6.6.x patch versions

- src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
- src/AutoPilotPlugins/PX4/SensorsComponentController.cc
- src/VehicleSetup/FirmwareUpgradeController.cc
Fix invocations of the "append" QML method from multiple C++ controllers to directly pass QString instead of QVariant and remove returnValue as there is no return value.
> Fix QML method invocations from C++

- src/QmlControls/QGCComboBox.qml
> Fix QGCComboBox popup width calculation when need to size popup to content

- .github/workflows/android_release.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/videoapp_linux.yml
- .github/workflows/windows_release.yml
This adds the automatic caching option to the install-qt-action. Also it removes the extra linux install from the android workflow, which is handled automatically by setting `extra:        --autodesktop` in the android Qt download.
One extra note: CCache isn't working in the workflows and hasn't been for some time, I might try and fix it but it's probably better to just wait until we switch to CMake, where ninja will make ccache less relevant.
> Cache CI Qt Downloads

- .github/workflows/android_release.yml
https://github.com/mavlink/qgroundcontrol/issues/10968
android-34-ext10 was being installed which was causing the build step on Stable-V4.3 to fail. 
I noticed similar issues were experienced in the past here: https://github.com/mavlink/qgroundcontrol/pull/10848
With this change I managed to get past the build step successfully. However, every branch our fork fails at the "Upload build to S3 Bucket" step, so I cannot confirm with full certainty that it will succeed.
Here's that workflow run if you are curious:
https://github.com/AscendEngineering/qgroundcontrol/actions/runs/7936789857/job/21672792328
> Fix Stable_V4.3 android build workflow

- CMakeLists.txt
- qgroundcontrol.pro
- qgroundcontrol.qrc
- src/AirLink/AirLinkManager.cc
- src/AirLink/AirLinkManager.h
- src/AirLink/AirLinkSettings.qml
- src/AirLink/AirlinkLink.cc
- src/AirLink/AirlinkLink.h
- src/AirLink/CMakeLists.txt
- src/CMakeLists.txt
- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QGroundControlQmlGlobal.h
- src/Settings/App.SettingsGroup.json
- src/Settings/AppSettings.cc
- src/Settings/AppSettings.h
- src/comm/LinkConfiguration.cc
- src/comm/LinkConfiguration.h
- src/comm/LinkManager.cc
Dear QGroundControl community,
My name is Constanteen, and I am a developer at ClearSky, the company behind airlink flight controllers.
To impove our products we decided to add support for connection to drones via LTE. My predecessor took an oportunity to add this feature. But during pull request dialog he faced requirement to impliment result of our work in form of plugin like microhard or taisync. The old pull request was deleted and my predecessor gave me full power of his repository. So here we are. Airlink features was extracted from LinkManager and airlink plugin settings was added.
Thank you for considering our contribution.
Best regards,
Constanteen
Airlink Team
ClearSky Company
> Plugin airlink

- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/videoapp_linux.yml
- .github/workflows/windows_release.yml
This will finally prevent it from creating so many caches,
Also, can you delete all the caches with timestamps appended again like `ccache-Linux-Debug-2024-02-20T19:46:10.843Z`? The Qt download caches are working well, but the timestamps are causing misses for the builds.
> Don't append timestamps to caches

- qgroundcontrol.qrc
- src/FlightDisplay/CMakeLists.txt
- src/FlightDisplay/FlyView.qml
- src/FlightDisplay/FlyViewBottomRightRowLayout.qml
- src/FlightDisplay/FlyViewTopRightColumnLayout.qml
- src/FlightDisplay/FlyViewWidgetLayer.qml
- src/FlightDisplay/TelemetryValuesBar.qml
- src/FlightDisplay/TerrainProgress.qml
- src/FlightMap/Widgets/CMakeLists.txt
- src/FlightMap/Widgets/HorizontalCompassAttitude.qml
- src/FlightMap/Widgets/IntegratedAttitudeIndicator.qml
- src/FlightMap/Widgets/IntegratedCompassAttitude.qml
- src/FlightMap/Widgets/PhotoVideoControl.qml
- src/FlightMap/Widgets/VerticalCompassAttitude.qml
- src/QmlControls/CMakeLists.txt
- src/QmlControls/QGroundControl/FlightDisplay/qmldir
- src/QmlControls/SelectableControl.qml
* Telemetry values and instruments are merged together aligned to bottom right edge. Custom builds folks may remember this look being in the old custom build example.
* Photo/Video control is aligned to top/right edge
* Goal is to keep center of screen as clear as possible
* Also created new layout mechanism for custom builds to more easily add to ui layer. They can resource override FlyViewTopRightColumnLayout.qml and/or FlyViewBottomRightRowLayout.qml to to add their own controls into the flow. The custom widget layer continues to work as before as does all the QGCToolInsets stuff. But these new mechanisms allow for less upstream change and simpler mods to get what you want.
More to come in cleaning up the Photo/Video control to not be such a large monstrosity.
> Rework instrument and video cluster

- .github/actions/upload/action.yml
- .github/workflows/windows_release.yml
Allows you to specify source directory for upload. Everything uses the default package directory except Windows which is in staging.
> Fix Windows AWS Upload

- cmake/MacOSXBundleInfo.plist.in
- cmake/QGCDeploy.cmake
- src/FlightDisplay/FlightDisplayViewUVC.qml
- src/VideoManager/VideoManager.cc
* cmake builds were not generating Info.plist file from template in OSX builds
* Added camera permission to Info.plist
* Updated VideoManager to request camera permissions. Given camera permission for UVC for the first time now requires QGC reboot to take effect. Theoretically this should not be needed but I couldn't figure out how to make Qt happy without it. Wondering if there is maybe a Qt bug there somewhere.
* Update UVC video qml to Qt6 changes
> UVC video fixes

- CMakeLists.txt
- cmake/CompileOptions.cmake
- src/FlightDisplay/FlyViewTopRightColumnLayout.qml
- test/CMakeLists.txt
This also has some cmake hacks to get things like MockLink testing into debug builds.
> Centered photo video

- src/QmlControls/ParameterEditorDialog.qml
It was still narrowly sized for the old right panel style dialogs. That dialog can be pretty wordy so wider is better.
> Larger width for parameter editor dialog

- src/FirmwarePlugin/APM/APMBatteryIndicator.qml
- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/APM/APMFlightModeIndicator.qml
- src/FirmwarePlugin/APM/APMMainStatusIndicatorContentItem.qml
- src/FirmwarePlugin/APM/APMResources.qrc
- src/FirmwarePlugin/APM/CMakeLists.txt
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FlightModeIndicator.qml
This brings in line the ArduPilot firmware specific side of things with respect to toolbar indicator expanded content. The goal of all of this is to provide a simpler place to modify vehicle settings which are changed frequently instead of having to root through the mass of Vehicle Setup pages.
Expanded main status indicator provides direct access to GCS Failsafe, and General Failsafe Options:
Expanded flight mode indicator provides direct access to RTL settings:
Expanded battery indicator provides direct access to Battery Failsafe settings:
> Toolbar Indicators expanded content for ArduPilot

- src/ADSB/CMakeLists.txt
- src/AirLink/CMakeLists.txt
- src/AnalyzeView/CMakeLists.txt
- src/Audio/CMakeLists.txt
- src/AutoPilotPlugins/CMakeLists.txt
- src/CMakeLists.txt
- src/Camera/CMakeLists.txt
- src/Compression/CMakeLists.txt
- src/FactSystem/CMakeLists.txt
- src/FactSystem/FactControls/CMakeLists.txt
- src/FirmwarePlugin/CMakeLists.txt
- src/FlightMap/CMakeLists.txt
- src/FollowMe/CMakeLists.txt
- src/GPS/CMakeLists.txt
- src/Geo/CMakeLists.txt
- src/Joystick/CMakeLists.txt
- src/MissionManager/CMakeLists.txt
- src/PositionManager/CMakeLists.txt
- src/QmlControls/CMakeLists.txt
- src/QtLocationPlugin/CMakeLists.txt
- src/Settings/CMakeLists.txt
- src/Terrain/CMakeLists.txt
- src/Vehicle/Actuators/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
- src/VehicleSetup/CMakeLists.txt
- src/VideoManager/CMakeLists.txt
- src/VideoReceiver/CMakeLists.txt
- src/Viewer3D/CMakeLists.txt
- src/api/CMakeLists.txt
- src/comm/CMakeLists.txt
Use qt_add_library instead of add_library, which I believe handles some things internally to help with deploying. Next task will be to add qml modules.
> Convert cmake to use qt_add_library

- src/ADSB/CMakeLists.txt
- src/AirLink/CMakeLists.txt
- src/AnalyzeView/CMakeLists.txt
- src/Audio/CMakeLists.txt
- src/AutoPilotPlugins/CMakeLists.txt
- src/Camera/CMakeLists.txt
- src/Compression/CMakeLists.txt
- src/FactSystem/CMakeLists.txt
- src/FactSystem/FactControls/CMakeLists.txt
- src/FirmwarePlugin/CMakeLists.txt
- src/FlightMap/CMakeLists.txt
- src/FollowMe/CMakeLists.txt
- src/GPS/CMakeLists.txt
- src/Geo/CMakeLists.txt
- src/Joystick/CMakeLists.txt
- src/MissionManager/CMakeLists.txt
- src/PositionManager/CMakeLists.txt
- src/QmlControls/CMakeLists.txt
- src/QtLocationPlugin/CMakeLists.txt
- src/Settings/CMakeLists.txt
- src/Terrain/CMakeLists.txt
- src/Vehicle/Actuators/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
- src/VehicleSetup/CMakeLists.txt
- src/VideoManager/CMakeLists.txt
- src/VideoReceiver/CMakeLists.txt
- src/Viewer3D/CMakeLists.txt
- src/api/CMakeLists.txt
- src/comm/CMakeLists.txt
By default, qt_add_library creates a library type based on how Qt was built - in our scenario, it's set to SHARED.
> Fix cmake build after migration to qt_add_library

- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/videoapp_linux.yml
- .github/workflows/windows_release.yml
- CMakeLists.txt
This will need a follow up after some more testing, but at least for now the linux_debug workflow has been updated to use CMake and runs the unit tests correctly. Getting this PR merged first will let us verify future CMake changes easier. The other workflows can be converted to CMake after we verify all of the deployment properties for each platform are set correctly.
Also added qtconnectivity which was required for bluetooth.
Ultimately I would like VideoReceiverApp to share the same root CMakeLists.txt and just be a separate executable.
> Update CMake Deployment

- src/VehicleSetup/JoystickConfigButtons.qml
- src/VehicleSetup/JoystickConfigCalibration.qml
- src/VehicleSetup/JoystickConfigGeneral.qml
This update changes the method signatures for "onAxisValueChanged", "onRawButtonPressedChanged", and "onAxisValues" events in QML according to Qt6 requirements. Each event now directly accepts the necessary arguments.
> Fixes for joystick event handling in QML

- docs/en/qgc-dev-guide/getting_started/index.md
- docs/en/qgc-user-guide/getting_started/download_and_install.md
* Fix typo in new dev guide setup for ubuntu shell script
* Add Qt6 requirements on Ubuntu in user guide. Temporary fix till AppImage is fixed up to include these things.
> Doc update

- .github/workflows/android_release.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_release.yml
- .github/workflows/videoapp_linux.yml
- .github/workflows/windows_release.yml
This prevents separate caches being created for every single pull request. Not sure if this is an issue with the ccache action or what but I don't see a way to change it. So only pushes on master will be cached for now.
> Dont cache pull requests

- src/Camera/QGCCameraControl.cc
- src/Camera/QGCCameraControl.h
- src/Camera/QGCCameraManager.cc
- src/FlightDisplay/FlyViewTopRightColumnLayout.qml
- src/FlightMap/FlightMap.qml
- src/FlightMap/Widgets/PhotoVideoControl.qml
* Added zoom slider support
* Reordered controls for better grouping of things which go together
* Take less horizontal real estate
Before:
After:
Simple (non mavlink camera protocol) camera: controls:
> Photo video control rework

- src/FlightDisplay/FlyViewToolStripActionList.qml
- src/Viewer3D/OsmParser.cc
- src/Viewer3D/OsmParser.h
- src/Viewer3D/Viewer3D/Models3D/Viewer3DModel.qml
- src/Viewer3D/Viewer3D/Models3D/Viewer3DVehicleItems.qml
- src/Viewer3D/Viewer3D/Models3D/Waypoint3DModel.qml
- src/Viewer3D/Viewer3D/Viewer3D.qml
The following changes have been made in this pull request to improve the 3D View:
- All types of buildings are now fetched from the OSM file and added to the 3D View.
- The ROI is shown with a separate marker (Letter "R") in the 3D View
- The takeoff position is also marked with the letter "T" in the 3D View
Here is a picture demonstrating the new changes:
> 3D View fixes: showing all types of buildings as well as the ROI

- .github/workflows/linux_debug.yml
- CMakeLists.txt
- cmake/CreateAppImage.cmake
I'm not sure linuxdeployqt is needed anymore because of the built in qt_generate_deploy_qml_app_script, but let's try it out anyway. I can only test via CI because the AppImageToolkit/linuxdeployqt guys are hostile about supporting newer os. I believe [this](https://github.com/linuxdeploy/linuxdeploy-plugin-qt) might be the better option
Edit: I have several different methods commented out to try in the cmake file.
> CMake: Create linux appimage

- src/Terrain/TerrainTile.cc
- src/Terrain/TerrainTile.h
This is instead of raw allocated memory. This way we can do some additional checks to prevent crashes caused by bad access into raw memory. Related to #11175. This fixes the crash but not the true cause as to how the tiles go screwed up in the first place.
> Switch elevation data storage to QList

- src/FlightDisplay/FlyViewMap.qml
- src/QmlControls/EditPositionDialog.qml
- src/QmlControls/MissionItemIndexLabel.qml
* No need to confirm set roi any more with slider
* Click ROI item shows menu. New feature to manually edit ROI position.
* Updated Edit Position dialog to new style
> ROI editing support

- .github/workflows/android_debug.yml
- cmake/Qt6QGCConfiguration.cmake
- test/qgcunittest/UnitTest.h
This doesn't build successfully because of a missing QtQuick3DTools lib, but I only see that available in the desktop Qt build? I'm not sure if this is a Qt bug or there's something I'm misunderstanding. Having set QT_HOST_PATH correctly, it shouldn't be related to the fact that it's cross-compiling for mobile. Although it builds for qmake so that shows I'm probably doing something wrong tho.
`Qt6Quick3D could not be found because dependency Qt6Quick3DTools could not be found.`
Here are the available Android libs:
And here's the same for Linux:
There is no Qt6Quick3DTools for Android so I don't really understand.
Also, I know there's a lot of workflows and they take forever now. Hopefully we can narrow that down soon but this at least ensures CMake will  work for everything.
> CI: Add android debug workflow

- src/Vehicle/Vehicle.cc
> Vehicle: Remove centi-degrees conversion in MOUNT_CONTROL

- CMakeLists.txt
- src/CMakeLists.txt
At first I was noticing an issue with where the Viewer3D qmldir was. I found out it was related to QT_QML_ROOT_PATH, so I changed that value. Then I had to fix the android app not finding the main function, which meant moving main.cc to the root executable.
> CMake: Fix Android Executable

- qgroundcontrol.qrc
- src/QmlControls/QGroundControl/Controls/qmldir
- src/Settings/RemoteID.SettingsGroup.json
- src/Settings/RemoteIDSettings.cc
- src/Settings/RemoteIDSettings.h
- src/Vehicle/RemoteIDManager.cc
- src/Vehicle/RemoteIDManager.h
- src/ui/SettingsPagesModel.qml
- src/ui/toolbar/CMakeLists.txt
- src/ui/toolbar/RemoteIDIndicator.qml
- src/ui/toolbar/RemoteIDIndicatorPage.qml
* Converted Remote ID Indicator to new style
* Removed the remote id enable setting:
* Remote ID settings page is always shown
* If comms are good in the remote id manager open drone id message are sent to the vehicle
* Added RemoteIDManager.available property. This indicates whether the vehicle support Open Drone ID of not
* Remote ID toolbar indicator will not be shown if the vehicle does not support Mavlink Open Drone ID
ToDo:
* Rework remote id settings to the new ui style
* Allow remote id settings to be configured in expanded page of the toolbar indicator
@Davidsastresas FYI: Other than the enable thing, the functionality is exactly the same. Just visual changes.
> Remote id indicator: Convert to new UI style, plus other changes

- src/PositionManager/PositionManager.cpp
- src/QGCApplication.cc
- src/QmlControls/QGroundControlQmlGlobal.h
QGeoPositionInfoSource::setUpdateInterval not support on iOS/OSX. If you do call it, it causes update timeout errors to be reported.
> Position manager fix

- src/FlightMap/FlightMap.qml
- src/ui/MainRootWindow.qml
The MouseArea fix was dominating the PinchHandler. Figured we should stick to the QML intended implementation of the Map and just disable the views if the tool drawer is open
> Pinch Zoom Fix

- src/QmlControls/QGCButton.qml
I screwed this up in my previous pull to fix icons on buttons. Change is subtle but important on small touch screen targets.
Before:
After:
> QGCButton: Put back missing implicitWidth/Height

- src/FlightMap/FlightMap.qml
- src/ui/MainRootWindow.qml
In the previous version, touch signals would undesirably propagate through the pages due to the DragHandler in FlightMap.qml not being correctly disabled when the toolDrawer was open. This update resolves this issue by adjusting the 'grabPermissions' setting and removing the flawed disabling of FlyView and PlanView that was previously based on the toolDrawer's visibility.
> Fix flight map DragHandler signal bleeding through the pages

- src/Vehicle/Vehicle.h
Both ArduPilot firmware and PX4 discard the altitude when called by this function:
https://github.com/mavlink/qgroundcontrol/blob/16f59b49208fe840ab511b5726a8e506c18681e7/src/FirmwarePlugin/APM/APMFirmwarePlugin.cc#L848
https://github.com/mavlink/qgroundcontrol/blob/16f59b49208fe840ab511b5726a8e506c18681e7/src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc#L487
I created the PR with the most obvious and least invasive fix, because for end-user there are still possibilities to change the altitude. If there would be a need to implement the API to call it with altitude, I'd contribute it guided by a maintainer what would be most useful for you
> Update Vehicle::guidedModeGotoLocation doc comment

- src/FactSystem/ParameterManager.cc
Fix bug with junk characters in 16-character parameter name
Description
-----------
I noticed that when parameters are 16-characters long, I can often see some junk characters in the end of their names when listing all the parameters. Looks like the problem was in the fact that we create a 16-characters buffer and copy the parameter name there. If the name is shorter than 16 characters, everything is fine, as the name is a null-terminated string. However, when the parameter name is exactly 16 characters long, there is no proper null-termination (which is allowed by [MavLink](https://mavlink.io/en/services/parameter.html#parameter-names)), and some junk characters get into the name. Fortunately, this seems to not break anything else, but potentially could lead to the application crash. An …
> Fix bug with junk characters in 16-character parameter name

- .github/workflows/android_debug.yml
- libs/CMakeLists.txt
- src/Utilities/CMakeLists.txt
This collects shapelib through fetchcontent in cmake, so that the submodule can be removed when qmake goes. They have done some cleanup to their cmake implementation since 1.5.0 but most of it seems to be coming after 1.6.0.
> Shapelib: Fetch through Cmake

- .github/workflows/android_debug.yml
- .github/workflows/android_release.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release.yml
- .github/workflows/macos_debug.yml
- .github/workflows/macos_release.yml
- .github/workflows/windows_debug.yml
- .github/workflows/windows_release.yml
- CMakeLists.txt
- QGCPostLinkCommon.pri
- deploy/docker/Dockerfile-build-linux
- qgroundcontrol.pro
- src/AutoPilotPlugins/APM/APMSafetyComponent.qml
- src/CMakeLists.txt
- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMParameterMetaData.cc
- src/FlightMap/MapItems/VehicleMapItem.qml
- src/FlightMap/Widgets/QGCAttitudeWidget.qml
- src/QmlControls/QGCColoredImage.qml
- src/QtLocationPlugin/CMakeLists.txt
- src/QtLocationPlugin/GoogleMapProvider.cpp
- src/Vehicle/CompInfoParam.cc
Resolves #11081. Removes all usage of the Qt5 Compatibility Module which I believe was made due to licensing issues with libraries Qt was using for the GraphicalEffects.
This also fixed a couple of issues:
- APMParameterMetaData::getParameterMetaDataVersionInfo was not getting the version numbers correctly
- APMFirmwarePlugin::_handleIncomingStatusText was never setting _coaxialMotors
All Qml visuals are 100% identical except for the ADSB shadow because I am terrible at graphical design. Here is a before and after:
@DonLakeFlyer Hopefully you can just tune a couple of the settings [here](https://github.com/HTRamsey/qgroundcontrol/blob/1dcc5f25c2581e83d0f1882e70f3beb76ae35824/src/FlightMap/MapItems/VehicleMapItem.qml#L47) to make it look better. I try to avoid touching Qml files since …
> Remove Qt5 Compatibility Module

- libs/CMakeLists.txt
- libs/zlib/CMakeLists.txt
- src/Compression/CMakeLists.txt
Fetch zlib through cmake and build. This ensures all platforms are on the same version. When qmake goes, the windows zlib can be removed from the libs folder.
> Zlib: Fetch through Cmake

- CMakeLists.txt
- libs/CMakeLists.txt
- libs/OpenSSL/CMakeLists.txt
Fetch Android Openssl through cmake, When qmake goes, libs/OpenSSL/android_openssl can go.
> Openssl: Fetch through cmake

- libs/CMakeLists.txt
- src/comm/CMakeLists.txt
This collects the qmdnsengine library through cmake instead of using the submodule. When qmake goes, the submodule can go.
> Qmdnsengine: Fetch Through Cmake

- ChangeLog.md
- src/AnalyzeView/MAVLinkInspectorController.cc
- src/AnalyzeView/MAVLinkInspectorController.h
- src/AnalyzeView/MAVLinkInspectorPage.qml
- src/QmlControls/QGCComboBox.qml
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Uses the currently selected message in the MavlinkInspector of the Analyze View to adjust individual message rates (rather than stream rates for groups of messages like is currently used for ArduPilot).
@DonLakeFlyer Design Advice? Maybe a TextField or SpinBox instead? Also, if you're cool with it I would like to move the QGCMAVLinkMessage and QGCMAVLinkSystem out of MavlinkInspectorController and into comm to be used by MAVLinkProtocol.
> Set Message Rates From Mavlink Inspector

- .github/workflows/macos_debug.yml
- .github/workflows/windows_debug.yml
- .github/workflows/windows_release.yml
- .gitmodules
- CMakeLists.txt
- libs/qmlglsink/CMakeLists.txt
- libs/qmlglsink/qt6/gstplugin.cc
- libs/qmlglsink/qt6/gstqml6glsink.cc
- libs/qmlglsink/qt6/gstqml6glsink.h
- libs/qmlglsink/qt6/gstqsg6glnode.cc
- libs/qmlglsink/qt6/gstqsg6glnode.h
- libs/qmlglsink/qt6/gstqt6element.cc
- libs/qmlglsink/qt6/gstqt6elements.h
- libs/qmlglsink/qt6/gstqt6gl.h
- libs/qmlglsink/qt6/gstqt6glutility.cc
- libs/qmlglsink/qt6/gstqt6glutility.h
- libs/qmlglsink/qt6/meson.build
- libs/qmlglsink/qt6/qt6glitem.cc
- libs/qmlglsink/qt6/qt6glitem.h
- qmlglsink.pri
- tools/setup/ubuntu.sh
This gets gstreamer to link correctly via cmake, and removes the unnecessary gst-plugins-good submodule since we only need the few files of the one plugin. Video is working fine on a Oneplus 9 pro streaming a 8mp 30fps rtsp camera.
> Qmlglsink: Gstreamer Build Fixes

- src/QmlControls/QGCMenuItem.qml
> Hack in MenuItem visible support

- src/Settings/FlightMode.SettingsGroup.json
- src/Settings/FlightModeSettings.cc
- src/Settings/FlightModeSettings.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/comm/QGCMAVLink.cc
- src/comm/QGCMAVLink.h
- src/ui/toolbar/FlightModeIndicator.qml
- test/MissionManager/MissionCommandTreeEditorTest.cc
- test/MissionManager/SimpleMissionItemTest.cc
* The vehicle classes are: Airship, Fixed Wing, Rover/Boat, Sub, Multi Rotor, VTOL
* This allows you have to separate hidden flight modes for a multi-rotor which are different for a fixed-wing for example
* The defaults have been adjusted to be vehicle class specific
* Updated defaults for ArduPilot vehicle classes according to discussion here: #11118
* Likely to have more updates to hidden defaults are I collect feedback
Example with default hidden flight modes applied on ArduCopter:
As opposed to the full list which scrolls off the screen!
> Hidden flight modes: Separate list for each firmware type and vehicle class combination

- src/QmlControls/QGCColoredImage.qml
At the moment, MultiEffect has limitations in its operation. It does not work with black images. Therefore, the most logical solution would be to use the features from Qt5
https://forum.qt.io/topic/144070/qt6-color-svg-using-multieffect/8
Multieffect:
ColorOverlay:
> Fix colorized icon with Qt5Compat.GraphicalEffects instead MultiEffet from Qt6

- src/Compression/CMakeLists.txt
- src/Utilities/CMakeLists.txt
Modify CMakeLists for shapelib and zlib fetch process to exclude them from install procedure
> Exclude shapelib and zlib from cmake install process

- QGCCommon.pri
- android.pri
- qgroundcontrol.pro
I pulled out the qmake changes from #11233 and put them here. This is mostly for anybody doing custom builds so this is probably the last qmake change before switching to cmake entirely.
- ANDROID_VERSION_NAME was being set to the literal string "APP_VERSION_STR"
- Use existing directory variables to clarify file locations
- core-private is still used in qtandroidserialport
Edit: This one isn't all that important
> Qmake: Android fixes

- .github/workflows/android.yml
- CMakeLists.txt
Provides single APK for armv7, arm64v8a
Edit: Times out when building for all of them? (w/ x86, x86_64)
> CI: Android Multi-ABI Build

- src/MissionManager/PlanManager.cc
- src/Vehicle/Vehicle.cc
- src/comm/MockLinkMissionItemHandler.cc
Needed for  #11229
A few mission related messages have changed, and I am not yet sure how to accommodate them. I've defaulted them to 0 for now which is what PX4 has while Ardupilot hasn't implemented the update yet. MAVSDK also initializes them to 0.
> Mavlink: Update submodule

- src/Vehicle/FTPManager.cc
Previously was only working on root paths
> FTPManager: Correctly fill in directory path

- CMakeLists.txt
- src/AnalyzeView/CMakeLists.txt
- src/Audio/AudioOutput.cc
- src/Audio/AudioOutput.h
- src/Audio/CMakeLists.txt
- src/CMakeLists.txt
- src/QGCApplication.cc
- src/QGCApplication.h
- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/QmlControls/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
- src/Vehicle/Vehicle.cc
- test/Audio/CMakeLists.txt
Modernizes AudioOutput with new functionality from [Qt6.6](https://doc-snapshots.qt.io/qt6-6.6/whatsnew66.html#qt-texttospeech-module).
- The queue is now handled internally in the QTextToSpeech object.
- Now available to use from QML.
- No longer dependent on QGCApplication making it an isolated utility available everywhere with a singleton using static methods.
- Inherits from QTextToSpeech making all [functions](https://doc.qt.io/qt-6/qtexttospeech.html) available.
- Makes use of a QHash for faster translations
- Uses InvokeMethod for thread safety
> AudioOutput: Improvements

- .github/workflows/docs_deploy.yml
The docs workflow needs to be rerun after fixing it. This allows us to do so without making a commit that changes the docs directory.
> CI: Allow Docs Deploy on Manual Runs

- libs/CMakeLists.txt
- src/CMakeLists.txt
- src/Camera/CMakeLists.txt
- src/Compression/CMakeLists.txt
- src/Compression/QGCLZMA.cc
- src/Compression/QGCZlib.cc
- src/Compression/QGCZlib.h
- src/Vehicle/CMakeLists.txt
- src/VehicleSetup/CMakeLists.txt
- Moves xz lib integration to Compression.
- Removes a couple unneeded files from the xz qt lib.
- Changes some public linking to private.
- Only link Compression lib where needed.
- Link to zlibstatic
- Capitalize Compression for lib name
- Dont install shared libs
> CMake: Cleanup Compression Linking

- CMakeLists.txt
- libs/CMakeLists.txt
- libs/qmlglsink/CMakeLists.txt
- src/CMakeLists.txt
- src/Joystick/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
- src/VideoReceiver/CMakeLists.txt
- src/VideoReceiver/GStreamer.cc
- src/VideoReceiver/GStreamer.h
- src/VideoReceiver/GstVideoReceiver.cc
- src/VideoReceiver/GstVideoReceiver.h
- src/VideoReceiver/VideoReceiver.h
- src/comm/CMakeLists.txt
SDL isn't needed outside of the joysticks lib
qmlglsink isn't needed outside videoreceiver
Import the external dependencies in the libs where needed
> CMake: Make Some Libs Private

- src/Audio/AudioOutput.cc
- src/Audio/AudioOutput.h
- src/QGCApplication.cc
- src/Vehicle/Vehicle.cc
Apparently some engines don't support volume changes so mute has to be handled independently from volume, which makes more sense anyways.
Also fixes initial mute value and renamed say to read to avoid shadowing QTextToSpeech's say function
> Audio Output: Fix Mute

- .github/workflows/android.yml
- .github/workflows/linux.yml
- .github/workflows/macos_debug.yml
- .github/workflows/macos_release.yml
- .github/workflows/windows.yml
There is not enough cache space to use ccache for everything so just use it for MacOS which takes the longest.
Also temporarily bring MacOS builds up to date until the full cmake conversion.
> CI: Cleanup Workflows

- CMakeLists.txt
It generates a lot of output, so only use it for debug builds.
> CMake: Make Deployment Verbose only for Debug

- .github/workflows/linux.yml
Switches from GCC-9 to GCC-13.
I'm also not entirely sure [Ubuntu 20.04 is officially supported](https://doc.qt.io/qt-6/supported-platforms.html) anymore?
> CI: Linux Build with GNU-13

- deploy/vagrant/.vagrantconfig.yml
- deploy/vagrant/Vagrantfile
Restore Vagrant build / get it working
Description
-----------
Vagrant support was removed, seemingly as some broad build-system changes, which was a little unfortunate.
This PR restores Vagrant support.
Test Steps
-----------
After running
```
VAGRANT_VAGRANTFILE=deploy/vagrant/Vagrantfile vagrant up
```
I can then run
```
/home/pbarker/rc/qgroundcontrol/shadow_build/AppDir/usr/bin/QGroundControl
```
and have that receive data from an ArduPilot SITL instance.
This is useful enough, I think.  I'd prefer to be able to generate AppImage, but there appears to be some issues with generating that on the VM.  I will continue to poke at that; there's a permission error which is relatively easily moved past but then something else <waves hands> pops up.
> Restore Vagrant

- .github/workflows/android.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- cmake/DownloadGStreamer.cmake
- libs/qmlglsink/CMakeLists.txt
- libs/qmlglsink/qt6/gstplugin.cc
- src/FlightMap/QGCVideoBackground.qml
- src/VideoManager/VideoManager.cc
- src/VideoReceiver/CMakeLists.txt
- src/VideoReceiver/VideoReceiver.pri
- Updates GStreamer to 1.22.11 for everything but Linux which will require building by source
- Auto Download GStreamer for Android in CMake instead of CI
- Auto Download Qt6 Plugin for all Platforms
> GStreamer: Update to 1.22.11

- src/VideoReceiver/GstVideoReceiver.cc
Bugfix - Unable to record h.265 video on Android devices.
Description
-----------
Some Android h.264 and h.265 decoders use 'byte stream' as the stream format. The existing code is intended to check for h.264 or h.265 streams and rename the stream format from 'byte stream' to either 'avc' or 'hvc1', which are compatible with the mux components used for the filesink downstream in the pipeline.
The existing code fails by always taking the h.264 option, irrespective of the stream type. This means the 'valve fails to link to the filesink', which means the h.265 stream cannot be recorded on Android devices. The error is caused by using the gst_caps_from_string() function, which effectively just creates a h.264 filter every time.
This fix replaces gst_caps_from_string() with the …
> Using GST structure to confirm video decoding stream format.

- .github/actions/gstreamer/action.yml
- .github/workflows/linux.yml
- tools/setup/ubuntu.sh
Adds an action to build the linux GStreamer. Very minor modifications would be needed to adapt to be able to use with other platforms. 1.24 allows fully static linking.
> CI: Action to Build GStreamer

- cmake/BuildSdl2.cmake
- src/Compression/CMakeLists.txt
- src/GPS/CMakeLists.txt
- src/Geo/CMakeLists.txt
- src/Joystick/CMakeLists.txt
- src/Utilities/CMakeLists.txt
- src/Vehicle/CMakeLists.txt
- src/comm/CMakeLists.txt
Disables a couple more SDL options from being built and adds commented out structures for FetchContent in CMake for more dependencies.
> CMake: FetchContent Improvements

- src/comm/BluetoothLink.cc
- src/comm/BluetoothLink.h
Updates BluetoothLink to use BluetoothConfiguration similar to how the other links do.
> Comms: Fix Bluetooth Configuration Usage

- CMakeLists.txt
Apparently the svg imageformat plugin wasn't included for mac builds
> CMake: Ensure QSvgPlugin is used

- src/ui/toolbar/BatteryIndicator.qml
BatteryIndicator remove duplicate qml Component and add flag for battery percentage availability
Description
-----------
This is a small change that adds the check for the availability of the percentRemaining data of the battery, since it can be unavailable in some autopilot configurations. Since all other values that can be unavailable have the check of the availability on the BatteryIndicator.qml page, same logic is applied for the percentRemaining Fact. In addition, this pull request removes the duplicate batteryValuesAvailableComponent element of type Component, containing all boolean values that define which data is to be displayed. 
Test Steps
-----------
Connect autopilot sending the -1 value of the field _battery_remaining_ in Mavlink BATTERY_STATUS message and check if data is …
> BatteryIndicator remove duplicate qml Component and add flag for battery percentage availability

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/APM/APMResources.qrc
Brings Ardupilot params up to date again. Still need to make this autorun.
Also auto searches for most recent parameters available if vehicle version is higher than the meta data files available.
Previously it would just use the oldest version if the requested one was unavailable.
If the vehicle version is invalid, then search for the oldest available file.
> APM: Update Parameter Repository

- .github/workflows/ios.yml
#11295
Adds iOS release build to CI workflows and uploads .app file.
This required updating the bluetooth link interface and expanding the NO_SERIAL_LINK checks since SerialPort isn't available for iOS. I replaced some mobile checks with NO_SERIAL_LINK when it made sense to, as technically android can use a serial gps if the serial implementation is reworked a bit (which I am working on), but since most androids only have a single serial port you could only do so if you don't already have a comm link via serial.
Edit: I just noticed #10250 and this is something that could be done in the future after my android serial updates
Edit2: Adjusted to just be CI related
> CI: Add iOS Workflow

- libs/libevents/CMakeLists.txt
- libs/libevents/libevents_includes.h
- libs/libevents/logging.cpp
- src/Vehicle/CMakeLists.txt
- src/Vehicle/EventHandler.cc
- src/Vehicle/EventHandler.h
- src/Vehicle/HealthAndArmingCheckReport.cc
- src/Vehicle/HealthAndArmingCheckReport.h
Simplifies the integration a bit. We can also use `ExternalProject_Add` instead of the submodule when removing qmake completely.
> libevents: update submodule

- CMakeLists.txt
Require 6.6.3 because otherwise libQt6QuickControls2Basic.so.6 & libQt6QuickControls2BasicStyleImpl.so.6 are missing.
> CMake: Require Qt Version 6.6.3

- .github/workflows/android.yml
- .github/workflows/linux.yml
Some debug builds were running out of space because of the limited 500MB to CI builds.
> CI: Cleanup to avoid running out of space

- .github/workflows/android.yml
- .github/workflows/linux.yml
The OpenSSL submodule is taking up over 50% of allowed space, so just delete it after cloning repo in linux.
> CI: Free up more space in linux builds

- cmake/Git.cmake
Turn off updating submodules because we no longer use them.
> CMake: Fix Git Usage

- src/CMakeLists.txt
This was why the build was taking so much space
> CMake: Make PCH Private

- src/ui/MainRootWindow.qml
Fix #11432
Hacked version of QGC which exacerbates the problem and shows the fix:
> Toolbar indicator dropdown: Fix position when at extreme right edge

- CMakeLists.txt
- android/src/AndroidInterface.cc
- src/FactSystem/CMakeLists.txt
- src/GPS/CMakeLists.txt
- src/Joystick/CMakeLists.txt
- src/MissionManager/CMakeLists.txt
- src/MissionManager/VisualMissionItem.h
- src/PositionManager/CMakeLists.txt
- src/QGCApplication.cc
- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QGroundControlQmlGlobal.h
- src/VehicleSetup/CMakeLists.txt
- src/comm/CMakeLists.txt
- src/comm/LinkManager.cc
- src/comm/LinkManager.h
- src/comm/QGCSerialPortInfo.cc
- src/comm/QGCSerialPortInfo.h
- src/comm/SerialLink.cc
- src/comm/SerialLink.h
- src/main.cc
Fixes build with QGC_NO_SERIAL_LINK set by expanding usage of NO_SERIAL_LINK to cover remaining serial code. Also Adjusts __ mobile __ macros to NO_SERIAL_LINK where appropriate since iOS builds will always build with NO_SERIAL_LINK but android can use its serial port for the GpsManager. This is necessary before iOS builds will compile.
> Correct NO_SERIAL_LINK Checks

- CMakeLists.txt
- src/FirmwarePlugin/APM/CMakeLists.txt
- src/FirmwarePlugin/PX4/CMakeLists.txt
- src/UTMSP/CMakeLists.txt
- test/CMakeLists.txt
Executable can't find them if they are private to lib, and lib can't find it if is private to executable.
> CMake: Readjust Resource Linking

- src/AutoPilotPlugins/APM/CMakeLists.txt
- src/FirmwarePlugin/APM/CMakeLists.txt
- src/FirmwarePlugin/CMakeLists.txt
- src/FirmwarePlugin/PX4/CMakeLists.txt
When making new libraries for individual firmware plugins, you need to link their factory loaders into the base firmware plugin library.
> CMake: Adjust Firmware Plugin Links

- src/CMakeLists.txt
- src/FactSystem/FactControls/CMakeLists.txt
Resources are being double added because of stuff that remains to work with qmake.
> CMake: Disable Adding Qml Modules For Now

- deploy/vagrant/Vagrantfile
- docs/en/qgc-dev-guide/getting_started/index.md
4594c382639a32dac3a74a7f32f8f1b59f2476d9 failed to update the Vagrantfile for the changed location of the install script.
This updates the Vagrantfile and a random document which also references it.
The Vagrant machine comes up after this change and successfully builds QGC for me.
> Correct path to debian (nee ubuntu) installation script

- src/QGCApplication.cc
- src/QGCApplication.h
- src/QGCToolbox.cc
- src/QmlControls/QGCImageProvider.cc
- src/QmlControls/QGCImageProvider.h
- src/Vehicle/Vehicle.cc
This should be handled entirely by the qmlappengine. There's no reason for it to be in the toolbox.
> Make QGCImageProvider not a Tool

- qgroundcontrol.pro
- test/QGCTest.pri
Since qmake is deprecated, disable unit testing so we can edit tests easier under cmake.
> Disable Unit Testing on qmake

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
Adds methods to the ArduPilot subclass sufficient to activate the existing interface elements.
Tested using ArduCopter in simulation:
> FirmwarePlugin: ArduPilot: Add support for changing ground speed for "Go to Location"

- src/AutoPilotPlugins/APM/APMSensorsComponent.qml
- src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
- src/AutoPilotPlugins/APM/APMSensorsComponentController.h
- src/AutoPilotPlugins/Common/RadioComponentController.cc
- src/AutoPilotPlugins/PX4/PowerComponentController.cc
- src/AutoPilotPlugins/PX4/SensorsComponentController.cc
- src/MAVLink/ImageProtocolManager.h
- src/MAVLink/MAVLinkFTP.h
- src/MAVLink/MAVLinkStreamConfig.h
- src/MAVLink/QGCMAVLink.cc
- src/MAVLink/QGCMAVLink.h
- src/MAVLink/SysStatusSensorInfo.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
This is generic mavlink code and doesn't have to belong to a vehicle type.
> Vehicle: Move Generic Code to MAVLink Module

- .github/workflows/linux.yml
the standard ppa has dropped 13
> CI: Fix linux Installing Build Tools

- .github/workflows/android.yml
CI tests aren't running for android when only the android directory is changed.
> CI: Android Remove Ignore Path

- android/src/AndroidInit.cpp
- src/main.cc
If storage permissions are denied, then it gets stuck in the splashscreen.
> Android: Fix Checking Storage Permissions

- libs/qtandroidserialport/qserialportinfo_android.cpp
Qt doesn't recognize String[] as a jobjectArray for some reason, so provide function signature manually.
> Android: Fix Java Return Type

- .github/workflows/android-macos.yml
- .github/workflows/android-windows.yml
- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows-arm.yml
- .github/workflows/windows.yml
- deploy/docker/Dockerfile-build-ubuntu
- deploy/vagrant/Vagrantfile
- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/Utilities/CMakeLists.txt
- src/Utilities/DeviceInfo.cc
- src/Utilities/DeviceInfo.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- tools/setup/install-qt-debian.sh
Uses available pressure & temperature sensors to adjust altitude offset on drones for long flights using the params BARO_GND_TEMP & BARO_ALT_OFFSET. No current method of enabling, but the logic is there.
> Ardupilot: Add Baro Alt Offset Compensation

- qgroundcontrol.pro
- src/Utilities/DeviceInfo.cc
- src/Utilities/DeviceInfo.h
This fixes:
- tabs instead of spaces
- reordering of variables
- linking in qmake
Fixup after #11538.
> Utilities: fixup warnings and linking

- .github/workflows/android.yml
- .github/workflows/qmake.yml
Create a qmake ci build just to verify builds pass until qmake is dropped entirely. Don't build Android Debug as a multi-ABI (which is pointless if you aren't uploading the APK anyways) to compensate for added build time a bit.
> CI: Create Temporary QMake Build

- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
Overrides aren't marked in function declaration
> Ardupilot: Fix Overrides

- src/Comms/USBBoardInfo.json
- src/VehicleSetup/FirmwareUpgradeController.cc
This adds support for the new JFB110 board of Japan Aviation Electronics Industry Ltd.
sorry, I closed PR by mistake, so I'll post it again.
> Hardware: Add support for JFB110

- src/QtLocationPlugin/BingMapProvider.cpp
- src/QtLocationPlugin/BingMapProvider.h
- src/QtLocationPlugin/ElevationMapProvider.cpp
- src/QtLocationPlugin/ElevationMapProvider.h
- src/QtLocationPlugin/EsriMapProvider.cpp
- src/QtLocationPlugin/EsriMapProvider.h
- src/QtLocationPlugin/GenericMapProvider.cpp
- src/QtLocationPlugin/GenericMapProvider.h
- src/QtLocationPlugin/GoogleMapProvider.cpp
- src/QtLocationPlugin/GoogleMapProvider.h
- src/QtLocationPlugin/MapProvider.cpp
- src/QtLocationPlugin/MapProvider.h
- src/QtLocationPlugin/MapboxMapProvider.cpp
- src/QtLocationPlugin/MapboxMapProvider.h
- src/QtLocationPlugin/QGCMapTileSet.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.h
- src/QtLocationPlugin/QGeoMapReplyQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
- src/Terrain/TerrainTileManager.cc
- src/Viewer3D/Viewer3DTileReply.cc
This consolidates the MapProviders to have much less duplicated code and makes them entirely const.
This required removing the google version check and converting the Google Satellite Maps from the Google Maps to Google Quick Maps Services, which don't require version numbers as they default to the latest available. The only reason we might want to log the version number is to keep cached tiles and downloaded tiles on the same version, but currently all downloaded google tiles are stuck forever on an ancient version. The google version check can be re-added at a later dated if desired (maybe in QGeoTileFetcherQGC), but it serves little purpose currently.
The purpose in doing this is such that the entire UrlEngine can then become a static lookup class, without having to pull definitions …
> QtLocationPlugin: Make MapProvider Functions Const

- src/AutoPilotPlugins/APM/APMRadioComponent.cc
- src/AutoPilotPlugins/AutoPilotPlugin.cc
- src/AutoPilotPlugins/AutoPilotPlugin.h
- src/AutoPilotPlugins/PX4/SensorsComponent.cc
- src/AutoPilotPlugins/PX4/SensorsComponent.h
- src/AutoPilotPlugins/PX4/SensorsComponentSummaryFixedWing.qml
- src/AutoPilotPlugins/PX4/SensorsSetup.qml
- src/VehicleSetup/VehicleComponent.cc
- src/VehicleSetup/VehicleComponent.h
- src/VehicleSetup/VehicleSummary.qml
> Rework PX4 airspeed cal due to parameter name/functionality changes

- docs/.vitepress/config.mjs
- docs/en/qgc-user-guide/index.md
I've removed the gitter and slack links, which I believe to be defunct.
This also fixes a broken link to support in the top toolbar, and adds links to the download pages in that top bar.
Checklist:
----------
> [Docs] Remove gitter/slack links. Add top bar quick download links

- src/Joystick/Joystick.h
Description
-----------
Fix a trivial typo that prevents changing the joystick axis polling frequency.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Fixes #11359
> Joystick: fix typo in _maxAxisFrequencyHz

- .github/workflows/android-macos.yml
- .github/workflows/android-windows.yml
- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
Seems like Qt Tools downloads are the most unreliable part, better to just use native installs I guess
> CI: Remove Qt Tools Downloads

- src/UI/preferences/SerialSettings.qml
Fixes  #10352. The clamping was backwards.
> Qml: Fix Serial Settings

- src/API/CMakeLists.txt
- src/API/QGCCorePlugin.cc
- src/CMakeLists.txt
- src/FlightDisplay/FlightDisplayViewVideo.qml
- src/FlightMap/QGCVideoBackground.qml
- src/Vehicle/Vehicle.cc
The VideoReceiver(s) should only be handled by the VideoManager for thread safety and in order to better support multiple videoreceivers.
The QGCVideoBackround also doesn't use this property.
> VideoReceiver: Remove references outside of VideoManager

- src/Joystick/Joystick.cc
- src/Joystick/JoystickManager.cc
- src/Joystick/JoystickSDL.cc
- src/Joystick/JoystickSDL.h
- Enable proper closing of SDL Joysticks (disabled due to crashes during closing).
- Fix double updating of SDL joysticks each loop of thread.
- Disable SDL Joystick Events if subsystem failed to initialize (probably redundant but whatever).
> Joystick: Fix SDL Closing

- src/FlightDisplay/FlyViewTopRightColumnLayout.qml
- src/FlightDisplay/FlyViewWidgetLayer.qml
- src/FlightDisplay/VirtualJoystick.qml
- src/QmlControls/JoystickThumbPad.qml
Closes #11589
Closes #11511
This commit solves two issues (#11589 & 11511) that were related. At startup, the VirtualJoystick show random axis values (#11589). Additionally, resizing the screen caused the joystick to malfunction, potentially leading to dangerous behavior (#11511). Now, the values remain stable during a resize, and at startup, the joystick initializes at the middle or bottom, depending on the selected settings. Also added logic for ReCenter settings changed during flight which could make something similar as issue (#11589) (if ReCenter is deselected while Joysticks are enabled the starting value will be the center position but without auto centering, instead if auto-center is deselected while Joystick aren't enable the starting position will be at bottom). …
> Rework + Fix for VirtualJoystick (#11589 & 11511)

- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QGroundControlQmlGlobal.h
- src/QtLocationPlugin/BingMapProvider.cpp
- src/QtLocationPlugin/BingMapProvider.h
- src/QtLocationPlugin/ElevationMapProvider.cpp
- src/QtLocationPlugin/ElevationMapProvider.h
- src/QtLocationPlugin/EsriMapProvider.cpp
- src/QtLocationPlugin/EsriMapProvider.h
- src/QtLocationPlugin/GenericMapProvider.h
- src/QtLocationPlugin/GoogleMapProvider.h
- src/QtLocationPlugin/MapProvider.cpp
- src/QtLocationPlugin/MapProvider.h
- src/QtLocationPlugin/MapboxMapProvider.cpp
- src/QtLocationPlugin/MapboxMapProvider.h
- src/QtLocationPlugin/QGCMapEngine.cpp
- src/QtLocationPlugin/QGCMapEngine.h
- src/QtLocationPlugin/QGCMapTileSet.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.h
- src/QtLocationPlugin/QGCTileCacheWorker.cpp
- src/QtLocationPlugin/QGCTileCacheWorker.h
- src/QtLocationPlugin/QGeoMapReplyQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
- src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
- src/Terrain/TerrainTileManager.cc
- src/Viewer3D/Viewer3DTerrainTexture.cc
- src/Viewer3D/Viewer3DTileReply.cc
- Adds the provider name and map id to the MapProvider class and removes their QObject inheritance.
- Completely converts the UrlEngine to a static class.
- Re-adds the esri maps to the list as previously they never got added after entering the token despite the comment.
> QtLocationPlugin: Make UrlEngine Static

- src/Settings/App.SettingsGroup.json
Proof: https://mavlink.io/en/messages/common.html#REQUEST_DATA_STREAM
Description
-----------
MavLink command REQUEST_DATA_STREAM is DEPRECATED: Replaced by MAV_CMD_SET_MESSAGE_INTERVAL. 
So, QGroundControl shouldn't use it by default.
Test Steps
-----------
1. Install QGroundControl on clean machine where it wasn't installed before or wipe QGroundControl saved settings.
2. Go to Application Settings, Telemetry, Stream Rates.
3. See default setting of "Controlled By vehicle" checkbox slider (when it's ON it means REQUEST_DATA_STREAM is disabled).
Checklist:
----------
Related Issue
-----------
#8304 
> Do not REQUEST_DATA_STREAMs by default, since it's deprecated

- src/Vehicle/Vehicle.cc
Description
-----------
Correctly reset the elapsedTimer in the _mavCommandList instead of resetting a temporary copy.
Test Steps
-----------
1. Run any long-running command that sends periodic progress updates.
2. QGC drops the command after 3 seconds anyway.
Checklist:
----------
> Reset mav command timer on MAV_RESULT_IN_PROGRESS

- src/Comms/MockLink/MockLink.cc
- src/Comms/MockLink/MockLink.h
- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.h
- src/FlightDisplay/FlyView.qml
- src/FlightDisplay/GuidedActionsController.qml
- src/FlightDisplay/GuidedValueSlider.qml
- src/QmlControls/ScreenTools.qml
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Fixes #10743
See Issue for details
> Guided value slider

- src/AnalyzeView/CMakeLists.txt
- src/AnalyzeView/LogDownloadController.cc
- src/AnalyzeView/LogEntry.cc
- src/CMakeLists.txt
- src/Camera/CMakeLists.txt
- src/Camera/VehicleCameraControl.cc
- src/QGCApplication.cc
- src/QGCApplication.h
- src/QtLocationPlugin/CMakeLists.txt
- src/QtLocationPlugin/QGCLocationPlugin.pri
- src/QtLocationPlugin/QGCMapEngine.cpp
- src/QtLocationPlugin/QGCMapEngine.h
- src/QtLocationPlugin/QGCMapTileSet.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.h
- src/QtLocationPlugin/QGeoTiledMapQGC.cpp
- src/QtLocationPlugin/QGeoTiledMapQGC.h
- src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
- src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.h
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
Move some functions out of QGCMapEngine to remove unnecessary linking to QGCLocation and to better organize methods with appropriate classes.
> QtLocationPlugin: Move functions out of QGCMapEngine

- qgroundcontrol.pro
- src/Vehicle/FactGroups/CMakeLists.txt
- src/Vehicle/FactGroups/VehicleFactGroup.cc
- src/Vehicle/FactGroups/VehicleFactGroup.h
- src/Vehicle/MultiVehicleManager.cc
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Aggregates remaining Vehicle Facts into their own fact group and makes Vehicle inherit from that factgroup rather than a generic fact group. This should result in the same exact Vehicle class, just with a pseudo separate fact group. Helps clean up Vehicle class a bit. Smaller & easier approach than #11428.
A couple of message handling functions are left in Vehicle for now because they use vehicle signals & private variables, and will require a bit more refactoring.
> Vehicle: Create Fact Group

- qgroundcontrol.pro
- src/API/QGCCorePlugin.cc
- src/Camera/MavlinkCameraControl.h
- src/QGCApplication.cc
- src/Settings/CMakeLists.txt
- src/Settings/VideoSettings.cc
- src/Vehicle/CMakeLists.txt
- src/VideoManager/CMakeLists.txt
- src/VideoManager/SubtitleWriter.cc
- src/VideoManager/SubtitleWriter.h
- src/VideoManager/VideoManager.cc
- src/VideoManager/VideoManager.h
- src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
- src/VideoManager/VideoReceiver/GStreamer/GLVideoItemStub.cc
- src/VideoManager/VideoReceiver/GStreamer/GLVideoItemStub.h
VideoManager had some issues that this addresses. For example, you could not use a UVC device without gstreamer being enabled despite the fact that UVC doesn't use gstreamer. Also the handling of multiple video receivers was never finished and this resolves some of the unfinished work. One particular issue is that the entire video manager was essentially disabled without gstreamer, which makes it impossible to use for custom builds that provide a video sink from a different source (They could override the VideoManager but that is unecessary).
> VideoManager: Fix GStreamer & UVC Setup

- src/PositionManager/CMakeLists.txt
- src/PositionManager/PositionManager.cpp
- src/PositionManager/PositionManager.h
- src/PositionManager/SimulatedPosition.cc
- src/PositionManager/SimulatedPosition.h
- src/Utilities/CMakeLists.txt
- src/Utilities/DeviceInfo.cc
- src/Utilities/DeviceInfo.h
Preps PositionManager to use more positioning sources. I have another PR coming up that preps the GPS module to use external connected gps's (other than base stations for RTK, which is currently the only GPS type supported) for positioning sources. This adds the ability to use QtSensors compass for the heading, but doesn't enable it yet (although in testing it works and shows up in Qml). Also does general code quality improvements.
> PositionManager: Update Sources

- libs/qtandroidserialport/qserialport_android.cpp
- src/Comms/SerialLink.cc
- src/Comms/SerialLink.h
Use the existing baud rate map that is detected per system rather than a hard coded map. Need to adjust for new Android Driver when that is merged.
Closes #10400.
> SerialLink: Use QSerialPortInfo for BaudRate Map

- src/QtLocationPlugin/CMakeLists.txt
- src/QtLocationPlugin/MapProvider.cpp
- src/QtLocationPlugin/QGCLocationPlugin.pri
- src/QtLocationPlugin/QGCMapEngine.cpp
- src/QtLocationPlugin/QGCMapEngine.h
- src/QtLocationPlugin/QGCMapEngineData.h
- src/QtLocationPlugin/QGCMapTileSet.cpp
- src/QtLocationPlugin/QGCMapTileSet.h
- src/QtLocationPlugin/QGCMapUrlEngine.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.h
- src/QtLocationPlugin/QGCTileCacheWorker.cpp
- src/QtLocationPlugin/QGeoFileTileCacheQGC.cpp
- src/QtLocationPlugin/QGeoFileTileCacheQGC.h
- src/QtLocationPlugin/QGeoMapReplyQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.h
- src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
- src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.h
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
- src/Terrain/TerrainTileManager.cc
Provides finer control over the caching and collects most of the cache related functions from the qgcmapengine giving better organization. Remaining qgcmapengine cache functions will be moved later, removing the class entirely. The QGeoTileFetcher/QGeoFileTileCache will be responsible for the TileCacheWorker. Then all mapping/caching related classes will be instantiated through the QGeoServiceProviderPlugin and be completely independent from the rest of the qgcApp making it easier to test independently.
> QtLocationPlugin: Add QGeoFileTileCache Implementation

- src/FactSystem/FactMetaData.cc
- src/QGCApplication.cc
- src/Settings/App.SettingsGroup.json
- src/Settings/AppSettings.cc
- src/Settings/AppSettings.h
- src/Settings/RemoteID.SettingsGroup.json
There were multiple problem here all star6ing from the fact the we had QLocale::Language ids stored in a json file. This is now set up in code such so that things don't get screwed up. Also added much more validation along the way that the right things are happening.
While testing this I discovered a number of problems with the Chinese json translations where the enum commands which changed to a Chinese char. Hence the string split for them was failing. Luckily most had already been fixed up in Crowdin and I just approved them And then fixed the missing ones.
Closes  #11541
> Select language fixes

- src/FlightDisplay/GuidedValueSlider.qml
Horizontal scroll indicator was showing up when width change due to larger numbers
> Guided Action Slider: Limit flickable to vertical scrolling

- src/Settings/RemoteID.SettingsGroup.json
It is very confusing when the "Fixed" option just seemingly doesn't work when you select it. Therefore, we should at least add this note.
Closes https://github.com/mavlink/qgroundcontrol/issues/11673.
> RemoteID: add note that Fixed only works in EU

- src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
VideoReceiver: provide GLVideoItemStub.h in public library interface if gstreamer is missing or Qt6 plugin wasn't found
Description
-----------
Currently, build is failing due to GLVideoItemStub.h being included in VideoManager.cc:
```
#ifdef QGC_GST_STREAMING
#include "GStreamer.h"
#include "VideoDecoderOptions.h"
#else
#include "GLVideoItemStub.h"
#endif
```
This header file is expected to be provided by VideoReceiver::GStreamer library. However, this library is not built at all due to early return statement in its CMakeLists.txt:
```
if(NOT GST_QT6_PLUGIN_FOUND)
return()
endif()
```
I have fixed it by still building this library (with a single GLVideoItemStub.h) file.
Test Steps
-----------
I have tested it by successfully building and launching QGroundControl without gstreamer in …
> Fix build without gstreamer or without Qt6 gstreamer plugin

- src/QmlControls/PipView.qml
Previously too small of a target. New target is full size of resize icon.
Fix #11699
> Fix resize MouseArea sizing, dragging

- docs/.vitepress/config.mjs
Website currently shows 4.3 instead of 4.4, not sure if this is the correct way to update this or not.
> Docs: Update Release Version to v4.4

- src/UI/MainRootWindow.qml
- src/main.cc
Fix the fact that you needed to Command-Q twice to get QGC to close
> OSX: Fix app close

- cmake/BuildGstQtPlugin.cmake
Generally it's better to avoid glob but this makes it easier to support different gstreamer versions
> CMake: Fix gstqtplugin building for different versions

- .github/workflows/windows.yml
The link on the website wasn't working because of the installer name
> CI: Fix installer name

- src/Gimbal/GimbalController.cc
- src/Gimbal/GimbalController.h
This includes several gimbal fixes. For more information, please check the individual commit descriptions.
Fixes #11686.
> [v4.4] Gimbal fixes

- docs/en/qgc-dev-guide/tools/index.md
- docs/ko/qgc-dev-guide/tools/index.md
- docs/tr/qgc-dev-guide/tools/index.md
Mocklink is included in debug builds, not daily builds
> Docs: Fix Mocklink Description

- docs/en/qgc-dev-guide/getting_started/index.md
Updated config for android for current versions : Jdk11 has been outdated for QT.6.6.3, and is only recommended for Qt 5.15.2
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Addroid Config Update: index.md

- CMakeLists.txt
These are already installed automatically when they are linked to the project sources
> CMake: Remove Duplicate Install of Resources

- src/QtLocationPlugin/BingMapProvider.h
- src/QtLocationPlugin/ElevationMapProvider.cpp
- src/QtLocationPlugin/ElevationMapProvider.h
- src/QtLocationPlugin/EsriMapProvider.cpp
- src/QtLocationPlugin/EsriMapProvider.h
- src/QtLocationPlugin/MapProvider.cpp
- src/QtLocationPlugin/MapProvider.h
- src/QtLocationPlugin/QGCCachedTileSet.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.cpp
- src/QtLocationPlugin/QGCMapUrlEngine.h
- src/QtLocationPlugin/QGeoMapReplyQGC.cpp
- src/QtLocationPlugin/QGeoMapReplyQGC.h
- src/QtLocationPlugin/QGeoServiceProviderPluginQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.h
- src/Terrain/TerrainTileManager.cc
- src/Terrain/TerrainTileManager.h
- src/Viewer3D/Viewer3DTileReply.cc
Updates the QGeoMapReplyQGC implementation to be more agnostic to the being used for altitude and tiles, and create the network requests in the tilefetcher instead of the map providers
> QtLocationPlugin: Update QGeoMapReplyQGC

- src/FlightDisplay/FlyViewWidgetLayer.qml
- src/FlightDisplay/VirtualJoystick.qml
- src/QmlControls/JoystickThumbPad.qml
Fixes #11687. On large screens, the joystick could appear off-screen. Additionally, the reCenter offset has been improved for small screens. Now, there is more offset on the side that is near the center, as there are no widgets there and is more easy to get there with the thumbs, the offset of the side next to the screen boundaries has been decreased.
> Fix for #11687 (Joystick out of screen) + misclick

- src/FlightDisplay/FlyViewMap.qml
Fix #8092
Fly View click in map:
> Fly View: Show lat/lon of click position

- src/MissionManager/MissionController.cc
In plan view, when selecting a mission item which is a child item ( on the right mission item view flickable for example ), the child item gets set as current item, and thus the parent gets highlighted in the map, as expected.
However, from there, when selecting a different current mission item, the previous highlighted ( parent of the previous selected mission item ) does not get cleared. If repeating this process, we end up with a lot of falsely highlighted items on the map.
This happens because we were forgetting to clear the hasCurrentChildItem property. This commit fixes this.
> MissionController.cc: fix bug current mission item not clearing:

- src/FirmwarePlugin/PX4/PX4FlightModeIndicator.qml
- src/FlightMap/MapItems/VehicleMapItem.qml
- src/MissionManager/KMLPlanDomDocument.cc
- src/PlanView/FWLandingPatternMapVisual.qml
- src/PlanView/PlanToolBarIndicators.qml
- src/PlanView/StructureScanEditor.qml
- src/PlanView/TerrainStatus.qml
Fix terrain status vertical unit string
Description
-----------
If a user has different units for vertical/height, then the terrain status would incorrectly show the wrong Height ASML unit string.
The change is self-explanatory. 
Test Steps
-----------
- Have different units for vertical and horizontal.
- Open up plan view
- Look at terrain status
Checklist:
----------
> Fix terrain status vertical unit string

- src/Vehicle/Actuators/ActuatorTesting.cc
On first startup a null pointer is dereferenced, this protects against that.
```
Thread 1 "QGroundControl" received signal SIGSEGV, Segmentation fault.
0x00007ffff4b93889 in QObject::deleteLater() () from /usr/lib/libQt6Core.so.6
(gdb) bt
#0  0x00007ffff4b93889 in QObject::deleteLater() () from /usr/lib/libQt6Core.so.6
#1  0x0000555555d51c4e in ActuatorTesting::ActuatorTest::updateFunctions (this=0x55555db54490, actuators=...)
at /project/source/src/Vehicle/Actuators/ActuatorTesting.cc:34
#2  0x0000555555d1f843 in Actuators::parametersChanged (this=0x55555db54430) at /project/source/src/Vehicle/Actuators/Actuators.cc:241
```
> Prevent a NPE when starting up

- src/Comms/USBBoardInfo.json
- src/VehicleSetup/FirmwareUpgradeController.cc
Description
-----------
This addition will help with this new board revision (under 3DR's brand) and the following new 3DR boards being recognized by QGC. 
3DR Control Zero H7 OEM Rev G is a board already working with Ardupilot Repos and a PR for PX4 is soon to be released (no later than this weekend).
> Hardware: Add support for 3DR Control Zero H7 OEM Rev G

- src/MissionManager/SurveyComplexItem.cc
I discovered this trying to override it from a custom plugin. Is this still neccesary? @julianoes could you confirm something like this is needed for PX4, in order to address it differently? It avoids setting a different default from a custom plugin. Thanks!
> SurveyComplexItem: remove px4 hack overriding default turnaround distance

- src/Settings/App.SettingsGroup.json
Reverts mavlink/qgroundcontrol#11531
Need a better solution due to Copter not initiating streams automatically
> Revert "Do not REQUEST_DATA_STREAMs by default, since it's deprecated"

- src/Comms/USBBoardInfo.json
Unable to parse board info json: "object is missing after a comma"
> Comms: Fix Extra Comma in BoardInfo json

- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QmlObjectListModel.h
- src/QtLocationPlugin/CMakeLists.txt
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h
Remove a couple unused signals
Use Application Instance instead of Toolbox for QGCMapEngineManager instance to further separate location plugin from core code & reduce linking/dependencies
Perform code quality maintenance
> QtLocationPlugin: Update QGCMapEngineManager

- cmake/CustomOptions.cmake
- custom-example/CMakeLists.txt
- custom-example/cmake/CustomOverrides.cmake
- src/AutoPilotPlugins/APM/CMakeLists.txt
- src/FirmwarePlugin/CMakeLists.txt
> CMake: Custom Build Fixes

- src/GPS/CMakeLists.txt
Fetch PX4-GPSDrivers through CMake. Had to add an empty folder to get the include path working
> CMake: Fetch PX4-GPSDrivers

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- deploy/installer/README.md
[](url)
Description
-----------
I noticed the "Discussion/Support" link in the root README.md had an outdated link. I fixed all occurances of the outdated link. 
https://github.com/user-attachments/assets/e2cf9ffd-069b-4af1-ae9f-3d30020b74b2
There was also a broken link should have been a link to a different page. In this video I show a fix for the broken link, and then the actual link that it is changed to in this PR (the "Console Logging" page instead of the "Reporting Bugs" page)
https://github.com/user-attachments/assets/3bc708b0-d752-4b33-8287-4e44721f8bd0
> Fix broken support links

- test/QmlControls/QmlTest.qml
> Fix light/dark toggle button on "Palette Test" page

- test/FactSystem/ParameterManagerTest.cc
- test/FactSystem/ParameterManagerTest.h
This test causes a segfault and prevents the remaining tests to finish. Disable it until that is fixed
> Test: Temporarily disable test causing segfault

- CMakeLists.txt
- src/Geo/CMakeLists.txt
- test/Geo/GeoTest.cc
- test/UnitTestList.cc
- tools/setup/install-dependencies-debian.sh
Seems like the geographiclib package has a different name depending on debian version, so account for installing each and linking them instead of building if possible.
> Geo: Re-enable Test

- .github/actions/upload/action.yml
Prevents aws upload attempts on CI of forks so that builds don't fail incorrectly
> CI: Don't try to upload to AWS from forks

- src/QtLocationPlugin/ElevationMapProvider.cpp
- src/Terrain/CMakeLists.txt
- src/Terrain/TerrainQuery.cc
- src/Terrain/TerrainQuery.h
- src/Terrain/TerrainQueryAirMap.cc
- src/Terrain/TerrainQueryAirMap.h
- src/Terrain/TerrainQueryInterface.cc
- src/Terrain/TerrainQueryInterface.h
- src/Terrain/TerrainTile.cc
- src/Terrain/TerrainTile.h
- src/Terrain/TerrainTileCopernicus.cc
- src/Terrain/TerrainTileCopernicus.h
- src/Terrain/TerrainTileManager.cc
- src/Terrain/TerrainTileManager.h
- test/Terrain/TerrainQueryTest.cc
- test/Terrain/TerrainQueryTest.h
- test/UnitTestList.cc
Clean up and better structure Terrain files in prep for #11795
Fixes some QObject parenting
Finishes setting up unit tests
> Terrain: Cleanup Terrain Queries

- src/ADSB/ADSB.h
- src/ADSB/ADSBTCPLink.cc
- src/ADSB/ADSBTCPLink.h
- src/ADSB/ADSBVehicle.cc
- src/ADSB/ADSBVehicle.h
- src/ADSB/ADSBVehicleManager.cc
- src/ADSB/ADSBVehicleManager.h
- src/ADSB/CMakeLists.txt
- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/QmlControls/QGroundControlQmlGlobal.cc
- src/Settings/ADSBVehicleManager.SettingsGroup.json
- src/Vehicle/Vehicle.cc
- test/ADSB/ADSBTest.cc
- test/ADSB/ADSBTest.h
- test/ADSB/ADSB_Simulator.py
- test/ADSB/CMakeLists.txt
- test/CMakeLists.txt
- test/UnitTestList.cc
Creates a unit test for ADSB
Remove need for restarting app when changing ADSB enabled setting
Better handling of TCPLink state
Change from Tool to Application Static to reduce linking and make better isolated/testable module
General code quality improvements
> ADSB: Add Unit Test

- src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
- src/Vehicle/FactGroups/SubmarineFact.json
Surftrak (range hold) mode (https://github.com/ArduPilot/ardupilot/pull/23435) has been merged in ArduSub, and will release with ArduSub 4.5. This PR adds support for surftrak mode.
> Add support for surftrak (range hold) mode

- src/QmlControls/QGCButton.qml
- src/QmlControls/QGCPopupDialog.qml
- src/QmlControls/QGCSimpleMessageDialog.qml
- src/UI/preferences/GeneralSettings.qml
Fixes a couple sizing bugs and makes button sizing/spacing look better
i gave buttons larger left/right padding and minimum sizes in accordance with the Google material design 2 design doc
> Sizing Fixes (buttons, popups, etc)

- src/QmlControls/QGCButton.qml
- src/QmlControls/QGCPopupDialog.qml
- src/VideoManager/VideoReceiver/GStreamer/README.md
This PR has 3 commits
1. Fixes hover radius
2. Fix size of some buttons
3. Fix outdated disable-GStreamer docs
> Button and docs fixes

- src/Vehicle/Vehicle.cc
* Mocklink send the message for MAV_CMD_REQUEST_MESSAGE before the ack for the command is sent
* QGC has code to handle this order of things happening but wasn't cleaning things up correctly in this case. This causing random memory to be written to and causing crashes.
> Fix crash when using MockLinks

- src/Settings/VideoSettings.cc
Fixes the following error caused by android also defining Q_OS_LINUX:
W QGroundControl_Daily: Value does not exist in fact: QVariant(int, 5)
> Settings: Fix Video Decode List for Android

- src/QmlControls/QGCPopupDialog.qml
Fix bug with Popup enter-key handling
If the event that triggered a Popup to open was an enter key being pressed, the Popup would immediately close because it would handle the onRelease of the press when it should listen to the onPressed. as with typing, it is expected that key strokes have an affect on press, not on release.
https://github.com/user-attachments/assets/5bcdae1c-2367-4103-9d6c-c5c7c6a627c1
@
https://github.com/user-attachments/assets/03a290da-a94c-4dac-9521-70f9dcbc9ff6
> Fix bug with Popup enter-key handling

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.cc
- src/FirmwarePlugin/FirmwarePlugin.h
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
- src/FlightDisplay/FlyViewMap.qml
- src/FlightDisplay/GuidedActionsController.qml
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Adds ability to change heading towards location on map, currently only for ardupilot (sub/copter)
> Vehicle: Add Change Heading

- .github/workflows/android-windows.yml
There is some issue, probably related to windows vs unix text encoding, that is causing the signing key to be incorrect. Doesn't matter in this case as we are not uploading these builds.
> CI: Dont Sign Android Windows For Now

- CMakeLists.txt
Cleans up the build dir a bit. Also includes minor fix for windows cmake
> CMake: Move Translations Output To Own Folder

- src/FlightDisplay/FlightDisplayViewVideo.qml
- src/Settings/Video.SettingsGroup.json
The enum values were opposite of how it was used in the code (hide is 1 but 1 enables gridlines). So just switch to a standard bool
> Settings: Fix Video Grid Lines

- src/QmlControls/HorizontalFactValueGrid.qml
- src/QmlControls/InstrumentValueEditDialog.qml
- src/QmlControls/QGCButton.qml
- src/QmlControls/QGCRadioButton.qml
- src/QmlControls/SettingsGroupLayout.qml
This PR has 2 commits
1. Fix button sizes in TelemetryValuesBar
* In QGC 4.4.2 these buttons look fine, but in the master branch they were super squashed looking
2. Organize "Value Display" so it is more scannable
* Now it is organized with keys on the left and values/inputs on the right, making the form more intuitive and scannable for first time users.
* The design of the form is now more similar to other parts of QGC, namely the views seen in "Application Settings"
https://github.com/user-attachments/assets/92304f65-fdee-4206-aab8-cc6e3ed7a0cc
https://github.com/user-attachments/assets/52c2dd33-761a-4f0a-8083-f2ba0afa5228
> "Value Display" update

- src/Comms/BluetoothLink.cc
- src/Comms/BluetoothLink.h
- src/Comms/LinkConfiguration.cc
- src/Comms/LinkConfiguration.h
- src/Comms/LinkInterface.h
- src/Comms/LinkManager.cc
- src/Comms/LinkManager.h
- src/Comms/LogReplayLink.cc
- src/Comms/LogReplayLink.h
- src/Comms/MAVLinkProtocol.cc
- src/Comms/MockLink/MockLink.cc
- src/Comms/MockLink/MockLink.h
- src/Comms/SerialLink.cc
- src/Comms/SerialLink.h
- src/Comms/TCPLink.cc
- src/Comms/TCPLink.h
- src/Comms/UDPLink.cc
- src/Comms/UDPLink.h
- src/QmlControls/QmlObjectListModel.h
- test/qgcunittest/UnitTest.cc
This is an effort to cleanup LinkManager before fixing link interface threading
Also resolves various missing overrides and const correctness
No logical or functional changes yet
> Comms: Fixup LinkManager

- custom-example/qgcresources.qrc
- qgcresources.qrc
- resources/terrain.svg
- src/FlightMap/MapScale.qml
Makes so the button used to expand/collapse the terrain panel has an icon instead of the letter "T"
> Use icon for terrain button instead of "T"

- src/PlanView/TerrainStatus.qml
When the theme was set to outdoor mode, the terrain chart's lines/labels weren't ledgible colors. This fixes that
> Fix terrain chart colors

- CMakeLists.txt
This recent PR seems to have broken translation file imports. 
https://github.com/mavlink/qgroundcontrol/pull/11912
I'm just reverting it back to what it was before.
> Fix Translations Import Path

- src/QtLocationPlugin/QGCCachedTileSet.cpp
- src/QtLocationPlugin/QGCCachedTileSet.h
- src/QtLocationPlugin/QGCMapEngine.cpp
- src/QtLocationPlugin/QGCMapEngine.h
- src/QtLocationPlugin/QGeoFileTileCacheQGC.cpp
- src/QtLocationPlugin/QGeoFileTileCacheQGC.h
- src/QtLocationPlugin/QGeoMapReplyQGC.cpp
- src/QtLocationPlugin/QGeoMapReplyQGC.h
- src/QtLocationPlugin/QGeoServiceProviderPluginQGC.cpp
- src/QtLocationPlugin/QGeoServiceProviderPluginQGC.h
- src/QtLocationPlugin/QGeoTileFetcherQGC.cpp
- src/QtLocationPlugin/QGeoTileFetcherQGC.h
- src/QtLocationPlugin/QGeoTiledMapQGC.cpp
- src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp
- src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.h
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.cc
- src/QtLocationPlugin/QMLControl/QGCMapEngineManager.h
- Move remaining file caching related stuff to QGeoFileTileCacheQGC to prep converting QGCMapEngine to a better threadWorker handler for  QGCCacheWorker
- Reduce total count of QNetworkAccessManager's, which each create a new thread per instance
- Translate output errors
- Network caching
> QtLocationPlugin: Minor Miscellaneous Improvements

- README.md
- docs/en/qgc-dev-guide/contribute/licences.md
- docs/en/qgc-dev-guide/getting_started/index.md
- docs/en/qgc-dev-guide/index.md
- docs/ko/qgc-dev-guide/contribute/licences.md
- docs/ko/qgc-dev-guide/getting_started/index.md
- docs/ko/qgc-dev-guide/index.md
- docs/tr/qgc-dev-guide/contribute/licences.md
- docs/tr/qgc-dev-guide/getting_started/index.md
- docs/tr/qgc-dev-guide/index.md
- docs/zh/qgc-dev-guide/contribute/licences.md
- docs/zh/qgc-dev-guide/getting_started/index.md
- docs/zh/qgc-dev-guide/index.md
Description
-----------
Commit b6a990dfda17567a92e7ee6d0d8e0ab6439324d2 moved the location of bunch of files such as `COPYING.md`, `CONTRIBUTING.md`, etc. This PR adjusts sources to changes.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update broken references

- CMakeLists.txt
- src/VideoManager/VideoReceiver/QtMultimedia/CMakeLists.txt
Apparently there is an occasional issue for some catching all dependencies if you don't find them all in the root cmakelists. Also, disable QtMultimedia receiver backend by default until it is stable.
> CMake: Find all packages in root CMakeLists.txt

- .github/workflows/macos.yml
- cmake/find-modules/FindLibExiv2.cmake
- src/AnalyzeView/CMakeLists.txt
- src/AnalyzeView/ExifParser.cc
- src/AnalyzeView/ExifParser.h
- test/AnalyzeView/CMakeLists.txt
- tools/setup/install-dependencies-debian.sh
Follow up to #11906
This had been replaced by Exiv2 entirely now since easyexif only does reading.
Future work is to enable XMP compatibility which is easy for linux/mac but requires an external Expat build for Windows & Android. Use package manager like conan or consider simpler library like https://github.com/libexif/libexif.
Alternative to exiv2: https://github.com/AcademySoftwareFoundation/OpenImageIO
> AnalyzeView: Remove easyexif lib

- .gitmodules
Remove Android OpenSSL submodule as it is not used and it takes up a massive amount of space. Offline builds should just copy the necessary libraries rather than downloading hundreds of MB. This was part of the reason CI builds would run out of space.
> Android: Remove OpenSSL Submodule

- src/FactSystem/FactMetaData.cc
- src/QmlControls/InstrumentValueEditDialog.qml
`enumStrings` and `enumValues` are not supposed to have leading/trailing whitespace on individual values. They should look like this `"foo,bar,baz"`. But when these are translated in Crowdin, translators have a tendency to change them to `"foo, bar, baz"` which leads the incorrect/bad ui. To prevent this they are now stripped of leading/trailing whitespace when the json is loaded.
> FactMetaData: Trim enum strings of leading/tailing whitespace

- src/AutoPilotPlugins/PX4/PowerComponentController.cc
Fixing bug where more popups open when relaunching ESC calibration
Description
-----------
Tested with px4.
Launching ESC calibration without battery status fails the `check_battery_disconnect()` in `src/modules/commander/esc_calibration.cpp` (px4-autopilot)
`Disconnect battery and try again` status is sent.
but QGC does not unsubscribe `_handleVehicleTextMessage` because `_stopCalibration` is not called (early exit)
->  causes stacking of popups the more we run ESC calibration
Test Steps
-----------
Launch ESC calibration without battery status for FC (eg no battery, FC powered by directly).
An error message appears: "Disconnect battery and try again"
Relaunch again
Same error message, this time only a single popup (because `_stopCalibration` unsubscribes `_handleVehicleTextMessage`) …
> bugfix: Stop calibration when disconnect battery is received

- test/ADSB/ADSB_Simulator.py
Description
-----------
This pull request addresses the issue where vehicles were not appearing on the map in QGroundControl when using the ADSB_Simulator.py script. The script has been updated to correctly generate and send ADS-B messages.
Checklist:
----------
Related Issue
-----------
Fixes #12002 - ADSB_Simulator.py Script Not Generating Vehicles on the Map
> Fix ADSB_Simulator.py to generate vehicles on the map (#12002)

- src/FactSystem/FactControls/LabelledFactTextField.qml
- src/QmlControls/ParameterEditorDialog.qml
- src/QmlControls/SettingsGroupLayout.qml
- src/Settings/RemoteID.SettingsGroup.json
- src/UI/preferences/RemoteIDSettings.qml
- src/UI/toolbar/RemoteIDIndicatorPage.qml
- src/Vehicle/RemoteIDManager.cc
This should be a UI only change as opposed to a functional change. It is also mostly just a stylistic changes as opposed to any user model changes. Things should work the same behind the scenes. The older style UI is currently left as still available from App Settings.
Validation reporting in the ui is not yet supported. There are a bunch of problems with the way validation in the current codebase is split across C++ code and qml code. To fix correctly it's going to require some fairly involved changes. That will come in a subsequent pull.
This is a replacement for #11228.
> Rework Remote ID settings to new style

- src/Vehicle/Vehicle.h
Closes https://github.com/mavlink/qgroundcontrol/issues/11957
**Before**
```
qrc:/qml/ActuatorComponent.qml:206:33: QML Connections: Cannot assign to non-existent property "onHadFailureChanged"
qrc:/qml/ActuatorComponent.qml:36: TypeError: Cannot read property 'groups' of undefined
qrc:/qml/ActuatorComponent.qml:38: TypeError: Cannot read property 'title' of undefined
qrc:/qml/ActuatorComponent.qml:45: TypeError: Cannot read property 'helpUrl' of undefined
qrc:/qml/ActuatorComponent.qml:43: TypeError: Cannot read property 'helpUrl' of undefined
qrc:/qml/ActuatorComponent.qml:57: TypeError: Cannot read property 'groups' of undefined
qrc:/qml/ActuatorComponent.qml:69: TypeError: Cannot read property 'groups' of undefined
qrc:/qml/ActuatorComponent.qml:162:21: Unable to assign [undefined] to …
```
> Vehicle: fix actuators page 

- .github/actions/upload/action.yml
This should upload commits to master to a continuous release making it easy for people to download daily builds
> CI: Create Continuous Prerelease

- src/AutoPilotPlugins/APM/APMAirframeComponentController.cc
- src/AutoPilotPlugins/PX4/AirframeComponentController.cc
The application will crash when you select an Airframe. This is because the overrideCursor is nullptr
https://doc.qt.io/qt-6/qguiapplication.html#overrideCursor
> PX4: Airframe: fix application crash when selecting Airframe type

- src/MAVLink/StatusTextHandler.cc
- src/MAVLink/StatusTextHandler.h
- src/Vehicle/Vehicle.cc
- test/MAVLink/StatusTextHandlerTest.cc
This is a replacement for #11990. I was crazy hard to get my head around all the back and forth of status text between vehicle and StatusTextHandler. So I created the most minimal set of changes I could come up with to fix the problem. I tested it and it works as far as I can tell.
The basic idea is that status text which flows through the system should not be html escaped until the very last place when it needs to be output to a rich text control. This is critical vehicle error popups and the message indicator dropdown. Status text which flows from Vehicle should raw for people connecting to that signaling.
@stepan14511 Can you test as well.
> Status text html escaping in wrong place

- .github/actions/gstreamer/action.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- cmake/CreateAppImage.cmake
- cmake/find-modules/FindGStreamer.cmake
- deploy/linux/AppRun
- src/VideoManager/VideoReceiver/GStreamer/GStreamer.cc
- src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt
- tools/setup/install-dependencies-debian.sh
> Linux: Improve GStreamer Dependencies

- .github/actions/playstore/action.yml
- .github/workflows/android-linux.yml
Closes #11989
Can't finish or test until dronecode android play store account is created
> CI: Create Android Play Store Action

- src/QtLocationPlugin/QGCCachedTileSet.cpp
- src/QtLocationPlugin/QGCCachedTileSet.h
Fix issue with cached tile set download cancelation
Description
-----------
Cancel download did not cancel download. It just set "downloading" flag to "false". This fix resolves this issue.
Test Steps
-----------
I have tested it locally, on release build, by starting offline map download and stopping it
Checklist:
----------
> Fix issue with cached tile set download cancelation

- CMakeLists.txt
- src/API/QGCCorePlugin.cc
- src/Camera/QGCCameraManager.cc
- src/Joystick/CMakeLists.txt
- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
- src/Joystick/JoystickAndroid.cc
- src/Joystick/JoystickAndroid.h
- src/Joystick/JoystickManager.cc
- src/Joystick/JoystickManager.h
- src/Joystick/JoystickSDL.h
- src/QGCApplication.cc
- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/Vehicle/MultiVehicleManager.cc
- src/Vehicle/MultiVehicleManager.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- src/VehicleSetup/JoystickConfigController.cc
- src/VehicleSetup/JoystickConfigController.h
Convert JoystickManager from a Tool to a Singleton as discussed in toolbox vs singleton instances convo
> Joystick: Convert Manager from Tool To Singleton

- src/FlightDisplay/FlightDisplayViewVideo.qml
Fixes #11896 
The wrong ratio was being used for GST video (if the video stream aspect ratio did not match the operator provided aspect ratio). This made so thinngs like grid lines weren't properly placed and also made track point setting inaccurate.
Note how the grid lines are not accurately placed and the video does not fill the width of the screen even though it is in "Fit Width" mode.
I generated the sample image using the following command
```
gst-launch-1.0 videotestsrc ! openh264enc ! rtph264pay config-interval=10 pt=96 ! udpsink host=127.0.0.1 port=5600
```
My QGC settings were "Fit Width" in video settings and I made video streaming enabled for h264 port 5600
Note how the grid lines are accurately …
> Use correct aspectRation for gst video

- src/Utilities/QGCCachedFileDownload.cc
- src/Utilities/QGCCachedFileDownload.h
- src/Utilities/QGCFileDownload.cc
- src/Utilities/QGCFileDownload.h
- src/Vehicle/Components/ComponentInformationManager.cc
- test/CMakeLists.txt
- test/UnitTestList.cc
- test/Utilities/CMakeLists.txt
- test/Utilities/QGCFileDownloadTest.cc
- test/Utilities/QGCFileDownloadTest.h
- test/Vehicle/Components/ComponentInformationTranslationTest.cc
Remove QNetworkAccessManager inheritance
Fix Slots declaration
Improve debugging
Add Unit Test Structure - don't enable yet, figure out internet during unit tests?
> Utilities: Cleanup File Download Classes

- src/Joystick/Joystick.h
- src/QmlControls/CustomAction.cc
- src/QmlControls/CustomAction.h
- src/QmlControls/CustomActionManager.cc
- src/QmlControls/CustomActionManager.h
- src/QmlControls/EditPositionDialogController.cc
- src/QmlControls/EditPositionDialogController.h
- src/QmlControls/ParameterEditorController.cc
- src/QmlControls/ParameterEditorController.h
- src/QmlControls/QGCFileDialogController.cc
- src/QmlControls/QGCFileDialogController.h
- src/QmlControls/RCChannelMonitorController.cc
- src/QmlControls/RCChannelMonitorController.h
- src/QmlControls/RCToParamDialogController.cc
- src/QmlControls/RCToParamDialogController.h
- src/QmlControls/ScreenToolsController.cc
- src/QmlControls/ScreenToolsController.h
Adds missing parenting to several classes
> QmlControls: Fix Parenting of Several Classes

- src/PlanView/SimpleItemMapVisual.qml
When video streaming was enabled, toggling between mini video and full screen video mode would make the circles representing loiter circles on the flight path disappear. This PR fixes that issue.
1. open a PX4 plane sim. ex
```
cd PX4-Autopilot
make px4_sitl gazebo-classic_plane_lidar
```
2. Open QGC daily
3. create a mission with a loiter waypoint.
4. upload the mission to the vehicle and go to Fly view
5. switch to big video mode
6. switch back to Big map mode
Notice how the loiter circle has collapsed. This is the bug that is fixed. With the fix in this PR the loiter circle properly reappears when toggling the video from mini to full screen.
> Fix disappearing loiter circles

- src/Comms/TCPLink.cc
- src/Comms/TCPLink.h
Related to https://github.com/mavlink/qgroundcontrol/issues/11598
Since every link type will have to be updated at the same time when the inheritance is moved from QThread to QObject, this is a PR to prepare everything else to simplify that change.
> Comms: Prepare TCP for Threading Changes

- src/Comms/LinkManager.cc
- src/Comms/TCPLink.cc
- src/Comms/TCPLink.h
Create TCP Link Worker Thread: Follow up to #11740
> Comms: TCPLink Threading Updates

- src/VehicleSetup/FirmwareUpgradeController.cc
- src/comm/USBBoardInfo.json
This is a backport to add the ARK FPV flight controller into 4.4.
> [BACKPORT] boards:  add ARK FPV

- src/comm/USBBoardInfo.json
This is a backport for #12050.
> This PR should fix the issue with mRo boards (using PX4) not connecting to QGC through Auto-Connect.
> [BACKPORT V4.4] USBBoardInfo.json: Adding missing mRo boards to be detected by Auto-Connect (PX4)

- src/Utilities/Compression/QGCZlib.cc
- src/Utilities/Compression/QGCZlib.h
Return value of -5/Z_BUF_ERROR originally broke the while loop, but should really continue. Caused by larger file downloads
> Utilities: Fix decompression of firmware downloads

- docs/en/qgc-dev-guide/getting_started/container.md
script name is wrong
Description
-----------
file name in the source is different than in the command
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Docs: fix container build script command

- docs/en/qgc-dev-guide/getting_started/container.md
Edit container build and run command for consistency and preventing confusion.
Description
-----------
`./deploy/docker/run-docker.sh` this script creates container under the name of "qgc-ubuntu-docker" using the Dockerfile `/qgroundcontrol/deploy/docker/Dockerfile-build-ubuntu`. Instructions for manually creating the container uses the same Dockerfile but names the container differently as "qgc-linux-docker".
Two different methods for creating and running the same container names it differently.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Docs: Update container.md

- src/FlightDisplay/FlightDisplayViewVideo.qml
- src/Settings/Video.SettingsGroup.json
The pre-existing video fit option "Stretch" would not fill the screen as expected. The grid lines were also not
accurately placed over the video.
"Stretch" is also not a great word to use because it hints the video may be transformed in a way were
its aspectRatio is different from the original, which is not the case.
This PR renames "Stretch" to "Fit" and fixes it so the video fills the screen when in that mode. A new mode was also added called "No Crop" which makes so the entire video is shown (no part of video goes past the bounds of the border of the screen, as would be the case in the other 3 video fit modes if the video width/height aspect ratio does not match the QGC app window width/height aspect ratio
Steps to reproduce
1. Run a vehicle
```
cd PX4-Autopilot
make px4_sitl …
```
> Update video fit options

- src/PlanView/FWLandingPatternEditor.qml
- src/PlanView/FWLandingPatternMapVisual.qml
- src/PlanView/VTOLLandingPatternEditor.qml
- src/PlanView/VTOLLandingPatternMapVisual.qml
Fix console warnings shown when adding complex land mission item
1. Remove references to non existent useLoiterToAlt.visible property
2. Don't add _mouseArea to the map (the action was failing and isn't necessary)
1. Run a plane sim
```
cd PX4-Autopilot
make px4_sitl gazebo-classic_plane
```
2. Run QGC master and create a mission with a complex land (use left tool bar to add a "Tokeoff" item and then use the left tool bar to add a "Land" item, which will be a FWComplexLand since a plane is connected to QGC.
3. You should see this warning in the QtCreator log (This PR removes the warning)
4. If you upload the mission to the vehicle and restart QGC, there is another warning that appears 
Run the steps in "Steps to reproduce issue" only use this PR's branch. The difference will be the …
> Fix console warnings shown when adding complex land mission item

- src/Joystick/Joystick.cc
Check to see if activeVehicle is null as that could cause a null exception when we don't.
Description
-----------
If a null vehicle was given to a joystick on creation the start-pulling function would eventually cause a null exception when it got to the _handleAxis function because we check if _activeVehical has joystickEnabled but not if the _activeVehical null. 
Test Steps
-----------
1. Make a slot that waits for the joystickManager to send out that a new joystick have been connected
2. Make a Vehical that is null
3. Start polling on the newly connected joystick with the null Vehical
Before that, the program would crash because of a null pointer exception. Now it keeps running and allows users to test the joysticks's raw value output if they desire 
Checklist:
----------
By submitting …
> Check if there is a valid _activeVehical to not get a nullpointer exception

- src/FirmwarePlugin/APM/APMSensorIdDecoder.qml
Moved INS_IIM42653 to the end of the devid list
I jumped the gun with https://github.com/mavlink/qgroundcontrol/pull/11995
Pending https://github.com/ArduPilot/ardupilot/pull/28383
> APMSensorIdDecoder: fix ID order for IIM42653

- src/AutoPilotPlugins/Common/RadioComponent.qml
- src/AutoPilotPlugins/Common/RadioComponentController.cc
- src/AutoPilotPlugins/Common/RadioComponentController.h
- src/MAVLink/CMakeLists.txt
Adds crsf-bind button.
Based on: 
- https://github.com/PX4/PX4-Autopilot/pull/23294
and
- https://github.com/mavlink/mavlink/pull/2162
Test Steps
-----------
The button successfully sets a CRSF (crossfire, ELRS, etc) receiver into bind mode
> Add crsf-bind button

- src/Comms/MockLink/MockLink.cc
- src/Comms/MockLink/MockLink.h
Description
-----------
Support for remote ID in mock link added to test remote ID UI and other features
Test Steps
-----------
Application Settings -> Mock Link -> Choose any vehicle 
FlyView Page -> Remote ID should be visible
Checklist:
----------
Related Issue
-----------
https://github.com/mavlink/qgroundcontrol/issues/12048
> Ready Arm status added in MockLink for remote ID

- cmake/CreateMacDMG.cmake
Taken from previous stable
https://github.com/mavlink/qgroundcontrol/blob/990ed12f5be9464d737ba0da703a126f63b0eff0/QGCPostLinkInstaller.pri#L22
> CMake: Fix MacOS GStreamer RPath

- CMakeLists.txt
Description
-----------
Changed the compile definition QGC_APP_NAME from ${CMAKE_PROJECT_NAME} to ${QGC_APP_NAME}, so that the app name will actually get overriden in custom builds. Haven't tested that non-custom builds still work, but according to CustomOptions.cmake in that case ${QGC_APP_NAME} will be the same as the default value of ${CMAKE_PROJECT_NAME}.
Checklist:
----------
> Fix app name override in custom builds

- CMakeLists.txt
- src/CMakeLists.txt
- src/MissionManager/CMakeLists.txt
- src/PlanView/CMakeLists.txt
- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/QmlControls/CMakeLists.txt
- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QGroundControlQmlGlobal.h
- src/UTMSP/CMakeLists.txt
- src/UTMSP/UTMSPAuthorization.cpp
- src/UTMSP/UTMSPFlightPlanManager.h
- src/UTMSP/UTMSPManager.cpp
- src/UTMSP/UTMSPManager.h
- src/UTMSP/UTMSPNetworkRemoteIDManager.h
- src/UTMSP/UTMSPVehicle.cpp
- src/UTMSP/UTMSPVehicle.h
- src/Vehicle/CMakeLists.txt
- src/Vehicle/Vehicle.cc
Convert from tools to singletons
> UTMSPManager: Convert to Singleton

- src/Audio/AudioOutput.cc
- src/Audio/AudioOutput.h
- test/Audio/AudioOutputTest.cc
- test/Audio/AudioOutputTest.h
The index of the internal queue doesn't actually decrement as expected based on documentation, so use connections to correct queue size.
Use atomics for thread safety
Remove unnecessary muted signal
> AudioOutput: Fix queue size and improve thread safety

- src/Comms/SerialLink.cc
To reproduce: on linux, try to connect to an existing /dev/ttySX that is not a valid serial port (preexisting ttys?)
Crash happens like this:
- Open an existing port that triggers on open a QSerialPort::ResourceError (stock /dev/ttySX on my end)
- Signal QSerialPort::errorOccurred
- Slot SerialLink::linkError
- LinkInterface::_connectionRemoved
- SerialLink::disconnect => set _port = null
- On retry, at [https://github.com/unjambonakap/qgroundcontrol/blob/aacb664bffc2baa47c6f6a8ec9a224149fd06977/src/Comms/SerialLink.cc#L182], crashes because _port == null
-----------
Simply moves the connection of signals (readyRead and errorOccurred) until the serial port's configuration is finished.
Note: I'm guessing that should data arrive in between port opening and connection of the readyRead() …
> Bugfix for racy crash on opening bad serial port

- src/Camera/SimulatedCameraControl.cc
- src/Camera/SimulatedCameraControl.h
- src/Camera/VehicleCameraControl.cc
- src/QGCApplication.cc
- src/QGCToolbox.cc
- src/QGCToolbox.h
- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QGroundControlQmlGlobal.h
- src/Settings/VideoSettings.cc
- src/Vehicle/Vehicle.cc
- src/VideoManager/VideoManager.cc
- src/VideoManager/VideoManager.h
Convert to Singleton and perform updates to further support multiple streams by using the VideoReceiverData struct in more places. Tested using RTSP & UVC on Linux & Android.
Later work includes moving the remaining variables like _decoding & _videoSize into the VideoReceiverData so that they can be unique per stream.
> VideoManager: Convert to Singleton

- src/VideoManager/VideoManager.cc
Use original cleanup method until the core plugin is a singleton.
> VideoManager: Fix Crash on Exit

- src/VideoManager/VideoReceiver/GStreamer/README.md
Description
-----------
GStreamer is now downloaded and set up for the build automatically as part of the CMake configure step. A note has also been added to help Windows users ensure that this works correctly.
Checklist:
----------
> Update outdated GStreamer for Android instructions

- android/src/org/mavlink/qgroundcontrol/QGCUsbSerialManager.java
Description
-----------
The overload to the registerReceiver method with a flags parameter was introduced in API level 26 (Android 8.0), which leads to an instant crash on startup on devices running older versions of Android. Adjusted the implementation to use the previous signature of registerReceiver on devices with API levels below 26.
Checklist:
----------
> Fix crash on startup for older Android devices

- src/Comms/USBBoardInfo.json
> USBBoardInfo: add missing ARK defines

- src/VehicleSetup/FirmwareUpgradeController.cc
Add BoardID for Holybro Kakuteh7mini to match the changes in  https://github.com/PX4/PX4-Autopilot/pull/23832 & https://github.com/PX4/PX4-Autopilot/pull/23922, allowing user to be able to flash firmware online in QGC with the new bootloader ID.
> Add BoardID for Holybro Kakuteh7mini

- src/UI/MainRootWindow.qml
> Only show close button when full screen

- CMakeLists.txt
- custom-example/android/AndroidManifest.xml
Description
-----------
Modified the build system to prioritize files under custom/android/ over android/ for Android deployment in custom builds.
If custom/android/ exists and contains files, these are overlaid onto the default android/ files, creating a combined Android package deployment template in the build directory. This enables customization of any aspect of the Android deployment in custom builds without modifying the upstream android/ directory. Additionally, any changes in either directory will trigger the CMake configuration step in order to update the combined directory.
This change also restores support for the custom Android icons under custom/android/, which had been disabled during the transition to CMake.
Additional note:
New CMake properties for Android deployment …
> Improve flexibility in Android custom builds

- src/AutoPilotPlugins/Common/RadioComponentController.cc
- src/Vehicle/Vehicle.cc
If you are using ELRS MAVLINK setup as per: https://www.expresslrs.org/software/mavlink/ then the number of channels will never be set. Hence it will remain 0 -- even though there is clearly control data going through. This is because ELRS is not sending a full `RC_CHANNELS` packet, only channel update packets via `RC_CHANNELS_RAW`, to update the position of the values. Therefore, the number of channels is not set.
This ELRS system forwards BOTH the RC and the Mavlink on the same ELRS link. Using one TX and one RX, you get to have both Mavlink and RC. The Mavlink is forwarded via the backpack chip in the TX to the wifi. You can then connect to this wifi and QGC picks it up automatically, via zero-conf (I think! Very cool) and "just works". Which is great. But the RC doesn't SEEM to work, …
> Fixing channel issue with ELRS Mavlink-rc: number of channels is not set by default

- .github/workflows/android-linux.yml
- .github/workflows/android-macos.yml
- .github/workflows/android-windows.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- cmake/find-modules/FindGStreamer.cmake
> Update CI dependencies

- cmake/find-modules/FindGStreamer.cmake
> CMake: Remove Graphene Linking

- src/PlanView/MissionItemEditor.qml
Description
-----------
Hides the "Show all values" option found in the mission item editor hamburger menu unless Advanced Mode is on.
Checklist:
----------
> Enable WP "Show all values" only in Advanced Mode

- .github/workflows/linux.yml
- deploy/docker/Dockerfile-build-ubuntu
- tools/setup/install-dependencies-debian.sh
Closes #12176
Use docker for 20.04 since it won't be available for GitHub runners soon
> CI: Prepare for GitHub's Removal of Ubuntu 20.04 Runner

- src/UI/preferences/RemoteIDSettings.qml
- src/UI/toolbar/RemoteIDIndicatorPage.qml
Description
-----------
Remove a few config settings related to remote ID as they are now shifted to Application Settings.
Test Steps
-----------
1) Start Mocklink
2) Toolbar -> Remote ID -> Extended Menu
Related Issue
-----------
https://github.com/mavlink/qgroundcontrol/issues/12018
> Remove RemoteID Configurations from Toolbar

- src/Comms/AirLink/AirLinkManager.cc
This can cause a build to fail on certain custom build setups
> Airlink: Add missing header file

- android/libs/qtandroidserialport/qserialport_android.cpp
- android/libs/qtandroidserialport/qserialport_p.h
- android/src/org/mavlink/qgroundcontrol/QGCUsbSerialManager.java
- src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc
- src/Comms/LinkManager.cc
- src/Comms/LinkManager.h
- src/Comms/QGCSerialPortInfo.cc
- src/Comms/QGCSerialPortInfo.h
- src/Comms/SerialLink.cc
- src/Comms/SerialLink.h
Related to https://github.com/mavlink/qgroundcontrol/issues/11598
fixes #11849
The QThread inheritance will have to be removed after the remaining links are fixed
Tested by turning all streams to 100Hz and letting it run for a while:
> Comms: SerialLink Threading Changes

- src/AutoPilotPlugins/APM/APMSafetyComponent.qml
- src/AutoPilotPlugins/APM/APMSafetyComponentPlane.qml
- src/AutoPilotPlugins/APM/APMSafetyComponentSummaryPlane.qml
Description
-----------
The ALT_HOLD_RTL parameter was removed in ArduPlane 4.5 and replaced with RTL_ALTITUDE. This change caused the Safety Component to display error messages when connecting to vehicles running newer firmware versions.
Added logic to use 'RTL_ALTITUDE' for ArduPilot versions 4.5 and above, while maintaining 'ALT_HOLD_RTL' for older versions.
Checklist:
----------
Related Issue
-----------
#11620
> Update RTL altitude parameter for ArduPlane 4.5+

- src/FlightDisplay/FlyView.qml
- src/FlightDisplay/GuidedValueSlider.qml
Replacement for #12165
While looking at #12165 I discovered other issues and also wanted to rework it so that the code was clearer. So this pull is based on that pull with some additional changes.
Changes:
* The slider is now parented right up to the top/bottom/right edges of window. Previously there was a small margin around it. This could cause problems where you would mistakenly zoom the map when you really wanted to scroll the slider if you were off the edge.
* Mouse events were bleeding through to the map below. So if you happens to scroll over the slider left/right using a track pad the map would zoom below it. There is not a dead mouse area below the control to prevent mouse events from bleeding through controls below it.
* There were various problems with the margins between the …
> GuidedValueSlider: Rework to fix margin issues and other things

- src/VideoManager/VideoReceiver/QtMultimedia/QtMultimediaReceiver.cc
Resolves a couple of issues with the QtMultimedia Receiver
> Video: Fix QtMultimedia Receiver Crashes

- src/Comms/UDPLink.cc
- src/Comms/UDPLink.h
Small changes to reduce time spent in reception socket
> Comms: Speed up UDPLink Reception

- src/FlightDisplay/ObstacleDistanceOverlay.qml
- src/FlightDisplay/ObstacleDistanceOverlayMap.qml
- src/FlightDisplay/ObstacleDistanceOverlayVideo.qml
Fixes issue where obstacle distances are displayed with a +90 degree offset. This is due to an error in the coordinate system math along with an error in calculating the degrees for the current distance index. The yaw angle theta is measured CW from North and therefore `r * cos(theta)` is negative Y axis and `r * sin(theta)` is positive X.
**Qt docs**
> The x values increase to the right and the y values increase downwards.
There's more still that needs to be done. The ObstacleDistanceOverlayVideo.qml probably needs this fix. There's also the VehicleObjectAvoidance class which seems to be entirely unused other than the `distances` array. This feature is currently broken in PX4 and I don't think anyone has used it in years. I want to resurrect the feature and make it all work again.
> [ObstacleDistanceOverlay] Fix 90 degree offset 

- src/API/QGCCorePlugin.h
- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
Description
-----------
This allows custom plugin to respond to joystick actions with MAVLink commands whose parameters can change during runtime.
Checklist:
----------
> Joystick: allow custom plugin to add and handle custom actions

- src/Comms/LinkManager.cc
- src/Comms/SerialLink.cc
- src/Comms/SerialLink.h
- src/Comms/UDPLink.cc
- src/Comms/UDPLink.h
This will cause continuous errors on autoconnect. So, only emit if not an autoconnect link
> Comms: Don't force disconnect autconnect links on failed setup

- src/Comms/LinkManager.cc
Quick fix for non-dynamic link saving
> Comms: Link dynamic fix

- custom-example/qgroundcontrol.qrc
- custom-example/src/CustomPlugin.cc
- custom-example/src/CustomPlugin.h
- src/API/QGCCorePlugin.cc
- src/API/QGCCorePlugin.h
Adding these was causing all sorts of problems in custom build implementations
> QGCCorePlugin: Remove const from all but the simplest methods

- custom-example/custom.qrc
- custom-example/qgroundcontrol.exclusion
- custom-example/qgroundcontrol.qrc
- custom-example/src/CustomGuidedActionsController.qml
- custom-example/src/FlyViewCustomLayer.qml
- custom-example/src/FlyViewToolStripActionList.qml
- qgroundcontrol.qrc
- src/FlightDisplay/CustomGuidedActionsController.qml
- src/FlightDisplay/GuidedActionsController.qml
- src/QmlControls/QGroundControl/FlightDisplay/qmldir
* Custom builds can override CustomGuidedActionsController.qml resource to add custom guided actions. This way y ou don't need to fully override the huge GuidedActionsController.qml file. Which is much more prone to causing problems when you update to new upstream qgc sources.
* Added example custom button to custom-example version of QGC
* At some point I'd like to do something much more sophisticated than this which also prevents the need to override FlyViewToolStripActionList.qml. But for now this is a step in a cleaner direction.
> Add simple custom build mechanism for custom guided actions

- src/Settings/CMakeLists.txt
- src/Settings/VideoSettings.cc
- src/Settings/VideoSettings.h
- src/VideoManager/CMakeLists.txt
- src/VideoManager/VideoManager.cc
Fixes Enable Macro for the Video Settings
> VideoManager: Fix QtMultimedia Define

- src/QmlControls/QGCTextField.qml
- src/UI/preferences/RemoteIDSettings.qml
* Fix #12137
* Use standard validation UI for operator id validation
> Remote ID: Fix validation

- src/Utilities/StateMachine.cc
- src/Utilities/StateMachine.h
- src/Vehicle/Components/ComponentInformationManager.cc
- src/Vehicle/Components/ComponentInformationManager.h
- src/Vehicle/InitialConnectStateMachine.cc
- src/Vehicle/InitialConnectStateMachine.h
- src/Vehicle/Vehicle.cc
- test/qgcunittest/UnitTest.cc
Correct inheritance through QObject
> Correct StateMachine Inheritance

- src/PlanView/MissionItemEditor.qml
> Plan: Only load editor if current item

- src/QmlControls/FlightModeMenu.qml
Description
-----------
If advanced mode changed which flight modes can be set, these changes were not visible in the UI.
Checklist:
----------
> FlightModeMenu: fix mode list not updating when changed by advanced mode

- src/PlanView/MissionItemEditor.qml
- src/PlanView/PlanView.qml
- src/QmlControls/QGCPopupDialog.qml
- src/QmlControls/ToolStripHoverButton.qml
- src/UI/MainRootWindow.qml
* Fix #12246
* When dialogs popup validation errors can stack up. Fix dialog handling when there are already validation errors in the ui displaying the dialog
* Added a few more view switch checks to prevent moving away when validation errors exist
> Validation fixes

- src/FlightDisplay/FlyViewWidgetLayer.qml
- src/QmlControls/PreFlightCheckButton.qml
Description
-----------
- When performing the preflight checklist, it is often necessary to close it at certain steps to complete some of the checks. However, when it got closed and reopened, its state was lost and all completed checks had to be manually re-checked. This commit wraps the checklist component in a loader, so that once its first opened, it stays loaded and keeps its state.
- Made it possible to set manual checklist buttons back to the pending state, so that in case of an accidental click, the check can be undone without resetting the entire checklist and having to go through it again.
Checklist:
----------
> Improve preflight checklist usability

- src/FlightDisplay/GuidedValueSlider.qml
https://github.com/user-attachments/assets/8a90ecf8-74d0-4f68-893f-c6f2e7048fc4
> GuidedValueSlier: Click on value to type into text field

- src/Comms/UDPLink.cc
Should reduce number of popups produced on weak udp links
> Comms: Reduce UDP Popups on Weak Links

- src/FactSystem/FactControls/FactCheckBox.qml
- src/MissionManager/FWLandingPattern.FactMetaData.json
- src/MissionManager/FixedWingLandingComplexItem.cc
- src/MissionManager/FixedWingLandingComplexItem.h
- src/MissionManager/LandingComplexItem.cc
- src/MissionManager/LandingComplexItem.h
- src/MissionManager/VTOLLandingComplexItem.cc
- src/MissionManager/VTOLLandingComplexItem.h
- src/PlanView/FWLandingPatternEditor.qml
- test/MissionManager/LandingComplexItemTest.cc
- test/MissionManager/LandingComplexItemTest.h
Description
-----------
Addressed issues with scanning and interpreting landing sequences for fixed wing ArduPilot aircraft. Previously, landing sequences uploaded to ArduPilot fixed wing aircraft and then downloaded back weren't being reinterpreted as QGC LandingComplexItems. The system to detect a landing sequence and translate it back to a LandingComplexItem wasn't working correctly due to multiple assumptions about mission item parameters that weren't accurate for ArduPilot.
The changes include adjusting parameter checks for NAV_LAND, NAV_LOITER_TO_ALT, NAV_WAYPOINT, and DO_LAND_START commands to align with ArduPilot's implementation, without modifying the existing logic for other firmwares.
When not using the "Use loiter to altitude" option in the Landing Pattern mission item, the …
> Various Landing Pattern fixes and add final approach speed

- src/Geo/CMakeLists.txt
This included a fix that resolves some warning we were getting with previous versions
> Geo: Update GeographicLib to 2.5

- src/FirstRunPromptDialogs/UnitsFirstRunPrompt.qml
Description
-----------
When changing unit system, the individual unit ComboBoxes weren't updating to reflect it. Fixed by forcing a model reload.
Checklist:
----------
> Fix unit system change in the units FirstRunPrompt

- CMakeLists.txt
- custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc
- custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.h
- src/AutoPilotPlugins/APM/APMSubMotorComponent.qml
- src/AutoPilotPlugins/APM/APMSubMotorComponentController.cc
- src/Comms/MockLink/MockLink.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.cc
- src/FirmwarePlugin/FirmwarePlugin.h
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
- src/FirmwarePlugin/PX4/px4_custom_mode.h
- src/QmlControls/PIDTuning.qml
- src/Vehicle/StandardModes.cc
- src/Vehicle/StandardModes.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Update APM and PX4 flight mode parsing methods
Description
-----------
- Removed use of direct strings to change flight mode.
- Case-sensitive issues in flight mode in APM.
- Internal Mapping to flight mode names.
- QGC Custom Build support has also been added.
- Add New Modes discovered via Available Mode packets received from the flight controller.
Related Issue
-----------
https://github.com/mavlink/qgroundcontrol/pull/12191
https://github.com/mavlink/qgroundcontrol/issues/12128
> Standard methods for parsing available flight mode for PX4 and APM

- src/Comms/USBBoardInfo.json
Useful to debug an MCU while also using QGC. I don't think we should identify FTDI devices as SiK Radios and attempt to autoconnect as such.
> remove FTDI from USB pid/vid list for SiK Radio

- cmake/CustomOptions.cmake
- src/Vehicle/StandardModes.cc
Fixes PX4 broken mode lists from https://github.com/mavlink/mavlink/pull/2191
Do we still need the mavlink submodule?
> Update mavlink 

- src/Joystick/Joystick.cc
- src/Joystick/JoystickSDL.cc
- src/QmlControls/AppMessages.qml
Problems fixed:
* Joystick code spitting out pile of this `qgc.joystick.joysticksdl: Couldn't add GameController mapping: Couldn't parse GUID from # Game Controller DB for SDL in 2.0.16 format`
* Joystick logging getting output even when not turned on
* PITA to turn off logging categories which are turned on and/or see which ones are on. Have to scroll through a big list
New logging dialog:
> Logging fixes

- src/QmlControls/ParameterEditor.qml
- src/QmlControls/ParameterEditorDialog.qml
Problems:
* On small screens like Herelink was pretty unusable
* No support for horizontal scrolling of parameter list
Changes:
* Fixed above problems
* Much better usage of available real estate 
* Much better handling of different screen sizes
New (Herelink sized screen):
Old (Herelink sized screen):
> Parameter editor usability

- src/Comms/LinkManager.cc
- src/Comms/UdpIODevice.cc
- src/Comms/UdpIODevice.h
- src/PositionManager/PositionManager.cpp
- src/UI/preferences/LinkSettings.qml
re-add NMEA to links
update UDPIODevice implementation
minor fix to auto connecting NMEA
> Comms: Update UdpIODevice

- src/Comms/CMakeLists.txt
- src/Comms/LinkConfiguration.cc
- src/Comms/LinkInterface.h
- src/Comms/LinkManager.cc
- src/Comms/LogReplayLink.cc
- src/Comms/LogReplayLink.h
- src/Comms/LogReplayLinkController.cc
- src/Comms/LogReplayLinkController.h
- src/QmlControls/LogReplayStatusBar.qml
- src/UI/preferences/LogReplaySettings.qml
Related to https://github.com/mavlink/qgroundcontrol/issues/11598
> Comms: LogReplayLink Threading Changes

- src/FlightDisplay/GuidedActionsController.qml
- src/FlightDisplay/GuidedValueSlider.qml
* Based on / replacement for #12259
* Make guided slider return floats not strings
* Fix orbit command to send altitude in AMSL frame
> Orbit fixes

- cmake/CustomOptions.cmake
- src/MAVLink/StatusTextHandler.cc
- src/UI/MainRootWindow.qml
* Temporarily disable video support on MAC till we can figure out how to make it work
* Fix crash in chunked status text handler
* Fix incorrect call to old popup code
> Disabled video support on MAC - plus other fixes

- CMakeLists.txt
- android/AndroidManifest.xml
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- cmake/CustomOptions.cmake
- cmake/printSummary.cmake
Set some properties provided in Qt6.7 & Qt6.8
> CMake: Set some Qt6.8 properties

- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.h
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Send the mavlink command MAV_CMD_DO_SET_MISSION_CURRENT in place of the old mavlink message MISSION_SET_CURRENT.  If "UNSUPPORTED" is received from the autopilot then send the old mavlink message.
The mavlink command has existed since 2019.
The mavlink message has been deprecated since Aug 2022.
ArduPilot has supported the command since 4.1.0 (2021)
Adds infrastructure which should be reused for (eg.) the DO_REPOSITION code.
> Use MAV_CMD_DO_SET_MISSION_CURRENT for APMFirmwarePlugin

- .dockerignore
- CMakeLists.txt
- cmake/Qt6QGCConfiguration.cmake
- deploy/docker/Dockerfile-build-macos
- deploy/docker/Dockerfile-build-ubuntu
- deploy/docker/run-docker-macos.sh
- deploy/docker/run-docker-ubuntu.sh
> Docker: Create MacOS script

- .github/workflows/android-windows.yml
- .github/workflows/custom.yml
- .github/workflows/linux.yml
- .github/workflows/windows.yml
- CMakeLists.txt
Enable building Windows Arm64
Edit: It's occurred to me that GStreamer would have to be built manually
> CI: Build Windows Arm64 CrossCompiled

- src/FactSystem/FactControls/FactTextField.qml
- src/QmlControls/QmlObjectListModel.cc
- src/UI/MainRootWindow.qml
- src/Vehicle/Vehicle.cc
> Fix flight modes being announced multiple times, plus others

- src/FirmwarePlugin/APM/ArduCopterFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.cc
- src/FirmwarePlugin/FirmwarePlugin.h
Resolved multiple flight modes in ArduPlane: https://github.com/mavlink/qgroundcontrol/pull/12254#issuecomment-2571379641
Arduplane is sending standard modes twice, thus adding them to the list multiple times.
Also changed from `final` to `override` for better integration in Custom GCS
> Add Unique Flight Modes Only

- src/MissionManager/MavCmdInfoCommon.json
Fixed Trigger Parachute, Guided Enable, Autotune Enable Commands.
Description
-----------
1. Trigger Parachute
Changed description of Trigger Parachute.
2. Guided Enable
Matched enumStrings and enumValues correctly.
On - 1, Off - 0
3. Autotune Enable
Changed param number. Enable/Disable should be param1 not param2.
param2 -> param1
Test Steps
-----------
Checklist:
----------
- [ x ] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [ x ] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [ x ] I have tested my changes.
> Fix MavCmd-Trigger Parachute, Guided Enable, Autotune Enable

- src/QmlControls/ToolIndicatorPage.qml
> Tool indicator: Put back separator between expanded content

- custom-example/src/FlyViewToolStripActionList.qml
- src/FlightDisplay/FlyViewToolStrip.qml
- src/FlightDisplay/FlyViewToolStripActionList.qml
- src/PlanView/PlanToolBarIndicators.qml
- src/PlanView/PlanView.qml
- src/UI/MainRootWindow.qml
- src/UI/toolbar/FlightModeIndicator.qml
- src/UI/toolbar/MainStatusIndicator.qml
- src/UI/toolbar/PlanViewToolBar.qml
* Main view is now just Fly View
* The remainder of the views are "Tools" and have a consistent way of selecting them as well as getting back to Fly view from them
* Fly and Plan buttons are no longer in the left side Toolstrips
* Some other minor user visible naming tweaks
> Tool consistency ui tweaks

- src/Comms/USBBoardInfo.json
Update USBBoardInfo.json to include 3DR Control Zero OEM G
Description
-----------
Adding USB PID & VID to recognize the 3DR Control Zero OEM G board.
I have already tested on Linux and Windows.
Test Steps
-----------
- Connect a board
- Attempt to Autoconnect/Upload Firmware
- The board should be recognized and be able to upload firmware
Checklist:
----------
- [X ] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [ X] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [ X] I have tested my changes.
Related Issue
-----------
> Update USBBoardInfo.json to include 3DR Control Zero OEM G

- src/VehicleSetup/FirmwareUpgradeController.cc
- src/comm/USBBoardInfo.json
Description
-----------
This backport brings PRs #11759 and #12367 into `Stable_V4.4`
Test Steps
-----------
Checklist:
----------
- [ x] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [ x] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [ x] I have tested my changes.
Related Issue
-----------
> [BACKPORT V4.4] Adding support for new 3DR boards 

- src/QmlControls/QGCSimpleMessageDialog.qml
- src/UI/MainRootWindow.qml
- src/UI/toolbar/GimbalIndicator.qml
fixes #12328 
If another user was in control of the gimbal, the current logic would stop gimbal commands from being sent out, but not show a "Request Gimbal Control" popup. There was a signal being emitted suggesting  a popup was intended to be shown, but wasn't. Now a popup is indeed shown.
> Add "Request Gimbal Control" popup

- src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt
* Local builds now work
* Building a DMG you install from and run still doesn't work
> Fix Mac gstreamer support

- .github/workflows/macos.yml
- CMakeLists.txt
- cmake/CreateMacDMG.cmake
- src/AnalyzeView/CMakeLists.txt
* Turned off code signing in mac ci since it's not working yet
* Switched exiv2 on osx to static lic. Dynamic lib wasn't being copied into bundle causing runtime failure
* Ad-hoc codesign bundle after macdeployqt step
* Fix macdeployqt args. This was the main problem in that the plugins were not being copied to the bundle. And then when you ran QGC it just seemed to hang with no ui and no helpful qt output as to why. Took forever to figure out what was going on.
> Mac install: DMG creation and app inside DMG not work correctly

- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
Description
-----------
Add new ArduPlane flight modes: AUTOLAND,LOITER2QLAND
Add the mode to the appropriate files for display and use
Checklist:
----------
- [x ] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [x ] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
> Add ArduPilot Plane AUTOLAND and LOITER2QLAND modes

- src/QmlControls/ParameterEditorController.cc
- src/QmlControls/ParameterEditorController.h
> param: debounce search with timer to reduce UI lag

- .github/actions/cache/action.yml
- .github/workflows/android-linux.yml
- .github/workflows/android-macos.yml
- .github/workflows/android-windows.yml
- .github/workflows/custom.yml
- .github/workflows/docs_deploy.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- test/AutoPilotPlugins/CMakeLists.txt
- test/Geo/CMakeLists.txt
- test/MissionManager/CMakeLists.txt
- test/MissionManager/MissionItemTest.cc
- test/MissionManager/MissionItemTest.h
- test/Terrain/CMakeLists.txt
- test/Vehicle/CMakeLists.txt
- test/Vehicle/SendMavCommandWithSignallingTest.h
> CMake: Link Test Libs Privately

- package-lock.json
- package.json
This updates the package.json for the docs build. 
Specifically it adds license info that otherwise gives build warning. But I also updated description, version, repo, and the Vitepress version.
We should probably move this file into docs to improve build "hygiene", but that would require I update the build actions too, and I don't have time.
Note, I was here to update the instructions to remove gstreamer dependencies, but since the install docs refer to the current release build, and that still requires them, have not done so.
> Update Vitepress version

- custom-example/qgroundcontrol.qrc
- qgroundcontrol.qrc
- src/FlightDisplay/FlyViewMap.qml
- src/PlanView/MissionItemEditor.qml
- src/PlanView/PlanView.qml
- src/QmlControls/DropPanel.qml
- src/QmlControls/QGroundControl/Controls/qmldir
- src/QmlControls/ToolStrip.qml
- src/QmlControls/ToolStripDropPanel.qml
Problems:
* When clicking in map to execute a position oriented command you lose context of where exactly you clicked when the command popup shows
* In the Plan view the hamburger item uses a QGCMenu which is based on QMl Menu control. A while back Qt screwed up this control such that it doesn't support dynamic visibility of items like it used to. This in turn made it very wonky looking. You can see it here:
Solution was to create a new DropPanel control which is based on the the ToolStrip drop panel control. This popup has an arrow indicator which points to the place the items are referring and doesn't suffer the problems QGCMenu has. I've switched over the Map click popup to use that as well as the Plan view hamburger drop down.
Here you can see a map click pop at the extreme edge of …
> Add/Use new DropPanel control

- src/AnalyzeView/CMakeLists.txt
- src/Joystick/CMakeLists.txt
Exiv2 has some build fixes & this is probably the last SDL2 version before SDL3
> CMake: Update Exiv2 & SDL2

- src/QmlControls/QGCPopupDialog.qml
This would lead to unexpected dialog close both on desktop and mobile. But much worse on mobile with virtual keyboard. Also I think with the new Qt version something changed with the virtual keyboard simulating an enter key press.
Fix #12426
> Remove enter key to close dialogs

- .github/workflows/android-linux.yml
- .github/workflows/android-macos.yml
- .github/workflows/android-windows.yml
- .github/workflows/custom.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/windows.yml
- cmake/find-modules/FindGStreamer.cmake
- src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
- src/VideoManager/VideoReceiver/GStreamer/GStreamer.cc
- src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt
Fixup the FindGStreamer.cmake a bit
> CMake: GStreamer Fixes

- .github/actions/qt-android/action.yml
- .github/workflows/custom.yml
- .github/workflows/linux.yml
- .github/workflows/windows.yml
- android/gradle/wrapper/gradle-wrapper.properties
Trying to silence Android cmake warning
Better support Linux c++20
Use newer aqt on windows
> CI: Update Various Deployment Tools Versions

- docs/en/qgc-dev-guide/getting_started/container.md
Documentation note about fuse in docker
Description
-----------
Some users encounter an error about fuse unable to mount a device during AppImage assembly. Note describes command line options necessary for solving this issue.
Test Steps
-----------
None.
Checklist:
----------
Related Issue
-----------
#11565 
> Note about fuse errors in docker

- src/MissionManager/StructureScanComplexItem.cc
Entrance altitude does not load form File (structure scan)
Description
-----------
Structure Scan Load File, results in a 0 for EntranceAltitude edit box.
Wrong JSON tag being used to lookup the Entrance Altitude.
"_entranceAltName" is the correct JSON string to use. As seen in ::save()
Test Steps
-----------
Create a Structure Scan plan. (I tested with Circle type, but it shouldn't matter).
Edit the "Entrance Altitude" in the Structure scan editor, to a memorable number.
Save this plan to file.
Clear plan.
Load the plan file.
The Entrance Altitude variable will be 0.
(the plan file has the correct value)
Checklist:
----------
- [ X] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [ X] [Review Code of …
> Fix file Load of EntranceAltitude in StructureScanComplexItem.cc

- src/Vehicle/FactGroups/VehicleBatteryFactGroup.cc
This was incorrect per mavlink spec. Didn't cause bad total voltage values though. But better to be correct to spec. Just discovered it while working on something else.
> Battery: Fix voltages_ext unsupported check

- src/QmlControls/DropPanel.qml
> DropPanel - dim = false

- src/PlanView/StructureScanEditor.qml
- src/QmlControls/SectionHeader.qml
Section header wasn't left-aligned correctly.
Before and after:
> Section header position

- src/QmlControls/ValueSlider.qml
Fix for https://github.com/mavlink/qgroundcontrol/issues/12453
The previous fix mentioned in this PR https://github.com/mavlink/qgroundcontrol/pull/12464 does not work as expected
> Fix: Prevent events from passing through ValueSlider to the map

- src/UI/toolbar/FlyViewToolBar.qml
> Fly View Toolbar: Add right margin for better visuals when scrolling

- .github/workflows/crowdin_download.yml
- crowdin_docs.yml
- docs/crowdin.yml
Crowdin currently works for getting QGC strings but not for docs. This is because the default integration only expects one integration and looks for the definition of that file in the root as `crowdin.yml`. 
This uses the GitHub crowdin action to separately manage the docs: https://github.com/crowdin/github-action/tree/master?tab=readme-ov-file#github-crowdin-action-
This is the first part, a test to download any translations into a docs PR. Initially this is an action that has to be manually triggered. We might add support for sync job after.
Note, this uses three access tokens: PX4BUILDBOT_ACCESSTOKEN (already in repo, might not work), CROWDIN_DOCS_PROJECT_ID , PX4BUILDBOT_CROWDIN_PERSONAL_TOKEN
> Fix crowdin for docs - download workflow

- src/API/CMakeLists.txt
- src/CMakeLists.txt
- src/Settings/CMakeLists.txt
- src/VideoManager/CMakeLists.txt
- src/VideoManager/VideoReceiver/CMakeLists.txt
- src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
- src/VideoManager/VideoReceiver/QtMultimedia/CMakeLists.txt
> CMake: Simplify VideoManager Linking

- src/FlightMap/FlightMap.qml
Simplest explanation is that using DragHandler's don't work if you ever overlay any other Qml over it in the hierarchy. Qt bug report list is littered with bug reports of people having similar problems. With only clear as mud responses/excuses/explanations of how to work around it. My take is DragHandler's are broken and shouldn't be used.
> Fix map panning yet again

- cmake/find-modules/FindGStreamer.cmake
I am uncertain if this is required, but it is taken from GStreamer's FindGStreamerMobile
> CMake: Add GStreamer Android 32bit Fix

- docs/en/qgc-dev-guide/getting_started/index.md
Description
-----------
By default the qt installation go into the users home folder. This fixes the command to take the default qt installation path.
Test Steps
-----------
1. Go to cloned qgroundcontrol folder
2. Run **~/Qt/6.8.2/gcc_64/bin/qt-cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug**
Checklist:
----------
> fix default path for qt-cmake for source build

- src/FactSystem/FactMetaData.cc
* Translators have a tendency to add spacing after the commands which breaks things
* Fix #12526
> Trim enumStrings/enumValues

- CMakeLists.txt
Android version code generation must be consistent release to release such that is always and increasing number. Without that you can install over other versions.
> Fix android version code generation

- src/FlightDisplay/GuidedValueSlider.qml
- src/QmlControls/ValueSlider.qml
When you click on the slider value the text field shouldn't show a full keyboard on mobile. Only a numeric keyboard.
> Fix value sliders to be numeric only text felds

- src/MissionManager/GeoFenceManager.cc
Description
-----------
This PR fixes 2 tiny issues:
1. an unclear `if-else if-else` tree that is written as `if-else if-if(?)`
2. right after that there is an `emit error(BadPolygonItemFormat, [QString])` where the `QString` part promises actual vs expected value but never delivers on this promise. Not wanting to break existing translations I added a `+ QString(" %1:%2")` right before the `.arg(...).arg(...)` to make sure the promised values are printed.
Test Steps
-----------
Visual inspection and successful compilation.
Checklist:
----------
> Small GeoFenceManager fixes

- src/AutoPilotPlugins/PX4/FlightModesComponent.cc
- src/AutoPilotPlugins/PX4/FlightModesComponent.h
Given the prevalence of things like Joysticks, Android controllers and the fact that you can change flight modes all you want from the QGC ui. It is not longer required to setup flight modes on an RC Transmitter channel.
> Flight mode config no longer warning about not being configured

- CMakeLists.txt
QT_NO_DEBUG_OUTPUT kills the availability of any qDebug logging in Release builds, include categorized logging which is the primary remote debugging tool
> Turn release debug logging back on

- cmake/CustomOptions.cmake
- src/MAVLink/CMakeLists.txt
* Related to #12410
* Added back development mavlink dialect
* Bumped mavlink headers to latest
This brings things back to where they were with previous stable
> Mavlink development dialect

- src/AutoPilotPlugins/AutoPilotPlugin.h
- src/FirmwarePlugin/APM/APMMainStatusIndicatorContentItem.qml
- src/FirmwarePlugin/PX4/PX4FlightModeIndicator.qml
- src/FirmwarePlugin/PX4/PX4MainStatusIndicatorContentItem.qml
- src/UI/toolbar/BatteryIndicator.qml
- src/UI/toolbar/FlightModeIndicator.qml
- src/UI/toolbar/MainStatusIndicator.qml
- src/UI/toolbar/RemoteIDIndicatorPage.qml
* Configure buttons only show in toolbar indicators when in advanced mode
* Better wording for GCS comm lost failsafe
* Removed Land Descent Rate from Flight Mode toolbar expanded indicator
> Advanced mode cleanup

- src/FirmwarePlugin/APM/APM-MavCmdInfoFixedWing.json
- src/MissionManager/SimpleMissionItem.cc
Description
-----------
ArduPlane does not support the radius or heading required parameters in the MAV_CMD_NAV_LOITER_TIME command, [as seen in the source code](https://github.com/ArduPilot/ardupilot/blob/1f51cb395e0453b87c2f94a807b848ca2bda9718/libraries/AP_Mission/AP_Mission.cpp#L1129-L1133).
Marked those parameters as removed in APM-MavCmdInfoFixedWing.json and updated the loiter radius visibility to not show for ArduPlane Loiter (time) mission items.
Checklist:
----------
> Fix Loiter (time) mission command for ArduPlane

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
- src/FlightDisplay/GuidedActionsController.qml
Description
-----------
This PR restores the "Change Airspeed" Guided mode action for ArduPilot fixed-wing aircraft, which was inadvertently disabled due to changes in ArduPilot's parameter names. Additionally, it updates the airspeed slider's default value to the current airspeed, for consistency with the "Change Altitude" action.
Added support for updated maximum and minimum airspeed parameter names in ArduPilot. This restores the "Change Airspeed" Guided mode action. Compatibility with the previous parameter names has been maintained.
Made the default value of the airspeed slider in the "Change Airspeed" Guided mode action match the current airspeed, to match the behavior of the "Change Altitude" action.
Checklist:
----------
By submitting this pull request, I confirm that you can use, …
> Fix "Change Airspeed" guided action

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/Vehicle/Vehicle.cc
Description
-----------
Requested MAVLINK_MSG_ID_EXTENDED_SYS_STATE messages from ArduPilot, as it does not send them unless explicitly requested. These messages are necessary to enable the Land Abort action, as they tell QGC when the aircraft is performing its landing sequence.
In addition to this, MAV_CMD_SET_MESSAGE_INTERVAL has been allowed to be sent multiple times before an acknowledgment is received, as it is necessary for this and possibly other use cases of the command.
Checklist:
----------
> Request MAVLINK_MSG_ID_EXTENDED_SYS_STATE in APM

- .github/workflows/macos_release.yml
Given it only fails after the first build it might have something to do with the caching, so let's just try to remove it for now.
> [v4.4] remove CI cache for macOS

- src/MissionManager/MissionController.cc
I noticed while debugging that if I put a print statement in TakeoffMissionItem's destructor it wouldn't be called when I downloaded a new mission from the vehicle. Its because there was a memory leak and the unused TakeoffMissionItem was never deleted. This PR fixes that memory leak. 
> Fix memory leak which happens when loading a new plan

- src/MissionManager/SimpleMissionItem.cc
Replacement for #12584. Repro steps there. Mission recalc routines were incorrectly causing the dirty bit on one of the visual items to change. Hence the whole plan was marked dirty.
> Plan: Fix dirty signal handling

- src/ADSB/ADSB.h
- src/ADSB/ADSBTCPLink.cc
- src/ADSB/ADSBVehicle.cc
- src/ADSB/ADSBVehicle.h
- src/ADSB/ADSBVehicleManager.cc
- src/ADSB/ADSBVehicleManager.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- test/ADSB/ADSBTest.cc
Related to  #12060
Handles remaining data from mavlink_adsb_vehicle_t
> ADSB: Handle Missing Data

- src/Comms/AirLink/AirLinkLink.cc
- src/Comms/AirLink/AirLinkLink.h
- src/Comms/AirLink/AirLinkManager.cc
- src/Comms/UDPLink.h
Updates AIRLink following the UDPLink Changes.
> Comms: Update AIRLink Threading

- src/MissionManager/PlanMasterController.cc
- src/MissionManager/PlanMasterController.h
This `PlanMasterController.dirtyChanged(val)` signal was being emmitted at times when no change in `PlanMasterController.dirty()` actually occured. In a profiling test I did, two thirds of the time the signal was emitted the property whose value was signalled to have changed did not actually have a change. 
For operators this means more resources are taken on their device. For myself as a programmer, the issue caused pain because I was debugging by following signal trails and I wasted some time following false signals.
Also, the parameter value of the dependency signals was inappropriately being passed as the parameter of the emitted signal. ex. if `MissionController::dirtyChanged(false)` was called that would cause `PlanMasterController::dirtyChanged(false)` to be emitted, even though …
> Emit dirtyChanged only if change has occurred

- .github/workflows/macos_release.yml
Description
-----------
- Adding macOS Arch arm64 to the actions 
- Gstreamer version update 
Checklist:
----------
Related Issue
-----------
Fixes: https://github.com/mavlink/qgroundcontrol/issues/12599 and https://github.com/mavlink/qgroundcontrol/issues/12597
cc: @HTRamsey @DonLakeFlyer @julianoes
> macOS CI corrections

- .github/workflows/android_release.yml
"android-35-ext15" was just added and it broke Android CI. Instead of adding a new uninstall command for "android-35-ext15" I made a command which uninstalls anything following the pattern android-* (except for android-33)
> Android CI fix: Prevent future android SDK releases from messing up CI

- src/Joystick/CMakeLists.txt
- src/Joystick/JoystickSDL.cc
Allows adding a custom joystick mapping or overriding an existing one via env variable
Closes #9884
Closes #12626
> Joystick: Allow SDL Mapping from Environment

- docs/en/qgc-user-guide/settings_view/general.md
- src/Settings/Video.SettingsGroup.json
- src/Settings/VideoSettings.cc
- src/Settings/VideoSettings.h
- src/UI/preferences/VideoSettings.qml
- src/VideoManager/VideoManager.cc
- src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc
- src/VideoManager/VideoReceiver/GStreamer/README.md
Replace #10974
Tested on Android & WIndows
> Video: Support Changing UDP URL

- test/MissionManager/SurveyComplexItemTest.cc
Corrected a logic error in SurveyComplexItemTest::_testItemCount() where all nested for loops used the same loop variable (i). This prevented proper generation of the 16 expected test case combinations. Each loop now uses its intended iterator (i, j, k, l).
> Fix incorrect loop variables in _testItemCount test case

- custom-example/qgroundcontrol.qrc
- qgroundcontrol.qrc
- src/API/QGCCorePlugin.cc
- src/API/QGCCorePlugin.h
- src/FlightDisplay/FlyViewBottomRightRowLayout.qml
- src/FlightDisplay/FlyViewTopRightPanel.qml
- src/FlightDisplay/MultiVehicleList.qml
- src/FlightDisplay/TelemetryValuesBar.qml
- src/FlightMap/Widgets/IntegratedAttitudeIndicator.qml
- src/FlightMap/Widgets/IntegratedCompassAttitude.qml
- src/QmlControls/FactValueGrid.cc
- src/QmlControls/FactValueGrid.h
- src/QmlControls/HorizontalFactValueGrid.cc
- src/QmlControls/HorizontalFactValueGrid.h
- src/QmlControls/InstrumentValueData.cc
- src/QmlControls/InstrumentValueData.h
- src/QmlControls/QGroundControl/FlightMap/qmldir
Operators are now given a customizable Telemetry data table in each vehicle card!
This was a request from a flight test team that was using QGC to fly multiple prototype autonomous fixed wing vehicles. When flying the vehicles, altitude/air-speed needs to be monitored for all vehicles at once to avoid stalls/crashes.
I used PX4's mutli vehicle sim while developing/testing
```
./Tools/simulation/gazebo-classic/sitl_multiple_run.sh -m plane -n 2
```
> Vehicle Card Telem Data

- src/Utilities/CMakeLists.txt
- src/Utilities/SignalHandler.cc
- src/Utilities/SignalHandler.h
- src/main.cc
The original handler wasn't safe to use with Qt
Using ctrl-c now closes cleanly
> Linux: Add Signal Handler

- .github/workflows/linux.yml
- tools/setup/install-dependencies-debian.sh
This should be handled by the dependencies script anyways
> CI: Don't add Test Repo for GCC

- cmake/find-modules/FindGStreamer.cmake
- src/VideoManager/VideoReceiver/GStreamer/CMakeLists.txt
- src/VideoManager/VideoReceiver/GStreamer/GStreamerHelpers.cc
- src/VideoManager/VideoReceiver/GStreamer/GStreamerHelpers.h
- src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc
Fixes #10402
Use GStreamer RTSP functions to verify RTSP URI, which allows other schemes like rtspt.
This means we will now have to directly link to GStreamer RTSP, which should be fine since it was included automatically with the rtsp plugin anyway.
> GStreamer: Allow Other RTSP Schemes

- src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/CMakeLists.txt
Installs all of the gstreamer plugins rather than just the ones listed for static linking
> Linux: Install all GStreamer Plugins into AppImage

- src/UI/toolbar/MainStatusIndicator.qml
Message icon is in the wrong place when vtol status is displayed. Should be next to main status text:
Touch areas are much too small. Super hard to touch with finger. Also message icon is separate touch area:
Fixed message icon positioning:
Fixed touch areas to be full toolbar height:
> Fix main status indicator mouse areas

- .github/workflows/android-linux-qt6.6.3.yml
- .github/workflows/android-linux.yml
- .github/workflows/android-macos.yml
- .github/workflows/android-windows.yml
This silences the annoying warnings from the legacy toolchain. Remove later when using a higher NDK version
Also add translations to triggers list
> CI: Silence Android Toolchain CMake Warnings

- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Add motor interlock aux function to joystick button options
Description
This PR adds the motor interlock feature of Ardupilot to the options for button actions in the joystick. It uses the mavlink aux function command ardupilot to enable and disable the motor interlock.
Test Steps
-----------
Start an helicopter simulation in ardupilot. Add motor interlock enable as an action on one button and motor interlock disable as an action on a separate button.  Press the motor interlock disable button to allow arming. Arm the heli and use the motor interlock enable button to spool up the rotor. 
Checklist:
----------
Related Issue
-----------
None 
> Add motor interlock aux function to joystick button options

- src/FirmwarePlugin/APM/APM.h
- src/FirmwarePlugin/APM/CMakeLists.txt
- src/Joystick/Joystick.cc
- src/Joystick/Joystick.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Follow up to #12721 that ensures usage of AUX_FUNCTION only w/ APM.
The separation of this kind of stuff really needs to be improved at some point
> Vehicle: Only Allow Motor Interlock Aux Function w/ APM

- src/MissionManager/MissionController.cc
Fix order of parameters in call to _addTimeDistance when using a RTH waypoint
Description
-----------
This corrects the order of parameters when calling MissionController::_addTimeDistance 
Note that the last 3 parameters are `time`, `distance` and `sequenceNumber` (in that order), and they are used correctly everywhere except where corrected by this PR, where previously they had been ordered `distance`, `time` and `sequenceNumber` (note `time` and `distance` were swapped).
This escaped the compiler because both parameters are `double`.
As a result:
* Before, when creating a route that included a Return To Launch waypoint the "Total Mission" "Distance" shown on top was `-.-`.
* For some reason this does not happen when downloading the route from the Drone to QGC.
* After the fix, when …
> Fix order of parameters in call to _addTimeDistance when using a RTL waypoint

- .github/ISSUE_TEMPLATE/bug_report.yml
Description
-----------
Improves the "Bug report" Issue Template by:
- removing a redundant `**(required)**` (already indicated to the user via a red asterisk)
- turning some placeholder attributes into values, so that the user can reuse that text without having to retype it
- making a helpful link immediately clickable by also putting it in the description
Test Steps
-----------
Tested it on our fork by committing the changes to master and creating an issue via that template.
Not sure how this could be tested on the main repo without merging into master.
Checklist:
----------
Related Issue
-----------
None.
> Improve "Bug report" Issue Template

- src/Viewer3D/OsmParserThread.cc
Fixing a bug regarding parsing OSM files for the 3D viewer.
Closes #12749
> Bug fix for the 3D viewer OSM parser

- src/AutoPilotPlugins/PX4/SensorsComponentController.cc
Description
-----------
Without this fix, the output from the level horizon calibration would show `[cal] progress &lt;50&gt;` etc, and the progress bar would not update properly.
The below is from our fork of QGC, I saw the same issue on the official QGC app. 
https://github.com/user-attachments/assets/a6422001-b115-442a-a967-1bc5e61f76ce
Test Steps
-----------
I verified that the issue was resolved by adding the two lines in this PR to our fork of QGC.
https://github.com/user-attachments/assets/a181ec23-482b-466d-a4bc-4924fa186766
Checklist:
----------
Related Issue
-----------
> AutoPilotPlugins: Correctly parse messages coming from level horizon calibration

- src/Camera/VehicleCameraControl.cc
- src/FlightDisplay/FlightDisplayViewVideo.qml
- src/QGCApplication.cc
- src/QmlControls/InstrumentValueData.cc
- src/Settings/VideoSettings.cc
- src/Vehicle/MultiVehicleManager.cc
- src/Vehicle/MultiVehicleManager.h
- src/Vehicle/Vehicle.cc
- src/VideoManager/SubtitleWriter.cc
- src/VideoManager/VideoManager.cc
- src/VideoManager/VideoManager.h
- src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc
- src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.h
- src/VideoManager/VideoReceiver/QtMultimedia/QtMultimediaReceiver.cc
- src/VideoManager/VideoReceiver/QtMultimedia/QtMultimediaReceiver.h
- src/VideoManager/VideoReceiver/QtMultimedia/UVCReceiver.cc
- src/VideoManager/VideoReceiver/QtMultimedia/UVCReceiver.h
- src/VideoManager/VideoReceiver/VideoReceiver.h
Enhanced structure of VideoReceivers and how the VideoManager interacts with them so that it is easier to have multiple simultaneous receivers.
Also includes another fix that was needed after #12634
Following this, each video receiver type needs to be improved/finished and then the implementation in QML needs to be updated.
> VideoManager: Improve Handling of Multiple Receivers

- src/Camera/QGCCameraControl.cc
- src/Camera/QGCCameraControl.h
- src/Camera/QGCCameraIO.cc
> [BACKPORT v4.4] A few Camera discovery fixes

- src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc
I had an misconstructred RTSP URI which causes makeSource to fail, the recorderQueue wasn't be freed and causing a memory leak resulting in a crash
> gst: deallocate recorderQueue in gst pipeline to fix memory leak

- src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc
Currently when pipeline construction fails in `makeSource` the worker thread immediately retries. This causes the retries to occur extremely rapidly, like thousands of times per second. 
I spent a bunch of time trying to pass a delay_ms variable into the thread dispatcher from `_initVideoReceiver`, which is the thing that kicks everything off from the `onStartComplete` signal, but it ended up being way too complicated. This implementation just sleeps for a second after failure before emitting the signal, which is much simpler and accomplishes the goal.
> gz: rate limit pipeline retries on failure

- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
PX4 actually implements this in radians, and so does MAVSDK.
My hunch is that this was not fully tested for PX4.
Further discussion in:
https://github.com/mavlink/mavlink/pull/2271
> PX4FirmwarePlugin: change yaw unit for DO_REPOSITION

- src/FirmwarePlugin/APM/APMFirmwarePlugin.cc
- src/FirmwarePlugin/APM/APMFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.cc
- src/FirmwarePlugin/FirmwarePlugin.h
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
- src/FlightDisplay/GuidedActionsController.qml
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Description
-----------
Implemented a fallback for the Takeoff action for vehicles that can take off but lack guided takeoff support. The fallback action switches to the vehicle's takeoff mode and then arms it, similar to how the Start Mission action works.
Key changes:
- Introduced a new GuidedTakeoffCapability flag to distinguish between takeoff capability and guided takeoff support.
- Added startTakeoff method in FirmwarePlugin to switch to takeoff mode and arm the vehicle, similar to startMission.
- Defined the takeoff flight mode for ArduPlane.
- Updated GuidedActionsController to use the original guided takeoff action or this fallback, as appropriate.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Add fallback takeoff support to the Takeoff action

- docs/en/qgc-user-guide/getting_started/download_and_install.md
Changed minimum Ubuntu version to 22.04 in installation documentation page
Description
-----------
QGC not compatible with Ubuntu 20.04 anymore
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update download_and_install.md -> Min Ubuntu Version: 22.04

- cmake/find-modules/FindGStreamer.cmake
Additional check for gstreamer path 
On Arch-based distros x86_64-linux-gnu exists but does not contain gstreamer-1.0 dir 
Description
Added check in cmake/find-modules/FindGStreamer.cmake
> additional gstreamer path check, fix build on arch-based distros

- src/VideoManager/VideoManager.cc
Fix #12817
VideoReceiver uri is initially null, but the equality check is still true, so the changed signal wouldn't get emitted the first time
> VideoManager: Fix Initial URI Change Signal

- src/Comms/SerialLink.cc
- src/Utilities/QGCLogging.cc
This was due to trying to close composite USBs which gets stuck in qt_safe_close for a little bit, so we need to wait for the worker to finish closing the port before quitting the thread
BlockingQueuedConnection should probably be used for the other LinkInterface destructors too
> SerialLink: Fix Crash on Cleanup of Composite USBs

- .github/workflows/android-linux-qt6.6.3.yml
- CMakeLists.txt
- cmake/CustomOptions.cmake
- src/Joystick/CMakeLists.txt
- src/Joystick/JoystickSDL.cc
* This is in prep for 5.0 release. Including default support for ranges of Qt versions just causes support nightmares
* Also adds specific support for Herelink option workaround to build against 6.6.3
* Fixes problem with gamecontrollerdb qt_add_resources causing link failures on 6.6.3
> Qt version lockdown to 6.8.3

- src/MissionManager/CameraSection.cc
- src/MissionManager/CameraSection.h
For a big survey mission it is nice if the images have sequence numbers. Also, this can prevent double captures when a command is re-transmitted somwhere in the chain.
> MissionManager: increment take photo sequence

- src/MissionManager/MissionController.cc
Set altitude mode to mixed when downloading from vehicle too.
Otherwise mission altitude mode will be set to relative even if all the waypoints are a different frame, and this will bring us 2 issues:
- Individual waypoints frame will be shown as relative, even if they are not, misleading the operator.
- We won't be able to change waypoints altitude mode at all, because in order to do this in mission settings item we need to not have any item in the mission, so we are in a deadlock.
We could always check item by item to first evaluate if we might have all of them with the same frame, and thus apply that frame as global frame in mission controller, but that is probably overkill and when loading from mission files we are taking the same approach anyway, unless having the json …
> MissionController: Fix wrong altitude frame representation when downloading from vehicle for non relative altitude frame

- src/Comms/LinkManager.cc
- src/Comms/LinkManager.h
- src/Comms/SerialLink.cc
- src/FlightDisplay/FlyViewMap.qml
- src/QmlControls/FactValueGrid.cc
* Fix #12858
* Fixes crash on usb cable disconnect
* Fixes main window disappearing on active vehicle going away
* Fixes link errors showing message in title and title in message area
* Stops popping link error dialog on usb cable pull
* Replacement for #12860
> Fix crash on usb disconnect, fix hiding of main window

- src/FirmwarePlugin/APM/APMSensorIdDecoder.qml
`busType` is a string, so the existing logic has never worked. This bug resulted in the compass being reported as
```
HMC5883_OLD(UAVCAN0)
```
With the fixed logic it is now
```
UAVCAN(UAVCAN0)
```
The DroneCAN MagneticFieldStrength2 message only has a `uint8 id` which is used for sensor instance reporting. There is no mechanism to report device type of the magnetometer sensor (eg ii2smdc, hmc5883, etc)
> APM: fix uavcan compass name

- src/FlightMap/FlightMap.qml
Discovered while testing #12236
> Map: Fix various zoomLevel problems

- src/PlanView/MissionSettingsEditor.qml
- src/PlanView/PlanView.qml
- src/QmlControls/ToolStripHoverButton.qml
* Related to #12657
* Plan now always allows you at a minimum to switch to Mixed Modes altitude even if you have alraedy added items to a plan
* Fixed toolstrip button showing hover highlight when disabled
* Fixed initial display of File Open when going to Plan for first time
> Mixed modes

- .github/workflows/android-linux-qt6.6.3.yml
- .github/workflows/android-linux.yml
- .github/workflows/android-macos.yml
- .github/workflows/android-windows.yml
Closes #12819
Closes #12898
We can always sign if the github secrets are accessible
> CI: Always Sign Android if Possible

- CMakeLists.txt
- cmake/CustomOptions.cmake
> CMake: Fix Overriding of CPM_SOURCE_CACHE

- src/QGCApplication.h
- src/QmlControls/QGroundControlQmlGlobal.cc
- src/QmlControls/QGroundControlQmlGlobal.h
- src/UI/preferences/GeneralSettings.qml
Fixes "Clear all settings on next start" option which wouldn't disable after being enabled
> QML: Fix Delete All Settings Option

- src/Comms/LinkManager.cc
- src/Comms/LinkManager.h
- src/Comms/SerialLink.cc
* Fix for #12893
* These changes should bring the basically code back to how 4.4 worked
* The secondary ports from a composite device are not made available to autoconnect
* The list of ports available to manual connections is the full un-filtered list. This differs from 4.4 which filtered the manual connect list as well.
* Fixed SerialLink to not pop PermissionError errors on autoconnect links
So far I've tested Mac and Windows for correct behavior on:
* Eating PermissionError's
* USB cable pull and reconnect. Note: On Windows, same as before, usb cable pull doesn't automatically close link,. You need to disconnect manually.
* Autoconnect to a composite device like Cube Orange running Ardupilot works
This can still cause failures on autoconnect to composite devices line Cube Orange. But …
> Autoconnect: Filter out secondary composite ports from autoconnect

- .github/workflows/android-windows.yml
This should have been more obvious at first
> CI: Fix Windows Android Signing Attempt 2

- .github/workflows/android-windows.yml
I'm not sure why this wont work for CI right now, will just disable for now since it works locally
> CI: Disable Android Windows Signing

- src/Terrain/TerrainQuery.cc
- src/Terrain/TerrainQuery.h
Description
-----------
This fixes a use-after-free crash caused by improper raw pointer usage in TerrainQuery.
Key changes:
- Replace raw TerrainAtCoordinateQuery pointers with QPointer to automatically track object lifetime.
- Remove manual destroyed signal handling and related cleanup code.
In addition to this, some no-op logic has been removed.
Test Steps
-----------
Connect a real APM vehicle with a mission of around 300 waypoints. The application will often crash after loading the mission and drawing the plan.
Checklist:
----------
> Terrain: Fix TerrainQuery crash

- custom-example/src/CustomPlugin.cc
Description
-----------
Updated the example implementation of the CustomPlugin to include the QtCore/QApplicationStatic header only for Qt versions over 6.8.0, where it was introduced.
Checklist:
----------
> CustomPlugin: Fix QApplicationStatic for Qt 6.6.3

- src/QmlControls/MissionItemEditor.qml
- src/QmlControls/MissionItemMapVisual.qml
- src/QmlControls/SimpleItemMapVisual.qml
Description
-----------
Replaced manual QML loading and object lifetime management in SimpleItemMapVisual and MissionItemMapVisual with Loaders. This substantially improves performance, as Loader is optimized for dynamic component loading, and avoids JavaScript on the object construction. It's also a more canonical and therefore maintainable approach.
Set the asynchronous property of MissionItemEditor's Loader to true, to prevent blocking the main GUI thread when expanding mission items.
Key changes:
- Removed manual lifecycle and error handling code for component creation.
- Introduced Loaders to dynamically load map visuals asynchronously.
- Set properties and reconnected signal bindings via Loader.setSource and Loader.onLoaded, respectively, avoiding slow JavaScript logic.
Profiling …
> QML: Various easy optimizations

- CMakeLists.txt
- src/CMakeLists.txt
- src/FactSystem/CMakeLists.txt
- src/QmlControls/QGroundControl/FactSystem/qmldir
- src/QmlControls/QGroundControl/Vehicle/qmldir
- src/Vehicle/CMakeLists.txt
Resolves the warning about a missing QGroundControl module
> CMake: Add QGroundControl QML Module

- src/Camera/QGCCameraIO.cc
- src/Camera/VehicleCameraControl.cc
* Previous code was failing with new 6.8. Switch to same code which is used in ParameterManager.
* Fix #12953 (hopefully!)
> Fix parameter name conversion from mavlink

- src/FlightMap/MapItems/QGCMapPolygonVisuals.qml
- src/QmlControls/QGCMapPolygon.cc
- src/QmlControls/QGCMapPolygon.h
- src/QmlControls/QGCMapPolyline.cc
- src/QmlControls/QGCMapPolyline.h
Description
-----------
I've noticed that when dragging the vertices of long polylines or large polygons, the UI would often freeze up completely (to the point of "program is not responding") after a few seconds of lag, and only sometimes recover from that state after tens of seconds.
Managed to fix it by debouncing "pathChanged" emissions to occour on every event loop, instead of every frame, which prevents dragging of such polylines/polygons from clogging up the UI code with too many path emissions.
Test Steps
-----------
Try creating Corridor Scan items with many polyline vertices or Survey scans (both basic and circular) covering a large area. Dragging of any polyline/polygon vertex won't cause the UI to freeze up completely, it will at worst lag a bit but always recover when …
> Plan View: Fix polyline/polygon vertex dragging freezing the UI

- src/QmlControls/MainWindowSavedState.qml
- src/UI/MainWindow.qml
* Trying to work around problem on android where main window size is too large and off screen
* Previous code was pretty convoluted and distributed all over the place. New code does all main window size stuff in MainWindowSavedState
* Hoping the change to set minWidth/Height on mobile to 0 (which is the normal default) will fix the problem
Related to #12956
> Reworked MainWindow sizing code

- src/AutoPilotPlugins/PX4/ActuatorComponent.qml
- src/Vehicle/Actuators/Actuators.cc
- src/Vehicle/Actuators/Actuators.h
- src/Vehicle/Actuators/GeometryImage.cc
- src/Vehicle/Actuators/GeometryImage.h
* For some reason even though we specify a sourceSize.width/height for the image the requestSize comes through at twice that size. Which in turns throws off the click determination. Seems to be a new thing with Qt 6.8.2. Previous 4.4 Stable requested size would come through as sourceSize.
* Fix #13018
> Fix motor assignment motor click determination

- src/Comms/SerialLink.cc
Closes #12992. Would like to add custom entry box too.
> Comms: Add Default List of Serial Baud Rates

- src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc
This would cause huge leaks if the stream was continuously restarting due to video timeout
> Stable: Fix leak of static pad on shutdown

- src/AutoPilotPlugins/PX4/BatteryParams.qml
- src/AutoPilotPlugins/PX4/PowerComponent.qml
- src/AutoPilotPlugins/PX4/PowerComponentSummary.qml
* Removed support for non-indexed battery params
* Handle all the crazy cases of battery parameter available or not depending on `BAT#_SOURCE` setting
* Fix #13065
> PX4 - Power Setup: Handle all cases of battery parameters available/missing

- src/MissionManager/FixedWingLandingComplexItem.cc
- src/MissionManager/LandingComplexItem.cc
- src/MissionManager/LandingComplexItem.h
- src/MissionManager/VTOLLandingComplexItem.cc
- src/QmlControls/FWLandingPatternEditor.qml
- src/QmlControls/FWLandingPatternMapVisual.qml
- src/QmlControls/VTOLLandingPatternMapVisual.qml
- test/MissionManager/LandingComplexItemTest.cc
- test/MissionManager/LandingComplexItemTest.h
Description
-----------
Updated the LandingComplexItem recalculation logic to properly handle waypoint approach items, fixing several issues with heading calculations and when loading plans, such as the loiter radius being taken into account despite the "Use loiter to altitude" option being disabled. Refactored the relevant areas to unify the naming and logic between waypoint and loiter-based approaches.
This replaces previous GUI-level workarounds (https://github.com/mavlink/qgroundcontrol/commit/ddd97adb7c4485a78faca0e4d4313c58e88dd366, https://github.com/mavlink/qgroundcontrol/commit/e0f6a0ad46a5f6f6e665cdac33fdcaa7bbfef2d7) that partially fixed these heading calculation problems by manipulating the loiter radius. This commit addresses the root cause instead, so it also fixes the …
>  MissionManager: Fix landing approach item handling (Stable v5.0)

- src/MissionManager/FixedWingLandingComplexItem.cc
- src/MissionManager/LandingComplexItem.cc
- src/MissionManager/LandingComplexItem.h
- src/MissionManager/VTOLLandingComplexItem.cc
- src/QmlControls/FWLandingPatternEditor.qml
- src/QmlControls/FWLandingPatternMapVisual.qml
- src/QmlControls/VTOLLandingPatternMapVisual.qml
- test/MissionManager/LandingComplexItemTest.cc
- test/MissionManager/LandingComplexItemTest.h
Description
-----------
Updated the LandingComplexItem recalculation logic to properly handle waypoint approach items, fixing several issues with heading calculations and when loading plans, such as the loiter radius being taken into account despite the "Use loiter to altitude" option being disabled. Refactored the relevant areas to unify the naming and logic between waypoint and loiter-based approaches.
This replaces previous GUI-level workarounds (https://github.com/mavlink/qgroundcontrol/commit/ddd97adb7c4485a78faca0e4d4313c58e88dd366, https://github.com/mavlink/qgroundcontrol/commit/e0f6a0ad46a5f6f6e665cdac33fdcaa7bbfef2d7) that partially fixed these heading calculation problems by manipulating the loiter radius. This commit addresses the root cause instead, so it also fixes the …
> MissionManager: Fix landing approach item handling

- src/QmlControls/MAVLinkChart.qml
* Hack fix for #13077
* In reality this code is majorly screwed up with respect to vehicle coming/going. It leaves references to deleted QGCMavlinkSystem objects. Will have to deal with this fully later.
> Fix Mavlink Inspector crash

- src/Vehicle/FactGroups/VehicleFact.json
- src/Vehicle/FactGroups/VehicleFactGroup.cc
- src/Vehicle/FactGroups/VehicleFactGroup.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
Description
-----------
Added headingFromHome and headingFromGCS Facts, useful to locate vehicles from the operator's perspective.
Checklist:
----------
> Vehicle: Add "heading from" Facts

- src/Comms/MockLink/MockLink.cc
- src/Comms/MockLink/MockLink.h
- src/FirmwarePlugin/FirmwarePlugin.cc
- src/Vehicle/StandardModes.cc
* This supports request for standard modes. It will also on a delay report new modes available which should trigger a new mode query and ui update.
* Related to #13095
> Add StandardModes support to MockLink

- CMakeLists.txt
- cmake/Helpers.cmake
Add a simpler way to set a file alias to its base file name for convenience
> CMake: Add QT_RESOURCE_ALIAS Helper

- src/FlightMap/MapItems/MapLineArrow.qml
- src/FlightMap/MapItems/MissionLineView.qml
Description
-----------
This fixes a bug where extremely long legs in flight plans were drawn as straight lines on the map, instead of following the great circle path.
Key changes:
- Break down mission legs longer than 50km into smaller segments that follow the great circle path based on accurate geodesic calculations.
- Update leg arrow heading calculation to account for changing bearing along great circle paths.
Before/after
----------
Checklist:
----------
> FlightMap: Fix drawing of very long mission lines (Stable v5.0)

- src/FlightMap/MapItems/MapLineArrow.qml
- src/FlightMap/MapItems/MissionLineView.qml
Description
-----------
This fixes a bug where extremely long legs in flight plans were drawn as straight lines on the map, instead of following the great circle path.
Key changes:
- Break down mission legs longer than 50km into smaller segments that follow the great circle path based on accurate geodesic calculations.
- Update leg arrow heading calculation to account for changing bearing along great circle paths.
Before/after
----------
Checklist:
----------
> FlightMap: Fix drawing of very long mission lines

- src/Camera/QGCCameraManager.cc
- src/VideoManager/VideoManager.cc
Title
Fix: Improve auto stream handling for MAVLink VIDEO_STREAM_INFORMATION (#12373) 
Description
This PR fixes [QGC issue #12373](https://github.com/mavlink/qgroundcontrol/issues/12373), where QGroundControl daily builds failed to automatically load and display the video stream based on the incoming VIDEO_STREAM_INFORMATION MAVLink message, despite receiving a correct URI. The issue manifested as GStreamer-related errors and video stream failures when using automatic stream selection (via MAVLink), while manual URI entry worked fine.
- Ensure stream info is updated for all video receivers, including thermal streams.
- Update auto-stream configuration logic for reliability when changing video sources or camera settings.
- Refactored stream reconfiguration logic so that UI and backend …
> Fix: Improve auto stream handling

- src/Vehicle/FactGroups/GPSFact.json
- src/Vehicle/FactGroups/VehicleGPS2FactGroup.cc
- src/Vehicle/FactGroups/VehicleGPSFactGroup.cc
- src/Vehicle/FactGroups/VehicleGPSFactGroup.h
- translations/qgc-json.ts
Add yaw in GPS fact and displayed it under GPS Status menu
Description
-----------
When using GPS heading along Gyroscope, QGrondControl will only show gyroscope compass, user can't know easily if heading is working correctly or what is his value.
I have added yaw to gps fact and make it displayed under Vehicle GPS Status menu.
The only way before was to open MAVLink inspector and check the value of yaw.
0 will be displayed if GPS do not provide heading and N/A when heading is not available.
Test Steps
-----------
Use GPS heading, 
Checklist:
----------
Related Issue
-----------
> Add yaw in GPS fact

- src/FlightMap/FlightMap.qml
* This allows you to go past where tiles exists but mirrors how 4.4 works. It allows you to go as far as possible zoomed in.
* Fix #13122
> Allow manual zoom level adjust to increase unbounded

- src/QmlControls/QGCTextField.qml
This mirrors how it worked in 4.4
> Force android soft keyboard to close with Done instead of Next

- test/FactSystem/ParameterManagerTest.cc
- test/FactSystem/ParameterManagerTest.h
This was causing the test to run forever
> Tests: Temporarily Disable Broken Test

- src/Camera/QGCCameraManager.cc
- src/Camera/QGCCameraManager.h
- src/Camera/VehicleCameraControl.cc
- src/Camera/VehicleCameraControl.h
- src/Vehicle/Vehicle.cc
This is an attempt to fix some of the corner cases trying to discover cameras, namely:
- Implement missing retries for CAMERA_INFORMATION, us old specific commands and REQUEST_MESSAGE.
- Try to simplify CameraControl::_initWhenReady a bit.
- Fix _requestStreamInfo() and _requestStreamStatus() using wrong retry variable.
- Add a few missing timers.
I haven't been able to properly test each and every retry mechanism used but overall this consistently initializes correctly for my case when it previously does not.
> Camera: try to make discovery more robust

- src/Utilities/QGCLogging.cc
- src/Utilities/QGCLogging.h
- src/Utilities/QGCLoggingCategory.cc
Adds a custom filter function for the logging categories which can allow easier/finer control of the enabled categories.
Also could collect the registered categories here and remove the custom QGCLoggingCategory class.
Fixes a debug output issue too.
> Utilities: Add Logging Filter

- cmake/CustomOptions.cmake
- src/Joystick/CMakeLists.txt
- src/Joystick/JoystickManager.cc
- src/Joystick/JoystickManager.h
- src/Joystick/JoystickSDL.cc
- src/Joystick/JoystickSDL.h
This may improve joystick compatibility & functionality
Also update thread safety in JoystickManager and cleanup vehicle joystick handling
> Joystick: Update to SDL3

- tools/setup/install-dependencies-debian.sh
Apt doesn't provide a new enough one on Ubuntu 22.04
> Linux: Get Latest CMake & Ninja

- src/QmlControls/SettingsGroupLayout.qml
Description
-----------
Before:
After:
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> QML SettingsGroupLayout: Fix dividers visibility

- src/FirmwarePlugin/APM/APMParameterMetaData.cc
- src/FirmwarePlugin/APM/APMParameterMetaData.h
- src/Utilities/QGCLogging.cc
Up to ArduPilot v4.5, Bitmasks came in the form 
`<field name="Bitmask">0:SwitchPos1, 1:SwitchPos2, 2:SwitchPos3, 3:SwitchPos4, 4:SwitchPos5, 5:SwitchPos6</field>`
now they look like
```
<bitmask>
<bit code="0">SwitchPos1</bit>
<bit code="1">SwitchPos2</bit>
<bit code="2">SwitchPos3</bit>
<bit code="3">SwitchPos4</bit>
<bit code="4">SwitchPos5</bit>
<bit code="5">SwitchPos6</bit>
</bitmask>
```
Also remove unused function
> APM: Support Parameter MetaData bitmask Element

- src/QmlControls/GPSIndicatorPage.qml
- src/Settings/RTKSettings.cc
- src/Settings/RTKSettings.h
Description
-----------
Refactor BaseModeDefinition to QObject with QML_UNCREATABLE, using auto type registration instead of manual.
Checklist:
----------
Related Issue
-----------
> Fix QML type registration for GPS RTK

- src/AnalyzeView/AnalyzeView.qml
- src/QmlControls/AppSettings.qml
- src/UI/MainWindow.qml
- src/Vehicle/VehicleSetup/SetupView.qml
Block click event leakage to underlying map
These changes fix 2 bugs:
1. Described here: (https://github.com/mavlink/qgroundcontrol/issues/13277)
2. The same for toolDrawer
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Closes #13277
> Fix Qml signal leaking to underlying map

- src/FlightMap/Widgets/PhotoVideoControl.qml
Description
-----------
The inner circle in the PhotoVideoControl widget was not always perfectly centered due to a bug in Qt's anchors.centerIn property (QTBUG-95224) which causes it to return integer positions instead of subpixel values.
Implemented a workaround by manually calculating the center position, ensuring exact centering regardless of parent and child dimensions and DPI scaling.
This fix should be reverted once QGC moves to Qt 6.8.1 or higher, where the underlying Qt bug has been resolved.
Related Qt bug: https://bugreports.qt.io/browse/QTBUG-95224
Qt fix commit: https://github.com/qt/qtdeclarative/commit/fd23a222efe189607eebd5c6782ca73eafa7080c
Checklist:
----------
Related Issue
-----------
#10046
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Fix centering of inner circle in PhotoVideoControl

- .github/actions/upload/action.yml
It happens to often to meet CloudFront rules
> We can't invalidate CloudFront cache for daily builds

- src/Joystick/JoystickSDL.cc
SDL_GAMEPAD_BUTTON_COUNT is an enum that's always available
> Joystick: Button Count Fix

- src/QmlControls/PlanViewToolBar.qml
In the original implementation, when there are validation errors, clicking the "Exit Plan" button to switch to the Flyview view results in being unable to switch to other views within Flyview, making it appear as though the button is unresponsive or the application has malfunctioned.
> fix: prevent plan view exit when validation errors exist

- custom-example/src/FirmwarePlugin/CustomFirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.cc
- src/FirmwarePlugin/PX4/PX4FirmwarePlugin.h
- src/Vehicle/StandardModes.cc
* Fix #13325
* This is just a quick fix. In reality the whole bag of code surrounding standard modes and flight modes needs to be re-written. I know what I want to do. I'll deal with that in master.
@dakejahl Can you review and test? I did minimal testing myself but ran out of time till tomorrow. I'll poke at it some more then. I think there is still ArduPilot side problems as well.
> PX4: Fix bugs with flight mode names changing from Standard Modes

- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
- src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.cc
- src/FirmwarePlugin/APM/ArduRoverFirmwarePlugin.h
- src/FirmwarePlugin/FirmwarePlugin.cc
Fix #13224 
@rubenp02 Can you verify this works for you?
> ArduPilot: Remove hardcoded flight mode names

- src/FlightDisplay/FlyViewTopRightColumnLayout.qml
- src/Vehicle/MultiVehicleManager.cc
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
- test/Vehicle/RequestMessageTest.cc
* Replacement for #13302 
* Remove Vehicle::prepareDelete for camera manager. Should not be needed with appropriate Loader usage on PhotoVideoControl
* Move deleteGimbalController/deleteCameraManager to private methods with friend class access for RequestMessageTest
> Clean up handling of vehicle and camera manager coming/going

- .github/workflows/macos.yml
- cmake/install/Install.cmake
- cmake/install/SignMacBundle.cmake
- docs/en/qgc-dev-guide/getting_started/index.md
Jumping through the Mac security hoops to use QGC is no longer needed
> Sign, Notarize and Staple Mac app bundle

- src/QtLocationPlugin/Providers/GenericMapProvider.h
Description
-----------
Just an URL update, as-is, the Norwegian maps are no longer working.
This should fix it, but I am unable to verify due to https://github.com/mavlink/qgroundcontrol/issues/13049
The same fix works for MAVproxy - so it should work fine. it's broken now, so it is not going to be worse. :) 
> Updated Norwegian map source.

- src/Gimbal/Gimbal.cc
- src/Gimbal/Gimbal.h
- src/Gimbal/GimbalController.cc
- src/Gimbal/GimbalController.h
- src/UI/toolbar/GimbalIndicator.qml
* Yaw follow and Retract only displayed if capability flags indicate support
* Some cleanup in Gimbal and GimbalController to improve readability
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Gimbal Indicator: Close popup after selecting gimbal command, Only show gimbal command if supported

- src/MissionManager/CorridorScanComplexItem.cc
- src/MissionManager/SurveyComplexItem.cc
- src/MissionManager/TransectStyleComplexItem.h
> Plan: Lower minimum transect spacing to 0.3 meters

- src/Camera/QGCCameraManager.cc
- src/Camera/QGCCameraManager.h
- src/Vehicle/Vehicle.cc
- src/Vehicle/Vehicle.h
* Remove start/stop capability which was added for testing but unused
* Start/Stop capability was causing cameras to never load since start was never called
* Fixed bad QObject::Connect call in _handleCameraInfoRetry which was throwing an assert due to Qt:: UniqueConnection not allowing lambda calls. Unique connection should not be needed given the fact that all signals a disconnected a few lines above.
> Camera Manager fixes

- src/Joystick/JoystickSDL.cc
Should return false if not pressed
Think this actually conflicts with the getHat stuff since the indices are (maybe?) different for the dpad of gamepad & hat of joystick?
> Joystick: Gamepad Button Fix

- custom-example/src/CustomPlugin.h
- src/API/QGCOptions.h
- src/AutoPilotPlugins/PX4/SensorsSetup.qml
I'm not sure if this warning is relevant anymore. It's very common to connect to QGC over the network with mavlink-router running onboard a companion computer. I've never had an issue with calibration over wifi and this warning has caused confusion for some users.
> remove warning about calibration over wifi
